### ISSUE TITLE
Nested lists not show properly

### ISSUE THREAD

**Issue by Fredrik5** [marktext/marktext#1002]
### Nested lists not show properly

Hey, i have trouble with nested lists and its view in readme.md on bitbucket.

In marktext i have

* Bullet list
  * Nested bullet
    * Sub-nested bullet etc
* Bullet list item 2

But readme.md online versions show it as
* Bullet list
* Nested bullet
  * Sub-nested bullet etc
* Bullet list item 2

Any idea how to format text properly in marktext?

**Comment by Jocs** [comment]
@Fredrik5 Can you attach a test markdown file here?

**Comment by Fredrik5** [comment]
@Jocs  sure

[README.zip](https://github.com/marktext/marktext/files/3138113/README.zip)

**Comment by Jocs** [comment]
>But readme.md online versions show it as

I test your markdown file on my computer, it seems look correctly? you can paste to the comment it should be a two level nested list.

**Comment by Fredrik5** [comment]
It looks corectly on my computer as well, but on  bitbucket it shows like this:

![readme](https://user-images.githubusercontent.com/50204564/57078217-21682380-6cee-11e9-8f44-9eb144b13859.JPG)

**Comment by Fredrik5** [comment]
And in marktext on my computer shows it as:
![marktext](https://user-images.githubusercontent.com/50204564/57078311-507e9500-6cee-11e9-8710-762c4909ecae.jpg)

**Comment by fxha** [comment]
Please see #887, you have to set `"listIndentation": "dfm"` in settings.
