### ISSUE TITLE
Opening files from file manager opens a new instance even with openFilesInNewWindow set to false

### ISSUE THREAD

**Issue by ToughGuyKunio** [marktext/marktext#1004]
### Description

Opening a file from a file manager like Nautilus, with `openFilesInNewWindow`set to `false`, should open the file in a tab. In current version it opens a new instance.

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. Set `openFilesInNewWindow` to `false`
2. Open file manager
3. Click on .md file

**Expected behavior:**

File opens in tab. (New tab if it's not already opened)

**Actual behavior:**

File opens in new instance.

**Link to an example: [optional]**

### Versions

- Mark Text: 0.14.0
- Operating system: Ubuntu 19.04

**Comment by fxha** [comment]
Blocked due #988 because Mark Text is not single-instance on Linux and Windows.
