### ISSUE TITLE
Do not auto-pair underscore

### ISSUE THREAD

**Issue by WXGopher** [marktext/marktext#1019]
### Description
Auto-pair should not auto-pair underscore ("_")

- [x] Can you reproduce the issue?

### Steps to reproduce
Type in "_" (without quotes)

**Expected behavior:**

A single underscore.

**Actual behavior:**

Underscore is auto-paired to "\_I_" where "I" is the cursor.

### Versions

- Mark Text: 0.14.0
- Operating system: Win10 10.0.17763.292

**Comment by fxha** [comment]
@WXGopher Markdown treats asterisks (`*`) and underscores (`_`) as indicators of emphasis. You could disable auto pairing for markdown in settings if you like.

**Comment by WXGopher** [comment]
Aha that's a good gotcha.
However, in math mode where you type "_" a loooooot, it would be pretty annoying to manually delete the extra "_" every time.

**Comment by WXGopher** [comment]
> @WXGopher Markdown treats asterisks (`*`) and underscores (`_`) as indicators of emphasis. You could disable auto pairing for markdown in settings if you like.

Aha that's a good gotcha.
However, in math mode where you type "" a loooooot, it would be pretty annoying to manually delete the extra "" every time.

**Comment by fxha** [comment]
What do you mean by math mode? When writing inside a math block (`$$<newline>...<newline>$$`) or inline math (`$...$`) autocompletion for markdown (`*`, `_`, ...) is disabled.
