### ISSUE TITLE
Highlight search result and provide a straight jump

### ISSUE THREAD

**Issue by shlinym** [marktext/marktext#1026]
### Describe your feature request
Highlight search result and provide a straight jump.

My idea is that, show (searching)keyword's specific position in file, not just a file, and also highlight the keyword, this feature will provide one step to get search result, and is more convenient.

### What problem does this feature solve? [optional]

After searching keyword, I found the search result only shows the file that contains the keyword, so I have to open the file, scroll it and find the keyword which I'm looking for.

**Comment by fxha** [comment]
@shlinym You mean find in files (sidebar second view), right? And show a result overview like in atom or vscode when searching in files, so you can select one result and open the file at this position?

**Comment by shlinym** [comment]
@fxha yeah, that is what I mean
