### ISSUE TITLE
Inline math equation not support \tag

### ISSUE THREAD

**Issue by linvis** [marktext/marktext#1030]
### Question description

I try to use "\tag{1}" in inline math equation($\tag{1}$), it shows "Invalid mathematical formula", 
but when I try it in block math equation(Advanced Block:Math Formula), it works.

(source code mode)
![image](https://user-images.githubusercontent.com/10113087/57993099-200a6980-7aea-11e9-8ea4-9b3b90813450.png)

![image](https://user-images.githubusercontent.com/10113087/57993210-8a230e80-7aea-11e9-975d-da47ad5f7079.png)

so, is it a bug or inline math equation doesn't support "\tag"?

**Comment by fxha** [comment]
@shlinym I guess `tag` is not supported in inline math, which also make sense because it can be used with other elements.

**Comment by shlinym** [comment]
got it
