### ISSUE TITLE
W10 file association

### ISSUE THREAD

**Issue by zawsx** [marktext/marktext#104]
### Description

Associating *.md files to MarkText doesn't open them on double-click

### Steps to reproduce

1. Right Click any .md and specify 'open with' MarkText and 'always use this program'
2. Verify that icon in file explorer has changed to the MarkText one for .md files
3. Double-click any .md in explorer

**Expected behaviour:** [What you expected to happen]
.md file should open in MarkText

**Actual behaviour:** [What actually happened]
MarkText presents a blank, new document, not the one you wanted opened.

NB: Could be an electron bug?
### Versions

- Mark Text: installed last week
- OS: W10 pro x64

**Comment by fxha** [comment]
Can't reproduce this with v0.8.x. Please download the latest version and try again. If you use version 0.7.x it's already fixed.

**Comment by zawsx** [comment]
Works with latest version, thanks!
Mark Text Setup 0.9.10.exe 80,954kb
Also the icon is better, as the old one was almost transparent on the taskbar.

p.s. When I view the marketext readme.md in marktext, I can see markup that isn't getting translated - should I post a different issue for that?

![marktext](https://user-images.githubusercontent.com/6049993/38162348-50c3b004-34d7-11e8-8f40-09ba23b2693a.png)

**Comment by Jocs** [comment]
@zawsx Mark Text does not support Raw HTML now, This is a new feature in TODO LIST.

A issue is appreciated.

**Comment by Jocs** [comment]
@zawsx 
>Works with latest version, thanks!

The `latest version` in your comments is refered to the master branch ?

**Comment by Jocs** [comment]
GitHub Flavored Markdown support `HTML block` and `inline raw HTML`, So it's right when you see the raw HTML in Mark Text.

The problem is that Mark Text have not highlight the raw HTML or do some thing else.

**Comment by zawsx** [comment]
Thanks for your prompt replies and your patience.  

I thought that the readme.md of Mark Text would be a great demo of a markdown renderer and so would not contain anything that looked like a fault - did not bother to read the raw script - doh!
Suggest you maybe create a 'holygrail.md' that demos the features supported/unsupported.
I will do an issue for the raw HTML in the hope that it helps.  

I also noticed that, if you open an .md and then immediately hit the 'x' icon to close the .md file, you get the 'save' prompt even though no changes have been made - annoying.  You then have to hit cancel. That doesn't end it though, as you then need to hit the 'x' icon again to actually close the file. One main use of Mark Text for me is to read .md files as well as edit/create them.  This is a UI issue and I guess way down the list but I'll raise another issue for it as useability is important imho. Hope my issues don't distract as they are far from important.

**Comment by Jocs** [comment]
@zawsx Go ahead and open another issue about what you described, thanks.
