### ISSUE TITLE
Cannot modify the same file on vscode and marktext simultaneously.

### ISSUE THREAD

**Issue by rhzone** [marktext/marktext#1043]
### Description
Cannot edit the same file on vscode and marktext at the same time. When I modified my markdown file on vscode, it would become empty on marktext, so I have to reopen marktext to see the changes.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. edit the same markdown file on vscode and marktext simultaneously.
2. modified the file on vscode.

**Expected behavior:**

* marktext can update the changes on my file, instead of being empty.

### Versions

- Mark Text:  0.14.0
- Operating system: Ubuntu 18.04.2 LTS

**Comment by fxha** [comment]
Thanks @rhzone, could you please give more information how to reproduce this issue because I cannot reproduce this issue - except once.

**Comment by rhzone** [comment]
> Thanks @rhzone, could you please give more information how to reproduce this issue because I cannot reproduce this issue - except once.
> 
> Edit: Is the file is located on a hard disk or network drive?

My file is located on the hard disk. Both vscode and marktext need to open the save file. Just try to add some new lines to the file  on vscode, my file will become empty on marktext later.

**Comment by fxha** [comment]
That's what I tried. I'm on Fedora 30, tested with Mark Text `develop` and v0.14.0. What file system type do you use?

**Comment by rhzone** [comment]
> That's what I tried. I'm on Fedora 30, tested with Mark Text `develop` and v0.14.0. What file system type and that vscode version do you use? I'm on v1.34.0 git build.
My file system is ext4, and vscode version is 1.34.0
![image](https://user-images.githubusercontent.com/30968676/58371996-9a534780-7f49-11e9-89f5-5665ed328f14.png)

**Comment by fxha** [comment]
Very strange issue but at least I can reproduce this issue on a raw Ubuntu VM.

**Comment by fxha** [comment]
The main issue here is that Unix allow simultaneous writes and reads on the same file and also our watcher reports the added/changed event when a file first appears on disk, before the entire file has been written, or sometimes while the file is being written on Unix (maybe Windows too?). This can lead to the issue that we read an empty file like described above on Unix - on Windows this might also happen but the following read will fail. I can reproduce this issue almost 100% on a VM with only 1 core enabled. I think the CPU and  I/O scheduler switches between vscode (or other editor) and Mark Text at the "wrong" time like:

1. vscode open the file handle and file is truncated
2. vscode start writing data to disk but data is not flushed yet and/or scheduler switches to Mark Text and we read the empty file
3. vscode writes remaining text and flush the buffer

We can workaround the issue with enabling file size polling when a file is added or changed for a short duration but this may leads to a hight CPU usage for a short time per changed file.
