### ISSUE TITLE
Cutting doesn't update diagrams, Math formula etc.

### ISSUE THREAD

**Issue by gaetanww** [marktext/marktext#1049]
### Description
When using the cut command (Ctrl+X), the rendering of the diagram or math formula is not updated.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Write formula or diagram:
```
$$
\frac{a}{b}
$$
```
Formula displays correctly.
2. Cut a part of the formula, for example:
```
$$
\frac{a}
$$
```
Formula doesn't update.

**Expected behavior:**

Rendering of diagram of formula should update whenever the corresponding code is modified.

**Actual behavior:**

When cutting (Ctrl+X) the rendering is not updated.

### Versions

- Mark Text: 0.14.0
- Operating system: Win10

**Comment by Jocs** [comment]
@fxha This seems fixed?
