### ISSUE TITLE
Can't remove entire markdown text

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#105]
### Description

I can't remove entire markdown text from editor. This worked in version 0.8.12.

### Steps to reproduce

1. write `a`
2. go to `Source Code Mode`
3. remove entire markdown text (here `a`)
4. exit `Source Code Mode`

**Expected behavior:**

Empty editor

**Actual behavior:**

`a`

### Versions

- Mark Text: commit `12fa87f`
- OS: Linux and Windows

**Comment by Jocs** [comment]
@fxha This bug is produced by fixing `can not export PDF in source code mode`.

**Comment by Jocs** [comment]
@fxha fixed
