### ISSUE TITLE
Font dialog cannot be closed with Esc button

### ISSUE THREAD

**Issue by dumplingsMing** [marktext/marktext#1050]
### Why font dialog cannot be closed with Esc button?

I found that most pop-up dialogs can be closed by Esc button, which is quite friendly for keyboard users. However, when it comes to font dialog (triggered by ctrl+.), it can only be closed by click in the editor.

This is due to the setting in src/renderer/components/font.vue, the dialog is not set as a modal dialog (modal="false"). Is this a feather of a bug? Should we change it to "true"?

**Comment by fxha** [comment]
I think `modal` should be `true` but we removed the font dialog in the latest development version and added GUI settings.
