### ISSUE TITLE
Hope that Marktext can show yaml when editing

### ISSUE THREAD

**Issue by BeautyYuYanli** [marktext/marktext#1056]
### Describe your feature request

When I type `---` at the begining of the text, it would be shown as

---

but not a `yaml` code block

**Comment by Jocs** [comment]
@BeautyYuYanli Do you want to edit the front matter like this bellow:

```md
---
title: 'foo'
name: 'bar'
---
```

We already support front matter, you can find it in the paragraph menu.

**Comment by fxha** [comment]
Sorry, I misunderstood the issue. I open another issue for TOML/JSON front matter support.

**Comment by fxha** [comment]
Closing this issue as no further information has been provided and this issue it not reproducible. Please feel free to reopen with more information.
