### ISSUE TITLE
Can't parse list items without new line

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#106]
### Description

List items with multiple lines and without new line not working.

```
- a
  b
  c
- d
  e
  f
```

**Expected behavior:**

- a
  b
  c
- d
  e
  f

**Actual behavior:**

```
- a b c
- d e f
```

### Versions

- Mark Text: all
- OS: all

**Comment by Jocs** [comment]
![list](https://user-images.githubusercontent.com/9712830/38161846-e4ceaa5c-3508-11e8-8ff4-63dba4f407fa.gif)

**Comment by Jocs** [comment]
http://spec.commonmark.org/dingus/?text=-%20one%0A%0A%20%20two%0A

![list2](https://user-images.githubusercontent.com/9712830/38161872-59e85f9a-3509-11e8-850e-51e8c944bcaf.gif)

**Comment by fxha** [comment]
But Github and other markdown editors support this. So maybe a GitHub Flavored Markdown feature?

**Comment by Jocs** [comment]
Can yo show me which editor support this?

**Comment by fxha** [comment]
e.g.

- Github
-  Typora
- https://stackedit.io
- https://pandao.github.io/editor.md/en.html
- https://dillinger.io/

**Comment by Jocs** [comment]
@fxha Yes, It's really a bug, Maybe it will be fixed with the new feature `support raw html in Mart Text`.

**Comment by Jocs** [comment]
@fxha It's finally resolved with the new feature `hard and soft line break`.
