### ISSUE TITLE
Web support 

### ISSUE THREAD

**Issue by 625781186** [marktext/marktext#1064]
@Jocs @fxha 
### Web Suppoer
[https://github.com/625781186/marktext2web](https://github.com/625781186/marktext2web)
I think web is possible, I'm trying.

And if you're free, I'd prefer to give it to you to do this project.

https://github.com/marktext/marktext/issues/772#issuecomment-497941813

![image](https://user-images.githubusercontent.com/30521429/58886125-f79f8380-8715-11e9-91a5-c4b15dc09f5d.png)

**Comment by Jocs** [comment]
@625781186 But where to save the edited markdown file?

**Comment by 625781186** [comment]
> @625781186 But where to save the edited markdown file?

I want to use it as a blog editor, so save it in the database.

I think I just need to provide a save interface.

**Comment by fxha** [comment]
@625781186 I think you should take a look at [muya](https://github.com/marktext/muya).

**Comment by 625781186** [comment]
> @625781186 I think you should take a look at [muya](https://github.com/marktext/muya).

thanks~
