### ISSUE TITLE
Unexpected error: selectionChange: expected cursor but cursor is null.

### ISSUE THREAD

**Issue by liziqiang** [marktext/marktext#1068]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
Error: selectionChange: expected cursor but cursor is null.
    at Es.To.A.selectionChange (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3525929)
    at file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3581280
```

### Version

Mark Text: v0.14.0 (4dada5b)
Operating system: Darwin x64 18.6.0 (darwin)

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. We cannot reproduce this issue without steps to reproduce, please provide some steps or how the error occurred.

There is a know issue when clicking behind an image (`![]()`) in preview mode. If you have issues with you build application, please use the latest stable release.
