### ISSUE TITLE
Opening non-Markdown files from folder explorer

### ISSUE THREAD

**Issue by Iffabled** [marktext/marktext#1096]
### Describe your feature request

Clicking a file (for example an exported PDF) that uses a format not supported by Mark Text in the folder explorer opens it in an external program (using system defaults).

### What problem does this feature solve? [optional]

Not being able to quickly open files using unsupported formats.

### Additional context [optional]

Caret Editor has a similar feature.

**Comment by fxha** [comment]
Setting this issue to `blocked` because as of v0.15.0 the side bar tree *may* shows markdown files only when #1086 is merged and then this issue can be closed.

**Comment by fxha** [comment]
Closing this issue because we only add markdown files to the sidebar. Other files are filtered out as of v0.15.0.
