### ISSUE TITLE
[Features] Support block HTML and Raw HTML in Mark Text

### ISSUE THREAD

**Issue by zawsx** [marktext/marktext#110]
### Description

Open up Mark Text's own README.md in Mark Text and you get a lot of raw html that makes it look as if Mark Text is not working.

### Steps to reproduce

1. Open github repo's README.md in Mark Text
2. The raw HTML looks like it's a rendering error

**Expected behavior:** Nice and shiny rendering demo of the power of markdown

**Actual behavior:** Looks likeMark Text has garbled the raw markdown (it hasn't but it looks as if it might have) Who needs a README.md with a lot of unintelligible html markup at the top?

**Link to an example:** 
![marktext](https://user-images.githubusercontent.com/6049993/38162806-ea29a822-34df-11e8-89cf-015ebdf7eea2.png)

### Versions

- Mark Text: Master branch, v 0.9.10
- OS: W10 Pro 64

**Comment by Jocs** [comment]
@zawsx the latest master commit has support this HTML block and raw html, You can download the source code and build Mark Text yourself. And try this new feature.
