### ISSUE TITLE
Table separators begin to move around when scrolling

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1106]
### Description

A few table separators begin to move around when scrolling the editor.

### Steps to reproduce

1. Insert document from below and insert as much lines as the editor begin to scroll.
2. Scroll a bit and you will notice one or multiple table separators/lines floating around.

```
foo

| a   | b   | c   |
| --- | --- | --- |
| d   | e   | f   |
| g   | h   | i   |
| j   | k   | l   |

foo

bar

foo

bar

foo

...
```

**Expected behavior:**

No table separators should move around.

**Actual behavior:**

A few table separators begin to move around while scrolling.

![mt_table_sep](https://user-images.githubusercontent.com/22716132/59375663-f04c2b80-8d4e-11e9-8e82-574e9906edfd.gif)

### Versions

- Mark Text: v0.14.0 develop build
- Operating system: all

**Comment by Jocs** [comment]
@fxha This issue seems to be fixed by update Electron to latest version.

**Comment by Jocs** [comment]
Pls check and to determine whether to close this issue.
