### ISSUE TITLE
Regression: no custom fonts are allowed

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1107]
### Describe your feature request

The (new GUI) font family settings should allow custom fonts and not only the 4 hard coded ones. Even the settings file on disk cannot be changed due settings validation (JSON schema) without patching Mark Text source code. This also applies for code block fonts.

### What problem does this feature solve? [optional]

This feature/regression should add custom font families to Mark Text back because not everyone want's to use the hard coded ones or can use these fonts. E.g. on Linux only `Open Sans` or `sans-serif` are available because the others are proprietary fonts and cannot be used.

### Versions

- Mark Text: v0.14.0 develop build / upcoming v0.15.0
- Operating system: all

**Comment by theUncanny** [comment]
I upvote this! :+1: 

I just updated to version 0.15.0 and when I try the new preferences GUI to reconfigure the necessary to my taste, it's not possible to set the fonts that I like, but that it was limited to choose from a reduced and closed preset list of typographical fonts and if I try to "encircle" it by editing and adding my prefered fonts in the file (Linux based system):

- `~/.config/marktext/preferences.json`

I launch Mark Text again on CLI but it closes and shows the following error:

```sh
There was an error during loading
This seems to be an issue with your configuration file(s). Config schema violation: `editorFontFamily` should be equal to one of the allowed values; `codeFontFamily` should be equal to one of the allowed values

[...]
```

I miss this basic customization feature... :disappointed:

**Comment by Ir1d** [comment]
Hi, any update on this? Really looking forward to use custom font instead of those ones.

**Comment by Ir1d** [comment]
@theUncanny I managed to build marktext with Fira Code supported:
1. append "Fira Code" in `src/renderer/prefComponents/editor/config.js`
2. append "Fira Code" in `editorFontFamily` in `src/main/preferences/schema.json`

**Comment by carlinmack** [comment]
I tried editing %APPDATA%\marktext\preferences.json but I am getting `'editorFontFamily' should be equal to one of the allowed values` For this issue to be closed you should be able to select a custom font through the GUI.

**Comment by Jocs** [comment]
@carlinmack What's the version of Mark Text you use?

**Comment by carlinmack** [comment]
v0.15.0.

I've upgraded through the menu>check for updates to v0.15.1 and the problem still persists 
![image](https://user-images.githubusercontent.com/6676843/69116960-2d35f000-0a5c-11ea-86a4-dbf7b1db37a8.png)

I'll try downloading the lastest release from github
