### ISSUE TITLE
Regression: image deletion url missing

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1114]
### Description

The SM.MS delete URL is no longer shown on develop branch after uploading an image.

### Versions

- Mark Text: v0.14.0 develop branch
- Operating system: all

**Comment by Jocs** [comment]
Where can we show the `delete URL`? put it in the `Notification` and click to copy to clipboard?

**Comment by fxha** [comment]
Yes right, show a notification and copy on click.
