### ISSUE TITLE
Integrating Marktext Into Zotero Reference Manager

### ISSUE THREAD

**Issue by maxsu** [marktext/marktext#1118]
[Zotero](https://github.com/zotero/zotero) is a research paper and notes organizer licensed under AGPL3. It currently uses [TinyMCE](https://github.com/tinymce/tinymce) for note editing and lacks support for markdown, formulas & diagrams. Zotero is moving to Electron and I have this wild idea: could we embed Marktext as a lightweight notes engine for Zotero?

### Strategy 

1. Import Marktext into a Zotero addon or Zotero mainline
2. Reuse/Repurpose Marktext `Renderer` vue component stack and `Main` backend
3. Pin against a fixed Marktext version
4. Occasionally integrate updates from Marktext upstream from time to time

### Questions

1. Does this usecase sound remotely plausible? What are some reasons to believe that updating (step 4) would be less than _awful_?
2. What is the status of Muya, and where should I go to learn more about it? What projects currently showcase its use?
3. What other advice or suggestions come to mind?
4. Is anyone particularly eager to brainstorm on this fool's errand with me?

**Comment by Jocs** [comment]
> Strategy

I read your description, I feel that you don't need Mark Text, you need Mark Text's markdown editor muya, muya's main development and maintenance is still in the Mark Text project, but it is very independent, in Mark In the Text project, it is a separate folder with no dependencies on other files in the project. If you only need a markdown editor, I think muya can meet your needs, just as you use Mark Text, it already Very stable.

There is another project in the marktext organization named muya, which is mainly for the development of muya 2.0, muya 2.0 will support collaborative editing, less memory consumption, higher performance. After the completion of muya 1.0 in Mark Text, it is also possible to move to the muya repository.

> Does this usecase sound remotely plausible? What are some reasons to believe that updating (step 4) would be less than *awful*?

Then if you need to update muya, just copy the muya folder to your project after the new version of Mark Text is released. It's as simple as that. If I publish it to npm, you only need to update it via npm.

> What is the status of Muya, and where should I go to learn more about it? What projects currently showcase its use?

The completion of muya in the Mark Text project is over 90%. The latter is mainly to improve stability, add some markdown non-standard syntax, and improve performance. Here is an example of using https://github.com/Jocs/muya-example. Although it is used in Vue projects, I also use muya development projects in other front-end frameworks, such as React.

> What other advice or suggestions come to mind?

Welcome to use muya, currently copy the Mark Text repository muya folder directly.

> Is anyone particularly eager to brainstorm on this fool's errand with me?

You can participate in discussions with me in this issue.

**Comment by maxsu** [comment]
Thanks for the informative response @Jocs! It feels like Muya could be a great fit for my use case, and I'm happy to hear it's healthy. Thanks for the example - I'll evaluate that and put together some next steps, which I may share here, or on the Muya issue tracker. I'll reach out if I have major success or major issues slotting Muya back in an electron environment. Pleased to make your acquaintance!

**Comment by BrandonKMLee** [comment]
A note here to https://github.com/marktext/marktext/issues/1358 that Zettlr has this integrated https://docs.zettlr.com/en/academic/citations/
