### ISSUE TITLE
Redundant document title

### ISSUE THREAD

**Issue by alxlg** [marktext/marktext#1123]
### Description

When using native title bar the title in the window is redundant.

- [x ] Can you reproduce the issue? 

### Steps to reproduce

1. Enable native window decoration (title bar) from Mark Text settings

**Expected behavior:**

When using native title bar the title in the window should be hidden.

**Link to an example:**

![immagine](https://user-images.githubusercontent.com/26327475/60282834-27523d80-9908-11e9-88f7-3e45c472646d.png)

### Versions

- Mark Text: 0.14.0
- Operating system: KDE Neon 5.16 (Ubuntu LTS 18.04)

**Comment by alxlg** [comment]
Forgot to mention that it happens only for unsaved documents, here it's more clear without the menu bar:

![immagine](https://user-images.githubusercontent.com/26327475/60283490-8b293600-9909-11e9-8971-392600eeba76.png)

**Comment by fxha** [comment]
I'm unsure how to best solve this problem and that's why we use a custom taskbar design and removed the native one a while ago but re-added on demand. We could use Mark Text or an empty native title and only show the path in the editor, this would be the easiest solution without adding lots of branches. We could also remove the not native title and show the path as native window title but then the space would be totally wasted but we have to show the word count somehow. Further ideas are welcome.

![mt_path_tb](https://user-images.githubusercontent.com/22716132/60366979-60181280-99ed-11e9-83db-537a6acefe40.png)

**Comment by alxlg** [comment]
@fxha three possible solutions:

1. In the title bar just display "MarkText" instead of the unsaved new document name 
2. In general use this scheme for the window title: `documentName.md — MarkText` (at least this makes the redundancy less evident)
3. Don't display that text label with the name of the unsaved document when native titlebar is used (but still display the current text label with the full path we have now that is always useful)

In my humble opinion the best would be a combination of 2. and 3. i.e. use `documentName.md — MarkText` as window title always and hide the unsaved document label below it when using native title bar

**Comment by alxlg** [comment]
i made a mockup:

![immagine](https://user-images.githubusercontent.com/26327475/60385325-42e45200-9a88-11e9-8bbe-d0cd270477aa.png)

**Comment by fxha** [comment]
@Jocs I don't really know where we set the window title. Is this handled by vue?

**Comment by Jocs** [comment]
@fxha Do you mean `<title>` tag in html?

I also found this in Electron documents.

> [new BrowserWindow(options)](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions)
>title String (optional) - Default window title. Default is "Electron". If the HTML tag <title> is defined in the HTML file loaded by loadURL(), this property will be ignored.

I also found this codes maybe be helpful in `titleBar.vue`

```js
    watch: {
      filename: function (value) {
        // Set filename when hover on dock
        const title = this.project && this.project.name ? `${value} - ${this.project.name}` : value
        document.querySelector('title').textContent = title
      }
    },
```

**Comment by fxha** [comment]
@alxlg I decided to only add ` - Mark Text` suffix to the native window but not remove the untitled tab title as in 3\. due unsaved changes notification dot.
