### ISSUE TITLE
Tab switching shortcut please

### ISSUE THREAD

**Issue by gooddadmike** [marktext/marktext#1124]
### Steps to reproduce

1. Open multiple tabs
2. Look longingly at the tab you want and despair there is no way to reach them without touching your mouse all the way over there ---->
3. Think to yourself, this app is so beautiful and so perfect. Besides this oversight. I should put in a polite feature request.

**Expected behavior: [Ctrl]+[tab] or something would allow me to change tabs**

**Nothing I try works**

### Versions

- Mark Text:v0.14.0
- Operating system: win10

**Comment by Jocs** [comment]
@gooddadmike This really is a good feature, we'll add it asap.
