### ISSUE TITLE
Buttons on the small picture are hidden.

### ISSUE THREAD

**Issue by IceEnd** [marktext/marktext#1127]
### Description

Buttons on the small picture are hidden, like `edit` and `delete`.

![image](https://user-images.githubusercontent.com/11556339/60392355-58fb1c80-9b33-11e9-9072-7b298b35d2ee.png)

How about put buttons on the right side of the line?

### Steps to reproduce

1. Insert a smaller image

### Versions

- Mark Text: 0.14.0
- Operating system: MacOS

**Comment by Jocs** [comment]
Do you have any solutions or suggest on how to solve this?

**Comment by fxha** [comment]
Closing this issue because we refactored the image "viewer".
