### ISSUE TITLE
Selecting all (control + A) does not function the same as a mouse selection

### ISSUE THREAD

**Issue by DomHudson** [marktext/marktext#1132]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Insert text
2. Select text (using Control + a)
3. Press a letter/backspace/delete
or
3. Press control + c
or 
3. Press control + x

**Expected behaviour:**

If a character is pressed: I expect the selected text to be replaced with the character.
If backspace or delete is pressed: I expect the selected text to be deleted.
If control +c is pressed: I expect the selected text to be copied to the clipboard.
If control + x is pressed: I expect the selected text to be "cut" to the clipboard.

**Actual behaviour:**

If a character is pressed: the selected text is unselected and the character is appended to the end of the document.
If backspace or delete is pressed, the selected text remains selected but no characters are deleted.
If control +c is pressed, the selected text remains selected but no characters are copied. Control + v does not insert any additional characters into the document.
If control + v is pressed, the selected text becomes unselected but no characters are deleted or cut from the document. Control + v does not insert any additional characters into the document.

### Versions

- Mark Text:
```
v0.14.0
```
- Operating system:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

**Comment by Jocs** [comment]
@DomHudson Very clear issue, thanks. I test it on the `develop` branch, I found that it works well. Can you help test it on the `develop` branch?

**Comment by fxha** [comment]
@Jocs Yes, seems to be fixed on latest development branch, except for this:

> If control + v is pressed, the selected text becomes unselected but no characters are deleted or cut from the document. Control + v does not insert any additional characters into the document.

But this is an optimization for later or even a won't fix. I guess that this is currently not possible to detect easily - or we would need to parse multiple times and compare against our data structure.

**Comment by Jocs** [comment]
>If control + v is pressed, the selected text becomes unselected but no characters are deleted or cut from the document. Control + v does not insert any additional characters into the document.

The clipboard text replace the selected text when I press `Cmd + V` on macOS. So it only occur on Linux systems?

**Comment by fxha** [comment]
I don't know, misread or so but all works fine with latest dev build.

**Comment by fxha** [comment]
Closing this issue because this is already fixed.
