### ISSUE TITLE
Checkbox text not aligned with box

### ISSUE THREAD

**Issue by NoelAbrahams** [marktext/marktext#1135]
- [x] Can you reproduce the issue?

The text is slightly above centre as shown in the image, also a bit more space between the box and the text is probably needed.

![image](https://user-images.githubusercontent.com/1106823/60595439-ee4e1900-9d9e-11e9-9f4a-a8ddfeaaa853.png)

This is the case for all other themes.

### Versions

- Mark Text: v0.14.0
- Operating system: Windows 10 (Version 10.0.17134 Build 17134)

**Comment by acicovic** [comment]
This bug seems to be back.

![image](https://user-images.githubusercontent.com/23142906/92300005-11a2c400-ef60-11ea-88f0-f6403d6e8317.png)

**Comment by TechManos** [comment]
I can confirm the issue is back, currently observing it:

![Image](https://github.com/user-attachments/assets/b2a2aac1-9fee-4be7-8b11-3019ec095c0e)

### Versions

- Mark Text:  v0.17.1
- Operating system: Microsoft Windows [Version 10.0.19045.5487]
  - Used `ver` command in CMD
