### ISSUE TITLE
"|" must be escaped in a table

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1136]
### Description

The `|` character must be escaped in the table in preview mode, otherwise data loss occurs like in the example below.

### Steps to reproduce

1. Create a markdown table and write e.g. `| a | b | c |` as column
2. Now edit cell `b` to `b|x` or simular in preview mode
3. Save document and reopen the document or switch to source-code mode and back
4. The cell next to the edited one was replaced with `x` because the `|` character was not escaped by Mark Text and is parsed as cell separator

**Expected behavior:**

The table separator `|` must be escaped when used in preview mode.

**Actual behavior:**

![mt_table_escape](https://user-images.githubusercontent.com/22716132/60618904-b616fc80-9dd7-11e9-96e8-ae2a9cc3fbb1.gif)

### Versions

- Mark Text: all
- Operating system: all

**Comment by Jocs** [comment]
@fxha I think we need to add a `\\` before `|` if user didn't write a `\\`.
