### ISSUE TITLE
can't type headers(start with ###) via fcitx

### ISSUE THREAD

**Issue by hungtcs** [marktext/marktext#114]
### Description

使用fcitx输入法输入标题的时候无法输入

![peek 2018-04-02 13-35](https://user-images.githubusercontent.com/11692935/38184533-e25d726c-367a-11e8-9cff-9df78aebab20.gif)

### Steps to reproduce

1. open marktext and input a header(start with ###) via fcitx

### Versions
- Mark Text: v 0.8.12
- OS: Ubuntu 16.04.1

**Comment by Jocs** [comment]
@hungtcs Thanks, I'll download fcitx and test it.

**Comment by Jocs** [comment]
@hungtcs 请问下你在使用搜狗输入法的时候也会遇到这种问题吗？

**Comment by hungtcs** [comment]
@Jocs If I type header text first, and then insert `###` before the header text may avoid this bug.

![peek 2018-04-02 14-25](https://user-images.githubusercontent.com/11692935/38185672-e208e876-3681-11e8-97f4-f5a5f1824733.gif)

**Comment by hungtcs** [comment]
@Jocs 不好意思，搜狗输入法没试过

**Comment by Jocs** [comment]
@hungtcs 😢 这一个 bug，总不能让用户先输入文字，再去输入`#`吧。能帮我测试下搜狗输入法吗？
mac 上好像没有 fcitx 这个输入法。

**Comment by hungtcs** [comment]
@Jocs 搜狗输入法没有这个问题

**Comment by Jocs** [comment]
@hungtcs 我暂时没法安装 fcitx 输入法，你能帮我找下原因吗？bug 应该是在 `editor/` 内。

**Comment by hungtcs** [comment]
有时间的话我会的，我猜问题应该与键盘的监听事件有关系

**Comment by zengyufei** [comment]
我也是遇到同样的问题，我的是搜狗输入法，换成讯飞输入法就没有这个问题

**Comment by hungtcs** [comment]
@Jocs 我的输入法不会出现这个问题了，我也不太清楚具体原因。
前两天我换了`google pinyin`代替`fcitx pinyin`（因为其他的原因），`google pinyin`没有出现上面的问题。
我昨天fork了项目准备测试，然后刚刚又安装了`fcitx-pinyin`，但是`fcitx pinyin`好像是被`google-pinyin`影响了，它也恢复正常了！下面的图片中可以看到现在`fcitx-pinyin`输入汉字的时候显示了灰色的预输入文本，之前是不会出现的（可以参考上面的图片，就没有出现）。这与 @zengyufei 的情况应该是同一个问题，因为`fcitx`并没有提供相应的设置选项，我已经无法复现之前的问题了。如果有在`elementary OS`上测试或者其他可以帮助您的，请@我

![peek 2018-04-18 11-47](https://user-images.githubusercontent.com/11692935/38911147-d7e616ae-42ff-11e8-96e0-fd478321c650.gif)

**Comment by Jocs** [comment]
@hungtcs 出现灰色文字是编辑器的问题，这是一个比较难优化的地方，但是不影响输入。

**Comment by Jocs** [comment]
@hungtcs 

>如果有在elementary OS上测试或者其他可以帮助您的，请@我

非常感谢你愿意为 Mark Text 做贡献，issue 中标记为 `bug` 或者 `help wanted` 都是需要解决的问题，如果你有时间的话，可以帮忙看看，如果你有其他想法，欢迎在这儿交流。

**Comment by Jocs** [comment]
@hungtcs 

>如果输入法没有这种预输入文本，会不会对编辑器的解析造成影响？

应该不会的

**Comment by Jocs** [comment]
@hungtcs 这个问题还存在吗？

**Comment by hungtcs** [comment]
@Jocs 我这里现在是正常的，但是我没有修改任何代码。现在我用fcitx-pinyin、google-pinyin和搜狗输入法都没有问题了。
