### ISSUE TITLE
Line width / line wrap threshold adjustable?

### ISSUE THREAD

**Issue by danielyzli** [marktext/marktext#1141]
### Question description

I was wondering whether line width / line wrap threshold is adjustable to fit the width of the application. Thanks in advance!

**Comment by yougotwill** [comment]
@danielyzli If I understand this correctly it's been fixed in version 0.15.x which hasn't been released yet. See my issue https://github.com/marktext/marktext/issues/1053

**Comment by danielyzli** [comment]
Thanks for the response!

**Comment by fxha** [comment]
Thanks for you question @danielyzli. As @yougotwill already mentioned, you can control the editor width in the next release or development version via settings. @Jocs and me are a litle bit bussy right know but the next version should be release any time soon.

![mt_pref_width](https://user-images.githubusercontent.com/22716132/60979035-5027f900-a332-11e9-9f7e-f780b1155bc7.png)
