### ISSUE TITLE
clickable links

### ISSUE THREAD

**Issue by gooddadmike** [marktext/marktext#1144]
### Describe your feature request

I would like an easy way to open formatted links (or any links)

### What problem does this feature solve? [optional]

As an editor "link preview" is the right default. As a notes tool, I would like a context menu or a tool-tip hint that would tell me how to launch the link in default browser. Instead of having to select and copy then switch and paste in URL bar.

### Additional context [optional]

I love you! (devs of this app)

**Comment by Jocs** [comment]
>I love you! (devs of this app)

Thank you! love you too.

We have one way to open the link by default browser by `CmdOrCtrl + Click`. We maybe add a `link` icon button on the right of link text in the future, so we can click the icon button to open the link or other markdown file.

**Comment by fxha** [comment]
Closing this because this feature is already implemented in the latest development version, as described above. But end-user documentation is still needed.
