### ISSUE TITLE
Can't realign an ex-bullet point to left side

### ISSUE THREAD

**Issue by AsierRF** [marktext/marktext#1149]
### Can't realign an ex-bullet point to left side

I noticed an strange behavior that does not allow me to move left (shift + tab keys) a bullet point from which I removed the '-' character.

* OS: Linux x64
* Marktext version: v0.14

Let me show an example:
I have created my bullet list until 'test4' item. Then I press enter key, (let's say that by mistake, I forget to remove the '-' from the list,) and added my next paragraph text. As shown below:
![image](https://user-images.githubusercontent.com/17161846/61184188-19f8bb00-a64b-11e9-9b08-de652031edef.png)

Then I realize that my *new paragraph* is as a bullet point so I remove the '- ' characters (space also removed). However, the paragraph stays tabbed (see first paragraph for comparison of left margin) as shown in the image below:
![image](https://user-images.githubusercontent.com/17161846/61184232-97bcc680-a64b-11e9-9ffa-b2ae5cabe75d.png)

As a result, I can not move the 'ex-bullet' to the left by pressing shift+tab or using the backspace key (the only solution is open the file in source mode and remove the 2 space characters left when removing the '- ' characters).

I wonder whether this is an expected behavior or it is a bug.

Thanks for your help. I also would like to congratulate you guys for this amazing editor. Can't wait for v0.15!!!

**Comment by fxha** [comment]
Thanks @AsierRF this is indeed a problem but the expected behavior because the line belongs to the parent list item according markdown specification. I would suggest that an `<enter>` after an empty line creates a new paragraph instead a new list item line.

E.g. `bar` should become a paragraph after pressing `<enter>`:

```
- foo1
- foo2
  <empty line>
  <enter>bar
```

**Comment by Jocs** [comment]
>Thanks for your help. I also would like to congratulate you guys for this amazing editor. Can't wait for v0.15!!!

The new version of Mark Text is basically completed, in the final test phase, stay tuned

**Comment by Jocs** [comment]
Closed due to inactive, feel free to reopen it if you have more info.
