### ISSUE TITLE
Rebase markedjs to latest version

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1155]
Issue to track the rebase of markedjs v0.7.0 - current marked version is 0.6.2. The new version contains inline style fixes but also two security fixes.

**Comment by Jocs** [comment]
@fxha I think this issue should be placed at 0.16.0, because rebase marked is a tedious job and it takes a long time to test?

**Comment by fxha** [comment]
I think we should pick the two security fixes and add further changes in v0.16.0.

**Comment by Jocs** [comment]
> the two security fixes

Which two fixes?

**Comment by fxha** [comment]
These two:

```
- Sanitize paragraph and text tokens #1504
- Fix ReDOS for links with backticks (issue #1493) #1515
```

**Comment by Jocs** [comment]
@fxha https://github.com/markedjs/marked/pull/1504#issue-292192337 is tolerated at current time, because we already sanitized the html in export html and preview html.

and I'll rebase \#1515.

**Comment by Jocs** [comment]
@fxha Did you finish this issue? Can we close it now?

**Comment by Jocs** [comment]
@fxha Did you finish this issue? Can we close it now?
