### ISSUE TITLE
'_' parser bug

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#116]
### Description

`_` within a text followed by something and `_` within a text is not parsed/rendered correctly.

### Steps to reproduce

1. Go to Source Code mode and insert:
   ```
   O_CLOEXEC - works

   O_CLOEXEC `O_RDONLY`

   O_CLOEXEC O_CLOEXEC

   `O_RDONLY` - works

   _foo_ - works (italic)
   ```
2. Exit Source Code mode

**Expected behavior:**

O_CLOEXEC - works

O_CLOEXEC `O_RDONLY`

O_CLOEXEC O_CLOEXEC

`O_RDONLY` - works

_foo_ - works (italic)

**Actual behavior:**

![mt_parser](https://user-images.githubusercontent.com/22716132/38360411-650da1a4-38ca-11e8-8bce-85d7a1664cc2.png)

### Versions

- Mark Text: 0.9.25 and latest master

**Comment by Jocs** [comment]
@fxha 

According GitHub Flavored Markdown.

>Inline code spans, links, images, and HTML tags group more tightly than emphasis. So, when there is a choice between an interpretation that contains one of these elements and one that does not, the former always wins. Thus, for example, \*[foo*\](bar) is parsed as *\<a href="bar">foo*\</a> rather than as \<em>\[foo\</em>\](bar).

Yes, this is a parse bug.

**Comment by fxha** [comment]
@Jocs  It's nice to see that the first problem is solved, but `a_b a_b` is still emphasis. E.g. [commonmark](http://spec.commonmark.org/dingus/?text=foo_bar%20foo_bar) and Github (a_b a_b) don't highlight this. They highlight `\b_[...]\b_` (regex) only. Do you want to change this? And another problem is that `a\_b a_b` is not escaped (`a\_b a\_b` is escaped successfully).

![mt_text](https://user-images.githubusercontent.com/22716132/38471624-ded29b24-3b73-11e8-9b30-8fdca01568ed.png)

**Comment by Jocs** [comment]
@fxha I'll fixed, thanks.

**Comment by Jocs** [comment]
@fxha Markdown syntax emphasize is strictly following [GFM](https://github.github.com/gfm/#punctuation-character) now.
