### ISSUE TITLE
Opens files in a seperate window

### ISSUE THREAD

**Issue by kumarve** [marktext/marktext#1166]
### Description

After launching the MarkText app, when a file is opened, it should open in the same windows rather than opening in a new window. This always leaves an empty window and it has to be manually closed.
### Steps to reproduce
1.  Launch MarkTest 
2. Cmd+O and open any file

**Expected behavior:**
The file should open in the already opened app If the app has a file previously opened, the new file can be opened in a tab

**Actual behavior:**
The file is opened in a new  window

### Versions

- Mark Text:0.14.0
- Operating system: Mac 10.12.6

**Comment by Jocs** [comment]
@kumarve You can set `openFilesInNewWindow` to false in the preference menu.
