### ISSUE TITLE
Unable to open files - Windows

### ISSUE THREAD

**Issue by ColdIce1** [marktext/marktext#1171]
### Description
Version: v0.14.0 - both portable & setup
Unable to open existing *.md files. Results in a new blank Mark Text window

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Open Mark Text
2. Go to Menu -> FIle -> Open File
3. Select existing *.md file

**Expected behavior:**
Existing *.md file to load with text

**Actual behavior:**
New empty Mark Text window without any text

### Versions

- Mark Text: Version: v0.14.0
- Operating system: Microsoft Windows 10 v1809

**Comment by fxha** [comment]
Thanks for reporting this issue. Could you please try a simple markdown file or provide a minimal example to reproduce this issue?
