### ISSUE TITLE
Markdown Extra 

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#1182]
### Describe your feature request

> Markdown Extra is an extension to PHP Markdown implementing some features currently not available with the plain Markdown syntax. Markdown Extra is available as a separate parser class in PHP Markdown Lib.
> 
> This document explains the changes and additions to the Markdown syntax implemented by Markdown Extra. You should already be familiar with original Markdown syntax documentation before reading this document.

Document:https://michelf.ca/projects/php-markdown/extra/

#### Missing extensions
+ Markdown Inside HTML Block
+ Attributes: `{#id .class}`
+ Fenced Code Blocks
+ Definition Lists

...You may need a custom CSS.

**Comment by Jocs** [comment]
Close this issue because we have submitted some new issues to track the different syntax of pandoc，feel free to reopen it if you question.
