### ISSUE TITLE
Move row / column inside table

### ISSUE THREAD

**Issue by N0rbert** [marktext/marktext#1186]
### Describe your feature request

Other editors such as Typora has very useful feature - moving row / column inside the table.
It is performed by mouse and <Ctrl+Shift>+<arrow> shortcut.

### What problem does this feature solve?

Move row / column inside the table. See animation below from [typora's help page](http://support.typora.io/Table-Editing/#move-rowcolumn):

>![t](https://user-images.githubusercontent.com/309456/61938412-ad11e900-af99-11e9-8d41-213e46f2e82e.gif)

**Comment by Jocs** [comment]
@N0rbert duplicated with #32 ?

**Comment by N0rbert** [comment]
Oh, yes, seems to be. I think we can add animated gif there :)
