### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by SuperAllenYao** [marktext/marktext#1189]
### Description

- [✅] Can you reproduce the issue? 

### Steps to reproduce

1. [First step] Open folder,  Auto Save selected
2. [Second step] selected a file
3. [and so on...] cmd+s 

**Expected behavior:** save the files

**Actual behavior:** apps go crash

**Link to an example: [optional]**
If you selected "Auto Save" feature , then this bug can be  reproduce
But the contents that I type, still saved. 
looks like the AutoSave is the key.

### Versions

- Mark Text:  v0.15.0-rc.1
- Operating system:    MacOS 10.14.6

**Comment by Jocs** [comment]
@SuperAllenYao Thanks for report this issue, it seems a serious bug, we'll fix it asap.

**Comment by SuperAllenYao** [comment]
> @SuperAllenYao Thanks for report this issue, it seems a serious bug, we'll fix it asap.

Holy shit man, you still online!!!!!!

**Comment by Jocs** [comment]
@SuperAllenYao You too.

**Comment by SuperAllenYao** [comment]
@Jocs 
Because I'm really love this app,  Ahahah.

**Comment by Jocs** [comment]
@SuperAllenYao Good night!!!

**Comment by fxha** [comment]
I cannot reproduce this issue on Linux.

> apps go crash

What does this mean exactly? Application crash or just an exception?

**Comment by Jocs** [comment]
The app crashed，it maybe due to the file/folder watcher, I think it only happen on macOS system, I will take a look tomorrow 

发自我的 iPhone

**Comment by SuperAllenYao** [comment]
> I cannot reproduce this issue on Linux.
> 
> > apps go crash
> 
> What does this mean exactly? Application crash or just an exception?

Application crash, Application suddenly disappear and pop an error information.
