### ISSUE TITLE
Didn't remember last windows state.

### ISSUE THREAD

**Issue by SuperAllenYao** [marktext/marktext#1192]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]                  open a file or directory
2. [Second step]            close the window 
3. [and so on...]              reopen Mark Text

**Expected behavior:** 
open the last file that I opened or directory

**Actual behavior:** 
open a new file

**Link to an example: [optional]**

### Versions

- Mark Text:    v0.15.0-rc1
- Operating system:    MacOS 10.14.6

**Comment by Jocs** [comment]
@SuperAllenYao I remember that this feature is not implemented yet.

**Comment by SuperAllenYao** [comment]
> @SuperAllenYao I remember that this feature is not implemented yet.

I see

**Comment by Jocs** [comment]
@fxha it maybe duplicate with #988 ?

**Comment by fxha** [comment]
Yes that's right. This is the default settings value but is currently not implemented. It was planned for v0.16.0 but as it seems like I have not enough time to implement it right now.
