### ISSUE TITLE
Typo in setttings menu

### ISSUE THREAD

**Issue by AsierRF** [marktext/marktext#1199]
Hello,

Version: Mark Text 0.15.0-rc.2
OS: Linux (AppImage)

I noticed a typo in the Image Preferences: They text says *sepcial* where I assume should say *special*. Image below shows this:

![image](https://user-images.githubusercontent.com/17161846/62044428-34ae6080-b203-11e9-8055-9eefa01c7036.png)

**Comment by Jocs** [comment]
Thanks for your reporting this bug, PR is also welcomed!

发自我的 iPhone

**Comment by CptPotato** [comment]
I think this is another typo:

![grafik](https://user-images.githubusercontent.com/3957610/62165856-a7acf980-b31f-11e9-8803-6ecb0951d1f4.png)

**Comment by escape0707** [comment]
> 
> Thanks for your reporting this bug, PR is also welcomed! 发自我的 iPhone
> […](#)
> 在 2019年7月29日，下午7:17，Asier ***@***.***> 写道： Hello, I noticed a typo in the Image Preferences: They text says sepcial where I assume should say special. Image below shows this: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

PR created.
