### ISSUE TITLE
Release plan of version 0.15.0

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#1201]
### Release plan

 - [x] Fixed all issues in project `0.15.x`
 - [x] Testing
 - [x] Publish GitHub beta release (v0.15.0-rc.1) or more
 - [x] Fixing all critical bugs (`pre-release` and `serious` label only)
 - [x] Update release notes and close all remaining issues
 - [x] Publish GitHub release (v0.15.0)
 - [x] Update app download link on website.

 ### Post release plan

- [x] Add or build libsecret for Flathub package due `node-keytar` dependency
- [x]  Publish Flathub package @fxha 

### Schedule

Planned early August
27 July 2019 expected release candidate
4 August 2019 expected stable release

**Comment by Jocs** [comment]
@fxha Can you help publish Flathub package? I have published the github release v0.15.0.

**Comment by fxha** [comment]
Corrected and added missing checksums of v0.15.0 release.

**Comment by Jocs** [comment]
>Corrected and added missing checksums of v0.15.0 release.

Is the checksum of the 0.15.0 version wrong now?

**Comment by fxha** [comment]
Yes, it *was* wrong and few checksums missing but I updated all checksums. The binaries are build against c071896 ([AppVeyor](https://ci.appveyor.com/project/marktext/marktext/builds/26507575) & [Travis](https://travis-ci.org/marktext/marktext/builds/568430374)).

**Comment by fxha** [comment]
The Flatpak package should be available in the next days. I need to patch some files so Electron 5 work in the Flatpak sandbox and do some testing afterwards.

**Comment by fxha** [comment]
Flatpak package is now available for download.
