### ISSUE TITLE
Source Code Mode font size are different with normal mode

### ISSUE THREAD

**Issue by SuperAllenYao** [marktext/marktext#1204]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. set 16px font size in normal mode
2. Selected source code mode

**Expected behavior:** source code mode font size is the what I set in normal mode

**Actual behavior:** source code mode font size smaller than normal mode

**Link to an example: [optional]**

### Versions

- Mark Text: 0.15 -rc2
- Operating system: macOS 10.14.6

**Comment by Jocs** [comment]
It's not implemented yet, I think this maybe use another preference option to set source code font size?

**Comment by SuperAllenYao** [comment]
> It's not implemented yet, I think this maybe use another preference option to set source code font size?

I think the font size setting affect to the all mode it will be better😂. because when I set the font size I want the all mode display the same size what I set.

**Comment by Jocs** [comment]
@SuperAllenYao the source code mode is different from preview mode, Because preview mode different block has different font size, for example, the header 1 is bigger than normal paragraph, so we need another option to set the source code mode's font size.

**Comment by fxha** [comment]
@Jocs I would say we should move the code font setting below the preview ones. Was there any reason to insert the settings in different positions?

**Comment by Jocs** [comment]
>I would say we should move the code font setting below the preview ones. Was there any reason to insert the settings in different positions?

Good idea, no other reason.
