### ISSUE TITLE
Github images upload service setting's UI incorrectly display

### ISSUE THREAD

**Issue by SuperAllenYao** [marktext/marktext#1205]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. click the  "save" button

**Expected behavior:** full blue line surround the button

**Actual behavior:** missing the right blue line in the button
<img width="971" alt="Screen Shot 2019-07-30 at 10 41 00 AM" src="https://user-images.githubusercontent.com/49594823/62101990-7ac9f980-b2c1-11e9-8188-8249a24c2754.png">

**Link to an example: [optional]**

### Versions

- Mark Text: 0.15 -rc2
- Operating system: macOS 10.14.6

**Comment by liziqiang** [comment]
same here!
