### ISSUE TITLE
Cursor should focus between parentheses after selecting text and clicking hyperlink icon

### ISSUE THREAD

**Issue by escape0707** [marktext/marktext#1206]
### Description

During editing, selecting text and clicking hyperlink icon will select description text between brackets. But I think when people do formatting works to add the link address after wrote the description, they usually want to:
1. Select text
2. Click hyperlink icon
3. `Ctrl-V` to paste the hyperlink copied previously.
Just like GitHub's WYSIWYG hyperlink tool behaves.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Select text
2. Click hyperlink icon

**Expected behavior:**

Cursor focuses between parentheses for directly insert or paste link address.

**Actual behavior:**

Link description text is selected.

### Versions

- Mark Text: v0.14.0
- Operating system: Windows 10 1903 (OS build 18362.239)

**Comment by Jocs** [comment]
Thanks for your reporting this issue, this maybe fixed on the 0.15.0-rc.2, you can download it and test.
