### ISSUE TITLE
Command-M keyboard shortcut  not working

### ISSUE THREAD

**Issue by liziqiang** [marktext/marktext#1208]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open MarkText
2. Press Command-M

**Expected behavior:**

The MarkText minimized to the Dock

**Actual behavior:**

Nothing happens

**Link to an example: [optional]**

### Versions

- Mark Text: v0.15.0-rc.2
- Operating system: macOS Mojave 10.14.6

**Comment by fxha** [comment]
@Jocs @liziqiang `Cmd+M` for minimizing is deprecated due math shortcut. Please see [here](https://github.com/marktext/marktext/blob/669918bda2c0d0784c06e7dffec56f9848344ba4/src/main/keyboard/shortcutHandler.js#L94). We would need to remap the math shortcut.
