### ISSUE TITLE
Font size settings for titles

### ISSUE THREAD

**Issue by adrienbeau** [marktext/marktext#1224]
### Feature request description

Currently (version 0.15.0-rc.3), Mark Text has font size settings for the editor text and code block text. However these settings do not affect the title font sizes in any way. In particular, using a smaller size results in titles that look awfully big.

It should be possible to set the title sizes. Having separate settings for each title level might be too much, but deriving the various sizes from one master setting would be nice.

Alternatively, there could be a "zoom" setting for the whole editor, which would affect all font sizes proportionately.

### What problem does this feature solve?

The title sizes are not harmonious compared to the body text size.

**Comment by fxha** [comment]
Thanks for reporting this issue. Indeed this need an improvement and the font size should affect all text content or the user should be able to control the different text sizes. You can find a zoom in/out under the `View` menu - but currently broken due an upstream issue.

**Comment by HemaKanakamedala** [comment]
I have found a solution for this and it worked. Can i be a part of this?

**Comment by Jocs** [comment]
>I have found a solution for this and it worked. Can i be a part of this?

Can you explain your solution here first?

**Comment by fxha** [comment]
@HemaKanakamedala @Jocs I guess we could use heading font sizes in `em` to automatically adjust to the default font size.

**Comment by HemaKanakamedala** [comment]
Yes @fxha . I have done the same thing. I have calculated the corresponding px size into em. That helped for the resizing of titles and headings also

**Comment by Jocs** [comment]
> I guess we could use heading font sizes in em to automatically adjust to the default font size.

Yes, that's a good solution, so we only to set the font size at the root element of editor.

**Comment by renehummen** [comment]
Mark Text is a great editor to handle my To-Do lists. Just the default font sizes are a bit too large for my purposes and when trying to decrease the font size via the preferences, I stumbled across the same issue. I am currently on Mark Text v0.16.0-rc.2.

@HemaKanakamedala Did you already make a PR for this issue as you seem to have figured out an appropriate solution?
