### ISSUE TITLE
Some menu entries doesn't work as expected

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1225]
### Description

On our latest development branch and release candidates some features like zoom in/out seem not to work as expected due an upstream Electron [issue](https://github.com/electron/electron/issues/18745). This issue tracks the upstream issue.

**Confirmed menu entires:**

- `zoomIn`
- `zoomOut`

### Versions

- Mark Text: development branch and v0.15.x releases
- Operating system: Linux, Window (maybe macOS)

**Comment by Jocs** [comment]
On the macOS system, this feature seems to have no effect from implementation to the present.

**Comment by fxha** [comment]
Window zooming has been disabled in v0.15.0 due the upstream issue.
