### ISSUE TITLE
Changes in Source Code Mode get lost sometimes

### ISSUE THREAD

**Issue by adrienbeau** [marktext/marktext#1226]
### Description

Sometimes (several times today), the application is in such a state that changes in Source Code Mode are lost when switching back to normal mode.

- [ ] Can you reproduce the issue?

### Steps to reproduce

The issue is hard to reproduce reliably. However, I have been able to trigger it several times today.

1. Trigger the issue (maybe by opening the Preferences, I'm not sure)
2. Switch to Source Code Mode
3. Edit the text
4. Switch back to normal mode

**Expected behavior:**

What I changed in Source Code Mode is reflected in normal mode.

**Actual behavior:**

My changes are lost!

**Link to an example:**

In the recording below, you can see me enter Source Code Mode, delete the "Here we go" line, and switch back to normal mode, at which point the line reappears.

![Animation showing a "Here we go" reappearing after I deleted it in Source Code Mode](https://i.imgur.com/HqAFfcn.gif)

### Versions

- Mark Text: 0.15.0-rc.3
- Operating system: Windows 7 Professional SP1 64-bits French

**Comment by fxha** [comment]
I guess I missed something when fixing this/similar issues like this (PR #881).
