### ISSUE TITLE
SUID sandbox issue on Linux

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1236]
### Description

Mark Text may not launch on Linux distros due the fact that Chromium's sandbox cannot be started on versions `>=0.15.0`. This can bypassed via `--no-sandbox` command-line flag that disable the sandbox. Currently we don't use the sandbox on the rendering process so we may safely disable the sandbox but the GPU process is also sandboxed. Disabling the sandbox in general is not a good idea but Mark Text is a desktop application where you shouldn't be able to load web resources, it should be ok and the rendering process is not sandboxed too.

> Electron v5 enabled mixed-mode sandboxing (i.e. some processes being sandboxed and others not) on Linux. This doesn't change whether your renderer processes are sandboxed by default, but it does mean that the GPU process is now sandboxed.

This issue affect user:

1. without kernel namespaces feature support and
2. if `chrome-sandbox` has no SUID flag or isn't owned by `root`.

Furthermore this affect the Flatpak package because it's a sandboxed applications without direct kernel access.

**References:**

- [Electron issue](https://github.com/electron/electron/issues/17972)

### Versions

- Mark Text: `develop` branch / >=v0.15.0(rc)
- Operating system: Linux

**Comment by fxha** [comment]
Please follow the steps above if this issue occur or feel free to comment on this issue.

**Comment by zoof** [comment]
It is not obvious what you mean by "follow the steps above".  I am running Debian Stretch and
```
$ ls -l /usr/lib/chromium/chrome-sandbox
-rwsr-xr-x 1 root root 18776 Mar 26 19:43 /usr/lib/chromium/chrome-sandbox
```
Is this a kernel issue?

**Comment by zoof** [comment]
Never mind.
```
echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/00-local-userns.conf
service procps restart
```
fixed the issue.

**Comment by fxha** [comment]
To clarify this problem, there are three options to fix/bypass this:

- Enable user namespaces if possible: `sudo sysctl kernel.unprivileged_userns_clone=1`
- `sudo chown root <path_to_marktext_dir>/chrome-sandbox && sudo chmod 4755 <path_to_marktext_dir>/chrome-sandbox`
- Launch Mark Text with `--no-sandbox`
