### ISSUE TITLE
Horizontal line with more than three "-"  is not displayed correctly

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#124]
### Description

.

`---<enter>` works

### Steps to reproduce

1. `----<enter>`

**Expected behavior:** [What you expected to happen]

HTML horizontal line

**Actual behavior:** [What actually happened]

```
----
```
### Versions

- Mark Text: 0.9.25 / master

**Comment by Jocs** [comment]
@fxha fixed but not perfect.

**Comment by Jocs** [comment]
@fxha now strictly follow GFM.
