### ISSUE TITLE
Table creator refuses to create table with 1 column

### ISSUE THREAD

**Issue by flokno** [marktext/marktext#1243]
### Description

When I use the table creator to create a table with **1** column, I get 2 columns.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Create table block
2. Choose 1 column

**Expected behavior:**

Get 1 column

**Actual behavior:**
I get 2 columns

### Versions

- Mark Text:
Ref: app/com.github.marktext.marktext/x86_64/stable
ID: com.github.marktext.marktext
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2019-07-01 21:27:25 +0000
Subject: fix native KDE titlebar issue due system permissions (#6) (b7f231c0)
Commit: 0576f3d3b2d1a9d46ac65a185797bfc827ea09a0fd444937194cce07e213f5d3
Parent: 80e175103e34f225010761520db71b762e1f0dc3f0a1e47a6502cfb64215afe4
Location: /var/lib/flatpak/app/com.github.marktext.marktext/x86_64/stable/0576f3d3b2d1a9d46ac65a185797bfc827ea09a0fd444937194cce07e213f5d3
Installed size: 274,2 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08

- Operating system:
Linux Mint 18.3 KDE

**Comment by fxha** [comment]
I don't really know whether this is a bug or not because the minimum row/column count is `2`. Meaning a 2x2 table is the minimum size that we support. Are there any reasons to allow 1x2/2x1 tables?

**Comment by flokno** [comment]
I wanted to create a list of things and used `table` for that. I don't see a real problem why 2x1/1x2 tables shouldn't be supported, since it's valid Markdown. Also, eventually Marktext is perfectly able to render e.g.

| test |
| ---- |
| a    |
| b    |


In any case: Being able to choose 2x1 in the table creator and then getting 2x2 is probably not a desired behavior.
