### ISSUE TITLE
opening marktext with file_name from command line does not working

### ISSUE THREAD

**Issue by menghuu** [marktext/marktext#1244]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. run command in iterm2 

`/Applications/Mark\ Text.app/Contents/MacOS/Mark\ Text README.md`

**Expected behavior:**

open window with README.md

**Actual behavior:**

empty file

### Versions

- Mark Text: 0.14.0
- Operating system: macOS

**Comment by menghuu** [comment]
the warning raised when run the command line

> 2019-08-07 10:35:32.903 Mark Text[32194:7332250] *** WARNING: Textured window <AtomNSWindow: 0x7fcbbb924d00> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

it may be helpful

**Comment by adrienbeau** [comment]
I could not reproduce this issue under Linux and the recently released Mark Text 0.15.0. I tried a filename without spaces and a filename with spaces. Both opened just fine.

More accurately my command lines were :

* `./marktext-0.15.0-x86_64.AppImage ~/Documents/test.md`
* `./marktext-0.15.0-x86_64.AppImage ~/Documents/Test\ with\ spaces.md`

**Comment by fxha** [comment]
@Jocs Can you please verify this issue. Maybe related to #1171?

@menghuu Is it possible to share the readme file to try to reproduce this issue?

**Comment by Jocs** [comment]
@menghuu @fxha Yes, I also can not open the file, it just start up Mark Text, but did not open the file with special path.

**Comment by fxha** [comment]
I guess this is macOS only, so [here](https://github.com/marktext/marktext/blob/04480e08ae8987b50cd17e08844f742ca40635f7/src/main/app/index.js#L210) may a good start to find the issue.

**Comment by menghuu** [comment]
Hi, here is the full command i try to open a file from terminal

```bash
(base) m @ humengdeMacBook-Pro /tmp $
: echo test document >> README.md
(base) m @ humengdeMacBook-Pro /tmp $
: /Applications/Mark\ Text.app/Contents/MacOS/Mark\ Text /tmp/README.md
2019-08-21 14:52:23.241 Mark Text[96903:2730408] *** WARNING: Textured window <AtomNSWindow: 0x7f9767308f00> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
(base) m @ humengdeMacBook-Pro /tmp $
: '/Applications/Mark Text.app/Contents/MacOS/Mark Text' /tmp/README.md
2019-08-21 14:53:24.669 Mark Text[97287:2732669] *** WARNING: Textured window <AtomNSWindow: 0x7fe680401590> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

it open with an empty file
