### ISSUE TITLE
GitHub image uploader cannot be set as default uploader

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1247]
### Description

The GitHub image uploader cannot be set as default uploader.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open settings and navigate to *Image Uploader*
2. Select GitHub and type some text in all three textboxes
3. Agree to terms and set as default uploader

**Expected behavior:**

GitHub should be selected as default uploader.

**Actual behavior:**

A notification is shown that the uploader is successfully set but the uploader text don't change and after closing and reopen the settings window the GitHub uploader is no longer set as default uploader - GitHub as never set as default uploader on disk.

### Versions

- Mark Text: v0.15.0
- Operating system: Linux (I guess all OSs)

**Comment by Jocs** [comment]
@fxha You also need to change to `image` tab in setting window, and select `upload image to cloud by image uploader`?

**Comment by fxha** [comment]
Yes, but that's not the problem. I cannot select GitHub uploader because the selection is never saved on disk and also not changed in GUI.

**Comment by Jocs** [comment]
@fxha Did you press the save button?

**Comment by Jocs** [comment]
If the user has to save before setting default, it doesn't feel like a good user experience. When the user clicks on the default uploader, we can save the setting before set as default uploader.

**Comment by fxha** [comment]
@Jocs I don't looked into this issue because I don't use any uploader. Here is an example:

![mt_github_uploader](https://user-images.githubusercontent.com/22716132/65840551-d7c24a00-e31a-11e9-9e7e-db75cfec0c6c.gif)

**Comment by fxha** [comment]
@Jocs This issue was not fixed by the linked PR.

**Comment by Jocs** [comment]
@fxha Do you want that set the uploader to github when you press `save` button? but `save` button only save the config, do not set it as default uploader.

**Comment by Jocs** [comment]
@fxha Do you think we need to combine the two buttons into one button, which have both functions save config and set as default config?
