### ISSUE TITLE
Sometimes the table of contents is not cleared after the document is closed

### ISSUE THREAD

**Issue by adrienbeau** [marktext/marktext#1249]
### Description

When the user closes a modified file, after getting a prompt about saving the file, the table of contents in the side bar is not erased. When closing a file that was not modified (not popup dialog box), the table of contents in the side bar is properly reinitialized.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Have a folder opened in the side bar
2. Open a Markdown file, make some changes
3. Close the tab, **save** or **don't save** the changes when prompted (what matter is you get a dialog box)
4. Display the table of contents in the side bar (H icon)

**Expected behavior:**

The side bar (table of contents) is empty.

**Actual behavior:**

The side bar still contains the table of contents of the closed document.

### Versions

- Mark Text: 0.15.0
- Operating system: Linux (up-to-date KDE neon 18.04)

**Comment by Jocs** [comment]
@fxha Can you reproduce this issue? I remember this issue already fixed, and I can not reproduce it.

**Comment by fxha** [comment]
Yes, I can reproduce this issue. I guess the fixed one was a similar issue.

**Comment by DutchPete** [comment]
I also have it with Mark Text 0.15.0 on Linux Mint 19.2.
