### ISSUE TITLE
Insert spaces when tab key is pressed

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#125]
PR #119 disabled tab focus, but does not insert a tab/spaces into document because if you insert a tab or multiple spaces, it will get converted into one space. So we have to find a way to resolve the problem.

Maybe use something like this:

```html
<span class="cm-tab" role="presentation" cm-text="	">  </span>
```

[Code template](https://github.com/marktext/marktext/blob/581afdca56ca1d56b2f8450380ff82a8c834412a/src/editor/contentState/tabCtrl.js#L67)

**Comment by Jocs** [comment]
>if you insert a tab or multiple spaces, it will get converted into one space.

Do you find the reason why it will convert multiple spaces to one space? I think this is the key point to this issue.

**Comment by Jocs** [comment]
@fxha 

```diff
.ag-line {
  display: block;
+  white-space: pre-wrap;
}
```
