### ISSUE TITLE
HTML image failures

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#126]
### Problem 1

1. Go into source code mode and insert
   ```
   <img src="https://raw.githubusercontent.com/marktext/marktext/master/static/logo-small.png" >

   foo
   ```
2. exit source code mode and select image

**Expected behavior:**  [What you expected to happen]

HTML code box as in the second image below

**Actual behavior:** [What actually happened]

![mt_img_bug_0](https://user-images.githubusercontent.com/22716132/38509660-db01ff08-3c22-11e8-9996-0dd2b37a0a29.png)

### Problem 2

1. Go into source code mode and insert
   ```
   <IMG src="https://raw.githubusercontent.com/marktext/marktext/master/static/logo-small.png" >

   foo
   ```
2. exit source code mode and select image

**Expected behavior:**  [What you expected to happen]

no exception

**Actual behavior:** [What actually happened]

![mt_img_bug_1](https://user-images.githubusercontent.com/22716132/38509685-ecaf87fc-3c22-11e8-8c9c-f34ab79268b8.png)

### Versions

- Mark Text: master (b71e11c)
- OS: Linux

**Comment by Jocs** [comment]
I think `problem 1` is not a serious bug, just treat it as raw html.

and `Problem 2` what's wrong with it? `IMG` is not a validated HTML tag name ?

[tag name](https://github.github.com/gfm/#tag-name)

**Comment by fxha** [comment]
> A tag name consists of an ASCII letter followed by zero or more ASCII letters, digits, or hyphens (-).

So `img`, `IMG` and so on is a valid tag name.  HTML is case insensitive or not?

**Comment by Jocs** [comment]
@fxha I think the issue's problem 2 is also solved after add [DOMPurity](https://github.com/cure53/DOMPurify) ?
