### ISSUE TITLE
File Changed on Disk at every save when file is in OneDrive

### ISSUE THREAD

**Issue by gaetanww** [marktext/marktext#1261]
### Description

- [x] Can you reproduce the issue? yes

### Steps to reproduce

1. Create a md file in OneDrive or Sharepoint folder
2. Write some text
3. Save (Ctrl + S)
4. Martext sends following message:
File Changed on Disk
1-N Attestation Protocol.md has been changed on disk, do you want to reload it?
5. If you click on it right away, nothing happens, if you click on it after doing some changes it will reset back to when the file was saved (lost work).

**Expected behavior:**

When saving, MarkText shouldn't say that the file has been changed on disk.

**Actual behavior:**

MarkText says that the file has been change on disk and will delete some content if you click on the popup later.

### Versions

- Mark Text: 0.15.0 & 0.14.0
- Operating system: Win10

**Comment by fxha** [comment]
Could you please set `watcherUsePolling` to `true` in `preference.json` located in the Mark Text's [data directory](https://github.com/marktext/marktext/blob/develop/docs/APPLICATION_DATA_DIRECTORY.md) and try again. I think the default watcher doesn't support network drives.

> 5\. [...] if you click on it after doing some changes it will reset back to when the file was saved (lost work).

Yes that's true and need an improvement like an time stamp to not load the outdated document from disk if the user makes an change or forbid to save if the file on disk is newer. This is tracked in #1035 and you may want to subscribe there for further updates.

**Comment by gaetanww** [comment]
setting `watcherUsePolling` to true in `preference.md` fixed the issue. Thank you very much!

**Comment by phisad** [comment]
> Setting `watcherUsePolling` to true in `preference.md` fixed the issue. Thank you very much!

This solved the problem for me on GoogleDrive as well. Thanks!

**Comment by Gez0377** [comment]
I also met this problem in v0.16.3, and the method works.

**Comment by PeterKDunn** [comment]
I am having problems with this same issue (version 0.17.1). My files are stored on [pCloud](https://www.pcloud.com/). 

As suggested above by others, I changed the file `preference.json` (located in Mark Text's [data directory](https://github.com/marktext/marktext/blob/develop/docs/APPLICATION_DATA_DIRECTORY.md)), so that `watcherUsePolling` is set to `true`.

However, this **did not work** for me (the same issue arises) **until I restarted by Mac**. It now seems to be working fine.
