### ISSUE TITLE
Copying code in code blocks will lose indentation

### ISSUE THREAD

**Issue by deathrush** [marktext/marktext#1264]
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

markdown file content:

```bash
cd /opt/ansible/
cat > test.yml <<EOF
- hosts: top_rank
  roles:
    - game
  tasks:
    - debug:
        msg: "{{ hostvars[inventory]['ansible_default_ipv4']['address'] }}:{{ global_usc.server_port }}"

EOF

```

Copy the codes above in Mark Text code block to VS Code.

**Expected behavior:**

Indentation retention

**Actual behavior:**

Indentation lost

### Versions

- Mark Text: 0.15.0
- Operating system: Windows 7

**Comment by Jocs** [comment]
能描述具体一点吗？从marktext 复制到其他地方？还是其他地方复制到 marktext？

**Comment by deathrush** [comment]
从marktext 复制到其他地方

**Comment by fxha** [comment]
@Jocs  Duplicate of #942?

**Comment by Jocs** [comment]
Duplicate of #942, and be closed.
