### ISSUE TITLE
The last empty in code block disappear

### ISSUE THREAD

**Issue by deathrush** [marktext/marktext#1265]
### Versions

Step 1: write test file bellow:

```md
### test file

\```js
const a = 'b'

\```

there is an empty after `const a = 'b'`
```

Step 2: change to source code mode and change back.

Expect

Last blank line is reserved

Actually

The last line disappear

- Mark Text: 0.15.0
- Operating system: Windows 7

**Comment by Jocs** [comment]
@deathrush 为什么需要保留一个空行呢？

**Comment by deathrush** [comment]
因为代码快里就有这个空行
