### ISSUE TITLE
Middle-click on a tab should close the tab

### ISSUE THREAD

**Issue by adrienbeau** [marktext/marktext#1266]
### Describe your feature request

It would be nice to support the standard "middle-clic" shortcut on tabs, which closes the tab. All browsers (and many other programs) support that.

**Comment by Jocs** [comment]
@adrienbeau Click what? the middle button on a mouse device?

**Comment by adrienbeau** [comment]
Yes, a mouse middle-click. On most modern mice, you can press the scroll wheel, it also acts as a button.

**Comment by Jocs** [comment]
I never use mouse, So someone can help with this feature?
