### ISSUE TITLE
New check list items are already checked

### ISSUE THREAD

**Issue by adrienbeau** [marktext/marktext#1267]
Mark Text supports the `- [ ]` syntax for check lists. When pressing Enter to create a new item in the list, it creates an item of the same type. If the item was checked, the new item is also checked. This is an unexpected behavior for a check list. Users expect new item to be unchecked, so they can check them at a later time.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Create a check list
2. Check some items
3. Position your cursor at the end of a checked item
4. Press the Enter key

**Expected behavior:**

I expect a new *unchecked* item is created.

**Actual behavior:**

A new *checked* item is created.

### Versions

- Mark Text: 0.15.0
- Operating system: Windows 7

**Comment by Jocs** [comment]
In fact, I am not sure which way users prefer, so we can wait for more users to participate in the discussion of this issue.

**Comment by stefnotch** [comment]
I personally usually add new items to existing lists whenever something *new* comes up.
So, I suppose I'd prefer it if they always were unchecked.

**Comment by DutchPete** [comment]
I agree with Adrien that & Stefnotch the new item should be unchecked.

Another issue here is that when an item is checked all the text following it is struck through, which, in my opinion, should also be for the user to decide rather than be a default setting that cannot even be changed.

My OS: Linux Mint 19.2 XFCE

**Comment by Jocs** [comment]
@DutchPete Do you have better way to indicate it checked, and not use struck through.

**Comment by DutchPete** [comment]
> @DutchPete Do you have better way to indicate it checked, and not use struck through.
>
To have an item checked is sufficient to indicate that it is done/terminated, it normally does not need to be struck through. Nevertheless, if a user wants to see an item that's done, i.e. finished, to be checked and struck through, then for the text after the text box he can use standard markdown syntax to do it manually.

**Comment by stefnotch** [comment]
For what's it worth, I quite like that checked items are struck through. 
Possible alternatives:
- Black text changes to grey text when checked
- Transparent/grey strike through

**Comment by DutchPete** [comment]
> For what's it worth, I quite like that checked items are struck through.
>
I understand that, and there will be others who are of that opinion. But is that a reason to impose the strike-through on users who don't want it?

When a check box is open, it is the user's choice whether to put a check mark in it or not. Similarly, the user should have the choice of whether the text next to the check box should be struck through or not.

As it stands currently, the user does not have that choice: the text is automatically struck through by default, without even so much as giving the user the possibility to undo that. IMHO, that is not user-friendly. The user should not even have to opt out: the user should opt in, i.e. choose, if strike-though is required.
