### ISSUE TITLE
Support for [TOC] generation

### ISSUE THREAD

**Issue by Dorian-DS** [marktext/marktext#1269]
Being able to use the [TOC] text to automatically generate a table of contents based on headers should be a feature available with Marktext.

Many other markdown editors support this, and so many documents are written with this tag.  While Marktext may have it's own sidebar TOC menu, this is outside of the document and seems messy and like an add-on.

Without this feature, the author isn't presenting their clean document as they intended.

**Comment by fxha** [comment]
Thanks @Dorian-DS, this was discussed in #80 and we'll support TOC only when exporting as HTML/PDF but not in the editor - at least in the near future. Please subscribe there for further updates.
