### ISSUE TITLE
Raw HTML js security issues

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#127]
### Description

You can load javascript into editor and bypass parser with some simple methods. Mark Text is not a "security" app, but I think it's better to protect the user against this.

The following issues affect only master branch and **not v0.9.25**.

`foo` is only used to skip problems with the cursor.

```
<script>alert('XSS')

foo
```

```
<script foo>alert('XSS')<script>

foo
```

```
<meta http-equiv="refresh" content="0; url=http://google.com;">

foo
```

output:

```
Electron Security Warning (Disabled webSecurity) This renderer process has "webSecurity" disabled. This exposes users of this app to severe security risks.

For more information and help, consult https://electronjs.org/docs/tutorial/security.
```

```
<svg width="400" height="100">
  <script>alert('xss')</script>
  <rect width="400" height="100" style="fill:rgb(0,0,0)" />
</svg> 

foo
```

```
<svg width="400" height="100">
  <script>
    const __win = window.open("https://google.com"); 
    __win.location = "javascript:alert('XSS')"; 
  </script>
  <rect width="400" height="100" style="fill:rgb(0,0,0)" />
</svg> 
```

The following does not work, but get loaded into editor

```
<p onload="alert('XSS')">asd</p>

foo
```

### Versions

- Mark Text: master (205cce0)

**Comment by Jocs** [comment]
@fxha Do you have any idea for solving this problem?

**Comment by fxha** [comment]
Atom uses [DOMPurify](https://github.com/cure53/DOMPurify) against XSS. DOMPurify seems to be fine and should be easy to integrate, but I don't know about performance.

**Comment by Jocs** [comment]
@fxha I'll create a PR, great thanks for informing DOMPurify to me.

**Comment by fxha** [comment]
I'll close this because it seems to be fixed and isn't affecting v0.9.25.

**Comment by fxha** [comment]
I found another issue. I think PR #132 is the source.

Insert following text into editor/source code mode (and exit source code mode). Press 4x (multiple times) backspace and then many exceptions.

```
<script foo>alert('XSS')</script>

foo
```

![mt_bug_00](https://user-images.githubusercontent.com/22716132/38630850-5f34d778-3db8-11e8-8e8d-b674ad804fe4.gif)

**Comment by Jocs** [comment]
@fxha Can you open another issue about the bug you described above?
