### ISSUE TITLE
[SOLVED] Exporting a document

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1270]
### Description

 Export to HTML or PDF does not work.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Click on File
2. Click on Export
3. Click on either HTML or PDF

**Expected behavior:**
To get a dialogue box asking where one wants the HTML or PDF version saved, and, after selecting either of the 2, to then have that version available.

**Actual behavior:**

 Nothing happened after clicking on PDf or clicking on HTML.

### Versions

- Mark Text: 0.15.0
- Operating system: Linux Mint 19.2 XFCE

**Comment by fxha** [comment]
Thank you for taking the time to report this issue! Can you reproduce this issue with a simple markdown document because we cannot reproduce this issue (at least on GNOME)?

**Comment by DutchPete** [comment]
> Thank you for taking the time to report this issue! Can you reproduce this issue with a simple markdown document because we cannot reproduce this issue (at least on GNOME)?

OK, I tried a small document of 116 words & just text, and indeed it works. But with a document that contains 356 words of text, an embedded image, and a table, it does not work. Are there set rules for export size & content of documents?

**Comment by fxha** [comment]
It should always work but perhaps there is an error while parsing and the action is aborted due this exception. You could take a look at the log files (located in the [application data folder](https://github.com/marktext/marktext/blob/develop/docs/APPLICATION_DATA_DIRECTORY.md) `logs/<year><month>/{main.log,editor-<number>.log}`) or try to reduce the issue on a text area (or email us the markdown document if possible).

**Comment by DutchPete** [comment]
> It should always work
>
That's good to know :-)

> You could take a look at the log files (located in the [application data folder](https://github.com/marktext/marktext/blob/develop/docs/APPLICATION_DATA_DIRECTORY.md) `logs/<year><month>/{main.log,editor-<number>.log}`)
>
I did, there is only 1 line in it:
> [2019-08-16 15:22:14.702] [error] The renderer process has crashed unexpected or is killed (true).
>
which was due to a freeze as per #1273.
>
What do you mean by:
> try to reduce the issue on a text area

**Comment by fxha** [comment]
> What do you mean by:

> >    try to reduce the issue on a text area

We need some text to reproduce this issue and identify the problem. It would be awesome if you can try to identify the problem by removing paragraphs or lines and give us a minimal example how to reproduce this issue. I guess it's some line in your markdown document that causes the problem.

**Comment by Jocs** [comment]
@DutchPete Can you send you markdown file to us or just paste it here?

**Comment by DutchPete** [comment]
I believe I have found the problem: the document that I cannot export has a YAML box at the top. I tried another document with 700 words of text and hyperlinks, no YAML matter, and export went fine.

**Comment by DutchPete** [comment]
2019-09-25 update: a document with a YAML box at the top can also be exported to PDF, and the YAML box does not show up in the PDF, which is correct.
This issue is solved.
