### ISSUE TITLE
Regression: paste LibreOffice Calc/Excel table as HTML table to Mark Text

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1271]
### Describe your feature request

 A table copied in Calc that is then pasted into Mark Text is embedded as an image. The request is to have the possibility to paste it as a real table that can be edited/amended in MT, rather than an embedded image as it is now.

### What problem does this feature solve? [optional]

 This means the table can be amended to suit the document it is pasted into, including adding data to the table after pasting.

**Comment by fxha** [comment]
This is a regression in v0.15.0 and needs further investigation.

**Comment by Jocs** [comment]
@DutchPete What's `Calc `?

**Comment by DutchPete** [comment]
> @DutchPete What's `Calc `?
>
Calc is the spreadsheet app that is part of the LibreOffice suite. Calc is the equivalent of Excel.

**Comment by fxha** [comment]
Please pay attention to #1329 when fixing this issue.
