### ISSUE TITLE
Create new file in same folder

### ISSUE THREAD

**Issue by AamerShareef** [marktext/marktext#1278]
### Question description
How do I create a new file in same folder via keyboard shortcut?

### Example
I have a directory called `dummy` in my home/notes folder. The folder has a `test.md` file.
I start marktext with the folder. `marktext dummy`
I click on test.md from the side bar. 

I enter CTL+N - A new tab opens.
I enter CTRL+S - A prompt to save file opens up - but the folder displayed is not the current folder `dummy`

Is there a way I can create a file in my current working directory by a keyboard command such as CTRL+N ?

Thank you!

**Comment by Jocs** [comment]
It seems a bug that we can not create a file in the working directory by click or shortcut too. I think right click on the folder name in the sidebar and show a new file/new folder menu will solve this problem, I am still not sure whether it's necessary to add an shortcut, because we still need to create new file in the subfolder.

**Comment by Jocs** [comment]
I can even not create new file in the subfolder by right click seems another bug, However, in the next version, we will optimize the sidebar as a whole, including lazy loading, which should solve these problems together.

**Comment by AamerShareef** [comment]
Thanks ! :+1:

**Comment by fxha** [comment]
@Jocs We could set the working directory from the file dialog to the opened root directory to solve this problem.

**Comment by Jocs** [comment]
>We could set the working directory from the file dialog to the opened root directory to solve this problem.

@fxha Sorry, I didn't get you point, can you explain more detail?

**Comment by fxha** [comment]
We could set the dialogs `defaultPath` property to the absolute root directory that is currently opened in Mark Text, so that the dialog default location is the Mark Text root directory.

**Comment by Jocs** [comment]
@We didn't have a `new file` shortcut? maybe it's necessary to add one.

**Comment by joshchristiane** [comment]
Still doesn't have this feature. Seems like a huge deal missing this... It's a LOT slower to manually save an MD file where you want it on disk, name it in Windows, then open it in MarkText. It'd be a lot easier if each file/directory had a right click "new file" option every time you wanted to create a new note. It prompts you to do this and works perfectly in an empty directory, but as soon as it has a note in it the function no longer displays whatsoever. Being able to just quickly click "new note" and name it just seems really useful, hopefully you guys can add it!

**Comment by joshchristiane** [comment]
This feature is now added, but for those curious who can't seem to find it, you need to have two file directories open and in your main file directory in order for it to work, if you only have one file director open or available in the left panel then right click "create new file" won't show up. This confused me at first but now it makes perfect sense.
