### ISSUE TITLE
Move image to file's path (current folder)

### ISSUE THREAD

**Issue by HannanAkbar** [marktext/marktext#1279]
Move image to the folder of opened file and if the file is unsaved then move to a special folder.

Very useful if you like to keep your notes and attachments in the same directory. Easily sync the complete notes folder to a network drive or any cloud storage.

![DeepinScreenshot_dde-desktop_20190817034648](https://user-images.githubusercontent.com/5216873/63202111-b0ccf300-c0a1-11e9-8803-de904b331e5a.png)

**Comment by Jocs** [comment]
@HannanAkbar is it similar to #549 ?

**Comment by HannanAkbar** [comment]
Yes :+1:
