### ISSUE TITLE
Mark Text crashed

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1285]
### Description

 MT crashed/stopped working

- [ ] Can you reproduce the issue?  I don't understand how it happens

 this is not related to #1273 because I tried PgUp and PgDn in a 1500 word document - no problems.
I have attached to log files.

### Versions

- Mark Text: 0.15.0
- Operating system: Linux Mint 19.2 XFCE 64-bit
[editor-1.log](https://github.com/marktext/marktext/files/3512776/editor-1.log)
[main.log](https://github.com/marktext/marktext/files/3512777/main.log)

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. We cannot reproduce this issue without steps to reproduce or a description, please provide some steps or how the error occurred. Please don't use <kbd>PageDown</kbd> or <kbd>PageUp</kbd> until #655 is fixed. The only saved error is that you or your system killed Mark Text multiple times.

**Comment by DutchPete** [comment]
@fxha : I try not to use <kbd>PgDn</kbd> or <kbd>PgUp</kbd>, but sometimes I forget :-((
As for this latest crash, I don't know what I did, but MT froze, so I had to terminate all the MT processes with `killall marktext`. And, as you can see from the log files, it happens regularly, which is very annoying, so it is something that needs fixing urgently.

**Comment by fxha** [comment]
We need a way to reproduce the issue otherwise it's hard/impossible to fix the issue.

**Comment by DutchPete** [comment]
@fxha : I understand that. I tried to reproduce it but could not, even by pressing <kbd>PgUp</kbd> or <kbdPgDn</kbd>, it so happened that these keys did not cause it. Nevertheless, a good hour later I pressed the <kbd>PgUp</kbd> accidentally and MT froze again. 

So perhaps those 2 keys are responsible, though not all the time. I think if that key issue gets fixed you'll see many fewer cases.

**Comment by JvilleDev** [comment]
Hi. When i try to mark a large line, this happens

https://github.com/marktext/marktext/assets/90424405/1f1ea8af-15b4-4cab-b0e2-0158cc9e18a5
