### ISSUE TITLE
Arrow down is not work in float box

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#129]
### Description

[Arrow down is not work in float box]

### Steps to reproduce

1. input `\`\`\`java`
2. The languages recommend float box is shown.
3. use arrow down to select language

**Expected behavior:** [What you expected to happen]

The next language bellow the current one will be highlight.

**Actual behavior:** [What actually happened]

Float box disappeared.

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

### Versions

- Mark Text: master
- OS: Mac

**Comment by fxha** [comment]
I tested this in v0.9.25 and it works, but on master I get a warning `j is not a valid language mode!` and box disappears.

```
e.prototype.pre2CodeMirror = function(e) {
[...]
 h = Object(r.a)(o, m), f = o.getAttribute("data-lang"), y;
                "code" === a.functionType && (y = Object(l.b)(o));
                var v = function(i) {
                    var s = i.name;
                    Object(r.i)(h, s).then(function(i) {
                        o.setAttribute("data-lang", i.name),
                        a.lang = i.name.toLowerCase(),
                        y && (y.value = i.name,
                        y.blur()),
                        t.cursor.start.key === a.key && e && (a.pos ? (h.focus(),
                        h.setCursor(a.pos)) : Object(r.h)(h))
                    }).catch(function(e) {
                        console.warn(e) <---------- source
                    })
```

**Comment by Jocs** [comment]
@fxha yeah, it's a newly bug introduced by I added  new feature `add new line between table or code block`.
