### ISSUE TITLE
Incorrect parsing of multiline comments inside `cpp` and `c` language code fences

### ISSUE THREAD

**Issue by ptheod** [marktext/marktext#1294]
### Description

The multiline comments inside code fences of `cpp` or `c` languages are not parsed correctly. Specifically the first line of such comments is correctly greyed out but subsequent lines are colorized like normal code.

### Steps to reproduce

Insert the following text in a blank document:

    ```cpp
    /* return
     * return 
     */
    ```
    return

**Expected behavior:**

The words `return` in lines 2 and 3 should be grey (comment color) and the `return` in the last line should be cyan (the keyword color).

**Actual behavior:**

The `return` in the second line is colorized like the `return` in the last line, i.e. it is parsed as normal C++ code.

### Versions

- Mark Text: 0.15.0  (installed from Flathub)
- Operating system: Clear Linux 30820

**Comment by fxha** [comment]
@Jocs I guess that this is an upstream issue with `prismjs`?

**Comment by Jocs** [comment]
>I guess that this is an upstream issue with prismjs?

@fxha maybe not due to `prismjs`, it's because I highlight cpp codes line by line, not as a whole part.
