### ISSUE TITLE
Linked images are not rendered

### ISSUE THREAD

**Issue by cbertelli** [marktext/marktext#1297]
Linked images do not work as expected. 

See the comparison between Typora and Mark Text:

![Typora and MarkText](https://i.imgur.com/YEHrZlZ.png)

Here is the relevant markdown text:
`````
# MIDDLEWARE CSP-PKCS11 PER LA CIE 3.0 [![Build status]
(https://ci.appveyor.com/api/projects/status/dpc0Oditjn04ylw6y?svg=true)]
(https://ci.appveyor.com/project/italia/cie-middleware)
`````

**Comment by Jocs** [comment]
It's seems that Mark Text can not render this image `![Build status]
(https://ci.appveyor.com/api/projects/status/dpc0Oditjn04ylw6y?svg=true)`, NOT due to it's a link image.
