### ISSUE TITLE
Fallback emoji characters on Windows 10

### ISSUE THREAD

**Issue by iansannar** [marktext/marktext#1299]
### Description
Some emojis from earlier unicode standards display as black-and-white fallback characters instead of their emoji glyphs. The following emoji are the specific ones I am having trouble with (but are not the only ones affected): ❄, ☣, ☠. They render properly in both notepad and chrome.

- [x] Can you reproduce the issue?

### Steps to reproduce
1. Open Mark Text
2. Insert any of the specified emojis above
3. Behold

**Expected behavior:**
Full-color emoji

**Actual behavior:**
Unicode fallback characters

![image](https://user-images.githubusercontent.com/8443754/63818604-f63dbb80-c8fe-11e9-9a7a-f4b78029fd49.png)
*I did not test every single emoji, but the ones originating from older standards seem to be the victims.*

### Versions

- Mark Text: v0.15.0
- Operating system: Windows 10 x64 Version 1903

**Comment by DutchPete** [comment]
@iansannar : the answer to this issue could be dovetailed with my question in issue #1296.
