### ISSUE TITLE
怎么输出成pdf呢？theme怎么切换呢？输入模式怎么切换呢？linux系统  

### ISSUE THREAD

**Issue by taotao7** [marktext/marktext#13]
### Description

[Description of the bug or feature]
快捷键
### Steps to reproduce

快捷键使用

### Versions

- Mark Text:
- OS:linux

**Comment by Jocs** [comment]
@taotao7 因为我暂时没有 Linux 系统，因此在 linux 系统中可能会有一些问题，我会尽快完善 Linux 系统中的功能，也欢迎你直接提交 PRs.

**Comment by lulucca12** [comment]
Can you speak English please
