### ISSUE TITLE
Open recent menu not working on Linux and Windows

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#130]
### Description

According to electron documentation (v2.0.0 beta):

> The following additional roles are available on macOS:
> [...]
> recentDocuments - The submenu is an "Open Recent" menu.
> clearRecentDocuments - Map to the clearRecentDocuments action.

To use this feature we have to implement it ourself, c&p a solution from atom, vscode, etc or disable menu entry `Open Recent` on Linux and Windows.

However taskbar recent documents working on Windows- Linux does not have such a feature.

### Versions

- Mark Text: all
- OS: not macOS

**Comment by Jocs** [comment]
@fxha Can you help implement `open recent` on windows and linux? and `taskbar recent` on windows.

**Comment by fxha** [comment]
Yes, I can. Basically we have to create a (json-)file and insert paths sorted by LRU. I think the core problem will be to insert/update menu entires at runtime.

> taskbar recent on windows

This already works

**Comment by Jocs** [comment]
@fxha waiting for you PR about this issue.:smile:

**Comment by fxha** [comment]
@Jocs Can you assign me and put WIP label on it. When I have some time I'll fix it.

**Comment by fxha** [comment]
#fixed but not released
