### ISSUE TITLE
Tidy markdown 

### ISSUE THREAD

**Issue by pykong** [marktext/marktext#1304]
I really like to see my markdown **prettified**. 
This could either happen on any change or on save.

A common package providing the functionality is:
https://github.com/prettier/prettier

**Comment by Illyism** [comment]
For reference, an example can be found in the [prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOBDAJnATgHSgF4TTDCB9AGQggGsAaCgAkh2YCMAbCMOgZ2YZccZgDMIuALYYY8LMwBUMWgEJF5KAAMdzAFb9CYgK5QwMAJbRmFnLAswAngAoAHgEpmwZiJjHcUMyuzAC+hDpamgAKFjwwAD4Agha4AA6SCagQ-oZQALR58UgFSPElhABSEAAWgQAiEHDxAMoA0gDi8QCMAMw9AByVGFCiAEqN8RUAYq3xPV0ALJp5zCtrqxvrW5ubmgDUzFQW-DCEzAcA7g7VQswA2lwWUHQAuszOAPQqH-wQUnAXap4ODuQgHYYKO7DCAwIG4ZjQOAvTRne7Q2F4BEjF5IZjMapyVJID4fOCuDBSVJcOAAOkgUmYAHIAKLkynU5iWGDUxmaGgiBkWVL8YwMrAQHjw-gOIT-GAMVjQfhwcxwPzw7BC45gJ4Ac2YcEeMBphAAwv4MBwHP5FVBlar1cwZK4LFJjIJcMd3QrlQpna73ZzDVxA5YzLZTDADcaQAwQBBUpYlchQMJcBALlFhAh+MgQBgAG4QWyxkAcXAYPhq5qpSt65AwXDGOBxp7K3AwKIV3UyZBiDBcZVxgyuABCFarMGaFLgRxGfYHQ5Atdw7bzMlwdHFFygpdSntgAHVbLDkP0AAxx-cQZWHiupPP7uDtgtwUsiACOxhScC7GB7GALoOLYgMqUgWA2TYgdKUC6tSACKxgwm+SD9sBcYwJax5YKeSAAEwYRWsR6qafy9igUCIqW7pwAAKpauaoYucAhCEQA).

I think this could be added as a preference.

**Comment by Jocs** [comment]
@pykong is there any syntax error when save the markdown file? So you want to prettify the markdown.

**Comment by retrography** [comment]
Very nice idea. Specially for complex structures like tables.

**Comment by Jocs** [comment]
But Mark Text already do the table beautify when save markdown file.

**Comment by pykong** [comment]
I like to have my whole markdown prettified not just the tables.

**Comment by DutchPete** [comment]
Mark Text is gorgeous as it is.

**Comment by fxha** [comment]
@Jocs I don't really understand the problem here. Mark Text formats all content automatically while saving.

@pykong Are there any issues with it?

**Comment by Jocs** [comment]
@pykong @Illyism @retrography @DutchPete as @fxha already saied, Mark Text will format and generate the markdown content according the GFM and Commonmark Spec, so no need to prettified any more?

**Comment by DutchPete** [comment]
Like I stated 2 comments up, MT is gorgeous and does not need any prettification, IMO.

**Comment by Jocs** [comment]
Closed, if you have any question, feel free to reopen it.

**Comment by pykong** [comment]
@Jocs I have not noticed MarkText doing anything in regard to prettification.
For example, it does not trim excessive blank lines.

**Comment by pykong** [comment]
@Jocs Push.

**Comment by adrienbeau** [comment]
I think there is a misunderstanding here. If I understand correctly:

* **pykong** would like all lines in a Markdown file be automatically reformatted every time a file is saved
* **Jocs** explained that all *new* lines generated by Markdown are pretty-enough

If anything, I have the opposite issue: I would like Mark Text to not reformat any line that I did not edit. Currently, it considers some files as modified as soon as I open them, presumably because of some internal automatic reformatting.

**Comment by DutchPete** [comment]
@adrienbeau : I agree with your last paragraph.

**Comment by Jocs** [comment]
>For example, it does not trim excessive blank lines.
Neither on save or otherwise. I have not seen any option or command to explicitly activate such prettification.

@pykong Can you show me a example markdown file with excessive blank lines after saved by Mark Text, so I can know what's your meaning of `excessive blank lines`.

**Comment by Jocs** [comment]
>If anything, I have the opposite issue: I would like Mark Text to not reformat any line that I did not edit. Currently, it considers some files as modified as soon as I open them, presumably because of some internal automatic reformatting.

@adrienbeau This will be optimized in the future version.

**Comment by Jocs** [comment]
>Jocs explained that all new lines generated by Markdown are pretty-enough

Yes, I think Mark Text saves the files, all the blank lines are needed and necessary. If you think that some blank lines are unnecessary, we can discuss them here.

**Comment by pykong** [comment]
@Jocs 

For example [prettier.io](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdBbAJgHSgYgAIBlCDOQgCTgEMsBLKAcz1PMMlgRkIBtGK0OADo8YqKzIVO8WHwGEYAdwiio6VCAA0ICAAcY9aAGdkoGgCcLEJQAVLCUyhoA3CPSzaQAIws0wANZwMMR6-oxMyDAWAK5wOgAWMBi8AOoJ9PDGYWBwxI6Z9C6ZAJ7I4MamOozGcBYwtn5MGDTIAGY0vLU6AFbGAB4AQn6BwcQ05AAyAu2d3SB9-cQRvHAAijEQ8LNd8SBhFrUW5S0WAVg2UF56FowwqR4wCcgAHAAMOjcQtal+euU3OBHFxwLwAR028Ea+icIBoxgAtFA4HAsKivBY4BD6JjGjRmq0kB1djpahh6FFYntjCt1pDQUS5nsYDRvA8sE9kAAmHTRGj0fjMADCZBa5SgQi8MVqABVWU5ibUAL5KoA)

Would format this...
```md
# Some Heading
Some content line one.



Some content line two.
```

... to that:

```md
# Some Heading

Some content line one.

Some content line two.
```

**Comment by Jocs** [comment]
@pykong I just test, and Mark Text also will format like prettier.io.

**Comment by pykong** [comment]
@Jocs 
If I paste the code example into MarkText it will indeed format like prettier on the fly.

However, if I type the example it will not. Those excessive blank lines will remain.
