### ISSUE TITLE
Debugging Export

### ISSUE THREAD

**Issue by seamyb88** [marktext/marktext#1305]
### As mentioned in another issue, exporting to pdf hangs with no feedback as to the error.

I would like to contribute to the project (it's really good) and this is the issue which I would like to see resolved, so I will try to if you allow it? Perhaps a terminal-type error logger which spits out the latex issues etc.

Full disclosure, I'm a c/python/bash/ruby programmer who's never used js, so I'm talking once I've dabbled a bit in node and electron. 

Thanks!

**Comment by Jocs** [comment]
>I would like to contribute to the project (it's really good) and this is the issue which I would like to see resolved, so I will try to if you allow it? 

First, thanks for you are willing to contribute to Mark Text, yeh, you are welcome to contribute to Mark Text. but which issue you want to solve?

**Comment by Jocs** [comment]
Closed because no more info, feel free to reopen it if you have more question.
