### ISSUE TITLE
vue-devtools not compatible with Electron 2.0

### ISSUE THREAD

**Issue by okcomp** [marktext/marktext#131]
### Description

I'm trying to get marktext up and running on my computer in order to have an understanding of how marktext use `codeMirror`, `snabbdom` and `vue` all together internally. The marktext app was working well, but I got the following error with `npm run dev`. 

```
┏ Electron -------------------

  Unable to install `vue-devtools`: 
   Error: Version of Electron: 2.0.0 does not match required range ^1.2.1 for extension nhdogjmejiglipccpnnnanhbledajbpd
      at Object.install (/Users/peng/Desktop/Pineapple/electron/*marktext/dist/electron/main.js:12606:29)
      at App.<anonymous> (/Users/peng/Desktop/Pineapple/electron/*marktext/dist/electron/main.js:11278:27)
      at emitTwo (events.js:131:20)
      at App.emit (events.js:214:7)
  
┗ ----------------------------
```

My guess is there's conflict with the Electron versions. So I downgrade the Electron version in the `package.json`, re-install npm packages, then vue-devtools was installed without issues. 

So is this something we can fix without downgrading Electron? Or any specific features of Electron marktext is using?

### Steps to reproduce

1. clone repo
2. npm install
3. npm run dev

### Versions

- Mark Text: Latest dev 
- OS: Mac 10.13.2 (17C88)

**Comment by Jocs** [comment]
@okcomp 

According to electron documentation (v2.0.0 beta):

>The following additional roles are available on macOS:
>[...]
>recentDocuments - The submenu is an "Open Recent" menu.
>clearRecentDocuments - Map to the clearRecentDocuments action.

So I think it's `vue-devtools` need to update?

**Comment by fxha** [comment]
PR #133 should fix the issue.

**Comment by okcomp** [comment]
@Jocs Thanks for the quick fix. 

Btw, is there any documentation that explains the architecture of Marktext and how `codeMirror`, `snabbdom` and `vue` work together internally? It's difficult to understand what's under the hood without any architecture-wise documentation. It could be super helpful for many of us.

**Comment by Jocs** [comment]
@okcomp 😄 it's @fxha 's work.

I will rich the documents after v1.0.0 released, maybe, at the beginning of July.
