### ISSUE TITLE
Whether it is "copy" or "copy as markdown", The content in the code block, the newline is invalid.

### ISSUE THREAD

**Issue by xjnotxj** [marktext/marktext#1310]
### Description
 
- [ yes ] Can you reproduce the issue? 

### Steps to reproduce

1. ”ctrl + a“ , select the entire article
2. Whether it is "copy" or "copy as markdown", The content in the code block, the newline is **invalid**.
3. But，in ”source code mode”<br>Whether it is "copy" or "copy as markdown", The content in the code block, the newline is **not invalid**.

> By the way, I want to ask，please. what is the difference between  "copy （ctrl + c）" / "copy as markdown" ? They copied the same content.
 
**Expected behavior:**

```
X-amz-meta-entity: photo 
x-amz-meta-entity-id: 92814
```
 

**Actual behavior:**

```
X-amz-meta-entity: photo x-amz-meta-entity-id: 92814
```

### Versions

- Mark Text:v0.15.0
- Operating system:MacOS 10.14 (18A391)

**Comment by fxha** [comment]
> By the way, I want to ask，please. what is the difference between "copy （ctrl + c）" / "copy as markdown" ? They copied the same content.

- Copy: Set HTML and markdown as pure content
- Copy as markdown: Set markdown as pure content without HTML (e.g. cannot pasted formatted into Word etc)
- Copy as HTML: Set only HTML content
