### ISSUE TITLE
CTRL/CMD+SHIFT+F opens sidebar and focuses on "search in folder"

### ISSUE THREAD

**Issue by Illyism** [marktext/marktext#1311]
### Describe your feature request

- You have CTRL/CMD+F now to start search in the current file
- We could add a keyboard shortcut to search through all files
- When a word or sentence is selected it should pre-fill the search query with the selected text

**Comment by Jocs** [comment]
Another point to note is that if there is no opened folder, this shortcut needs to be disabled and the menu item will be grayed out(disabled).

**Comment by Illyism** [comment]
Also, the search keyword is reset when the *search container* is mounted. I think this should be remembered in vuex / storage.

And the input should get focus and the value should be selected.

**Comment by tongphe** [comment]
I also recommend using ESC to unfocus search box and focus back on file sidebar/tab

**Comment by ianhinder** [comment]
Thanks for implementing.  This would be much more useful if the focus was also transferred to the search box.  As far as I can tell, if I want to search, I hit Cmd-Shift-F, and then have to click in the search box in order to type.  I'd like to do all this from the keyboard.  Should I open a new issue?

**Comment by Jocs** [comment]
>Thanks for implementing. This would be much more useful if the focus was also transferred to the search box. As far as I can tell, if I want to search, I hit Cmd-Shift-F, and then have to click in the search box in order to type. I'd like to do all this from the keyboard. Should I open a new issue?

Please open a new issue about your description, it's a new feature, thanks.
