### ISSUE TITLE
windows 10 failed

### ISSUE THREAD

**Issue by allegrofb** [marktext/marktext#1319]
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text:
- Operating system:

marktext-0.15.0-x64-win.zip

![Untitled](https://user-images.githubusercontent.com/1701019/64146640-4c0aea00-ce50-11e9-9b58-8a818a1ecfc9.png)

**Comment by allegrofb** [comment]
I am wrong, it can run, just open file.

**Comment by allegrofb** [comment]
it's different with home page 'screenshot'

**Comment by Jocs** [comment]
Closed due to inactive, feel free to reopen it if you have more info.
