### ISSUE TITLE
image is missing if change to source code mode

### ISSUE THREAD

**Issue by shlinym** [marktext/marktext#1337]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step] in normal mode, paste an image from clipboard, image show normally.
2. [Second step] after paste, change to source code mode immediately, it show 
```
![loading-ag-70]()
````
3. [and so on...] cancel source code mode, change to normal mode, image missing, 
![image](https://user-images.githubusercontent.com/10113087/64752728-2fa73580-d553-11e9-93c4-41724db02dd6.png)

**Expected behavior:**
image should not miss

**Actual behavior:**
miss

**Link to an example: [optional]**

### Versions

- Mark Text:v0.15.0
- Operating system: mac OS mojave 10.14.4

**Comment by shlinym** [comment]
but if I change to source code mode after a few seconds in second step, image is not missing.

**Comment by shlinym** [comment]
> > but if I change to source code mode after a few seconds in second step, image is not missing.
> 
> Yes, the image maybe is uploading, where do you put your images?

using option:

insert absolute or relative path of image, and I choose a local folder.

**Comment by fxha** [comment]
@Jocs The issue occurs if you use absolute or relative path image settings, insert the image and switch to source code mode immediately. The operation is done asynchrony and never completed because the view is switched before.
