### ISSUE TITLE
linux版无法使用fcitx输入法编写标题行

### ISSUE THREAD

**Issue by inuxor** [marktext/marktext#134]
### Description

搜狗输入法或fcitx输入框架下的其他输入法，在输入标题行即#行时输入条闪烁，且无法上词

### Steps to reproduce

1. 打开空白文档
2. 敲下1到n个#，空格
3. 切换fcitx输入法，试图输入汉字

**Expected behavior:** 正常输入文字，且符合标题行格式

**Actual behavior:** 输入条闪烁，且无法上词

### Versions

- Mark Text: marktext_0.9.25_amd64.snap
- OS:
Ubuntu Bionic Beaver (development branch) x86_64 
Kernel: 4.15.0-13-generic 
DE: KDE
WM: KWin

**Comment by Jocs** [comment]
@inuxor duplicate  #114
