### ISSUE TITLE
Email Link on Website Is Incorrect

### ISSUE THREAD

**Issue by laemongrass** [marktext/marktext#1340]
### The email link is written as **ransixi@gamil.com** instead of **ransixi@gmail.com**.

_What it says on the website:_
![Annotation 2019-09-13 225843](https://user-images.githubusercontent.com/53713662/64864481-89eee600-d67a-11e9-8f2d-a1a7195417b2.png)

**Comment by Jocs** [comment]
@laemongrass Thank you, PR is also welcomed.
