### ISSUE TITLE
Mark Text(v0.15.0) vega-lite Invalid Sequence Codes in win10

### ISSUE THREAD

**Issue by boarenlong** [marktext/marktext#1342]
### Question description

how to use it, thanks

![Mark Text vega-lite Invalid Sequence Codes in win10 with v0 15 0](https://user-images.githubusercontent.com/46042607/64906871-1e5e5480-d71e-11e9-8b8f-eac8345004dc.png)

**Comment by fxha** [comment]
@boarenlong You can find examples and a tutorial [here](https://vega.github.io/vega-lite/).

**Comment by faesjeroen** [comment]
Even when copying the example code, the renderer does not seem to work

![vega](https://user-images.githubusercontent.com/14826686/65967732-67bedb80-e462-11e9-9254-5a035165f697.png)

**Comment by Jocs** [comment]
@faesjeroen What's your Mark Text version number?

**Comment by faesjeroen** [comment]
I've recently downloaded the latest version (0.15.1) for Windows. It works fine when the document is exported to HTML or PDF, but not inline.

**Comment by fxha** [comment]
@Jocs @faesjeroen I can confirm that the given diagram doesn't work work with v0.15.1 but with our develop version.

**Comment by Jocs** [comment]
@fxha @faesjeroen  Yes, I remember that there is a typo error that cause this issue, and already fixed on develop branch, and will release in the next 0.16.0 version.

**Comment by fxha** [comment]
@Jocs  The issue occurs again with latest develop version.
