### ISSUE TITLE
Cannot input Chinese characters.

### ISSUE THREAD

**Issue by roberChen** [marktext/marktext#1353]
### Description

Unable to input Chinese characters but able to show Chinese characters on Ubuntu.
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open the mark text app in Ubuntu 18.04
2. Change into Chinese input method (e.g. Google Pinyin), and type Chinese characters.

**Expected behavior:**

It's expected to show Chinese characters been typed.
**Actual behavior:**

Nothing been input.
(Note. This bug doesn't occur on Windows.)

### Versions

- Mark Text: version v0.15.0
- Operating system:  5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Jocs** [comment]
换一个输入法还是无法输入中文吗？

**Comment by roberChen** [comment]
不能,可能是配置原因,但是不清楚是哪里的配置问题. 还没试过其他输入法框架,目前只用fcitx.

**Comment by roberChen** [comment]
This bug may be related to flatpak. Many other software installed via flatpak occur the same problem( Cannot input Chinese characters).

**Comment by fxha** [comment]
@roberChen Could you please update Mark Text via flatpak and retry. I'm not familiar with input methods but it should work with `fcitx` now.
