### ISSUE TITLE
Option to open files with double click instead of single click

### ISSUE THREAD

**Issue by Pewsplosions** [marktext/marktext#1361]
### Describe your feature request

As of now I do not see this option in the preferences. 

It would be nice to be able to choose to open files via single or double click. Right now it is only single click. It is a small thing but it gets annoying when I double click and instead open the file and the file next to it because my mouse moved slightly.

### What problem does this feature solve? [optional]

It is just a nicety to be able to choose for both styles of workflow.

### Additional context [optional]

I haven't looked at any of the code but it seems like it'd be a pretty simple option to change the click function to look at the option and use single vs double click.

Maybe I'll have time to look around myself but for now I thought I'd add this simple request in case someone wants to look at some 'low hanging fruit' upgrades.

**Comment by Jocs** [comment]
I don't fully understand the problem, you just want to open the file by double-clicking the file?

**Comment by Jocs** [comment]
So what effect do you single click on the file in the sidebar?

**Comment by Pewsplosions** [comment]
The single click is fine as-is. When you click a file in the side bar it opens the file up in the editor section. Or if the file is already opened it changes to that tab.

I'm just suggesting adding a feature in the preferences section to select to change that to require double clicking instead of single clicking.

The preference would allow you to choose between single or double. If it is single it will just work exactly like it is currently working. If you choose double click in this preference option, you will have to double click the file in the sidebar to achieve these same operations.

**Comment by danuluma** [comment]
Now suppose you have that setting, and you have opted for double clicks to open files on the side bar,,,,what should happen if you click on a file just once?

**Comment by Pewsplosions** [comment]
@danuluma Good question. I could see it going a few ways.

1. The easy way would probably be just have single click do nothing at all. Double click or nothing if the setting is on.
2. Another would be single clicking an already open file could still change the tabs on the editor to make that the visible file in the editor. Otherwise still do nothing on single click.
3. A sub-option could exist to further choose one of the above two.

**Comment by fxha** [comment]
Closing this issue as we currently don't plan to implement the feature but we may reopen it on demand.
