### ISSUE TITLE
editor crashed when press `Delete` key

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#1366]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a paragraph with two lines, like bellow:

```md
foo
bar
```

2. Put cursor before `foo`.
3. Press `delete` to delete all the content.
4. Press `backspace` key, the editor crashed.

**Expected behavior:**

The editor does not crashed.

**Actual behavior:**

The editor crashed

**Link to an example: [optional]**

### Versions

- Mark Text: all
- Operating system: all

**Comment by fxha** [comment]
@Jocs I cannot reproduce this issue.

**Comment by Jocs** [comment]
@fxha It's due to `Delete` key did not delete the `soft line break` after delete all the content. there is still one `soft line break` left when you click `backspace`, and it will cause editor crashed.
