### ISSUE TITLE
Change the write width of text in .md document

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1368]
### Question description

 When I export a document to PDF, the width of the text field is good, leaving narrow but acceptable margins on the right and the left of the text.

But in the orginal .md document those margins are a lot wider. Is there a way to adjust the *write width* (as it is known) in the original .md document?

**Comment by DutchPete** [comment]
Wrong app. Apologies. MT exports perfectly.

**Comment by fxha** [comment]
> in the original .md document

What do you mean by original document? The editor? If so, there is a settings option under **Editor** at the bottom "*Defines the maximum editor area width [...]*". You can use pixels (`px`), percentage from the total width (`%`) or characters (`ch`). E.g. `80ch`, `80%` or `1000px`.

**Comment by DutchPete** [comment]
Hi Felix, yes that's what I meant. Thanks for your help and my apologies for the disturbance.
