### ISSUE TITLE
Table of Content: numbering of headers not shown anymore

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1375]
### Description

When I open a document with H1, H2, H3, etc headers the ToC in the sidebar does not show the numbering anymore.
I changed the headers in a document, after which the numbering disappeared. But when I open another, unrelated document with headers, the numbering does not show up either.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a document with headers
2. Change a header from e.g. H1 to H2
3. Save
4. Header numbering has disappeared, but the tree structure is still there
5. Close document
6. Reopen the document
7. Numbering is not back

**Expected behavior:**

 Numbering should adjust automatically, real time, with changes being made.

**Actual behavior:**

 as described in intro

**Link to an example: [optional]**

### Versions

- Mark Text: 0.15
- Operating system: Linux Mint 19.2

**Comment by fxha** [comment]
> in the sidebar does not show the numbering anymore. 

Which numbering do you mean?

**Comment by DutchPete** [comment]
When the sidebar is shown, there is a tree in the sidebar which shows the headers and subheaders.
The 1st H1 header is normally shown in the tree with number 1.
If below that 1st H1 header there is an H2 header, that one is shown and numbered 1.2
If below H2 there is an H3 header, that one is shown and numbered 1.3
And so on.

The next H1 header is shown in the tree with number 2.
If below that 2nd H1 header there is an H2 header, that one is shown and numbered 2.2
And so on.

**Comment by DutchPete** [comment]
@fxha : Am I right to say headers are normally numbered in the sidebar?

**Comment by fxha** [comment]
@DutchPete Headers are currently not numbered, neither in the sidebar nor editor.
