### ISSUE TITLE
Add docs to the Wiki

### ISSUE THREAD

**Issue by yougotwill** [marktext/marktext#1381]
### Describe your feature request

I think it would be useful to add all the files from [docs](https://github.com/marktext/marktext/tree/develop/docs) to the repository Wiki. 

### What problem does this feature solve?

It's quicker for new users to find out information about Mark Text. For example how to have a portable data directory. 

Most people know to check the wiki before making issues so hopefully this will reduce the number of non-development issues made. 

I almost opened an issue to ask for a portable data directory until I stumbled on [PORTABLE.md](https://github.com/marktext/marktext/blob/develop/docs/PORTABLE.md) by luck.

Thanks for reading and keep up the hard work!

**Comment by Jocs** [comment]
is there a way to automatically sync `doc` folder in repo to wiki?

**Comment by fxha** [comment]
@Jocs The wiki is just another git repository but I added a link to our documentation because GitHub wiki is not very good designed.

**Comment by yougotwill** [comment]
Quick and easy solution! Thank you @fxha. Probably not necessary but I did some googling anyway. For the record, you can treat the wiki as a git submodule in the main project. This means you can essentially make the docs folder the repo for the wiki and push all the files. Though I'm not sure if the formatting will be perfect.

See this link. https://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/
