### ISSUE TITLE
can not import html with pandoc installed

### ISSUE THREAD

**Issue by L1cardo** [marktext/marktext#1392]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step] 
drag `html` file into the window

**Expected behavior:**

successfully open `html` file

**Actual behavior:**

can not open `html` file
![截屏2019-09-27下午9 07 24](https://user-images.githubusercontent.com/33802186/65771457-d0f4d500-e16a-11e9-9625-a88850a66dd6.png)
![截屏2019-09-27下午9 08 16](https://user-images.githubusercontent.com/33802186/65771575-17e2ca80-e16b-11e9-9b0a-0e4e5c72c3e7.png)

**Link to an example: [optional]**

### Versions

- Mark Text: v0.15.0
- Operating system: 10.15 Beta(19A573a)

**Comment by fxha** [comment]
Thanks @L1cardo  for reporting this issue. This seems to be a system misconfiguration so Mark Text cannot find pandoc.

- Run `which pandoc` to get the binary location (or macOS equivalent) and
- add the direcotry to your bash profile like this: `[[ -d "$HOME/.cargo/bin" ]] && PATH="$PATH:$HOME/.cargo/bin"`.
- You may need to restart your session.

Afterwards Mark Text should find pandoc.

**Comment by L1cardo** [comment]
I have added the direcotry to my zsh profile, and restarted my macbook, but it did not work
![截屏2019-09-29下午10 51 50](https://user-images.githubusercontent.com/33802186/65834348-94f97580-e30c-11e9-8233-b7687f3638f1.png)
![截屏2019-09-29下午10 52 46](https://user-images.githubusercontent.com/33802186/65834349-988cfc80-e30c-11e9-9efe-e9239bc5b434.png)

**Comment by fxha** [comment]
@Jocs Any ideas?

**Comment by Jocs** [comment]
@L1cardo I also can not reproduce this issue, I just try to import `html` file with the latest version 0.15.1, and it works well, So can yo try the following steps:

1. reinstall pandoc.
2. download the latest version of marktext.

My pandoc version is:

```md
pandoc 2.0.4
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.4.4.1
Default user data directory: /Users/ransixi/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by L1cardo** [comment]
still not working

pandoc version is `2.7.3`

```bash
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: /Users/licardo/.local/share/pandoc or /Users/licardo/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

mark-text version is `v0.15.1`

macOS:  `10.15 Beta(19A578c)`

**Comment by ddhogan** [comment]
I'm having this issue too, in which I can't import any files.  I just get the "Import Warning
Install pandoc before you want to import files." popup.  I'm running the same version of pandoc (`v2.7.3`), it's in my path, and macOS `v10.14.6`.

**Comment by L1cardo** [comment]
Is there any way to fox this ?

**Comment by Jocs** [comment]
@L1cardo We still didn't find the reason, we need some more info.

**Comment by L1cardo** [comment]
What else info do you need from me ？

**Comment by fxha** [comment]
@L1cardo That's actually a good question. Do you/macOS run Mark Text in a sandbox or with restricted privileges? For example the flatpak packages on Linux run inside a sandbox and we have no direct access to the host. Could you please test the following:

1. `command -v pandoc` - the result should point to your pandoc binary like `which pandoc`.

&nbsp;

1. Please set `MARKTEXT_DEBUG` environment variable in your terminal (or OS wide) like `export MARKTEXT_DEBUG=1`.
2. Run Mark Text from the terminal instance where you set the variable (or restart session when set globally): e.g. `~/.bin/marktext_dev/marktext` on my Linux.
3. Is there a menu entry `View -> Toggle Developer Tools`?
4. No --> that's very bad because we have no access to your host system. Try 5\. with `marktext --debug` flag.
5. Yes --> Open Developer Tools and type  (not paste) in console `process.env.PATH` - depending on your OS `PATH` may be lower-case or has a different name on Windows.
6. Press `Enter` and the result should be your `PATH` environment variable. Meaning your pandoc directory should be included.

![mt_dev_console](https://user-images.githubusercontent.com/22716132/67621607-29260200-f811-11e9-9c78-06fbcf223c80.png)

**Comment by L1cardo** [comment]
I think pandoc directory is included, but still not working..... :(
![image](https://user-images.githubusercontent.com/33802186/67621865-9607bf00-f846-11e9-9896-8d963adc6cd5.png)
![image](https://user-images.githubusercontent.com/33802186/67621868-a029bd80-f846-11e9-9de7-15f87a81d74d.png)

**Comment by fxha** [comment]
Unfortunately, I cannot test the issue without macOS but I'll add an environment variable to set the path. Does the dev. tools appear when you set `MARKTEXT_DEBUG=1` in your terminal or environment configuration file like described as above?

**Comment by L1cardo** [comment]
> Unfortunately, I cannot test the issue without macOS but I'll add an environment variable to overwrite the pandoc path. Does the dev. tools appear when you set `MARKTEXT_DEBUG=1` in your terminal or environment configuration file like described as above?

Yes，I did exactly what you said.

**Comment by fxha** [comment]
@L1cardo Could you please try the latest release candidate, set `MARKTEXT_PANDOC` environment variable to the pandoc binary path (`/some/path/pandoc`) and try again?

**Comment by L1cardo** [comment]
I have set the enviroment, but still got the problem
![image](https://user-images.githubusercontent.com/33802186/69737403-48e17a80-116f-11ea-9f54-21c630b4b833.png)

**Comment by fxha** [comment]
This is very strange behavior but mean that Mark Text cannot access or has no permission to `/usr/local/bin/pandoc` because we just execute the binary when `MARKTEXT_PANDOC` is set and exists. Do you know whether applications on macOS are sandboxed (=restricted by the system)? How did you install Mark Text?

Could you please execute `require('fs-extra').statSync('/usr/local/bin/pandoc)` like [here](https://github.com/marktext/marktext/issues/1392#issuecomment-546610479)? It should successfully print the file information, otherwise an error message.

**Comment by L1cardo** [comment]
my mark text version is v0.16.0-rc.2, I donwloaded dmg file from release page and installed it .
![image](https://user-images.githubusercontent.com/33802186/69786853-2e9eaf80-11f6-11ea-94ac-369a021bc9a9.png)

**Comment by fxha** [comment]
@L1cardo My bad, please try again with `require('fs-extra').statSync('/usr/local/bin/pandoc')` (there was a missing `'`).

**Comment by L1cardo** [comment]
![image](https://user-images.githubusercontent.com/33802186/69804341-4fc4c780-1219-11ea-9402-ba98ac40b7dd.png)

**Comment by fxha** [comment]
@Jocs Please inspect the issue on macOS with the DMG.

**Comment by franz-sp** [comment]
Hi everybody!
Thank you for developing MarkText.
I had the same issue: MarkText on MacOs didn't recognise a valid pandoc installation. 
I noticed that MarkText recognises pandoc if I launch it from the command line, i.e., if MarkText is installed in the /Applications folder:
`/Applications/Mark\ Text.app/Contents/MacOS/Mark\ Text`

**Comment by fxha** [comment]
Could you please check whether your `pandoc` binary is a symbolic link, thanks? If so, then #2416 should fix this issue.

`stat $(which pandoc)` should return something like this

```
  File: /usr/bin/pandoc
  Size: 155174680       Blocks: 303088     IO Block: 4096   regular file
                                                           ^^^^^^^^^^^^^^
Device: fd00h/64768d    Inode: 166811      Links: 1
[...]
```

and include either *symbolic link* or *regular file* on the top right.

**Comment by orbanbalage** [comment]
I have the same issue. How can I debug this please?


```
Mark Text
v0.16.3

➜  ~ stat $(which pandoc)
16777222 37166972 lrwxr-xr-x 1 orbanbalage admin 0 32 "Mar  8 17:39:35 2021" "Mar  8 17:39:35 2021" "Mar  8 17:39:35 2021" "Mar  8 17:39:35 2021" 4096 0 0 /usr/local/bin/pandoc
```

**Comment by tamet83** [comment]
Hello,

I'm facing the same issue with my install of Mark Text on my MacBook Air m1.
I installed it with `brew install --cask mark-text`
I have also installed pandoc:
```
matteo@IT-LAPTOP-039 ~ % which pandoc
/opt/homebrew/bin/pandoc
```
The pandoc PATH is inside homebrew PATH
```
matteo@IT-LAPTOP-039 ~ % echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
```
But i tried anyway to add it in this way:
```
matteo@IT-LAPTOP-039 ~ % echo $PATH
/Users/matteo/opt/homebrew/bin/pandoc:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
```
I can't open MarkText from terminal:
```
matteo@IT-LAPTOP-039 ~ % marktext
zsh: command not found: marktext
```
I tried to add also Mark Text path
```
/Users/matteo/Applications/Mark Text.app/Contents/MacOS/Mark Text:/Users/matteo/opt/homebrew/bin/pandoc:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
```
But I receive the same error about `marktext` command.
So I can't try any of the solutions you provided before.

What kind of information do you need to help me?

**Comment by dalianzhu** [comment]
I have found a solution:

1. When launching MarkText from the command line using `/Applications/MarkText.app/Contents/MacOS/MarkText`, it doesn't throw any errors. However, when starting it directly from Finder or using cmd+space, it gives an error indicating that pandoc cannot be found.
2. Launch MarkText from Joplin using the --debug flag and open the developer tools by selecting "View-Show Developer Tools". In the console, enter `process.env.PATH`. It seems that only the following directories are present in the PATH: `/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`.
3. Create the directory `mkdir -p /Library/Tex/texbin`. Then move the pandoc executable to this directory. This should resolve the issue.

You don't actually need to install Joplin. I just wanted to clarify that when launching MarkText from Finder, it only searches for pandoc in the directories `/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`. This behavior **might be a bug** that needs to be addressed.

version:
Mac m1 pro 13.3.1 (a) (22E772610a)
MarkText v0.17.1
