### ISSUE TITLE
Images in document are not exported with export to PDF

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1396]
### Description

When an .md file contains images, they are not exported with export to PDF, only the path to the file is shown.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a file
2. Insert an image
3. export to PDF
4. Open PDF

**Expected behavior:**
I would expect the images to show up in the PDF

**Actual behavior:**
No images are shown.

### Versions

- Mark Text: 0.15.0
- Operating system: Linux Mint

**Comment by fxha** [comment]
Maybe duplicate of #1367?

**Comment by DutchPete** [comment]
@fxha : tanks for pointing that out. What @infeeeee mentions in #1367 is correct. I have commented on that page as to how to handle that, so I'll close this issue (#1396), and #1367 can probably be closed too.
