### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1408]
### Describe your feature request

The command palette should be a drop down menu with all available commands that can be opened with `Ctrl-Shift-P`. It should also support sub commands like an input to save the file to.

### What problem does this feature solve? [optional]

We could easy integrate all commands and further functions like line ending and file encoding to the command palette via (sub) commands. The user can simply search needed commands/feature and don't need to use the menu. Also the key bindings should be displayed. Furthermore we could integrate features that are not sufficient for the menu such file encoding etc. It's would be also a major step for keyboard only use.

### Additional context [optional]

![](https://flight-manual.atom.io/getting-started/images/command-palette.png)

**Comment by Jocs** [comment]
@fxha Can you explain more detail about this feature:

- List the commands it support
- Does it support quick open folder(side bar opened) files and recently opened files?#581
- Do we need to classify the commands?

**Comment by fxha** [comment]
> List the commands it support

All commands that are available with menu but also further like file encoding. We could basically add more commands to it but I don't really know (yet), how to load the current state from Muya/editor to disallow commands and request information.

> Do we need to classify the commands?

What do you mean by this? Maybe the example below helps.

> Does it support quick open folder(side bar opened) files and recently opened files?

I thought of this and started with some demo code to test but I don't guess. You can see an example command below. We can add/remove commands at runtime and the "command center" can executes commands that are received via bus. Currently I don't really know how to best implement quick open into the command palette component. I think the best is to copy the design and implement specially made version for files.

A query is searched by matching `description` value. If the user presses enter, either the command is executed or subcommands are loaded into view. There are some issues with this approach like the mentioned issues above to load the state and that all values are static - we cannot load values. Maybe we need to create a few commands at runtime with bindings/callbacks to react to the editor state. Planned is currently to defined as many commands statically via JS object (as below), complete some commands at runtime and maybe add missing commands at runtime that require to interact with the editor.

I also thought to use a different approach to define all commands at runtime with classes/function that the command palette can call to build commands/subcommands. These commands would be registered at runtime with the needed binding to other editor components. I guess this approach would support quick open because we can register a command that loads all files depending on search query from the root directory state. We could add a prefix similar to vscode like `>`, `?` to either load commands or search in opened files and root directory.

**Example data strucure from first part:**

```js
  {
    // The unique command name.
    id: 'test-command-1',
    // The command display name: (<category>: )<name>
    description: 'Test Command 1',
    // Optional shortcut to show.
    shortcut: null,
    // Each command can have an optional data attribute that is passed together
    // with action. This is mainly used for subcommands and only static.
    value: null,
    // Handler type that is called if selected. If...
    //   `0` `action` is emitted on bus.
    //   `1` `action` is emitted to `ipcRenderer`.
    //   `2` `action` is emitted to `ipcMain`.
    //   `3` `cb` is executed.
    handler: null,
    // The event name or callback that is used/called when the command is selected.
    action: null,
    // Each command can have nestled subcommands that have the same
    // properties like a command. If subcommands are defined no event
    // is emitted and the subcommands are loaded into view.
    subcommands: [
      {
        id: 'sub-test-command-1',
        description: 'Sub Test Command 1',
        shortcut: null,
        value: 'foo'
      },
      {
        id: 'sub-test-command-2',
        description: 'Sub Test Command 2',
        shortcut: null,
        value: 'bar'
      }
    ]
  }
```

**Comment by fxha** [comment]
**Example from last part:**

```js
const registerCommand = cmd => {
  if (!rootCommandState) {
    rootCommandState = new RootCommand()
  }
  rootCommandState.subcommands.push(cmd)
}

// ...

// Root command that contains all other commands and is only loaded as
// root entry to execute subcommands.
class RootCommand {
  constructor () {
    this.id = '#'
    this.description = '#'
    this.subcommands = []
  }

  async run () {}

  // Execute the command.
  async execute () {
    throw new Error('Root command.')
  }
}

// And in other files we can create and register instances.

class OpenNewTabCommand {
  constructor () {
    this.id = 'file.open-new-tab'
    this.description = 'File: Open new Tab'
    this.shortcut = null // Load this from main process
  }

  // Execute the command.
  async execute (args) {
    ipcRenderer.send('my-custom-command')
  }
}

class FileEncodingCommand {
  constructor () {
    this.id = 'file.change-encoding'
    this.description = 'File: Change Encoding'

    this.subcommands = []
    this.subcommandSelectedIndex = -1
    this.subcommandsAvailable = true
    this.customSubcommandsExecute = true
  }

  // Prepare subcommands and run the command when the entry is set as root.
  async run () {
    this.subcommandSelectedIndex = 0 // Load from editor state
    this.subcommands = []
    for (const [key, value] of Object.entries(ENCODING_NAME_MAP)) {
      this.subcommands.push({
        id: key,
        description: value
      })
    }
  }

  // Execute the command.
  async execute () {
    // Send bus message to show "this" as root command palette entry.
  }

  // Execute a subcommand.
  async executeSubcommand (id) {
    // Change encoding to "id"
  }

  // Unload buffers when the command palette is closed to reduce memory usage.
  unload () {
    this.subcommands = []
  }
}

class SearchCommand {
  constructor () {
    this.id = 'search.quick-search'
    this.description = 'Searc: Quick Search'
    this.shortcut = null

    this.subcommands = []
    this.subcommandSelectedIndex = -1
    this.subcommandsAvailable = true
    this.customSubcommandsExecute = true
    this.customSearchHandler = true
  }

  // Handle search query changes when the entry is root.
  search (query) {
    // Interact with `project.js` and return search results. This instance should
    // be initialized in `project.js` to get access to the data.
    const searchResultFilesnames = []
    return searchResultFilesnames.map(f => {
      return {
        id: f,
        description: f
      }
    })
  }

  // Prepare subcommands and run the command when the entry is set as root.
  async run () {
    // Load recently used files but don't try to load all files from sidebar.
    this.subcommands = []
  }

  // Execute the command.
  async execute () {
    // Send bus message to show "this" as root command palette entry.
  }

  // Execute a subcommand.
  async executeSubcommand (id) {
    // Open tab with filename "id".
  }

  // Unload buffers when the command palette is closed to reduce memory usage.
  unload () {
    this.subcommands = []
  }
}
```

**Comment by Jocs** [comment]
> We could add a prefix similar to vscode like >, ? to either load commands or search in opened files and root directory.

I think this feature request is a little like [Alfred](https://www.alfredapp.com/), I use it to quick open app or open files. for example:

It will search the app name contains `foo`, if I input `foo` in the input panel.

<img width="1437" alt="截屏2019-10-13下午9 26 33" src="https://user-images.githubusercontent.com/9712830/66716445-5087d280-ee00-11e9-9600-9141e063c7a6.png">


It will search the file's name contains `foo`, if I input `<white space>foo` in the input panel.

<img width="859" alt="截屏2019-10-13下午9 27 36" src="https://user-images.githubusercontent.com/9712830/66716446-52519600-ee00-11e9-9868-e57226233389.png">

**Comment by Jocs** [comment]
Looking forward to this feature, because I can only remember a few Mark Text shortcuts 😿
