### ISSUE TITLE
pre should be interpreted as html block

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1409]
### Description

We should show single HTML `pre` tags as code block like GitHub does.

- [x] Can you reproduce the issue? 

### Steps to reproduce

Insert example below:

```
bar

<pre>
foo
foo
foo
foo
</pre>

bar
```

**Expected behavior:**

When we parse a single `pre` tag as block like above, we should show it as code block.

**Actual behavior:**`

Content is not shown.

### Versions

- Mark Text: all
- Operating system: all

**Comment by Jocs** [comment]
>We should show single HTML pre tags as code block like GitHub does.

I think single HTML pre tags should be HTML block, not code block? but there has bugs to render `pre` HTML block as you described above. `Content is not shown`.
