### ISSUE TITLE
Question: Why embed marked instead of including as a dependency?

### ISSUE THREAD

**Issue by styfle** [marktext/marktext#141]
I noticed you have and old copy of [marked.js](https://github.com/marktext/marktext/blob/master/src/editor/parser/marked.js) included in your src instead of as a dependency.

What did you modify and do you plan to submit back to [markedjs/marked](https://github.com/markedjs/marked)?

**Comment by Jocs** [comment]
Someone else asked the same question before, and here I explain it in a unified way. 

Marked is a cool markdown parser.

The reason for cloning a copy is that marked has already been said in its [issue](https://github.com/markedjs/marked/pull/587) and it will not support the task list.

I'll use a copy of marked before it support task list. Also I add some special features to marked for Mark Text use.

**Comment by styfle** [comment]
Thanks for the response!

>  Also I add some special features to marked for Mark Text use.

Which special features? Are these part of the CommonMark or GitHub Flavor Markdown specifications? http://commonmark.org/

**Comment by Jocs** [comment]
for example:

We add `task list` and `disable inline`.

**Comment by fxha** [comment]
@styfle Another big feature is loose and tight list compatibility, but there are still some problems like #106.

**Comment by styfle** [comment]
Let me discuss with the marked team.
We opened https://github.com/markedjs/marked/pull/587 since we now have some tests to run against the GFM spec.

**Comment by Jocs** [comment]
@styfle Great thanks to you! 

I hope that one day marked can support the task list, and I will always pay attention to the development of marked.

**Comment by styfle** [comment]
FYI, https://github.com/markedjs/marked/pull/587 was fixed in https://github.com/markedjs/marked/pull/1250

**Comment by Jocs** [comment]
@styfle 
Thank you for your notice. I have also been focusing on marked. Now Mark Text's development may not be able to directly use marked, because I added some custom syntax, such as math block, front-matter, etc.

so I have been looking for opportunities, I would like to ask whether the marked will support plugins ?  can add some custom syntax, and rendering functions, so that it will not invade the core features of the marked.If you have such plans, I would be happy to make some contribution.

**Comment by styfle** [comment]
@Jocs Unfortunately, marked is not ready to be extended with plugins at this time.

The goal for v1.0.0 is to reach parity with existing markdown specs (CommonMark and GFM) and make the project stable. Once it's stable, then we can look at creating some kind of extensible API or plugins for v2.0.0 but that could take some time.

**Comment by Jocs** [comment]
@styfle About marked I have another suggestion to rewrite the existing project through the ES6 module, because the current file is too large for maintenance. Then pack up to the target code by webpack or rollup, do you have such plans? I have done some of this work in the Mark Text.

**Comment by styfle** [comment]
@Jocs I personally would be fine with it for v2.0.0

There is some discussion already

- Coding standards: https://github.com/markedjs/marked/issues/1089
- Modularization of library: https://github.com/markedjs/marked/issues/746

**Comment by Jocs** [comment]
@styfle I don't know why I missed these issues. I'm glad to see that marked has already started preparing for these jobs. I also hope that I can make some contributions while I'm free.

**Comment by styfle** [comment]
@Jocs Feel free to comment on those issues. We all maintain marked in our spare time so it doesn't move very fast 😅

**Comment by Jocs** [comment]
@styfle OK 👍
