### ISSUE TITLE
Autolinks are not supported

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1410]
### Describe your feature request

GFM autolinks are not supported by Mark Text.

> Autolinks are absolute URIs and email addresses inside < and >. They are parsed as links, with the URL or email address as the link label.
> 
> A URI autolink consists of <, followed by an absolute URI followed by >. It is parsed as a link to the URI, with the URI as the link’s label.
> 
> An absolute URI, for these purposes, consists of a scheme followed by a colon (:) followed by zero or more characters other than ASCII whitespace and control characters, <, and >. If the URI includes these characters, they must be percent-encoded (e.g. %20 for a space).

**Example:**

```
foo <http://foo.bar.baz> bar

foo <mail@bar.baz> bar
```

Renders to:

foo <http://foo.bar.baz> bar

foo <mail@bar.baz> bar

**Comment by Jocs** [comment]
The spec of autolink https://github.github.com/gfm/#autolinks

**Comment by fxha** [comment]
Duplicate of #1202.
