### ISSUE TITLE
Unnecessary file watch notification when I edit in marktext

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#1418]
### Description

- [x] Can you reproduce the issue? 

I edit the file in any folder, Unnecessary file watch notification shown after I save the edited file.

### Steps to reproduce

1. Open one folder with markdown file in Mark Text.
2. Click one markdown file in side bar and edit the content.
3. press `Cmd + S` to save file.

**Expected behavior:**

File be saved silently.

**Actual behavior:**

<img width="859" alt="屏幕快照 2019-10-01 下午3 56 39" src="https://user-images.githubusercontent.com/9712830/65944532-81612280-e464-11e9-86ae-117dae223923.png">

**Link to an example: [optional]**

### Versions

- Mark Text: develop
- Operating system: macOS

**Comment by fxha** [comment]
@Jocs Maybe an issue with [this](https://github.com/marktext/marktext/blob/c2c4dee785f7f4e9f822e265fe2cf3608b4ebb11/src/main/filesystem/watcher.js#L319) function. Also network mapped folders cause this error, you need to use polling for network disks.

**Comment by Jocs** [comment]
>you need to use polling for network disks.

I don't quite understand what is saved to network disks? Do we use network disks?

**Comment by fxha** [comment]
You need to set `watcherUsePolling` to `true` in `preference.json` if you want to watch files on a Network File System (NFS) such as iCloud Drive or Google Drive. Setting this to polling continuously checks all files for changes which can result in very bad performance and high CPU usage in larger directories.  Could you please confirm that this is not a chokidar issue? Is it reproducible with v0.15.1?

chokidar documentation:

> `usePolling` (default: `false`).
Whether to use fs.watchFile (backed by polling), or fs.watch. If polling
leads to high CPU utilization, consider setting this to `false`. It is
typically necessary to **set this to `true` to successfully watch files over
a network**, and it may be necessary to successfully watch files in other
non-standard situations.

**Comment by Jocs** [comment]
@fxha I use `usePolling` on macOS system, and it works.
