### ISSUE TITLE
Hiding Illustrations

### ISSUE THREAD

**Issue by edi0th** [marktext/marktext#1436]
Hey MarkText makers !

First of all, thanks for you work. Marktext is a great tool, and writing with it is a real pleasure !

I was wondering if it could be possible to add a option in the configuration panel, allowing us to hide or not the illustrations displayed here and there in the software. They are really nice, and the style is sober as it should be not to distract us, but if the goal of next version is the possibility of theming MarkText, then, leaving the illustration no matter what could be a problem because the colors won't automatically match.

Illustrations add a friendly good vibes to the sobriety of MarkText, but It gives too much of a graphical direction for those who want to personalize it perfectly to their taste.

**Comment by fxha** [comment]
> allowing us to hide or not the illustrations displayed here and there in the software

Thanks for your feedback. Do you mean the format and link pop up or which illustrations do you mean?

**Comment by Jocs** [comment]
@edi0th maybe mean this.

<img width="1162" alt="屏幕快照 2019-10-03 下午10 56 40" src="https://user-images.githubusercontent.com/9712830/66138436-321c1d00-e631-11e9-9f3d-9c21d5938725.png">

**Comment by edi0th** [comment]
Sorry ! Yes, I mean exactly this : )

**Comment by Jocs** [comment]
Maybe we need designers to help us design more concise icons and illustrations, or animal images for Mark Text, so Mark Text will be more vivid.

**Comment by edi0th** [comment]
Fact is, i'm a graphic designer ( ͡° ͜ʖ ͡°) 

The thing is, it depends of the philosophy you want to embrace. 

At the bottom of your post _Looking for contribution_ Fxha says that «[...] our philosophy is to keep things clean, simple and minimal. [...] So we allow everyone to customize Mark Text for it needs and provide a minimal default interface.» And I think this is the right idea a software should follow. Be simple as it can be, allowing those who want to make it perfectly adapted to their needs.

If someone doesn't want to personnalize Marktext, and just want a friendly TextWriter Software, then thinking about vivid illustration is a plus. But if someone wants to change MarkText theme for it's own, and wants to apply some dark horrific theme, then, vivid illustration become a burdain for him/her, not matter how nice they are. That's why I think illustration could be activate by default, for MarkText to be welcoming, but also should be an option for those who want to give the software another feel.

That being said, if you don't have any designer in the team, I could try to make a overall checkup of the design if you want it (but besides the illustration thing, everything looks already pretty great). But i'm not really good at illustrations, so I wont be much of an help for that...

**Comment by Jocs** [comment]
> our philosophy is to keep things clean, simple and minimal.

Yes, our product philosophy has not changed, and we are still pursuing a simple, clean and minimal interaction.

> But if someone wants to change MarkText theme for it's own, and wants to apply some dark horrific theme, then, vivid illustration become a burdain for him/her, no matter how nice they are. 

I haven't considered this in design before. we are not designers(me and @fxha ), and I didn't consider the illustration under the black theme. I only want to make Mark Text more vivid, so I add the illustration.

> but also should be an option for those who want to give the software another feel.

Is it possible to design a simple, clean illustration, not necessarily colorful, and then present it well on all themes? 

>That being said, if you don't have any designer in the team, I could try to make a overall checkup of the design if you want it (but besides the illustration thing, everything looks already pretty great). But i'm not really good at illustrations, so I wont be much of an help for that...

Yes, we are an open source organization that offers open source and free products, Mark Text, for all markdown and writing enthusiasts. Currently we don't have designers to join, so we hope someone can provide design for Mark Text, we also know that there are many places in Mark Text that are not well designed, editor layout is also a problem, Logo needs to be redesigned, with different themes, etc., I sincerely hope that you can help Mark Text to make some improvements to the design.

**Comment by edi0th** [comment]
Okay. I'd be glad to help.
Since I would not code anything, but just helping on design, is this thread the best place to works or should I write you somewhere else ?

**Comment by Jocs** [comment]
Do you use zeplin and sketch? We can discuss on github and check design on zeplin or sketch?

发自我的 iPhone

**Comment by edi0th** [comment]
I use neither of those : / I only work with free softwares. Would it be a problem to give you more unconventional vizualisations, like pdf mockup ?

**Comment by Jocs** [comment]
>I use neither of those : / I only work with free softwares. Would it be a problem to give you more unconventional vizualisations, like pdf mockup ?

Sorry for response so late, do you use any other softwares?
