### ISSUE TITLE
Support Front Matter for GitHub Pages

### ISSUE THREAD

**Issue by Sharaal** [marktext/marktext#144]
### Description

If making markdown files for GitHub Pages, a header in the Front Matter format is needed. It would be nice if this will be supported in the editor to show there is this special kind of header and highlight the key/value pairs.

Details for Front Matter used by GitHub Pages:
https://jekyllrb.com/docs/frontmatter/

**Comment by coolreader18** [comment]
I second this. YAML front matter isn't just used by Jekyll, it's used by a lot of static site generators, so it'd be nice if there could be either a YAML syntax for text between the two `---`'s or even a GUI editor for it, though that's a lot to ask.

**Comment by johnblommers** [comment]
Agreed. And until YAML front matter is supported the presence of a YAML block should be ignored. All of my Markdown files have YAML in the front matter. I hope this enhancement is implemented sooner rather than later.

**Comment by Ciantic** [comment]
This also incorrectly wants to add extra new line each time I open a document with YAML in the beginning e.g.

```
---
title: My title here
category: flowers
author: Myself
created: 2018-09-01
---

# Sometitle
```

If I open the document it converts it to this:

```
---
title: My title here
category: flowers
author: Myself
created: 2018-09-01

---

# Sometitle
```

**Comment by Jocs** [comment]
@Ciantic Can  you open another issue and explain this bug more detailly, thx.
