### ISSUE TITLE
Support Todo.txt

### ISSUE THREAD

**Issue by mundo03** [marktext/marktext#1454]
### Support Todo.txt

I would be awesome if Marktext supports [todo.txt]( http://todotxt.org/)

### What problem does this feature solve? [optional]

Better handling of todo lists, specially when syncing notes between devices.
I use syncthing to sync my phone to a raspberry to my laptop where I use marktext, the phone markdown editor ([markor](https://github.com/gsantner/markor)) supports todo txt, it would be awesome if marktext supports it too.

**Comment by fxha** [comment]
Thanks for your request. Unfortunately, Mark Text is a pure markdown editor with some special extensions but maybe in the future we could integrate an importer if there is sufficient interest in this request. You may can try pandoc to convert the file to markdown.

**Comment by nettok** [comment]
I would also love to have some basic handling and syntax highlighting for todo.txt files.

My workflow is pretty similar to what mundo03 said.   I use syncthing to sync with phone, but using Epsilon Notes which also supports todo.txt besides markdown.
