### ISSUE TITLE
Cannot change the language Mark Text use.

### ISSUE THREAD

**Issue by Pylory** [marktext/marktext#1463]
### Description

I use this software under the japanese win10 operating system.
I want to set the language to Chinese.
However, the option is grayed out and cannot be changed.
I try to run the program as an administrator.
Still gray and can't be changed.
![image](https://user-images.githubusercontent.com/19777313/66447690-a9164300-ea81-11e9-8d29-72d69727da19.png)

### Versions

- Mark Text: v0.15.0
- Operating system: jp_windows_pro_1803_x64

**Comment by Jocs** [comment]
Duplicated with #138

**Comment by Jocs** [comment]
Mark Text does not support internationalization now, and will be support in version 0.17.0

**Comment by myggj** [comment]
> Mark Text does not support internationalization now, and will be support in version 0.17.0

Thank you.

**Comment by Pylory** [comment]
> Mark Text does not support internationalization now, and will be support in version 0.17.0

Thank you.
