### ISSUE TITLE
Code block syntax hight-light lost when reopen files

### ISSUE THREAD

**Issue by umi-neko** [marktext/marktext#148]
New created code block's syntax hight-light is corrected, but after reopen it, the syntax hight-light will lost.
OS: macOS
marktext version: 0.6.12

**Comment by Jocs** [comment]
@umi-neko Please download the latest version, I remember the bug has been fixed in the new version.

**Comment by umi-neko** [comment]
Oh that's my fault, I thought the one on baidu yun also is the latest version
0.9.25 is ok
