### ISSUE TITLE
PDF export has an empty additional page

### ISSUE THREAD

**Issue by L0Lock** [marktext/marktext#1480]
### Description

When exporting to PDF format with just enough text to fill the page to the last line, a new empty page is added in the PDF:

![demo pic](https://i.imgur.com/3hjk25x.png)

It's quite annoying because the only way to not get this empty page is to not use the last line of the previous page, which often leads to deleting parts of the text.
If I inspect the PDF file there is no additional character nor line return justifying the new page.

### Steps to reproduce

1. Make a document with enough text to fill the first page up to the last line
2. File → Export → PDF
3. Open the PDF and see.

**Expected behavior:**

No additional blank page.

**Actual behavior:**

Additional blank page.

**Link to an example: [optional]**

[markTextPdfExportTest.pdf](https://github.com/marktext/marktext/files/3721909/markTextPdfExportTest.pdf)

### Versions

- Mark Text: 0.15.1
- Operating system: Windows 10 Pro

**Comment by fxha** [comment]
Thanks @L0Lock  for reporting the issue. This issue need further investigation, maybe just an empty new line might be the problem for that or an Electron issue due to wrong height calculation. 

**Example text to reproduce:**

You can print the example just in one page by removing one or two "words" at the ending.

```
sdasda

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasd

sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasdsasdasd

sdasda sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd sasdasd
```

**Comment by L0Lock** [comment]
The issue with the "just remove words" solution, is that it's unpredictable and unusable for important documents.

Sometimes removing a word or two will do it, sometimes you will have to remove more.

I'm writing job-related documents right now. I don't have many spare words if any: I'm already choosing each word carefully and I'm not writing things I don't need to put in there. And I **have** to fit them in no more than one page. Right now there are documents I'm obliged to write on another softwares just because of that.

**Comment by fxha** [comment]
> The issue with the "just remove words" solution, is that it's unpredictable and unusable for important documents.

@L0Lock Maybe bad written from me but I didn't mean that as solution, rather as hint when investigate the issue. The problem was easy to fix because just padding from the last paragraph was on the "empty" page.

**Comment by L0Lock** [comment]
Oh ok i see.
