### ISSUE TITLE
Muya API/usage issues

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1491]
### Description

I noticed some issues during developement of the command palette:

1. Muya allows all actions/commands to be used, even in invalid states. E.g. You can create a HR inside a table that crashes the editor when emitting the needed event on bus. Muya should keep track of allowed actions and forbid to use them in invalid states. Currently the actions are only disabled when the menu is disabled but you can still use actions if you want. Whereas this could be done by the editor too, Muya should handle this issue and provide an API to ask for disabled/not allowed actions. Furthermore Muya should emit an event when the available actions changes. As far as I know this is currently done in main process to disable menu items.
2. We should integrate an API to edit text using functions like `formatLine(lineToEdit, editRange, actionToDo)` (as `replaceWord` for spell checking) to allow edits when no selection is available from the user.
3. Related to 2\.: Opening a dialog will deselect the editor and doesn't restore the previous selection/state when the dialog disappears. This cause the problem that we cannot execute commands to format the editor from command palette because no selection and no API's are available to manually change formatting.

/cc @Jocs

**Comment by Jocs** [comment]
>Muya allows all actions/commands to be used, even in invalid states. E.g. You can create a HR inside a table that crashes the editor when emitting the needed event on bus. Muya should keep track of allowed actions and forbid to use them in invalid states. Currently the actions are only disabled when the menu is disabled but you can still use actions if you want. Whereas this could be done by the editor too, Muya should handle this issue and provide an API to ask for disabled/not allowed actions. Furthermore Muya should emit an event when the available actions changes. As far as I know this is currently done in main process to disable menu items.

We have `selectionChange` and `selectionFormats` event, can we use this to judge whether to disable some action, for example forbid create HR inside a table cell?

**Comment by Jocs** [comment]
>We should integrate an API to edit text using functions like formatLine(lineToEdit, editRange, actionToDo) (as replaceWord for spell checking) to allow edits when no selection is available from the user.

Good idea, I have a question about `actionToDo`, do you mean the replaced text?

**Comment by Jocs** [comment]
>Related to 2.: Opening a dialog will deselect the editor and doesn't restore the previous selection/state when the dialog disappears. This cause the problem that we cannot execute commands to format the editor from command palette because no selection and no API's are available to manually change formatting.

I think we need to save the cursor before show the dialog, and restore the cursor after the dialog disappears, then we can execute the commands?

**Comment by fxha** [comment]
> We have selectionChange and selectionFormats event, can we use this to judge whether to disable some action, for example forbid create HR inside a table cell?

That sounds good and I prefer to move the logic to Muya and remove the code from main process like [this](https://github.com/marktext/marktext/blob/5d247ec5ee42b49d0a33f97fe7ee8694a3446af7/src/main/menu/actions/paragraph.js#L95). Muya should provide a list of disabled actions that we can emit to main process. Currently we just forward both Muya events to main process.

> Good idea, I have a question about actionToDo, do you mean the replaced text?

The format action like `bold` or `link`. We get a line and range to manipulate plus the action what should be changed.

> I think we need to save the cursor before show the dialog, and restore the cursor after the dialog disappears, then we can execute the commands?

Yep, that should work with a timeout or special functions that allow edits with the saved cursor.

**Comment by Jocs** [comment]
>That sounds good and I prefer to move the logic to Muya and remove the code from main process like this. Muya should provide a list of disabled actions that we can emit to main process. Currently we just forward both Muya events to main process.

I prefer move it to `common` folder, because it will be used in `main process` and `renderer process`, so put it in common folder, but it's no need to put it in `muya`, maybe other users no need these disable info when they use `muya` in their project.

**Comment by fxha** [comment]
Closing as 3\. was already fixed, 1\. should be fixed by #1493 and worked around 2\.
