### ISSUE TITLE
Shortcut for Typewriter Mode triggers Terminal in Linux/Ubuntu

### ISSUE THREAD

**Issue by leosoaivan** [marktext/marktext#15]
### Description

Great job on this markdown editor.

The current shortcut for Typewriter mode on Linux (`Ctrl + Alt + T`) unfortunately brings up the terminal. Consider changing the shortcut.

### Steps to reproduce

1. Load Mark Text on a Linux system
2. Hit `Ctrl + Alt + T`

**Expected behavior:**
Mark Text enters Typewriter mode

**Actual behavior:** [What actually happened]
Linux boots up the terminal

### Versions

- Mark Text: 0.6.14
- OS: Ubuntu 16.04

**Comment by Jocs** [comment]
@leosoaivan Thank you for report the bug, I'll change the shortcut for Typewriter Mode in the next release version. stay tuned.

**Comment by gilbertohasnofb** [comment]
In general, it would be better to avoid all `Ctrl-Alt-something` shortcuts on Linux. At least with Ubuntu and Linux Mint, many of those are tied to system functions and system shortcuts, e.g.`Ctrl-Alt-t` for terminal, `Ctrl-Alt-d` for showing desktop, `Ctrl-Alt-l` for lock screen, `Ctrl-Alt-Del` for logout, `Ctrl-Alt-Backspace` for restarting the X server, `Ctrl-Alt` with numbers or arrows to move around workspaces, etc.

Right now, as of version 0.16.2, the shortcuts are quite inconsistent, with some modes using `Ctrl-Alt` shortcuts while Focus Mode uses `Ctrl-Shift`:

![image](https://user-images.githubusercontent.com/5700795/97614518-f3ae8880-1a11-11eb-9b03-c156bf0de5a7.png)

Perhaps using only `Ctrl-Shift` for Linux would be a better approach, making them all consistent, Linux-friendly, and also easier to memorise by not mixing them.
