### ISSUE TITLE
Is there a reset settings?

### ISSUE THREAD

**Issue by boyoungzheng** [marktext/marktext#1502]
### Question description

Is there a way to reset settings? I played around but messed things up. I need a `reset` button somewhere in the settings.

Thanks!

Mark Text
v0.15.1
macOS
10.15

**Comment by fxha** [comment]
@boyoungzheng You have to remove the `preferences.json` file in the [application data directory](https://github.com/marktext/marktext/blob/develop/docs/APPLICATION_DATA_DIRECTORY.md) when Mark Text is not started.

**Comment by Jocs** [comment]
@fxha is it necessary to add a reset button to reset user preferences?

**Comment by fxha** [comment]
I don't think so.
