### ISSUE TITLE
Do you want Mark Text to support Touch Bar?

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#1513]
**Note**: This issue is about whether to support the touch bar on the macbook pro.

### Purpose

1. In the feature request issues of Mark Text, there is currently no issue related to touch bar. Do you often use touch bar? So this issue wants to investigate, do you have any need for touch bar support, if you have, please :+1:.
    
2. If you have a need for a touch bar, what do you want the touch bar to do? Everyone is welcome to discuss this issue.
    

### Some features that may be implemented:

1. Migrate `turn into` menu item in the Front menu to the touch bar.
    
2. Migrate the format tool bar to the touch bar and hope to customize it.
    
3. Table operations, adding rows/columns, deleting rows/columns, moving rows/columns, cell alignment, copying, and deleting tables.
    
4. List operations, conversions between lists(task list, bullet list and order list), list indentation, etc.
    
5. Code block operation, copy, delete code block, code block language selection.
    
6. Search for emojis.
    
7. Show and hide the sidebar
    
8.  ...
    

Welcome everyone to add above list.

**OS system**: macOS with touch bar

**Comment by L1cardo** [comment]
I think any features in the Touch Bar will be awesome!

**Comment by kosssi** [comment]
Your app is so awesome but this feature is so useless, I think internationalization is much more important ;)

**Comment by bravekingzhang** [comment]
It's great, but it's not a necessity

**Comment by saegl5** [comment]
> It's great, but it's not a necessity
@bravekingzhang correct, and it's limited to macbook pros

**Comment by Jocs** [comment]
Closed due to Apple give up touchbar already.
