### ISSUE TITLE
Weird ":" highlighting

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#152]
Text which is between `:` and another `:` is highlighted in cyan. Maybe problem with smiley highlighting?

### Steps to reproduce

Insert following text into source mode and exit.

```
std::thread::hardware_concurrency

a::b::c

https://google.com - ok

foo: https://google.com

foo: asd & bar: !asd
```

**Expected behavior:**

Black text

**Actual behavior:**

![mt_highlighting](https://user-images.githubusercontent.com/22716132/38765593-e30175f8-3fc4-11e8-814f-99f8f295a6ca.png)

### Versions

- Mark Text: v0.9.25/master

**Comment by Jocs** [comment]
I use the color `cyan` to indicate that the `emoji` is not validated.

>foo:https\://wwwbaidu.com

should not be parsed as emoji syntax.

I'll fixed, thanks.

**Comment by Jocs** [comment]
@fxha I changed the invalid emoji color to `rgba(242, 134, 94, .7)`.
and markdown text like below.

> foo:https\://wwwbaidu.com

will not be parsed as emoji syntax now.
