### ISSUE TITLE
Error messages when exporting fails

### ISSUE THREAD

**Issue by schrej** [marktext/marktext#1523]
### Describe your feature request
I'm not really sure whether this is a bug or intentional/not a feature yet.

Currently, whenever exporting fails I don't get an error message. This is incredibly frustrating. First of all you don't really know if it even tried to export. And second, there is no sensible way of fixing your document so it can get exported successfully.

A proper error message should be shown. Ideally it would include the location in the document where the exporting failed. Ideally the issues would then be annotated within the document.
And if you want to go all fancy, the issues would be shown directly while typing (but that's probably a little too much).

### What problem does this feature solve? [optional]
It greatly facilitates fixing errors in documents that prevent it from getting exported.
My current approach was to basically delete stuff until it exports, and then slowly add stuff to find the part that breaks it.

**Comment by fxha** [comment]
I think you refer to #1521 and #1522, right? Both are exceptions which should not occur. I guess we can improve the UX with LaTeX syntax instead showing *invalid mathematical formula* in preview mode (@Jocs). Issues while exporting are reported back if no critical exception occur.

**Comment by schrej** [comment]
Ah. Then maybe critical exceptions should also be returned back, just to give any feedback at all. Maybe in a "please report this issue here" way with a collapsed error message, that caring users can then open an issue for. That would probably facilitate finding and fixing such bugs.

**Comment by fxha** [comment]
Ok, we should definitely catch all exceptions during export. The example below is outdated in the latest mermaid version and throws an exception:

<pre>
## Sequence diagram

```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts 
prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```
</pre>

**Comment by Jocs** [comment]
@fxha Do we need to show an `error report` dialog as in main process?

**Comment by fxha** [comment]
>  Do we need to show an `error report` dialog as in main process?

@Jocs  We have to make sure that no exceptions are thrown if a user makes a mistake like wrong syntax. I thought that this was already done but if you paste the example above, a lot of warnings and a few exceptions are shown/thrown. So we have to catch these and show a simple notification that there was an issue with x while exporting - maybe we can get an issue message from the library that thrown the exception - like in diagram code blocks that only show `Invalid <library> code`.

**Comment by Jocs** [comment]
>We have to make sure that no exceptions are thrown if a user makes a mistake like wrong syntax. I thought that this was already done but if you paste the example above, a lot of warnings and a few exceptions are shown/thrown. So we have to catch these and show a simple notification that there was an issue with x while exporting - maybe we can get an issue message from the library that thrown the exception - like in diagram code blocks that only show Invalid <library> code.

We maybe add some `event` to muya, like:

```js
muya.on("render-error", handler)
```

So we can report/show these error on renderer process.

**Comment by fxha** [comment]
I think we could wrap the export module method in a try/catch because it's just a standalone module AFAIK.

**Comment by Jocs** [comment]
Yes, and emit the `render-error` event after we catch the error.

**Comment by fxha** [comment]
Reopen as export fails when an invalid math formula exist and no clear error message is given - just that an error occurred. I think we should show the error message and skip invalid math formula with a warning.

**Comment by Jocs** [comment]
@fxha Can you paste the invalid math formula?
