### ISSUE TITLE
Double space between tasklist checkbox and text

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#153]
### Description

Double space between tasklist checkbox and text.

### Steps to reproduce

Insert following task list into source code mode and exit. Then go back into source code mode.

```
- [ ] a
- [ ] b
```

**Expected behavior:**

```
- [ ] a
- [ ] b
```

**Actual behavior:**

Double space between `]` and `a/b`

```
- [ ]  a
- [ ]  b
```

### Versions

- Mark Text: v0.9.25/master

**Comment by Jocs** [comment]
@fxha Yeh, can you help fix this issue.:smile:

**Comment by vineethkartha** [comment]
@Jocs I can take this up

**Comment by Jocs** [comment]
@vineethkartha my fault, can you open an PR?

**Comment by vineethkartha** [comment]
@Jocs  I'm working on the fix once ready will create a PR
