### ISSUE TITLE
Release plan of v0.16.0

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1544]
### Release plan

- [x] Fix all planned [issues](https://github.com/marktext/marktext/projects/9)
- [x] Testing
- [x] Publish GitHub release candidate (`v0.16.0-rc.1`)
- [x] Publish GitHub release candidate (`v0.16.0-rc.x`) until all critical bug are fixed
- [x] Fix all (critical) bugs from feedback (`pre-release` label only)
- [x] Update documentation
- [ ] Update Flatpak images
- [ ] Update release notes and close all remaining issues
- [ ] Publish stable GitHub release (`v0.16.0`)

### Post release plan

- [ ] Update app download link on website
- [ ] Rebase `master` from `develop`
- [ ] Publish Flathub package

### Schedule

- Planned mid November
- Early November expected release candidate
- `?? November 2019` expected stable release (probably 1-2 weeks after first release candidate)

**Comment by fxha** [comment]
We'll move custom application themes and sidebar optimization to v0.17.0.

**Comment by Jocs** [comment]
Since @fxha and me are busy recently, v0.16.0 may be delayed and released some time later. because there are still some `pre-release` labeled issues need to be fixed.

**Comment by Jocs** [comment]
@all we have release version 0.16.0-rc.3, feel free to download and try it.

https://github.com/marktext/marktext/releases/tag/v0.16.0-rc.3

**Comment by fxha** [comment]
Mark Text version 0.16.1 has been released and the release process is finished. Please see [here](https://github.com/marktext/marktext/blob/master/.github/CHANGELOG.md) for changes.
