### ISSUE TITLE
Fountain (screenplay markdown) support

### ISSUE THREAD

**Issue by brandonkal** [marktext/marktext#1553]
### Describe your feature request

[Fountain is the markdown format for screenplays](https://fountain.io).

This feature request is a bit of a long shot, but it would be a differentiating feature that you don't see in most markdown editors. If anyone is interested in diving into this, the spec itself is extremely simple to implement.

### How

I imagine supporting fountain through code blocks like so:

~~~md
## How To Write Suspense

Have a look at this piece of inspiration

```fountain
INT./EXT.  BLOOM HOUSE - (PRESENT) DAY

The front door opens to reveal Will and Josephine on the porch with their bags.  REVERSE to Will's mother Sandra (53), surprised and a little annoyed. 

SANDRA
How did you get here?
WILL
We swam.  The Atlantic, it's not that big really.
```
That is how you start a scene.
~~~

When the cursor leaves the fenced block, Mark Text can render the block in markdown format with character names properly centered.

### What problem does this feature solve? [optional]

This opens up mark-text as a prime candidate for writers who blog about writing.
The intent with this feature request is not to implement a complete screenwriting environment. Instead, it would allow writing snippets of screenplays within a larger body of text, like a blog post.

### Additional context [optional]

https://fountain.io
Slugline is a MacOS app that is live WYSIWG http://slugline.co
There is a VSCode plugin that parses fountain files for syntax highlighting

**Comment by Jocs** [comment]
@brandonkal is there a library to render  `fountain` to html?

**Comment by brandonkal** [comment]
@Jocs Yes, there is the [fountain.js](https://github.com/mattdaly/Fountain.js)

**Comment by fxha** [comment]
@Jocs @brandonkal I think this is (currently) outside the scope of the project.

**Comment by Jocs** [comment]
Yes, it also not a computer science language, so we can not put it in code block.
