### ISSUE TITLE
Improve "has File changed"-check

### ISSUE THREAD

**Issue by Blechlawine** [marktext/marktext#1554]
### Describe your feature request
A File should only be marked as "changed" if the File has been edited, not if you've only placed the cursor inside

### What problem does this feature solve?
currently, a file is marked as "changed" even when you've only placed the cursor inside

**Comment by Jocs** [comment]
@Blechlawine duplecated with #912 ?

**Comment by Blechlawine** [comment]
@Jocs Yep
