### ISSUE TITLE
Ctrl+Arrow behavior is counter intuitive.

### ISSUE THREAD

**Issue by Kuinox** [marktext/marktext#1571]
### Description
I will use this text as exemple:
```
aaaaa aaaaa aaaaa
bbbb bbbb bbbb
```
When you are right before the last "aaaaa" word, in browsers, and marktext, the arrow jump right before the "bbbb" word.
On most IDEs, and Word Processing softwares, the cursor jump at the end of the word if the word is the last one in the line, it allow to simply append the line.

- [X] Can you reproduce the issue? 

### Steps to reproduce

1. Put your cursor behind the last word of a line.
2. Press ctrl+right_arrow

**Expected behavior:**

The cursor should be after the last word of a line, allowing to append the line simply.

**Actual behavior:**

The cursor jumped to behind the first word on the next line.

### Versions

- Mark Text: v0.15.1
- Operating system: Windows 10

**Comment by fxha** [comment]
Closing as this seems to be fixed with latest develop version.
