### ISSUE TITLE
imageSelector has dark font color in dark themes

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1580]
### Description

All textboxes have a dark font color when a dark theme is selected and you cannot just overwrite it by CSS.

### Steps to reproduce

Open image selector overlay with dark theme.

**Example:**

![mt_imageSelector_font_color](https://user-images.githubusercontent.com/22716132/68040608-f5465300-fcce-11e9-8972-f07075e8830d.png)

### Versions

- Mark Text: develop
- Operating system: all

**Comment by Jocs** [comment]
@fxha It's ok on develop branch on my computer,  what's the css, and why can not overwrite it by CSS?

<img width="719" alt="截屏2019-11-02上午11 03 46" src="https://user-images.githubusercontent.com/9712830/68065198-a0ebb380-fd60-11e9-879a-ec6559534f29.png">

**Comment by fxha** [comment]
Ok, it's currently only an issue with Electron 7 because my build use Electron 7.

**Comment by Jocs** [comment]
>Ok, it's currently only an issue with Electron 7 because my build use Electron 7.

So move this issue to v0.17.0?

**Comment by fxha** [comment]
Fixed by Electron 7.0.1.
