### ISSUE TITLE
Issue with dialog and image picker/overlay

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1581]
### Description

Select an image that the image is marked with blue dot's. Open a dialog like about dialog and press `Space` or `Enter`.

**Expected behavior:**

Image selector should not be shown.

**Actual behavior:**

Image viewer or editor is shown when pressing `Space` or `Enter`.

### Versions

- Mark Text: >=v0.15.0
- Operating system: all

**Comment by Jocs** [comment]
blocked due to other PRs.

we can hide all the float tools and set selectedImage and selectedTableCells to `null` in muya's `blur` method when we show modal like `quick open`.
