### ISSUE TITLE
Error when searching folder with hidden files

### ISSUE THREAD

**Issue by Henry78** [marktext/marktext#1598]
### Description

In my notes base folder and subfolders, there are some hidden files (from other note taking tools). If i search my notes an error text is displayed above the search results which clutters the (small) sidepane. The error text (replaced file and path names) :
```
An error occurred:
/home/user/Notes/.file1.md: No such file or directory (os error 2)
/home/user/Notes/.file2.md: No such file or directory (os error 2)
/home/user/Notes/some/deep/path/.file3.md: No such file or directory (os error 2)
/home/user/Notes/very/very/deep/path/.file4.md: No such file or directory (os error 2)
```
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Put a hidden file somewhere in your note folder hierarchy
2. Search for some text

**Expected behavior:**

Error text is suppressed in the GUI.
Or: Error text is prettyfied and displayed below search results
Or: Hidden files are searched (not preferred by me)

**Actual behavior:**

Error text is displayed above the search results.

### Versions

- Mark Text: 0.15.1
- Operating system: Linux, Arch

**Comment by fxha** [comment]
Thanks for reporting this issue but I cannot reproduce the error. The error occurred in ripgrep, the searcher we're using, and I cannot say why ripgrep thinks that the files doesn't exit. Maybe an issue with permission or locked files?

> Hidden files are searched (not preferred by me)

Yeah that's a bug due to a wrong condition and get fixed in next release.

**Comment by Henry78** [comment]
My fault. The files were hidden **and** broken links. Sorry for your wasted time.

If in future hidden files aren't searched, this problem should go away anyways.
