### ISSUE TITLE
Mark Text doesn't save selected theme

### ISSUE THREAD

**Issue by notAlaanor** [marktext/marktext#16]
### Description

Mark Text doesn't save the selected theme, perhaps there could be a user config file.

### Steps to reproduce

1. Change Theme
2. Reopen Mark Text

**Expected behavior:**
Mark Text should keep selected theme

**Actual behavior:**
Mark Text doesn't keep selected theme

### Versions

- Mark Text: 0.6.14
- OS: Windows 10 x64

**Comment by Jocs** [comment]
@notAlaanor Yes, User Preference setting is in the plan， You can refer the [TODOLIST](https://github.com/marktext/marktext/blob/master/.github/TODOLIST.md) -  Preference in Mark Text Menu.
