### ISSUE TITLE
The current window is shown as `undefined`.

### ISSUE THREAD

**Issue by 31piy** [marktext/marktext#1602]
### Description

The current opened item is shown as `undefined` in the `Window` menu.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Open the app.
2. Open a folder which contains some docs.
3. Open a doc from the left navbar.
4. Observe the current doc title is shown in the `Window` menu.
5. Close the opened doc.
6. Observe the current doc title in the `Window` menu.

**Expected behavior:**

The item in `Window` menu should be changed to either of the below:
1. `Mark Text`, as it was when the app was opened and no document is opened.
2. The name of the folder opened.

**Actual behavior:**

The menu item shows `undefined - <folder name>`.

**Link to an example: [optional]**

![image](https://user-images.githubusercontent.com/3369637/68111974-57dd6000-ff16-11e9-864f-001a922038f0.png)

### Versions

- Mark Text: v0.15.1
- Operating system: MacOS Mojave 10.14.6

**Comment by Jocs** [comment]
@31piy Thanks for reporting this bug, PR is also welcomed.
