### ISSUE TITLE
Saving dialog ignores default directory

### ISSUE THREAD

**Issue by skyblue002** [marktext/marktext#1603]
### Description
The save dialog ignores the default directory and reverts to `~/Documents`. The default directory must be navigated to manually every time a note is saved.

- [x] Can you reproduce the issue? -- It persists after restarting the app.

### Steps to reproduce

1. Go to `Menu` > `File` > `Preferences`, and under `General`, select `Open a default directory`, set the preferred folder.
2. Create a new note.
3. Save the note.

**Expected behavior:**

I would expect the save dialog to show the default directory when attempting to save the note.

**Actual behavior:**

It reverts to showing the `~/Documents` directory. If the user is using any other folder as their default directory, they will have to manually navigate to that folder every single time they try to save a note, otherwise it will end up being saved to `~/Documents`.

This persists after restarting MarkText.

**Link to an example: [optional]**
The preferences were set to `~/Documents/MarkText`:
![MarkText-Preferences](https://user-images.githubusercontent.com/41849249/68120349-15466400-fed3-11e9-9c70-987b5900bf77.png)
The save dialog defaults to saving in the `~/Documents` folder:
![MarkText-Save-dialog](https://user-images.githubusercontent.com/41849249/68120367-22635300-fed3-11e9-8c05-8d0233efd367.png)

### Versions

- Mark Text: v0.15.1
- Operating system: Linux

**Comment by Jocs** [comment]
@fxha @skyblue002  I think the default save directory need to be the opened folder? then the default setting folder if no folder is opened.

**Comment by skyblue002** [comment]
@Jocs I like that idea. It's smart. It's very helpful for if a user is saving to multiple directories. This way the user will not have to change the directory manually if they open another folder and begin working with the files in it, but it's not the default.

**Comment by fxha** [comment]
>  think the default save directory need to be the opened folder?

That's already implemented on develop.

> then the default setting folder if no folder is opened.

I don't agree with you because the default startup directory is set as root directory, so if it's the first editor window it's already handled but not on second window which isn't a problem because it's only the startup directory.

**Comment by skyblue002** [comment]
> I don't agree with you because the default startup directory is set as root directory, so if it's the first editor window it's already handled but not on second window which isn't a problem because it's only the startup directory.

I'm not sure what you mean by this. But, I'm using tabs, not additional windows, so perhaps this doesn't apply to my case.

Will the feature to default to the specified directory when saving be included in the next release? I wasn't clear on that since it was removed from the `TO DO`.

**Comment by Jocs** [comment]
> Will the feature to default to the specified directory when saving be included in the next release? I wasn't clear on that since it was removed from the TO DO.

This feature is already added, and will release in version https://github.com/marktext/marktext/issues/1544, so stay tuned.
