### ISSUE TITLE
Code fence does not support php language

### ISSUE THREAD

**Issue by abeaczg** [marktext/marktext#162]
1,文字一多,变得很卡.（When the markdown file is too large, the Mark Text editor will become stuck #165）
2.代码区没有php支持..（Code fence does not support php language）

**Comment by Jocs** [comment]
@abeaczg 

>1,文字一多,变得很卡.

你好这个问题需要根据内容来排查，能将你打开很大的 markdown 文件发我邮箱吗？ransixi@gmail.com，所有内容仅作为开发 mark text 所用。

>2.代码区没有php支持..

Mark Text 内部使用的 codemirror，如果 codemirror 支持 PHP 的话，我会尽快添加上。如果你能够提一个 PR 的话，将非常感谢。

**Comment by Jocs** [comment]
@abeaczg 非常感谢你提的 issue。希望下次一个问题一个 issue，并且描述详细一些。
