### ISSUE TITLE
Change the default theme of js-sequence from hand-drawn to normal one

### ISSUE THREAD

**Issue by ioztelcan** [marktext/marktext#1628]
### Describe your feature request

I think the regular style of js-sequence diagram is much better than the wacky hand drawn version, perhaps the default can be changed?

### What problem does this feature solve? [optional]

It gets rid of hard to read hand-drawn sequence diagram theme and uses a more readable one.

**Comment by Jocs** [comment]
Thanks for report this issue, we maybe add a setting option to all diagrams' themes, user can select which theme to use.
