### ISSUE TITLE
 Problemas ao alterar do modo de código-fonte para o modo de máquina de escrever

### ISSUE THREAD

**Issue by HigorRozan** [marktext/marktext#163]
### Description

When I change to Source Code Mode I can't go back to Typewriter Mode, it just happen when I save the file 

### Steps to reproduce

1. Open a markdown file or save a file 
2. Change to source code mode 
3. Change to typewriter mode

**Expected behavior:** Go back to typewriter mode

**Actual behavior:**  Stay in souce code mode

### Versions

- Mark Text: v0.9.25 
- OS: Linux Ubuntu 16.04

**Comment by Jocs** [comment]
@HigorRozan You mean the `Typewriter mode` in the menu?

If you are editing in `source code mode`, You can not change to `Typewriter mode`, Because `source code mode` does not have `Typewriter mode`.

**Comment by HigorRozan** [comment]
Ok, thanks for helping.
