### ISSUE TITLE
Export doesn't work with two or more math expressions in one line

### ISSUE THREAD

**Issue by MoritzBrueckner** [marktext/marktext#1630]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a new file
2. Add two inline math expressions (some math between $...$ characters) into one line of text
3. Go to File > Export > PDF or HTML

**Expected behavior:**

A file dialog should open.

**Actual behavior:**

Nothing happens.

**Link to an example: [bug-md.zip](https://github.com/marktext/marktext/files/3815781/bug-md.zip)**
(GitHub doesn't allow .md files for upload)

### Versions

- Mark Text: v0.15.1
- Operating system: Windows 10 64bit

**Comment by Jocs** [comment]
@MoritzBrueckner This bug is already fixed on develop branch, and we'll release the new version in the middle of this month.

Thanks for reporting this bug.
