### ISSUE TITLE
What's the difference between this and BoostNote?

### ISSUE THREAD

**Issue by StewAlexanderACC** [marktext/marktext#1631]
The "best" markdown apps I have come across are [Boostnote](https://boostnote.io/) and [Bear](https://bear.app/l), what differentiates Mark Text from these two others?

I mean I understand building something "because you can", but recently there has been a flood of Markdown apps, you can even write mark down inside your browser with [StackEdit](https://stackedit.io/) or [Dillinger](https://dillinger.io/) which requires no app to download.

Me personally I value portability and export ability above all else, can I write my Markdown on my phone, finish it on my computer and export it to a consumable PDF or html page without breaking a sweat or going through 30 screens? If yes, success, if not I'll go elsewhere.

If **Bear** which I describe above was cross-platform that would be all I need, sorry to say it isn't. 

If something could store my Markdown in a private cloud where I can seamlessly start a doc on my iPhone and pick it up again on my Ubuntu / Windows / Mac desktop (I use all three as an engineer) and share it without hassle to social apps, or export it to a PDF / Photo / HTML doc - game changer

**Comment by kingvagabond** [comment]
Since you are comparing it with Boostnote or Bear, you just did not get the point. The alternative is typora, but typora is not open-sourced. That's the point.

**Comment by StewAlexanderACC** [comment]
Yeah, I see that after using it, as it auto-converts text on the fly to Markdown, I loved typora but it was buggy as hell

I got rid of BoostNote, prefer you all after using it for only 10 minutes.

Bear's feature I love is its phone app - desktop hand-off, you can start a note in Bear on the iphone, and continue with it on the Mac.

So, are you all up to developing a web app and or smartphone app for Android / iOS?

**Comment by Jocs** [comment]
@StewAlexanderACC Mark Text is a pure markdown editor, and not a note-taking app, it has not support labels, and will not help you save you content in database or else where. it save the content as markdown file. 

BTW, you can also use it as a note-taking app, you can open a default note folder every time you open Mark Text, (You can set the default open folder when startup Mark Text).

BTW, we also consider to develop a note-taking app, support labels and help users save their notes in DB or cloud(google drive, iCloud etc), and sync to other devices(Android/iOS), but it takes time.

Thanks for trying Mark Text.

**Comment by StewAlexanderACC** [comment]
Hmm, well there's the differentiation, this is a pure Markdown editor, rather than a Markdown note taking app... 

BoostNote should choose one or the other, it chooses neither and basically is weak at both.

I Still like your app, and if you ever want to get into the iPhone as an app let me know as I can provide some time to help.
