### ISSUE TITLE
Ability to search by filename in a folder tree

### ISSUE THREAD

**Issue by shadyabhi** [marktext/marktext#1633]
### Describe your feature request

A quick way to open files by filtering them by filenames. 

### What problem does this feature solve? [optional]

Currently, Find only searches for text inside files. It would be good to have a way to search files by filenames too. 

### Additional context [optional]

Similar to quick-open file feature in VSCode: https://code.visualstudio.com/docs/editor/editingevolved#_quick-file-navigation

**Comment by Jocs** [comment]
@shadyabhi This feature will be support in version 0.16.0, you can press `CmdOrCtrl + P` to open a quick open panel, and search and filter files in opened folder by filenames.

So stay tuned, and we'll release the new version(0.16.0) in the middle of this month.
