### ISSUE TITLE
Wrong shortcut symbols in block list

### ISSUE THREAD

**Issue by Lisiadito** [marktext/marktext#1635]
### Description
When adding a block by typing `@` I get shown the shortcuts for a Mac keyboard even tough I'm using the AppImage for Linux.
![image](https://user-images.githubusercontent.com/13214912/68338150-2d400280-00e2-11ea-8829-9cdd04b51af8.png)

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Type `@` 

**Expected behavior:**

I expect to see the correct shortcuts for my OS.

**Actual behavior:**

I see the wrong shortcuts.

### Versions

- Mark Text: v0.15.0
- Operating system: Linux Mint Mate 18.3

**Comment by Jocs** [comment]
@Lisiadito I got the shortcuts like bellow on macOS:

<img width="868" alt="截屏2019-11-07下午7 08 50" src="https://user-images.githubusercontent.com/9712830/68384210-18bb4300-0192-11ea-9b1a-587558414ed0.png">

@fxha can you help check whether it's wrong？

**Comment by fxha** [comment]
@Jocs These are macOS shortcuts, so they may confusing to non macOS users because they don't know what the symbols mean.

**Comment by Jocs** [comment]
>These are macOS shortcuts, so they may confusing to non macOS users because they don't know what the symbols mean.

i don't know the what's the look like of shortcuts on Linux and Windows, so can you submit a PR when you are convenient?

**Comment by fxha** [comment]
> > These are macOS shortcuts, so they may confusing to non macOS users because they don't know what the symbols mean.
> 
> i don't know the what's the look like of shortcuts on Linux and Windows, so can you submit a PR when you are convenient?

I guess `Ctrl`, `Alt` and `Shift` directly?

**Comment by Lisiadito** [comment]
In the menu you can see the correct shortcuts.
If you can give me an hint where I need to look to fix that I'm glad to open a PR
![image](https://user-images.githubusercontent.com/13214912/68386053-84ce8480-015b-11ea-9c64-5df6c21156b5.png)

**Comment by Lisiadito** [comment]
ok I think I found where they are specified.
`src/muya/lib/ui/quickInsert/config.js` 
If you're fine with it I will see if I can fix it and open a PR.

**Comment by Jocs** [comment]
@Lisiadito PR is welcome, you can use `isMac` and `isWin` in the folder.

<img width="1231" alt="截屏2019-11-07下午8 19 12" src="https://user-images.githubusercontent.com/9712830/68388587-faf2db80-019b-11ea-972c-877023f72b66.png">

**Comment by Jocs** [comment]
>Another question would be if we want to use ^ as a symbol for ctrl as it is already in use or use the word ctrl instead?

I think you can the word in the menu.
