### ISSUE TITLE
PortableApps Version of MarkText

### ISSUE THREAD

**Issue by jgonyea** [marktext/marktext#1636]
### Describe your feature request

Would you consider packaging the application to be PortableApps (*.paf.exe) compatible?  

### What problem does this feature solve? [optional]

I'd love to take the entire app, along with settings etc. with me on my flash drive without leaving data behind on the host PC.  I know I can just run the zip version from the flash drive, but that will leave data in the %appdata% folder.

Thanks either way.

**Comment by Fastidious** [comment]
I am afraid that’s not possible, as the application uses Electron. I am not fully sure, though, so I am curious as well for a more overwhelming answer.

**Comment by fxha** [comment]
> Would you consider packaging the application to be PortableApps (*.paf.exe) compatible?

I'm not familiar with PortableApps and we already have a portable mode build in but if anyone has interest in it, please feel free to create a bundle.

> I'd love to take the entire app, along with settings etc. with me on my flash drive without leaving data behind on the host PC.

You can create a directory called `marktext-user-data` to save all user data inside on Linux and Windows. Please see [here](https://github.com/marktext/marktext/blob/develop/docs/PORTABLE.md).

**Comment by jgonyea** [comment]
@fxha , Thanks!  This gets me 99.9% the way there.  I note that even if I pass in the parameter, the %appdata%/Mark Text/logs folder is still created on my system drive.

**Comment by jgonyea** [comment]
Should anyone come behind me and be looking for a paf compatible version of MarkText, I have a repo here: https://github.com/jgonyea/Mark-Text-Portable that repackages the zip version of MarkText into the PAF and leverages the aforementioned command-line parameter to force portable mode.

**Comment by fxha** [comment]
>  I note that even if I pass in the parameter, the %appdata%/Mark Text/logs folder is still created on my system drive (it is empty, however)

The directory is created by Windows setup and not by Mark Text. We using `marktext` or `marktext-dev` as settings directory.

**Comment by adrienbeau** [comment]
Testing this under Windows.

* Running `Mark Text.exe` (extracted from the 0.15.1 zip file) creates an AppData\Roaming\Mark Text directory.
* Running `Mark Text.exe` (extracted from the 0.16.0-rc1 zip file) does not create that directory.

So the directory issue is solved.

**Comment by RoyiAvital** [comment]
@adrienbeau , So the ZIP file contain a Portable version? I don't see any difference in it from the manually extracted installer. What's the difference which makes it portable?

**Comment by adrienbeau** [comment]
I do not use Mark Text anymore and do not think I have ever used the installer. It is entirely possible there is no difference between the extracted contents of the zip file and the extracted contents of the installer.
