### ISSUE TITLE
yarn dev fails with node 12.0.0

### ISSUE THREAD

**Issue by Lisiadito** [marktext/marktext#1637]
### Description

When running `yarn dev` I get following error:
```
#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
error Command failed with exit code 1.
```
It seems to work with node 10.16.3.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Use node 12.0.0
2. run `yarn dev`

**Expected behavior:**
That it runs the app in dev mode.

**Actual behavior:**
Process exits with error code.

### Versions

- Mark Text: 0.15.1
- Operating system: Linux Mint Mate 18.3

**Comment by Jocs** [comment]
@Lisiadito  Could you please upgrade your node and yarn to latest version and try again. thanks.

**Comment by Lisiadito** [comment]
@Jocs Thanks. With `node 12.13.0` and `yarn 1.19.1` it will start! I still have some Electron errors/warnings. But not sure how dramatic they are:
```
┏ Electron -------------------

  10:12:25.944 › Error while installing Hunspell default dictionary. Mark Text resources are corrupted!
  
  DevTools listening on ws://127.0.0.1:8315/devtools/browser/827139a4-22a8-4bf9-91a7-c70c9c27cc3a
  
┗ ----------------------------

┏ Electron -------------------

  (node:14851) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

**Comment by danielsouzat** [comment]
I'm getting this same error message in 0.16.1.

>Error while installing Hunspell default dictionary. Mark Text resources are corrupted!

### System
Mark Text: v0.16.1 (3a6182b)
Node.js: 12.13.0
Electron: 8.2.3
Chromium: 80.0.3987.163
OS: Linux x64 5.4.33-3-MANJARO

**Comment by fxha** [comment]
> I'm getting this same error message in 0.16.1.
> 
> > Error while installing Hunspell default dictionary. Mark Text resources are corrupted!
> 
> ### System
> 
> Mark Text: v0.16.1 (3a6182b)
> Node.js: 12.13.0
> Electron: 8.2.3
> Chromium: 80.0.3987.163
> OS: Linux x64 5.4.33-3-MANJARO

I think this is the same issue as in #2055.
