### ISSUE TITLE
Scroll bar will auto scroll to top

### ISSUE THREAD

**Issue by DMIAOCHEN** [marktext/marktext#164]
### Description
when scroll to bottom, then click any space that not empy, then the scrollbar will auto scroll to top.

### Steps to reproduce

**Expected behavior:** scrollbar will stay on

**Actual behavior:**auto scroll to top

### Versions

- Mark Text: v 0.9.25
- OS: Windows 10 Pro

**Comment by Jocs** [comment]
@DMIAOCHEN Can you show me some `gif` pictures of this issue, So I can fully understand what you described.

**Comment by DMIAOCHEN** [comment]
sorry, it's fine today:scream:, maybe some other cause. i will reopen this issue when it happend again

**Comment by stefnotch** [comment]
I can still reproduce this. Here is a test file:
```
## Step 1: Click here

- lorem --> lorem lorem

- lorem

  - lorem --> lorem lorem lorem lorem lorem lorem lorem lorem (lorem lorem lorem lorem lorem lorem lorem lorem)

  - [lorem](lorem://lorem.lorem.lorem/lorem/lorem/lorem/lorem/6.3/lorem-lorem-lorem.lorem): lorem, lorem lorem lorem, lorem, lorem'lorem lorem lorem

    > lorem lorem lorem lorem lorem lorem lorem lorem lorem, lorem lorem lorem lorem lorem lorem lorem lorem, lorem.lorem. lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem.

  - [lorem lorem]( lorem://lorem.lorem.lorem/lorem/lorem/lorem/lorem/lorem/lorem-lorem-lorem-lorem.lorem): lorem lorem <---------

- ```lorem
  "lorem": [
    {
      "lorem": {
        "lorem_
          "lore
          "lor
        }
      }
    },
    {
      "lorem": {
        "lorem_lore
          "lorem"
          "lorem"
        }
      }
    },
    {
      "lorem": {
        "lorem": {
          "lore
          "lorem"
        }
      }
    }
  ]
  ```

- Step 2: Scroll down

  - lorem lorem & lorem lorem lorem, lorem, lorem lorem lorem lorem lorem (lorem)

  - lorem lorem lorem lorem lorem

- lorem

- lorem

- lorem

- lorem

- lorem

- Step 3: click here
```

**Comment by fxha** [comment]
@stefnotch Which Mark Text version and OS did you use. I cannot reproduce this issue on Linux with v0.12.25.

**Comment by stefnotch** [comment]
@fxha I used Mark Text version 0.12.25. And, I'm using Windows 10. (Tested it on 2 different PCs, 100% reproduction rate)

Depending on your screen size, you could try clicking somewhere else (e.g. the code block) *after* you clicked on the heading and scrolled down.

**Comment by fxha** [comment]
Yes, if you click on the first and last line in a maximized window it jumps to the beginning of the document. However not if the windows is not maximized.

**Comment by Jocs** [comment]
@fxha @stefnotch Do you still can reproduce this issue in the latest version 0.13.50 ?

**Comment by stefnotch** [comment]
Can't reproduce
