### ISSUE TITLE
macOS: “Mark Text.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by MatanYadaev** [marktext/marktext#1649]
Tried using brew cask & dmg, I can't open the app.

**Comment by Jocs** [comment]
Please open the system preference and select 
<img width="649" alt="Screenshot 2019-11-08 at 9 26 35 AM" src="https://user-images.githubusercontent.com/9712830/68441699-e9e0b380-0209-11ea-950a-35acfffa3b52.png">

And click `open？` button.

**Comment by MatanYadaev** [comment]
Got it, after I launched the app I had an "open anyway" button.
Great app, I like it.

Any expectation to verify it with Apple Developer Program?
![button](https://cdn.winytips.com/wp-content/uploads/2019/10/Developer-or-app-cannot-be-verified-for-malware-1024x452.jpg.webp)

**Comment by Jocs** [comment]
>Any expectation to verify it with Apple Developer Program?

It need an Apple Developer ID, And Apple development id requires an annual fee of $99 per year. Currently, we don’t have any additional funds to cover this part of the cost.
