### ISSUE TITLE
language problem

### ISSUE THREAD

**Issue by limaonet** [marktext/marktext#1652]
My friend and I like your editor very much, but my friend is not very good at English. Can I add language options?

**Comment by limaonet** [comment]
Chinese option

**Comment by Jocs** [comment]
>My friend and I like your editor very much, but my friend is not very good at English. Can I add language options?

We'll support other languages in version 0.18.0, yeh, it will include Chinese. so stay tuned.

**Comment by chenrui9312** [comment]
waiting for, too

**Comment by chenrui9312** [comment]
> > My friend and I like your editor very much, but my friend is not very good at English. Can I add language options?
> 
> We'll support other languages in version 0.18.0, yeh, it will include Chinese. so stay tuned.

maybe you can shows the method first， and release the task to others
