### ISSUE TITLE
Stack pages toghether

### ISSUE THREAD

**Issue by lulucca12** [marktext/marktext#166]
### Description

You sould be able to stack multiple pages like in a browser

### Steps to reproduce
1. open a file
2. open another file

**Expected behavior:** be an option for stacking them both in just one window
**Actual behavior:** no option

### Versions

- Mark Text: 0.9.25
- OS: ALL

**Comment by Jocs** [comment]
`Tabs` and `Side Bar` are in the roadmap of version 1.0.0.

we will implement these features before version 1.0.0 released.

**Comment by Jocs** [comment]
@lulucca12 duplicated with #71 and I'll close it, thanks.
