### ISSUE TITLE
Logs folder created on system drive while in portable mode on Windows

### ISSUE THREAD

**Issue by jgonyea** [marktext/marktext#1661]
To reproduce bug:
- Extract zip version of MarkText onto a flash drive
- Run Mark Text with the `user-data-dir` pointing to a folder on the flash drive

Expected :
All data to remain on the flash drive

Observed:
On Windows, while in portable mode, an empty logs folder is still created on the system drive at `%appdata%\Mark Text\logs`

**Comment by fxha** [comment]
The directory is created by Windows setup and not by Mark Text. We using `marktext` or `marktext-dev` as settings directory.

**Comment by jgonyea** [comment]
I'd like to reopen this ticket, as I wasn't using the installer, but the zip file version of the app

**Comment by fxha** [comment]
@jgonyea Which version do you use? `Mark Text` is not used by us, maybe due to a bug in Electron or so. Did you try to remove the folder and try again?

**Comment by fxha** [comment]
Closing as this seems to be an issue with Electron 5 (v0.15.1) that is fixed with latest Electron.

**Comment by adrienbeau** [comment]
Testing this under Windows.

* Running `Mark Text.exe` (extracted from the 0.15.1 zip file) creates an AppData\Roaming\Mark Text directory.
* Running `Mark Text.exe` (extracted from the 0.16.0-rc1 zip file) does not create that directory.

So the directory issue is solved. (Sorry I left an identical comment in #1636.)
