### ISSUE TITLE
Math formula popup overlaps text

### ISSUE THREAD

**Issue by AndiLeni** [marktext/marktext#1664]
Hello,
when editing an existing line of math code, the popup with the formula preview overlaps the text in the line below it.

Here is a screenshot:
![grafik](https://user-images.githubusercontent.com/13385771/68528198-f2131e80-02ef-11ea-88a0-e1253a985fd2.png)

**Comment by Jocs** [comment]
This already fixed, please download the v0.16.0-rc.1 for test in the release page.
