### ISSUE TITLE
鼠标点击设置按钮无反应

### ISSUE THREAD

**Issue by cunyu1943** [marktext/marktext#1667]
### Description

使用时，鼠标点击设置按钮无反应

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. 打开marktext鼠标点击设置按钮

### Versions

- Mark Text: v0.16.0-rc.1
- Operating system: Windows10

**Comment by Jocs** [comment]
Thanks, we'll fix it before release v0.16.0.
