### ISSUE TITLE
图片地址乱码

### ISSUE THREAD

**Issue by LuckyHookin** [marktext/marktext#1668]
### Description

图片地址乱码。

- [x] Can you reproduce the issue? 

### Steps to reproduce

拖动图片到编辑框。

![2](https://user-images.githubusercontent.com/45350455/68542449-94fa9400-03e7-11ea-8ff2-055b88e0862b.gif)

### Versions

- Mark Text: v0.16.0-rc.1
- Operating system: windows 10

**Comment by jerryc127** [comment]
me too

**Comment by Jocs** [comment]
@fxha Can you help test this issue on Windows, and it works well on macOS, this issue describe that, drag image to Mark Text, and the image path is encoded and can not be display correctly.

**Comment by Jocs** [comment]
@jerryc127 Are you also Windows system?

**Comment by jerryc127** [comment]
> @jerryc127 Are you also Windows system?

Yes , windows10

**Comment by fxha** [comment]
I can confirm that this is an issue with Windows path separators (`\`).
