### ISSUE TITLE
feat: Get document title from markdown heading when exporting HTML/PDF

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#167]
Iterate through markdown/html and extract the highest heading and set it as document title when exporting HTML/PDF. Highest heading: `# > ## > .. > ###### > "Mark Text"`.

**Comment by Jocs** [comment]
@fxha there is nothing in the description! ❔

**Comment by Jocs** [comment]
`# > ## > .. > ###### > "Mark Text"` is the title or path?

**Comment by fxha** [comment]
I have reconsidered the idea  once again. Take `#` heading text (`h1`) as document title or "Mark Text" when exporting HTML/PDF.

E.g:

```markdown
# title

text
```

we would get `title` as title

```markdown
## subheading

text
```

we would choose `Mark Text` as document title.

**Comment by Jocs** [comment]
@fxha In my opinions.

if the edited file is saved, we can use the file name directly.

if the file is not saved, I recommend use the first 10 words in  document, for example:

```markdown
## title
```

if the length of `title` is less than 10, use the `title` directly, if its length is more than 10, use the first  10 words?

**Comment by fxha** [comment]
This sounds good, but I think it's better to take the `#` heading text if it's in the first line instead of the filename because filenames sometimes have `-` and `_` symbols in it.

**Comment by Jocs** [comment]
`#` heading sometimes also have `-` and `_` symbols ?

**Comment by Jocs** [comment]
@fxha we can recommend a default title when export HTML/PDF, and show a `save dialog` to let user edit the file name?

**Comment by Jocs** [comment]
@fxha I forgot that the interaction now already pops up a dialog...

**Comment by fxha** [comment]
> I forgot that the interaction now already pops up a dialog...

What? The save dialog?

Front Matter (#144) supports a `title` keyword. Maybe we should extract the tile from it.

**Comment by Jocs** [comment]
this [slugify](https://github.com/sindresorhus/slugify) lib may help us

**Comment by fxha** [comment]
I think we could use the library for table of contents and heading ids. So that we can use heading text as link id (`a öüäb@$"` -> `a-ouab`).

**Comment by Jocs** [comment]
good idea

**Comment by Jocs** [comment]
@fxha [slugify](https://github.com/sindresorhus/slugify) dose not support Chinese, So we used [markdown-toc](https://github.com/jonschlinkert/markdown-toc) directly.
