### ISSUE TITLE
[PreRelease] Diagrams do not show on HTML Export

### ISSUE THREAD

**Issue by carlosefonseca** [marktext/marktext#1670]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Add a mermaid diagram to a doc
2. Export as HTML
3. Open HTML

**Expected behavior:**

The diagrams shows on the web page.

**Actual behavior:**

The diagram shows as small rectangle without the diagram.

**Link to an example: [optional]**

![](https://dsc.cloud/carlosefonseca/Screen-Shot-2019-11-10-12-05-33.30.png)

### Versions

- Mark Text: v0.16.0-rc.1
- Operating system: macOS 10.14.6

**Comment by Jocs** [comment]
@carlosefonseca Thanks for report this bug, we'll fix it before version 0.16.0.
