### ISSUE TITLE
Re-Export

### ISSUE THREAD

**Issue by carlosefonseca** [marktext/marktext#1671]
### Describe your feature request

Add an option to re-export to HTML (and possibly PDF) with the same settings as before, without any prompt. Just hit the menu or hotkey and it's done.

### What problem does this feature solve?

When working on a document that will be exported to HTML, it's useful to export from time to time and checkout if it's looking good. Going through the settings and file naming every time is a bit annoying, specially if you want a certain filename and it keeps suggesting the document title (which is not a problem for one export).

**Comment by fxha** [comment]
Closing this issue as we currently don't plan to implement the feature but we may reopen it on demand.
