### ISSUE TITLE
Issue when paste lists

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1678]
### Description

There is an issue when copy and paste a task list in preview mode that the first list item is interpreted as bullet list item. Copy&paste an ordered list result always in a bullet one.

### Steps to reproduce

Paste the example below in preview mode, then copy the task-list from preview editor and paste it after a new paragraph:

```
- [ ] foo
- [ ] bar
- [ ] bar
```

**Expected behavior:**

```
- [ ] foo
- [ ] bar
- [ ] bar

foo

- [ ] foo
- [ ] bar
- [ ] bar
```

**Actual behavior:**

```
- [ ] foo
- [ ] bar
- [ ] bar

foo

- foo

- [ ] bar
- [ ] bar
```

### Versions

- Mark Text: develop?
- Operating system: all

**Comment by Jocs** [comment]
Reproduced this issue, I'll take a look.

**Comment by fxha** [comment]
@Jocs The issue above is fixed on develop but the first task list item is always checked.

**Comment by Jocs** [comment]
@fxha I'll take a look later.
