### ISSUE TITLE
Do not apply strikethrough to completed tasks

### ISSUE THREAD

**Issue by DanEble** [marktext/marktext#1680]
### Description

Mark Text renders checked task list items as struck through.  This differs from how GitHub renders them and makes it impossible to distinguish entries that are actually struck through from those that are not.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Enter this text
    ```
    - [x] Lorem ipsum dolor sit amet
    - [x] ~~Ut enim ad minim veniam~~
    ```

**Expected behavior:**

- [x] Lorem ipsum dolor sit amet
- [x] ~~Ut enim ad minim veniam~~

**Actual behavior:**

Both entries are struck through.

### Versions

- Mark Text: 0.15.1
- Operating system: macOS 10.15.1 (Catalina)

**Comment by Jocs** [comment]
I think a GitHub flavored theme will solve this issue, and do not mark checked task list as line through in this `GitHub flavored theme`, yeh, we'll add custom theme in version 0.17.0, in other some official themes, we maybe still use line through in checked task list item. what's your opinions?

**Comment by DanEble** [comment]
A GitHub-flavored theme would mostly solve the issue when creating GFM.  For the comfort of your users, you might also want to supply at least one dark theme that does not strike through completed tasks.  Thanks.

**Comment by adrienbeau** [comment]
This was also discussed in #1267.

I think DanEble makes a very good point for having the lines *not* struck through by default: there is no way to distinguish between text "struck through by markup" (in his second line) and text "struck through because the task is completed". Maybe the default theme should just use lighter grey text rather than black for completed tasks?

**Comment by HemaKanakamedala** [comment]
I have found a solution for this which works. Can i participate?

**Comment by DanEble** [comment]
Here's another idea.  You could triple-strike deleted text in a completed task entry.  My understanding is that CSS allows this, though I have not tested it.
```
text-decoration-line: line-through overline underline;
```
This is not my preference; I mention it only to help complete the options.

**Comment by Jocs** [comment]
<img width="575" alt="截屏2019-11-18上午12 34 14" src="https://user-images.githubusercontent.com/9712830/69010477-2bf0be80-099b-11ea-9cb8-25ce09beaf6a.png">

Triple-strike is a little odd, I prefer @adrienbeau saied, use a lighter grey color?

**Comment by DanEble** [comment]
Personally, I find it easier to read my document without the reduction in contrast—a check mark is enough to show that a task is complete—but if you want to keep the gray color, I won't complain.
