### ISSUE TITLE
双引号"问题

### ISSUE THREAD

**Issue by cunyu1943** [marktext/marktext#1681]
### Description

MarkText中写好的代码，copy到其他平台，`"、'、>、<`等符号渲染出错：
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. MarkText写好代码
![image](https://user-images.githubusercontent.com/22308895/68602207-e5095180-04e0-11ea-9d12-a383a5b41a8c.png)

2. Copy到其他平台（CSDN、简书等）
![image](https://user-images.githubusercontent.com/22308895/68602272-00745c80-04e1-11ea-8cc9-b6a0900cd865.png)

**Expected behavior:**
出现与Marktext相同效果；

**Actual behavior:**
未出现与Marktext相同效果；

### Versions

- Mark Text: v0.16.0-rc.1
- Operating system: Windows10

**Comment by Jocs** [comment]
@cunyu1943 我刚才复制到 GitHub 的评论框貌似没有问题，复制到 VSCode 也没有问题，除了简书和 CSDN， 还有其他平台有问题吗？

**Comment by fxha** [comment]
Closing as duplicate of #1821 because the other issue is written in English. @Jocs Please reopen this one if it's a different issue.
