### ISSUE TITLE
Can't add custom export themes

### ISSUE THREAD

**Issue by Jackeriss** [marktext/marktext#1689]
### Description
I tried to follow this [guide](https://github.com/marktext/marktext/blob/develop/docs/EXPORT_THEMES.md) to add a custom export theme but failed. There are always only the three built-in themes.

- [x] Can you reproduce the issue? 

btw，why the One Dark theme not a built-in export theme? That's the reason why I use marktext. It's stunning.

### Versions

- Mark Text: v0.16.0-rc.1
- Operating system: 10.14.6 (18G103)

**Comment by fxha** [comment]
Thank you for reporting this issue. 

```diff
- You can install a theme by copying the `.css` file to the [application data directory](APPLICATION_DATA_DIRECTORY.md) location but you may need to restart Mark Text to detect the theme.
+ You can install a theme by copying the `.css` file to `themes/export/` directory inside the [application data directory](APPLICATION_DATA_DIRECTORY.md) location but you may need to restart Mark Text to detect the theme.
```

**Comment by CaptSteel** [comment]
I tried following the same (updated) guide, there is no  `themes/export/` directory inside the application data directory.

**Comment by chenxuetao** [comment]
I also encountered the problem, and I just create the themes/export/ folders under %APPDATA% directory and move .css files into themes/export/ and that works.

**Comment by kittichat** [comment]
I created themes/export folders under "~/Library/Application Support/marktext" and move "css" file into it but none of them work. Could someone direct me in the right direction?

**Comment by GuardianTempest** [comment]
I got custom export themes to work on my end. The issue is due to the guide not pointing to the correct AppData Subfolder.

What I thought: Appdata\Local\Marktext

What I did: Appdata\Roaming\Marktext

<img width="630" height="600" alt="Image" src="https://github.com/user-attachments/assets/16a48ba3-47b0-46c9-ab90-e7e2af01a9f5" />
