### ISSUE TITLE
feature: left click context menu

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#169]
### Description

Some useful shortcuts will be listed in the left context menu, eg:

* copy as markdown
* copy
* paste
* paste as plain text
* Insert Image
* ...

If you have any advice, please let me know?

### Versions

- Mark Text: master
- OS: all platforms

**Comment by stefnotch** [comment]
Here is what some other markdown editors are doing with the right click menu:
### Sofish:
![sofish](https://camo.githubusercontent.com/9f2b62f592bfaf976c06842003f7cf1c360fc613/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3135333138332f313039333637312f36316434633064322d313661392d313165332d383865642d3031623137353861396134322e706e67)

### TOAST UI Editor 
![tui.editor](https://user-images.githubusercontent.com/1215767/34354831-5f04c7e6-ea74-11e7-9664-97f71c4fee6e.png)

### Typora
![Typora](https://user-images.githubusercontent.com/587790/27765620-7290c3b8-5e6b-11e7-83c3-3245459f195c.png)
