### ISSUE TITLE
Append new tasks as unchecked

### ISSUE THREAD

**Issue by DanEble** [marktext/marktext#1690]
### Describe your feature request

When a new task marker is created by pressing `Enter` at the end of a task list, leave it unchecked regardless of the state of the previous marker.  Example:

#### State before pressing `Enter`
☑︎ Duct tape \<cursor\>
#### Desired state after pressing `Enter`
☑︎ Duct tape\
☐ \<cursor\>

### What problem does this feature solve? [optional]

In my experience, I am most likely to add _incomplete_ tasks to the end of a list, so this feature would save me the step of having to uncheck the marker.  Thank you.

**Comment by Jocs** [comment]
@DanEble What's you Mark Text version? can you check the `v0.16.0-rc.1` in the release page?

**Comment by DanEble** [comment]
I was using Mark Text 0.15.1.  I tried the same with 0.16.0-rc1 and the problem has been fixed.  Thanks.
