### ISSUE TITLE
How can I make the content shows in wide mode?

### ISSUE THREAD

**Issue by chenyj796** [marktext/marktext#1695]
### Describe your feature request
Currently the content only use about 1/3 area of the screen.
I hope there is an option to set it shows in wide mode, almost the whole screen width.

**Comment by Jocs** [comment]
>Currently the content only use about 1/3 area of the screen.
I hope there is an option to set it shows in wide mode, almost the whole screen width.

You can set the edit area width in the setting window like bellow:

<img width="1251" alt="截屏2019-11-13下午12 50 39" src="https://user-images.githubusercontent.com/9712830/68734177-5f86be00-0614-11ea-8b18-2c38428a336e.png">

**Comment by chenyj796** [comment]
Thanks @Jocs , I got it.
Maybe we can set it to 100% as default value.

**Comment by Jocs** [comment]
>Maybe we can set it to 100% as default value.

I prefer the value in the theme. BTW, we can change the value in theme when we add custom theme.
