### ISSUE TITLE
can not open file with uppercase extension

### ISSUE THREAD

**Issue by liziqiang** [marktext/marktext#1696]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. create file with name aaa.MD
2. select that file
3. nothing happens

**Expected behavior:**

open selected file

**Actual behavior:**

Nothing happens

**Link to an example: [optional]**

### Versions

- Mark Text: all
- Operating system: all

**Comment by Jocs** [comment]
Thanks！
