### ISSUE TITLE
Can not open bold or italic hyperlinks through Cmd+Click

### ISSUE THREAD

**Issue by aJIEw** [marktext/marktext#1698]
### Description
I just switched to MarkText from Typora, and I found that I can't open a Bold or Italic hyperlink text with cmd+click, maybe someone can tell me why? 

### Steps to reproduce
Add bold or italic style to a hyperlink text, and try to use cmd+click to open it.

**Expected behavior:**
Open the link in a browser.

**Actual behavior:**
Nothing happened.

### Versions
- Mark Text: v0.15.1
- Operating system: Mac OS X 10.15.1

By the way, thanks for building such a wonderful tool you guys, great work!

**Comment by Jocs** [comment]
@aJIEw Can you show me you markdown content? because I can pen bold link by CMD + click.

**Comment by aJIEw** [comment]
Hi @Jocs , I made a gif.
![mark_text_bold_link.gif](https://i.loli.net/2019/11/18/1ygbJBiVpMqT48h.gif)

**Comment by Jocs** [comment]
@aJIEw Thanks, I reproduce it. PR is also welcomed.

**Comment by MrHeer** [comment]
In this case, the `LinkTools` also doesn't work
