### ISSUE TITLE
Enable MindMapping / Outlining using markmap

### ISSUE THREAD

**Issue by retrography** [marktext/marktext#1699]
MarkText now supports diagrams and charts. It would be great to be able to use [markmap](https://github.com/dundalek/markmap) to render an outline / mindmap in a document.

**Comment by Jocs** [comment]
I hope you describe your needs in detail. Do you need to just display the headings as a mindmap? Or the entire markdown as a mindmap, or add a mindmap block. Used to display mindmap separately, similar to the current mermaid and so on.

**Comment by retrography** [comment]
You are right, I may not have been very forthcoming with the details.

What I was thinking of was to be able to have a mind map block, just like the other blocks. But actually, anything works for me. 

I do think that it is more consistent with the spirit of the current developments to have it as a block. But we can also imagine having an outlining / mind map view that allows us to start outlining the document and then proceeding to the write up in the normal view. 

Both can be very useful.

**Comment by Jocs** [comment]
I prefer to support markmap via plugin, please discuss under #375
