### ISSUE TITLE
Change install path so that Admin rights aren't required. [Window]

### ISSUE THREAD

**Issue by hughwilliams94** [marktext/marktext#17]
### Description

Hey thanks for the app, it looks great. Is there any way you could think about changing the default installation directory from C:\Program Files\ to a less privileged location. I would love to install the app on my work laptop but don't have admin rights. Another option would be to make the installation path configurable.

### Steps to reproduce

1. Download Windows binary and try to install.
2. Installation prompts for admin login

**Expected behavior:** [What you expected to happen]

Download binary and try to install, program installs either to a user directory (e.g. C:\Users\$USER\AppData\Roaming) or prompts for install path.

### Versions

- Mark Text: v.0.6.14
- OS: Windows 7

**Comment by notAlaanor** [comment]
Fixed with #18

**Comment by Jocs** [comment]
@notAlaanor 👍
