### ISSUE TITLE
Integrated Git or integrated command line window

### ISSUE THREAD

**Issue by barlowliu** [marktext/marktext#1701]
Writing documentation is often used with version management, but since there is no integrated git (and no command line window), I need to open a new command line window for version commit after each edit.

**Comment by Jocs** [comment]
Mark Text is just a pure markdown editor, why not use another shell or terminal to use git?

**Comment by fxha** [comment]
@Jocs I think this is outside of the scope of Mark Text, so we should close the issue.

**Comment by Drallas** [comment]
I also would like to have support for Git Commit / Push from the editor?
Some of my libraries are connected to a Github / Gitlab repository and now i need to leave Mark Text to sync upstream. I don't think this is out of scope, it's a normal feature that some user expect!
