### ISSUE TITLE
Cannot open md file that was saved as UTF8 with BOM

### ISSUE THREAD

**Issue by arcqiufeng** [marktext/marktext#1703]
### Description

 无法打开含有BOM的UTF8文件
Cannot open md file that was saved as UTF8 with BOM

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. just open a file that previous edited by other application and saved as utf8 with bom.
> see attachment.
[sample.zip](https://github.com/marktext/marktext/files/3845152/sample.zip)

2. marktext prompt the following: cannot open the tab

**Expected behavior:**

Just like typora, no error prompt.

### Versions

- Mark Text: 0.15.1
- Operating system: Microsoft Windows 10 (1903)

**Comment by fxha** [comment]
Thanks for reporting this issue. I'm closing this issue because it's a problem with all versions <=0.15.1 due to a problem with BOM encoding but it was fixed in our first release candidate of v0.16.0.
