### ISSUE TITLE
Cannot open markdown file with the filename extension uppercased as "MD"

### ISSUE THREAD

**Issue by arcqiufeng** [marktext/marktext#1705]
### Description

Mark Text cannot open the file that name as "*.MD".  The filename extension is uppercased.

- [x] Can you reproduce the issue? 

### Steps to reproduce

Just as title.

### Versions

- Mark Text: 0.15.1
- Operating system: Windows 10 (1903)

**Comment by aJIEw** [comment]
duplicate issue for #1696, it's been fixed, I think they will release it on v0.16.0, feel free to close this issue.

**Comment by arcqiufeng** [comment]
Yes, it is duplicate.
