### ISSUE TITLE
The "Preferences" button (cog icon) does not work anymore

### ISSUE THREAD

**Issue by hrvojegolcic** [marktext/marktext#1706]
### Description

Clicking the "Preferences" button (cog icon) in the bottom left corner of the editor does not work anymore. Nothing happens when clicked.

In previous version 0.15 the issue does not exist and it behaves as expected.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Click the "Preferences" icon in the bottom left corner of the editor

**Expected behavior:**

Preferences dialog should open

**Actual behavior:**

Nothing happens when clicked

### Versions

- Mark Text: v0.16.0-rc.1
- Operating system: Win 8.1

**Comment by MrHeer** [comment]
I have the same problem.

**Comment by MrHeer** [comment]
I want to fix it.
