### ISSUE TITLE
Add support for automatic micro-typography 

### ISSUE THREAD

**Issue by virtualritz** [marktext/marktext#1711]
Convert quotation marks.
'foo' becomes ‘foo’ 
"bar" becomes “bar”

Convert dashes to long(er) dashes.
“it is -- marvelous” becomes “it is – marvelous”
“Paris---London” becomes “Paris—London”

Convert apostrophes.
“Helen's hiccup” becomes “Helen’s hiccup”

English only for starters. Other languages have other rules.
If Mark Text ever supports different languages, this can be added.

**Comment by fxha** [comment]
Thanks for your suggestion but this is currently out of the scope of the project.

**Comment by vinliao** [comment]
Hey @virtualritz I know this feature won't be supported anytime soon. You get any workaround with this?

Is there any web app out there that can automatically convert all the dashes and quotations?
