### ISSUE TITLE
Want Support for "==text==" highlight element

### ISSUE THREAD

**Issue by arcqiufeng** [marktext/marktext#1712]
### Describe your feature request

Want Support for "==text==" highlight element

### What problem does this feature solve? [optional]

Just as title. Action as in typora highlight enabled

**Comment by Jocs** [comment]
Does any markdown standard(or flavor markdown) support this syntax to highlight? Currently we only support commonmark Spec and GFM, as well as some other extensions.

**Comment by adrienbeau** [comment]
See also #1529 which seems to implement the same feature, with a different syntax (more verbose, but more versatile).

**Comment by arcqiufeng** [comment]
> See also #1529 which seems to implement the same feature, with a different syntax (more verbose, but more versatile).

thank you for reply. I've got the marktext-style way to highlight text. <mark>xxx</mark> can solve it.

**Comment by fxha** [comment]
Closing this issue as it's no standard markdown and we already support the HTML part.
