### ISSUE TITLE
The badge in title can't normally render

### ISSUE THREAD

**Issue by tjx666** [marktext/marktext#1714]
### Description
The badge insert to title can't normally render

source:

```
## :handshake: Contributing [![PRs Welcome](https://img.shields.io/badge/PRswelcome-brightgreen.svg?style=flat-square)](http://makeapullrequest.com)

非常欢迎提出你的宝贵意见和 pull request。
```

- [x] Can you reproduce the issue? 

### Steps to reproduce

Just copy the source code to markText to see the render result

**Expected behavior:**

github render result:

![Snipaste_2019-11-16_19-14-22](https://user-images.githubusercontent.com/41773861/68992367-637d3f00-08a5-11ea-9793-c4d73308dbc2.png)

**Actual behavior:**

markText render result: 

![Snipaste_2019-11-16_19-13-17](https://user-images.githubusercontent.com/41773861/68992356-3761be00-08a5-11ea-8228-7a50454bdb62.png)

**Link to an example: [optional]**
[refine nowcoder README](https://github.com/tjx666/refined-nowcoder/blob/master/README.md)

### Versions

- Mark Text: v0.15.1
- Operating system: win10 pro 1909

**Comment by Jocs** [comment]
<img width="559" alt="截屏2019-11-18上午12 28 16" src="https://user-images.githubusercontent.com/9712830/69010391-58f0a180-099a-11ea-8e98-a8fdc6af1ae7.png">

Already fixed in v0.16.0, you can download v0.16.0-rc.01 for test.
