### ISSUE TITLE
jumpClick can't jump to another file

### ISSUE THREAD

**Issue by MrHeer** [marktext/marktext#1721]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. prepare test1.md and test2.md in the same directory
2. open test1.md in MarkTest and add `[test2](./test2.md)`
3. hover on `test2` and you can see the `LinkTools`
4. click the second `JumpIcon`, not work

**Expected behavior:**

jump to test2.md like CTRL+CLICK

**Actual behavior:**

nothing

**Link to an example: [optional]**

### Versions

- Mark Text: [develop](https://github.com/marktext/marktext/commit/11dfa2529dfd948dd40edba3539134a6e6d4b735)
- Operating system: elementary OS 5.0 Juno

**Comment by MrHeer** [comment]
Here only deal with the situation start with `http` 
https://github.com/marktext/marktext/blob/11dfa2529dfd948dd40edba3539134a6e6d4b735/src/renderer/components/editorWithTabs/editor.vue#L678-L683

**Comment by MrHeer** [comment]
I want to try fix it, can I PR for this?

**Comment by Jocs** [comment]
@MrHeer Yes, of course, thanks.
