### ISSUE TITLE
MacOS auto Light/Dark Mode not working as expected

### ISSUE THREAD

**Issue by bitterbit** [marktext/marktext#1723]
### Description
When setting MacOS appearance (dark mode) to auto, All apps will switch to dark mode except for MarkText which will stay in light mode.

- [x] Can you reproduce the issue? Yes

### Steps to reproduce
1. On macos preferences set General > appearance to "auto"
2. Wait to change from day to night
Or
1. Wait to night
2. Select appearance "auto"

**Expected behavior:**
Dark mode should be used

**Actual behavior:**
Stays in regular mode. Changing the mode manually in the MacOS global preferences doesn't fix the problem. It will toggle to dark mode when all apps change back to regular mode. 

**Link to an example: [optional]**

![ezgif-5-73f4772fbbdd](https://user-images.githubusercontent.com/4591339/69067502-d4e6fa00-0a2b-11ea-9c53-44f0551dfa1b.gif)

### Versions

- Mark Text:  v0.15.1
- Operating system: MacOS Catalina

**Comment by Jocs** [comment]
Thanks for your feedback, because Electron's API has changed, but the new API does not have a complete documentation, so we have not yet fully adapted, and of course you are welcome to submit a PR.

**Comment by bitterbit** [comment]
@Jocs I saw the following line in the master branch (`src/main/app/index.js`)
```js
systemPreferences.subscribeNotification(
        'AppleInterfaceThemeChangedNotification',
        () => {
// ... 
```

But it does not exist anymore on the develop branch. Did someone fix the issue already?

**Comment by Jocs** [comment]
@bitterbit We have move to use [nativeTheme](https://github.com/electron/electron/blob/660e56620130ba96a729d5630f5ee3e87e2168e0/docs/api/native-theme.md) module, because `systemPreferences.subscribeNotification` only work for `macOS` system. but `nativeTheme` seems not work well now.

**Comment by Jocs** [comment]
The relative codes are in this file    https://github.com/marktext/marktext/blob/fc15356b9b9155793b2172c60759d2ac61721e43/src/main/app/index.js#L161

**Comment by fxha** [comment]
@bitterbit You can see the equivalent [here](https://github.com/marktext/marktext/pull/1543/commits/2cb29d309e9b9376ba804e1fa1b4d20483db0ca6) but there are definitely bugs in there because it behaves differently on each OS.

@Jocs `systemPreferences.subscribeNotification` API is deprecated for theme stuff and with latest macOS you cannot longer detect the system theme, only the active application theme acording Electron team - so the API should be broken.

**Comment by bitterbit** [comment]
@fxha I see what you say about the api being deprecated. Looks like the code changed quite a bit from the release version I had been using. I'll wait to see if the issue is fixed in the next release 😸

**Comment by fxha** [comment]
>  I'll wait to see if the issue is fixed in the next release

We removed automatically theme changing at runtime and only detect the native theme at application startup, if preferred.

**Comment by fxha** [comment]
Closing this issue as we remove  theme changing at runtime.
