### ISSUE TITLE
Search when invoked should get prefilled from the currently selected text

### ISSUE THREAD

**Issue by hrvojegolcic** [marktext/marktext#1729]
# Description

Unlike the global search (Ctrl+Shift+F) the local search (Ctrl+F) when invoked gets prefilled from the currently selected text as a search query.

I don't know if the behavior is intentional but in my opinion the global search should also get prefilled from the currently selected text.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Select some text within the current document
1. Press Ctrl+Shift+F to invoke the global search
1. The global search sidebar appears

**Expected behavior:**

The search query input field should receive the focus.
The search query input field should be prefilled from the currently selected text, similarly how the local search is implemented.

**Actual behavior:**

The search query input field is not focused nor prefilled.

### Versions

- Mark Text: 0.15.x and 0.16.x
- Operating system: Win 8.1

**Comment by MaanasArora** [comment]
Can I work on this issue?

**Comment by Jocs** [comment]
@MaanasArora Yes, you are always welcomed to make PRs.

**Comment by RicardoHE97** [comment]
@MaanasArora Did you manage to solve the issue? If not I would like to work on it as well :)

**Comment by Henry78** [comment]
As of v16 (see #1311) the search box is prefilled with currently highlighted text in global search. But the box is still not focussed. And I'm not able to unfocus/return on hitting 'Esc'

**Comment by Henry78** [comment]
I added the more specific issue #2294 for the unimplemented parts of this issue. So I think this issue may be closed.
