### ISSUE TITLE
insert image

### ISSUE THREAD

**Issue by scuzhangzhang** [marktext/marktext#173]
###Sometimes ，Inserting  a image doesnt work ,i have to close the marktext and open again 

### Versions

- Mark Text:
- OS:  windows 10

**Comment by Jocs** [comment]
@scuzhangzhang HI, 能够描述得详细一些吗？可以直接中文的。
1. 用什么方式插入图片。
2. 具体步骤。
3. 按着 issue template 的格式。

**Comment by Jocs** [comment]
@scuzhangzhang I'll close this issue if no more info. if you add more detail I'll re-open it.
