### ISSUE TITLE
Do not change the file content when it is opend

### ISSUE THREAD

**Issue by deathrush** [marktext/marktext#1731]
### Describe your feature request

Now the software will automatically change the lines of a existing file.

I hope it will no longer change the opened files.

### What problem does this feature solve? [optional]

Even if I doesn't change any character, when closing it, the software need I to confirm the change.

**Comment by Jocs** [comment]
duplicate with #912 ?

**Comment by fxha** [comment]
Mark Text automatically formats the document and from version 0.16.0 we automatically identify the trailing newline mode.
