### ISSUE TITLE
To-do list indentind wrong while switch Souce Code Mode

### ISSUE THREAD

**Issue by MrHeer** [marktext/marktext#1733]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. open Mark Text and  turn on `Souce Code Mode`, then input this

``` markdown
- [ ] task1
  
  - [ ] task1_1
    
    - [ ] task1_1_1
```
2. turn off `Souce Code Mode`

**Expected behavior:**

- [ ] task1
  - [ ] task1_1
    - [ ] task1_1_1

**Actual behavior:**

- [ ] task1
  - [ ] task1_1
  - [ ] task1_1_1

### Versions

- Mark Text: v0.16.0-rc.1
- Operating system: Windows 10

**Comment by IvanFrescas** [comment]
Hi, can I work on this?

**Comment by fxha** [comment]
@IvanFrescas Your contribution is welcome.

**Comment by qihuazhong** [comment]
experiencing the same issue.
The editor would just undo any indentation further than 2nd level

**Comment by fxha** [comment]
Yes, this issue is also triggered when switching tabs or opening a file. Short summary: all nestled task list items (`I > 2` where `I` is the list indentation starting at `1`) are formatted and saved as level two task list items.
