### ISSUE TITLE
Files ending with an empty blockquote don't render

### ISSUE THREAD

**Issue by mrhelmut** [marktext/marktext#1735]
### Description

Hello there!

I noticed that when a file ends with an empty blockquote, MarkText will not be able to render it and won't allow to be edited anymore. If there is multiple tabs opened, MarkText will show the last rendered file instead of the one it can't render.

Cheers! Keep up the good work!

- [x] Can you reproduce the issue? 

### Steps to reproduce

Create a file with this content:

```
Some text

>
```

Try to open it with MarkText.

**Expected behavior:**

File should render normally and be editable.

**Actual behavior:**

The file doesn't render (blank page) or that tab contains the previously rendered file if multiple ones are open and it can't be edited.

### Versions

- Mark Text: 0.15.1
- Operating system: Windows 10 (build 1903)

**Comment by Jocs** [comment]
@mrhelmut Thanks for report this issue, we'll fix it asap.
