### ISSUE TITLE
set hyperlink in table not working

### ISSUE THREAD

**Issue by liziqiang** [marktext/marktext#1749]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. create a table
2. input something in a cell
3. press cmd + L or use the popover menu to add hyperlink

**Expected behavior:**

can add hyperlink

**Actual behavior:**

nothing happens

**Link to an example: [optional]**
![(null) 2019-11-23 10_02_08](https://user-images.githubusercontent.com/208130/69471271-69f54480-0dd8-11ea-96c1-2fc5fdfe92a8.gif)

### Versions

- Mark Text: 0.16.rc2
- Operating system: MacOS 10.15.1

**Comment by Jocs** [comment]
I test this issue, and all inline tools can not work in table cell.
