### ISSUE TITLE
Copy and paste text with subscript will lose the <sub> tag

### ISSUE THREAD

**Issue by AlexanderMisel** [marktext/marktext#1754]
# Description
Copy and paste text with subscript will lose the `<sub>` tag, even inside marktext.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Type `E<sub>1</sub>` in view mode
2. Copy and paste the E<sub>1</sub>

**Expected behavior:**

The pasted text should be the same as copied.

**Actual behavior:**

The E<sub>1</sub> becomes E1

### Versions

- Mark Text: 15.1
- Operating system: Windows 10

**Comment by fxha** [comment]
Closing as this issue is already fixed on develop and v0.16.0 release candidate.
