### ISSUE TITLE
文字无法录入

### ISSUE THREAD

**Issue by morehardy** [marktext/marktext#177]
#### 在使用 # 后无法直接输入文字,需要额外的空格之后,文字才能录入

**Actual behavior:**
无法紧跟#之后录入文字,编译器会解析空格,造成排版混乱

**Example:**
![1](https://user-images.githubusercontent.com/30150764/38910247-0210b3e4-42fb-11e8-8bde-c181ea357fc7.gif)

### Versions

- Mark Text: 0.10.21
- OS: windows 10

**Comment by Jocs** [comment]
@morehardy 什么输入法？

**Comment by hungtcs** [comment]
@morehardy 标准markdown的标题写法应该是`###`后面有跟空格的吧
```
###这里不解析为标题
### 这里解析为标题
```

**Comment by morehardy** [comment]
搜狗输入法

**Comment by morehardy** [comment]
@hungtcs 
我试过这样写,只写一个空格一样有 bug, 只有两个以上空格才能输进去,但这样空格会解析,排版乱了

**Comment by hungtcs** [comment]
@morehardy 那应该和我遇到的问题是一样的，不过我在ubuntu上使用搜狗输入法没问题，fcitx-pinyin有这个问题

**Comment by Jocs** [comment]
@hungtcs 标准中，`#` 后面是必须有空格的，我还在考虑是否需要严格按照标准。

**Comment by jimmyko** [comment]
建議：第一次輸入空格外的字元時提示要求輸入空格去設定標題格式，第二次再輸入空格外字元時直允許輸入但不進行標題格式化。

**Comment by Jocs** [comment]
@jimmyko 在下一个版本，会严格要求在`#` 后面输入一个空格来表示标题。
