### ISSUE TITLE
Spelling seems to not be enabled?

### ISSUE THREAD

**Issue by albins** [marktext/marktext#1770]
### Question description

I have installed MarkText through the homebrew cask on macOS Mojave, and I cannot find anything related to spelling, including in the settings, despite having a working hunspell setup. Reading the manual, I could not find any additional instructions about what to do.

**Comment by fxha** [comment]
@albins  Thanks for your question, I guess you are using v0.15.1, right? Spelling is only available in the latest release candidate that can be downloaded from Github and further v0.16.0. The documentation is currenlty for the latest develop version and need to be split into stable and develop after v0.16.0 release.

**Comment by albins** [comment]
I am; thank you. It works as expected when I build from source :)
