### ISSUE TITLE
[Feature Request] Add an option to enable word wrap in outline

### ISSUE THREAD

**Issue by PowerSnail** [marktext/marktext#1772]
### Describe your feature request

Add an option to enable word wrap in outline.

### What problem does this feature solve? [optional]

Some articles/books/documents have long titles that are not well displayed in the current outline view. Either it displays only a few words, or the user has to resize the sidebar to very wide. Neither is an ideal option. 

This is less of a problem for technical documents since they have short headings. However, in different writing styles, long chapter titles can be appropriate and widely used. For example, in the famous book _Candide_ by Voltaire, the chapter titles easily exceed 15 words. 

When long titles are truncated, they become incomprehensible. Hence, it defeats the purpose of the outline bar.

Thanks.

**Comment by Jocs** [comment]
How about show the `...` when the headers is too long, and show the full content when hover on the header?

**Comment by PowerSnail** [comment]
I don't think showing full content while hovering solves the problem. First, there is an accessibility issue (requiring a mouse); second, the user still cannot look at the outline and directly read out the structure.
