### ISSUE TITLE
Changing font failed if there are chinese characters in the font's name

### ISSUE THREAD

**Issue by LosikiS** [marktext/marktext#1773]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1.Open the preferences and change font in the Editor tab, if there is a chinese character, this change is invalid.

**Expected behavior:** Change font successfully

**Actual behavior:** The font has not changed

**Link to an example: [optional]**
<img width="202" alt="捕获" src="https://user-images.githubusercontent.com/33153388/69894856-848f6680-1360-11ea-94ee-cebc213382a3.PNG">
<img width="190" alt="捕获2" src="https://user-images.githubusercontent.com/33153388/69894858-8822ed80-1360-11ea-8bd0-e8fc212d6aba.PNG">
<img width="195" alt="捕获3" src="https://user-images.githubusercontent.com/33153388/69894860-8b1dde00-1360-11ea-8e00-8d2d264b339c.PNG">

### Versions

- Mark Text: v0.16.0-rc.2
- Operating system: Windows 10 1903

**Comment by fxha** [comment]
@Jocs Any ideas here? The issue is that we restrict the allowed font family name to `^[_A-z0-9]+((-|\s)*[_A-z0-9])*$` to prevent bad input and I also don't know whether Chromium supports non-ASCII font family names.

**Comment by Jocs** [comment]
>The issue is that we restrict the allowed font family name to ^[_A-z0-9]+((-|\s)*[_A-z0-9])*$ to prevent bad input and I also don't know whether Chromium supports non-ASCII font family names.

Yes, `微软雅黑` is an valid font family name, so I think we should not restrict the allowed font family name to `^[_A-z0-9]+((-|\s)*[_A-z0-9])*$`. Maybe we only need to exclude some special characters?
