### ISSUE TITLE
Directory switching does not work properly

### ISSUE THREAD

**Issue by LosikiS** [marktext/marktext#1775]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce
![a](https://user-images.githubusercontent.com/33153388/69908840-17e19e00-142c-11ea-83d3-7a8d079c3c6e.gif)

### Versions

- Mark Text: v0.16.0-rc.2
- Operating system: Windows 10 1903

**Comment by fxha** [comment]
@Jocs I guess there is an issue with slugifying non-ASCII characters.

**Comment by Jocs** [comment]
@LosikiS Can you send us an example test markdown file which can not work to ransixi@gmail.com

**Comment by YalandHong** [comment]
> @Jocs I guess there is an issue with slugifying non-ASCII characters.

Non-ASCII? It seems that the same issue also happens to simple ASCII characters (#1916 ).

I also encounter this problem.

**Comment by Jocs** [comment]
@YalandHong Can you send me a test file ransixi@gmail.com, and remark the issue number. thanks.

**Comment by shootheart** [comment]
I am having the same issue.

MarkText v0.16.3
Windows 10 Pro 1909

**Comment by sammaddens** [comment]
I also have the same issue with the following Windows scale settings: 125% and 1920x1080.

![Resolution](https://user-images.githubusercontent.com/53434469/106661903-0ea90f80-65a2-11eb-85fb-9577d9589c42.jpg)

Changing the scale to 100% (or changing the resolution) gives a normal behaviour.

MarkText v0.16.3
Windows 10

**Comment by XavierCLL** [comment]
Hi @fxha all these issues (this one + #2424 #2471) are related to a HiDPI scaling problem (I can confirm these issues)

you can reproduce these problems running Marktext as: `marktext --force-device-scale-factor=1.5` (any scale factor not equal to 1)

**Comment by kebinzhi** [comment]
> Hi @fxha all these issues (this one + #2424 #2471) are related to a (maybe the same) HiDPI scaling problem (I can confirm these issues on Linux)
> 
> you can reproduce these problems running Marktext as: `marktext --force-device-scale-factor=1.5` (any scale factor not equal to 1)

Only useful when the scale value is an integer in Windows 10.

**Comment by Weijun-Lin** [comment]
@sammaddens 
it does work correctly, but the blurry is also unbearable.
Hope Marktext can fix it in future version, can make it more excellent.
Thanks to all developers.

**Comment by song-bate** [comment]
it does work correctly, but the blurry is also unbearable.
Hope Marktext can fix it in future version, can make it more excellent.
Thanks to all developers.

**Comment by YYorozuya** [comment]
Override the high DPI scaling for MarkText only does fix the problem, but after that the text and interface become quite blurry.
