### ISSUE TITLE
Allow to jump to heading from link reference

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1780]
### Describe your feature request

The preview editor should be able to jump to the linked heading from a URL like the sidebar.

### What problem does this feature solve? [optional]

It would make it easier to reference other headings and navigate through the document in preview editor.

### Additional context [optional]

```md
# Heading 1

foo

## Heading 2

foo

[...]

foo [ref to Heading 2](#heading-2) bar

**Comment by Jocs** [comment]
This feature request and [internal link with header identifiers](https://github.com/marktext/marktext/issues/1528) seem to solve the same problem? If you use the header content as the id, this will have special characters, which is not easy to handle, so I prefer the header identifiers.

**Comment by fxha** [comment]
I don't think it's a duplicate because all headers are slugifyed by default and we can link to the id for ASCII headings like in exported documents.

**Comment by fmg-dave** [comment]
+1

**Comment by alfredo-mejia** [comment]
Hi, I would like to work on this feature. I never contributed to open source but I've read the contributing documentation and would like to have this feature implemented.

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2469. You may want to subscribe there for further updates.
