### ISSUE TITLE
The shortcuts of SAVE AS and SOURCE CODE MODE are conflicted

### ISSUE THREAD

**Issue by mice33** [marktext/marktext#179]
如题

**Comment by Jocs** [comment]
@mice33 Yeh, My fault, Do you have any good idea for the shortcut of `source code mode` ?

**Comment by mice33** [comment]
`Ctrl+Shift+V` 如何

**Comment by Jocs** [comment]
直接 `Shift + V` 会有冲突吗？

**Comment by fxha** [comment]
@mice33 `Ctrl+Shift+V` is reserved to paste text without formatting.

**Comment by Jocs** [comment]
@fxha Do you have any idea for this shortcut of `source code mode`?

**Comment by mice33** [comment]
唔，按着有点别扭..`Ctrl+U` 呢？
