### ISSUE TITLE
Unexpected error: net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by Endogen** [marktext/marktext#1796]
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Version

Mark Text: v0.16.0-rc.1
Operating system: Windows_NT x64 10.0.17763 (win32)

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. We cannot reproduce this issue without steps to reproduce, please provide some steps or how the error occurred.

**Comment by Jocs** [comment]
Closed due to can not reproduce.

**Comment by JeremyLormand** [comment]
upon booting my PC I get this JS error in a window.  Error: net::ERR_HTTP_RESPONCE_CODE_FAILURE  How can I fix it?
