### ISSUE TITLE
Export to Image and CSS suport

### ISSUE THREAD

**Issue by phoenixray2000** [marktext/marktext#1807]
### Describe your feature request

1. Export to Image file or Clipboard is very useful when sharing ideas with nice format.
2. CSS support is critical when we want a customized look

### What problem does this feature solve? [optional]

Easy to share in IM and social media with good format control.

**Comment by fxha** [comment]
> Export to Image file or Clipboard is very useful when sharing ideas with nice format.

What are the benefits from adding image support? You could also export the document as PDF, that is supported on all OSs and also convert it into other formats.

> CSS support is critical when we want a customized look

Please see [themes (export)](https://github.com/marktext/marktext/blob/develop/docs/EXPORT_THEMES.md) for more information that are supported with latest release candidate or develop.

**Comment by Jocs** [comment]
Closed due to not active.
