### ISSUE TITLE
Marktext does'nt execute

### ISSUE THREAD

**Issue by algunacosa** [marktext/marktext#1808]
### Description

I try to open Marktext and it does'nt work. I tried to:
* Use AppImage Launcher
* Execute in terminal
* Build and run binary

- [ ] Can you reproduce the issue? 

**Expected behavior:**

Marktext's AppImage opens naturally.

**Actual behavior:**

* __AppImage:__ It does nothing.
* __Terminal:__ Prints this error:
`The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_markteB2WulJ/chrome-sandbox is owned by root and has mode 4755. `
This directory (/tmp/.mount_markteB2WulJ/chrome-sandbox) __does'nt exists.__
* __Build:__ The binary works properly, so I move the build folder to `$HOME/.local/bin`. But, when I do it, I got this error when executing:
`marktext: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory`
I ckecked the folder and `libffmpeg.so` is there.

### Versions

- Mark Text: Lastest (0.15.1)
- Operating system: Manjaro 18.3 "Jurhaya"

**Comment by fxha** [comment]
Thank you for reporting the issue. Please see [FAQ](https://github.com/marktext/marktext/blob/d330a1dcbc32be776968b236d8a372f0c16ebbb3/docs/FAQ.md#i-cannot-launch-mark-text-on-linux-suid-sandbox) for more information about the SUID sandbox and steps to solve the issue.

> This directory (/tmp/.mount_markteB2WulJ/chrome-sandbox) does'nt exists.

The random directory is used by AppImage without user access. The AppImage packages and your system configuration is not compatible, right know.

> The binary works properly, so I move the build folder to

This seems to be a system issue but you could try the `marktext-x64.tar.gz` archive or also community managed AUR packages.
