### ISSUE TITLE
Suspicious Action alert from Norton Antivirus

### ISSUE THREAD

**Issue by wecreate1** [marktext/marktext#1812]
### Description

Norton Antivirus alerts of suspicious activity.

It seems to be because the "My Data Sources" folder in documents has a special icon.
![image](https://user-images.githubusercontent.com/41131095/70761811-207f8180-1d14-11ea-93a9-01f1fc9771fd.png)

This my be an electron issue, I have no idea, and it's not reproducible, but I figured I'd report it.

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. With Norton Antivirus...
2. File -> Open Folder in Mark Text
3. Go to Documents library in windows

**Expected behavior:**

No alert from antivirus

**Actual behavior:**
![Capture](https://user-images.githubusercontent.com/41131095/70761612-6425bb80-1d13-11ea-8600-64f0d11e8e23.PNG)

### Versions

- Mark Text: v0.16.0-rc.2
- Operating system: Windows 8.1

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. Please report the detected file as false positive to your anti-virus manufacturer. Mark Text may be detected because we don't digitally sign our application, please also see https://github.com/marktext/marktext/issues/418#issuecomment-403988212.
