### ISSUE TITLE
notes list

### ISSUE THREAD

**Issue by flyisland** [marktext/marktext#1815]
After opening a folder, there could be a list at the sidebar to show all notes inside that folder and its sub-folder, and allow it to be sorted by time ascending/descending.

It'd be better to support showing "title" but not the file name in this notes list, a "title" of a markdown file could be "title" property of its front matter, or the first header.

**Comment by fxha** [comment]
> show all notes inside that folder and its sub-folder

What do you mean by *notes*?

> After opening a folder, there could be a list at the sidebar to show all notes inside that folder and its sub-folder, 

Please see [here](https://github.com/marktext/marktext/blob/develop/docs/BASICS.md#open-a-directory)

> and allow it to be sorted by time ascending/descending.

There are already issues opened for this.

> It'd be better to support showing "title" but not the file name in this notes list, a "title" of a markdown file could be "title" property of its front matter, or the first header.

I think this could be an improvement for later but increases the opening duration a lot because we need to parse each file, so I guess this is a won't fix for now.

**Comment by flyisland** [comment]
I think it's about the position of marktext.

If we think of marktext as an editor, then I agree that this feature request is a low priority.

But if we think of marktext as a notes manager plus editor, kind of like Evernote, then sort notes by time, search by tag, etc would be a high priority.

Anyway, I hope you would work out a plugin framework soon, then these features would be more easy to be added.

**Comment by fxha** [comment]
This is currently not on our roadmap as Mark Text is a pure text editor. I'm also closing the issue because there are already issues open about file (name) sorting. We may reopen this issue on demand for plugins later.
