### ISSUE TITLE
T

### ISSUE THREAD

**Issue by Popsoywhip** [marktext/marktext#182]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](https://codepen.io/) or a similar service and paste a link here]

### Versions

- Mark Text:
- OS:

**Comment by Jocs** [comment]
What’s this issue used for?

**Comment by Popsoywhip** [comment]
Testing
