### ISSUE TITLE
Clipboard issues with escape characters

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1821]
### Description

All JavaScript escape characters are encoded before copied to clipboard. E.g. `f'(x)` is copied as `f&#39;(x)` to clipboard.

**Expected behavior:**

`f'(x)`

**Actual behavior:**

 `f&#39;(x)`

### Versions

- Mark Text: v0.16.0.rc-2
- Operating system: all

**Comment by fxha** [comment]
@Jocs https://github.com/gabrielegiammatteo/marktext/commit/3960f429ced4182a84e06e862e281c14b5eee7a3

**Comment by Jocs** [comment]
I don’t remember the specific reason, maybe it is to prevent XSS attacks?

**Comment by fxha** [comment]
I don't think so because it's on the plain text. I'll submit a PR to remove `escape` from the plain text but the others are needed to display HTML correctly.
