### ISSUE TITLE
[feature request] drag to arrange heading and subsequent text

### ISSUE THREAD

**Issue by retsyo** [marktext/marktext#1827]
# English description
## Why I ask?
We (ok, maybe only me) often re-arrange the text during writing. 
## The question
So as the title says, is it possible to do following?

1. select only by heading, then drag it to a new position. 
2. now, not only the heading but all the subsequent text and sub-heading are moved to the new position.

## What I thought
Of cause this is more reasonable if 
1. we only select the heading in the outliner view
or
2. the markdown file is rendered as a mind-map diagram, all heading is treated as the node, then subsequent text is treated as note as [midmup](http://www.mindmup.com) does. Here we drag the node to arrange

# 自带中文翻译

## 问题起源
我觉得有书写的时候，思路还不清晰，会把一些内容的先后顺序调来调去。

## 问题描述
能否选择一个标题之后，拖动它在整个markdown文件中的位置；拖动之后，不仅这个标题位置重新设置，而且下方的正文/子标题全部移动

## 我的脑洞
1. 这个拖拽标题操作，好像只有在大纲视图中弄才说得清楚；如果在markdown编辑界面中，如何体现选择了下方所属的一切？

2. 或者把markdown渲染成脑图，所有标题作为节点，标题下的其他文字作为“笔记”（参看[midmup](http://www.mindmup.com)）。我们可以在脑图中，拖拽节点改变顺序（节点附属的笔记自然也跟着一起动）。脑图里面的节点，可以按照从左到右、从上到下的顺序，与markdown对应——好吧，我承认其实我是在说一个结合了markdown和mind-map的软件。

**Comment by fxha** [comment]
Thank you for reporting the issue. This feature is currently not planned but we may support rearrange via shortcuts in the further.

**Comment by YalandHong** [comment]
Someone has opened a new issue (#2705) about this feature. I think you should either reopen this issue or discuss in that one.

**Comment by YalandHong** [comment]
Also related to #2705

**Comment by YalandHong** [comment]
Also related to #2285

**Comment by FelixOlschewski** [comment]
+ 1

This would truly set Marktext apart from the rest. It is a killer feature for any serious author. Rearranging words is our business. Rearranging sections and chapters is part of that.
