### ISSUE TITLE
bug during exporting to PDF/html with 'auto numbering heading' on

### ISSUE THREAD

**Issue by retsyo** [marktext/marktext#1830]
I am using marktext-x64-win.zip ( 0.16.0-rc.2). I thought the following text 
```
# title 1
## sub-title
### sub-sub-title
# title 2
```
shoud be exported as 

# 1. title 1
### 1.1.1 sub-sub-title
# 2. title 2

but what we get in the exported html/pdf is 

# title 1
### 1.1 sub-sub-title
# title 2

**Comment by fxha** [comment]
I'm closing this issue as this is normal and the expected behavior. Only chapters, sections, and subsections should be numbered but not the main heading.
