### ISSUE TITLE
[feature request]more extension/plugins

### ISSUE THREAD

**Issue by retsyo** [marktext/marktext#1831]
as we can find on http://mdp.tylingsoft.com/, more extension is supported. Will marktext support them, for example, `AsciiMath`. `Charts`, `mermaid charts`? Thanks

**Comment by retsyo** [comment]
its code is on https://github.com/tylingsoft/markdown-plus

**Comment by fxha** [comment]
Thank you for suggestion but we noticed that this is a duplicate of #375 and #224. You may want to subscribe there for further updates.
