### ISSUE TITLE
the copy does not work as the original text

### ISSUE THREAD

**Issue by chuoke** [marktext/marktext#1834]
### Description

the copy does not work as the original text. It lost linefeed.

### Steps to reproduce

```bash  
$ sudo yum remove docker \
        docker-client 
```

**Expected behavior:**

```bash
$ sudo yum remove docker \
        docker-client 
```

**Actual behavior:**

```bash
$ sudo yum remove docker \        docker-client 
```

### Versions

- Mark Text:  v0.15.1
- Operating system: Windows 10

**Comment by fxha** [comment]
Thank you for reporting the issue. This issue has been fixed, and you could try our testing build v0.16.0-rc2.

**Comment by chuoke** [comment]
I updated to v0.16.0-rc2. The copy is work. but the copy of right-click menus does not copy anything.

**Comment by fxha** [comment]
> The copy is work. but the copy of right-click menus does not copy anything.

Thanks for your feedback, could you please explain the issue in detail - maybe open another issue if it's not related to this one?

**Comment by chuoke** [comment]
Sorry, I didn't say clearly. 

In the left sidebar, select one markdown and right click, then choose the copy, but there is nothing copied.
