### ISSUE TITLE
How to enable `斗图` in Mark Text?

### ISSUE THREAD

**Issue by alexshenyuefei** [marktext/marktext#184]
### Description

windows 系统怎么使用斗图
windows上面斗图的快捷键是什么
谢谢

**Comment by alexshenyuefei** [comment]
谢谢

**Comment by wuseal** [comment]
斗图功能屌炸天呐，表示很佩服！

**Comment by keienatinb** [comment]
![image](https://user-images.githubusercontent.com/54785533/76837869-3a2de900-686e-11ea-8c32-3a48d82ef92c.png)
我打开了这个功能，但是我无法将喜欢的动图贴到里面去，单击双击都不信，是我的操作有问题吗

**Comment by jxmnhm** [comment]
> 吗
你的这个问题解决了吗？我的也是，点了没反应。
