### ISSUE TITLE
Softbreaks are not rendered onto a single line

### ISSUE THREAD

**Issue by Benjamin-Lee** [marktext/marktext#1843]
### Description

#159 does not appear to be solved.

If your source looks like:

```
This is the first line.
This is the second line.
```

It is rendered as 

```
This is the first line.
This is the second line.
```

when Markdown spec requires that it render as

```
This is the first line. This is the second line.
```

This breaks the use of [semantic line breaks](https://sembr.org).
- [x] Can you reproduce the issue? 

### Steps to reproduce

Write two lines of text on separate lines.

**Expected behavior:**

https://spec.commonmark.org/0.29/#softbreak

**Actual behavior:**

Source code mode:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/13618205/71464808-f304f000-2777-11ea-8192-5b3933a5403a.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/13618205/71464820-ff894880-2777-11ea-8a68-6d5fa4b25988.png">

**Link to an example: [optional]**

### Versions

- Mark Text: v0.15.1
- Operating system: MacOS 10.15.1

**Comment by Jocs** [comment]
>According to https://spec.commonmark.org/0.29/#softbreak (A softbreak may be rendered in HTML either as a line ending or as a space. The result will be the same in browsers. In the examples here, a line ending will be used.)

**Comment by Jocs** [comment]
Feel free to reopen this issue if you have any other options.

**Comment by Benjamin-Lee** [comment]
@Jocs Would it be possible to make this an option? Rendering soft breaks as line endings makes Mark significantly less usable with SemBr Markdown files. For reference, Typora renders soft breaks as spaces.

**Comment by Jocs** [comment]
>For reference, Typora renders soft breaks as spaces.

I remember that Typora also treats soft line break and hard line break as new lines? Are you mean export html or PDF?
