### ISSUE TITLE
Add instructions in the image uploader configuration

### ISSUE THREAD

**Issue by CouldBeThis** [marktext/marktext#1848]
### Describe your feature request

Preferences -> Image uploader -> GitHub needs a bit of instruction.

I would suggest something like this:
> If you don't have a GitHub account, you will need to [make one](https://github.com/join?source=header-home). 
> A token can be generated in [Settings/Developer settings](https://github.com/settings/tokens)
> For more detailed instructions, [consult the wiki](https://github.com/marktext/marktext/blob/develop/docs/IMAGE_UPLOADER_CONFIGRATION.md).
> Note: By default, all uploads to GitHub are public. It is possible to configure your repository to be "private". 
_❓How private is private?? I tried to find some info but can't._

### What problem does this feature solve? [optional]

Not everyone is familiar with how to use this GitHub feature. (Or even that GitHub exists.) 

### Additional context [optional]

Someone else who couldn't figure it out: 
How to set github token on mac os ? #1476 
It's worth noting that 99% of people who can't figure this out also won't think to make an issue on GH so this is likely an extreme under representation of those with problems. 

### Also, about the wiki page

This could use a bit of work but I'm not sure what the system is for helping with that. Do I put my edit here or as a new issue? Or if I hit "edit" on the wiki make some magic happen and create a discussion? Or is there someone here really likes editing the wiki?

What's needed is:

1. Brief 1 or maybe 2 sentence explanation of what GH is. 
2. At least some links to docs about how to create a repo. Hints on what kind to create (public/private, template folder, ghpages... various things that can be confusing.)
3. A brief description of what a token is 
4. Guidance on what *scopes* to select. First I tried selecting nothing, but that didn't work. I got it by checking all the boxes in the first section. But are they all required or can/should I change anything? (my repo is private)
- [x]  Repo - Full control of private repositories
  - [x]  repo:status   -  Access commit status
  -  [x]   repo_deployment   -  Access deployment status
  -  [x]   public_repo   -  Access public repositories
  -  [x]   repo:invite   -   Access repository invitations

**Comment by Jocs** [comment]
@CouldBeThis Help is wanted, thanks

**Comment by ShravanSunder** [comment]
@CouldBeThis  did you get the images to upload.  i got the api key and everything setup, according to your comments, but i can't get the image to upload

**Comment by mxrodriguez** [comment]
Same issue here.  I created the Repo and generated a APi token.. but Image upload is failing.
A bit more details in the wiki would be helpful

**Comment by Cipher358** [comment]
Same here on version 0.16.1 of MarkText on a private repository with all the `repo` permissions.
I tried using a public repo but the result was the same.

**Comment by teopost** [comment]
I have the same problem too - rel. 0.16.1

**Comment by violetu** [comment]
same here in Linux. I don't think the instruction is detailed. It‘s the obstacle for me to start using marktext.

**Comment by ctjlewis** [comment]
Does anyone know where logs might be located where I can debug why this isn't working? Installed from Flatpak on Ubuntu.

**Comment by phanikaran** [comment]
This helped me get it done in case someone else's still looki ng - https://github.com/marktext/marktext/blob/develop/docs/IMAGE_UPLOADER_CONFIGRATION.md
