### ISSUE TITLE
Feature Request: Workspace support

### ISSUE THREAD

**Issue by g-plane** [marktext/marktext#185]
### Description

Just open a directory instead of a single markdown file, like:

![image](https://user-images.githubusercontent.com/17216317/38977441-ff58f11a-43e6-11e8-8e0a-8d44a6b9bec9.png)

(This is Typora)

### Versions

- Mark Text: 0.10.21

**Comment by Jocs** [comment]
duplicate with #71

**Comment by g-plane** [comment]
Should I close it?

**Comment by Jocs** [comment]
Ok，we will support sidebar and tabs before v1.0.0
