### ISSUE TITLE
align the text position to the left

### ISSUE THREAD

**Issue by uocxp** [marktext/marktext#1857]
![screenshot_46](https://user-images.githubusercontent.com/8387383/72079396-20ff3e00-32fb-11ea-911c-48ce11180778.png)

As you see in the screenshot the markdown text is very central. How can i align it to the left side of the window?

I am using ubuntu 18.04 with the latest version of marktext.

**Comment by renehummen** [comment]
@uocxp I also came across this issue and already fixed this for myself.

What I noticed is that the editor component of the window has a fixed max width but is aligned to the center on the horizontal axis. As a result, the text position will on have a fixed (small) margin relative to the sidebar when the window is sufficiently small or the sidebar is sufficiently large.

I fixed this by tweaking the CSS for the editor component and can make a PR as it seems to others as well.

**Comment by uocxp** [comment]
@renehummen did you make a PR ?

**Comment by Jocs** [comment]
I think custom theme(this feature will be implemented in the future) will solve this issue?

**Comment by ldavis2020** [comment]
@renehummen: If there was any chance you put up a PR for your change to the editor CSS to fix this issue it would be very much appreciated. As I have the same problem (Win 10, but it sounds like it applies to all OS's) and I find it quite painful so your fix would be amazing!

**Comment by BitThr3at** [comment]
I am also having same issue, not able to utilize full space of editor as it is centered.

By the way awesome creation.👍

**Comment by fxha** [comment]
Please set settings -> editor -> maximal editor area to `100%`.

**Comment by uocxp** [comment]
@fxha changing the maximum width to 100% does not resolve the issue. The window is not progressive, so when i minimize the width of the windows, the text is cut out.
![image](https://user-images.githubusercontent.com/8387383/103892608-26e55600-50ec-11eb-992b-1118fa8f8882.png)

**Comment by uocxp** [comment]
This is the wished behaviour similar to **Typora** 
![progressive](https://user-images.githubusercontent.com/8387383/103892859-96f3dc00-50ec-11eb-8b4e-201291a544f1.gif)
