### ISSUE TITLE
Allow hotkeys customizations

### ISSUE THREAD

**Issue by saveriomiroddi** [marktext/marktext#1862]
### Describe your feature request

Add the option to customize the hotkeys.

### What problem does this feature solve? [optional]

Some key combinations, in particular Ctrl+Alt ones, are in some operating systems used for global events, ie. Ctrl+Alt+T is the Ubuntu (possibly Debian) standard for a console.

Right now, it's impossible to switch to Typewriter mode via hotkeys, since a terminal is opened instead.

**Comment by Jocs** [comment]
You can refer this document: https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md
