### ISSUE TITLE
Sync location between regular and source modes

### ISSUE THREAD

**Issue by saveriomiroddi** [marktext/marktext#1865]
### Describe your feature request

It would be useful to have the cursor/viewport go to the corresponding location when the mode is switched from regular to source (or viceversa)

### What problem does this feature solve? [optional]

It happens relatively frequently that I'm viewing a document, then I decide to edit something. In this case, I generally switch to source mode, since I find it cleaner. The problem is that I have to find the location to edit again, because the cursors/viewport don't move to the corresponding location. When I switch back to regular mode, the same problem happens again.

Syncing the position would make the process much smoother (right now, I have to search the location twice).

**Comment by fxha** [comment]
Thank you for reporting the issue. We sync the cursor between both editors but the cursor is located at the bottom of the screen.
