### ISSUE TITLE
How can i open file or directory from command ?

### ISSUE THREAD

**Issue by Wang-Kai** [marktext/marktext#1868]
### Question description

How can i open file or directory from command ?

just like :
```
textmark . // open whole directory

textmark a.md // open a file
```

**Comment by adrienbeau** [comment]
This works fine with Mark Text 0.16.0-rc2 under Windows 7.

* `"Mark Text.exe" .` opens the current directory (list of files in sidebar)
* `"Mark Text.exe" test.md` opens the file

Under Windows, this only works if no other Mark Text instance is running.

**Comment by Wang-Kai** [comment]
@adrienbeau Thank you very much !

But, i use MacOS，can i do it on MacOS ?

**Comment by Jocs** [comment]
>But, i use MacOS，can i do it on MacOS ?

Yes, it is also possible in 0.16.0-rc2.
