### ISSUE TITLE
Vega-Lite broken?

### ISSUE THREAD

**Issue by lrq3000** [marktext/marktext#1871]
I tried to use this example from Vega-Lite docs:

https://vega.github.io/vega-lite/examples/circle_wilkinson_dotplot.html

But it does not work. Is marktext supporting an older version of vega-lite? If yes, then which one?

I am running Windows 10 Home x64. Vega-lite support (and other graphs) is really a killer feature! Great Job!

**Comment by Jocs** [comment]
@lrq3000 Thanks for you report this issue, I'll take a look and update vega-lite.
