### ISSUE TITLE
Command to 'Copy As Rich Text'

### ISSUE THREAD

**Issue by ejm554** [marktext/marktext#1872]
### Describe your feature request

Provide an option to copy rich text, in a way that is similar to the existing Copy As HTML and Copy As Markdown options.

### What problem does this feature solve?

It would be useful when you want to paste part or all of the document into program that supports rich text, but doesn't automatically convert HTML or Markdown.

![image](https://user-images.githubusercontent.com/26723535/72632459-ee1d0180-391b-11ea-9860-a5951e7cf0eb.png)

**Comment by DXXL** [comment]
I think the default "Copy" already does copy rich text.

**Comment by ejm554** [comment]
It appears that you're right. But when pasting, I'm not seeing the format defined in my preferences (Open Sans font, etc.). Instead, I'm just seeing some old-school font, i.e. Times, in my target file. So perhaps I should refine my request feature request as follows: 

1. Change the 'Copy' command to explicitly say 'Copy As Rich Text', so it is more clear to the user, and is otherwise consistent with the related Markdown and HTML commands.
2. When using the 'Copy (As Rich Text)' command, the formatting defined in the Preferences is also copied to the clipboard.

**Comment by fxha** [comment]
I'm closing this issue as we currently don't plan to implement the feature but we may reopen it on demand. Currently we only support raw HTML (without style).
