### ISSUE TITLE
The text doesn't scroll when going outside the viewport via arrows

### ISSUE THREAD

**Issue by saveriomiroddi** [marktext/marktext#1873]
### Description

If I move the cursor above/below the viewport, using the arrows (up/down), the text doesn't scroll.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Create a document that is larger than a screen, preferrably a few
2. Go to the middle
3. Go up with the up arrow, above the upper limit of the viewport
4. The text doesn't scroll

(same concept applies to the down arrow/lower limit)

**Expected behavior:**

The text should scroll, following the cursor.

**Actual behavior:**

The text doesn't scroll.

### Versions

- Mark Text: 0.15.1
- Operating system: Ubuntu 18.04 derivative

**Comment by acicovic** [comment]
I'm on Windows and have the same issue. I thought this was a bug.

**Comment by acicovic** [comment]
@fxha any idea when this is going to be integrated in a release?
