### ISSUE TITLE
Unexpected error: Cannot read property 'delete' of undefined

### ISSUE THREAD

**Issue by twodogegg** [marktext/marktext#1875]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: Cannot read property 'delete' of undefined
    at Notification.onclick (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:52:115082)
```

### Version

Mark Text: v0.16.0-rc.2 (N/A)
Operating system: Darwin x64 19.2.0 (darwin)

**Comment by Jocs** [comment]
how to reproduce this issue? can you give more detail.
