### ISSUE TITLE
输入中文的时候，滚动条会自动跳到顶部。

### ISSUE THREAD

**Issue by kobejie93** [marktext/marktext#188]
### Description

When the content is entered, the top is automatically rolled. Input Chinese
输入中文的时候，滚动条会自动跳到顶部。
### Steps to reproduce

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](https://codepen.io/) or a similar service and paste a link here]

### Versions
v0.10.21
- Mark Text:
- OS: Windows

**Comment by Jocs** [comment]
@kobejie93 can you write the reproduce steps? you can write it in Chinese.
