### ISSUE TITLE
Github Image Upload - Deleting unused images from repo

### ISSUE THREAD

**Issue by berkancetinkaya** [marktext/marktext#1881]
Hi,
### Describe your feature request
Uploading images to github repo is really briliant idea but wouldn't it be better if we remove images if they're not used?

Basically when user clicks the delete button, we can trigger a delete commit.

#### One case to be considered
there is one trade-off. Even if it's deleted, user might close editor without saving file. For this reason, after image delation, better to have a auto save.

Thanks,

**Comment by Jocs** [comment]
>Basically when user clicks the delete button, we can trigger a delete commit.

This image maybe also used in other markdown file, so we can not remove it from github repo. you need to remove the unused images in the Github repo by yourself. 

>there is one trade-off. Even if it's deleted, user might close editor without saving file. For this reason, after image delation, better to have a auto save.

BTW, we'll ready have auto save feature, but you need to enable it in the file menu.
