### ISSUE TITLE
Reduce time of launch

### ISSUE THREAD

**Issue by ejm554** [marktext/marktext#1883]
### Describe your feature request

Reduce the amount of time it takes to launch the application.

### What problem does this feature solve?

Currently, it takes a relatively long time to launch the program, at least compared to similar text/document editors. For example, launching a Markdown document with Mark Text on an older MacBook Pro* takes about 18 seconds.  Launching that same document with the [MultiMarkdown Composer app](https://multimarkdown.com) takes only about 2 seconds. 

### Additional context

\* Device specs: MacBook Pro (13-inch, Mid 2009); macOS 10.11.6 (El Capitan); 2.26 GHz Intel Core 2 Duo; 8 GB 1067 MHz DDR3

**Comment by fxha** [comment]
Thank you for reporting the issue. Mark Text is still in development and we try to optimize the engine to get better performance.

**Comment by DYH-Hong** [comment]
Please consider tracking #2638 and report your problems there. Thanks!
