### ISSUE TITLE
Image Upoader module can be replaced by other mature image uploading tools

### ISSUE THREAD

**Issue by ghost** [marktext/marktext#1890]
### Describe your feature request
Image Upoader module can be replaced by other mature image uploading tools, as marktext should focus more on Markdown itself.[picgo] (https://github.com/Molunerfinn/PicGo), for example,It has a variety of built-in picture beds and supports picture management, plug-in system provides a richer for it:
![image](https://user-images.githubusercontent.com/37654563/73604503-e4a6c100-45cc-11ea-9b83-47ee9a8ddbe1.png)
Users can choose an app(e.g. picgo). then marktext uses picgo(or others) to upload pictures when pasting pictures into Markdown.

**Comment by Jocs** [comment]
In fact, this is also the result we want. We hope to realize the upload of pictures through plugins. Users can develop some plugins for uploading pictures for Mark Text. I have tried picgo-core before, as if it only supports use in the main process. Later gave up.
