### ISSUE TITLE
Rejected by McAfee and Fails VirusTotal

### ISSUE THREAD

**Issue by Syenta** [marktext/marktext#19]
### McAfee Uninstalls MarkText + VirusTotal finds Ad-Ware package

[Description of the bug or feature]

### Steps to reproduce

1. Install software
2. McAfee checks files
3. McAfee uninstalls software and shows message regarding concerns for URLs MarkText is trying to connect to.
4. VirusTotal scan shows up an Ad-Ware package included with your program. This is possibly a false positive as the other scanners shows clean files.

### Latest version

- Mark Text: Latest version as of 17 March 2018
- OS: Windows 10 Pro - fully up to date

**Comment by SuperSandro2000** [comment]
Smart screens had some complains sometimes too

**Comment by evantbyrne** [comment]
Closed without any explanation. Sketchy...
