### ISSUE TITLE
Two AppData\Roaming folders on Windows

### ISSUE THREAD

**Issue by heydojo** [marktext/marktext#190]
### Description

marktext creates two folders inside the folder C:\Users\USERNAME\AppData\Roaming

### Steps to reproduce

1. Using Windows explorer, navigate to the location C:\Users\USERNAME\AppData\Roaming
(replacing USERNAME with your username)
2. Scroll down to the folder Mark Text
3. Observe that there is also a folder below named marktext

**Expected behavior:**

Only one folder used for roaming data.

**Actual behavior:** [What actually happened]

Two folders are used.

### Versions

- Mark Text: v 0.10.21
- OS: Microsoft Windows 10 - X86_64

**Comment by Jocs** [comment]
@heydojo can you show some pictures about this issue? what's folders' name?

**Comment by SuperSandro2000** [comment]
I think he means there are the folders Mark Text and marktext. I assume one from electron and one from the settings.

**Comment by heydojo** [comment]
> there are the folders Mark Text and marktext.

Correct. 👍

There doesn't need to be two. And to be honest it's not really regarded as good practice to use the roaming folder for application data. It eliminates portability. The application has an installation folder; why not use it to store application settings and use the registry for per user settings?

If you won't, please ensure that AppData\Roaming entries are cleared out by the uninstall routine.
AppData\Roaming clutter gets really bad on Windows from lots of different install routines which don't clean up after themselves.

**Comment by SuperSandro2000** [comment]
> why not use it to store application settings and use the registry for per user settings?
UAC and there is no such thing as a registry on linux so it is easier to port and test with a file based config.

**Comment by fxha** [comment]
Yes, Mark Text use `marktext` folder for settings and electron cache. `Mark Text` folder is not used by us.  I'm not sure, but maybe the windows setup (NSIS) use`Mark Text` for log files.

As already mentioned by @SuperSandro2000, Mark Text is a cross-platform application and the easiest way to support settings is to use a folder in user directory. Maybe we can add a `--portable` flag to use a subdirectoy later. And registry is not really portable. By the way `AppData` means Application Data -> "Per-user application-specific files". If we would move this into another place, users have same settings.

> install routines which don't clean up after themselves.

That's true. We we do not delete user preferences. It's generally a good idea to let the user decide whether he want to delete his preferences or not. Let me see what I can do against this issue.

**Comment by heydojo** [comment]
Cool. Probably just the installer cache then.

> And registry is not really portable too.
Neither are user specific settings.

In all honesty, for Windows; you likely should be targeting the Windows store. I say this as someone who has no interest in using store apps myself. However, you have the likes of [Atom](https://atom.io/) to compete with in this space and their markdown support is the best I have found. Atom, however does not have a Windows store offering.
Might be something to look into in the future?

**Comment by fxha** [comment]
> Neither are user specific settings.

Sure of course, we save user preferences, recently used documents on Linux and Window and also window settings in there.

> you likely should be targeting the Windows store

At the moment the primary focus is to develop all missing feature, fixing bugs and stabilization. I think there could be also problems with sandboxing (filesystem access) and we would need a windows certificate. There are good reasons why atom, vscode etc are not in the store.

> I would suggest trying to change on of the names so that both folders are combined.

@SuperSandro2000  Thought about it too and also don't know why we use "Mark Text" on Windows. I think I can change this to "marktext" too. The only problem is that we would lose all existing user settings :/

@Jocs What's your opinion?

**Comment by SuperSandro2000** [comment]
> The only problem is that we would lose all existing user settings :/

Alpha/Beta 😆

**Comment by Jocs** [comment]
First of all, I don't think this is a destructive issue. As you said, our focus at this stage is still on improving functionality and stability.

**about this issue:**

- Since I don't quite understand how to uninstall Mark Text above windows, I hope to be able to clean these folders when I uninstall it.
- >I would suggest trying to change on of the names so that both folders are combined.

  I don't know weather this will affect other systems or other systems has the same issue.

So, I suggest clean up these folders when uninstall Mark Text(not updated)?
