### ISSUE TITLE
Improve zoomable user interface

### ISSUE THREAD

**Issue by sfjohansson** [marktext/marktext#1906]
### Describe your feature request

The ability to zoom/adjust size of the document view area.

### What problem does this feature solve? [optional]

Currently the app is working fine on a laptop screen, but  unusable out of the box on my desktop with 4k screen. Resizing the window would leave the content just centered in the middle.
Being able to arbitrarily resize the view to adjust for ergonomics on any screen/viewing distance would greatly improve the usability across various screens.

### Additional context [optional]
This could be implemented in multiple ways, a free pan/zoom canvas like a webpage would be most flexible. A more simple implementation could be to just have a multiplier for already defined text sizes.

Related to ergonomics... it would be good to be able to scroll beyond end of document/content, without manually adding empty spaces, in order to center the text one is currently writing.

**Comment by Jocs** [comment]
The width of the editor can now be changed in the settings, will this solve your problem？

**Comment by sfjohansson** [comment]
Awesome, thanks for looking at this so quickly. 

I've tested the new build and adjusting the document area width doesn't really help as the problem lies in the text size varying between different screens.

Although I did find a solution through the newly exposed command palette, using the zoom option. A little clunky...but it can get the job done, hotkeys or perhaps slider,  could would be more workable.

Here are some screenshot, the first shows the case where it is pretty unreadable on the 32" 4k screens while being fine on the 24" FullHD.

**4k, 32" screen.**
![4k_32_mark_text](https://user-images.githubusercontent.com/912814/74605768-ea1f0380-50c2-11ea-9996-d9bdbb026364.jpg)

**FullHD 24"**
![Full_HD_24](https://user-images.githubusercontent.com/912814/74605769-f30fd500-50c2-11ea-99fe-fc956594ae6d.jpeg)

**Latest build, wider view area:**
![New Mark Text](https://user-images.githubusercontent.com/912814/74605775-fefb9700-50c2-11ea-9e1b-8100396e0efd.jpeg)

**Latest Build Zoom through command palette**
![zoom_mark_Test](https://user-images.githubusercontent.com/912814/74605786-1a66a200-50c3-11ea-84e0-75b507213856.jpg)

**Comment by fxha** [comment]
@sfjohansson Our latest release candidate(s) contain an option under `Window -> Zoom` or via command palette (`Ctrl+Shift+P`) to adjust the DPI but it's not persistent and I think we don't have any  settings entry for it.

**Comment by sfjohansson** [comment]
This is great...it's kind of fine not persisting if treated like zoom. In my case...I'm fine not zooming when it's the 1080p screens but need to zoom on 4k. Moving the window over to the other screen I need to zoom out again..so easy access feels important.

The usability would increase even more if we can have the zoom step amount adjustable in preferences along with hotkeys/keycombo+mouse scroll wheel.

**Comment by fxha** [comment]
> Moving the window over to the other screen I need to zoom out again..so easy access feels important.

Dynamic DPI scaling is only supported on Windows (10) but is very bugged by Electron/Chromium.

**Comment by AlJohri** [comment]
Is there anyway to use Cmd +- or Ctrl +- to control the zoom? Or holding control and scrolling the mouse wheel?

**Comment by samuel-lucas6** [comment]
This is my biggest gripe with the program. It's a hassle having to keep adjusting the zoom every time the program is launched. Remembering the zoom, keyboard shortcuts, and only zooming in on the editing pane would all be incredibly helpful.

**Comment by geckolinux** [comment]
As a workaround, you can add this to your `.desktop` launcher file in Linux:
`--force-device-scale-factor=1.1` (or whatever scale factor you need)

**Comment by edo0** [comment]
> As a workaround, you can add this to your `.desktop` launcher file in Linux: `--force-device-scale-factor=1.1` (or whatever scale factor you need)

Thank you very much, that is a great workaround

**Comment by loyukfai** [comment]
Ditto

**Comment by lichever** [comment]
Are key shortcuts for zoom changes available now?

**Comment by fxha** [comment]
User-defined shortcuts and mouse zoom support is available in our next release but no persistence.

**Comment by lichever** [comment]
> User-defined shortcuts and mouse zoom support is available in our next release but no persistence.

sounds  great. BTW, when I zoom in in the latest version, the index in the table of contents will not work any more. But if I change it back to the normal scale, it will work again.

**Comment by fxha** [comment]
This feature will be available in our next release.

> when I zoom in in the latest version, the index in the table of contents will not work any more.

What do you mean by index? That the editor jumps to the wrong position, then is a fixed bug in v0.16.3.

**Comment by lichever** [comment]
> 

I mean the heading in the table of contents.
