### ISSUE TITLE
“Mark Text.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by qoomon** [marktext/marktext#1907]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. open application

**Expected behavior:**

startup application

**Actual behavior:**

Error dialogue
`“Mark Text.app” cannot be opened because the developer cannot be verified.`

### Versions

- Mark Text:  v0.15.1
- Operating system: macOS Catalina 10.15.3

**Comment by qihuazhong** [comment]
This may help you:
https://support.apple.com/en-ca/guide/mac-help/mh40616/mac

In short, when you first open the app, don't just double click. Use the Control-click (in my case, I click with two fingers on the touchpad) to call out and shortcut menu, and then open.
