### ISSUE TITLE
Font selction is limited - please allow us to use any installed font

### ISSUE THREAD

**Issue by NiklasBr** [marktext/marktext#1908]
### Describe your feature request

Ability to select any operating system installed font

### Additional context [optional]

Currently only a few fonts are available for selection, but I would like to use any of my installed fonts for rendering the document.

**Comment by Jocs** [comment]
@NiklasBr You can try the 0.16.0-rc.2, it support system installed font.

**Comment by NiklasBr** [comment]
@Jocs I could get it to work for Code Blocks, but I am unable to click and change the font in any way for the regular editor. See screen shot below, green square: clickable, red square: not clickable.

![Screenshot (3)](https://user-images.githubusercontent.com/279826/74606028-5272e280-50cd-11ea-9015-428b4f93a9cb.png)

**Comment by Jocs** [comment]
@NiklasBr What's you Mark Text version?

**Comment by Jocs** [comment]
<img width="944" alt="截屏2020-02-16下午10 10 23" src="https://user-images.githubusercontent.com/9712830/74606179-2e34f700-5109-11ea-8cd6-aa26ac5bcc06.png">

1. Clear the selected font in the input.
2. You'll the the options...

version: 0.16.0-rc.3

**Comment by NiklasBr** [comment]
1. Impossible because it is not clickable, see the screen shot above.
2. I'll what?

I'm using v0.16.0-rc.3

**Comment by NiklasBr** [comment]
Re-installed 0.16.0-rc.3 but still experiencing this. I can actually write whatever I want in the *font block* input field (why isn't it a regular drop-down by the way?) and if I spell a font correctly it works.

Still not able to use the regular editor to choose a different font.

**Comment by fxha** [comment]
@Jocs I can confirm this issue. I just build v0.16.0-rc-3 from develop (1c5b714) and the font family "list" only contain the selected font family without any logged errors. rc-2 (develop, custom build) from 30 January worked correctly.

**Comment by Jocs** [comment]
>and the font family "list" only contain the selected font family without any logged errors. 

@fxha @NiklasBr Can you see all the installed fonts in the drop down if you clear the selected font family?

>I'll what?

You can see the installed font family options.

**Comment by fxha** [comment]
> Can you see all the installed fonts in the drop down if you clear the selected font family?

@Jocs  You're right, the UX is very bad because the list is filtered. We should instead show all font families by default and only filter if the user types, otherwise it might be confusing. But I don't know whether @NiklasBr has the same issue, at least for me, the drop down list is always shown.

**Comment by NiklasBr** [comment]
> @NiklasBr Can you see all the installed fonts in the drop down if you clear the selected font family?

No, beucase it acts as a text input field, not as a dropdown. Clicking on the chevron does nothing. There is no dropdown anywhere when I click on it (as I expect it to be). It seems to *detect* the fonts if I spell them correctly though.

**Comment by NiklasBr** [comment]
I installed v0.16.1 and the issue persists
