### ISSUE TITLE
Typing chemical formulas and schemes

### ISSUE THREAD

**Issue by Shatonly** [marktext/marktext#1909]
### Describe your feature request

A way to type chemical formulas and scheme, probably in KaTeX.
Like [this](https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem).

Thanks for this amazing software.

**Comment by YalandHong** [comment]
Duplicate of #2301. A PR (#2327) has been linked to that issue.

**Comment by YalandHong** [comment]
#2327 has been merged so this issue should be closed and marked as release pending.
