### ISSUE TITLE
斗图搜索后点击无响应

### ISSUE THREAD

**Issue by liziqiang** [marktext/marktext#1914]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Press CMD + / to open popup window
2. click one image
3. Nothing happed

**Expected behavior:**

insert image to editor

**Actual behavior:**

Nothing happened

**Link to an example: [optional]**

### Versions

- Mark Text: v0.16.0-rc.3
- Operating system: macOS Catalina 10.15.3
![Feb-16-2020 20-43-31](https://user-images.githubusercontent.com/208130/74604876-2f602700-50fd-11ea-9436-ae0512010546.gif)

**Comment by bravekingzhang** [comment]
图片上传到github也是传不了。

**Comment by dreamzoy** [comment]
win10-1903也不行

**Comment by Jocs** [comment]
和 #1889 重复，先关闭了。

**Comment by Jiangnanmisty** [comment]
斗图在Windows11上加载不出来 
点击搜索三个点一闪而过
