### ISSUE TITLE
Right menu disappeared

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#1915]
### Description

The right menu in editor and sidebar can not be shown by right click.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open any markdown file.
2. Right click on the edit area

**Expected behavior:**

Show the right menu.

**Actual behavior:**

The right menu is not shown.

**Link to an example: [optional]**

### Versions

- Mark Text: 0.16.0-rc.3
- Operating system: macOS or All

**Comment by fxha** [comment]
@Jocs Do you mean the native menu? I guess you should report it to Electron but the menu works correctly on Linux.

**Comment by Jocs** [comment]
@fxha I first suspected that the API was changed due to the upgrade of Electron. After reading the documentation and Electron's Change log, I did not find the reason. I first determined whether it was an Electron problem.

**Comment by hematogender** [comment]
Reproduced successfully, nothing happens on right click.

v0.15.1 though (stable)
Win10
