### ISSUE TITLE
Copy the file to a relative path when drag a jpg/png file into edit window, as typora does

### ISSUE THREAD

**Issue by arcqiufeng** [marktext/marktext#1917]
### Describe your feature request
as title

### Additional context [optional]

typora can do this:
![Screenshot](https://user-images.githubusercontent.com/57745184/74710824-81b85980-525d-11ea-9a0c-0aac21bc1b7c.png)

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate of #549. You may want to subscribe there for further updates.
