### ISSUE TITLE
Unexpected error: e.transition is not a function

### ISSUE THREAD

**Issue by MrHeer** [marktext/marktext#1918]
### Description

An unexpected error occurred in the renderer process.

### Stack Trace

```
TypeError: e.transition is not a function
    at SVGGElement.call (file:///home/mrheer/Documents/Src/Web/marktext/build/linux-unpacked/resources/app.asar/dist/electron/webpack:/node_modules/mermaid/dist/mermaid.core.js:2727:17)
    at SVGGElement.<anonymous> (file:///home/mrheer/Documents/Src/Web/marktext/build/linux-unpacked/resources/app.asar/dist/electron/webpack:/node_modules/d3-selection/src/selection/on.js:27:16)
```

### Version

Mark Text: v0.16.0-rc.3 (1c5b714)
Operating system: Linux x64 4.15.0-88-generic (linux)

**Comment by MrHeer** [comment]
When I use the `mermaid`, I found some problems.
1. This error will appear while the mouse move out the render zone.
2. The indent will be cleared after switch `source code mode`.

**Comment by Jocs** [comment]
How to reproduce this issue? `TypeError: e.transition is not a function`

**Comment by MrHeer** [comment]
This error will appear while the mouse move out the `mermaid` render zone.

**Comment by Jocs** [comment]
@MrHeer 可以用中文描述，我还是无法复现这个问题，怎么插入 mermaid 图标，怎么点击，是否可以截图

**Comment by MrHeer** [comment]
1. 先插入 `mermaid` 图表
  ```mermaid
  graph TD
    Start --> Stop
  ```
2. 将鼠标移动到图标区域，然后再移出，反复几次
3. 例如：
![Screen record from 2020-02-23 13 46 28](https://user-images.githubusercontent.com/18595761/75104409-a9d00000-5643-11ea-83ad-5987352c36e0.gif)

**Comment by fxha** [comment]
@MrHeer Can you still reproduce the issue?

**Comment by MrHeer** [comment]
No problem now
