### ISSUE TITLE
remember sidebar status

### ISSUE THREAD

**Issue by itviewer** [marktext/marktext#1920]
### Describe your feature request
remember sidebar open status

 every time you open a document then manually open the sidebar is too annoying

**Comment by fxha** [comment]
Duplicate of #519. You can set the prefered option in setting (settings file only via `sideBarVisibility`), please see [here](https://github.com/marktext/marktext/blob/develop/docs/PREFERENCES.md#view).

**Comment by YalandHong** [comment]
I think this is more likely a duplicate of #2378, which has been merged into #1274.

The author wants MarkText to **remember** the status of sidebar upon closing, not to forcibly open the sidebar every time.
