### ISSUE TITLE
What content of file would be auto changed on open?

### ISSUE THREAD

**Issue by zpdcodes** [marktext/marktext#1922]
I opened a markdown file and did nothing to change the file manually, but Mark Text tells the file has changed when I try to close the editor. The markdown file is from macos and opened in linux. What could be the possible cause for this behavior? Does Mark Text auto change something of file on open, like encoding?

**Comment by Jocs** [comment]
@zpdcodes it maybe due to this reason https://github.com/marktext/marktext/issues/1354

**Comment by zpdcodes** [comment]
@Jocs Thanks. Mark Text auto formats my file on open, inserting some empty lines. Same issue as #1354
