### ISSUE TITLE
cannot insert image with Aidou

### ISSUE THREAD

**Issue by miao17game** [marktext/marktext#1924]
### Description

Cannot insert image with Aidou.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. ctrl+/
2. search with keywords
3. click image
4. nothing happened...

**Expected behavior:**

insert image with image url into my file in the correct position

**Actual behavior:**

nothing happened.

### Versions

- Mark Text: 1.15.1
- Operating system: Windows 10 Pro 10941.84
- Image Settings: Use github uploader

**Comment by miao17game** [comment]
Is this the expected behavior? or i should drag the image to desktop and insert it manually? 🤔

**Comment by swift502** [comment]
I also got confused with that. Clicking on the gifs seems to do nothing. I'm on Windows 10 also.

**Comment by TangXinGithub** [comment]
I meet also same bug

**Comment by 1354686404** [comment]
I meet the same bug in MacOS 10.13.5

**Comment by bravekingzhang** [comment]
看了下源码，应该是sm图床api升级导致的，不知道formdata中是否在支持blob了，也不大好调试，等官方修复

**Comment by bravekingzhang** [comment]
```js
 sm (base64) {
    const api = 'https://sm.ms/api/upload'
    const data = new window.FormData()
    data.append('smfile', dataURItoBlob(base64))
    return axios.post(api, data).then(({ data }) => {
      const { data: res } = data
      return {
        url: res.url,
        err: '',
        server: 'sm'
      }
    }).catch(err => {
      console.log(err)
    })
  }
}
```
现在api已经是V2版本了，https://sm.ms/api/v2/upload，麻烦官方适配一下，另外fetchImgToBase64函数，response拿到的data是一个string，虽然axios中指定responseType是blob。

```js
fetchImgToBase64 (url) {
    return axios({
      method: 'get',
      url,
      responseType: 'blob'
    })
      .then(({ data }) => new Promise((resolve, reject) => {
        const reader = new window.FileReader()
        reader.onloadend = () => {
          console.log(reader)
          resolve(reader.result)
        }
        reader.onerror = reject
//这里需要加一个判断，转一下
        if (typeof data === 'string') {
          data = new Blob([data])
        }
        reader.readAsDataURL(data)
      }))
  },
```

**Comment by bravekingzhang** [comment]
> Is this the expected behavior? or i should drag the image to desktop and insert it manually? 🤔

显然不是，以前用过，是点下就插入了，看代码也是有那个回调的，只不过，现在上传图片就挂了。

**Comment by Jocs** [comment]
@bravekingzhang 欢迎提交 PR

**Comment by bravekingzhang** [comment]
@Jocs 我机器特别渣，run dev起来卡爆了，试着改了下没成功，我机器调试时卡到爆，碎放弃。

**Comment by bravekingzhang** [comment]
@Jocs 大佬有空修复下，应该是接口不支持了，github不能上传图片原因差不多。

**Comment by Jocs** [comment]
好的👌

发自我的iPhone

**Comment by ZhuJinquan** [comment]
还是不能用

**Comment by EightEggs** [comment]
This issue still exists...

(On Windows11.

**Comment by Jocs** [comment]
@EightEggs PR is welcomed.
