### ISSUE TITLE
Codeblock colors don't adhere to theme colors

### ISSUE THREAD

**Issue by Gurran** [marktext/marktext#1926]
### Description
When exporting a file containing a codeblock the colors shown in the editor is _not_ the same colors that shown up in the exported file.

- [x] Can you reproduce the issue?

### Steps to reproduce 
``scss
$var-name: (

  a: $other-var,

  b: $other-var,

  c: $other-var,

  d: false,

  e: $other-var,

  f: true

);
``

![image](https://user-images.githubusercontent.com/42462633/75158712-02240200-5717-11ea-98f3-2252347315d1.png)

### Steps to reproduce

1. Make a codeblock of type scss
2. Make a scss variable 
3. export as either html or pdf

**Expected behavior:**

The colorscheme shown in marktext should also be shown in the exported file

**Actual behavior:**
The colorscheme shown in the exported file is always the same. Not taking theme selection into account. 

**Link to an example: [optional]**

![image](https://user-images.githubusercontent.com/42462633/75159193-f5ec7480-5717-11ea-887d-449a516815dd.png)

### Versions

- Mark Text:
![image](https://user-images.githubusercontent.com/42462633/75159246-07ce1780-5718-11ea-80be-edb98e08d994.png)

- Operating system: Microsoft Windows [Version 10.0.19569.1000]

**Comment by fxha** [comment]
Thank you for reporting the issue. We use the light theme with PDF files and light themes instead the dark theme that is used with dark themes.
