### ISSUE TITLE
Mark Text does not support footnotes

### ISSUE THREAD

**Issue by johnblommers** [marktext/marktext#193]
### Request support for footnotes

Many Markdown processors support footnotes so it would be nice to have it in marktext.

### Steps to reproduce

1. Insert into the text [^XYZ] to denote a footnote
2. Insert elsewhere the text on its own line [^XYZ]: Text for the footnote
3. When the markdown is rendered as HTML the footnotes appear at the bottom.
4. When the markdown is exported to PDF the footnotes appear at the bottom of the page.

**Expected behavior:** Footnotes appear at the bottom of the HTML page or corresponding PDF page.

**Actual behavior:** The footnote syntax is printed verbatim

### Versions

- Mark Text: v 0.10.21
- OS: Mac OS 10.11.6 El Capitan

**Comment by Jocs** [comment]
As mentioned in #195 ,we plan to support GFM syntax first, then we'll add some external syntax.

**Comment by Jocs** [comment]
@johnblommers I have research the [pandoc's footnote](https://pandoc.org/MANUAL.html#footnotes)

it's syntax like this:

```md
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

        { some.code }

    The whole paragraph can be indented, or just the first
    line.  In this way, multi-paragraph footnotes work like
    multi-paragraph list items.

This paragraph won't be part of the note, because it
isn't indented.
```

the `longnote` footnote with multiple blocks, so do you need multiple blocks?
