### ISSUE TITLE
muya 中 postcss 变量是在哪里定义的？

### ISSUE THREAD

**Issue by lilee** [marktext/marktext#1934]
###  muya 中 postcss 变量是在哪里定义的？

想在自己的 React 工程中引入 muya，引入后发现 css 中的变量没有被替换，我也按`webpack.config.js`中写的那样引入了`postcss-loader` 并设置了相关参数。

另外，很希望作者能维护一个稳定的 npm 包

**Comment by Jocs** [comment]
>想在自己的 React 工程中引入 muya，引入后发现 css 中的变量没有被替换，我也按webpack.config.js中写的那样引入了postcss-loader 并设置了相关参数。
