### ISSUE TITLE
PDF Export is contacted by LaTeX hightlight

### ISSUE THREAD

**Issue by johnblommers** [marktext/marktext#194]
### The PDF export includes the onscreen LaTeX highlight

The PDF export appears to literally render whatever is present in the HTML preview. If you have clicked into a LaTeX expression the preview balloon is present in the PDF export. If you just checked for updates to marktext then the notification is printed at the bottom of each PDF page.

### Steps to reproduce

1. Check for updates
2. Enter a LaTeX expression and leave the cursor in it to reveal the preview balloon
3. Export to PDF

**Expected behavior:** No LaTeX preview balloon and no update status message should appear in the PDF output.

**Actual behavior:** The LaTeX preview balloon appears in the output, and the update status message appears at the bottom of each PDF page.

### Versions

- Mark Text: v 0.10.21
- OS: MacOS 10.11.6 El Capitan

**Comment by Jocs** [comment]
This issue will be fixed in the next released version.
