### ISSUE TITLE
No support for subscripts and superscripts

### ISSUE THREAD

**Issue by johnblommers** [marktext/marktext#195]
### No support for subscripts and superscripts

In other Markdowns you can write an expression like a~2~ x^2^ to express simple algebra.

### Steps to reproduce

1. Write the text a~2~ x^2^
2. Click elsewhere to allow the text to render
3. Nothing special happens and we don't get a nice algebra formula

**Expected behavior:** We should see subscripts and superscripts

**Actual behavior:** The literal text is rendered instead.

The workaround is to use LaTeX instead $a_2 x^2$

### Versions

- Mark Text: v 0.10.21
- OS: MacOS 10.11.6 El Capitan

**Comment by Jocs** [comment]
We are focus on [GFM](https://github.github.com/gfm/) syntax before v1.0.0, we'll take `subscripts` and `superscripts` into consideration after v1.0.0 released.

**Comment by samuelmehr** [comment]
for academic writing scientists generally use R Markdown, would be awesome if this could be supported (e.g. caret syntax for ^superscripts^)

**Comment by Jocs** [comment]
@samuelmehr I reopened this feature request issue, for support `^super^` and `~sub~` syntax.
