### ISSUE TITLE
Double * for bold does not allow "type-over" like a single *

### ISSUE THREAD

**Issue by pelegm** [marktext/marktext#1952]
### Description

Typing `*` complete to `**` (with the right preference turned on), which is nice. Now, typing a character (say, `x`) and then another `*` brings the state to `*x*`, which is expected. Trying the same with `**` instead of `*` (for bold), fails.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Type `**`
2. Type `x`
3. Type `**`

**Expected behavior:**

I would have expected to see at this point `**x**`, which translates to bold `x`.

**Actual behavior:**

I see instead `**x****`, which translates to bold `x**`.

### Versions

- Mark Text: v0.15.1
- Operating system: Ubuntu 18.04.4

**Comment by Jocs** [comment]
Normal interaction because `*` autocompletion.
