### ISSUE TITLE
Switching tabs using alt-#

### ISSUE THREAD

**Issue by pelegm** [marktext/marktext#1953]
### Describe your feature request

It would be nice to switch tabs using alt-<tab #>.

### What problem does this feature solve?
This is the default behaviour in many applications (at least in Ubuntu). Examples include firefox, nautilus, gnome-terminal, etc.

I know (from #1283) that <kbd>Ctrl</kbd>-<kbd>Tab</kbd> should cycle through tabs, but (a) it doesn't seem to work at all in Ubuntu, and (b) there's a default behaviour I've mentioned earlier *in addition* to this tab cycling (which is *good*).

**Comment by MrHeer** [comment]
I want to take it.
