### ISSUE TITLE
Tab scrolling using ctrl-tab doesn't work in Ubuntu

### ISSUE THREAD

**Issue by pelegm** [marktext/marktext#1954]
### Description

Tab scrolling using ctrl-tab doesn't seem to work at all in Ubuntu.

I've noticed this bug when opening the feature request #1953, which should be an extension to the tab cycling feature.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open marktext
2. Open a new tab using <kbd>Ctrl</kbd>-<kbd>n</kbd>
3. Press <kbd>Ctrl</kbd>-<kbd>Tab</kbd>

**Expected behavior:**

The tab should switch from the second one to the first one.

**Actual behavior:**

4 spaces are being inserted, and the tab is not switched.

### Versions

- Mark Text: v0.15.1
- Operating system: Ubuntu 18.04.4

**Comment by fxha** [comment]
Thank you for reporting the issue. Unfortunately, v0.15.x has no support of these shortcuts and our documentation is based on v0.16.x. You can try out our latest release candidate [here](https://github.com/marktext/marktext/releases/tag/v0.16.0-rc.3).
