### ISSUE TITLE
No option for spell check on mac OS Catalina

### ISSUE THREAD

**Issue by prash-kr-meena** [marktext/marktext#1955]
### I wasn't able to find any option for enabling spell checking on the mark text's mac app.

Is this feature built on mac?  I am studying the documentation and in there it does mention spell check in  mac, but i am unable to find it.

**Comment by pelegm** [comment]
I also don't see spell check in my Ubuntu 18.04.4, marktext v0.15.1.

**Comment by fxha** [comment]
Yeah your right, our documentation is based on v0.16.x that is currently in testing. Unfortunately, v0.15.x has no spell checking but you can download the latest release candidate from Github releases.
