### ISSUE TITLE
Pandoc Integration

### ISSUE THREAD

**Issue by integzz** [marktext/marktext#1956]
### Describe your feature request

Hi, Marktext ! Your app is great, it is the best open source markdown editor.

I think it can be better if it has **Pandoc** integration.

### What problem does this feature solve? [optional]

**Pandoc** is a swiss knife for document format convertion, and it can rise the work efficiency.

### Additional context [optional]

Moreover, if you can add **.bibex** integration, that would be perfect for a student like me. 

Thank you.

**Comment by FilipVerhaeghe** [comment]
It is important that MarkText is MIT, whereas Pandoc is GPL. At the very least, the way it is integrated matters. Also, the rendering is not the same, as Pandoc makes its own choices.
