### ISSUE TITLE
[Feature Request] Quick filter by filename with hotkey

### ISSUE THREAD

**Issue by zpdcodes** [marktext/marktext#1960]
### Describe your feature request

It would be good if we have quick filter function to filter files by filename. It can be a filter box in the files list view and refresh instantly while typing, or like the "go to anything" function in Joplin app. And it's different from current search function. 

### What problem does this feature solve? [optional]

The goal of this filter feature is to find file by minimal keystrokes without mouse movement. Current search function has no hotkey and cannot refresh instantly while typing in the search box.

**Comment by fxha** [comment]
Thank you for taking the time to report the issue. We already added a quick open dialog (<kbd>CmdOrCtrl</kbd>+<kbd>P</kbd>) to quickly open a file from the opened root directory or editor in our latest release canidate. You can download the latest release candidate from Github releases. Feel free to reopen the issue, if this is not a duplicate.

![mt_quick_open](https://user-images.githubusercontent.com/22716132/76361265-ee83b880-631e-11ea-8f1a-2b5a4b4832a4.png)
