### ISSUE TITLE
Rendering of notes is significantly slower when I add mermaid diagrams. 

### ISSUE THREAD

**Issue by j718** [marktext/marktext#1962]
### Description

When I add a mermaid diagram, everything that I add afterwards takes a very long time to load. Are the diagrams being rerendered with each change?
- [ X] Can you reproduce the issue? 

### Versions

- Mark Text: 0.16.0-rc.3
- Operating system: Windows 10

**Comment by persidskiy** [comment]
Having the same issue. Rendering becomes very slow and hungs up my Mac for several seconds.
Most of the time it happens when I edit Paragparh after Mermaid diagram.
