### ISSUE TITLE
Wish Add Cypher Syntax Highlight

### ISSUE THREAD

**Issue by fish-404** [marktext/marktext#1964]
Wish add Cypher syntax highlight in code block.
It's used in Neo4j which is a graph database.
The Cypher manual : [The Neo4j Cypher Manual v3.5](https://neo4j.com/docs/cypher-manual/3.5/).

**Comment by fxha** [comment]
Thank you for reporting the issue. Please open an upstream issue on prism.js that is used to highlight code blocks.
