### ISSUE TITLE
Don't Modify File Just by Viewing

### ISSUE THREAD

**Issue by Greg-McPherran** [marktext/marktext#1966]
### Description

When open existing file just to view, it becomes modified, and because I use AutoSave, it saves the changes. The changes made relate to adding blank line after SetExt heading (e.g. heading 2). When I edit it as text I have no blank line after the SetExt "-----------------" but MarkText adds it. Even if this or other sytnax is not right, I don't want MarkText to change the file automatically (i.e. unless I want it to.)

Great Markdown tool, by the way!!

- [x] Can you reproduce the issue? 

### Steps to reproduce
1 .Edit with normal text editor:
```
Test Heading
--------------
Test line of data.
```

2. Open with Marktext with AutoSave on and file is changed such that if again open with normal text editor it appears as follows with blank line added after heading:

```
Test Heading
--------------

Test line of data.
```

**Expected behavior:**

File should not be modified and saved automatically (e.g. with blank line added).

**Actual behavior:**

Blank line is added triggering file save because AutoSave is on.

### Versions

- Mark Text: 0.16.0-rc3
- Operating system: Windows 10.0.18362

**Comment by zpdcodes** [comment]
The automatic changes issue is discussed at #1354 . For now MarkText would parse the file before showing it in editor, which cause some automatic changes.

**Comment by Greg-McPherran** [comment]
Solution: Offer and "Open for Viewing" menu option, that opens the file as read only. From there the user could switch to "editing mode" if they want.

This allows you to keep parsing and changing your internal buffer the way that you already do - just the buffer won't be treated as a file to be saved unless user switches to "edit mode".

Thank You.

**Comment by zpdcodes** [comment]
@Greg-McPherran As a suggestion, you might close this issue and follow up to #1354 to get latest update related to automatic changes. The dev team are discussing possible option there. I'm also a user who wants the read-but-not-auto-change behavior.

**Comment by fxha** [comment]
I'm closing this issue in favour of #2189. You may want to subscribe there for further updates.
