### ISSUE TITLE
[No offense]This application is badly translated.

### ISSUE THREAD

**Issue by maidmeow4** [marktext/marktext#1967]
### Question description

It's a really nice markdown editor, but those descriptions in settings window is translated really bad, and very hard to understand.
For instance, see the screenshot here
![image](https://user-images.githubusercontent.com/8447650/76179861-34ddf800-61f7-11ea-8f20-079d70355270.png)

Perhaps the developers are not good at the English language?
My opinion is that we should use Chinese for default langauge now, and refine translations, so we can have a better user experience when switching language is shipped to the users.

**Comment by fxha** [comment]
Thanks @maidmeow4 for your feedback. You could try out the latest release candidate from Github releases that include a lot of enhancements and features. There is also an open PR (#1967) to improve overall spelling. If you find other spelling mistakes or possible improvements, feel free to comment or open issues, so we can solve these issues.
