### ISSUE TITLE
Does rendering happen locally only?

### ISSUE THREAD

**Issue by davidmichaelhuber** [marktext/marktext#1971]
When viewing/editing files with Mark Text will the data in those files ever leave my system? Is anything rendered by an external api of some sort or does everything happen locally?

**Comment by fxha** [comment]
Thanks @davidmichaelhuber for your question. No, Mark Text is a desktop application that doesn't require a internet connect and *all data is processed locally* in the application. We do not make any http requests or send any user data to a (external) server. However, we fetch external images that are embed in your markdown document or check automatically for updates in some packages. Feel free to ask more questions if you like.

**Comment by davidmichaelhuber** [comment]
Alright, thanks a lot!

So just for clarification, as long as "Image" > "Insert absolute or relative path of image" is selected my local images will never ever get uploaded somewhere but are solely copied into the specified local image folder, right?

**Comment by fxha** [comment]
Yes that's right, as long as you don't select "upload to cloud".
