### ISSUE TITLE
The document scroll doesn't follow the text input on macOS Catalina

### ISSUE THREAD

**Issue by magnus-w** [marktext/marktext#1972]
## Description
When writing a document and the text gets longer than the size of the app window, the document doesn't 'scroll with' the writing but the writing disappears under the lower end of the app window. 

Just to compare, this isn't true in v0.15.1 on Elementary OS. There, the document automatically scrolls down to follow the text input when it goes below the lower edge of the document window, as expected. 

*Versions*
**Mark Text:** 0.15.1 (the latest version, downloaded this weekend)
**Operating system:** macOS Catalina 10.15

**Comment by fxha** [comment]
@magnus-w Thanks for your feedback! We already changed the behavior to automatically follow the cursor while writing. You can try the latest testing version from Github releases (`v0.16.0-rc.3`).

**Comment by magnus-w** [comment]
👍

[https://res.gethop.com/c/?id=bs8vkvuhyijfcdh5&s=48&m=c&_ts=fc2dn]              Magnus Westerberg - Chat @ Spike<https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=fc2dn>       [fc2dn]

On March 17, 2020 at 18:19 GMT, Felix Häusler <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1972<https://github.com/marktext/marktext/issues/1972>.
