### ISSUE TITLE
I cannot find spelling options

### ISSUE THREAD

**Issue by Li-An** [marktext/marktext#1990]
### Description

Hello, I must be blind, I don’t find spelling options in Preferences. The official Wiki talks about Settings but I don’t find how to show this.

### Steps to reproduce

Find Settings window

**Expected behavior:**

Easy to find Settings

**Actual behavior:**

Cannot find Settings

### Versions

- Mark Text: 1.5.1
- Operating system: Win 10 64 bits

**Comment by acicovic** [comment]
Hi,

As far as I know this will be released in 1.6. It should be in the 1.6 pre-releases.

**Comment by Li-An** [comment]
Thanks. Do you know where I can find the 1.6 RC  ? I cannot find.

**Comment by acicovic** [comment]
You can find all releases including pre-releases here:
https://github.com/marktext/marktext/releases

**Comment by Li-An** [comment]
Thanks à lot :-)
