### ISSUE TITLE
macOS Malware Alert

### ISSUE THREAD

**Issue by znatno** [marktext/marktext#1991]
### Description

Apple alert that app can be malware

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Move App to /Applications/
2. Open App

**Expected behavior:**

Opens the app

**Actual behavior:**

Showing alert

**Link to an example: [optional]**

### Versions

- Mark Text: 0.15.1
- Operating system: macOS 10.15.3

**Comment by a-heryani** [comment]
Confirming same behaviour on macOS Catalina 10.15.4

<img width="419" alt="image" src="https://user-images.githubusercontent.com/26278881/78508634-a8a9fb00-77cb-11ea-8114-ae7be49b23b1.png">

**Comment by a-heryani** [comment]
Any plans to sign the app with a verified developer cert?

**Comment by fxha** [comment]
> Any plans to sign the app with a verified developer cert?

That is the plan for later versions when Mark Text is more stable as the certificate cost around 100$/y.

/cc @Jocs

**Comment by fulldecent** [comment]
Thing big!

Recommend to start a fundraiser to get the $100 per year (plus more, you're worth it) and sign the binary.
