### ISSUE TITLE
Increase folder indentation?

### ISSUE THREAD

**Issue by IORoot** [marktext/marktext#1995]
### Question description

Hi. Is there any way to increase the indentation width of the subfolders in the side panel? It's a little narrow for my taste. It looks to be about 6px difference between the parent folder and child, but I'd preferably want it at least the width of the icon, maybe more, which seems about 12 - 15px. 
If this isn't possible, perhaps this could be a feature request instead? 
Thanks.

**Comment by berkcodes** [comment]
This. Currently it's difficult to tell the hierarchy of the folder. Just a bit more indentation would be nice, similar to Typora's.

**Comment by qihuazhong** [comment]
Exactly what I am experiencing. Thanks for pointing it out.

**Comment by fxha** [comment]
This issue was fixed and will be release in version 0.16.2 soon.
