### ISSUE TITLE
GIT Support

### ISSUE THREAD

**Issue by Drallas** [marktext/marktext#1996]
I think it would be nice to have support for Git Commit / Push from the editor?
Some of my libraries are connected to a Github / Gitlab repository and now i need to leave Mark Text to sync upstream. I know it has been asked before but i think it shoud be reconsidered!

**Comment by sfjohansson** [comment]
Maybe a way to do this could be to  have to have generic “marktext hooks”, for events like modifying/saving/add image/closing app. Users could hook up their own system commands.

**Comment by Jocs** [comment]
For the time being, we will not consider supporting Git directly in marktext. We should consider that marktext is just a markdown editor. Later, it supports plugin extensions. Git can be introduced as a plugin.
