### ISSUE TITLE
An error occurred while copying

### ISSUE THREAD

**Issue by LuckyHookin** [marktext/marktext#1998]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

![1](https://user-images.githubusercontent.com/45350455/77394956-81baf480-6ddb-11ea-9d73-c2dee22ae560.gif)

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text: 0.16.0-rc.3
- Operating system: win10

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate of #1821. You may want to subscribe there for further updates.
