### ISSUE TITLE
Open with not working on Win

### ISSUE THREAD

**Issue by SuperSandro2000** [marktext/marktext#20]
### Description

Mark Text does not support Windows "Open with.." feature.

### Steps to reproduce

1. Associate .md files with Mark Text/
2. Open md file
or run "C:\Program Files\Mark Text\Mark Text.exe" README.md in a folder with a README.md file

**Expected behavior:** Open that md file

**Actual behavior:** blank page

### Versions

- Mark Text: 0.6.14
- OS: Win10 64 Bit, Win7 64 Bit

**Comment by Jocs** [comment]
@notAlaanor Can you help with this issue? I don't have a Win10 system.

**Comment by SuperSandro2000** [comment]
Just to let you know. I tested it on my Windows 7 VM and I think this is broken on all Windows versions.

**Comment by Jocs** [comment]
@SuperSandro2000 Thank you for reporting this issue, it maybe a common bug in all Windows version, PR is welcome.
