### ISSUE TITLE
Image path autocomplete is bugged

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2001]
### Description

If you want select an image path from path auto-completion the existing text is not replaced.

### Steps to reproduce

1. `![]()` -> the image picker overlay is shown.
2. Write `as`, now you get a completion list of `assets/`.
3. Select  `assets/`.
4. The result will be `asassets/` instead `assets/`.

**Expected behavior:**

The old text should be removed, so that we got `assets/` as path.

### Versions

- Mark Text: v0.16.0.rc.x
- Operating system: all

**Comment by yhancik** [comment]
I should add that after clicking the autocompleted suggestion, the suggestion dropdown remains visible, hiding the "Embed image" button.
