### ISSUE TITLE
Underline in spelling error is not showing

### ISSUE THREAD

**Issue by Li-An** [marktext/marktext#2015]
### Description

Spelling errors are not underlined

**Expected behavior:**
It should work :-) (it worked on a previous version)
The right click suggestion works as intended.

### Versions

- Mark Text: 0.16.1
- Operating system: Win 10 64 bits

**Comment by fxha** [comment]
Thank you for taking the time to report this issue but unfortunately, we cannot reproduce the issue. Please provide steps or an example that we can reproduce the issue. Maybe you enabled "don't underline spelling mistakes" in settings?

**Comment by Li-An** [comment]
OK, I’m French, so I chose **Français** as language. But it does not work with this choice. If I choose another suggested language as English (en-US) or Français (fr-BE), it works correctly. So I don’t have some Français (fr-FR) to choose. I may stay with another Français (fr-xx) but it’s a little frustrating.

<img width="713" alt="2020-03-29_15h45_37" src="https://user-images.githubusercontent.com/689870/77850798-202cc880-71d5-11ea-9106-44c5db1d379f.png">

**Comment by fxha** [comment]
Unfortunately, I cannot reproduce the issue on Windows 10 (18363.752) but I don't have the French dictionary installed, only German and English.

> it worked on a previous version

What do you mean by that? We haven't changed anything on the spellchecker. However, it may an issue with Windows spell checker or dictionaries that we use by default on Windows 10. You might want to try out Hunspell spell checker that is build-in but you need to manually download dictionaries via settings.

**Comment by Li-An** [comment]
I tried a previous beta version and it seems to me that it worked. It’s not a big problem as I said before but it’s kinda strange but it could be relative to my configuration.

**Comment by acicovic** [comment]
I can confirm that words with spelling mistakes are not underlined (Windows 10 x64 1909). I tried to play around with spelling settings but no results. @fxha it works well for you?

I think that it is an important issue for certain users that use Mark Text to write large reports or articles. For example, in my case I write English, French and Greek every day and I'm not skilled equally in every language. So underlining mistakes is a life-saver for me.

Can I do something to help troubleshoot?

Thank you for all the work you've been putting into Mark Text!

**Comment by acicovic** [comment]
Hm, now it works. So tinkering with settings changed something. I'll see if I can narrow it down.

**Comment by acicovic** [comment]
OK, so I'm using the OS spellchecker (Windows 10 x64 1909). The option that disables underlining is the "Automatically identify the used language".

Can you reproduce it?

**Comment by fxha** [comment]
@acicovic Yes, thanks for the hint! The used language is currently only detected on macOS, so you should disable it until we fix the issue or enable that feature on Windows.

Steps to reproduce:

1. Enable "Automatically identify the used language" in settings
2. Open another window
3. Issue occurs

I guess there is an issue when initializing spell checker because the feature is currently not used on Windows.
