### ISSUE TITLE
Incorrect sha256 hash for v0.16.1 dmg installer on macOS

### ISSUE THREAD

**Issue by Loyalsoldier** [marktext/marktext#2016]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Download v0.16.1 dmg file
2. `shasum -a 256 marktext.dmg`
3. The output sha256 hash is `676fbcb7230e736f6b41b3ee21df864131565dee45b212b658990e7760218962`, different from the one written in release note.

### Versions

- Mark Text: v0.16.1
- Operating system: macOS Catalina 10.15.4

**Comment by Jocs** [comment]
Updated, can you help check is it right now?

**Comment by Loyalsoldier** [comment]
It is correct now.

But you miss the sha256 hash of files `marktext-amd64.deb` and `marktext-x86_64.rpm`
