### ISSUE TITLE
After I changed the maximum width of the editor area, the contents of the file could not be fully displayed

### ISSUE THREAD

**Issue by chinagui** [marktext/marktext#2019]
### Description

After I changed the maximum width of the editor area, the contents of the file could not be fully displayed. But not for all files. These document was previously written by typora.
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]Click the preference of Mark Text, then select Edtior item, define the maximum width of the editor area to be 90%.
2. [Second step]Open a md file

**Expected behavior:**

The contents of the file could be fully displayed in the editor area.
**Actual behavior:**

The contents of the file could not be fully displayed. There is a large blank space on the left of the editor area, likes a big margin on the left. And the contents of the file on the right are out of the screen.
**Link to an example: [optional]**

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. We cannot reproduce this issue, please provide some steps how the error occurred or upload a file, so we can reproduce the issue.

**Comment by syco** [comment]
Hi,
I'm having the same issue, I've set the maximum width to 100%, and this is what happened as I resize the window down:
Very large window, width larger than longer text line:
![image](https://user-images.githubusercontent.com/54575/111139058-90fcfa00-8578-11eb-8a08-df872d10b7ce.png)
Large window, width larger than longer text line:
![image](https://user-images.githubusercontent.com/54575/111138996-804c8400-8578-11eb-80dd-24561b270c86.png)
Small window, width now smaller than longer text line:
![image](https://user-images.githubusercontent.com/54575/111139093-98bc9e80-8578-11eb-8b4a-97913705020e.png)

**Comment by YalandHong** [comment]
The description in this issue is vague. Possibly related to #2608

**Comment by fxha** [comment]
The editor content (especially code blocks) may overflow if you set maximum width of the editor in settings and open the sidebar or resize the window small. We may overwrite the automatic resize property of the editor view.

[Example document (markdown syntax)](https://github.com/marktext/marktext/blob/develop/docs/MARKDOWN_SYNTAX.md)
