### ISSUE TITLE
Table inside a list is not supported

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#202]
### Description

Table inside a list is not supported.

### Steps to reproduce

```
- a

- b

  | foo     |     |     |
  | ------- | --- | --- |
  | bar     |     |     |
  | baz     |     |     |
  |         |     |     |
```

**Expected behavior:** [What you expected to happen]

List with a table

**Actual behavior:** [What actually happened]

List with markdown table text

### Versions

- Mark Text: v0.10.21 / master
- OS: all

**Comment by Jocs** [comment]
@fxha Do you want to fix this?

**Comment by fxha** [comment]
@Jocs  I really don't have time for this. But if you don't want to fix it, then later.

**Comment by Jocs** [comment]
I'm going to prepare a technical seminar, so I didn't have much time to maintain Mark Text before May 20th. It's okay. We are not in a hurry.
