### ISSUE TITLE
Spell checker keyboard shortcut

### ISSUE THREAD

**Issue by faldor20** [marktext/marktext#2025]
### Describe your feature request

A keyboard shortcut or bringing up the spell check menu.
A shortcut for moving the cursor to the next error would be amazing too.

### What problem does this feature solve? [optional]

Allows quick spell checking more quickly and easily 

### Additional context [optional]

Caret markdown editor has this and it is extremely handy.

**Comment by fxha** [comment]
I'm closing this issue as we currently don't plan to implement this feature but we may reopen it on demand.
