### ISSUE TITLE
Any plan for support more image uploader?

### ISSUE THREAD

**Issue by moriwang** [marktext/marktext#2031]
### Describe your feature request

There are many open-source image uploader tools like [uPic](https://github.com/gee1k/uPic), [PicGo-Core](https://github.com/PicGo/PicGo-Core) can allow us to customize the image hosting to Github, Amazon S3, Imgur, custom upload api, etc

Bring these tool into Marktext can improve the writing experience a lot.

**Comment by fxha** [comment]
Thank you for reporting the issue. This is planned later via plugins.
