### ISSUE TITLE
Option for always visible markdown 

### ISSUE THREAD

**Issue by larabr** [marktext/marktext#2033]
### Describe your feature request
I'd like to have the markdown symbols always visible, not just when I click on styled words (e.g. I always want to see \*\***bold words**\*\* instead of **bold words** regardless of where the cursor is).
Is there already an option for this, which I have overlooked?
If not, I can also implement this change myself.. could you point me to the relevant code in case?

Thanks for the great editor!

PS: I am aware there is the Source Code mode, but I still want the file typesetted "nicely" like in normal view, just with added symbols.

**Comment by larabr** [comment]
Update: I've actually managed to implement this already (it's in my forked repo). Let me know if you'd like to add an option in the preferences to toggle this mode, then I can make a PR.

**Comment by Jocs** [comment]
We still hope that the markdown syntax marker can be hidden when it is not being edited, and we don't want to expose too much markdown syntax, so that users are actually unaware of the markdown syntax when using Mark Text.
