### ISSUE TITLE
Pressing the Focus Mode shortcut brings up the Search Sidebar

### ISSUE THREAD

**Issue by sabretou** [marktext/marktext#2040]
### Description

When I press the shortcut for entering Focus Mode (Ctrl+Shift+F), Mark Text instead opens the Search sidebar. It does not enter Focus Mode. Pressing the shortcut again while the search sidebar is open has no effect.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a file, or create a new file
2. Press Ctrl+Shift+F

**Expected behavior:**

Mark Text should enter Focus Mode.

**Actual behavior:**

The Search Sidebar opens.

**Link to an example:**

![2020-04-11 21_24_47-Untitled-1 - Drafts](https://user-images.githubusercontent.com/7028559/79048473-e62ede00-7c3a-11ea-8731-3310f938d365.png)

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10 Home 64-bit

**Comment by hematogender** [comment]
I have the same problem, it really worsens my performance, because these settings are not remembered.

By the way, the Typewriter Mode shortcut (Alt + Ctrl + T) doesn't work at all, could it be related? The Source Code Mode (Alt + Ctrl + S) works fine, though.

**Comment by iJunkie22** [comment]
I have found that remapping Toggle Focus mode to use Alt instead of Shift (and remapping Replace so it doesn't conflict) makes it work. I also found that at least on Mac, the shortcut works if you have the View menu already open. It appears someone has already unsuccessfully attempted to remedy this by wrapping the typewriter mode and focus mode callbacks in this little function
```javascript
const focusEditorAndExecute = fn => {
  setTimeout(() => bus.$emit('editor-focus'), 10)
  setTimeout(() => fn(), 150)
}
```

The bindings [live here](https://github.com/marktext/marktext/blob/develop/src/renderer/commands/index.js#L623) and look like this
```javascript
// --------------------------------------------------------------------------
  // View

  {
    id: 'view.source-code-mode',
    description: 'View: Toggle Source Code Mode',
    execute: async () => {
      bus.$emit('view:toggle-view-entry', 'sourceCode')
    }
  }, {
    id: 'view.typewriter-mode',
    description: 'View: Toggle Typewriter Mode',
    execute: async () => {
      focusEditorAndExecute(
        () => bus.$emit('view:toggle-view-entry', 'typewriter')
      )
    }
  }, {
    id: 'view.focus-mode',
    description: 'View: Focus Mode',
    execute: async () => {
      focusEditorAndExecute(
        () => bus.$emit('view:toggle-view-entry', 'focus')
      )
    }
  }, {
    id: 'view.toggle-sidebar',
    description: 'View: Toggle Sidebar',
    execute: async () => {
      bus.$emit('view:toggle-view-layout-entry', 'showSideBar')
    }
  }, {
    id: 'view.toggle-tabbar',
    description: 'View: Toggle Tabs',
    execute: async () => {
      bus.$emit('view:toggle-view-layout-entry', 'showTabBar')
    }
  },
```
