### ISSUE TITLE
windows 最新版斗图点击无反应 无法选择

### ISSUE THREAD

**Issue by nafei-zhang** [marktext/marktext#2045]
ctrl+/ 斗图调用出来，无法选择，
![issue](https://user-images.githubusercontent.com/32798948/79245735-1086d280-7eab-11ea-9010-e9146496d96b.gif)
请检查图片。为啥不能选择搜索到的斗图

**Comment by Jocs** [comment]
斗图在新版将被移除，请自己搜索图片插入
