### ISSUE TITLE
Code blocks always default jump to left

### ISSUE THREAD

**Issue by Menn1s** [marktext/marktext#2046]
### Description
When using a code block, any code block with text that extends beyond the width of the code block will cause this behavior. When I am trying to type more code at the end of the line, it will constantly jump back to the left of the line, making it difficult to see what I am typing at the end of the line.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a code block with triple backticks
2. Type beyond the right edge of the code block so it starts scrolling

**Expected behavior:**

The code block will follow the cursor so that I can see what is being typed at the end of the line.

**Actual behavior:**
The code block will jump to the end of the line only briefly while I am typing, before jumping back to the left (beginning) of the line.

### Versions

- Mark Text: v0.16.1
- Operating system: OSX 10.15.3

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate of #2000. You may want to subscribe there for further updates.
