### ISSUE TITLE
URL's with trailing slashes are not recognized

### ISSUE THREAD

**Issue by eagleofnorth** [marktext/marktext#2047]
### Description

Mark Text does not always make URL's clickable when the URL has a trailing slash. 

### Steps to reproduce

1. Open an empty document in Mark Text
2. Paste (or type) the following text:

```
# Link testing

https://www.google.com/

https://www.google.com

https://www.google.com/
```

**Expected behavior:**

All three links should be recognized by Mark Text as URL's and be clickable. 

**Actual behavior:**

Only the 2nd link is clickable. 

### Versions

- Mark Text: 0.16.1
- Operating system: W10

**Comment by YaFou** [comment]
I have no problem to click with any links. The tree links work on my computer. Maybe your tab is opening in background and you need to check on your browser manually.

**Comment by eagleofnorth** [comment]
Thats strange, @YaFou 

This is how it looks at my end:

[https://www.screenpresso.com/=q1ebe](https://www.screenpresso.com/=q1ebe)

**Comment by YaFou** [comment]
Yes, you've right right @eagleofnorth. I used `[Google](https://google.com)` instead of `https://google.com`. This is strange, I think it's just a problem in the matcher to create links.

**Comment by eagleofnorth** [comment]
Thanks @YaFou. Not a big problem and I probably should use proper Markdown syntax for links anyway.

**Comment by YaFou** [comment]
Yes, @eagleofnorth. You can avoid the problem by writing this: `[https://google.com](https://google.com/)`.

**Comment by sweetliquid** [comment]
I am willing to solve this issue.
