### ISSUE TITLE
Unindenting does not work

### ISSUE THREAD

**Issue by raamana** [marktext/marktext#205]
### Description

When I press a tab in a bullet item, it gets indented one more level, which is great. I'd like the reverse too - Shift+Tab should deindent it one level, like in other text editor. This feature would be great if possible.

**Comment by Jocs** [comment]
@raamana thanks for open this issue, it's a cool feature!

**Comment by Jocs** [comment]
@fxha Do you have any ideas about this new feature?

**Comment by fxha** [comment]
Basically reserve tab indentation:

1. move selected item into parent list
2. append items behind selected item as a subitem

E.g.:

```
- a
  - b
  - c <shift + tab>
  - d
    - x
- e
- f
```

will become:

```
- a
  - b
- c
  - d
    - x
- e
- f
```

**Comment by Jocs** [comment]
@raamana already add this feature in master, and will release in the next version, So I'll close this issue, thanks for your reporting this issue.

**Comment by stefan2904** [comment]
is this supposed to work? When i type shift + tab, it is indenting instead of unindenting ...

(I run the latest marktext on the latest ubuntu.)

**Comment by v-marinkov** [comment]
> is this supposed to work? When i type shift + tab, it is indenting instead of unindenting ...
> 
> (I run the latest marktext on the latest ubuntu.)

I experience exactly the same thing. Appimage on PopOS (Ubuntu).
@Jocs what could be going wrong here? Thanks

**Comment by v-marinkov** [comment]
@stefan2904 @Jocs Has this really been fixed? Has it been released? It is still not working on my end and renders Mark Text unusable for anything but paragraphs and headings

**Comment by micdah** [comment]
This still seems to be an issue in latest version, might be a regression?

**Comment by Jocs** [comment]
@micdah I test this issue on the develop branch, and it works well, but it doesn't work in the v0.16.3. we'll release the next version this month.
