### ISSUE TITLE
How do you update a portable Windows installation?

### ISSUE THREAD

**Issue by pitastrudl** [marktext/marktext#2053]
### Question description

Hello, 

If you download the windows zip, which you can just start the application. How do you upgrade the application? I am speculating just a replacement of the newer files would cause loss of data. Thank you

**Comment by fxha** [comment]
@pitastrudl You simply need to backup your [portable user data directory](https://github.com/marktext/marktext/blob/develop/docs/PORTABLE.md) if exists and replace Mark Text with the latest version. By default we save all user data in the users local folder.
