### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by danielsouzat** [marktext/marktext#2054]
### Description
Search is not working.

### Steps to reproduce
Try to search anything.

#### App error message
>spawn /usr/lib/marktext/resources/app.asar.unpacked/node_modules/vscode-ripgrep/bin/rg

#### stdout
<pre><font color="#AA0000">09:55:38.706</font> › {
  constructor: <font color="#00AA00">&apos;Error&apos;</font>,
  errno: <font color="#00AA00">&apos;ENOENT&apos;</font>,
  code: <font color="#00AA00">&apos;ENOENT&apos;</font>,
  syscall: <font color="#00AA00">&apos;spawn /usr/lib/marktext/resources/app.asar.unpacked/node_modules/vscode-ripgrep/bin/rg&apos;</font>,
  path: <font color="#00AA00">&apos;/usr/lib/marktext/resources/app.asar.unpacked/node_modules/vscode-ripgrep/bin/rg&apos;</font>,
  spawnargs: [
    <font color="#00AA00">&apos;--json&apos;</font>,       <font color="#00AA00">&apos;--fixed-strings&apos;</font>,    <font color="#00AA00">&apos;--ignore-case&apos;</font>,
    <font color="#00AA00">&apos;--follow&apos;</font>,     <font color="#00AA00">&apos;--iglob&apos;</font>,            <font color="#00AA00">&apos;**/*.markdown&apos;</font>,
    <font color="#00AA00">&apos;--iglob&apos;</font>,      <font color="#00AA00">&apos;**/*.markdown/**&apos;</font>,   <font color="#00AA00">&apos;--iglob&apos;</font>,
    <font color="#00AA00">&apos;**/*.mdown&apos;</font>,   <font color="#00AA00">&apos;--iglob&apos;</font>,            <font color="#00AA00">&apos;**/*.mdown/**&apos;</font>,
    <font color="#00AA00">&apos;--iglob&apos;</font>,      <font color="#00AA00">&apos;**/*.mkdn&apos;</font>,          <font color="#00AA00">&apos;--iglob&apos;</font>,
    <font color="#00AA00">&apos;**/*.mkdn/**&apos;</font>, <font color="#00AA00">&apos;--iglob&apos;</font>,            <font color="#00AA00">&apos;**/*.md&apos;</font>,
    <font color="#00AA00">&apos;--iglob&apos;</font>,      <font color="#00AA00">&apos;**/*.md/**&apos;</font>,         <font color="#00AA00">&apos;--iglob&apos;</font>,
    <font color="#00AA00">&apos;**/*.mkd&apos;</font>,     <font color="#00AA00">&apos;--iglob&apos;</font>,            <font color="#00AA00">&apos;**/*.mkd/**&apos;</font>,
    <font color="#00AA00">&apos;--iglob&apos;</font>,      <font color="#00AA00">&apos;**/*.mdwn&apos;</font>,          <font color="#00AA00">&apos;--iglob&apos;</font>,
    <font color="#00AA00">&apos;**/*.mdwn/**&apos;</font>, <font color="#00AA00">&apos;--iglob&apos;</font>,            <font color="#00AA00">&apos;**/*.mdtxt&apos;</font>,
    <font color="#00AA00">&apos;--iglob&apos;</font>,      <font color="#00AA00">&apos;**/*.mdtxt/**&apos;</font>,      <font color="#00AA00">&apos;--iglob&apos;</font>,
    <font color="#00AA00">&apos;**/*.mdtext&apos;</font>,  <font color="#00AA00">&apos;--iglob&apos;</font>,            <font color="#00AA00">&apos;**/*.mdtext/**&apos;</font>,
    <font color="#00AA00">&apos;--iglob&apos;</font>,      <font color="#00AA00">&apos;**/*.text&apos;</font>,          <font color="#00AA00">&apos;--iglob&apos;</font>,
    <font color="#00AA00">&apos;**/*.text/**&apos;</font>, <font color="#00AA00">&apos;--iglob&apos;</font>,            <font color="#00AA00">&apos;**/*.txt&apos;</font>,
    <font color="#00AA00">&apos;--iglob&apos;</font>,      <font color="#00AA00">&apos;**/*.txt/**&apos;</font>,        <font color="#00AA00">&apos;--&apos;</font>,
    <font color="#00AA00">&apos;preguiça&apos;</font>,     <font color="#00AA00">&apos;/home/daniel/Notas&apos;</font>
  ],
  stack: <font color="#00AA00">&apos;Error: spawn /usr/lib/marktext/resources/app.asar.unpacked/node_modules/vscode-ripgrep/bin/rg ENOENT\n&apos;</font> +
    <font color="#00AA00">&apos;    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n&apos;</font> +
    <font color="#00AA00">&apos;    at onErrorNT (internal/child_process.js:456:16)\n&apos;</font> +
    <font color="#00AA00">&apos;    at processTicksAndRejections (internal/process/task_queues.js:80:21)&apos;</font>
}
</pre>

### System
Mark Text: v0.16.1 (3a6182b)
Node.js: 12.13.0
Electron: 8.2.3
Chromium: 80.0.3987.163
OS: Linux x64 5.4.33-3-MANJARO

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. I think this is the same issue as in #2055. Please follow the steps there and provide feedback.

**Comment by alerque** [comment]
I can replicate this too. Again please assign to me since it seems to be an Arch packaging issue. Alternatively if you don't want packaging issues in this repo at all I'll give you access to migrate them to [my AUR packages repo](https://github.com/alerque/aur) where they could be migrated.

**Comment by alerque** [comment]
I don't think this is the same issue as #2055. If I run the original bundled electron build unmodified from the upstream build system the issue with the current directory and saved workspace goes away, but this search issue is still present.

**Comment by fxha** [comment]
> If I run the original bundled electron build unmodified from the upstream build system the issue with the current directory and saved workspace goes away, but this search issue is still present.

I don't really understand what you mean by that but `vscode-ripgrep` has a hard-coded path that points to the executable `rg` inside the `app.asar.unpacked` directory like `/home/felix/.bin/marktext_dev/resources/app.asar.unpacked/node_modules/vscode-ripgrep/bin/rg`.

**Comment by alerque** [comment]
This issue is fixed in the `0.16.1-4` package version in the AUR.

**Comment by alerque** [comment]
Hunspell is a different issue, and not expected it work in the Arch package at this time. Let's track that elsewhere: https://github.com/alerque/aur/issues/2
