### ISSUE TITLE
Error while loading config - Cannot find module '@babel/compat-data/corejs3-shipped-proposals'

### ISSUE THREAD

**Issue by danielsouzat** [marktext/marktext#2056]
### Description
Module build fail during build with Node 13 but not with Node 12.

### Steps to reproduce
Try to build with NodeJS 13

>yarn install
>yarn run build (or dev)

### Behaviour
<pre><font color="#0000AA">  \ building main process</font>
<font color="#0000AA">  \ building renderer process</font>

  <span style="background-color:#AA0000"><font color="#AAAAAA"> ERROR </font></span> failed to build main process

    Hash: <b>526804d914d08ec24e68</b>
    Version: webpack <b>4.42.0</b>
    Time: <b>1784</b>ms
    Built at: 21/04/2020 <b>12:18:29</b>
          <b>Asset</b>      <b>Size</b>  <b>Chunks</b>         <b>Chunk Names</b>
        <font color="#00AA00"><b>main.js</b></font>  3.69 KiB       <b>0</b>         main
    <font color="#00AA00"><b>main.js.map</b></font>   1.6 KiB       <b>0</b>  <font color="#00AA00"><b>[dev]</b></font>  main
    Entrypoint <b>main</b> = <font color="#00AA00"><b>main.js</b></font> <font color="#00AA00"><b>main.js.map</b></font>
    [0] <b>./src/main/index.js</b> 2.73 KiB {<font color="#AA5500"><b>0</b></font>}<font color="#00AA00"><b> [built]</b></font><font color="#AA0000"><b> [failed] [1 error]</b></font>
    
    <font color="#AA0000"><b>ERROR in ./src/main/index.js</b></font>
<font color="#AA0000"><b>    Module build failed (from ./node_modules/babel-loader/lib/index.js):</b></font>
<font color="#AA0000"><b>    Error: /home/daniel/AUR/marktext/marktext-0.16.1/babel.config.js: Error while loading config - Cannot find module &apos;@babel/compat-data/corejs3-shipped-proposals&apos;</b></font>
<font color="#AA0000"><b>    Require stack:</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/preset-env/lib/index.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/babel.config.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/core/lib/config/files/module-types.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/core/lib/config/files/configuration.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/core/lib/config/files/index.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/core/lib/index.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/babel-loader/lib/index.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/loader-runner/lib/loadLoader.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/loader-runner/lib/LoaderRunner.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/webpack/lib/NormalModule.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/webpack/lib/NormalModuleFactory.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/webpack/lib/Compiler.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/node_modules/webpack/lib/webpack.js</b></font>
<font color="#AA0000"><b>    - /home/daniel/AUR/marktext/marktext-0.16.1/.electron-vue/build.js</b></font>
<font color="#AA0000"><b>        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)</b></font>
<font color="#AA0000"><b>        at Function.Module._load (internal/modules/cjs/loader.js:835:27)</b></font>
<font color="#AA0000"><b>        at Module.require (internal/modules/cjs/loader.js:1012:19)</b></font>
<font color="#AA0000"><b>        at require (internal/modules/cjs/helpers.js:72:18)</b></font>
<font color="#AA0000"><b>        at Object.&lt;anonymous&gt; (/home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)</b></font>
<font color="#AA0000"><b>        at Module._compile (internal/modules/cjs/loader.js:1123:30)</b></font>
<font color="#AA0000"><b>        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)</b></font>
<font color="#AA0000"><b>        at Module.load (internal/modules/cjs/loader.js:972:32)</b></font>
<font color="#AA0000"><b>        at Function.Module._load (internal/modules/cjs/loader.js:872:14)</b></font>
<font color="#AA0000"><b>        at Module.require (internal/modules/cjs/loader.js:1012:19)</b></font>
<font color="#AA0000"><b>        at require (internal/modules/cjs/helpers.js:72:18)</b></font>
<font color="#AA0000"><b>        at Object.&lt;anonymous&gt; (/home/daniel/AUR/marktext/marktext-0.16.1/node_modules/@babel/preset-env/lib/index.js:29:44)</b></font>
<font color="#AA0000"><b>        at Module._compile (internal/modules/cjs/loader.js:1123:30)</b></font>
<font color="#AA0000"><b>        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)</b></font>
<font color="#AA0000"><b>        at Module.load (internal/modules/cjs/loader.js:972:32)</b></font>
<font color="#AA0000"><b>        at Function.Module._load (internal/modules/cjs/loader.js:872:14)</b></font>

### Versions
Mark Text: v0.16.1 (3a6182b)
Node.js: 13.13.0
Electron: 8.2.3
Chromium: 80.0.3987.163
OS: Linux x64 5.4.33-3-MANJARO
babel-loader: 8.0.6 and 8.1.0 too

**Comment by fxha** [comment]
Please use node v12 for now as it's an upstream error.
