### ISSUE TITLE
Emojis are rendered differently in some themes

### ISSUE THREAD

**Issue by kulbhushanchand** [marktext/marktext#2058]
### Description
The issue is with rendering of emojis in different themes. There are two ways to insert emojis - 
1. Using markup, eg -  `:hammer:`
2. Directly pasting the unicode emoji, eg - `🔨`
**_ Issue - The unicode pasted emojis (2nd type) are rendered a bit faded in some of the themes -_** 

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Insert a emoji by two different ways as stated above

**Expected behavior:**

Both emojis should render as same

**Actual behavior:**

The emoji inserted by copy pasting the unicode is rendered as a bit faded than other one

**Link to an example: [optional]**

**-  In the following themes the 2nd type emojis are faded -** 

**- Theme - Cadmium Light**
![image](https://user-images.githubusercontent.com/17742733/79974965-ce1b5200-84b7-11ea-835e-35a40ce31cd8.png)

**- Theme - Dark**
![image](https://user-images.githubusercontent.com/17742733/79975035-f30fc500-84b7-11ea-8e2f-9b410dcc59f7.png)

**- Theme - Graphite Light**
![image](https://user-images.githubusercontent.com/17742733/79975127-19cdfb80-84b8-11ea-8059-c0e41176c12a.png)

**_ However in the following themes, both type emojis are rendered same -_**

**- Theme - Material Dark**
![image](https://user-images.githubusercontent.com/17742733/79975242-4a159a00-84b8-11ea-8289-b9d38222f079.png)

**- Theme - One Dark**
![image](https://user-images.githubusercontent.com/17742733/79975276-5b5ea680-84b8-11ea-93a7-66e10e15b629.png)

**- Theme - Ulysses Light**
![image](https://user-images.githubusercontent.com/17742733/79975363-7af5cf00-84b8-11ea-9bf7-3a5ab8f909b6.png)

### Versions

- Mark Text: v0.16.1
- Operating system: WIn10 64bit

**Comment by kulbhushanchand** [comment]
Closed the issue by mistake. Reopening it again

**Comment by fxha** [comment]
Thank you for reporting the issue. We use different fonts across OSs but this seems to be an issue with the used font or the rendering in Chromium.
