### ISSUE TITLE
Redo not working

### ISSUE THREAD

**Issue by AlJohri** [marktext/marktext#2059]
### Description

I can't undo and then redo after pasting a link.

- [ ] Can you reproduce the issue? Yes

### Steps to reproduce

Paste a link via Ctrl-V
Undo pasting via Ctrl-Z.
Redo paste via Ctrl-Shift-Z. <- redo does not work

**Expected behavior:**

It should re-paste the link.

**Actual behavior:**

It does nothing.

### Versions

- Mark Text: Latest
- Operating system: Windows

**Comment by fxha** [comment]
Thanks for creating this issue. Undo/redo have known problems but are currently overworked.
