### ISSUE TITLE
Change lineHeight may cause format error

### ISSUE THREAD

**Issue by umi-neko** [marktext/marktext#206]
### Description
When set lineHeight to 0.5 in User Preferences, display format get error.

[Description of the bug or feature]
Set lineHeight to 0.5 and restart the app, it will look like this:
![1524468401247](https://user-images.githubusercontent.com/6946691/39112332-c1d6a40a-470a-11e8-924a-5b6ff175e356.jpg)

### Versions

- Mark Text: v0.10.21 (compile from github source)
- OS: macOS

**Comment by fxha** [comment]
> The line-height property specifies the height of a line.

This means it's up to you to choose a valid line height.

**Comment by umi-neko** [comment]
unordered list and ordered list format format ok, but task list align not correct.
![1524482980832](https://user-images.githubusercontent.com/6946691/39124091-b31b04fc-472c-11e8-915c-294d0be8bd60.jpg)
do you known what I said?...

**Comment by Jocs** [comment]
@umi-neko no one will set `line-height` to 0.5 if he know what line-height mean.

>lineHeight = `single text height` / fontSize

If line height less than 1, there is not enough space for render the text.

Since the `user preferences` file is completely free, the user should be very clear about the purpose of his own settings, otherwise he should use the settings in the menu `view => font`.

Hope this will help you!

**Comment by fxha** [comment]
@Jocs I think @umi-neko means that the we should ignore `line-height` property for task-lists too because it's looks strange, so  `line-height` only affects text and not lists.

**Comment by Jocs** [comment]
@fxha I found there is something wrong with the style of task list checkbox, after you mentioned

>I think @umi-neko means that the we should ignore line-height property for task-lists too because it's looks strange, so line-height only affects text and not lists.

I'll fix it in the next commit.
