### ISSUE TITLE
Should not modify a file when opening it

### ISSUE THREAD

**Issue by xaxousis** [marktext/marktext#2062]
### Description

Opening a file in normal mode will change the format of its content. If the editor is in source code mode, this won't happen.

Related to #2035 #2036.

- [x] Can you reproduce the issue? 

### Steps to reproduce

test file:
```
| Head1 | Head2  |
| --------- | ---------------|
| Content1 | Content2 |
```

1. Open test file.
2. Change to source code mode. The file looks like this.
  ```
  | Head1    | Head2    |
  | -------- | -------- |
  | Content1 | Content2 |
  ``` 
3. Close file without saving
4. Reopen file. The file look like the original file.

**Expected behavior:**

The file lines should not be reformatted if they haven't been modified. This prevents correct tracking of changes to a file with Git for example.

**Actual behavior:**

See step to reproduce.

### Versions

- Mark Text: 0.16.1
- Operating system: Linux Mint (19.3)

**Comment by fxha** [comment]
I'm closing this issue in favour of #2189. You may want to subscribe there for further updates.
