### ISSUE TITLE
"Open the last window state" option disabled

### ISSUE THREAD

**Issue by alerque** [marktext/marktext#2064]
This is a follow up to issue #2055. For some reason in my builds (using system Electron & launching through a wrapper script) the option to launch to the last window state is disabled:

![image](https://user-images.githubusercontent.com/173595/80149493-6f410000-85bf-11ea-96a0-861f2599441f.png)

What could cause this?

**Comment by fxha** [comment]
It's currently not implemented but the default option as we planned implementing it soon (#988). Since we are both very busy right now, there is no process and don't expect "big" features or changes 2020.

**Comment by alerque** [comment]
Up, okay. I confess I was greatly puzzled by an option being selected by default but disabled at the same time, and after changing it not being able to get the option back. I guess if it's not implemented I won't worry about it being a bug in packaging!
