### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by Altiano** [marktext/marktext#2074]
### Question description

Is there a way to customized markdown elements styling?
I wish to change the font-weight of `h1` etc to 600

**Comment by LivelyCarpet87** [comment]
You can create your own styles for exporting and make edits to existing setups by altering their respective CSS files. The directory for export themes is ~/Library/Application Support/marktext/themes/exports.

**Comment by hialemat** [comment]
Hi, I can't figure out at all out to find out the directory %APPDATA%\marktext on Windows.
Where can I find this Application Data directory?
I'd like to create my own style for exporting. 
Thanks.

**Comment by fxha** [comment]
We currently doesn't support applications themes. Please see

- [Themes](https://github.com/marktext/marktext/blob/develop/docs/THEMES.md) and
- [Themes (Export)](https://github.com/marktext/marktext/blob/develop/docs/EXPORT_THEMES.md).

**Comment by moshpirit** [comment]
Marktext v. 0.17.1 is out, on [Themes](https://github.com/marktext/marktext/blob/develop/docs/THEMES.md) it's said that user-defined application themes was planned for v. 0.17.0. Is is supported now or is still just a requested feature? I really like Marktext and I think this is a great feature.
