### ISSUE TITLE
Creating a new file using the sidebar does not automatically open it on Windows

### ISSUE THREAD

**Issue by manastalukdar** [marktext/marktext#2079]
### Description

Creating a new file using the sidebar does not automatically open it on Windows

yes: `[x]` 

### Steps to reproduce

Under a folder, create a new markdown file using the sidebar.

**Expected behavior:**

The file automatically also opens up.

**Actual behavior:**

File does not open and user has to click on it to open.

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10 x64

### Note

On MacOS, the newly created file is automatically opened.

**Comment by Jocs** [comment]
I can not reproduce this issue, it maybe already fixed? and close it, please feel free to reopen it, if it already existed.
