### ISSUE TITLE
does this support document grouping ?

### ISSUE THREAD

**Issue by Janloong-Doo** [marktext/marktext#208]

**Comment by fxha** [comment]
What did you mean with document grouping? Could you give me more details.

**Comment by Janloong-Doo** [comment]
I'm sorry that I didn't see the todolist file before. I want to express the functions like file grouping, or similar tags, so I can quickly switch different files.I think the most important thing right now is the table, the picture, these basic document functions.   
Plus, it's a great app.I'm looking forward to the 1.0 release.  Thanks for the author behind the scense.
