### ISSUE TITLE
clarify or simplify multitab use

### ISSUE THREAD

**Issue by brainchild0** [marktext/marktext#2080]
Currently, the application supports multiple open windows, and multiple tabs in each window. 

If a user wishes to open a new file, the general possibilities include creation of a new window, or of a new tab in the existing window. Which possibility occurs in a particular case depends not on explicit direction by the user, but on the manner in which the the  file is selected. 

If the file is selected through the menu, a new window is created, whereas if it is selected by side bar, a new tab is created. It is unclear whether this behavior is generally desired. Perhaps the intention is that each window corresponds to some directory tree, represented by a sidebar, from which files might be opened in new tabs. Yet, from this particular distinction might follow the conclusion that opening a new file, as opposed to a new directory, from the file menu corresponds to a preference for creating a new tab, compared to the current behavior for this case, of creating a new window.

In fact, while some users may prefer use of multiple tabs, some may wish for only one open file per window.  A mode of operation that excludes tabs might produce a behavior of creating a new window for files opened from the menu, yet *replacing the current editor buffer* for files opened from the sidebar.

While it may be unclear precisely which design ultimately might  prove optimal, the topic appears appropriate for discussion.

**Comment by fxha** [comment]
> If the file is selected through the menu, a new window is created,

You can control this via settings.

> whereas if it is selected by side bar, a new tab is created. 

Files inside the current "workspace" are opened in the same editor as expected.

---

In the future the file is opened according the current editor (window) workspace/session but can be overwritten by settings (e.g. open all new files in a new window).
