### ISSUE TITLE
Bug in text highlight

### ISSUE THREAD

**Issue by specter78** [marktext/marktext#2084]
### Description
When highlighting text in multiple lines, only some portion is highlighted even though `mark` tag is applied correctly.

- [x ] Can you reproduce the issue?

### Steps to reproduce

1. Select multiple lines
2. Attempt to highlight text

**Expected behavior:**

Highlighted text should match `mark` tag text.

**Actual behavior:**
![ezgif-5-7a382a76c65f](https://user-images.githubusercontent.com/40606342/80709109-647bf300-8b0a-11ea-9175-8a0a96a42be1.gif)

### Versions

- Mark Text: 0.16.1
- Operating system: macOS 10.15.4

**Comment by specter78** [comment]
Also the app does not allow highlighting text across multiple paragraphs.

**Comment by dnswd** [comment]
It's been a year and nobody has fixed the issue yet? I'll try to dig into this.

**Comment by Jocs** [comment]
highlighting text is only allowed in one paragraph. it's a online format.
