### ISSUE TITLE
Download new dictionary for Hunspell: t.data.pipe is not a function

### ISSUE THREAD

**Issue by 80jan** [marktext/marktext#2088]
### Description

Attempt to add Polish language ends in error: Error while downloading: t.data.pipe is not a function

### Steps to reproduce

1. Preferences 
2. Spelling
3. Download new dictionaries for Hunspell: Polish

**Expected behavior:**

Add **Polish** dictionaries

**Actual behavior:**

> Error while downloading: t.data.pipe is not a function 

### Versions

- Mark Text: v0.16.1
- Operating system: Windows 10 Pro

**Comment by Nullmaruzero** [comment]
Same here. Applies to every language.

Mark Text 0.16.1
Win 10 Home
