### ISSUE TITLE
Multifile and project support

### ISSUE THREAD

**Issue by redoxmatlab** [marktext/marktext#2102]
Hello, 

At the moment Mark Text does not seem to support exporting all files in a folder. I wonder if I am missing something here?

I have been able to create a bash file to export multiple MD files based on this project (https://github.com/wikiti/pandoc-book-template) and I do not see why not such simple operation could not be implemented within Mark Text?

By the way, the https://github.com/Zettlr/Zettlr shines in this particular area with an excellent project management support... maybe Mark Text will find Zettlr a useful project to learn from.

Thank you

**Comment by fxha** [comment]
Thanks for creating this issue. Session are planned in #988 and we currently doesn't support multi export of files (there are an issue about this and we add this on demand).
