### ISSUE TITLE
Support for mhchem both inline and at export

### ISSUE THREAD

**Issue by redoxmatlab** [marktext/marktext#2104]
Hello,

I wish to request support for mhchem package (https://mhchem.github.io/MathJax-mhchem/).

This package is critical for technical writers. I have tried to add the equation below but it could not be exported correctly into PDF since mhchem is not supported.
$\ce{CH4 + 2 $\left( \ce{O2 + 79/21 N2} \right)$}$

The same applies to LaTeX expressions such as (this one below is from Typora website):

$$
\begin{align*}
y = y(x,t) &= A e^{i\theta} \\
&= A (\cos \theta + i \sin \theta) \\
&= A (\cos(kx - \omega t) + i \sin(kx - \omega t)) \\
&= A\cos(kx - \omega t) + i A\sin(kx - \omega t)  \\
&= A\cos \Big(\frac{2\pi}{\lambda}x - \frac{2\pi v}{\lambda} t \Big) + i A\sin \Big(\frac{2\pi}{\lambda}x - \frac{2\pi v}{\lambda} t \Big)  \\
&= A\cos \frac{2\pi}{\lambda} (x - v t) + i A\sin \frac{2\pi}{\lambda} (x - v t)
\end{align*}
$$

Any ideas?

Many thanks.

**Comment by redoxmatlab** [comment]
Solving this myself. See below for whoever interested.

\begin{aligned}
y = y(x,t) &= A e^{i\theta} \\
&= A (\cos \theta + i \sin \theta) \\
&= A (\cos(kx - \omega t) + i \sin(kx - \omega t)) \\
&= A\cos(kx - \omega t) + i A\sin(kx - \omega t) \\
&= A\cos \Big(\frac{2\pi}{\lambda}x - \frac{2\pi v}{\lambda} t \Big) + i A\sin \Big(\frac{2\pi}{\lambda}x - \frac{2\pi v}{\lambda} t \Big) \\
&= A\cos \frac{2\pi}{\lambda} (x - v t) + i A\sin \frac{2\pi}{\lambda} (x - v t) \\
\end{aligned}

**Comment by 0187773933** [comment]
https://github.com/marktext/marktext/blob/develop/src/muya/lib/utils/exportHtml.js#L3

```
import katex from 'katex'
import 'katex/dist/contrib/mhchem'
import loadRenderer from '../renderers'
```
