### ISSUE TITLE
Image settings : clarify "local folder" & "Insert absolute or relative path of image"

### ISSUE THREAD

**Issue by yhancik** [marktext/marktext#2105]
### Description

First of all, thanks for all your work so far on Mark Text!

I find the wording of the Image settings is a bit confusing, especially for newcomers (currently trying to convert my students to Markdown!)
 
"Local folder" is used twice with apparently two different meanings : 
- "The default behavior after insert image from _local_ _folder_"
- "The _local_ image _folder_"

With another term introduced in "Move image to _special folder_".

If I understand well what you mean, would this be more clear?
- "The default behavior after insert image from your computer"
- "Move image to assets folder"
- "The assets folder"

__

Next to that, and maybe related to #549 : the "Insert absolute or relative path of image" option.  I'll describe the issue below.

- [x] Can you reproduce the issue? 

### Steps to reproduce
I want to be able to use relative paths for the images I insert in my Markdown files.

1. I select "Insert absolute or relative path of image", as it's the only option mentioning relative paths
2. Through the insert image dialogue, I click "Select" and "Choose an image", and pick a picture from my computer that is also in the same folder as the current Markdown file.
3. (unrelated issue, but the dialogue doesn't close after inserting the image)
4. The image is inserted with an absolute path

**Expected behavior:**

I have the possibility to insert the image with a relative path.

**Actual behavior:**

The image is inserted with an absolute path. 

If I understand well, "Select" will only insert images with an absolute path but that's being worked on (?)
The "or" in "absolute or relative path" might give the impression that we currently can choose between absolute or relative, but if I understand well, it's more "depending on whether the insert mode will allow it or not".
I think this should be more clearly explained in the interface so users don't feel confused and frustrated with unexpected behaviours :) 

### Versions

- Mark Text: v0.16.1
- Operating system: Windows 10

**Comment by theoryshaw** [comment]
i like the idea of inserting images based on relative path, as well.

**Comment by xgdgsc** [comment]
I also need inserting to relative path

**Comment by northword** [comment]
I also need inserting to relative path, in order to easily insert the picture in a relative path, I have to continue to use typora, but it uses mathjax instead of katex.

**Comment by ZhaoZuohong** [comment]
Same issue.

**Comment by carmolim** [comment]
+1

**Comment by YalandHong** [comment]
Related to #2560
