### ISSUE TITLE
Always use forward slashes on Windows

### ISSUE THREAD

**Issue by yhancik** [marktext/marktext#2106]
### Describe your feature request

On Windows, when files are added through "Select" + "Choose an image", drag&drop or copy-paste, Mark Text uses backslashes as a path delimiter, the default on Windows . These paths don't work on other systems, on Github, and seem to break the export (see #1367 & #2085).

Since Mark Text seems to be able to display images with forward slashes in their path, even on Windows, why not enforce forward slashes for all image paths on Windows?

(an HTML editor wouldn't use backslashes for its paths, would it?)

### What problem does this feature solve?

- Better compatibility and portability of Markdown files created on the Windows version of Mark Text
- Might solves the export bug where images don't show when their paths use backslashes?

**Comment by kiyoka** [comment]
I agree with that opinion.
On Windows, additional code is required In various places. 
But, It is worth the effort.
