### ISSUE TITLE
How do I create/edit themes?

### ISSUE THREAD

**Issue by aayushdutt** [marktext/marktext#2108]
### Question description

I want to create a new theme for marktext, how do I do it?

**Comment by fxha** [comment]
We currently doesn't support applications themes. Please see

- [Themes](https://github.com/marktext/marktext/blob/develop/docs/THEMES.md) and
- [Themes (Export)](https://github.com/marktext/marktext/blob/develop/docs/EXPORT_THEMES.md).

**Comment by nickbe** [comment]
How far are we away from custom themes then?

**Comment by fxha** [comment]
Unfortunately, Mark Text is currently not maintained and therefore there is no planned date and upcomming changes.

**Comment by nickbe** [comment]
Oh. Sorry to hear that.  Are pull requests merged by someone at all then?
