### ISSUE TITLE
Support or at least let open .mdx?

### ISSUE THREAD

**Issue by kud** [marktext/marktext#2109]
### Describe your feature request

It could be great to support https://mdxjs.com/

**Comment by jd-carroll** [comment]
It would be amazing if marktext supported `.mdx` files!!!!

But I think this gets at a larger capability, which would be some type of plugin model.  First the Markdown flavor would have to be pluggable (some type of BYOF "bring your own flavor"), then it would be possible to inject an mdx renderer.
