### ISSUE TITLE
Undo not working on Souce Code Mode

### ISSUE THREAD

**Issue by msmafra** [marktext/marktext#2112]
### Description

Can not undo any typo, any typying, when in Source Code Mode.

- [x] Can you reproduce the issue?

### Steps to reproduce
1. Open any dot md file;
2. Change something;
3. Try to undo it with both Ctrl+Z or using Edit -> Undo;

**Expected behavior:**
To undo any changes to the text/code.

**Actual behavior:**
Nothing happens.
**Link to an example: [optional]**
https://youtu.be/P36GKfPN7Js

### Versions

- Mark Text: v0.16.1
- Operating system: Linux Fedora Workstations 32

**Comment by fxha** [comment]
Duplicate of #1639.
