### ISSUE TITLE
 electron-rebuild -f Rebuild Failed

### ISSUE THREAD

**Issue by smart817** [marktext/marktext#2113]
### Question description

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.2 | win32 | x64
gyp info find Python using Python version 3.7.6 found at "D:\program\Anaconda3\python.exe"
gyp http GET https://www.electronjs.org/headers/v8.2.5/node-v8.2.5-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo ENOENT gh-contractor-zcbenz.s3.amazonaws.com
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\smart\\Desktop\\marktext\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=8.2.5" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\smart\Desktop\marktext\node_modules\@hfelix\spellchecker
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

**Comment by fxha** [comment]
Thanks for reporting the issue. Please try again, as it seems to be an issue with your internet connection:

```
ERR! stack Error: getaddrinfo ENOENT gh-contractor-zcbenz.s3.amazonaws.com
```
