### ISSUE TITLE
realtime preview backslash disappearing on Windows 10

### ISSUE THREAD

**Issue by solomonfentonmiller** [marktext/marktext#2124]
### Description

Every other backslash that is typed in real-time preview mode does not show on screen. Instead, a small blank space appears. The character is still there and can be viewed in source code mode.

- [X] Can you reproduce the issue?

### Steps to reproduce

1. Type two or more backslashes
2. Every other backslash is invisible on screen (shows as a blank space)

**Link to an example: https://imgur.com/0Vrh7VX**
In the example, see that I switch between the real preview and the source code mode and the number of backslashes don't match.

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10 64-bit

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. The described behaviour is how it is expected to work because "Any ASCII punctuation character may be escaped using a single backslash."

Example: `\*this is not italic\*` becomes \*this is not italic\*

**Comment by solomonfentonmiller** [comment]
Thanks for the explanation - the behavior makes sense to me now.
