### ISSUE TITLE
Ctrl+Alt+S does not work in debian

### ISSUE THREAD

**Issue by sgon00** [marktext/marktext#2149]
OS: debian 10
Desktop Env: xfce
marktext versin: v0.16.1 (016c7b4c)
Installation method: build manually

`Ctrl+Alt+S` does not work to switch to source code mode. I even assign this key again in `keybindings.json`, but no luck. 

Right now, I have modified it to `Super+S` and works. 

I am not sure why. I don't see Ctrl+Alt+S assigned by any apps. 

Thanks a lot.

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2370. You may want to subscribe there for further updates.
