### ISSUE TITLE
Question: Which shortcut can jump out of source code edit mode

### ISSUE THREAD

**Issue by codeskyblue** [marktext/marktext#215]
### Description
![image](https://user-images.githubusercontent.com/3281689/39340726-4c5b03a6-4a02-11e8-9ae1-2b9481fe3d82.png)

How to jump out of the source code edit and write normal text
### Versions

- Mark Text: v 0.10.21
- OS: mac air

**Comment by Jocs** [comment]
`Shift + Cmd + S`, but this shortcut is conflict with `Save as`, So you'd better switch `source code mode` in `view Menu => source code mode`.

**Comment by Jocs** [comment]
@codeskyblue Do you mean cursor in the code block? Use arrow up and down to go out of code block.
