### ISSUE TITLE
Provide an option to disable all features except wysiwyg rendering to improve performance

### ISSUE THREAD

**Issue by sgon00** [marktext/marktext#2150]
Hi, I am aware of https://github.com/marktext/marktext/issues/511. But that issue is talking about performance in big document. But I feel marktext is slow even with a few lines document. Maybe my laptop is not that powerful. It's simply a 4GB thinkpad with intel graphic card. A standard low-power laptop.

I tried nearly all markdown editors in two days. (Btw, I am running Linux, debian 10). Marktext is the coolest one, but a very slow one. Other markdown editors will take less CPU/RAM and faster when I type etc. even if some of them are also using electron.

I don't really need all marktext advanced features except wysiwyg rendering engine. I tried to disable all auto complete, auto trim features in preferences, but it doesn't help. I am not a nodejs developer so I am not sure what the cause is and any other features may affect the performance. For example, I have filed an issue about moving cursor. Moving cursor is the simplest action everyone will do, but that is slow when I hold UP/DOWN key. Ctrl-V or Ctrl-Shift-V to paste an URL is also very slow in my laptop (it took about 3 seconds to complete the paste, that is kinda too long when I used to typing things very fast). Every actions that I do, I feel slow. 

Can marktext provide an option to disbale all features and only keep the rendering part to improve the performance? 

Thank you very much for your help.

**Comment by femto-code** [comment]
I am facing the same experience, hardware characteristics may **not** be the cause.
Relating to #2300 (and #511) this could be a general issue. Performance seems to be laggy in nearly every ElectronJS application. Besides a part that is almost immutable _(due to Electron app concept with Chromium which uses a great amount of RAM)_ we could try to improve certain app procedures in order to speed it up.

**Comment by Jocs** [comment]
The preference poor is not due to the features, one reason is Electron, and another is the architecture of marktext editor, we are refactoring the editor `muya` already to improve preference of it.
