### ISSUE TITLE
Key binding does not work

### ISSUE THREAD

**Issue by learnyoung1990** [marktext/marktext#216]
已经将 `user perference` 下的`aido`设置为`true`了但是仍然不能用`ｃｔｒｌ+/`呼出界面

**Comment by xxxgitone** [comment]
@Jocs 遇到相同的问题，无法呼出界面，重启过。系统版本：deepin 15.5

**Comment by Jocs** [comment]
@xxxgitone 在 Edit 菜单中有 Aidou 选项吗？

**Comment by Jocs** [comment]
@xxxgitone 能够你的 user preference 文件截图贴到这个 issue 吗？

**Comment by xxxgitone** [comment]
@Jocs `Edit`菜单有`Aidou`,点击能够弹出斗图界面的。下面是`user preference`截图

![user preference](https://raw.githubusercontent.com/xxxgitone/learningProcess/master/issueImg/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20180428194849.png)

`Ctrl`配合其他键，比如`ctrl + n`、`ctrl + 2`啥的都是有用的，唯独配合`ctrl + /`不行。

我到时候再排查一下是不是电脑自身的问题。谢谢

**Comment by fxha** [comment]
@Jocs When you enable aidou, `Ctrl+/` (`Ctrl+Shift+7`) is not working on Linux (maybe on Windows too) - if this was the problem. It only select all text.

**Comment by Jocs** [comment]
@fxha I test this issue, and it works on my Mac. and I can use `Cmd + /` to open the 'Aidou' panel.

So I think the `Cmd + /` is conflict with other shortcuts on Linux system?

**Comment by fxha** [comment]
It seems to be a issue with punctuation and non US-keyboards. See [here](https://github.com/atom/atom-keymap/issues/37) for more info. `Ctrl+#` (not `Ctrl+Shift+#`) is equivalent to `Ctrl+/` on a german keyboard. So I have to use `Ctrl+#` instead of `Ctrl+/`. The menu accelerator seems to be bind to the symbol behind `Ctrl+/` and not to the shortcut `Ctrl+/`.

**Comment by fxha** [comment]
@Jocs Any updates here?

List of know broken shortcut on German keyboard - maybe all non-US keyboards.

| Shortcut | Working shortcut (Linux)   | Working shortcut (Windows) |
| -------- | -------------------------- | -------------------------- |
| `Ctrl+U`* | `Ctrl+Super+U`             |not working           |
| `Ctrl+=` | `Ctrl+Plus` (`+`)          | `Ctrl+Plus` (`+`)          |
| `Ctrl+/` | `Ctrl+#` (without `Shift`) | `Ctrl+#` (without `Shift`) |

*: I think `Ctrl+U` (`Ctrl+Shift+U`) is a problem with unicode characters.

**Comment by Jocs** [comment]
`Ctrl+# (without Shift)` is the shortcut of `heading 3` ? 

Now the problem is `Ctrl + U`、`Ctrl + =`、`Ctrl + /` are not working in Linux system? or German keyboard?

**Comment by fxha** [comment]
See my comment above: https://github.com/marktext/marktext/issues/216#issuecomment-385186913. Electron don't listen for `Ctrl+#` shortcut but instead of the key-id from `Ctrl+#`. Let's say `Ctr+#` has key-id `1` on a US-layout, but on a German-layout `2`. Key-id  `1` is `Ctrl++` or what ever on a Germany-keyboard. So you have to type `Ctrl++` (because it's key-id `1`) instead of `Ctr+#`. But at the save time the menu item is displayed as `Ctrl+#`... This is because the US and German keys are located at different (physical) places.

I think it's a cross-platfrom non-US-keyboard language problem with electron because many electron applications have/had this issue. If I change my keyboard language to US, every think work as expected.

**Comment by stefnotch** [comment]
@fxha According to the issue you linked, Atom already handles non-US keyboards properly. What's preventing Marktext from doing the same?

**Comment by fxha** [comment]
@stefnotch That's right. I didn't have a close look at it so far and I don't have time for this right now. Maybe we can just use some key maps. Otherwise I don't really know how to solve it.

**Comment by stefnotch** [comment]
@fxha Using `KeyboardEvent.code` should solve this issue. https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

So, to fix it on Windows (I'm not sure how Linux and Mac should behave), when the user presses CTRL (`KeyboardEvent.ctrlKey == true`), instead of looking at the `KeyboardEvent.key`, you have to look at `KeyboardEvent.code`.

**Comment by fxha** [comment]
We use electron menu items for shortcuts. You can find more details [here](https://electronjs.org/docs/api/menu-item) and [here](https://electronjs.org/docs/api/accelerator). So we define shortcuts only and electron will do the rest for us. I don't know if we can display shortcuts names only and manage it by ourself.

**Comment by fxha** [comment]
We finally found the problem to some shortcut problems: https://github.com/marktext/marktext/issues/328#issuecomment-396633900. This affects all menu shortcuts which are also defined in the code above - like `Ctrl+Z`, `Shift-Ctrl-Z` and `Ctrl+U`.

**Comment by Jocs** [comment]
@fxha But `Ctrl + Z` and `Ctrl + /` are work well with MacOs?

**Comment by fxha** [comment]
@learnyoung1990 @xxxgitone 

I'm happy to announce that we solved the keybinding issue. Could you please check whether everything is ok on your machine. Maybe we have to improve the solution, particularly relating non US-keyboards. Prebuilt binaries for Linux and Windows are available [here](https://github.com/marktext/marktext/releases/tag/KeybindingFixes). Please see PR #543 for more information.

Thanks!

**Comment by stefnotch** [comment]
@fxha I'm happy to report that they seem to work perfectly on my Windows 10 machine. I even tested them with a totally [non standard keyboard layout](https://github.com/stefnotch/portable-us-colemak) and everything worked as expected.

**Comment by phaazon** [comment]
Hello. I’m sorry to tell you it’s not fixed. On my keyboard (layout bépo), I cannot correctly bind the `altgr-space` (underscore with bépo). Any idea? :( (it doesn’t work on Linux but works on macOSX).

**Comment by fxha** [comment]
@phaazon Do you mean you have an issue with `atom` or I don't get you? If you have an issue related to atom or an atom extension please open an issue at [atom](https://github.com/atom/atom). This issue tracks keyboard issues about Mark Text markdown editor. Otherwise can you please give me more details?

BTW `AltGr+Space` is often a operating system shortcut for non-breaking space.

**Comment by phaazon** [comment]
Dammit, I thought I was on Atom. Sorry for the noise :laughing:

**Comment by sheldonhull** [comment]
I am trying to rebind `Ctrl+/` to show source code view, but it won't work. In reviewing source code, it looks like `showAiDou` method and functionality is being used, which I really don't need at this time. Is there anyway to unmap this? I tried

```
{
    "showAiDou": "",
    "viewSourceCodeMode": "CmdOrCtrl+/"
}
```

and this didn't work.

**Comment by fxha** [comment]
@sheldonhull Could you please open an issue and give more information about your OS and keyboard information like:

- Mark Text version (`marktext --version` or about dialog)
- OS and keyboard language
- `marktext --dump-keyboard-layout` and
- `setxkbmap -query` output on Linux (pasted in code block or similar)

I tested your example on Fedora with a Germany keyboard and everything works as expected but `showAiDou` should be `editAidou`. There are know issues with some shortcuts like `Ctrl+/` because e.g. this shortcut doesn't exists on a German keyboard but `Ctrl+7` (that produces `/`) and we need to build mnemonics.

**Comment by stefnotch** [comment]
It seems like this broke again in the latest Marktext update

To reproduce:
1. Switch to a non-US keyboard layout like the French AZERTY keyboard layout.
2. Shortcuts like `CTRL+A` and `CTRL+Q` don't work as expected, because the keyboard layout remapped them.

**Comment by fxha** [comment]
@stefnotch I didn't tested this on AZERTY keyboard but on a German (`Ctrl+Z`) works fine. Do you switched keyboard layout when Mark Text is not running? We have currently no runtime support to switch keyboard layouts.

**Comment by DutchPete** [comment]
@stefnotch : `CTRL+A` works fine on Linux Mint 19.2 XFCE and Typora 0.9.75 with a QWERTY GB-keyboard.

**Comment by stefnotch** [comment]
@fxha 
I switched to the French keyboard before starting Mark Text and was still able to reproduce this issue. I can also reproduce the issue with a German keyboard. Pressing `Ctrl+Z` on a German keyboard results in Mark Text *re-doing* the action instead of undoing it.

OS: Windows 10 
Version: Latest published Mark Text version

**Comment by stefnotch** [comment]
@fxha :
<details>
  <summary>Here is a dump of a French keyboard layout where I can reproduce the issue (spoiler) </summary>


```jsonc
 Layout: A0000409
Language: en-GB

{
  "KeyA": {
    "unmodified": "q",
    "withShift": "Q",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyB": {
    "unmodified": "b",
    "withShift": "B",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyC": {
    "unmodified": "c",
    "withShift": "C",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyD": {
    "unmodified": "d",
    "withShift": "D",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyE": {
    "unmodified": "e",
    "withShift": "E",
    "withAltGraph": "├⌐",
    "withAltGraphShift": "├ë"
  },
  "KeyF": {
    "unmodified": "f",
    "withShift": "F",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyG": {
    "unmodified": "g",
    "withShift": "G",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyH": {
    "unmodified": "h",
    "withShift": "H",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyI": {
    "unmodified": "i",
    "withShift": "I",
    "withAltGraph": "├¡",
    "withAltGraphShift": "├ì"
  },
  "KeyJ": {
    "unmodified": "j",
    "withShift": "J",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyK": {
    "unmodified": "k",
    "withShift": "K",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyL": {
    "unmodified": "l",
    "withShift": "L",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyM": {
    "unmodified": ",",
    "withShift": "<",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyN": {
    "unmodified": "n",
    "withShift": "N",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyO": {
    "unmodified": "o",
    "withShift": "O",
    "withAltGraph": "├│",
    "withAltGraphShift": "├ô"
  },
  "KeyP": {
    "unmodified": "p",
    "withShift": "P",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyQ": {
    "unmodified": "a",
    "withShift": "A",
    "withAltGraph": "├í",
    "withAltGraphShift": "├ü"
  },
  "KeyR": {
    "unmodified": "r",
    "withShift": "R",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyS": {
    "unmodified": "s",
    "withShift": "S",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyT": {
    "unmodified": "t",
    "withShift": "T",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyU": {
    "unmodified": "u",
    "withShift": "U",
    "withAltGraph": "├║",
    "withAltGraphShift": "├Ü"
  },
  "KeyV": {
    "unmodified": "v",
    "withShift": "V",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyW": {
    "unmodified": "z",
    "withShift": "Z",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyX": {
    "unmodified": "x",
    "withShift": "X",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyY": {
    "unmodified": "y",
    "withShift": "Y",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyZ": {
    "unmodified": "w",
    "withShift": "W",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit1": {
    "unmodified": "1",
    "withShift": "!",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit2": {
    "unmodified": "2",
    "withShift": "\"",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit3": {
    "unmodified": "3",
    "withShift": "┬ú",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit4": {
    "unmodified": "4",
    "withShift": "$",
    "withAltGraph": "Γé¼",
    "withAltGraphShift": null
  },
  "Digit5": {
    "unmodified": "5",
    "withShift": "%",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit6": {
    "unmodified": "6",
    "withShift": "^",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit7": {
    "unmodified": "7",
    "withShift": "&",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit8": {
    "unmodified": "8",
    "withShift": "*",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit9": {
    "unmodified": "9",
    "withShift": "(",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit0": {
    "unmodified": "0",
    "withShift": ")",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Space": {
    "unmodified": " ",
    "withShift": " ",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Minus": {
    "unmodified": "[",
    "withShift": "{",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Equal": {
    "unmodified": "=",
    "withShift": "+",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "BracketRight": {
    "unmodified": ";",
    "withShift": ":",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Backslash": {
    "unmodified": "\\",
    "withShift": "|",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Semicolon": {
    "unmodified": "m",
    "withShift": "M",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Quote": {
    "unmodified": "'",
    "withShift": "@",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Backquote": {
    "unmodified": "#",
    "withShift": "~",
    "withAltGraph": "\\",
    "withAltGraphShift": "|"
  },
  "Comma": {
    "unmodified": ".",
    "withShift": ">",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Period": {
    "unmodified": "/",
    "withShift": "?",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Slash": {
    "unmodified": "`",
    "withShift": "┬¼",
    "withAltGraph": "┬ª",
    "withAltGraphShift": null
  },
  "NumpadMultiply": {
    "unmodified": "*",
    "withShift": "*",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "NumpadSubtract": {
    "unmodified": "-",
    "withShift": "-",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "NumpadAdd": {
    "unmodified": "+",
    "withShift": "+",
    "withAltGraph": null,
    "withAltGraphShift": null
  }
}
```
</details>

This is how I added it (Windows Settings Screenshot):

![Windows Settings Screenshot](https://user-images.githubusercontent.com/10220080/64843821-67bb8080-d606-11e9-862e-21fe132df028.png)


<details>
  <summary>And here is a dump of my customized (Colemak) keyboard layout that I usually use (spoiler)</summary>


````jsonc
Layout: 00000809
Language: en-GB

{
  "KeyA": {
    "unmodified": "a",
    "withShift": "A",
    "withAltGraph": "├í",
    "withAltGraphShift": "├ü"
  },
  "KeyB": {
    "unmodified": "b",
    "withShift": "B",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyC": {
    "unmodified": "c",
    "withShift": "C",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyD": {
    "unmodified": "s",
    "withShift": "S",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyE": {
    "unmodified": "f",
    "withShift": "F",
    "withAltGraph": "├⌐",
    "withAltGraphShift": "├ë"
  },
  "KeyF": {
    "unmodified": "t",
    "withShift": "T",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyG": {
    "unmodified": "d",
    "withShift": "D",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyH": {
    "unmodified": "h",
    "withShift": "H",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyI": {
    "unmodified": "u",
    "withShift": "U",
    "withAltGraph": "├¡",
    "withAltGraphShift": "├ì"
  },
  "KeyJ": {
    "unmodified": "n",
    "withShift": "N",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyK": {
    "unmodified": "e",
    "withShift": "E",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyL": {
    "unmodified": "i",
    "withShift": "I",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyM": {
    "unmodified": "m",
    "withShift": "M",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyN": {
    "unmodified": "k",
    "withShift": "K",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyO": {
    "unmodified": "y",
    "withShift": "Y",
    "withAltGraph": "├│",
    "withAltGraphShift": "├ô"
  },
  "KeyP": {
    "unmodified": ";",
    "withShift": ":",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyQ": {
    "unmodified": "q",
    "withShift": "Q",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyR": {
    "unmodified": "p",
    "withShift": "P",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyS": {
    "unmodified": "r",
    "withShift": "R",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyT": {
    "unmodified": "g",
    "withShift": "G",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyU": {
    "unmodified": "l",
    "withShift": "L",
    "withAltGraph": "├║",
    "withAltGraphShift": "├Ü"
  },
  "KeyV": {
    "unmodified": "v",
    "withShift": "V",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyW": {
    "unmodified": "w",
    "withShift": "W",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyX": {
    "unmodified": "x",
    "withShift": "X",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyY": {
    "unmodified": "j",
    "withShift": "J",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "KeyZ": {
    "unmodified": "z",
    "withShift": "Z",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit1": {
    "unmodified": "1",
    "withShift": "!",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit2": {
    "unmodified": "2",
    "withShift": "@",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit3": {
    "unmodified": "3",
    "withShift": "#",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit4": {
    "unmodified": "4",
    "withShift": "$",
    "withAltGraph": "Γé¼",
    "withAltGraphShift": null
  },
  "Digit5": {
    "unmodified": "5",
    "withShift": "%",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit6": {
    "unmodified": "6",
    "withShift": "^",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit7": {
    "unmodified": "7",
    "withShift": "&",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit8": {
    "unmodified": "8",
    "withShift": "*",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit9": {
    "unmodified": "9",
    "withShift": "(",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Digit0": {
    "unmodified": "0",
    "withShift": ")",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Space": {
    "unmodified": " ",
    "withShift": " ",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Minus": {
    "unmodified": "-",
    "withShift": "_",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Equal": {
    "unmodified": "=",
    "withShift": "+",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "BracketLeft": {
    "unmodified": "[",
    "withShift": "{",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "BracketRight": {
    "unmodified": "]",
    "withShift": "}",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Backslash": {
    "unmodified": "\\",
    "withShift": "|",
    "withAltGraph": "\\",
    "withAltGraphShift": "|"
  },
  "Semicolon": {
    "unmodified": "o",
    "withShift": "O",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Quote": {
    "unmodified": "'",
    "withShift": "\"",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Backquote": {
    "unmodified": "`",
    "withShift": "~",
    "withAltGraph": "┬ª",
    "withAltGraphShift": null
  },
  "Comma": {
    "unmodified": ",",
    "withShift": "<",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Period": {
    "unmodified": ".",
    "withShift": ">",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "Slash": {
    "unmodified": "/",
    "withShift": "?",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "NumpadMultiply": {
    "unmodified": "*",
    "withShift": "*",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "NumpadSubtract": {
    "unmodified": "-",
    "withShift": "-",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "NumpadAdd": {
    "unmodified": "+",
    "withShift": "+",
    "withAltGraph": null,
    "withAltGraphShift": null
  },
  "IntlBackslash": {
    "unmodified": "\\",
    "withShift": "|",
    "withAltGraph": null,
    "withAltGraphShift": null
  }
}
```
</details>

**Comment by fxha** [comment]
@stefnotch I cannot reproduce your issue and we didn't change anything between 0.14.x and 0.15.0. Your posted layout seems also fine. There is one known issue that special character may not mapped correctly, especially on Windows due an upstream issue in atom's keyboard-layout library.

E.g. what I tried: on a Germany keyboard (qwertz) and German keyboard layout (qwertz):

- `Ctrl+A` (shortcut) = `Ctrl+A` (physically on keyboard), `Ctrl+Z` = `Ctrl+Z` --> Ok

On a German keyboard and Frence keyboard layout (azerty):

- `Ctrl+A` = `Ctrl+Q`, `Ctrl+Z` = `Ctrl+W` --> Ok

**Comment by stefnotch** [comment]
That's odd. I'll report back if I can find any more details regarding this.
