### ISSUE TITLE
Provide a way to edit language tag for a code fence in non-source-code-mode

### ISSUE THREAD

**Issue by sgon00** [marktext/marktext#2160]
This is a feature request. 
I find out I can not edit the language tag for a code fence once it has one in non-source-code-mode. 
For instance, if I want to change 

<pre>
```bash
</pre>
to
<pre>
```vim
</pre>

I can not do it in non-source-code-mode.
The only way to change it is to switch to source code mode.
But the switching btw non-souce-code and source-code mode is too slow and not much support (no find/undo feature) in source-code-mode.
I always avoid using the source code mode.
Thanks a lot.

**Comment by fxha** [comment]
Thank you for taking the time to report this issue.  You can simply click on the language (such as `bash`) and rename it to another language or select it via drop-down menu.

![mt_lang_id](https://user-images.githubusercontent.com/22716132/83337421-64167980-a2bb-11ea-8f49-b23173fd0a26.gif)
