### ISSUE TITLE
source code is modified when switching source code mode

### ISSUE THREAD

**Issue by aisbergde** [marktext/marktext#2171]
### Description

marktext changes the source code when switching source code mode

- [x] Can you reproduce the issue?

### Steps to reproduce

In source code mode use this text (2 spaces at the end of each line)

```
* abc  
** def  
† asd  
†† qwet
```

toggle the source code mode, toogle back, marktext will change the source code:

```
* abc  
  ** def  
  † asd  
  †† qwet
```

**Expected behavior:**

marktext should not manipulate my source code, when I switch

**Actual behavior:**

marktext manipulates and changes the source code

**Link to an example: [optional]**

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10

**Comment by fxha** [comment]
Thank you for taking the time to report this issue! Unfortunately, this is the expected behaviour as `*` is a list marker like `-`. You could escape the character with `*` like `\*`.

E.g. GitHub (GFM):

* abc  
** def  
† asd  
†† qwet

**Comment by aisbergde** [comment]
you are right in terms of syntax, and that is the point. 
The major issue is: **marktext changes text without my permission, not asking me.**

**That is the worst what an editor can do**: When I use Word or some similar with auto correction I can reject the auto correction. But I can't reject marktext auto correction. And this is "no go" for me and it would prevent me to use marktext as default editor for any markdown files because I should be afraid that some "marktext thinks it is incorrect text" will be corrected.

It would be great when marktext will hint me about syntax issues, and if it will even suggest me to change, also some "auto correction under my control" would be fine. 

But it must be possible to disable auto correction. Otherwise how to "view only" files?

Please reopen the issue. It is a major issue and major feature request, to prevent auto correction. You can rename the issue.

**Comment by fxha** [comment]
> marktext changes text without my permission, not asking me.

Please see #2189.
