### ISSUE TITLE
Add option to prevent hash resizing

### ISSUE THREAD

**Issue by Timecrash** [marktext/marktext#2172]
### Describe your feature request

I use MarkText primarily for writing fiction. A common way to break scenes up is to use a hash symbol ('#') between lines. However, in MarkText, typing a hash implies I want to make a heading, and automatically resizes any text that comes afterward to a standard h1 size, as well as adding spacing around the line. Since I don't intend to make a heading, I leave the hash alone and press enter. This makes the hash disappear. For it to appear, I have to escape it ('\#'), which adds an unnecessary character.

I propose an option which disables this automatic formatting and just interprets the hash as a regular character. No extra formatting is done.

If there's already a way to accomplish this, please let me know.

### What problem does this feature solve? [optional]

n/a

### Additional context [optional]

Here's an example of what I mean:
![2020-06-03 19_27_14-Window](https://user-images.githubusercontent.com/15052506/83698793-4fdebf00-a5d0-11ea-87e0-05fc147329b4.png)

The space between paragraphs is an empty line, though there's a hash there, as seen in the following image:
![2020-06-03 19_27_27-Window](https://user-images.githubusercontent.com/15052506/83698812-5cfbae00-a5d0-11ea-8f4f-e6e6d6839ea4.png)

If I add an escape character before the hash, the hash appears as regular text, however with an invisible character:
![2020-06-03 19_28_36-Window](https://user-images.githubusercontent.com/15052506/83698847-7866b900-a5d0-11ea-9e20-5ec951e33b55.png)

**Comment by fxha** [comment]
Thank you for taking the time to report this issue! Unfortunately, this is the expected behavior for a realtime preview editor but you can escape the heading with a backslash like `\#` to prevent this.
