### ISSUE TITLE
Theme issue

### ISSUE THREAD

**Issue by im-AMS** [marktext/marktext#2179]
Hi,
im using manajro kde.
I have a mac like theme,
It is not using my default global theme.
It is sort of rendering a windows like theme, which i dont even have in my system

**Comment by Deslucido** [comment]
_Ctrl + Coma ( , )_ and then set **titlebar** to _Native_

**Comment by im-AMS** [comment]
Is there gonna be a Qt version of this app...coz im in KDE and it does not behave well with GTK apps..

**Comment by fxha** [comment]
Thanks for creating this issue. Unfortunately, we do not plan to port Mark Text to other GUI frameworks. We use a cross-platform framework and design with the possibility to change the titlebar to the native one.

**Comment by 2br-2b** [comment]
Duplicate of #690
