### ISSUE TITLE
add graphics code in markdown

### ISSUE THREAD

**Issue by findNextStep** [marktext/marktext#218]
# 建议

建议添加对于一些markdown绘图代码的支持

比如`mermaid`,`flow`,`vega`使得通过markdown编写文档更加有效

[这里](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/diagrams)有一个[`vscode`](https://github.com/shd101wyy/vscode-markdown-preview-enhanced)/`atom`插件的实例

### Versions

- Mark Text:0.10.21(in master)
- OS: ubuntu 16.04

**Comment by Jocs** [comment]
感谢你提供的库，它应该是一个很好的参考，在 v1.0.0 之前可能不会添加对图表的支持，因为1.0版本之前主要是保证所有的 GFM 语法的支持，以及编辑器的稳定性。在 v1.0.0之后，我会考虑对图表支持，还有其它的一些未被 GFM 接受但是常见的语法，但是这些语法支持后，都将默认处于关闭状态，需要从 user preference 中打开。

**Comment by Jocs** [comment]
@findNextStep 也欢迎贡献代码？如果你有什么想法，可以在这讨论

**Comment by jeasonstudio** [comment]
关于图表相关的支持，我提供一些简单的参考：
1. UML/sequence 时序图：https://bramp.github.io/js-sequence-diagrams/
2. FlowChart  流程图：http://flowchart.js.org/
3. Graphviz 高阶作图：https://www.graphviz.org/ 和 http://viz-js.com/

最后，感谢 @Jocs  能开源这么好的 editor，让我在 Typora 之外眼前一亮。

**Comment by Jocs** [comment]
@jeasonstudio 第一和第二个已经在使用了，应该会在下一个版本推出，第三条中的两个库，我没有用过，需要调研下，如果符合需求，也会考虑的。谢谢你的关注。

**Comment by fxha** [comment]
Translation: Gant, sequence and flowchart diagrams should be released in the next version (`0.14.x`).

@Jocs `vega-lite` doesn't work properly any more. It says `Invalid Sequence Code` with any example.
