### ISSUE TITLE
 Option to hide prompt: 'Type @ to insert'

### ISSUE THREAD

**Issue by andynameistaken** [marktext/marktext#2180]
### Option to hide prompt: 'Type @ to insert'

Toggle switch for hiding this prompt - option in View menu and/or keyboard shortcut

### What problem does this feature solve? 
It helps to see only what you created so far - there is no true focus mode if you see more than you wrote in text editor.

### Additional context 

Nothing really, I just wanted to thank you for creating program with really nice UX.

**Comment by fxha** [comment]
Please goto "Editor" settings page and toggle "Hide hint for quickly creating paragraphs".
