### ISSUE TITLE
Disable save prompt

### ISSUE THREAD

**Issue by casonadams** [marktext/marktext#2184]
### Describe your feature request

I would like to have an option to disable the save prompt when closing out a document that has been modified

### What problem does this feature solve? [optional]

The files seem to be modified just by viewing them and when I close the window I get prompted to save.  Pretty annoying.

### Additional context [optional]

![image](https://user-images.githubusercontent.com/17597548/83932546-67e54880-a760-11ea-98be-bb48db58866f.png)

**Comment by fxha** [comment]
I'm closing this issue in favour of #2189. You may want to subscribe there for further updates.
