### ISSUE TITLE
设置中的一些选项没法更改

### ISSUE THREAD

**Issue by Royce003** [marktext/marktext#2193]
### 问题描述

请问无法更改语言为中文是什么原因

![img](https://user-images.githubusercontent.com/57910033/83963464-ee249a80-a8d8-11ea-82a6-f4ad243866d1.png)

theme 下的这两个按钮也灰灰的无法点击

![image](https://user-images.githubusercontent.com/57910033/83963509-3e9bf800-a8d9-11ea-8ca2-fe2205c51c57.png)

**Comment by chasezcz** [comment]
怎么解决的呢？
我咋也是这个、、、
