### ISSUE TITLE
Typo in Editor Preferences

### ISSUE THREAD

**Issue by Nesaijn** [marktext/marktext#2196]
### Description

There is a typo in the preferences.
Preferences > Editor > "What to do with traling newlines."

There is an "i" missing in "traling". It should be "trailing".

I have found the Typo in this exact file, line 90:
https://github.com/marktext/marktext/edit/develop/src/renderer/prefComponents/editor/index.vue

### Steps to reproduce

1. Open preferences
2. Click on "Editor"
3. Scroll down to the setting "What to do with traling newlines."

**Link to an example: [optional]**

![image](https://user-images.githubusercontent.com/25134837/83967156-42228580-a8bf-11ea-8778-e2ed3572396e.png)

### Versions

- Mark Text: v0.16.1 (AppImage)
- Operating system: Manjaro Gnome 3.36.2

**Comment by fxha** [comment]
Thank you for taking the time to report this issue and the typo is already fixed.
