### ISSUE TITLE
Can't install with brew cask 

### ISSUE THREAD

**Issue by so77id** [marktext/marktext#22]
using commnad `brew cask install mark-text` on mac, i don't get install the app.

![screen shot 2018-03-18 at 12 00 41](https://user-images.githubusercontent.com/4089219/37567313-0d2cf784-2aa4-11e8-9908-e0aaa8f07696.png)

**Comment by Joel-Costamagna** [comment]
<img width="814" alt="capture d ecran 2018-03-18 a 11 55 56" src="https://user-images.githubusercontent.com/16178951/37567862-5ff07640-2aa3-11e8-84f4-1f0d09233fe6.png">

works on my machine, can you try `brew update` ?

**Comment by so77id** [comment]
solved, ty
