### ISSUE TITLE
marktext converts Front Matter to content

### ISSUE THREAD

**Issue by houfu** [marktext/marktext#220]
### Description

I wanted to use mark text to write post in hexo (blog generator). When I open the markdown generated by hexo, mark text changes the front matter to be part of the content upon saving. This makes it impossible for me to use mark text to write blog posts.

### Steps to reproduce

1. Create a new markdown file using hexo (for example `hexo new page projects`). This is the plain output with some light editing.
```markdown
---
title: projects
date: 2018-04-29 00:15:16
---
# Projects

I have a lot of things to do!
```
2. Open markdown file in mark text. Screen display already shows that it is being converted into the content.
<img width="934" alt="screen shot 2018-04-29 at 12 25 41 am" src="https://user-images.githubusercontent.com/19525701/39398684-e42e6b18-4b43-11e8-91c8-8c7ffb5699f1.png">

3. **Don't do anything.**

4. Save file. File is different from original.
```markdown
---

title: projects

## date: 2018-04-29 00:15:16

# Projects

I have a lot of things to do!
```

**Expected behavior:** While I do not mind that mark text does not specially allow me to edit front matter (would be nice though: see #144), I at least expect mark text not to modify or affect the front matter.

**Actual behavior:** Front Matter is converted into content.

### Versions

- Mark Text: v 0.10.21
- OS: macOS 10.13.4

**Comment by Jocs** [comment]
@houfu thank you for you reporting, It's really a problem.

Before the support of Front Matter, marktext should not modify the contents of Front Matter. The reason that marktext modified Front Matter content is that the inside of marktext parser regard it as ATX heading.

**Comment by VonFry** [comment]
#223
