### ISSUE TITLE
Regex group search/replacement

### ISSUE THREAD

**Issue by ihipi** [marktext/marktext#2201]
### Describe your feature request
I felt in love with your editor and a litle thing that I miss in it is the regex group replacement.

### What problem does this feature solve? [optional]
I've developed the ability to replace a regex search using groups defined in the search input.

### Additional context [optional]
I'm used to use the regex group substitution in the search and replace and I added it locally. 
For the moment it is able to replace grouups identifying them by $1, $2, $x ... . If the number does not match with a valid group matched from search it will mantain a $x string.
I'm not used to develop in Vue and I'm still working on how to alert if you are typing and out of range group
![imatge](https://user-images.githubusercontent.com/12025838/83977947-605ea480-a904-11ea-89e4-e312e92b6f09.png)
![imatge](https://user-images.githubusercontent.com/12025838/83977980-9865e780-a904-11ea-920e-5da487fc836f.png)
I hope you like this feature and hope soon have the alert solved to make a PullRequest if you like it

**Comment by Jocs** [comment]
Implemented but not released.
