### ISSUE TITLE
UI typos

### ISSUE THREAD

**Issue by StructByLightning** [marktext/marktext#2202]
### Description
A couple of minor typos I noticed.

- [X] Can you reproduce the issue?

### Steps to reproduce
*This typo is in the Preferences/General tab.*
There should not be a period before the colon.
![image](https://user-images.githubusercontent.com/32056364/83985864-8ded2300-a8ef-11ea-8fb4-e111c2d17b59.png)

*The following three typos are in the Preferences/Editor tab.*
This period should not be present.
![image](https://user-images.githubusercontent.com/32056364/83985800-60a07500-a8ef-11ea-9e74-19309bf62d24.png)

Nor this one.
![image](https://user-images.githubusercontent.com/32056364/83985789-50889580-a8ef-11ea-84d0-7ed401955306.png)

Or this one.
![image](https://user-images.githubusercontent.com/32056364/83985833-744bdb80-a8ef-11ea-9462-7ab4c862e3b7.png)

*This typo is in Preferences/Markdown tab.*
The word "dilimiter" should be spelled "delimiter": https://www.dictionary.com/browse/delimiter
![image](https://user-images.githubusercontent.com/32056364/83985957-f3411400-a8ef-11ea-8fcc-dc4287b75697.png)

### Versions

- Mark Text: v0.16.1
- Operating system: Ubuntu 18.04

**Comment by brainchild0** [comment]
Is this issue resolved by c79f84e5cb7f1c4633ad52de3fd8130fafcda2f5?
