### ISSUE TITLE
characters are escaped  when copy & paste from Mark Text

### ISSUE THREAD

**Issue by persidskiy** [marktext/marktext#2204]
Text copied from Mark Text contains html escaped symbols

### Steps to reproduce

1. write a text with `>` character to any file
2. copy it using ctrl+c
3. paste it to any other editor

**Expected behavior:**

`>` is pasted

**Actual behavior:**

`&gt;` is pasted

![marktext_bug](https://user-images.githubusercontent.com/1527181/84056896-8bf29500-a9bf-11ea-9ed2-a34246fe4161.gif)

### Versions

- Mark Text: 0.16.1
- Operating system: archlinux 5.4.42-1-lts, Gnome 3.36

**Comment by persidskiy** [comment]
The same issue on my Mac

**Comment by pitastrudl** [comment]
Same issue with Latest version as of far, on Windows 10.

**Comment by fxha** [comment]
Duplicate of #1821.
