### ISSUE TITLE
Typo in settings

### ISSUE THREAD

**Issue by DSiekmeier** [marktext/marktext#2218]
### Description

In the settings dialog section "Markdown" there is a typo: The preferred d**i**limiter used in order list. instead of d**e**limiter.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open Mark Text
2. Open Settings
3. Navigate to `Markdown`
4. Scroll to delimiter setting

**Expected behavior:**

The word should be written correctly.

**Actual behavior:**

The word is written wrong.

### Versions

- Mark Text: v0.16.1
- Operating system: Xubuntu 18.04.4

**Comment by brainchild0** [comment]
Resolved in development branch (commit [c79f84e5c](https://github.com/marktext/marktext/commit/c79f84e5cb7f1c4633ad52de3fd8130fafcda2f5#diff-81e6914de72d12db99087632013f7de7)).
