### ISSUE TITLE
Compose key does not work anymore.

### ISSUE THREAD

**Issue by epeios-q37** [marktext/marktext#2225]
### Description

With version 0.16.1, the compose key, that is the key combination which allows to type precomposed characters such as `œ` or `…`, is no longer working. The compose key combination seems to be ignored.

The compose key works perfectly with v0.15.1 

- [X] Can you reproduce the issue? 

### Steps to reproduce

1. Type the compose key combination
2. type characters `o` and then `e` 

**Expected behavior:**

`œ` should be displayed.

**Actual behavior:**

`oe` is displayed.

### Versions

- Mark Text version: v0.16.1 (this bug does **not** occur with v0.15.1)
- Operating system: Kunbuntu 18.0.4

**Comment by brainchild0** [comment]
I failed to  reproduce in Mint 19.3 with Cinnamon 4.4.8.

Is Mark Text the only application currently affected by this problem on your system?

**Comment by epeios-q37** [comment]
Yes, only Mark Text v0.16.1 and v0.16.2, but **not** v0.15.1.

To summarize:

| Version | Source   | Result |
| ------- | -------- | ------ |
| 0.15.1  | AppImage | Works  |
| 0.16.1  | Kubuntu  | Fails  |
| 0.16.2  | AppImage | Fails  |

**Comment by brainchild0** [comment]
Could you test with 0.16.0?

**Comment by epeios-q37** [comment]
Same problem with v0.16.0.

Now, we have:

| Version | Source   | Result |
| ------- | -------- | ------ |
| 0.15.1  | AppImage | Works  |
| 0.16.0  | AppImage | Fails  |
| 0.16.1  | Kubuntu  | Fails  |
| 0.16.2  | AppImage | Fails  |

I occasionally have access to a Windows machine, on which I could install Mark Text and do some testing, but I doubt it would be useful. What do you think about it?

**Comment by brainchild0** [comment]
@epeios-q37: It may be useful to know whether you find the problem occurs on Windows, if you are able and willing to test.

**Comment by epeios-q37** [comment]
I tried v0.15.1 and v0.16.2 under *Windows* 10, and both work.

| Version | OS or Source   | Result |
| ------- | -------- | ------ |
| 0.15.1 | AppImage | **Works**  |
| 0.15.1 | Windows | **Works** |
| 0.16.0 | AppImage | Fails  |
| 0.16.1 | Kubuntu  | Fails  |
| 0.16.2 | AppImage | Fails  |
| 0.16.2 | Windows | **Works**  |

*OS or Source*:
- `Windows`: under *Windows 10*,
- `AppImage`: *AppImage* under *Kubuntu* v18.0.4,
- `Kubuntu`: official package under *Kubuntu* v18.0.4.

**Comment by brainchild0** [comment]
Thank you for the report. These problems appear to have a common source upstream.   Suggest closing in favor of https://github.com/marktext/marktext/issues/2235.

**Comment by epeios-q37** [comment]
#2235 suggests that the problem comes from *Electron*, but I also use *VSCodium*, which is based on *Electron*, and the compose key works as expected.

Here is the *about* from *VSCodium*:

```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-19T10:53:55.306Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-59-generic
```

If you still think that #2235 is related to this one, close the latter. I will test the version of Mark Text which fixes #2235 to check if there is still the compose key bug and will reopen this issue if necessary.

**Comment by brainchild0** [comment]
Electron may have problems that  manifest differently, in some case not at all,  in various builds or versions of various application run on different systems. Some VSCode users are affected by similar issues.  You might look at   the discussions in some of the Atom and Electron issues, and test some of the workarounds, then report any information relevant to your situation. I placed some links in #2235.

**Comment by epeios-q37** [comment]
I have to correct one of my previous statement.
This story in #2235 with *Electron* made me suspicious, so I did some tests with *Chromium* (83.0.4103.61), and the compose key issue **does** occur too. *Firefox* is my default browser, that's why I never noticed it...
So, I guess *Electron* is the culprit...

| Program | Version | OS or Source   | Result |
| ------- | :- | -------- | ------ |
| Mark Text | 0.15.1 | AppImage | Works  |
| Mark Text | 0.15.1 | Windows | Works |
| Mark Text | 0.16.0 | AppImage | **Fails**  |
| Mark Text | 0.16.1 | Kubuntu  | **Fails**  |
| Mark Text | 0.16.2 | AppImage | **Fails**  |
| Mark Text | 0.16.2 | Windows | Works  |
| Chromium | 83.0.4103.61 | Kubuntu | **Fails** |

*OS or Source*:
- `Windows`: under *Windows 10*,
- `AppImage`: *AppImage* under *Kubuntu* v18.0.4,
- `Kubuntu`: official package under *Kubuntu* v18.0.4.

**Comment by epeios-q37** [comment]
Workaround: set `GTK_IM_MODULE` environment variable to `xim`.
See https://bugs.chromium.org/p/chromium/issues/detail?id=1129424

**Comment by Jaaaarne** [comment]
0.16.3 on Windows 8.1. AltGr code doesn't work.

**Comment by avbenavides** [comment]
MarkText v0.16.3
MacOS BigSur 11.6.1 (20G224)

The AltGR keys don't work with Swedish keyboard:
©@£$∞§|[]
ALT GR + 1...9
Instead swaps to open tab with the index of the key, as in ALT+1...9

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2235. You may want to subscribe there for further updates.
