### ISSUE TITLE
Feature Suggest: please support plugin in Mark Text

### ISSUE THREAD

**Issue by rainfu** [marktext/marktext#224]
### Description

[这个项目很惊艳，尤其是虚拟node与可视化写作～即便是对多年开发写作类软件的我。本希望贡献一些插件，不过目前插件对核心代码干挠过大，希望能在1·0之前尽快布局下插件机制，让关注者可以贡献代码、而核心团队专注于主版本更新]

### Steps to reproduce

以目前其中的一个典型插件**斗图**为例，我查找了下，在以下6个文件中有引用

1. Store/index.js
2. Menus/edit.js
3. App.vue
4. Preference.md
5. Uploadimage
6. aidou.vue

其实也就是插件机制需要处理的问题

1. Vue store自带Module 机制
2. 插件中添加menu相关，程序启动时加载
3. 动态组件？
4. 插件可在插件区域内自动加载至设置文件中，比如
`｛ 
      …，
      Plugins:{
          Aidou:{
               Enable:false,
               … 
          }
     }
}
`
5. Plugin 代码 

**Expected behavior:** [What you expected to happen]

新的开发者将代码放在src/plugins/aidou 下即可实现全部功能，删除插件删除代码即可。

### 建议

最好有意识的在editor,eventcenter,bus，parser中暴露一些api，让开发者能够获得更多处理事件机会

共勉:）

**Comment by Jocs** [comment]
@rainfu 感谢你的建议，Mark Text 是有计划在 v1.0.0 发布之后添加插件机制，以及自定义主题。在 v1.0.0 主要还是完善基本功能，及编辑器稳定性。

**Comment by Jocs** [comment]
@rainfu If you are interested in this project, welcome to contribute your code or give some opinions.

**Comment by Jocs** [comment]
dup to #375
