### ISSUE TITLE
Mark Text used a lot of memory

### ISSUE THREAD

**Issue by chlins** [marktext/marktext#225]
### Description

macOS 10.13 下打开后占用1G左右

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](https://codepen.io/) or a similar service and paste a link here]

### Versions

- Mark Text: 最新版
- OS:

**Comment by Jocs** [comment]
@chlins 请问下，你打开的文件大小，以及编辑时间等参数？及编辑的一些细节？

**Comment by Jocs** [comment]
@chlins If no more detail after one week, I'll close this issue.

**Comment by chlins** [comment]
新建了一个文件，内容是空的，重新关闭marktext再打开就好了

**Comment by Jocs** [comment]
@chlins 1G 左右还是比较正常，应为毕竟 Electron 中包含了一个 Chrome 浏览器。
