### ISSUE TITLE
剪切后无法撤销

### ISSUE THREAD

**Issue by leaves4j** [marktext/marktext#226]
### Description

mac command+x 之后再 command+z 并不能撤销，这个时候关闭编辑器文件会自动保存，一晚上写的文章就这么找不回来了🙂

### Versions

- Mark Text: 0.7.17
- OS: mac

**Comment by Jocs** [comment]
@leaves4j 很抱歉，Mark Text 给你带来不便，现在 Mark Text 还处于全力开发中，release 的版本也会有些 bug。

我刚才测试了，现在确实还无法撤销 剪切内容，在下一个版本我们会修复这个问题。也请你及时更新到最新版本。

**Comment by Jocs** [comment]
@leaves4j 自动保存功能默认是关闭状态，可以根据需要选择打开或者关闭。

**Comment by Jocs** [comment]
@leaves4j 在将来，我们可能会添加版本控制或者「time machine」 功能，这样及时不小心删除也能够找回文件内容。

**Comment by Jocs** [comment]
duplicate with #232
