### ISSUE TITLE
TOC navigation does not work.

### ISSUE THREAD

**Issue by CyrusYip** [marktext/marktext#2261]
### Description
TOC navigation does not work on marktext 0.16.2 on Kubuntu 20.04 and windows10 2004.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. open a file
2. Ctrl + J
3. Click a heading on the sidebar

**Expected behavior:** 
Current page jumps to the heading
![deepin-screen-recorder_typora_20200627160122](https://user-images.githubusercontent.com/60951091/85917763-99e55880-b88f-11ea-9f32-067af6617498.gif)

**Actual behavior:** 
Current page just moves a bit.
![deepin-screen-recorder_marktext_20200627155038](https://user-images.githubusercontent.com/60951091/85917616-3870ba00-b88e-11ea-8af6-307f910f8269.gif)

**Link to an example: [optional]**

### Versions

- Mark Text version: 0.16.2
- Operating system: Kubuntu 20.04 / Windows10 2004

**Comment by pitastrudl** [comment]
Same issue on XUbuntu 18.04, version 0.16.2

**Comment by 4l1fe** [comment]
Same issue Kubuntu 18.04, Marktext 0.16.2.

I figured out it happens after zooming out over 100%. When i get back to 100% navigation works well.

**Comment by otie** [comment]
Can confirm the zoom-issue. If scale in windows 10 is set to something else than 100% the issue described above occurs. Works perfect with 100% scale.

**Comment by fsourd** [comment]
To refine, it seems to work if the scale factor is integer `--force-device-scale-factor=2`, which can be useful for 4K screens.

**Comment by YalandHong** [comment]
Possible duplicate of #1775 

The problem also seems to appear when you search the document, i.e. using Ctrl+F.

Please close this issue if it helps. There're way too many duplicate issues in this repo. Thanks!

**Comment by CyrusYip** [comment]
100% and 200% scale work for me.

```bash
marktext --force-device-scale-factor=1
marktext --force-device-scale-factor=2
```

Thanks to @4l1fe and @fsourd .

**Comment by CyrusYip** [comment]
I closed this issue because it's a duplicate of https://github.com/marktext/marktext/issues/1775

**Comment by YalandHong** [comment]
> This is still an issue:
> 
> ```
> Mark Text: v0.16.3
> Node.js: 12.18.3
> Electron: 11.1.1
> Chromium: 87.0.4280.88
> OS: Linux x64 5.10.80-1-lts
> ```

Yes, but it's a dup of #1775. Please upvote that issue and report your problems there. Thanks!
