### ISSUE TITLE
sidebar does not remember width on collapse

### ISSUE THREAD

**Issue by Miosame** [marktext/marktext#2268]
If you collapse the sidebar via: ![image](https://user-images.githubusercontent.com/8201077/86314341-b84caa80-bc27-11ea-952c-69ea0789c565.png) and then open it again, it won't remember the width it was prior to collapsing, having to resize it each time you open it again.

**Comment by Jocs** [comment]
maybe due to #988

**Comment by YalandHong** [comment]
please track #2421
