### ISSUE TITLE
Modification indicator not working

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#227]
### Description

The modification indicator (red dot) is not working any more when you don't touch the custom titlebar on Linux and Windows.

@Jocs You also can't save a file because backend thinks no changes are made (file size is 0KB). I think this is a problem relating to the performance fixes.

### Steps to reproduce

1. Start Mark Text and type something --> modification indicator don't apperars.

**Expected behavior:** [What you expected to happen]

Backend should notice the changes.

**Custom titlebar:**

![mt_tb](https://user-images.githubusercontent.com/22716132/39514169-c3ea5b7c-4df6-11e8-92df-8b06439a931d.png)

### Versions

- Mark Text: master (dc82145)
- OS: at least Linux and Windows

**Comment by Jocs** [comment]
@fxha I just test it on MacOs, and it works well, I just delay the `change` event for 1 second. So can you help find why it does not work on Linux and Windows?

**Comment by Jocs** [comment]
@fxha 

I am also confused why it dose not work in Linux and Windows system, and it works well in MacOs system.

So can you check weather `dispatchChange` method in `src/editor/index.js` is called when you typing?

this method will trigger the `change` event.

**Comment by fxha** [comment]
OK, it was my bad on Windows, because I don't wait 1s. But Linux seems to work too. I don't know why...
