### ISSUE TITLE
Couldn't open preference.md in new version

### ISSUE THREAD

**Issue by infinitelamx** [marktext/marktext#228]
### Description

While clicking preference, it would not open preference.md but a new edit windows

### Steps to reproduce

1. Click Menu
2. Click File
3. Click Preferences

**Expected behavior:** Open preference.md

**Actual behavior:** Open a new edit windows

### Versions

- Mark Text: 0.10.21
- OS: Windows 10 1083

**Comment by infinitelamx** [comment]
It only happen at completely new install, if some one install an early version, then the issue will not happen.
And there is another small problem, if I install version 0.10.21 when I don't uninstall the earlier version, then both versions will appear in Application list of windows setting.

**Comment by Jocs** [comment]
>And there is another small problem, if I install version 0.10.21 when I don't uninstall the earlier version, then both versions will appear in Application list of windows setting.

this problem please refer to the release [log](https://github.com/marktext/marktext/releases).

>You need uninstall the old version of Mark Text before install version 0.10.21, because we changed the AppId when build.

**Comment by fxha** [comment]
> It only happen at completely new install, if some one install an early version, then the issue will not happen.

@infinitelamx I can't reproduce this issue with v0.10.21 on Windows. Can you please check whether the directory `%appdata%\marktext` (`C:\Users\YOUR_USERNAME\AppData\Roaming\marktext`) exists and `preference.md` or `error.log` exists inside this folder.

Maybe the following will help:

1. Please make a copy of `%appdata%\marktext` - this will only contains user settings and error logs.
2. Then try:
  - delete `%appdata%\marktext\preference.md` and try again
  - delete `%appdata%\marktext` and try again. After you start Mark Text there should be files inside the folder like `preference.md`.
3. But if this is not working, can you please send us the latest entries from error log (`%appdata%\marktext\error.log`). Either via E-Mail (see profile from @Jocs  or @fxha) or post it here. The log file should be sorted by date and contains only error information.

>  And there is another small problem, if I install version 0.10.21 when I don't uninstall the earlier version, then both versions will appear in Application list of windows setting.

As @Jocs already said. You can just remove the old entry.
