### ISSUE TITLE
Import custom themes in Ubuntu 20.04

### ISSUE THREAD

**Issue by rohan-paul** [marktext/marktext#2283]
Add a new custom theme is greyed out in Ubuntu 20.04 (not sure if this is the currenct expected behaviour or if its a bug )

![image](https://user-images.githubusercontent.com/12703975/87800944-a8120d80-c86c-11ea-9f28-0fa7a3749f43.png)

**Comment by rockhazard** [comment]
I don't believe this works for anyone yet. See this post: [Themes.](docs/THEMES.md)

**Comment by fxha** [comment]
Thank you for reporting the issue but user themes aren't supported yet.
