### ISSUE TITLE
Math matrix are being exported too close

### ISSUE THREAD

**Issue by BaiqingL** [marktext/marktext#2288]
- [x] Can you reproduce the issue? 

Export the following math code to a PDF:

`$$
q-p=\begin{bmatrix}
0-(-6)\\-4-3
\end{bmatrix}\\
=\begin{bmatrix}
6\\-7
\end{bmatrix}
$$`

**Expected behavior:**

The second matrix be placed at an appropriate distance below the first one

**Actual behavior:**

The second matrix almost touching the first one

- Mark Text version: 0.16.2
- Operating system: Windows 10 x64

**Comment by barro350** [comment]
Well, this issue is actually about the LaTeX syntax. Strictly speaking, you cannot use `\\` in the math mode unless you are in the `align` environment or something similar.

Try:

```
$$
\begin{aligned}
q-p=\begin{bmatrix} 0-(-6)\\-4-3 \end{bmatrix}\\ =\begin{bmatrix} 6\\-7 \end{bmatrix}
\end{aligned}
$$

**Comment by BaiqingL** [comment]
Oh! Learned something new today, thanks!
