### ISSUE TITLE
copy image file to current fold

### ISSUE THREAD

**Issue by wsrf16** [marktext/marktext#2292]
### Describe your feature request

I wish to copy image file to ${current_fold/.asset} when upload.3q
### Additional context [optional]

like this.
![image](https://user-images.githubusercontent.com/11867768/88474326-e20f9d80-cf57-11ea-8bbc-d6c2e40685e1.png)

**Comment by brainchild0** [comment]
Is this request the same as in #549?

**Comment by wsrf16** [comment]
yes  3q
