### ISSUE TITLE
Add embedded terminal

### ISSUE THREAD

**Issue by eeriksp** [marktext/marktext#2297]
### Describe your feature request

When working with a bigger body of text with a more complicated directory structure it is very convenient to do some operations using the command line. Since jumping between windows is distracting, it would be great to have a possibility to have an embedded terminal in the bottom of the window, just as in VC Code or in IntelliJ IDEA.

### Additional context

Proposal regarding design: the terminal should appear in the lower part of the editor window. It should not cover the left sidebar. Displaying the terminal should be optional (and perhaps not shown by default) since the application is not only for developers.

**Comment by brainchild0** [comment]
A handful of requests have been for features borrowed from IDEs. 

It is an open question whether Mark Text seeks to resemble an IDE in any specific way.

**Comment by 4l1fe** [comment]
Your wish is like making IDE from a simple, specific editor what is wrong concept at all. Just take an IDE , they are almost all support markdown editing.

**Comment by fxha** [comment]
Thanks for the idea but this is outside of the scope of the project. We want keep things clean and minimal but this could be realized via plugins later.
