### ISSUE TITLE
Impossible to type "#" on Mac keyboard due to tab switching

### ISSUE THREAD

**Issue by vfxdev** [marktext/marktext#2299]
### Impossible to type "#" on Mac keyboard due to tab switching

When trying to type "#" on a Mac keyboard (using ALT-3) tab switching is activated and "#" does not appear.

### Steps to reproduce

1. Pressing ALT-3 on a Mac keyboard

**Expected behavior:**

"#" appears in the text

**Actual behavior:**

Active tab is switched to number 3.

### Versions

- Mark Text version: 0.16.2
- Operating system: MacOS 10.15.5

PS: Thanks to all the developers for their efforts, MarkText is awesome!

**Comment by ortonomy** [comment]
Came here to say this. Seems like a lovely app, but broken on MacOS as it is.

**Comment by ttomasini** [comment]
Until it has been fixed in [`shortcutHandler.js`](https://github.com/marktext/marktext/blob/develop/src/main/keyboard/shortcutHandler.js) (e.g. for swiss keyboard layouts) you can just add the following json to your [`keybindings.json`](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md) file:

```json
{
    "tabs.switch-to-first": "Cmd+1",
    "tabs.switch-to-second": "Cmd+2",
    "tabs.switch-to-third": "Cmd+3",
    "tabs.switch-to-fourth": "Cmd+4",
    "tabs.switch-to-fifth": "Cmd+5",
    "tabs.switch-to-sixth": "Cmd+6",
    "tabs.switch-to-seventh": "Cmd+7",
    "tabs.switch-to-eighth": "Cmd+8",
    "tabs.switch-to-ninth": "Cmd+9",
    "tabs.switch-to-tenth": "Cmd+0"
}
```

**Comment by vfxdev** [comment]
> Until it has been fixed in [`shortcutHandler.js`](https://github.com/marktext/marktext/blob/develop/src/main/keyboard/shortcutHandler.js) (e.g. for swiss keyboard layouts) you can just add the following snippet to your [`keybindings.json`](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md) file:
> 
> ```json
> {
>     "tabs.switch-to-first": "Cmd+1",
>     "tabs.switch-to-second": "Cmd+2",
>     "tabs.switch-to-third": "Cmd+3",
>     "tabs.switch-to-fourth": "Cmd+4",
>     "tabs.switch-to-fifth": "Cmd+5",
>     "tabs.switch-to-sixth": "Cmd+6",
>     "tabs.switch-to-seventh": "Cmd+7",
>     "tabs.switch-to-eighth": "Cmd+8",
>     "tabs.switch-to-ninth": "Cmd+9",
>     "tabs.switch-to-tenth": "Cmd+0"
> }
> ```

That fixed it, thank you for the great workaround!

**Comment by MrHeer** [comment]
https://github.com/marktext/marktext/pull/1975#discussion_r428621120

**Comment by qihuazhong** [comment]
Interest... I didn't know there are two versions of Mac keyboard. On my (old) Mac Pro, # is shift+3, as in the usual windows keyboard.

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2235. You may want to subscribe there for further updates.
