### ISSUE TITLE
快捷键撤销问题

### ISSUE THREAD

**Issue by xianyunyh** [marktext/marktext#230]
### 撤销容易出问题

我在使用的时候，经常撤销，撤销经常 出错。有一次，我全选了，然后不小心撤销了。然后我的内容全没了。这是很让人头疼的事。
快捷键是否可以支持自定义。

### Versions

- Mark Text: v 0.10.21

- OS: Windows 10

**Comment by Jocs** [comment]
@xianyunyh 在1.0版本之前不会有快捷键自定义功能，针对内容丢失问题，之后可能会出一个 time machine 功能，就是即使没有保存，marktext 崩溃等，都可以找回编辑的内容。

现在撤销功能存在一些问题的，在 1.0 版本会有所改进。

**Comment by xianyunyh** [comment]
软件中Source Code mode, Typewriter mode 中切换的快捷键是否能改变下？
因为很多大部分软件`Ctrl+Shift+S`都是代表另存为。

**Comment by Jocs** [comment]
@xianyunyh 这个问题在 master 分支中已经解决了，应该在下一个发布版本更新出来。
