### ISSUE TITLE
Support for chemical equations via mhchem

### ISSUE THREAD

**Issue by sandeep-rao** [marktext/marktext#2301]
### Describe your feature request
I would really appreciate the addition of mhchem extension to KaTex / MathJax to help in writing chemical equations and formulae.

### Additional context [optional]
Joplin already has support for this, since it's OSS, maybe one could have a look into it and port it here.
see <https://discourse.joplinapp.org/t/feature-request-implementation-of-the-mhchem-extension-to-katex/3765/3>

**Comment by 0187773933** [comment]
https://github.com/marktext/marktext/blob/develop/src/muya/lib/utils/exportHtml.js#L3

```
import katex from 'katex'
import 'katex/dist/contrib/mhchem'
import loadRenderer from '../renderers'
```

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #1909. You may want to subscribe there for further updates.
