### ISSUE TITLE
Markdown syntax inside HTML tags (CommonMark spec)

### ISSUE THREAD

**Issue by barro350** [marktext/marktext#2308]
### Describe your feature request

[CommonMark spec](https://spec.commonmark.org/0.29/#example-122) prescribes that one may use Markdown syntax inside a HTML tag by separating Markdown paragraphs with the HTML tags by newlines:

```markdown
<div style="color:red;">

*Markdown*

</div>
```

This should be rendered in HTML to:

```html
<div style="color:red;">
<p><em>Markdown</em></p>
</div>
```

It would be great if Mark Text can handle this case so that the WYSIWIG mode supports CommonMark in a more faithful way.

**Comment by wundrweapon** [comment]
Perhaps Mark Text can depend on an existing CommonMark-compliant renderer

**Comment by DYH-Hong** [comment]
Duplicate of #1764
