### ISSUE TITLE
Save images in same folder as markdown-file

### ISSUE THREAD

**Issue by mbranchnl** [marktext/marktext#2309]
### Describe your feature request

I like the feature of being able to paste an image in my marktext files. There are a few options but i'm missing the option to save the pasted image in the same folder as where my markdown file is.

### What problem does this feature solve? [optional]

Being able to 'export' and easly send the markdown file with the attachments with it.

**Comment by brainchild0** [comment]
Is this request the same as in #549?

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate of #549. You may want to subscribe there for further updates.
