### ISSUE TITLE
Fenced code blocks - cut not working

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#231]
### Description

In fenced code blocks (```), CTRL+X (cut) doesn't work.

### Steps to reproduce

1. Create a fenced code block
2. Write some text
3. Use CTRL+X

**Expected behavior:** The text gets removed and copied to the clipboard

**Actual behavior:** Nothing

### Versions

- Mark Text: v 0.10.21
- OS: Windows 10

**Comment by Jocs** [comment]
Yeh, I just test it, and find `cut` in fenced code block is not work.

as an alternative,

You can use copy\paste in code block, and select what you want to cut, use `backspace` to delete them.

we will fix this issue as soon as possible.
