### ISSUE TITLE
Links to headers as document navigation panel

### ISSUE THREAD

**Issue by mohamnag** [marktext/marktext#2315]
### Describe your feature request

In lengthy documents with substantial amount of text, it would be very nice to have an additional side panel with all headers listed up (with styling to show the header level) with links that makes it possible to navigate to that header by clicking on it in that panel.

### What problem does this feature solve? [optional]

navigation and keeping oversight while working on larger documents.

**Comment by brainchild0** [comment]
Have you tried using the _Table of Contents_ tab in the sidebar?

**Comment by mohamnag** [comment]
ups, haven't seen it. just searched in the menus and didn't find any thing related. but then I will close this.
