### ISSUE TITLE
Undo cut not working

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#232]
### Description

CTRL+X (cut) is not compatible with undo/redo

### Steps to reproduce

1. Write some text
2. Select a part of it
3. CTRL+X (cut)
4. Text gets cutted
5. CTRL+Z (undo) to undo the cutting

**Expected behavior:** That the cutted text is there again

**Actual behavior:** It doesn't get undone

- Mark Text: v 0.10.21
- OS: Windows 10

**Comment by Jocs** [comment]
thanks for your reporting this issue, and we'll fix it in the next release version!
