### ISSUE TITLE
Refresh images manually or automatically (on change)

### ISSUE THREAD

**Issue by rugk** [marktext/marktext#2320]
### Describe your feature request

* for local images: maybe check for changes autl´omatically and refresh (if possible)
* otherwise/for remote images: provide a "refresh" button in the image menu

### What problem does this feature solve? [optional]

When an image changes if you have a document open, that is not refreshed.
You need to reopen the document to do that.

### Additional context [optional]

Example use case:
I e.g. draw an image with MyPaint, embed it in a MD document. Then change that image again, because I forgot something.
Problem is, it is not updated now.

**Comment by YalandHong** [comment]
Dup of #703

In order to reduce duplications, please close this issue and report your problems there. Thanks!

**Comment by rugk** [comment]
Duplicate of #703
