### ISSUE TITLE
CTRL+Z not working in Source Code Mode

### ISSUE THREAD

**Issue by DocBrown101** [marktext/marktext#2328]
### Description
Pressing `CTRL+Z` doesn't do anything in Source Code Mode.

### Steps to reproduce
1. Toggle Source Code Mode on
1. Type some text
2. Delete some text
3. `CTRL+Z`

**Expected behavior:** That the deleting text gets undone

**Actual behavior:** Nothing happens

### Versions
* Mark Text: v 0.16.2
* OS: Windows 10
* QWERTZ keyboard layout

**Comment by berserkwarwolf** [comment]
is this issue recognized by the development team ?

**Comment by xrat** [comment]
Also, I can reproduce this on Ubuntu MATE 20.04, also Mark Text v0.16.2

**Comment by xrat** [comment]
This issue might be/is likely a duplicate of https://github.com/marktext/marktext/issues/1321

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate of #2188. You may want to subscribe there for further updates.
