### ISSUE TITLE
Shift+Tab does not navigate through table in reverse

### ISSUE THREAD

**Issue by evan-cohen** [marktext/marktext#2330]
### Description

Shift+Tab is typically understood to move to the previous cell or row when in a table.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Insert a table
2. Select number of rows and columns
3. Press tab to navigate through cells and rows
4. Press Shift+Tab. No response is given.

**Expected behavior:**

Shift+Tab should switch focus to the previous cell in the same row, or to the last cell in the previous row.

**Actual behavior:**

No response is observed.

### Versions

- Mark Text version: v0.16.2
- Operating system: macOS 10.15.5

**Comment by bmvisoky** [comment]
Noticed pull request was never closed, I can take a look and see if I can get this working?

**Comment by evan-cohen** [comment]
@bmvisoky I got it working in #2331, but still waiting on a review by the maintainers
