### ISSUE TITLE
Can't insert items between two adjacent code blocks

### ISSUE THREAD

**Issue by zmen** [marktext/marktext#2334]
### Description

It's not convenient to insert items between two adjacent code blocks.

### Steps to reproduce

1. Create two code blocks, with nothing else between them
2. Try to insert something between `block1` and `block2`

```javascript
block1
```
```javascript
block2
```

**Expected behavior:**

I can easily add a new line between blocks by moving my cursor. Just like what Typora does.

**Actual behavior:**

Currently I can only do it by:

- Switch to source code mode
- Or delete one blocks, paste it back after editing

### Versions

- Mark Text version: v0.16.1
- Operating system: macOS Catalina 10.15.6

**Comment by GalensGan** [comment]
is there  additional simple ways to get it ?

**Comment by zmen** [comment]
> is there additional simple ways to get it ?

Yes, I found each active block has an icon on the left, you can select `New Paragraph` to add a new line (or shortcut `Shift + Cmd + N`)
