### ISSUE TITLE
Could not select Chinese font that already installed in the system.

### ISSUE THREAD

**Issue by wanyt** [marktext/marktext#2340]
### Question description

 不能选择中文字体，在字体选择的选项没有系统中的中文字体。

**Comment by 71GA** [comment]
I also can not select the font installed on the system. Marktext is v0.16.2 and I am on Debian.

**Comment by fxha** [comment]
Thank you for reporting the issue. Could you please provide the font name here?

**Comment by wanyt** [comment]
I find the Chinese font recently. The font shows "SongTi TC" not "仿宋", so I didn't find it in the first time. You can search the font name in English, not your local language.
