### ISSUE TITLE
Pandoc import not working with flatpak package

### ISSUE THREAD

**Issue by thecursedfly** [marktext/marktext#2343]
### Description

The issue occurs with the flatpak package on linux.
When I try to import a file (File>Import),  all I get is a popup message saying that pandoc is not installed. Even after I installed it myself (in Opensuse through Yast software).
The issue can be reproduced anytime even after restarting.

**Expected behavior:**

When I install Mark Text, pandoc is included in the installation, so that any feature included in Mark Text automatically works without the need of separate installations.
Also, when the File>Import feature is used, if pandoc is installed (which should be true automatically, see previous sentence), it is possible to select a file to import, without a popup telling me that pandoc is not installed.
The same should be true when drag and dropping the file to import onto the window.

### Versions

- Mark Text version: 0.16.2 (flatpak package)
- Operating system: OpenSuse Tumbleweed 20200914

**Comment by FilBot3** [comment]
The Flatpak manifest file is located here

* https://github.com/flathub/com.github.marktext.marktext

From my recent experience with Flatpak, it's working as intended. Maybe the makers of this Flatpak should use a shim start up script instead to setup the PATH's for Mark Text to see the host system commands, or allow an override so that `flatpak-spawn --host pandoc` can be used.

**Comment by FilBot3** [comment]
Your issue may be better supported on the Flathub repo for this project.

**Comment by fxha** [comment]
Thank you for taking the time to report this issue. This is an issue with Flatpaks sandbox and you have manually allow the access to `pandoc` on your host system. Please checkout Flatpaks documentation for this because including it into the manifest would possible allow to bypass the sandbox.
