### ISSUE TITLE
Why do HTML Inline Style Attributes Do Not Render While in the Editor Mode ? 

### ISSUE THREAD

**Issue by 0187773933** [marktext/marktext#2344]
### But why can't it render while you are writing the source markdown?

```
<div>
<center><h2> <span style='color:#35a166'>testing</span> </h2></center>
</div>
```

**Comment by fxha** [comment]
Thank you for reporting the issue but currently no CSS or HTML style attributes are allowed due to markdown specification and we don't plan to change this in the future.
