### ISSUE TITLE
Image uploader to GitHub fails for copy/pasted image

### ISSUE THREAD

**Issue by kzu** [marktext/marktext#2347]
### Description

Drag&drop of a local image file property works fine and uploads to GH.

Pasting image from clipboard fails and is replaced with local image path.

![MarkTextPasteFails](https://user-images.githubusercontent.com/169707/94046532-2d52fa80-fda7-11ea-9cc2-235090d662f5.gif)

**Expected behavior:**

Pasted image should be saved temporarily with some name (similarly to how files are named when uploaded to GH from local files), then uploaded, finally replaced in the markdown.

**Actual behavior:**

Upload fails and just the local file path is saved in the markdown.

### Versions

- Mark Text version: v0.16.2
- Operating system: Windows 10 Pro 20H2, 19042.508

**Comment by kzu** [comment]
@Jocs I looked at your original PR introducing the feature, and I can't seem to find any logs or obvious mistakes. Images for local files are properly uploading to https://github.com/kzu/img (it's public even), so I'm thinking something specific to the pasting is involved here. 

Sorry for the direct ping :(

**Comment by ctjlewis** [comment]
Same, if I could just find logs, this would be a lot easier to debug. Did you make any progress on this by chance @kzu? I put in a PR about using OAuth and handling this 100% for the user at #2364.

**Comment by kzu** [comment]
Nope, no fix or workaround :(

**Comment by lichever** [comment]
I met the same issue. Is there any workaround or fix on this bug?

**Comment by ctjlewis** [comment]
> I met the same issue. Is there any workaround or fix on this bug?

No fix. The workaround is to use different software.

**Comment by KoenVanduffel** [comment]
Running into the same issue. I drag and drop the images from explorer to Marktext. It will save them in a local assets folder but not upload to GitHub nor to SM.MS

seems like this package isn't maintained any more. Do you have a suggestion for a different package?

**Comment by Jocs** [comment]
@kzu @all Very sorry for replying now, I will update sm and Github image uploader over the weekend

**Comment by Jocs** [comment]
A PR is submited to fix this issue.

**Comment by WenHv587** [comment]
It hasn't been fixed yet？
