### ISSUE TITLE
Keyboard shortcut for view source code mode not working

### ISSUE THREAD

**Issue by StefanAbl** [marktext/marktext#2348]
### Description

The shortcut to view the source code mode does not work. However when I change it to e.g. Alt+S in the source code it works.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Install marktext
2. Open it
3. Hit CmdOrCtrl+Alt+S
4. Nothing happens

**Expected behavior:**
Source code mode should open

**Actual behavior:**

### Versions

- Mark Text version: v0.16.2 installed from flathub also happens for AppImage version
- Operating system: Pop-OS 20.04 Gnome session with wayland

**Comment by YalandHong** [comment]
Reproduced on my Ubuntu 20.04, which also ships with GNOME desktop.

I have tested this problem using VSCode, another Electron app, following the instructions in [Microsoft's docs](https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-generic-keybindings). The same problem appears.

Related to microsoft/vscode#70471

![CtrlAltSNotWork](https://user-images.githubusercontent.com/52960068/145677136-3f7bf3f3-02b9-4cf8-9375-522190c59811.gif)

**Comment by YalandHong** [comment]
I also found something hilarious. If I press `alt` to make the menu focused, then `ctrl+alt+s` works.
![CtrlAltWorks](https://user-images.githubusercontent.com/52960068/145678048-194f8dfa-c868-4bb4-97b1-42aef1e379c1.gif)

**Comment by YalandHong** [comment]
So I agree with #2370. Please avoid using `ctrl+alt+<something>`.

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2370. You may want to subscribe there for further updates.
