### ISSUE TITLE
Multi line highlight. 

### ISSUE THREAD

**Issue by ajitgoel** [marktext/marktext#2353]
### Question description
I am trying to highlight multiple lines using mark text. Mark text highlights only the first line. What am I missing?

![image](https://user-images.githubusercontent.com/6394444/95602962-456b8080-0a1b-11eb-8c5e-7555fa0c6082.png)

**Comment by KaziFarhanuddin** [comment]
Same problem
![aass](https://user-images.githubusercontent.com/26270542/99924011-836bfc00-2d5e-11eb-9ede-abd32ace8eb0.png)
