### ISSUE TITLE
I am trying to yarn install but failing to get ripgrep from github, I want to know how fellow developers get access to this kind of file?

### ISSUE THREAD

**Issue by xiongmao86** [marktext/marktext#2358]
Any way to get access ripgrep?

While I am trying to `yarn install` I failed to fetch ripgrep from github. I know it's blocked from china, I want to know what options do i have to fetch the resources. This is probably not a marktext related question, but I don't know where else I can ask. Is vpn an good option, since I heard vpn packet would be dropped?

**Comment by fxha** [comment]
Unfortunately, `ripgrep` is limited to ~5000 downloads per hour and IP by GitHub. We had some issues with this on our CI but you can download it with your GitHub access token to "bypass" this. Please also see [mirrors](https://www.electronjs.org/docs/tutorial/installation#custom-mirrors-and-caches) if you have troubles downloading Electron binaries (when you stuck at rebuilding packages).

**Comment by xiongmao86** [comment]
Thanks, @fxha, I have trouble building too. Didn't realize about mirror solution.
