### ISSUE TITLE
How to install it on windows?

### ISSUE THREAD

**Issue by zhangsanlzh** [marktext/marktext#236]
How to install it on windows?

**Comment by xianyunyh** [comment]
windows download link
[https://github.com/marktext/marktext/releases/download/v0.10.21/marktext-setup-0.10.21.exe](https://github.com/marktext/marktext/releases/download/v0.10.21/marktext-setup-0.10.21.exe)

**Comment by Jocs** [comment]
@zhangsanlzh Have you installed windows version now?

**Comment by zhangsanlzh** [comment]
Not yet . I tryed to download the windows version, but it is slowly to death. so I am trying to build the source code ,but i dont know how. It is too difficult. My God!

**Comment by fxha** [comment]
You can follow [these](https://github.com/marktext/marktext/issues/88#issuecomment-377276800) instructions, but Github releases and development dependencies are hosted both on AWS. Meaning this may be not faster than downloading the setup, but maybe you find some mirrors.

**Comment by zhangsanlzh** [comment]
@fxha  It works ,but when i run the code `npm install`，the installation can not go on .
 [77/80] Installing readable-stream@^2.0.0

Do you have some good idea?

**Comment by zhangsanlzh** [comment]
@fxha And I don't know what would be installed after the 77 item . Therefor , If I download them manually , What's the next after 77 item?

**Comment by zhangsanlzh** [comment]
@xianyunyh Wow ,(●ˇ∀ˇ●)  It's amazing!!
