### ISSUE TITLE
Close tabs with middle-click

### ISSUE THREAD

**Issue by Alterae** [marktext/marktext#2361]
### Describe your feature request

When middle-clicking on a tab (pressing the mouse wheel on a mouse, or a three-finger click on most touch pads), the tab should close.

### What problem does this feature solve? [optional]

Makes closing tabs very slightly more convenient.

### Additional context [optional]

While honestly not very important, this feature is standard in most software that uses tabs (such as web browsers) and I have developed a habit of using it.  It's a nice quality-of-life thing.

**Comment by bmvisoky** [comment]
I will work on this.

**Comment by ctjlewis** [comment]
Good feature. Thanks for your help @bmvisoky!

**Comment by fxha** [comment]
Thanks for the suggestion but we already support closing the tab via middle mouse click. Unfortunately, there was a bug in the current version that's was recently fixed and is available in the next release.
