### ISSUE TITLE
Word counter hard to see in Graphite Light theme

### ISSUE THREAD

**Issue by Alterae** [marktext/marktext#2363]
### Description

In the "Graphite Light" theme, it is extremely hard to read the word counter because it displays in a color which contrasts poorly with the sidebar background.  This impairs usability and polish.  While perhaps more of a design issue than a bug, there is no template for design issues.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Use Mark Text on Windows 10 with the Title Bar Style option set to "Custom"
1. Set the theme for the editor to "Graphite Light".
1. Have the sidebar visible.

**Expected behavior:**

The word counter should display in a color that is legible against the background.

**Actual behavior:**

The word counter displays in a color very close to that of the background, and as such is extremely difficult to read.

**Link to an example: [optional]**

![image](https://user-images.githubusercontent.com/27498421/96277390-71de4a00-0f91-11eb-82d7-2529afa0239a.png)
Shown here, the word counter is only very slightly darker than the background, and thus very difficult to make out.

### Versions

- Mark Text version: v0.16.2
- Operating system: Windows 10

**Comment by AltayAkkus** [comment]
I'll try working on it! Seems like a good first issue.

**Comment by bmvisoky** [comment]
@AltayAkkus I didnt see you update this at all so I just took a swing at it. Unsure how to approach this one but I just made the word count the same color as the hamburger menu so it matched, since it is visible with the sidebar, but also without.
