### ISSUE TITLE
Feature Request: GitHub OAuth as sole image upload method

### ISSUE THREAD

**Issue by ctjlewis** [marktext/marktext#2364]
### Describe your feature request
Remove SM.MS option for Image Uploader, default to GitHub with a single "Sign In with GitHub" link, and a description: *MarkText will store your images in a private repo called `marktext-image-uploads`.* The app can simply request the necessary repo permissions and automate the entire image upload setup rather than requiring users to do this manually.

### What problem does this feature solve?
Image uploading is rather hard to get working correctly, and is not very intuitive. This change will make the process much more intuitive and straightforward, and also prevent the need to deal with "Set as Default" logic (took me a few tries to realize that even though I'd set GH auth info, it was still set to SM.MS).

I actually can't get GH auth to work even with a token I know works, and full repo permissions (running Flatpak on Ubuntu). This software is amazing but I think this part of the UX can be improved.

**Comment by Jocs** [comment]
We use PicGo to replace sm.ms, and GitHub uploader will also be removed in the future version, please use PicGo in the next version.
