### ISSUE TITLE
automatically open previous files when starting the marktext

### ISSUE THREAD

**Issue by fhamborg** [marktext/marktext#2367]
### Describe your feature request

Automatically open previous files when starting the marktext. e.g., similarly as done by popular browsers or text editors. For instance, if you close the editor while having three documents A, B, and D open, marktext should automatically open the same three documents once you start marktext again.

**Comment by brainchild0** [comment]
See #988.

**Comment by brainchild0** [comment]
Is there any reason to keep open?

**Comment by fhamborg** [comment]
sorry :-)
