### ISSUE TITLE
I Can Not Input Japanese

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#237]
### Description

I can not enter Japanese, it garbled when reading the MarkDown file written in Japanese.

### Versions

- Mark Text: v0.10.21
- OS: Windows

**Comment by Jocs** [comment]
@keito940 can you send me one example markdown file which written in Japanese, So I can fully understand what this issue described.

ransixi@gmail.com

thanks!

**Comment by keito940** [comment]
I Am Sorry.
I confirmed it later that I could enter Japanese properly.

**Comment by keito940** [comment]
I think that Van Halen.md attached to the e-mail is a file in which garbling of the problem occurs.
But I was able to properly input Japanese after confirming it later.

**Comment by Jocs** [comment]
Maybe it's related to character encoding. This issue is set up first to see if there are users who are experiencing the same problem.

**Comment by fxha** [comment]
@keito940 Do you use CRLF line endings (which is default on Windows with other editors). Then text is formatted incorrect and it's might be a problem like in issue #48 and.

@Jocs  Can you please check line endings.

**Comment by keito940** [comment]
@fxha Do Not Use.

**Comment by keito940** [comment]
@fhxa I am in trouble because it only supports UTF-8, not that kind of thing. (In my environment Japanese fonts were attached.)

**Comment by fxha** [comment]
If it's only a font issue, you could compile the latest master version, which has custom font family support (but master may be unstable) or wait for the v0.11 release.

**Comment by Jocs** [comment]
@keito940 Can you input Japanese now?

**Comment by keito940** [comment]
@Jocs Yes.

**Comment by Jocs** [comment]
@keito940 Ok, I'll close this issue.
