### ISSUE TITLE
Several issues with shortcuts in Linux Mint

### ISSUE THREAD

**Issue by gilbertohasnofb** [marktext/marktext#2370]
First, let me just start by saying how much I love this editor. I just recently discovered it and it has become my favourite Markup editor! 

But as of version 0.16.2, tested in Linux Mint, there are several issues with shortcuts.

1. In general, it would be better to avoid all `Ctrl-Alt-something` shortcuts on Linux. At least with Ubuntu and Linux Mint, many of those are tied to system functions and system shortcuts, e.g.`Ctrl-Alt-t` for terminal, `Ctrl-Alt-d` for showing desktop, `Ctrl-Alt-l` for lock screen, `Ctrl-Alt-Del` for logout, `Ctrl-Alt-Backspace` for restarting the X server, `Ctrl-Alt` with numbers or arrows to move around workspaces, etc.

    Right now, as of version 0.16.2, the shortcuts are quite inconsistent, with some modes using `Ctrl-Alt` shortcuts while Focus Mode uses `Ctrl-Shift`:

    ![image](https://user-images.githubusercontent.com/5700795/97614518-f3ae8880-1a11-11eb-9b03-c156bf0de5a7.png)

    Perhaps using only `Ctrl-Shift` for Linux would be a better approach, making them all consistent, Linux-friendly, and also easier to memorise by not mixing them.

2. Similarly, using `Ctrl-Alt-f` for Find and Replace is problematic and a bit unusual too. Most other text editors I use (Atom, xed, texmaker, LibreOffice Writer etc.) use either `Ctrl-r` or `Ctrl-h` for Find and Replace. Perhaps this change could be considered.

3. Shortcut bug: pressing `Ctrl-Alt` moves the editor to the end of the file unless Soure Code Mode has been enabled before. This is particularly annoying since `Ctrl-Alt-<numbers>` change workspaces on Linux

4. `Ctrl-z`, `Ctrl-Shift-z`, and `Ctrl-f` do not work in Source Code Mode

5. `Ctrl-z` and `Ctrl-Shift-z` are quite buggy, often redo does not redo the last action, and multiple undos is often unreliable too.

I'm happy to do any tests on my side to help with these.

**Comment by cjpoor** [comment]
I would like to confirm and upvote this.

**Comment by YalandHong** [comment]
See [KEYBINDINGS.md](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md) for shortcut customization.

**Comment by fxha** [comment]
Sorry, this issue has been open for a while, but nobody has tackled it yet. There are other open issues on Ubuntu like distros that report this. I think the best way to solve this, is to change the existing bindings to non-system relevant ones. Maybe we need to discuss whether we change Linux bindings only and create OS depending bindings.

**Comment by YalandHong** [comment]
This issue contains too many things and should be split into multiple issues.

For example, shortcut conflict and shortcut malfunction are separate issues. Here are some problems about shortcut malfunction:
1. #781
2. #1321
3. #1864
4. #2399
