### ISSUE TITLE
Mark Text fails to open symlinkes

### ISSUE THREAD

**Issue by gilbertohasnofb** [marktext/marktext#2373]
Mark Text fails to open symlinked files and folders in version 0.16.2 (I'm running Linux Mint 18.3). Trying to open a symlinked file or right clicking on a symlinked folder and trying to open it will result in Mark Text starting but with an empty document. Other text editors are able to open the same files and folders.

**Comment by brainchild0** [comment]
Confirmed, running Mint 20.0. 

Symlink dirs are treated as empty when opened, and are not given in dir list when parent is opened.

**Comment by brainchild0** [comment]
May be root cause of symptoms reported in  #2038.
