### ISSUE TITLE
support PlantUML And Tui.Chart

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#238]
### Description
I would like to suggest the introduction of the library of [tui.chart](https://github.com/nhnent/tui.chart) and [plantuml](http://plantuml.com/). Though it may be ahead like #218, please do not mind.
plantuml and tui.chart are adopted in [this editor](https://github.com/nhnent/tui.editor).

### Versions

- Mark Text:v0.10.21
- OS:Windows 10

**Comment by Jocs** [comment]
Yeah, we have plan to add this feature after version 1.0.0. because we still have a lot basic things need to do before version 1.0.0. for example, `tabs`, `right click context menu`, `side bar` for open the folder, and tabs for open multiple files at the same time.
