### ISSUE TITLE
Can't copy mathematical expressions

### ISSUE THREAD

**Issue by AltayAkkus** [marktext/marktext#2381]
### Description

If you have multiple lines of mathematical expressions, whether as inline or as a block, and you try to copy it, the raw LaTEX is copied, but not the surrounding $ tags.
So if you paste it into another document, you have to add the tags yourself line by line.

- [ X] Can you reproduce the issue? 

### Steps to reproduce

1. Open new document
2. Write multiple lines of mathematical expressions (whether inline or as a whole block)
3. Copy them by dragging your cursor across it and pressing CTRL C
4. Paste them with CTRL V

**Expected behavior:**

It pastes the mathematic expressions fully so that I can just use them after it.
Example: copy  $ \int_{a}^b $ 
Wanted outcome: $ \int_{a}^b$

**Actual behavior:**
it copies \int_{a}^b 

You see the raw LaTEX Code which stands between the $ 

### Versions

- Mark Text version: 0.16.2
- Operating system: Ubuntu 16.04

**Comment by AltayAkkus** [comment]
Found the option to copy as markdown, drag your cursor across it, left click and select "Copy markdown"

I don't really see the use case of having to do this manually but I am still happy :D

**Comment by u0nel** [comment]
I think this should still be open.

**Comment by YalandHong** [comment]
> I think this should still be open.

Possible dup of #1638
