### ISSUE TITLE
Table creation bugged out

### ISSUE THREAD

**Issue by AltayAkkus** [marktext/marktext#2383]
### Description
The GUI which previews your table is bugged out (first line is always full)

- [ x] Can you reproduce the issue? 

### Steps to reproduce

1. Create table thats 2x5 or something like that
2. See the outcome

**Expected behavior:**
![grafik](https://user-images.githubusercontent.com/7849969/98487120-aad0ae00-2221-11eb-9374-d5c99cad5452.png)

**Actual behavior:**
![grafik](https://user-images.githubusercontent.com/7849969/98487109-9e4c5580-2221-11eb-9840-3c4856be22b7.png)

### Versions

- Mark Text version: 0.16.2
- Operating system: Windows 7

(I'll try fixing it, I really love this editor <3)

**Comment by antonfreeman** [comment]
I can work on this issue if you haven't fixed it yet
