### ISSUE TITLE
Inspect MarkText Export Command

### ISSUE THREAD

**Issue by kataras** [marktext/marktext#2384]
Hello marktext team,

First of all kudos for the development of MarkText. I have a silly question, how to debug/inspect the `pandoc` (?) command that marktext running to export a markdown file to pdf? I've tried MARKTEXT_DEBUG=1 and opened the dev tools but I don't see the command text there, can somebody help?

/CC @erentar 

Thanks,
Gerasimos Maropoulos

**Comment by fxha** [comment]
Hi @kataras, we actually don't use `pandoc` to export the document but a self-build exporter based on HTML and Chromiums PDF-engine. It a little bit hacky but the core code is located in [Muya](https://github.com/marktext/marktext/blob/develop/src/muya/lib/utils/exportHtml.js) and some in the [rendering process](https://github.com/marktext/marktext/blob/develop/src/renderer/util/pdf.js). Debugging this is a bit tricky but running Mark Text developement version (`yarn dev`) enables you to change code just in time and export the content as HTML or print it to your terminal.
