### ISSUE TITLE
Global Hide/Show App Shortcut (Overlay Mode)

### ISSUE THREAD

**Issue by bendman** [marktext/marktext#2385]
### Describe your feature request

It would be great to have a shortcut that would toggle visibility of the app in all workspaces. 

### What problem does this feature solve? [optional]

This would allow quick access to notes/documents from anywhere else so we could take and see notes quickly no matter what we were doing. This could work something like [iTerm2's Hotkey Window](https://www.typefloundry.com/1-800-iterm-bling.html).

**Comment by brainchild0** [comment]
Would not a user usually control this visibility through the window manager?

**Comment by bendman** [comment]
@brainchild0 Do the Mac and Windows window managers allow a user to do all of this with one shortcut? I couldn't find a way to do it outside of the application itself. Note that this is different than just "cmd-tab" because it works across workspaces, returns focus automatically, and doesn't require toggling through all other open applications.

#### If the app is visible and focused:
- Hide the application
- Return focus to the previously focused application

#### Otherwise:
- Show the application
- Focus the application window
- Bring the application to the currently visible workspace
- Bring the application window to the top of other windows

**Comment by brainchild0** [comment]
Window managers may vary in capabilities, but it is not an appropriate feature of an application that would attempt to compensate for some lack in certain window managers, as though to equalize the differences. How a user is able to manipulate a window, with respect to   the way you suggest, is determined by the window manager.

**Comment by bendman** [comment]
I can see this isn't a popular idea with you, but I would disagree that it is within the scope of an application to register a global shortcut to activate the application.

- [Dev Docs](https://github.com/egoist/devdocs-desktop#global-shortcut) does
- [Dash](https://kapeli.com/dash) does
- [iTerm](https://iterm2.com/documentation-hotkey.html) does
- [Recollectr](https://iterm2.com/documentation-hotkey.html) does

**Comment by brainchild0** [comment]
Are you referring to a feature such as *minimize to tray*?

**Comment by bendman** [comment]
If _minimize to tray_ does everything I mentioned [here](https://github.com/marktext/marktext/issues/2385#issuecomment-727900373) and is toggleable on/off with a global shortcut, then yes.

**Comment by brainchild0** [comment]
I am trying to identify the feature you are requesting in terms of the applications you gave as examples.

Taking the first example, *Dev Docs*, the documentation indicates the following:

> When closing the window, the app will continue running in the background, in the dock on macOS and the tray on Linux/Windows.

This behavior is called *minimize to tray*, and is appropriate for applications that operate in the background, without user intervention. Mark Text is an editor, and has no such operation. 

Otherwise, I cannot identify any common application feature that matches your request. Certainly, I currently cannot understand how the request makes the application more usable or robust.

**Comment by bendman** [comment]
> I cannot identify any common application feature that matches your request.

All of the applications that I linked above have a feature that does exactly what I am suggesting here, and when possible (like with DevDocs) I linked directly to the point in the documentation that mentions the global shortcut. This doesn't just "minimize to tray" or "run in background", but actually provides a global shortcut to toggle the application visibility and focus on and off. All of these applications involve frequent user interaction. The last application, Recollectr, is even a note taking tool that supports markdown, similar to Mark Text.

> I currently cannot understand how the request makes the application more usable or robust.

This seems like it's becoming a disagreement of opinion on what makes the application more usable. Regardless of whether you agree, do you understand how a global application shortcut for a terminal (like available in many linux/macos terminals like iTerm) is useful? Or a shortcut to access a documentation tool (like DevDocs or Dash) or a shortcut to access your note taking application (like Recollectr does and MarkText could)?

I am currently running my fork locally and I use this feature dozens of times a day. When I am in the middle of a video call I can use the shortcut to toggle MarkText, write a note about the meeting, then hide MarkText again. This shortcut always accesses MarkText directly. I use it in interviews, meetings, while coding, researching, etc because it is much faster and simpler than Alt-Tab menus that always change the number of presses depending on application recency.

The feature _is_ objectively useful, semantics of naming aside. The questions are: whether you accept pull requests for features, if this is a feature you accept in an application that can be used for note taking, and whether this implementation is acceptable.

**Comment by brainchild0** [comment]
> This seems like it's becoming a disagreement of opinion on what makes the application more usable. 

I think what would help the discussion is a use case, preferably one familiar to a typical user of the application.

> Regardless of whether you agree, do you understand how a global application shortcut for a terminal (like available in many linux/macos terminals like iTerm) is useful? 

Yes. But a terminal application may be seen by many as more fundamental than a note taking application. More importantly, I would note that on Linux desktops, the terminal shortcut is provided by the desktop environment, and works equally well regardless of whether any terminal application is currently resident in memory.

> Or a shortcut to access a documentation tool (like DevDocs or Dash) or a shortcut to access your note taking application (like Recollectr does and MarkText could)?

Yes, I think so, but it seems as though these tools are largely built on the feature of rapid access through the keyboard. Mark Text is a classical editor. The use case is opening the application, then opening an existing document or beginning a new one, saving the document, and then, finally, exiting. 



> The questions are: whether you accept pull requests for features, if this is a feature you accept in an application that can be used for note taking, and whether this implementation is acceptable.

I don't make such decisions. I am only offering my opinion. The core maintainers do accept PRs generally, and which ones are outside my discretion. My view is that this feature needs further review to determine whether and how it might most productively be included in the application, but my view belongs to no one but to me.

**Comment by brainchild0** [comment]
(@bendman: Note that your link for Recollectr points to the wrong site. You might edit the post to correct.)

**Comment by bendman** [comment]
> I think what would help the discussion is a use case, preferably one familiar to a typical user of the application.

It could be that I'm a "non-typical" user, because I use it throughout the day to take notes and always want quick access to my note taking tool. This is why I made it an optional feature that is disabled by default. This is why the "rapid access through the keyboard" is a useful feature to me and possibly others.

As far as I can tell, if you don't want to use this feature then this pull request doesn't impact you, because it is disabled by default. It adds a minimal amount of code to support the feature, but it isn't a large change. If you _do_ want this feature, it _isn't possible_ without it being built into the program because window managers don't support this feature in a way that can be applied to any application.

That being said, if you _do_ know of a way to get this functionality in Windows, MacOS, and the common Linux windows managers, that would be a very helpful alternative, but I couldn't find it.

> (@bendman: Note that your link for Recollectr points to the wrong site. You might edit the post to correct.)
Thanks, fixed!

**Comment by brainchild0** [comment]
> As far as I can tell, if you don't want to use this feature then this pull request doesn't impact you, because it is disabled by default.

This observation unfortunately is not adequate, in my view, to support a conclusion for including a feature.

> That being said, if you _do_ know of a way to get this functionality in Windows, MacOS, and the common Linux windows managers, that would be a very helpful alternative, but I couldn't find it.

Might you simply install a keyboard shortcut with the desktop environment?

**Comment by bendman** [comment]
> This observation unfortunately is not adequate, in my view, to support a conclusion for including a feature.

Can you explain why? I agree that useless code shouldn't be added, but this is useful to me at least, and I think others would find it useful as well.

> Might you simply install a keyboard shortcut with the desktop environment?

The question is how? I have tried and it doesn't seem possible. On MacOS I have even tried writing custom automator script to handle this, and it doesn't have the same abilities, and that is just _one_ window manager.

This isn't some huge infrastructure that is being built; it is a simple application. While I agree that modern window managers _should_ be capable of this, they aren't, and I like to take the open-source approach of solving a problem where possible. This is the point where it is possible.

Do you _at least_ concede the undeniable fact that this is useful for me? I feel like I'm just getting blocked by principle and opinion here with no attempt at understanding.

**Comment by brainchild0** [comment]
> Can you explain why?

Adding features without adequate discretion leads to [*feature bloat*](https://en.wikipedia.org/wiki/Software_bloat), which is harmful for both maintainers and users.



> The question is how?

If it's not supported natively on your desktop, maybe an add-on offers the functionality.



> Do you _at least_ concede the undeniable fact that this is useful for me?

Of course no one says the feature is not useful to you if you say it is. But you are requesting including a feature in a public code base of an application used widely among the public. You're experience is not the only one that matters.

>  I feel like I'm just getting blocked by principle and opinion here with no attempt at understanding.

I am trying to understand the the best argument for including the feature. I have not heard any that convinces me that users widely would benefit from this feature, which would add to the total number of items in the preferences view as well as the size of code that developers must then maintain. 

You are free a more thorough argument, if you have one. Please note that I am not blocking anything, only offering my opinion. I can't accept your PR even if I wanted to do so.

**Comment by bendman** [comment]
My argument is that:

1. this feature is useful for me, would likely be useful to others
2. the functionality isn't possible without it being in this code

I have researched both of these points and they seem to be true, because other similar tools include this feature (point 1) and I have tried many other ways to get this to work without modifying the application code, including custom scripts and 3rd party addons, and I haven't found one that works (point 2).

**Comment by brainchild0** [comment]
> My argument is that:
> 
> 1. this feature is useful for me, would likely be useful to others
> 2. the functionality isn't possible without it being in this code
>   I have tried many other ways to get this to work... and I haven't found one that works.

Responses:

1. In my opinion, it would be helpful for you to _justify_ the claim that the feature would be useful to some broad demographic of users of the application, rather than simply _making_ the claim.
2. Sorry you haven't found a solution. It would surprise me that no addon application is available in macOS to launch an application from a desktop keyboard shortcut. 

    Of course not having found one and none being available are not the same. Perhaps someone reading knows how it might be accomplished, and might post a suggestion.

**Comment by bendman** [comment]
Okay, thank you. I have provided ample justification and done ample research into alternatives, so I am just leaving this here and will use my fork for now.

**Comment by fxha** [comment]
Thanks @bendman for the idea and PR. I think this is an OS feature and shouldn't be directly included into Mark Text. Maybe we can support this via plugins later or on demand.

**Comment by MostHated** [comment]
The first thing I noticed that was missing was a global hide/show of the application window, which I really wish this had. I have tried dozens of applications, and the ones that have the features I want don't have a global hide/show, the ones that do have it, are missing other major features. Just can't win.
