### ISSUE TITLE
Can't initiate

### ISSUE THREAD

**Issue by naivenaive** [marktext/marktext#2387]
### Question description
I follow the instruction in https://github.com/marktext/marktext/blob/develop/docs/dev/BUILD.md to start developing. When I run 'yarn install', It stopped and can't move further.

$ node .electron-vue/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[###########################################################################################################] 1809/1811 

How to solve it?

**Comment by fxha** [comment]
Thank you for reporting the issue. This might be an issue with your internet connection (VPN, restricted internet, etc). You could try `yarn rebuild` to redownload all files or use a different CDN.
