### ISSUE TITLE
Continuous integration migration (CI)

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2389]
### Problem

Travis CI closes the `travis-ci.org` service for open-source projects on December 31, 2020 and we have to migrate to `travis-ci.com`. As far as I know, the new plan will be limited to 1000 build minutes per month and we could also migrate to another service that provides a better plan as we had a few issues with Travis CI such caching etc.

#### Solutions

1. [Migrate](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) from `travis-ci.org` to `travis-ci.com` with limited plan (1000 build minutes per month).
2. Use different CI for Linux and macOS such CircleCI or GitHub Actions.

@Jocs I think we should first migrate to `travis-ci.com` and then take a final decision how to continue.

**Comment by Jocs** [comment]
>Use different CI for Linux and macOS such CircleCI or GitHub Actions.

GitHub Actions is a good option, but as you said, we can migrate to `travis-ci.com` first.
