### ISSUE TITLE
Parser treats * and + lists as - list

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#239]
### Description

Mark Text converts `*` and `+` lists into `-` lists. I think this is a parser/html to markdown parser bug, because CommonMark and GFM support `*`, `-` and `+` lists.

### Steps to reproduce

1. Write list with `*` or `+` and type some text
2. go to source code mode

**Expected behavior:** [What you expected to happen]

```
* foo
```

or 

```
+ foo
```

**Actual behavior:** [What actually happened]

```
- foo
```

### Versions

- Mark Text: v0.10.21

**Comment by Jocs** [comment]
I think it's better to let user to choose his prefer list begin marker in the user preference?

user can set the prefer list marker in the user preference file. then Mark Text will use the `list marker` in user preference file when output the markdown file.

**Comment by Jocs** [comment]
now we set `-` as the default list item marker.

**Comment by fxha** [comment]
Sounds great, but if the user wants to open files with different lists styles, we got a problem and/or he has to change it every time. The easiest is to hack into marked.js.

**Comment by Jocs** [comment]
>we got a problem and/or he has to change it every time. 

why need to change every time? we don't render marker in the text editor, and only the list marker when out put markdown file.

>The easiest is to hack into marked.js.

How to to this hack?

And I have another idea:

If the user open an existed markdown file, we save the marker of each list into the `block`.

```javascript
block.marker = '-'
block.type = 'ul'
```

 If it is a newly created list by input `* text`. we use the marker entered by the user, and if it is a list created through a shortcut, use a user-configured marker in user preference configure file.

If it is a newly created file, basically the same as above.

**Comment by fxha** [comment]
> How to to this hack?

You already written the "hack" :smile:

**Comment by Jocs** [comment]
@fxha haha, Then set my plan above?

>If the user open an existed markdown file, we save the marker of each list into the block.
