### ISSUE TITLE
Mark Text doesn't open link to non markdown files

### ISSUE THREAD

**Issue by raphaelhuleux** [marktext/marktext#2396]
Hi, 

In my markdown files, I have link to pdf files written as
`[name](/path/to/pdf.pdf)`. Those links are recognized by when I click them, nothing happens. In Typora, clicking on those links open them in my default pdf reader app.

**Comment by brainchild0** [comment]
Do you want a relative link to appear in a PDF file?

**Comment by raphaelhuleux** [comment]
I am not sure what you mean by this. The expected behaviour would be that when clicking on the link (cmd + click, more precisely), the pdf file would be opened in the default app.

**Comment by brainchild0** [comment]
Perhaps your expectation is accurate for links given as a fully-qualified URL to a web page. Your example takes the form of a path to a file on your local system, whereas PDF documents are generally, and by design, standalone, or self contained. 

I would not personally expect any PDF to feature a link that is relative, or as in the form of your example (and despite my earlier incorrect characterization) absolute but local to some system.

One question is whether you do get the desired behavior if you use a full URL (e.g. `https://www.github.com`. (A second question whether,  if the first answer is affirmative, then  whether  you really do believe that a bug or useful enhancement has been identified.)

**Comment by raphaelhuleux** [comment]
Hi,

The behavior I’m describing is the default one currently in Typora, and this would be expected given that links to markdown files are opened on Mark Text too (cmd + click on a ‘[name](nametomarkdown.md)’ does open the file).

Maybe I’m not describing well what I’m thinking but I am not referring to opening the PDF file in Mark
text. Simply opening the linked file in the default PDF app.

Raphaël

**Comment by brainchild0** [comment]
> Simply opening the linked file in the default PDF app.

I think I understand, but it appears to me that for this feature, separate from what Typora might do, whether by design or accident, the current behavior might be more desirable. If you attach a PDF file for example to an e-mail message, then the local link is not available to the recipient. PDF documents are by design generally standalone, for example, with respect to media being embedded, and similarly, I tend to expect that links will be limited to fully-qualified URIs.

Perhaps describing a full use case  would bring better light to the subject.

**Comment by raphaelhuleux** [comment]
I understand your point but obviously we can’t attach PDF files to markdown files, so the only option is to insert path to files. Also, what is the point of being able to adding path to files (which is standard markdown, I believe) if you can’t open them?

Raphaël

**Comment by brainchild0** [comment]
Maybe I have misunderstood. Are you referring to issues in PDF documents generated by the application from Markdown, or links to PDF documents in the Markdown editor?

**Comment by raphaelhuleux** [comment]
Links to PDF documents in the Markdown editor. Maybe I'll be clearer if I explain my workflow more precisely:
- I have a list of markdown files, connected between themselves with links `[title](title.md)`. 
- When I want to make a reference to a certain pdf file I just read, I also create a link to those files as such `[name_pdf](path/to/pdf.pdf)`. 
Right now, if I click in Mark Text on a link to a markdown file, this file is opened in Mark Text. If I click on a link to a pdf file, nothing happens. I would to change this behavior to open the file in a pdf app.

**Comment by brainchild0** [comment]
I see. Unfortunately, I misunderstood the original problem.

However, I am still wondering whether many of the same observations are relevant. Creating a Markdown document that is tied to the layout of a local system seems very unfamiliar to me, even if Typora allows the specific behavior.

**Comment by fxha** [comment]
@raphaelhuleux Thanks for creating this issue. There's currently no handler implemented for local relative paths but feel free to create a PR, the code is located [here](https://github.com/marktext/marktext/blob/8d8465417bf437df6f16944dc3973ec9f76657d1/src/main/menu/actions/file.js#L392).

I'm thinking of the following: Open the local relative path iff the document/file is saved and it's safe to open the file. We have to consider that we might open a bad path such as a script or launch an application.

**Comment by brainchild0** [comment]
> There's currently no handler implemented for local relative paths but feel free to create a PR, the code is located [here](https://github.com/marktext/marktext/blob/8d8465417bf437df6f16944dc3973ec9f76657d1/src/main/menu/actions/file.js#L392).

Isn't this issue primarily about *absolute* paths? (Or are you using *relative* in the loose sense, of *local*?)

**Comment by fxha** [comment]
Sorry, I was thinking about relative images before but it doesn't matter. If we find a valid path that isn't a URL or markdown file, try to open it with the default application. Relative paths are often used in blog pages and absolute if you manage your notes with Mark Text. It shouldn't be to hard to implement this but we need take care of bad paths.

**Comment by brainchild0** [comment]
> Sorry, I was thinking about relative images before but it doesn't matter. If we find a valid path that isn't a URL or markdown file, try to open it with the default application. Relative paths are often used in blog pages and absolute if you manage your notes with Mark Text. It shouldn't be to hard to implement this but we need take care of bad paths.

I feel cautious about giving the same behavior to absolute links versus relative. Absolute links seem to erode the principles of Markdown.

**Comment by FrancoisEx** [comment]
This feature would be very helpful. I use Markdown notes to organize my work and the possibility to link to local files is quintessential for that. It is easy to do in Typora, impossible yet in Mark Text. I strongly support the development and the integration of this feature request.
An alternative is to use Obsidian.

**Comment by xiongmao86** [comment]
I would like to take a stab,  but I am not sure what to do when `dirname` is empty? Show a message box or simply do nothing?
