### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [marktext/marktext#24]
![logo-example](https://user-images.githubusercontent.com/36993664/37568967-6a8ff536-2aed-11e8-9601-3a91a51b30ae.jpg)

Hi, I have studied your work and I think a new logo will make you more visible. I designed a logo for you, I hope you like it and you want to use it. If you contact me here or from doganzr@gmail.com I can give you all the formats of the logo. If you want a change please specify.

![marktext-logo](https://user-images.githubusercontent.com/36993664/37568973-78cc9f00-2aed-11e8-83ef-cadc5af9328b.jpg)

**Comment by Jocs** [comment]
@Yasujizr thank you for your great work, I'll contact you by email, If I adopt your logo design finally, I will mention it in README file, Thank you!

**Comment by Ldoppea** [comment]
Hi,

Talking about design: The app icon is invisible in Windows 10 because taksbar is black in this version and as the app icon is also black with transparent background.

So if you plan to re-design it, it would be a good opportunity to fix this 😃

**Comment by Jocs** [comment]
@Ldoppea Yes, Mac also has this problem when the background is black.
