### ISSUE TITLE
Change math delimiters to standard MultiMarkdown

### ISSUE THREAD

**Issue by raphaelhuleux** [marktext/marktext#2401]
Hello,

Right now, a math block can be created with this syntax:

```

$$
\sum_{t=0}^{\infty} \beta^t u(c_t)
$$

```
But the standard markdown (see http://fletcher.github.io/MultiMarkdown-5/math.html) is defined as

```
$$\sum_{t=0}^{\infty} \beta^t u(c_t)$$
```

or
```
\\[
\sum_{t=0}^{\infty} \beta^t u(c_t)
\\]
```

Would it be possible to add the possibility to choose the math delimiters so that the markdown files created in Mark Text are usable in other apps who follow the MultiMarkdown standard, such as iA Writer?

**Comment by Jocs** [comment]
we support inline and display math.

inline math `$ a \ne b$`

display math

```
$$
a \ne b
$$
```
