### ISSUE TITLE
VSCode Plugin

### ISSUE THREAD

**Issue by cpsauer** [marktext/marktext#2404]
Another feature request, but only because I'm loving it so much:

Any chance some subset of the functionality could make it's way into a VSCode editor? It'd be so sweet to have this for editing and viewing markdown docs while navigating through a codebase.

**Comment by fxha** [comment]
Thanks for your suggestion but this is out of the scope of the project. If you need a standalone version you could try [Muya](https://github.com/marktext/muya), the core of Mark Text.

**Comment by anishmittal2020** [comment]
@cpsauer May I ask you what feature you are looking for in vscode that is available in marktext but not in vscode?

**Comment by cpsauer** [comment]
Sure! I find Marktext's WYSIWYG a fantastic experience both for reading and for editing markdown. Markdown files are often interspersed in a codebase as higher level documentation. For that documentation, usually you read it first (and thus want it renderer) and then want to make changes in context as you go. That'd be a great match for Marktext's WYSIWYG interface!

(AFAIK, VSCode has only an updating preview, split screen from the file itself, and blocking easy editing of code in parallel. There are some solid plugins to help editing make down source, but Marktext would be just so much nicer: Read docs, beautifully rendered. Update them in context in the same window. Ahh.)

**Comment by cpsauer** [comment]
And @fxha, a much belated thanks, both for the grace of your answer and for this wonderful project.
