### ISSUE TITLE
Export to html

### ISSUE THREAD

**Issue by SorinGFS** [marktext/marktext#2406]
### Question description

Marktext is awesome tool, but I didn't quite undestand how to setup a workflow with it! 
So, we edit `md files`, everything looks nice, then we need to export to html each file piece by piece by entering the export details every single time? This for me looks like a death in pain over and over again! 
Or, maybe there is something I missed here, is there another way to work with `marktext` ?

**Comment by YalandHong** [comment]
Unfortunately, currently there may not be such features coverting multiple MDs to HTMLs at once.

Related issues: #1143
Please consider upvoting and tracking them. Thanks.
