### ISSUE TITLE
Shift+Down gets stuck 

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#241]
### Description

When you select some text and use `Shift` + `Down Arrow Key` to deselect part of it, it can get stuck at certain places

### Steps to reproduce

1. Type 
```
`Hello`World
Hi up there
```
2. Place your cursor after the word `Hi` and before `up`
3. Hold down `Shift`
4. Press the right arrow key
5. Press the up arrow key. It should look like:
![image](https://user-images.githubusercontent.com/10220080/39635572-31590a46-4fbe-11e8-8b10-26a84d7860b8.png)
6. Press the down arrow key
7. Press the down arrow key
8. Press the down arrow key
etc.

**Expected behavior:** That the selection doesn't get stuck

**Actual behavior:** The selection got stuck

### Versions

- Mark Text: v 0.10.21
- OS: Windows 10

**Comment by Jocs** [comment]
>Press the down arrow key
@stefnotch Do you mean Mark Text need select `up there` when press the down arrow key?

**Comment by stefnotch** [comment]
@Jocs The selection gets stuck. It should stop selecting `World` and start selecting `up there`. Here is a GIF of what Marktext does. At the end, I'm spamming the down arrow key, but nothing happens.:
![2018-05-05_11-27-24](https://user-images.githubusercontent.com/10220080/39661762-593491ea-5057-11e8-9146-f6ef9af363f2.gif)

**Comment by aladagemre** [comment]
A similar issue: Shift+down does not select but just moves the cursor, works like only pressing down. Shift+up does not move the cursor. You have to Shift-left until selecting whole line and spanning over the line above and then you can use Shift-up for selecting the rest.

**Comment by Jocs** [comment]
>The selection gets stuck.

@stefnotch Do you mean you can not cancel select `World` by press `shift + ArrowDown`? Can you still reproduce this issue in the latest version 0.14.0?

**Comment by stefnotch** [comment]
Yes, I can still reproduce it.

For the record, the expected behaviour looks like this:
![2019-04-20_14-53-09](https://user-images.githubusercontent.com/10220080/56457504-099eb000-637c-11e9-82fb-c35f4ab81773.gif)
