### ISSUE TITLE
Same Shortcut Issue

### ISSUE THREAD

**Issue by tux543** [marktext/marktext#2415]
Hi Mark Text Team,
I am a Chinese user by using Zhuyin input method, which is one of the main input method in Traditional Chinese. 
Normally, I have to add comma "，" to show a pause in the sentence a lot.
Unfortunately, the comma "，" shortcut is "Ctrl+comma" ,which is exactly the same shortcut as preference.
Each time I type comma"，" ,the preference window pop out. 
That makes Mart Text hard to edit any file in Zhuyin input and makes me frustrated.
Is there any possible that users can custom and remap the shortcut?

**Comment by YalandHong** [comment]
Dup of #2599. See [KEYBINDINGS.md](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md) for shortcut customization.

FYI, try to add this to your `keybindings.json`. An empty string disables a shortcut.
```json
{
  "file.preferences": "",
}
```
Here's the result:
![2021_12_04_09_18_18](https://user-images.githubusercontent.com/52960068/144691356-eb4c4081-cbf2-46ee-b982-85c69e05eeb9.png)
