### ISSUE TITLE
New Future:Math Block

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#242]
### Description
Although Mark Text certainly allows you to enter mathematical expressions, it is a difficulty that you can not enter mathematical expression codes that span multiple lines.
So, why do not you include a math block that can contain mathematical expression code over multiple lines like Typora?

exapmle:

```markdown
$$
\frac{3}{4}
\times
\frac{5}{2}
=6\frac{1}{2}
$$
```

### Versions

- Mark Text:v0.10.21
- OS:Windows 10

**Comment by fxha** [comment]
That' true, the display math preview in editor mode seems broken with new lines. 

@Jocs Display math not working on master :/ Should I open another issue for that?

**Comment by Jocs** [comment]
@fxha pls open another about this， thanks！

**Comment by fxha** [comment]
> @Jocs Display math not working on master :/ Should I open another issue for that?

OK I was wrong, this is a issue regarding multiline display math blocks.

**Comment by cbrasser** [comment]
Might be related to this one, I cant get the $$$$ to work inline which would be very useful instead of having a new line for a short block of math

**Comment by fxha** [comment]
@cbrasser You can use inline math `$ math $` in a text/table/list etc. Display math (`$$ math $$`) can not be nested.

**Comment by JamieCorkhill** [comment]
@Jocs Has this been fixed yet? I'm using version 0.14.0, and I have text wrapping issues with Math Blocs and PDF Export:

Editor:

![MarkText Issue](https://user-images.githubusercontent.com/28678855/57564057-9c26e380-736b-11e9-9afc-f171e7f725e9.PNG)

PDF Export:

![MTPDF](https://user-images.githubusercontent.com/28678855/57564068-c24c8380-736b-11e9-8c07-858d914dd4bf.PNG)

HTML Export does not cause the same problem.

Thanks.
