### ISSUE TITLE
Zoom In Ctrl + F not jumping correctly

### ISSUE THREAD

**Issue by samuel-lucas6** [marktext/marktext#2424]
### Description
When using Window => Zoom In, I've noticed that find (Ctrl + F) is unreliable because the up/down arrows don't jump to the searched term. Instead, they move the page marginally up/down. However, find works fine when not zoomed in.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Go to Window => Zoom In and click it three or four times.
2. Use Ctrl + F and search for a term you've written.
3. Press the up/down arrows or Enter on the keyboard to move to the location of the next searched term.

**Expected behavior:**
The editor should jump/scroll to the location of the searched term.

**Actual behavior:**
The editor position scrolls marginally but not to the location of the searched term.

**Screenshot:**

![MarkText Ctrl F](https://user-images.githubusercontent.com/63159663/101476981-78ac8c00-3946-11eb-84d5-98b63dec351b.gif)

### Versions
- Mark Text version: v0.16.2
- Operating system: Ubuntu

**Comment by sammaddens** [comment]
I have the same issue on my Windows machine. This is caused by the high DPI scaling (see #1775).
