### ISSUE TITLE
Jumping on a random line when deleting code

### ISSUE THREAD

**Issue by ghost** [marktext/marktext#2428]
### Description

When deleting code block in python, after one line is deleted, the selector jumps to a random point in the line above instead of the end of the line.
### Steps to reproduce

1. Insert a python code block
2. Write a random code:
x = 0
for x in range(0,2,10):
print(x)
3. delete the last line of code by pressing backspace until you delete the whole line.

**Expected behavior:**

when the line is deleted, the selector must jump to the end of the second to last line

**Actual behavior:**

the selector becomes located after the letter g in the word 'range', so if i pressed backspace again it will start deleting from there and not from the end.

### Versions

- Mark Text version:  0.16.2.2126
- Operating system: windows 10

**Comment by Undeio** [comment]
#### Yeah, I also found a similar problem.

no picture, no truth.

![pic](https://tva1.sinaimg.cn/large/0081Kckwly1gln82craqgg30rs0c015q.gif)

##### Versions
- Mark Text version: 0.16.2
- Operating system: macOS 10.14.6

**Comment by YalandHong** [comment]
Dup of #2153
