### ISSUE TITLE
Mark Text change indent code block to fenced code block unexpectly

### ISSUE THREAD

**Issue by Lammmm** [marktext/marktext#243]
### Description

从网上下下来的md文件，用marktext打开后会自动加入一些符号（貌似是对md文件的内容进行了格式规范化），但是我不想要它加入这些东西

打开是下面这样，左边是原来的文件，右边是marktext自动添加的一些东西
![image](https://user-images.githubusercontent.com/23132744/39661865-ab77b908-508b-11e8-9a4b-9b400d0bcf8c.png)

Mark Text changed indent code block to fenced code block unexpectedly

from

```markdown
    code
    code
```

to

```markdown
\```
code
code
\```
```

**Comment by Lammmm** [comment]
用的是最新版的marktext

**Comment by Jocs** [comment]
你是指最开始的

\```
设计
写作
\```

这儿的修改吗？

这是因为文字如果之前留有四个或以上空格，将被视为代码块。marktext 将其转化成了 fenced code block。

这是代码块的两种 markdown 语法。

marktext 以后会在这写地方做一些优化，尽量不去破坏之前的 markdown 语法。但是现在还没法办到。

**Comment by Lammmm** [comment]
好的，谢谢
