### ISSUE TITLE
Ctrl+F not working on master

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#244]
### Description

The title already says everything.

1. Both `startParagraph` and `endParagraph` can be `null` ([ref](https://github.com/marktext/marktext/blob/3a3a3b54a557415baa82ad77c12cd5ee7424d1ee/src/editor/selection.js#L771)).

```
let startParagraph = findNearestParagraph(anchorNode)
let endParagraph = findNearestParagraph(focusNode)
```

2. The `Crlt+F` error occurs because we try to access `null` object:

https://github.com/marktext/marktext/blob/3a3a3b54a557415baa82ad77c12cd5ee7424d1ee/src/editor/selection.js#L792

### Steps to reproduce

1. Start Mark Text and press `Ctrl+F`

### Versions

- Mark Text: master (2ebf8c8)

**Comment by Jocs** [comment]
@fxha I can not always reproduce this issue, This error happens occasionally.

**Comment by fxha** [comment]
When I press `Ctrl+F` it always crashes.

**Comment by Jocs** [comment]
yeah, that way you described will always reproduce this issue.

**Comment by fxha** [comment]
@Jocs  Update first comment.

The problem is that we have to return a cursor, but I think you can handle this :smile:

**Comment by Jocs** [comment]
Ok, I'll handle this issue.

**Comment by Jocs** [comment]
@fxha 😢 I can not reproduce this issue again.

I run npm run dev

then I press `ctrl + f`

but no error happened?

**Comment by fxha** [comment]
Yes sure.

**Comment by Jocs** [comment]
@fxha I think this issue can be closed?
