### ISSUE TITLE
when it export as a pdf, it can't classify shift+enter and enter (two different types of line feeds)

### ISSUE THREAD

**Issue by Anditty** [marktext/marktext#2446]
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text version:
- Operating system:

**Comment by fxha** [comment]
Mark Text renders a soft line break as break in the editor and otherwise as space, according to markdown specification:

> A softbreak may be rendered in HTML either as a line ending or as a space. The result will be the same in browsers. In the examples here, a line ending will be used.
