### ISSUE TITLE
What preperations should I do if I want to contribute my code for this project?

### ISSUE THREAD

**Issue by zhangsanlzh** [marktext/marktext#246]
What preperations should I do if I want to contribute my code for this project ?
What dev softwares should I install ?
Node.js ? Electron ? And what something else?

**Comment by Jocs** [comment]
For issues that are marked as bugs, then discuss the solution in the issue. If the final solution is passed by the marktext team members, then the PR can be submitted.

I hope that I can see you PR next time!
