### ISSUE TITLE
when add PicGo-Core plugin?

### ISSUE THREAD

**Issue by vx642620018** [marktext/marktext#2460]

**Comment by vx642620018** [comment]
If Mark Text can add picgo-core，it will be perfect. Because the sm.ms and github sometimes cannot work well

**Comment by tabris233** [comment]
I have a version that supports PicGo based on develop, need open picgo-server.(should only work on Mac/Linux, (Forgive me for not knowing how to write front-end 
))。

If you want to use it, you can download it from [here](https://github.com/tabris233/marktext/releases/download/picgo_support/Mark.Text.app.zip) or compile it with this [branch](https://github.com/tabris233/marktext).

**Comment by YalandHong** [comment]
According to #2031, this may be via plugins when MarkText supports plugins.

**Comment by Jocs** [comment]
A PR is submited.
