### ISSUE TITLE
Remember opened sidebar and opened folder

### ISSUE THREAD

**Issue by xor-gate** [marktext/marktext#2467]
### Describe your feature request

* Running Mark Text version 0.16.2
* When I enable the view of the sidebar it is not remembered on next open
* Opened folder in sidebar is not remembered and I need to open it every time I open the app

### What problem does this feature solve?

Extra actions to view the sidebar and open a folder

**Comment by YalandHong** [comment]
Possible dup of #386, which has been merged into #998

*Please close this issue if it helps*. There're way too many duplicate issues in this repo. Thanks!
