### ISSUE TITLE
Flickering while writing last line in Windows 10

### ISSUE THREAD

**Issue by set92** [marktext/marktext#2470]
### Description

I'm not sure if calling it flickering, so I couldn't search it very well, I think I saw something similar but in horizontal (#2151). But basically when you are writing the last line of a document the view tends to go up and down instantly or it does it in few ms, because in the video it looks like it takes a lot of time but in reality is shorten. So I suppose this is a common bug or not sure what I'm doing for it to appears only to me.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open new tab
2. Write until you fill the height of your window of marktext
3. While you write the last line you will notice some flickering.

**Expected behavior:**

No flickering.

**Actual behavior:**

It kind of flickers when you are writing the last line, like it is jumping to some previous part of the document and quickly returning.

**Link to an example:**

In a real document: https://i.imgur.com/2V4QlgB.gif
In a new document: https://imgur.com/SppzURi (A little worse quality because of how I recorded it)

### Versions

- Mark Text version: 0.16.2
- Operating system: Windows 10 20H2 (19042.630)

**Comment by ferozen** [comment]
I'm also having the same issue. Just installed the app and am having the exact visual glitch, though it isn't the last line of text visual on the document for me. 

I've noticed that it happens after the page auto adjusts to be focused on the last line. See the video below, I initially click on the line I want to edit and the page shifts upwards. After that happens, it starts to glitch. When I move the page to where it won't adjust, it doesn't seem to do it anymore. 

https://imgur.com/a/WKLDvpV

**Versions**
- Mark text 0.16.3
- Windows 10 Pro 1909 (build 18353.1316)

**Comment by markmillerdev** [comment]
I am experiencing this too with v0.16.3 on a Mac

**Comment by r0bc94** [comment]
I'm also experiencing this behavior. 

Version: v0.16.3 on Windows.

**Comment by lu-st** [comment]
I'm having the same issue.

Version: v0.16.3 on Windows 10 Pro 20H2.

On my Debian machine it seems to be fine.

**Comment by consal** [comment]
Same issue, macOS Big Sur

**Comment by pixl-fox** [comment]
Same issue. Win10, Mark Text version v0.16.3.

**Comment by JamesFrederik** [comment]
same issue, Win 10, Mark Text v0.16.3

**Comment by InaudibleParadox** [comment]
Experiencing the same issue on W10 with v0.16.3.

**Comment by JohnnyGo-chn** [comment]
I'm also experiencing this behavior.

Version: v0.16.3 on MacOs 11.6

**Comment by YalandHong** [comment]
There's also a video from #2516, recording and describing this issue in detail:
https://www.youtube.com/watch?v=DDd_nKN0cZ0

**Comment by XingrunLi** [comment]
same issue, Win 10 21H2, Mark Text v0.16.3

**Comment by GambitFPS** [comment]
Same issue.

**Comment by Marius-Muis** [comment]
I am experiencing the same problem. The issue has been open for more than a year? Yikes...
