### ISSUE TITLE
Internal link to go to some file part by the id

### ISSUE THREAD

**Issue by DesobedienteTecnologico** [marktext/marktext#2474]
### Describe your feature request
Use of internal links like `[Go to Python cheatsheet](#python)` or `<a href="#python">Go to Python cheatsheet</a>` to go to determinate div inside the same file.

### What problem does this feature solve? [optional]

1. Helping making cheatsheets in amazing way.
2. Helps with large documents.

**Comment by YalandHong** [comment]
Possible dup of #2469

In order to reduce duplications, please close this issue and report your problems there.

Besides, please don't open the same issue twice.

Thanks!

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2469. You may want to subscribe there for further updates.
