### ISSUE TITLE
the black background disappeared when export PDF in dark theme

### ISSUE THREAD

**Issue by CSUwangj** [marktext/marktext#248]
### Description

导出黑色主题的pdf后，从第二页开始样式不对

### Steps to reproduce

1. 打开任意一个转成pdf超过2页的.md文件
2. 选择dark主题
3. 导出为pdf

**Expected behavior:** 所有页面都是黑色主题

**Actual behavior:** 从第二页开始样式出错

**Link to an example:** ![example](https://i.loli.net/2018/05/06/5aef00d3a2727.png)

### Versions

- Mark Text: v 0.10.21
- OS: Windows10

**Comment by Jocs** [comment]
@CSUwangj thank you for your reporting this bug, and this will be fixed in the next released version.
