### ISSUE TITLE
Jump to the top when typing

### ISSUE THREAD

**Issue by wu-yue-yu** [marktext/marktext#2487]
### Description

When I type something (at anyplace, anytime, it will happen), especially when I press <kbd>Enter</kbd>, it just jump to the beginning of my text for a short time, then jump back to the place I'm editing. 

### Steps to reproduce

Just type something. It will show up from time to time.
See this gif

![example2](https://user-images.githubusercontent.com/59756623/105821649-fee26780-5fb2-11eb-89df-e9f8c138bdab.gif)

### Versions

- Mark Text version: 0.16.3
- Operating system: Windows 10

Thanks for reading!

**Comment by joonyoungleeduke** [comment]
I got this same error and it primarily seems to occur when the enter key scrolls the document (i.e. this does not occur when you use the enter key to create more space first). Maybe it has to do with the rendering? I'm new to the repo but I can look into it when I have time.

**Comment by CindyCyber** [comment]
> I got this same error and it primarily seems to occur when the enter key scrolls the document (i.e. this does not occur when you use the enter key to create more space first). Maybe it has to do with the rendering? I'm new to the repo but I can look into it when I have time.

OK, thanks for replying!

**Comment by YalandHong** [comment]
Possible dup of #2470

In order to reduce duplications, please close this issue and report your problems there. Thanks!

----

这个问题可能已经有人提过了：#2470

如果你碰到了一样的问题，请关闭这个issue，把你的问题反馈到#2470，谢谢！
