### ISSUE TITLE
[Feature-request] Tasks with Reminders or separate Task-View

### ISSUE THREAD

**Issue by sspaeti** [marktext/marktext#2495]
### Describe your feature request

Reminders for tasks or a separate view with all task listed.

### What problem does this feature solve? 

One thing I'm currently missing is to have notes and reminders in one. Meaning when you take notes for something I often write down tasks and to do's. But mostly they get lost in the notes. For that reason having a separate view or just custom set reminder would be awesome! What do you think?

### Additional context
The syntax might be something like this:
```
- [ ] Reply customer email ![remind] today 16 hs
- [ ] Foo @due(2019/01/31 19:00)
```

**Comment by tauren** [comment]
I personally would love a feature like this. But I suggest sticking with an existing standard format for cross-app compatibility. See https://github.com/todotxt/todo.txt

What I'm looking for is a tool that will let me take notes in markdown, throw TODO items (`- [ ] Clear out garage @Home +GarageSale`) anywhere in any note, and it would extract all TODOs into a separate view. Bonus points if that view can group, sort and filter the TODO items by context (`@Home`), project (`+GarageSale`), due date, priority, etc.

**Comment by andypillip** [comment]
Love the idea of a view on the current tasks. The sidebar would be a great place for that list I think.

**Comment by sspaeti** [comment]
I'll close for now, as I'm not using Marktext and due to inactivity. Please feel free to re-open if you have other plans.
