### ISSUE TITLE
View choices aren't retained between app usages

### ISSUE THREAD

**Issue by Chuhtra** [marktext/marktext#2499]
Hi! New here, cheers for the great app!

### Description

Setting choices in 'View' isn't retained between application restarting.

- [x] Can you reproduce the issue? 

So I choose View parameters for the application and, to my "surprise", these choices aren't retained the next time I open the app. For example, if I select to use the app with Sidebad shown and 'Source Code Mode' on, the next time I open the app these Sidebar is hidden and Source Code Mode is deactivated. In other words, it always starts with the defaults.

### Steps to reproduce

1. Open the app.
2. Select choices in the View tab (like the examples above).
3. Do things in the app (or not), and close it.
4. Open it again.
5. Your selected View choices are gone.

**Expected behavior:**

I would expect (or like to be more precise) these choices to be retained. 

**Actual behavior:**

The View choices defaults are used every time.

### Versions

- Mark Text version: v0.16.3 ([this from aur](https://aur.archlinux.org/packages/marktext))
- Operating system: Manjaro Linux

**Comment by brainchild0** [comment]
Related to #519 and #2345.

**Comment by Chuhtra** [comment]
Thanks for the comment @brainchild0. I tried looking for existing issues but couldn't find any.

As both these issues cover what I talk about, I am closing this.
