### ISSUE TITLE
cmd + s not work, and the orange dot does not disappeared after press cmd + s

### ISSUE THREAD

**Issue by liyuan0704** [marktext/marktext#250]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](https://codepen.io/) or a similar service and paste a link here]

### Versions

- Mark Text:
- OS:

**Comment by Jocs** [comment]
Could you please explain it more clear, because we can not reproduce it?
请将 issue 描述更加清晰一些，按照 issue template。这样我们才能够完全明白 issue 表达的内容。

**Comment by fxha** [comment]
@Jocs The issue with the modification indicator was fixed in version 0.10.21.

@liyuan0704 Do you use the latest version (v0.10.21)?

**Comment by Jocs** [comment]
@fxha I forgot that you have fixed this problem!:smile:
