### ISSUE TITLE
Retain Sidebar and Tab bar state between sessions

### ISSUE THREAD

**Issue by Epacik** [marktext/marktext#2502]
I'd like to have an option to have sidebar and tab bar open on startup if I left them open exiting from Marktext, because opening them each time I start the program is quite a tedious process

**Comment by morgenman** [comment]
Having the tab bar and opened files in the side bar feels redundant. Maybe add an option to show tab bar only when sidebar is closed?

**Comment by Epacik** [comment]
At startup yes it may seem redundant, but I don't think there's a reason to stop people from doing that

**Comment by orbanbalage** [comment]
See #1274

**Comment by Jocs** [comment]
Dup of #1274, please discuss in that issue.
