### ISSUE TITLE
Run as extension inside VS Code

### ISSUE THREAD

**Issue by stephenermshar** [marktext/marktext#2503]
### Describe your feature request

When a markdown file is opened in VS Code it would be pretty cool if instead of opening a text editor and preview tab, it would open a tab with the Mark Text embedded in it.

### What problem does this feature solve? [optional]

it would provide quick access to Mark Text features when working in VS Code without opening the standalone program. And would remove the need to work in a dual-pane view with the text editor and preview tab when editing markdown files in a code base, like readme or documentation files.

### Additional context [optional]

Since Mark Text appears to be written in JS it seems like it might fit in well as an extension in VS code, in addition to the stand alone version that already exists. I imagine this could potentially be supported as a fourth platform alongside windows/mac/linux versions that already exist.

**Comment by YalandHong** [comment]
Dup of #2404, but I think you can keep this issue anyway.

**Comment by Jocs** [comment]
It's not a feature of MarkText, but a plugin of VSCode?  I think you can use [muya](https://github.com/marktext/muya) to write a VSCode plugin, but I'm not sure if it's possible
