### ISSUE TITLE
Default to recent directory when opening a new window and custom keyboard shortcut

### ISSUE THREAD

**Issue by klovack** [marktext/marktext#2507]
### Describe your feature request
First of, Mark Text is a great markdown editor, but there are 2 features I miss the most when using it. 

1. The functionality to **edit the keyboard shortcut**
This is self explanatory. I would like to have my own keyboard shortcut, e.g. I want `ctrl+n` to just open a new file instead of opening new empty window. If I want a new empty window, I'll assign that to `ctrl+shift+n`. This could just be of a json or yaml format.

2. **Not having to open the same folder when I exit Mark Text**. 
I change from folder to folder a lot, and that makes the default directory option in the settings a bit useless. If I want to tell Mark Text to open the folder that I'm currently editing the next time I open it, I would have to go to `preferences -> general -> action on startup -> select open the default directory -> select folder (additionally finding the folder)`.

### What problem does this feature solve? [optional]

1. Most people would love custom keyboard shortcut, because they can use the keyboard shortcut they feel most comfortable, instead of having to learn new keyboard shortcut.

2. Save time for users the next time they open the editor.

**Comment by YalandHong** [comment]
The first issue is a dup of #2599. See [KEYBINDINGS.md](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md) for shortcut customization.

FYI, try to add this to your `keybindings.json`:
```json
{
  "file.new-file": "CmdOrCtrl+Shift+N",
}
```
Here's the result:
![2021_12_04_09_11_15](https://user-images.githubusercontent.com/52960068/144691146-aef7a13e-4038-406b-afb3-bb7e4fe7eb69.png)

----

The second issue is a dup of #2467.
