### ISSUE TITLE
 the underline in the link is automatically escaped when coping

### ISSUE THREAD

**Issue by zombiecong** [marktext/marktext#251]
如原链接为 https://xxx/xxxx/xxxt_xxxx_xxx_xxx_xxx 会自定转义成 https://xxx/xxxx/xxxt\_xxxx\_xxx\_xxx\_xxx , 能否关闭自动转义？

![untitled](https://user-images.githubusercontent.com/7962780/39683297-4c513294-51e7-11e8-8a4c-b167e3441263.gif)

### Versions

- Mark Text:  v0.10.21
- OS: macOS  10.13.5 beta

**Comment by Jocs** [comment]
@zombiecong Thanks for report this issue, and we will fix it latter.
