### ISSUE TITLE
Close window when closing document

### ISSUE THREAD

**Issue by DePasqualeOrg** [marktext/marktext#2520]
Currently, when closing a document (at least on macOS), Mark Text shows a window with a "New File" button. Other text editors simply close the window and get out of the way when a document is closed. The current behavior in Mark Text is counterintuitive and not very useful in my opinion. Furthermore, the keyboard command (Command-W) to close the document does not work on the "New File" window, which is also counterintuitive. I'd like to suggest adopting the behavior of text editors like Sublime and simply closing the window when the user closes the document.

**Comment by DejayRezme** [comment]
The current behavior might make sense when you open all documents in one window, but if you select "open document in new window" you expect that new window to close.

Alternatively you could not close ALL windows with Ctrl-Q. 

Right now there seems to be no way to open a document, do a quick edit then save and close it without leaving an empty window open or closing other mark text windows.

**Comment by Jocs** [comment]
The current interaction is the same as VSCode, and we will also add some shortcut keys to the blank page later
