### ISSUE TITLE
Where can I find the documents or user manual?

### ISSUE THREAD

**Issue by yilikun** [marktext/marktext#253]
一直在看图学习，但是真心不知道按的是哪些快捷键

**Comment by Jocs** [comment]
@yilikun We will write the documents and user manual after version 1.0.0, because the shortcuts maybe change latter.

**Comment by yilikun** [comment]
ok,thanks for your work

**Comment by Jocs** [comment]
You can find user document and developer document [here](https://github.com/marktext/marktext/tree/develop/docs). close this issue due to inactive.
