### ISSUE TITLE
Bug: auto-generate closing symbol even if following a non-whitespace char.

### ISSUE THREAD

**Issue by Banyc** [marktext/marktext#2534]
### Description

When I type `$` or `(`, it will auto-generate `$` or `)`, which is sweet. However, when I type the char right before a non-whitespace char, I do not expect the closing symbol since I might want to append the closing symbol to the adjacent word or there has already been one.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. type `hello world`
2. type `(` before `world` -> `hello (world`
3. I don't expect the closing symbol shows up now.

**Expected behavior:**

No auto-generated closing symbol.

**Actual behavior:**

A closing symbol generated nevertheless.

### Versions

- Mark Text version: v0.16.3
- Operating system: Windows 10

**Comment by YalandHong** [comment]
Might have been fixed by #2960
