### ISSUE TITLE
Bug: the collapse does not work

### ISSUE THREAD

**Issue by Banyc** [marktext/marktext#2536]
### Description

```text
-   <details><summary>rules</summary>

    -   $\displaystyle \nabla (\bold{A} \bold{x}) = \bold{A} ^ T$
    -   $\displaystyle \nabla (\bold{x} ^ T \bold{A}) = \bold{A}$
    -   $\displaystyle \nabla (\bold{x} ^ T \bold{A} \bold{x}) = (\bold{A} + \bold{A} ^ T) \bold{x}$
    -   $\displaystyle \nabla ||\bold{x}|| ^ 2 = \nabla (\bold{x} ^ T \bold{x}) = 2 \bold{x}$

    </details>

```

It does not collapse the content in `<summary>`.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Copy the example code and paste it to marktext.

**Expected behavior:**

The content in `<summary>` should not appear.

**Actual behavior:**

It shows up and the collapse seems not working at all.

### Versions

- Mark Text version: v0.16.3
- Operating system: Windows 10

**Comment by Jocs** [comment]
Please remove the empty lines between \<detail> and try again?

**Comment by Banyc** [comment]
@Jocs It's been a long time since I encountered this problem, I might lack the ability to catch up the updates.

Thanks for the help!
