### ISSUE TITLE
When I add new line, the page will blink.

### ISSUE THREAD

**Issue by Anditty** [marktext/marktext#2541]
### Description

When I add new line, the page will blink, and the right scrollbar will blink to the top.

### Repreduce
I just keep pressing "Enter" button to insert new line, and the page will blink.
![Mar-28-2021 22-57-34](https://user-images.githubusercontent.com/71593976/112756812-69e30580-9019-11eb-9236-f3a2d3c0858c.gif)

- Mark Text version:v0.16.3
- Operating system:MacOs 11

**Comment by lucas979797** [comment]
To work around this I just put some text at the bottom of the page and it seems to alleviate the issue. Hopefully there will be proper fix for this soon though.
