### ISSUE TITLE
Outdated links on help menu

### ISSUE THREAD

**Issue by sanjay-swain** [marktext/marktext#2553]
### Outdated links on help menu

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. On the menu under help section the links to changelog, Quick Start and markdown reference.

**Expected behavior:**
Clicking on changelog should redirect [here](https://github.com/marktext/marktext/blob/develop/CONTRIBUTING.md).

**Actual behavior:**
It is redirecting to outdated [master branch](https://github.com/marktext/marktext/blob/master/.github/CHANGELOG.md) same for Quick Start link and markdown reference links.

### Versions

- Mark Text version:  v0.16.3
- Operating system: Win 10

**Comment by fxha** [comment]
The existing behavior is how it is expected to work. The current stable version should link to the `master` branch. `develop` is used for the next release.
