### ISSUE TITLE
Ability to store images in a relative directory per file

### ISSUE THREAD

**Issue by fgimian** [marktext/marktext#2559]
### Describe your feature request

Continuing on from the discussion in #549 

Mark Text only offers the ability to store all images for multiple Markdown files in a relative directory (e.g. assets), unlike Typora which allows you to create one directory per document (e.g. ./${filename}.assets). I much prefer the latter approach as it keeps each individual document separate with its own dedicated directory for images. If you had for example 20 Markdown files, and each had images, these would all be put into a single folder with Mark Text, which makes it harder to move pages to a different location and also leads to a messier filesystem.

### What problem does this feature solve? [optional]

This makes it possible to create self contained pages with their own respective directory that can be easily shared, backed up or moved to a different location together.

### Additional context [optional]

Here's the related options in Typora:

![image](https://user-images.githubusercontent.com/1811813/115016947-1ddcff80-9ef9-11eb-868a-3ccc54e40529.png)

I'm specifically looking for Copy image to ./$(filename).assets

A similar syntax where the filename is substituted could be supported in the following MarkText option:

![image](https://user-images.githubusercontent.com/1811813/115017054-46fd9000-9ef9-11eb-923d-3b193d5bae08.png)

**Comment by nutnutwin** [comment]
I personally wish this to be implemented
Only problem I can see stopping me from Switching from Typora(which is horrible in searching within doc, and tabs in Windows)
also from #549

**Comment by teopost** [comment]
+1

**Comment by carmolim** [comment]
+1

**Comment by Kellermaan** [comment]
+1

**Comment by PropFault** [comment]
+1

**Comment by ECJH** [comment]
+1

**Comment by conscloud** [comment]
+1

**Comment by filefi** [comment]
+1

**Comment by bdillahu** [comment]
Yep, just another vote for this...

**Comment by tikikun** [comment]
has this been fixed

**Comment by OuttaSpaceTime** [comment]
@fxha will this be available with the next release?

**Comment by fxha** [comment]
Yes, this feature available in our next release.

**Comment by Kellermaan** [comment]
@fxha  wow, then may i ask when is our next release?

**Comment by fgimian** [comment]
I've just built the latest develop branch to test out this feature and it works great, but there is one minor difference to Typora and that is that `${filename}` in Typora excludes the *.md extension which I think is cleaner.

e.g. Mark Text does this

```
My Document.md
My Document.md.assets/image.png
```

e.g. Typora does this

```
My Document.md
My Document.assets/image.png
```

What do you think?

I think it would also be good to add some text on the Image config page indicating that this is an option or it's simply impossible for anyone to know:

![image](https://user-images.githubusercontent.com/1811813/150062904-f9129c69-65fb-42ea-999f-0bbd4a71fbf2.png)

Huge thanks
Fotis

**Comment by fgimian** [comment]
Just tagging @fxha since the issue is closed and may be easy to miss my comment 😄

**Comment by fxha** [comment]
> wow, then may i ask when is our next release?

Release candidates for testing should be available later this month and a release is panned for February.

> I've just built the latest develop branch to test out this feature and it works great, but there is one minor difference to Typora and that is that ${filename} in Typora excludes the *.md extension which I think is cleaner.

Yes, you're right and there is already a PR that we'll merge #2905.

**Comment by fgimian** [comment]
> > wow, then may i ask when is our next release?
> 
> Release candidates for testing should be available later this month and a release is panned for February.
> 
> > I've just built the latest develop branch to test out this feature and it works great, but there is one minor difference to Typora and that is that ${filename} in Typora excludes the *.md extension which I think is cleaner.
> 
> Yes, you're right and there is already a PR that we'll merge #2905.

Fantastic, thank you so much! ❤️

**Comment by Kellermaan** [comment]
> > > wow, then may i ask when is our next release?
> > 
> > 
> > Release candidates for testing should be available later this month and a release is panned for February.
> > > I've just built the latest develop branch to test out this feature and it works great, but there is one minor difference to Typora and that is that ${filename} in Typora excludes the *.md extension which I think is cleaner.
> > 
> > 
> > Yes, you're right and there is already a PR that we'll merge #2905.
> 
> Fantastic, thank you so much! ❤️

cool, Thanks a lot!!

**Comment by OuttaSpaceTime** [comment]
Something I wanted to add for usability is that I like the simply dialog in typora menu. Using filepath is kind of techy, programmers like us will like it or have at least no problem using it, but normal people may find it a little bit confusing at first.
