### ISSUE TITLE
Memory leak in MacOs version (maybe all versions)

### ISSUE THREAD

**Issue by WinterChenS** [marktext/marktext#256]
### 发现Mac OS版本内存泄漏

用了两天这个软件的Mac OS版本，最中意的一个md编辑器，但是使用的过程中发现会越来越卡顿，然后看了一眼内存的使用状况，如图：
![](http://ozlpw4ja9.bkt.clouddn.com/WX20180510-164127@2x.png)

### Versions 

- Mark Text: 0.10.21
- OS: Mac OS 10.13.2

**Comment by Jocs** [comment]
@WinterChenS 内存使用情况在下一个版本会有所改善。

请问下你打开文件的体积？编辑时长？

**Comment by WinterChenS** [comment]
文件大小为10k，编辑时长大约为一个小时

**Comment by Jocs** [comment]
@WinterChenS 推测大概原因应该是 history 太深了，不过在下个版本做出优化，undo 的次数有限制了，这样就不会一直吃内存了。
