### ISSUE TITLE
Support Ruby Character

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#257]
### Description
Ruby Character's Description Is [here](https://en.wikipedia.org/wiki/Ruby_character).
Japanese Free Novel Site [Hameln](https://syosetu.org/?mode=readme_view&fid=25)(Japanese Only.) Style.
...But I'm Hameln User.

```markdown
｜東京《とうきょう》は素敵な街です。
* English Transration: Tokyo Is Beautiful Town.
```

### Versions

- Mark Text: v0.10.21
- OS: Windows

**Comment by keito940** [comment]
@fxha that's right.
How is this kind of?

```markdown
|東京<とうきょう>
```
Since ruby character in HTML is rather troublesome, we devised it.

**Comment by fxha** [comment]
I still don't get the point. You write ruby characters inside `<` and `>`. But how do you write ruby characters into a document/text so that we can parse it? There can be normal text between the smaller and greater sign. Maybe @Jocs understands the topic better than I.

**Comment by Jocs** [comment]
@keito940 Do you mean we write in this way:

```
|東京<とうきょう>
```

but it looks like:

![](https://user-images.githubusercontent.com/22716132/39921210-565255f8-551a-11e8-8c1c-e90b195a7eac.png)

?

**Comment by keito940** [comment]
@jocs Yes.

**Comment by Jocs** [comment]
@keito940 You can use a html block to render Ruby Character,  like this bellow.

```md
<ruby>
 <rb>北</rb>
 <rp>(</rp><rt>ㄅㄟˇ</rt><rp>)</rp>
 <rb>京</rb>
 <rp>(</rp><rt>ㄐ丨ㄥ</rt><rp>)</rp>
</ruby>
```

![屏幕快照 2019-04-03 上午11 56 23](https://user-images.githubusercontent.com/9712830/55451901-91a85a00-5607-11e9-866c-703268825f29.png)


in the next release version, you can write ruby tag in paragraph as bellow:

```md
<ruby>漢<rt>Kan</rt>字<rt>ji</rt></ruby>
```

![屏幕快照 2019-04-03 上午11 56 08](https://user-images.githubusercontent.com/9712830/55451909-979e3b00-5607-11e9-88fd-7c9234edab40.png)

**Comment by keito940** [comment]
What is My Create Ruby Tag?

**Comment by Jocs** [comment]
This is a markdown syntax of [GFM](https://github.github.com/gfm/#raw-html), that you can write html in your paragraph, So you also can write `ruby` element in paragraph.

**Comment by keito940** [comment]
But is it better to put in my ruby ​​tag?

**Comment by Jocs** [comment]
But if there is already a syntax that can support ruby character, why do we need another custom syntax?

**Comment by keito940** [comment]
The ruby ​​you have already prepared can not understand if you can not read the HTML, 
but the ruby ​​syntax I made is easy to understand that the ruby ​​is shaken when I see the plain text MarkDown.

**Comment by keito940** [comment]
It is difficult.

**Comment by Jocs** [comment]
What is difficult? write html tag?

**Comment by Jocs** [comment]
>The ruby ​​you have already prepared can not understand if you can not read the HTML,
but the ruby ​​syntax I made is easy to understand that the ruby ​​is shaken when I see the plain text MarkDown.

Yes, you are right.

**Comment by keito940** [comment]
What is My Custom Syntax?

**Comment by Jocs** [comment]
@keito940 Sorry that we'll not consider custom syntax of markdown before version 1.0.
