### ISSUE TITLE
KaTeX Version is Outdated

### ISSUE THREAD

**Issue by furkantaskin** [marktext/marktext#2573]
Just met with the software. Interface is great but something is bringing problem for me.  Latest KaTeX version is 0.13 which brings support for many environments. But Mark Text is currently using v0.12.x which lacks of environment support. Is there any plan to update KaTeX?

An example can be seen in the image below

![image](https://user-images.githubusercontent.com/9028874/116788458-5f051000-aab2-11eb-9e49-a389542b5d6f.png)

**Comment by fxha** [comment]
KaTeX is up to date in our latest development version, we'll create a nightly soon and a release is planned within the next month.
