### ISSUE TITLE
Custom Image uploader and right click to insert image

### ISSUE THREAD

**Issue by CesarPazzi** [marktext/marktext#2581]
### Custom Image uploader

Put a field for a command to execute when inserting an image.
For example, inserting image1.jpg will execute a custom command and the file will serve as an argument to take from the custom command previously specified.

For example:
When image1.jpg was inserted, the following command will be executed:
python.exe .\MyCustomUploader.py 'image1.jpg' 
image1.jpg will serve as an argument for the script and will return:
https://myimageserver.com/path_to_uploaded_image.jpg <-- and this will be inserted in the editor

Also, the option to insert an image from the right click menu.

### What problem does this feature solve? [optional]

Devs will make more options for uploading to different services and not getting stuck with 2 options.

### Additional context [optional]

I know I'm comparing to Typora but these are cool features to have along with publishing to platforms like blogger, wordpress or a custom platform like Hive.

![marktext1](https://user-images.githubusercontent.com/15187706/118239184-0ee95e80-b45f-11eb-90f9-69039e57a91e.JPG)
![marktext2](https://user-images.githubusercontent.com/15187706/118239185-0ee95e80-b45f-11eb-8166-322331723b8d.JPG)
![marktext3](https://user-images.githubusercontent.com/15187706/118239187-0f81f500-b45f-11eb-8529-021e66ea745b.JPG)

**Comment by jonejkim** [comment]
I second this. I am currently still using Typora, but would always like to switch to opensource markdown editor at some point. Typora does not by default ship with image uploader but allows you to bring your own as long as the command call complies to its requirements.

Here is my [repository](https://github.com/jonejkim/httpfs) of example on how I have DIY-ed my own local server image uploader for Typora.

**Comment by YalandHong** [comment]
For custom image uploader, please track #2100 and #2776.

**Comment by fxha** [comment]
This feature was implemented in #2100.
