### ISSUE TITLE
I want to translate the user interface, which file i need edit?

### ISSUE THREAD

**Issue by EuriNaiz** [marktext/marktext#2589]
I want to translate the app to Spanish, I have searched a file to do it, but i didn't find, how can I do it?

**Comment by YalandHong** [comment]
Dup of #138 

According to the roadmap, MarkText team will open another repo for internalization. ([comment](https://github.com/marktext/marktext/issues/138#issuecomment-380867653))

Also, you're not the only one who want a Spanish version. ([comment](https://github.com/marktext/marktext/issues/138#issuecomment-784180040))
