### ISSUE TITLE
Unexpected "File changed on Disk" prompt when using OneDrive

### ISSUE THREAD

**Issue by JohannHoepfner** [marktext/marktext#2592]
### Description

If you save a Markdown file on OneDrive (Not tested with other clouds) the syncing seems to make MarkText think, that the file has been changed externally from Markdown.
This does not happen using a local file. I verified that OneDrive does not change the content of the file when syncing and suspect that MarkText uses e.g. the modified date for looking whether the file was changed externally from MarkText.
This issue is relevant because the prompt is only shown after a few seconds and as a consequence if the user reloads the file using the button in the prompt they will lose what they have just written after saving.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create Markdown file in OneDrive folder on Windows
2. Open file in MarkText 
3. Change file
4. Save file

**Expected behavior:**
Saving without "File changed on disk" prompt
**Actual behavior:**
after about 5 seconds
![Screenshot 2021-05-26 151950](https://user-images.githubusercontent.com/62462701/119667562-b2127e80-be36-11eb-89de-504e7eed040d.png)

### Versions

- Mark Text version: v0.16.3 
- Operating system: Windows 10 21H1

**Comment by andypillip** [comment]
I am seeing the same issue when working on a regular windows network drive.

v0.16.3
Windows Version 10.0.18363 Build 18363

**Comment by fatcat73** [comment]
The "File changed" prompt appears only once every one or two hours, never continuously pop up though I save file frequently. I tried to monitor the file status. Each time when I save the file, its modification and access time are both updated. Then the OneDrive changes its access time again after 100 ms more or less.

**Comment by fxha** [comment]
You need to configure the [filesystem watcher](https://github.com/marktext/marktext/blob/master/docs/PREFERENCES.md#file-system) to use polling when editing a file on a network drive. We'll try to add a settings options to select paths that should use polling by default in the future.

> You need to set `watcherUsePolling` to `true` in `preference.json` if you want to watch files on a Network File System (NFS) such as iCloud Drive or Google Drive. Setting this to polling continuously checks all files for changes which can result in very bad performance and high CPU usage in larger directories. [...]
> 
> chokidar documentation:
> 
> > `usePolling` (default: `false`).
> > Whether to use fs.watchFile (backed by polling), or fs.watch. If polling
> > leads to high CPU utilization, consider setting this to `false`. It is
> > typically necessary to **set this to `true` to successfully watch files over
> > a network**, and it may be necessary to successfully watch files in other
> > non-standard situations.

Ref. #2170.

**Comment by Honghe** [comment]
`watcherUsePolling: true` doesn't work.

**Comment by Honghe** [comment]
@fxha watcherUsePolling: true doesn't work.

**Comment by W2Q3Q1** [comment]
Unfortunately, I am facing that problem on a local file on Win11.

**Comment by xyangwu** [comment]
> Unfortunately, I am facing that problem on a local file on Win11.

I was facing the same problem. But the "reload" prompt never pop up after i restarted MarkText. I dont't why🙊
