### ISSUE TITLE
Footnote support

### ISSUE THREAD

**Issue by AmanKabra** [marktext/marktext#2598]
### Describe your feature request

The current version of Mark Text does not seem to support the addition of footnotes/endnotes to the document. Can that feature be please, please added?

### What problem does this feature solve?

Several academia-folks want to write papers and blogs using Mark Text, but footnote feature absence is acting as a deal breaker.

**Comment by dave-kennedy** [comment]
Pandoc-style footnotes are disabled by default. You can enable them under Preferences > Markdown > Markdown extensions.
