### ISSUE TITLE
I have conflicts when using shortcut keys and I have some suggestions

### ISSUE THREAD

**Issue by HWH-2019** [marktext/marktext#2599]
### Additional context [optional]
That's the box. I don't feel comfortable
![image](https://user-images.githubusercontent.com/59130930/121841909-e67caa80-cd11-11eb-983d-41ca117cb620.png)

**Comment by EuriNaiz** [comment]
28 days ago I also suggested the [custom shortcuts and Obsidian shortcuts/hotkeys by default](https://github.com/marktext/marktext/issues/2587), I hope they could add that option, In other hand I recommend you add your suggestions on a existing thread (if it already exists) for the UI related or opening new if it doesn't exists... I realised that Marktext hasn't been so active with new code, but I hope they're creating a new version improved an more complete, with more functions.

**Comment by YalandHong** [comment]
FYI, try to customize your shortcuts accroding to [KEYBINDINGS.md](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md#available-keys)
