### ISSUE TITLE
Markdown contained in html block not rendering.

### ISSUE THREAD

**Issue by JACK0YORK** [marktext/marktext#2602]
### Description

Markdown contained in html block not rendering.

### Steps to reproduce

1. Create an html block in Mark Text
2. Add any markdown to the inside of the html block.

**Example:**

```html
<div>

*italic*

</div>
```

**Expected behavior:**

<div>

*italic*

</div>

**Actual behavior:**

<div>

\*italic*

</div>

### Versions

- Mark Text: v0.16.3
- Operating system: Windows 10 Home 10.0.19042

**Comment by DYH-Hong** [comment]
Duplicate of #2308

**Comment by Jocs** [comment]
Duplicated of #1764
