### ISSUE TITLE
 Code block width does not change upon resizing window

### ISSUE THREAD

**Issue by dodedodo** [marktext/marktext#2608]
### Describe your feature request

When I resize the marktext window, the document text should reflow to the smaller width.

Current behaviour: when resizing marktext's window, the document width stays the same, and overflows on the right when the window's width is too small. Essentially making that part of the document inaccessible. 

### What problem does this feature solve? [optional]
I often find myself tiling marktext right next to a browser or code editor for taking notes, or referring back to an existing document (with the sidebar disabled). If marktext would be able to claim less horizontal space, that would make it less obtrusive.  

Right now, marktext needs a little less than half the width of a 1080p screen.

**Comment by YalandHong** [comment]
Possible dup of #1695

Please try to adjust the percentage in the settings.

**Comment by dodedodo** [comment]
Thanks for your reply! I do not think this is a duplicate. 

The issue you refer to is about making the most use of screen real estate. I'm talking about a text-overflow issue when making the window smaller than ~540px (that number is higher with sidebar enabled).

I've tested this some more, and this issue seems to be specifically triggered by code blocks. An empty code-block resizes just fine, however, a code-block with text inside does not.

Ok
```
abc
```

Not ok
```
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz

**Comment by YalandHong** [comment]
Reproduced on my Windows 10, with MarkText version 0.16.3.

**Bug description**: The code block does not change its width when I resize the window, making the editor erea overflow.

![image](https://user-images.githubusercontent.com/52960068/145740812-38af9b83-da72-4f29-b0c7-116baeacd0be.png)

**Comment by YalandHong** [comment]
The title of this issue is not clear. Please consider changing it to *Code block width does not change upon resizing window* or something like that. Thanks!
