### ISSUE TITLE
Table cell selection

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#262]
I think it would be a good enhancement to only select text from the selected table cell (and not the full document) if you press `Ctrl+A`. What's you opinion, @Jocs?

**Comment by Jocs** [comment]
@fxha I agree with you, do you want to handle this issue?

**Comment by Jocs** [comment]
@fxha I think first need to prevent the default select all, then we can set the cursor range and render.

**Comment by fxha** [comment]
@Jocs Reopen as it's broken with develop, pressing (multiple times) `Ctrl+A` doesn't do anything.

**Comment by Jocs** [comment]
@fxha duplicated with #1666 ？please close this issue and remove from 0.16.0 project and `pre-release` label if it's duplicated.
