### ISSUE TITLE
Relative image folder support ${filename}

### ISSUE THREAD

**Issue by qylixin** [marktext/marktext#2624]
### Describe your feature request

Relative image folder path support use ${filename} as an variable which is this markdown's filename.
So images in different markdown are saved in different folders.
for example, when i use "./${filename}.assets" as relative image folder, images in hello.md are saved in ./hello.assets folder and images in world.md are saved in ./world.assets folder.

**Comment by imckh** [comment]
${filename}.assets
Something like this:
![image](https://user-images.githubusercontent.com/24891226/143666804-859b68bb-e210-4bb2-ade7-cb8af7e63628.png)

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2559. You may want to subscribe there for further updates.
