### ISSUE TITLE
Agressive placement of a page break before a large code block

### ISSUE THREAD

**Issue by de-abreu** [marktext/marktext#2634]
### Description

Using Flatpak's distribution of Marktext version 0.16.3, I used [this document](https://board.disroot.org/media/attachments/f/c/6/5/83415b453b288a3a7b1994645707df60d82a759955b6ae71d09346457dfd/semana-04-respostas.md?token=YTtgFA%3AaZyAltA0qso5SXm1OOGP_1kxL4D-MwGcZR_GYTl-BIAijVkrcoWSfNyQMO3cxhJ0FEwat06hgYIf5eoHFRssuA#_taiga-refresh=userstory:1014) to generate this [pdf file](https://board.disroot.org/media/attachments/e/d/6/8/84533c9d6cd82f528eeaea024a3ec7b720c6d41db4ab3d432bf4f36b5683/semana-04.pdf?token=YTtgBw%3Ax2-uH1pOyteC0VUKn7Lmg0z0AK0HLQ3py1cS-EiD6fsNa_xKnf5W6E-T7uYWG43r1YN74_G9VxkAP7A6Dn8aHw#_taiga-refresh=userstory:1015). As shown, it features a a extensive code block spawning multiple pages. At the beginning of the code block, Marktext inserted a page break. 

**Expected behavior:**

I would rather prefer that it didn't introduce that page break.

**Comment by sergio9929** [comment]
Hi @de-abreu, have you managed to solve this?
The links are no longer available, I asume you are having this same issue #2609.

**Comment by de-abreu** [comment]
Hi @sergio9929,
 
I've been able to solve it by manually inserting breaks to the code blocks as needed. Indeed, I'm having the exact same issue as #2609, so I'll close this one.
