### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by Donkey-Doug** [marktext/marktext#2635]
Please make it possible to change the font. I would like to change the font locally, that is, for a few lines of text. However, I guess changing the font globally (for the entire document) might also be desirable for some people.

**Comment by wrenger** [comment]
You can change the font globally in the `Preferences > Editor` settings. Just like the whole theme.

Documents, however, are stored as markdown, a very simple plain text format, that does not support more complex styling like custom fonts or colors.

**Comment by Donkey-Doug** [comment]
Thank you. I really wanted local font changes, but if it is limitation of markdown then I guess it is too much too implement.
