### ISSUE TITLE
Can't upload  image when copy&paste

### ISSUE THREAD

**Issue by alston19** [marktext/marktext#2643]
I used Typora before and switched to MarkText last year. MarkText is so awesome that I suggest everyone around me to take a try. However, recently I encountered a bug/problem when using MarkText.

## Description
I config "Image Uploader" correctly and set "Upload to cloud using selected uploader". It works perfectly when I drag and place a picture. The picture will be uploaded to Github successfully. When I **copy & paste ** this picture instead, however, it shows "uploaded Failed".

I know there is another issue representing the same bug. But I still want to open a new one and hope MarkText can be better and bettter!

**Comment by YalandHong** [comment]
Dup of #2347
Please upvote it and discuss about it there.
