### ISSUE TITLE
How to Increase the width of the content area ?

### ISSUE THREAD

**Issue by smartsubbi** [marktext/marktext#2654]
### Question description
There are lot of space both on left and right hand side of the content area how do i utilize those ? or increase my content area width ?

![image](https://user-images.githubusercontent.com/339559/137584042-212fc344-8389-4259-aeaa-cfacf7bce8e5.png)

**Comment by YalandHong** [comment]
dup of #1695

**Comment by zq1997** [comment]
> it's in the preferences ![image](https://user-images.githubusercontent.com/19881231/137635044-f4a34460-b3fa-40f7-a20c-b14f90c31cfa.png)

![image](https://github.com/marktext/marktext/assets/17429111/242ada06-dbcc-4a73-9bdb-8781493f6950)
Does this option disappear in the latest version?

**Comment by luweijun1992** [comment]
> > it's in the preferences ![image](https://user-images.githubusercontent.com/19881231/137635044-f4a34460-b3fa-40f7-a20c-b14f90c31cfa.png)
> 
> ![image](https://private-user-images.githubusercontent.com/17429111/297031664-242ada06-dbcc-4a73-9bdb-8781493f6950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODI4NTAsIm5iZiI6MTcxMjg4MjU1MCwicGF0aCI6Ii8xNzQyOTExMS8yOTcwMzE2NjQtMjQyYWRhMDYtZGJjYy00YTczLTliZGItODc4MTQ5M2Y2OTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAwNDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZDlkNmM5YWU3ZDg5NGQzYjg4NzNmNjRmODlmODE2MzQzMzZlNDk1NDkwYTM5MmNjYThiZDcwOThiZjhmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vmAPZQOq0bFZQhk1j3z9cISyyqSlyqsbxcnevOrQ_KQ) Does this option disappear in the latest version?

![image](https://github.com/marktext/marktext/assets/58923704/eaa1acf4-4e93-463b-a08b-05b40bdf2649)

**Comment by gm-333** [comment]
I am new to marktext (it's great). In the current version the hint about using unit suffixes is gone. I couldnt figure it out for quite a while. I believe that hint should be brought back to make it easier for new users
