### ISSUE TITLE
OpenBSD Support?

### ISSUE THREAD

**Issue by anoduck** [marktext/marktext#2655]
### Describe your feature request

OpenBSD support, or at least instructions on how to compile from source.

**Comment by Jocs** [comment]
@anoduck Refer to this https://github.com/electron-userland/electron-builder/issues/1470, and PR is welcomed

**Comment by fxha** [comment]
@Jocs BSD is not supported by Electron.

**Comment by anoduck** [comment]
Electron is now available as a pkg in OpenBSD, it wasn't for way too long of a time, but finally someone did some justice and made it so.

https://openports.se/devel/electron
