### ISSUE TITLE
Feature Request: Templates

### ISSUE THREAD

**Issue by methane4** [marktext/marktext#2656]
My issue requests the ability to have templates integrated into Mark Text.

I had the idea of using a window similar to the one that the preferences uses with various categories to choose your templates from, i will provide a simple sketch.

![Screenshot from 2021-10-16 17-38-38](https://user-images.githubusercontent.com/46012160/137596094-e5b03099-dff4-4bbe-ba72-a968f8b277e6.png)

This is would be very beneficial for a lot of users.

**Comment by Jocs** [comment]
This is more like the function provided by the `plugin` function, please discuss this issue in the `plugin` related issue #375
