### ISSUE TITLE
Local links doesn't work 😢

### ISSUE THREAD

**Issue by lua-rocks** [marktext/marktext#2664]
Local links or **#links** are supported in VSCode:

![1](https://user-images.githubusercontent.com/82697845/138978114-c8754e47-aca6-49e9-a9aa-356589c3b957.png)

...and browser extensions like [this one](https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer-webext).

Even Github supported them ([example page](https://github.com/lua-rocks/core/tree/main/lib/object)):

![gif](https://user-images.githubusercontent.com/82697845/138979116-7e89397c-a59d-4ae9-a44e-31270428d93c.gif)

**Comment by loopernow** [comment]
Agreed...would like to see this implemented.

**Comment by YalandHong** [comment]
Possible dup of #1780

In order to reduce duplications, please close this issue and report your problems there. Thanks!

**Comment by lua-rocks** [comment]
Sorry, I searched but didn't find it.
