### ISSUE TITLE
Session snapshot and periodic backup

### ISSUE THREAD

**Issue by veringsek** [marktext/marktext#2665]
### Describe your feature request

Session snapshot and periodic backup is a feature in Notepad++, with which users can close the app without saving files, yet, the changes will be restored when the app is started again.

When enabled, the app save a snapshot to a given path for every `n` seconds, where `n` is configurable. Once the app is started, it will check the backup folder to see if any snapshot exists, if so, automatically opens those files, restores backup contents, and marks those tabs as *unsaved*. 

### What problem does this feature solve? [optional]

With this feature, users can quickly take notes by starting-typing-closing, also, works can be restored if some accidents happen so the app is terminated before they save.

**Comment by tehmasterer** [comment]
+1.

This is the reason I stuck with Notepad++ for so long. I recentley moved VS Code which has the same feature built-in and turned on by default.

If Mark Text adds this I would switch in a heartbeat.

**Comment by plum** [comment]
+1
A sesssion might contain opened files form the default folder and others from without the default folder. snap shot of such a state would permit swift return to the session, even after a week. 

There could be no downside, unless for some reason a user wishes to start with a blank session. In that case, a preference could take care of that, according to need. An alternative would be to have more than one session, with names.

**Comment by DYH-Hong** [comment]
Possible dup of #1274 and #988
