### ISSUE TITLE
当输入很多内容后，在最底部输入中文时，有时候滚动条会自动跳转到顶部

### ISSUE THREAD

**Issue by xtdiary** [marktext/marktext#267]
### Description

当输入很多内容后，在最底部输入中文时，有时候滚动条会自动跳转到顶部

### Steps to reproduce

1. 输入很多中文，从第7行开始插入代码块，之后在输入很多中文

**Expected behavior:** [What you expected to happen]
当在底部输入中文时，滚动条应该保持不动
**Actual behavior:** [What actually happened]
滚动条会自带跳到顶部
**Link to an example

:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text:
- OS:

**Comment by Jocs** [comment]
能把能够复现的 markdown 文件发我一份吗？ransixi@gmail.com

**Comment by kobejie93** [comment]
好的，晚上回家发你

**Comment by Jocs** [comment]
@kobejie93 hi, 暂时没有收到？

**Comment by xiocode** [comment]
![image](https://user-images.githubusercontent.com/1326473/40342262-429e091c-5dbc-11e8-8095-c3c6b4ebaa26.png)

同样的问题

@Jocs

**Comment by WinterChenS** [comment]
同样的问题

**Comment by Jocs** [comment]
@xiaotonglee @xiocode @WinterChenS 下载新版本还有有相同问题吗？因为我一直没有重现出来这个问题。

**Comment by xiaotonglee** [comment]
不好意思，最近没有写文章。下次看看

At 2018-06-21 18:07:54, "冉四夕" <notifications@github.com> wrote:


@xiaotonglee@xiocode@WinterChenS 下载新版本还有有相同问题吗？因为我一直没有重现出来这个问题。
