### ISSUE TITLE
Make keybindings changeable

### ISSUE THREAD

**Issue by aalars** [marktext/marktext#2671]
### Describe your feature request

Would like to change keybindings, so Martext can be used with other keyboard layouts.

### What problem does this feature solve?

With my keyboard (Estonia) typing `@` is triggered using `Alt` + `2`. In Marktext [this](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md#:~:text=switch-to-second-,Alt,2,-Switch%20tab%20to) combination switches tab to the 2nd. So currently this makes the application pretty much unusable.

### Additional context

Being able to type `@` seems to be a cornerstone for good user experience here. 
![Screenshot 2021-11-09 at 11 36 52](https://user-images.githubusercontent.com/46534875/140900473-a134afbe-6d60-4383-ab00-a7597ef33dd8.png)

**Comment by YalandHong** [comment]
According to [KEYBINDINGS.md](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md#available-keys), can't you just type an empty string to disable this shortcut?

If you can't, may be you can track issue #2235
