### ISSUE TITLE
Emoji is transparent when selected from emoji keyboard

### ISSUE THREAD

**Issue by ghost** [marktext/marktext#2674]
### Description

Emoji is displayed transparent when selected from the Windows emoji keyboard.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Press <kbd>Win</kbd> + <kbd>.</kbd> to open the emoji keyboard
2. Select an emoji
3. Emoji is transparent

**Expected behavior:**

Emoji should not look transparent

**Actual behavior:**

Emoji is transparent

**Link to an example: [optional]**

![1](https://user-images.githubusercontent.com/94283672/142334494-849d4c7c-2979-43f9-abad-87cb38b77818.gif)

### Versions

- Mark Text version: v0.16.3
- Operating system: Windows 10

**Comment by JakeWoodleigh** [comment]
Strangely this exact same thing happens with my MacBook Pro when selecting from the emoji bar (where F1-12 usually is), see below image (left side is selected from the emoji 'bar', right by typing with ::)
<img width="43" alt="Screen Shot 2021-11-22 at 12 35 24 pm" src="https://user-images.githubusercontent.com/68621689/142788578-c07222d1-ea5b-450d-a3e6-97bd7455bdb4.png">

**Comment by Jocs** [comment]
Because the second emoji you inserted is part of the text content, we add a transparent font color to the text content. we recommend you to insert emojis by `:heart:` syntax.
