### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Harvy1314** [marktext/marktext#2679]
### Question description

Can you adapt to Chinese，Make the global village better

**Comment by LaoshuBaby** [comment]
虽然#138 已经不止一次提到说这些是Duplicate
但我依然要对这种“重复就关闭”的社区模式说不
如果一个问题反复被提及，那开发者最好是去真的处理这个问题，而不是仅仅关闭一个Issue
因为Issue会被一次又一次的再创建，直到这个问题真的被处理得当。

**Comment by Jocs** [comment]
FYI https://github.com/marktext/marktext/issues/138#issuecomment-981650531, this issue will be closed.
