### ISSUE TITLE
How about supporting custom commands for image upload?

### ISSUE THREAD

**Issue by czf0613** [marktext/marktext#2687]
### Custom commands are important for me
I see that you provide SM.MS and Github as image uploaders. But, for some reasons, I cannot use those platforms as my pic-bed.
I made a command line tool to upload images automatically, so I need custom command support in MarkText.
You can check the Typora image upload options for inspiration.

Thanks sincerely. I hope that MarkText can be the best substitute for Typora!

**Comment by bode135** [comment]
I need it too...
Git and SM.MS's picture is invisible in China...

**Comment by bode135** [comment]
Maby we can write a plugin to realize it, like auto load picture to Gitee.

**Comment by czf0613** [comment]
> Maby we can write a plugin to realize it, like auto load picture to Gitee.

Well, it's a good idea, but I think "custom commands" is more practical because I cannot use Gitee either. We have the image upload command-line tool in my company.
By the way, how to develop the plugin for MarkText? If there's no official support for my request, I hava to decide making one on my own.

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2737. You may want to subscribe there for further updates.
