### ISSUE TITLE
failed upload Image & Copy bug!

### ISSUE THREAD

**Issue by kewtgh** [marktext/marktext#2688]
### Describe your feature request

1. After failed upload Images, can use "right click" to upload again. 
2. Maybe bugs: can't copy and past "&emsp;"(space:"& e m s p ;") at the beginning of a paragraph. Maybe you can add an option: Modified "@" function to insert a modified paragraph.

**Comment by YalandHong** [comment]
More info is needed.
For image upload failure, it's a possible dup of #2347 
For the bug about copying blank characters, it's a possible dup of #1822
Besides, you have used a wrong template. This is a bug report, not a feature request.

----

你的问题描述很不详细。这些问题有可能已经有人提过了。
从剪贴板里的粘贴图片无法正常上传：#2347
字符串在复制粘贴的时候，尾部的空白字符会被去掉：#1822

**Comment by kewtgh** [comment]
多谢回复，中文形容可能更容易理解。
1. 第一个问题是指，在上传图片失败后，无法操作进行再次上传，与您展示的 #2347 略有不同。建议添加右键操作，可以手动再次上传。
2. 第二个问题已经解决了，最初发现复制空格的转义字符，粘贴后转义字符直接变成空格。后来发现利用CTRL+Shift+C复制为Markdown文本即可粘贴为转义字符。

**Comment by YalandHong** [comment]
> 多谢回复，中文形容可能更容易理解。
> 
> 1. 第一个问题是指，在上传图片失败后，无法操作进行再次上传，与您展示的 [Image uploader to GitHub fails for copy/pasted image #2347](https://github.com/marktext/marktext/issues/2347) 略有不同。建议添加右键操作，可以手动再次上传。

上传失败以后，图片就被保存到本地了，生成的链接也是本地路径。目前也许只能通过鼠标拖拽等方式再插入一遍，看看是否上传成功。

至于将upload image加入到右键菜单，有人提过类似的问题（#2581），当然你也可以专门开一个issue。

**Comment by Readme0** [comment]
> > 多谢回复，中文形容可能更容易理解。
> > 
> > 1. 第一个问题是指，在上传图片失败后，无法操作进行再次上传，与您展示的 [Image uploader to GitHub fails for copy/pasted image #2347](https://github.com/marktext/marktext/issues/2347) 略有不同。建议添加右键操作，可以手动再次上传。
> 
> 上传失败以后，图片就被保存到本地了，生成的链接也是本地路径。目前也许只能通过鼠标拖拽等方式再插入一遍，看看是否上传成功。
> 
> 至于将upload image加入到右键菜单，有人提过类似的问题（#2581），当然你也可以专门开一个issue。

这个问题有修复计划吗？
