### ISSUE TITLE
一个关于Latex的疑似Bug

### ISSUE THREAD

**Issue by NorDorado** [marktext/marktext#269]
是个小问题，不知道能不能算BUG
在Latex语句中【$之间$】任意回车，将会从第一个图变成第二个人图
![QQ截图20180516234027.png](https://i.loli.net/2018/05/16/5afc5172d66e4.png)
![QQ截图20180516234129.png](https://i.loli.net/2018/05/16/5afc5172c51eb.png)
- Mark Text: v 0.10.21
- OS:windows

**Comment by NorDorado** [comment]
就是有时候不小心会按到Enter ,要是很长串的Latex，这个操作会一下多出四倍长，体验会变差,

**Comment by Jocs** [comment]
@NorDorado 能给一个很长的 Latex 的例子吗？
后期我们考虑支持多行 数学公式。
#242 这个是你想要的吗？

**Comment by NorDorado** [comment]
抱歉，平时不太使用Github,回复有些晚，不好意思
比如这串Latex：
$$J(\theta)=\frac1{2m}\sum_{i=0}(y^i-h_\theta(x^i))^2$$
如果在输入过程中按到enter,这么长串的LATEX自动复制几倍，基本就要重新打了.蛮影响体验的，
![image](https://user-images.githubusercontent.com/36447758/40313100-4cef7920-5d47-11e8-9cd3-1c08ac1d8199.png)

![image](https://user-images.githubusercontent.com/36447758/40313216-b4fe2cbe-5d47-11e8-9861-d29bff8dae96.png)

**Comment by NorDorado** [comment]
在此感谢大佬所做的工作，为我们提供了这么棒的工具
