### ISSUE TITLE
I hope the reltive image file use the reltive path

### ISSUE THREAD

**Issue by ytianxia6** [marktext/marktext#2700]
### Describe your feature request
If you use a relative image, when you copy an image, it is copied to the .assert directory, but the absolute path is used to reference it in the md file. Cannot be recognized using relative paths. I hope it can use a reltive path. 

### What problem does this feature solve? [optional]
When I use marktext to edit gitlab wiki, the picture is not recognized after upload

**Comment by YalandHong** [comment]
Duplicate of #2560

**Comment by ytianxia6** [comment]
Yes it's what I want.
