### ISSUE TITLE
Make paragraphs / equations draggable

### ISSUE THREAD

**Issue by bardo84** [marktext/marktext#2705]
I find it difficult to relocate equations in WYSIWYG mode, hitting the boundaries etc.
Simple dragging would be cool.

[Notion ](https://www.notion.so/)has a dragging symbol next to the paragraph icon on the left.
But instead of adding a dragging symbol, why not use the existing one for dragging?

**Comment by YalandHong** [comment]
Partially dup of #2285

**Comment by retsyo** [comment]
well, I think it is difficult to implement drag&drop

**Comment by bardo84** [comment]
Marktext should already have the notion of paragraph.
If not by mouse, would it be easier to move paragraphs by shortcuts like in Word?
"press and hold down the Shift+Alt+Up/Down key to move it"

**Comment by YalandHong** [comment]
> Marktext should already have the notion of paragraph. If not by mouse, would it be easier to move paragraphs by shortcuts like in Word? "press and hold down the Shift+Alt+Up/Down key to move it"

Please track #580 for this feature

**Comment by Jocs** [comment]
dup to #2285, and this feature is already implemented in `muya` repo, but it will take a long time to make it available in MarkText.
