### ISSUE TITLE
Upload failed, the image will be copied to the image folder

### ISSUE THREAD

**Issue by Giyn** [marktext/marktext#2718]
Upload failed, the image will be copied to the image folder

![image](https://user-images.githubusercontent.com/60831460/144259485-9a923a7b-f219-4f13-8ddd-144d671679b8.png)

**Comment by YalandHong** [comment]
More info is needed. Your issue is not clear. Please provide your MarkText and OS Version as well as how to reproduce this bug.

Possible dup of #2347 if you want to copy and paste an image from clipboard then upload it to GitHub.

**Comment by Jocs** [comment]
Closed due to no more detail.
