### ISSUE TITLE
Associate .md file with marktext

### ISSUE THREAD

**Issue by wuhanstudio** [marktext/marktext#2719]
### Describe your feature request

It would be great if we can associate all *.md files with marktext after installation, or there is a setting for file associations.

**Comment by fxha** [comment]
@wuhanstudio Which operating system do you use?

**Comment by wuhanstudio** [comment]
Hi, it's Windows 10.

**Comment by fxha** [comment]
The setup should be automatically associate with various markdown files. Please try to reinstall Mark Text.

**Comment by wuhanstudio** [comment]
Perhaps it's because I installed Typora beforehand, so that the file assosiation is not overritten.

Can I reassociate *.md files with Mark Text in the settings?

**Comment by loyukfai** [comment]
> Perhaps it's because I installed Typora beforehand, so that the file assosiation is not overritten by Mark Text.
> 
> Can I reassociate *.md files with Mark Text in the settings?

Possible. It seems I have encountered the/a same/similar problem too.

Anyhow, after a number of installs/uninstalls, .md files are now associated with MarkText.

Cheers.

**Comment by fxha** [comment]
> Can I reassociate *.md files with Mark Text in the settings?

Unfortunately not, you have to launch the installer again because the file associations are OS specific.

**Comment by YalandHong** [comment]
> Perhaps it's because I installed Typora beforehand, so that the file assosiation is not overritten by Mark Text.
> 
> Can I reassociate *.md files with Mark Text in the settings?

How to associate file types with programs is probably a system-dependent problem. For example, on Windows 10, you can set your default applications in control panel or in your right-click menu. Just google this question and you can easily find what you want.

Reinstalling MarkText is not an ideal way, I think.

**Comment by wuhanstudio** [comment]
Indeed, file assosiations are OS dependent. Relevant settings are available in system settings. 

Capable of associating *.md files with Mark Text during the first-time installation should be enough.
