### ISSUE TITLE
A suggestion for export file

### ISSUE THREAD

**Issue by Gaays** [marktext/marktext#2731]
### Describe your feature request

export file name is the markdown file name

for example：

a md file name is `study.md`

the first line of the file is： **1. project：xxx**

when export file the file name default is:  **1. project：xxx**.pdf

expect export file default name is: `study.pdf`

### What problem does this feature solve? [optional]

when export file the file name is the first line of the file

**Comment by Jocs** [comment]
@fxha If there is a file name, should we use the file name first? Only use the `first header` without a file name?

**Comment by fxha** [comment]
Seems to be a good idea.
