### ISSUE TITLE
编辑状态下会闪，太快了会造成电脑卡死重启

### ISSUE THREAD

**Issue by ClarenLee** [marktext/marktext#2733]
下载了来试用了下，发现编辑状态下很容易会整个页面闪烁，这时如果一直输入造成持续闪烁，一会电脑就卡死重启了。
我电脑刚买的新电脑，旗舰配置。我试了下typora不会有这个问题。
希望越做越好。

**Comment by YalandHong** [comment]
怎么个闪烁法？能否提供GIF或者录屏？

**Comment by ClarenLee** [comment]
> 怎么个闪烁法？能否提供GIF或者录屏？

就是整个文章上下页面上下跳动，类似拉着右侧的滑动条上下快速拖一样，这个现象是在文本内内容较多右侧出现滑动条，且前面内容有一些非普通文字的内容的时候（比如标题，表格等）。
GIF或者录屏的话，我研究下怎么传上来哈。

另外，电脑配置：
CPU:11800H 8核
内存：16G
操作系统：WIN11 家庭版本（正版）
Mark Text 版本：v0.16.3

谢谢！

**Comment by YalandHong** [comment]
这个问题可能已经有人提过了：#2470

MarkText在编辑最后一行的时候，滚动条会向前跳动。这是个BUG。

如果你碰到了一样的问题，请关闭这个issue，把你的问题反馈到#2470，谢谢！

**Comment by wealthz01** [comment]
Who can help me rectify my account

**Comment by ClarenLee** [comment]
> 

好的，我看了#2470是一样的问题。

**Comment by ClarenLee** [comment]
问题和[#2470](https://github.com/marktext/marktext/issues/2470)一样
