### ISSUE TITLE
【建议】是否可以匹配简体中文呢？

### ISSUE THREAD

**Issue by fhmohen** [marktext/marktext#2734]
This project is one of the most beautiful markdown note taking software I have ever used, and my operating habits are also very comfortable. However, I do not understand English and do not use it very smoothly. In this case, many Chinese people encounter this problem, so I hope to match the simplified Chinese version. I am willing to undertake the translation work (I will use the translation software to assist), I hope more Chinese people can know and like marktext @Jocs

**Comment by YalandHong** [comment]
Duplicate of #138 

----

开发者的话（#138）：
>可能需要等到 v1.0.0 版本发布以后，到时候我会再开一个仓库用来做 Mark Text 国际化。

>很高兴大家的持续关注，一直没有国际化的原因是，目前我们认为 MarkText 还不够稳定，还有很多新的功能需要添加，菜单选项也会调整，因此目前不是一个很好的国际化时机，但是应该不会太长时间了，我和开发团队的其他成员已经沟通，我们依然对 MarkText 抱有热情和期望。

**Comment by wealthz01** [comment]
I need help on the China wallet

**Comment by fhmohen** [comment]
> #138的副本
> 
> 开发者的话（#138）：
> 
> > 可能需要等到 v1.0.0 版本发布以后，到时候我会再开一个仓库用来做 Mark Text 国际化。
> 
> > 很高兴大家的持续关注，一直没有国际化的原因是，目前我们认为 MarkText 还不够稳定，还有很多新的功能需要添加，菜单选项也会调整，因此目前不是一个很好的国际化时机，但是应该不会太长时间了，我和开发团队的其他成员已经沟通，我们依然对 MarkText 抱有热情和期望。

是很值得~

**Comment by fhmohen** [comment]
> I need help on the China wallet

You can contact my email seeyyy@qq.com

**Comment by junchao98** [comment]
This is a great markdown editor, looking forward to his upgrade

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #138. You may want to subscribe there for further updates.

**Comment by gpchn** [comment]
I love this so much! Looking forward to Chinese updates!
