### ISSUE TITLE
add `Custom Command` as image-uploader

### ISSUE THREAD

**Issue by thep0y** [marktext/marktext#2737]
### Describe your feature request

Add `Custom Command` as image-uploader.

like `typora`:
<img width="714" alt="屏幕截图 2021-12-05 163838" src="https://user-images.githubusercontent.com/51874567/144739762-c9bd4c1a-42b2-480f-96dd-1421243fd97e.png">

Test Result:
<img width="716" alt="屏幕截图 2021-12-05 164713" src="https://user-images.githubusercontent.com/51874567/144739859-cca9c711-5fb6-4696-b5a6-0721e6cb8457.png">

Upload an image:
![upload](https://cdn.jsdelivr.net/gh/thep0y/image-bed/md/1638709355927732.png)

我不打算提交pr，因为这个仓库已经常年未发布新release了

windows版下载链接：
https://www.aliyundrive.com/s/ta6CS1qsxCi

**Comment by YalandHong** [comment]
Duplicate of #2687

同时，如果有PR可以修复这个问题，请务必提交。开发者虽然最近很少有时间更新，但情况只是暂时的。并且这个仓库的PR本来就少，更多的PR也可以减轻开发者的负担。感谢支持！

**Comment by thep0y** [comment]
> Duplicate of #2687
> 
> 同时，如果有PR可以修复这个问题，请务必提交。开发者虽然最近很少有时间更新，但情况只是暂时的。并且这个仓库的PR本来就少，开发者仍然会抽空合并PR。更多的PR也可以减轻开发者的负担。感谢支持！

我能看见有合并pr，但一年都没有发布release，合并了pr短期内也没什么用，毕竟不能要求所有使用者都自行编绎吧？

**Comment by Indosaram** [comment]
+1 to this change. It can be very handy because I'd rather upload my images directly to my private blog.

**Comment by thep0y** [comment]
> +1 to this change. It can be very handy because I'd rather upload my images directly to my private blog.

This is the windows installer compiled after adding `Custom Command` option, if you are interested, you can try it.
https://www.aliyundrive.com/s/ta6CS1qsxCi

**Comment by YalandHong** [comment]
> > 如果有PR可以修复这个问题，请务必提交。开发者虽然最近很少有时间更新，但情况只是暂时的。并且这个仓库的PR本来就少，开发者仍然会抽空合并PR。更多的PR也可以减轻开发者的负担。感谢支持！
> 
> 我能看见有合并pr，但一年都没有发布release，合并了pr短期内也没什么用，毕竟不能要求所有使用者都自行编绎吧？

开发者的话：https://github.com/marktext/marktext/issues/2744#issuecomment-994920982

>我们最近会发布一个小版本更新，修复了一些问题，同时确实我们是在重构编辑器，这是一个比较漫长的过程。

目前，第三方image uploader还不在MarkText的计划中。所以，PR越早提交，问题越有可能早点修复。如果你打算过一段时间再PR也没关系，但用户们就可能要再过好几个版本才能享受到这个功能了。感谢你对MarkText的关注和支持！

**Comment by thep0y** [comment]
> 目前，第三方image uploader还不在MarkText的计划中。所以，PR越早提交，问题越有可能早点修复。如果你打算过一段时间再PR也没关系，但用户们就可能要再过好几个版本才能享受到这个功能了。感谢你对MarkText的关注和支持！

提交pr了，merge 后再关闭这个 issue 吧。

**Comment by fxha** [comment]
This feature was implemented in #2100 and will be available in our next release.
