### ISSUE TITLE
Can not use global search(ctrl+f) to jump to the location of keyword.

### ISSUE THREAD

**Issue by YYorozuya** [marktext/marktext#2738]
### Description

![9WUT_YM ~}~AMS TXCTL2}8](https://user-images.githubusercontent.com/38746589/144773894-83d5c0b8-3c56-4fb7-b4fe-5ce2be5dbb92.png)

### Versions

- Mark Text version: 0.16.3
- Operating system: Windows 10

**Comment by YalandHong** [comment]
Possible dup of #1775 and #2424

In order to reduce duplications, please close this issue and report your problems there. Thanks!
