### ISSUE TITLE
Support export docx and picture

### ISSUE THREAD

**Issue by liukangcc** [marktext/marktext#2739]
### Describe your feature request

This is a very useful software, but the export function supports a little less variety. 

Please support export docx file, image and some other format .  Thanks.

Are there plans to support exports in other formats

**Comment by YalandHong** [comment]
**Export to docx**: Dup of #2103

**Export to images**: This needs to be dicussed. (#1807). I don't think MarkText team are going to implement that because you can convert your PDF to image using other tools. Maybe they'll leave this to the plugins.

**Comment by Jocs** [comment]
close due to dup of #2103
