### ISSUE TITLE
文字选中状态自动变为未选中状态

### ISSUE THREAD

**Issue by faimin** [marktext/marktext#274]
### Description

在代码段内选中某段想删除的文本时，当松开鼠标打算按`delete`删除时，已选文字自动变为未选中状态。好像是自动调用了`Edit`选项中的某个操作，因为能看到桌面`Edit`按钮那里出现闪动。非必现问题，但是出现几率也挺高的。

### Steps to reproduce

1. 在代码段中选中一部分的文字
2. 松开鼠标按键
3. 已选中的文字自动变为了未选中状态

**Expected behavior:** 希望已选中文字不会被自动重置为未选中状态

### Versions

- Mark Text:    **v 0.10.21**
- OS:   **Mac OS 10.13.4**

**Comment by Jocs** [comment]
@faimin 我刚才也试了，这应该是一个 bug。现在你可以这样做，先将光标移动到代码块，然后在选择你要删除的内容。这样 selection 就不会消失了。后续版本我们会 fix 这个问题。

谢谢！

**Comment by faimin** [comment]
@Jocs OK, thanks ❤️
