### ISSUE TITLE
shortcut to operate whole line

### ISSUE THREAD

**Issue by jinmingyi1998** [marktext/marktext#2740]
### Describe your feature request

move or duplicate selected lines like `alt + (up/down)`
insert/delete tab on selected lines `tab`

### What problem does this feature solve? [optional]

fit users habbits

### Additional context [optional]

this is a common feature on Most Editors

**Comment by jinmingyi1998** [comment]
[!2533](https://github.com/marktext/marktext/issues/2533)

i just found a similar issue

**Comment by ouyangtianhan** [comment]
https://github.com/marktext/marktext/issues/2715

**Comment by Jocs** [comment]
duplicated with #2533
