### ISSUE TITLE
Source code shortcuts（ALT+CTRL+S） are useless

### ISSUE THREAD

**Issue by szzhh** [marktext/marktext#2742]
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text version:
- Operating system:

**Comment by YalandHong** [comment]
More info is needed. Please provide screenshot, video or describe how to reproduce your problem.

----

你的问题描述很不详细。请提供更多信息，比如截图、录屏或者具体操作的步骤。

**Comment by szzhh** [comment]
按下转换源码快捷键（ALT+CTRL+S）后，系统不发生任何变化，即这个快捷键没有用

**Comment by YalandHong** [comment]
I can't reproduce on my Windows 10. Ctrl+Alt+S does work. Please check if there's any shortcut conflict in your system.

----

我无法复现这个问题。在我的Windows 10上，Ctrl+Alt+S可以正常工作，如下图所示。请确保你的快捷键没有和其它应用冲突。

![2021_12_09_14_38_59](https://user-images.githubusercontent.com/52960068/145347477-d5450252-19df-466a-81c8-6f5fd6a24918.gif)

**Comment by szzhh** [comment]
我使用的是Win11系统，不知道是否兼容

**Comment by szzhh** [comment]
并且我看到了好几个人反映了这个问题

**Comment by whiteS18** [comment]
> I can't reproduce on my Windows 10. Ctrl+Alt+S does work. Please check if there's any shortcut conflict in your system.
> 
> 我无法复现这个问题。在我的Windows 10上，Ctrl+Alt+S可以正常工作，如下图所示。请确保你的快捷键没有和其它应用冲突。
> 
> ![2021_12_09_14_38_59](https://user-images.githubusercontent.com/52960068/145347477-d5450252-19df-466a-81c8-6f5fd6a24918.gif)

插个题外话，这种能在屏幕上显示最近按键的软件叫什么？

**Comment by YalandHong** [comment]
> 插个题外话，这种能在屏幕上显示最近按键的软件叫什么？

There's a lot of tools with similar features. I'm using carnac here. 

----

这种软件有很多。我这里用的是carnac。

https://github.com/Code52/carnac

**Comment by whiteS18** [comment]
> 这种软件有很多。我这里用的是carnac。
> 
> https://github.com/Code52/carnac
昨天尝试了下，用着用着就自动退出了。

**Comment by YalandHong** [comment]
Reproduced on Ubuntu 20.04.2. `Ctrl+Alt+S` does not work. ( #2348 ).

----

在我的Ubuntu 20.04上存在这个问题。Ctrl+Alt+S不起作用。

![marktextBug](https://user-images.githubusercontent.com/52960068/145674970-f618cbaa-7503-40b6-9f37-9b06fa7d667c.gif)

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2370. You may want to subscribe there for further updates.
