### ISSUE TITLE
什么时候出新版本呢？

### ISSUE THREAD

**Issue by hu76589** [marktext/marktext#2744]
release 0.16.3还是2020年12月份放出来的，到现在接近1年了，不知道新的release什么时候会出来？难道没有新的版本了？希望能尽快发布一个新的版本，修复一下目前存在的一些问题，比如点击大纲无法跳转的问题、输入文字的时候页面抖动等。

**Comment by szzhh** [comment]
你好，你的这个快捷键有用吗（ALT+CTRL+S），我这里不起作用

**Comment by zero-hugo** [comment]
这软件是不是放弃了啊？都一年没更新了。

**Comment by fhmohen** [comment]
代码有更新，只是没有出发行版

**Comment by hu76589** [comment]
是啊，代码更新的还挺勤，不知道为什么不出发行版，是在憋大招，还是让我们自己构建？

**Comment by fhmohen** [comment]
我自己建过环境，安装依赖就安装不上了，总是出错！

**Comment by fhmohen** [comment]
MarkText这个软件是目前为止，最接近Typora的一款开始项目了，是我最喜欢的项目，没有之一~

**Comment by calan0117** [comment]
> 

应该是你的全局热键冲突了，建议检查QQ和输入法等全局快捷键。

**Comment by calan0117** [comment]
> 你好，你的这个快捷键有用吗（ALT+CTRL+S），我这里不起作用

可能是全局热键冲突了。

**Comment by pnqx** [comment]
我搞了个自动编译最新版本 https://github.com/pnqx/build-Mark-Text ，不过没感觉到新的和旧的有什么区别。

**Comment by DYH-Hong** [comment]
> 是啊，代码更新的还挺勤，不知道为什么不出发行版，是在憋大招，还是让我们自己构建？

憋大招当然是不太可能的，代码更新得并不勤快。2020年12月份出了0.16.3版本之后，MarkText的维护就几乎暂停了，2021这一整年基本上没有commit。

**Comment by Jocs** [comment]
我们最近会发布一个小版本更新，修复了一些问题，同时确实我们是在重构编辑器，这是一个比较漫长的过程。

We'll release a new version in the near future, fixed some issues, yeh, We are refactorring the core-editor muya in another repo, so the update of this repo will be slower.
