### ISSUE TITLE
Slider can't fix when edit YAML front matter block

### ISSUE THREAD

**Issue by kewtgh** [marktext/marktext#2750]
### Description

- [ ] Can you reproduce the issue? 

If the content of YAML front matter are to long it can't wrap automatically. Instead, it will use a slider to display the content. But if you edit the YAML front matter block, the slider won't fix and jump to the beginning position.
---
当YAML头信息过多时，头信息块会采用滚动条，而非自动换行显示内容，但是在编辑时，滚动条不能固定，只要输入一个字母，就会跳到初始位置，操作极为困难。

### Steps to reproduce

1. Insert the YAML front matter block of a markdown profile.
2. At any position of the YAML front matter block, input words, just like a "excerpt" content, till the slider appears.
3. Then slide to the right and edit the content of YAML.
4. Type any word it will jump to the beginning.

**Expected behavior:**

Fix the position of the slider when editing, or auto wrap.

**Actual behavior:**

Type any word it will jump to the beginning

### Versions

- Mark Text version: v0.16.3
- Operating system: Win10

**Comment by YalandHong** [comment]
Possible dup of #2151 and #2470.

The scrollbar of MarkText will constantly jump to the beginning, making the view flickers. This is considered as a bug.

If this helps, please close this issue and report your problems there. Thanks!

----

这个问题可能已经有人提过了： #2151  #2470

MarkText的水平/竖直滚动条存在频繁跳回开头的BUG，导致画面闪烁。

如果你碰到了一样的问题，请关闭这个issue，把你的问题反馈到#2151  #2470 。最好能够上传截图或录屏。谢谢！

**Comment by kewtgh** [comment]
Thank a lot!
