### ISSUE TITLE
How to add custom export themes with flatpak version?

### ISSUE THREAD

**Issue by seefrye** [marktext/marktext#2752]
Attempting to add a custom theme by following the instructions [here](https://github.com/marktext/marktext/blob/develop/docs/EXPORT_THEMES.md). However, I can't seem to find the correct directory. I am using the flatpack version. Any help would be much appreciated.

**Comment by fxha** [comment]
The settings are saved inside the `$XDG_CONFIG_HOME/marktext` directory. On flatpak, it should be something like `~/.var/app/com.github.marktext.marktext/config/marktext`.
