### ISSUE TITLE
Why can't this PR pass appveyor？

### ISSUE THREAD

**Issue by jhxqy** [marktext/marktext#2756]
### Question description

提示
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

What is the problem and how to deal with it?

https://github.com/marktext/marktext/pull/2755

**Comment by fxha** [comment]
Thanks for creating this issue. I think you mean that AppVeyor currently fails due to the given issue above? We changed from Travis CI/AppVeyor to GitHub Actions and still need to disable AppVeyor integration. Please keep issues and discussions in English, otherwise it's hard to work on it.

**Comment by jhxqy** [comment]
yes，AppVeyor currently fails due to the given issue above

**Comment by jhxqy** [comment]
I tried to reopen this pr, but it didn't work

**Comment by fxha** [comment]
Yeah, @Jocs has to disable the GitHub integration. I'm unfortunately unable to do so but if the issue remains I'll delete the Mark Text AppVeyor project. Just ignore the AppVeyor status and take a look at Github Actions.

**Comment by fxha** [comment]
AppVeyor is now finally disabled.
