### ISSUE TITLE
Font color for math blocks can't be changed

### ISSUE THREAD

**Issue by cbrasser** [marktext/marktext#276]
### Description

Math blocks are really hard to read in dark mode since one can't change the font color of those

### Steps to reproduce
 
1. Enable dark mode
2. Create Math block using $$[Math]$$

**Expected behavior:** The equation is rendered in a light color so that it is clearly visible

**Actual behavior:** The math equation is rendered in a black font, which makes it really hard to read in dark mode

### Versions

- Mark Text: 0.11.31
- OS: Xubuntu Linux

**Comment by fxha** [comment]
Thanks @cbrasser,

the issue is already fixed, but not yet released.

**Comment by cbrasser** [comment]
Just built the version on the master and noticed, nice thank you!
