### ISSUE TITLE
请问能不能设定默认开启边栏呢

### ISSUE THREAD

**Issue by WzyPaopao** [marktext/marktext#2762]

**Comment by calan0117** [comment]
如果你是说边栏是文件目录和大纲的话，在view中勾选Show Sidebar。

**Comment by fhmohen** [comment]
> 如果你是说边栏是文件目录和大纲的话，在view中勾选Show Sidebar。

问题是不保存，当下次打开后，还是隐藏的！

**Comment by calan0117** [comment]
> > 如果你是说边栏是文件目录和大纲的话，在view中勾选Show Sidebar。
> 
> 问题是不保存，当下次打开后，还是隐藏的！

我没有遇到这个问题，勾选去除都能正确的显示。重新安装一次试试。

**Comment by yuzhen1024** [comment]
> > 如果你是说边栏是文件目录和大纲的话，在view中勾选Show Sidebar。
> 
> 问题是不保存，当下次打开后，还是隐藏的！

重现该问题。
版本：v0.16.3

**Comment by YalandHong** [comment]
Duplicate of #2378

**Comment by fffffreedom** [comment]
最新版本也有该问题？

$ brew info mark-text
mark-text: 0.17.1

**Comment by MyLuoYu** [comment]
Linux(manjaro) marktext-bin v0.17.1-1也有这个错误
