### ISSUE TITLE
MarkText is a better name

### ISSUE THREAD

**Issue by miantianlai** [marktext/marktext#2763]
### Describe your feature request

MarkText is better than Mark Text. Can you change it for all the platforms?

### Additional context [optional]

Like MacVim, MacDown, remove the space is more readable, clean and professional. It's the same as MarkDown but just change a word to define a new powerful tool.

These names could be changed:

- Official site title
- Official site name
- Desktop app name
- Desktop app alt name

**Comment by Jocs** [comment]
Thank you for your suggestion, we will update in a later version
