### ISSUE TITLE
Image Relative Path

### ISSUE THREAD

**Issue by iWuYc** [marktext/marktext#2764]
### Describe your feature request
Dear developer for marktext:
 I paste an image to markdown document,the marktext using absolute path on "![] (c:/../task/assert/image.png)".when I move the task directory to another drive letter,example "d:",the markdown document absolute path change to "d:/../task/task.md",but the image can't show ,because it using absolute path also.
Can we try using relative path when paste image,like typora(example:"\!\[image\](./assert/image.png)"),or support choose option using relative path or not.
Thank you for your contribution!!

**Comment by YalandHong** [comment]
Dup of #2560 and #2652

**Comment by fxha** [comment]
@iWuYc You can select this behavior under via `Settings -> Image`. Select "Move to designated local folder" and activate "Prefer relative assets folder".
