### ISSUE TITLE
not change file, but show save of prompt.

### ISSUE THREAD

**Issue by yuzhen1024** [marktext/marktext#2766]
- [x] Can you reproduce the issue? 
- Mark Text version: v0.16.3
- Operating system: windows

没有对文件进行任何更改，但退出时显示“是否保存”的选项。
not change file, but show save of prompt.

![2021-12-15](https://user-images.githubusercontent.com/47154428/146088477-ec2844c8-0678-4b8d-97db-1e419497bc9f.jpg)

**Comment by calan0117** [comment]
应该是一些自动格式化的。
我的md放在了git中，使用mark text 打开后会有：标题删除多余空格，相邻代码块加空格的操作。提示你是否保存变更。

**Comment by YalandHong** [comment]
Duplicate of #2189

**Comment by YalandHong** [comment]
> 应该是一些自动格式化的。 我的md放在了git中，使用mark text 打开后会有：标题删除多余空格，相邻代码块加空格的操作。提示你是否保存变更。

Right. This is caused by auto formatting: https://github.com/marktext/marktext/issues/2189#issuecomment-761855902 https://github.com/marktext/marktext/issues/2189#issuecomment-719302298
