### ISSUE TITLE
Second entry, unable to enter the situation

### ISSUE THREAD

**Issue by jCodeLife** [marktext/marktext#2767]
### Question description
安装后成功进入了，未做任何操作的情况下，点击关闭，提醒保存，我选择不保存。之后我再打开，就一直卡在卡在这个页面，进不去，系统是win7 64

![image](https://user-images.githubusercontent.com/50767049/146293507-5e49db43-24cc-4d36-b8cc-7e685987e45e.png)

**Comment by jCodeLife** [comment]
后来进去了，但是每次进去都很久，试过10+次了，有人跟我一样的情况吗

**Comment by DYH-Hong** [comment]
Possible dup of #2300 and #2638

Currently, MarkText is not very efficient and has lots of performance issues, such as slow startup and lagging.

目前MarkText的性能优化得不好，存在启动慢、大文件速度慢等问题。
