### ISSUE TITLE
点击大纲，无法跳转

### ISSUE THREAD

**Issue by yuanleyuanleyuan** [marktext/marktext#2768]
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text version:
- Operating system:

**Comment by DYH-Hong** [comment]
Duplicate of #2736
