### ISSUE TITLE
关于图片自动上传

### ISSUE THREAD

**Issue by klnsGenesis** [marktext/marktext#2785]
### Describe your feature request

能否在MacOS版本中加入uPic图床上传的功能，这样就能使用阿里云oss和别的oss了

### What problem does this feature solve? [optional]

解决了现有免费只能上传5MB的窘境

这是uPIC的官网：https://blog.svend.cc/upic/

![image](https://user-images.githubusercontent.com/65278566/147348678-c96e298d-138a-4c75-bb3e-10d05b921b43.png)
![image](https://user-images.githubusercontent.com/65278566/147348704-439283a1-f147-4b16-822c-828deae82771.png)

**Comment by Jocs** [comment]
This feature may be provided by the plugin function, so please submit your feature request to this #375
