### ISSUE TITLE
Map Preferences Shortcut to Something Other than Control-Comma?

### ISSUE THREAD

**Issue by loyukfai** [marktext/marktext#2793]
### Describe your feature request

Map Preference Shortcut to Something Other than Control-Comma

### What problem does this feature solve? [optional]

Under Windows' Chinese input method, Control-Comma is used to enter the full-width comma sign

**Comment by loyukfai** [comment]
As an individual workaround it's easily overridden with the below content following this (https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md) instruction.
```
{
  "file.preferences": ""
}
```
Cheers.

**Comment by bolshoytoster** [comment]
I don't think it's worth changing the default shortcut and interfering with a lot of people just to accommodate for one keyboard. It's probably best to keep it the way it is, where you can change it if you want.

**Comment by loyukfai** [comment]
Agree. Perhaps I'll make it a feature request to have keybindings easily adjusted via GUI instead.

Cheers.

**Comment by bolshoytoster** [comment]
@loyukfai that sounds like a good idea.

**Comment by loyukfai** [comment]
Done https://github.com/marktext/marktext/issues/2801
