### ISSUE TITLE
Custom Keybindings in Preferences Page

### ISSUE THREAD

**Issue by loyukfai** [marktext/marktext#2801]
### Describe your feature request

Currently, keybindings can be customized by editing KEYBINDINGS.md (https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md)

It will be more user friendly if it can be configured within the Preferences panel.

As an simple alternative, a button can be provided in the Preferences panel to open and edit the KEYBINDINGS.md file?

**Comment by YalandHong** [comment]
Duplicate of #2730
