### ISSUE TITLE
光标位置问题 Cursor position

### ISSUE THREAD

**Issue by wenkm** [marktext/marktext#2802]
### Description
当进行回退删除的时候，光标位置不对
When type backspace, the cursor get wrong place

**Comment by YalandHong** [comment]
More info is needed. Please provide screenshot, video or describe how to reproduce your problem.

----

你的问题描述很不详细。请提供更多信息，比如截图、录屏或者具体操作的步骤。

**Comment by wenkm** [comment]
https://user-images.githubusercontent.com/3335540/147997390-c474511c-6dec-4f22-9031-b893ac572b32.mp4

上次录屏有隐私信息，删了。重新录了一下。
版本：v0.16.3

**Comment by wenkm** [comment]
> More info is needed. Please provide screenshot, video or describe how to reproduce your problem.
> 
> 你的问题描述很不详细。请提供更多信息，比如截图、录屏或者具体操作的步骤。

代码编辑的时候。换行，输入空格，然后回退删除，就会出现问题

**Comment by YalandHong** [comment]
Dup of #2013
