### ISSUE TITLE
打开一个新文件，不做任何动作，仍然会有文件修改操作

### ISSUE THREAD

**Issue by a358003542** [marktext/marktext#2804]
打开一个新文件，不做任何动作，仍然会有文件修改操作。我比较了一下，主要是一些多余空行的删除，虽然这很好，但在git版本控制环境下，这个多余的文件修改动作还是很让人困惑【我第一次尝试这个软件就被这个劝退的，怕这个软件不可控。】。个人觉得这个默认的修改动作还是很值的商榷的。

marktext version: 0.16.3

**Comment by hedonihilist** [comment]
我也遇到了这个问题，多余空行好像会被合并成一个空行，找了一下好像没有对应的配置项？

最好能增加一个配置项用来控制是否默认合并多余空行，否则存储和再次打开的时候文件内容不一样确实容易让人困惑，并且有种不安全的感觉。

version: v0.16.3 (473b79af)

**Comment by hedonihilist** [comment]
好像这个问题有点久了： #2189

**Comment by Jocs** [comment]
Closed as duplicated with https://github.com/marktext/marktext/issues/2189.
