### ISSUE TITLE
操作标题头，目录没有很好地更进状态

### ISSUE THREAD

**Issue by a358003542** [marktext/marktext#2805]
比如将标题头从H2变成H3，目录那里对应的标题会有更新，不过对应的标题前面会有多余的 `###` 这样的符号，重新打开文件后这些 `###` 符号会消失。

marktext version: 0.16.3

**Comment by fxha** [comment]
@Jocs Could you please translate this and add translation required labels otherwise :smile:

**Comment by AnClark** [comment]
> Could you please translate this and add translation required labels otherwise smile

Let me help you:

## TOC doesn't update properly when modifying headers

For example, when changing header from H2 to H3, TOC updates, but with unneeded symbols like `###`. Those symbols disappears when reopening files.
