### ISSUE TITLE
shortkey customization feature needed. 快捷键自定义功能。

### ISSUE THREAD

**Issue by a358003542** [marktext/marktext#2806]
希望这个编辑器能够增加快捷键自定义功能。

Hope this editor can add shortkey customization feature.

version: 0.16.3

**Comment by x1angli** [comment]
+1 for this feature

really wish the hotkeys can be customized. 
in particular, i'd like to press Ctrl + H to bring up the replacement dialog

**Comment by Jocs** [comment]
@a358003542 @x1angli Do you mean [key bindings](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md)?
