### ISSUE TITLE
Image path supports variables, such as file name

### ISSUE THREAD

**Issue by ruanhailiang** [marktext/marktext#2809]
Can add the function of image path support variable, like "typora", such as creating a folder with file name as a unit to store images, for example:
./images/${filename}

**Comment by bolshoytoster** [comment]
How would the variables be defined? I couldn't find any mention of variables in typora's documentation.

**Comment by ruanhailiang** [comment]
![image](https://user-images.githubusercontent.com/15086045/147518204-f562d2ad-16f5-4bb9-9f49-b08d598df30f.png)

**Comment by bolshoytoster** [comment]
I’ve opened a pr that adds support for this.
