### ISSUE TITLE
Add option to format source text with semantic linefeeds

### ISSUE THREAD

**Issue by derekbeau** [marktext/marktext#281]
Feature request / request for comments. If there is agreement on this I could try my hand at implementing it.

### Description

Add a setting to automatically format source text with semantic linefeeds.

### Steps to reproduce

When writing in the default/preview mode, pressing `Return` key for a new line automatically inserts two line breaks into the source. This is desired and expected behavior for hassle-free writing, but removes a bit of control.

### Supporting resources

For reasons why this would be desired, please see the following links:

- http://rhodesmill.org/brandon/2012/one-sentence-per-line/
- https://github.com/cllns/semantic_linefeeds

>By starting a new line at the end of each sentence, and splitting sentences themselves at natural breaks between clauses, a text file becomes far easier to edit and version control. Text editors are very good at manipulating lines — so when each sentence is a contiguous block of lines, your editor suddenly becomes a very powerful mechanism for quickly rearranging clauses and ideas.

**Comment by Jocs** [comment]
@derekbeau Hi, Thank you very much for your proposal. There is a new feature in our next release version, [Soft line break](https://github.github.com/gfm/#soft-line-breaks) and [hard line break](https://github.github.com/gfm/#soft-line-breaks). You can insert a soft line break after punctuation with shift + enter. I'm not quite sure if this is what you want? But does this actually implement linefeeds?

Anyway, you can clone the source codes and build the latest commit version to use these new features.

Also, we hope more people to contribute their codes and ideas to Mark Text.

**Comment by derekbeau** [comment]
The visual soft line break would be implemented by a double space after the line in the source, correct?

With the semantic linefeed, the visual output would read as paragraphs, since markdown does not make a new line unless it is followed by two spaces. In this case, it would be compatible with the new features you mentioned above.

The result is that humans can read the formatted text just as intended, whille the source would be more compatible with version control diffs and collaboration.

I have forked the repo and started going through the code. If I can implement a quick demo, I’ll share it here for review before working on a proper refactored solution and moving towards a PR.

**Comment by Jocs** [comment]
>The visual soft line break would be implemented by a double space after the line in the source, correct?

A line break (not in a code span or HTML tag) that is preceded by two or more spaces and does not occur at the end of a block is parsed as a hard line break (rendered in HTML as a <br /> tag)

>I have forked the repo and started going through the code. If I can implement a quick demo, I’ll share it here for review before working on a proper refactored solution and moving towards a PR.

OK! Thanks, if you need some help or confused with the source code, you can ask question here, I am very willing to answer your questions.

**Comment by derekbeau** [comment]
@Jocs do you have a VSCode `launch.json` configuration or some advice on another way I can properly run a debugger and step through the code?

Not sure if the issues I'm having are related to `electron-vue` or something else, but I can't get VSCode or WebStorm to load the source maps and use original source for stepping through.
