### ISSUE TITLE
Sidebar file icons missing

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2813]
### Description

@Jocs Updating the file-icons in PR #2775 broke the whole file icon preview in the sidebar. Currently no icons are shown.

### Steps to reproduce

1. Open a folder.

**Link to an example: [optional]**

![](https://user-images.githubusercontent.com/22716132/147476530-209fa43e-1541-4a64-a09e-221cddc9dabd.png)

### Versions

- MarkText version: 0.16.3-dev (8af9605e)
- Operating system: all

**Comment by Jocs** [comment]
@fxha I'll submit a PR to fix it.
