### ISSUE TITLE
"delete" shortcut on a selected image deletes the text after it

### ISSUE THREAD

**Issue by x1angli** [marktext/marktext#2816]
### Description

image deletion

### Steps to reproduce

1. Insert an image
2. Select that image 
3. Hit "Del" key or "Ctrl + X" to delete the image
4. Then, it's the following text that gets deleted, not the intended image

**Expected behavior:**
the selected image should be deleted

**Actual behavior:**
the following text/character will be delete

**Link to an example: [optional]**

### Versions

- MarkText version: v0.16.3
- Operating system: Win10

**Comment by YalandHong** [comment]
Your title is kind of misleading. The proper title should be *`Delete` selected image deletes the text after it*.

Reproduced on my Ubuntu 20.04.3, using MarkText 0.16.3.

![delBug](https://user-images.githubusercontent.com/52960068/147728174-cae95c29-42fd-43cc-add1-fb1faf974956.gif)

**Comment by x1angli** [comment]
Thanks for sharing the gif image 
And yup, I changed the title to make it more clear
