### ISSUE TITLE
Automatic image reload feature

### ISSUE THREAD

**Issue by kiyoka** [marktext/marktext#2828]
### Describe your feature request

I want images to reload automatically when they are edited.

### What problem does this feature solve? [optional]

When I write application operation instructions, I paste many screen capture from the clipboard into Mark Text.
Then I edit the image file to make the document easier to understand.
It looks like this.

- original capture image

![search1](https://user-images.githubusercontent.com/80378/147804402-7aedd4f8-bc47-4ea8-b008-9e62aa1b621b.png)

- edited with paint.exe

![search2](https://user-images.githubusercontent.com/80378/147804405-6ce270ed-f47a-4e08-91a1-a1aab241cfdf.png)

However, the image on Mark Text does not change after saving with paint.exe.
Unfortunately, in the current version, I have to restart Mark Text to reload the image.

### Additional context [optional]

I think it is possible to use a periodic timer to check the update time of image files.

**Comment by YalandHong** [comment]
Dup of #703

In order to reduce duplications, please close this issue and report your problems there. Thanks!

**Comment by kiyoka** [comment]
> Dup of #703
> 
> In order to reduce duplications, please close this issue and report your problems there. Thanks!

Thanks.
This issue is the duplication of #703 .
