### ISSUE TITLE
How about u adjust the edit area blank space 

### ISSUE THREAD

**Issue by bowuL** [marktext/marktext#2830]
While i am typing, u can see the blank space of the left and right, it takes up much area, i think. And we can't define the css, so i suggest reduce the waste,.
thx, and wait for ur reply

**Comment by bowuL** [comment]
![image](https://user-images.githubusercontent.com/41602940/147809113-60f36d63-ff84-4d08-8af7-2a9797aae521.png)

**Comment by bowuL** [comment]
I don't understand this area use for what

**Comment by DYH-Hong** [comment]
Dup of #2654. Check the comments there.

----

这个问题已经有人提过了（#2654），并且有相应的解决方案。
