### ISSUE TITLE
'marktext' is not recognized

### ISSUE THREAD

**Issue by KikeVen** [marktext/marktext#2831]
### Question description

I installed it with choco on Windows 10. It is installed, but when I call it, it gives me the following message.

```cmp
C:\Users\x>marktext
'marktext' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by fxha** [comment]
Hi, Chocolatey is a third-party distributor but I guess the binary is called `Mark Text.exe` on Windows. It should be added to the start menu by default. Please contact the Chocolatey package maintainer for further questions.
