### ISSUE TITLE
Save header and footer for PDF export

### ISSUE THREAD

**Issue by tomoem** [marktext/marktext#2844]
### Question description

Is there a way to save the header and the footer for the next time we export of the same markdown document to PDF (or at least for all exports)?
I see that MarkText supports Front Matter. It's possible to define this settings in the Front Matter? I've searched the documentation, but didn't find anything about it. In some editors is possible to define something like this to be taken in account by the export feature:

```
---
title: Sample Title
header: Sample Header
footer: Sample Footer
---
```

Thanks

**Comment by fxha** [comment]
Hi @tomoem, currently the information are only saved at runtime but I think it's an improvement to load the information from the document if possible.
