### ISSUE TITLE
In long text, when I click outline catalog title, I can not jump to the corresponding text location.  

### ISSUE THREAD

**Issue by xxxhycl2010** [marktext/marktext#2856]
In long text, when I click outline catalog title, I can not jump to the corresponding text location.

**Comment by YalandHong** [comment]
More info is needed. Please provide screenshot, video or describe how to reproduce your problem.

Possible dup of #1775.

----

你的问题描述很不详细。请提供更多信息，比如截图、录屏或者具体操作的步骤。

这个问题可能已经有人提过了（#1775）。
