### ISSUE TITLE
Ctrl+T is not working after 2 tables

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#286]
### Description

`Ctrl+T` is not working after 2 tables.

### Steps to reproduce

1. Create first table: `Ctrl+T`
2. Create second table: `Ctrl+T`
3. Write some text (optional)
4. Try to create another table: `Ctrl+T`

**Expected behavior:**

That I can create another table.

**Actual behavior:**

Nothing happens...

### Versions

- Mark Text: master (2b05619)

**Comment by Jocs** [comment]
@fxha I can create three tables?
![table](https://user-images.githubusercontent.com/9712830/40304252-855a5b5a-5d28-11e8-9d35-e8a788721545.jpg)

**Comment by fxha** [comment]
You are right. I have to wait for 1-2 seconds after I type in text. I think we should reduce the 1s time-out  you added a bit. I had a similar problem with saving files. E.g. you type in text, press `Ctrl+S` and close Mark Text, but the document is not saved because of the 1s time-out.

**Comment by Jocs** [comment]
@fxha I'll handle this in next commit. 👍
