### ISSUE TITLE
Shift+Tab doesn't work

### ISSUE THREAD

**Issue by jin8495** [marktext/marktext#2865]
### Description
Un-indent is not working.
I've seen the changelog and issue #2466, it said that the "Shift+Tab" feature is added. However, still not working.

- [x] Can you reproduce the issue?

### Steps to reproduce
Just pushing tab, and shift+tab.

**Expected behavior:**

When I press "shift+tab", a line should be un-indented

**Actual behavior:**

Pressing "shift+tab" makes a line get indent one more level.

### Versions

- MarkText version: v0.16.3
- Operating system: Windows 11 (x64)

**Comment by DYH-Hong** [comment]
This feature will be added in the next stable version.

v0.16.3 is actually a very old version, released in 2020.

**Comment by 827551331** [comment]
Current version is v0.17.1 ，the issue have not fixed, shift + tab not work yet

**Comment by cnmicha** [comment]
Same issue here when using todo lists, version 0.17.1.

@fxha Could you please re-open the issue?
