### ISSUE TITLE
Disable titleBar

### ISSUE THREAD

**Issue by GambitFPS** [marktext/marktext#2866]
### Question description

Is there a way to disable the titleBar? Maybe via .css? 
![grafik](https://user-images.githubusercontent.com/54640740/148861799-8d0c46f8-2c29-4c17-b33f-1288232ab35b.png)

**Comment by DYH-Hong** [comment]
Unfortunately I don't think there's any setting that allows you to do so.

But you can upvote these issues: #1847 #1238

**Comment by fxha** [comment]
@GambitFPS Unfortunately, currently not but you could build MarkText yourself and edit the style.
