### ISSUE TITLE
Cannot select an entire document if table is at the beginning

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#287]
### Description

Cannot select an entire document if table is at the beginning of the document.

### Steps to reproduce

1. Create a table at the beginning of the document
2. Write text in the first cell: `foo`
3. Write text behind table
4. `Ctrl+A` outside table

```
| foo |     |     |
| --- | --- | --- |
|     |     |     |

-->cusor here<--
```

**Expected behavior:**

Entire document is selected.

**Actual behavior:**

Entire document is selected, but without `f`.

### Versions

- Mark Text: master (2b05619)

**Comment by Jocs** [comment]
@fxha 

This bug is a little weird. If I release the `A` key first, then I can select all. If I release the `ctrl` key first, then I cannot select `f`.
D

**Comment by Jocs** [comment]
@fxha 

This bug is a little weird. If I release the `A` key first, then I can select all. If I release the `ctrl` key first, then I cannot select `f`.
D

**Comment by fxha** [comment]
Well, I do not know... Maybe problem with key-down listening?

**Comment by Jocs** [comment]
@fxha I found that this issue has been fixed?
