### ISSUE TITLE
Unwanted style block after pasting from Microsoft Word

### ISSUE THREAD

**Issue by cloudy-sfu** [marktext/marktext#2873]
### Description

<img src="https://user-images.githubusercontent.com/41314224/149132922-c66a5792-7010-4a6a-ab31-f2ebc1dd71b1.png" alt="..." width="400px">

When I copy a paragraph from Microsoft Word and paste it to Marktext, there is an unwanted <style> block before the paragraph, as shown in the image above.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step] Write a paragraph in Microsoft Word.
2. [Second step] Paste the paragraph to Marktext.
3. [and so on...] An unwanted <style> block appears.

**Expected behavior:**

**Actual behavior:** No unwanted <style> appears.

**Link to an example: [optional]**

### Versions

- MarkText version: v0.16.3
- Operating system: Windows 10 64-bit, Microsoft Word 2021 LSTC

**Comment by fxha** [comment]
Thanks for reporting the issue, have you tried to paste the content as plain text with `Ctrl+Shift+V`? This should remove all rich text from the text that was added by other applications.

**Comment by cloudy-sfu** [comment]
> Thanks for reporting the issue, have you tried to paste the content as plain text with `Ctrl+Shift+V`? This should remove all rich text from the text that was added by other applications.

Thank you. With `Ctrl+Shift+V`, the rich text is removed. It's helpful, but sometimes users want to remain formats like "bold" or "italic". If pasting with `Ctrl+Shift+V`, these formats will be lost too.

If convinient, I hope this feature can be added to future release; or if it costs a lot, keeping the software's current behavior is good.
