### ISSUE TITLE
How can I make the text space wider?

### ISSUE THREAD

**Issue by Yush08** [marktext/marktext#2884]
I'm currently switching from Typora and I'm absolutely *loving* MarkText. Typora went paid and wasn't open source to begin with and Obsidian didn't have the features I used like Sequence diagrams

Just had a question, How can I make the text space wider? I don't particularly like each line being this small. Hope you understand :)
![image](https://user-images.githubusercontent.com/93856041/149347001-00068f6d-08d7-4bb6-9acb-60db074c51a2.png)

**Comment by fxha** [comment]
You can change the maximum width of the editor area under Editor and choose a "Maximum with of text editor" like `110ch`. See https://github.com/marktext/marktext/issues/2654#issuecomment-945149376.
