### ISSUE TITLE
Copy table in preview mode as formatted markdown

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#289]
We want to copy a table in preview mode as formatted markdown table. Let's say we want to copy the following table:

| a   | b   | c   |
| --- | --- | --- |
| d   | e   | f   |

At the moment we receive `abcdef`, but we want a well-formatted markdown table like:

```
| a   | b   | c   |
| --- | --- | --- |
| d   | e   | f   |
```

**Comment by Jocs** [comment]
@fxha I find that we can copy whole table, if we put end cursor out of table when we select table, but I think it will make user confused.

![out](https://user-images.githubusercontent.com/9712830/41107893-d6f9a166-6aa5-11e8-9e08-90967c7c6573.gif)

**Comment by Jocs** [comment]
@fxha Do you have any idea to improve user experience, I think add a copy button in the table tool bar to copy the whole table as markdown format?
