### ISSUE TITLE
GitHub Specific Emoji Support

### ISSUE THREAD

**Issue by jrbgit** [marktext/marktext#2896]
Issue #1677 reported as a bug could be addressing this.

I think it is more of a feature than a bug, but feel free to recategorize/link/or close.

### GitHub Specific Emoji's

🟢 `:green_circle:` did not render when I opened a document. However, 🔴 `:red_circle:` did render correctly. I know that there are some GitHub specific emoji's - so, it would be nice to see full support for them

**Comment by Jocs** [comment]
We use this json file https://github.com/github/gemoji/blob/master/db/emoji.json, and haven't update it for a long time. we'll create a npm package to maintain emojis used in marktext later.
