### ISSUE TITLE
Image relative path is relative to root folder that you open, not the file.

### ISSUE THREAD

**Issue by wiwikuan** [marktext/marktext#2901]
### Description

Image relative path is relative to the root folder that you open, not the file.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. In preferences → image, I set "Prefer relative assets folder" to "On", and Relative image folder name to `.`.
2. Let's say I have a project folder at `/project`, and I open that folder in Mark Text.
3. I then edit a file at `/project/some_folder/index.md`
4. I paste an image into it, and the image is copied to `/project/image.jpg` instead of `/project/some_folder/image.jpg`. 

**Expected behavior:**

When setting relative image folder, it should be relative to the markdown file itself (Typora does that), not the project root folder.

### Versions

- MarkText version: 0.16.3
- Operating system: macOS 10.14

**Comment by wiwikuan** [comment]
I saw in #2826 we added the `${filename}` variable, can we add `${currentFilePath}` and `${projectRootPath}`? That will easily solve this issue.

**Comment by fxha** [comment]
That's a good point and we should save the image relative to the opened file when a variable is used. This issue only occures if you opened a folder because all images are saved relative to the project root.
