### ISSUE TITLE
how to fix this 

### ISSUE THREAD

**Issue by qardac** [marktext/marktext#2903]
### Question description

when i try to download in IDM it asks me user and password 
what is that??????????????????
![Capture](https://user-images.githubusercontent.com/97979008/149992552-261fb440-33e5-4cf8-9d7e-fd2ce28c2b53.PNG)

**Comment by brainchild0** [comment]
The application is using Github as the storage location for document images. You need to select another storage back end if you do not wish to use Github.

**Comment by YalandHong** [comment]
What do you use IDM for? Are you downloading MarkText installer?

Although I have never used IDM, I found this from [StackOverflow](https://stackoverflow.com/questions/70634546/authorization-required-when-downloading-from-objects-githubusercontent-com):
>When you download a release asset from GitHub, the link redirects from the one you provided, using an HTTP 302, to objects.githubusercontent.com, using a special, **time-limited, signed** URL.

**Comment by qardac** [comment]
but i try to download from the website it self it is the same....

**Comment by qardac** [comment]
https://stackoverflow.com/questions/70634546/authorization-required-when-downloading-from-objects-githubusercontent-com was help full,
 please tell me how to download?

**Comment by qardac** [comment]
soory i downloaded thank all of you. it happens if the speed of your internet is not fast then that popup will show up but if the speed is great it will download. that is all.
![test1](https://user-images.githubusercontent.com/97979008/150065498-537f93c8-4448-4886-ab02-ecfef8d18d0d.PNG)
![test2](https://user-images.githubusercontent.com/97979008/150065503-2ad22aea-d15b-4bc8-9c54-7afedd2f6c00.PNG)

**Comment by fxha** [comment]
Seems to be solved.
