### ISSUE TITLE
when I type something, the editor will shaking

### ISSUE THREAD

**Issue by annanShao** [marktext/marktext#2904]
### Description

- [ x ] Can you reproduce the issue? 

### Steps to reproduce

1. type some lines to activate the scroll bar
2. scroll the bar to the bottom and type anything
3. you will see the shaking bug

**Expected behavior:**

fix this bug

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- MarkText version: v0.16.3
- Operating system: windows10

**Comment by YalandHong** [comment]
Dup of #2470, which will be fixed in the next release.

----

这个BUG已经被修复了。请等待下一个版本的发布。

**Comment by fxha** [comment]
This bug is already fixed on develop.
