### ISSUE TITLE
style show question

### ISSUE THREAD

**Issue by iti6** [marktext/marktext#2908]
### Question description
It looks like this on the MAC. Can I fill it up in the middle?
![http://www.xielianying.com/wp-content/uploads/2022/01/2022012002114260.png](http://www.xielianying.com/wp-content/uploads/2022/01/2022012002114260.png)

**Comment by YalandHong** [comment]
More info is needed. Please provide screenshot, video or describe how to reproduce your problem.

Do you want to change the text width or customize the theme/style?

----

你的问题描述很不详细。请提供更多信息，比如截图、录屏或者具体操作的步骤。

你是想要改变编辑区域的宽度吗？还是想改变主题和背景色？

**Comment by iti6** [comment]
> More info is needed. Please provide screenshot, video or describe how to reproduce your problem.
> 
> Do you want to change the text width or customize the theme/style?
> 
> 你的问题描述很不详细。请提供更多信息，比如截图、录屏或者具体操作的步骤。
> 
> 你是想要改变编辑区域的宽度吗？还是想改变主题和背景色？

是的，如何改变编辑区域的宽度？

**Comment by YalandHong** [comment]
https://github.com/marktext/marktext/issues/2654#issuecomment-945149376

**Comment by iti6** [comment]
> [#2654 (comment)](https://github.com/marktext/marktext/issues/2654#issuecomment-945149376)
thanks！
谢谢！
