### ISSUE TITLE
No results upon searching with Aidou

### ISSUE THREAD

**Issue by Ranoiaetep** [marktext/marktext#2909]
## No images shows up upon searching with Aidou

No result shows up with either manual input or using the random button.

### Actual behavior:
The Green Spinning animated loading icon will show up for a second, but no further result will show up.
**Screenshots:**
Manual search:
<img width="634" alt="Screen Shot 2022-01-19 at 11 17 46 PM" src="https://user-images.githubusercontent.com/55516229/150272493-ec3a53eb-10d4-4a7d-a451-aa963a96fa54.png">

Searching through random button:
<img width="653" alt="Screen Shot 2022-01-19 at 11 16 52 PM" src="https://user-images.githubusercontent.com/55516229/150272435-55de385e-c3db-4be1-b8a8-011c18971e11.png">

### Versions

- MarkText version: v0.16.3
- Operating system: macOS 12.1, MacBook Air (M1, 2020)

**Comment by fxha** [comment]
This feature was removed and is no longer supported.
