### ISSUE TITLE
Not scrolling to headers on Table of Contents

### ISSUE THREAD

**Issue by brunoccr** [marktext/marktext#2911]
### Description

When creating a header that goes beyond the focus area and clicking on the header in the Table of Contents, the behavior does not occur as expected, which is scrolling to the header.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Create a header overflow in screen area.
2. Scroll until a header is not visible.
3. Clicking on a non-visible header in Table of Contents.

**Expected behavior:**

Scroll to header clicked.

**Actual behavior:**

Scroll a few pixels.

**Link to an example: [optional]**

![bug](https://user-images.githubusercontent.com/5890352/150339794-3bb93612-912c-4785-b3b2-16509784cd34.gif)

### Versions

- MarkText version: v0.16.3
- Operating system: Windows 11 Pro Build 22000.434

**Comment by brunoccr** [comment]
I just tested it on Linux and the scroll works correctly

**Comment by YalandHong** [comment]
See #2818. This is going to be fixed in the next release.
