### ISSUE TITLE
Handwritten notes

### ISSUE THREAD

**Issue by Kruemmelspalter** [marktext/marktext#2913]
I think this is a really cool program, there's just one feature I'm missing for this to be perfect: I'd really like handwritten notes, I'd imagine it would make basically an editable image in which you can draw, erase and also maybe add text.

**Comment by qds-soft** [comment]
While I agree with you that handwritten notes are useful, but it's not the purpose of markdown. I suggest using OneNote (or similar) for handwriting. Then you can paste a screenshot of it when needed in martext...

**Comment by fxha** [comment]
Great idea but this feature requested is out of the scope of MarkText as a markdown editor. I think there are great handwriting tool available that support image exporting.
