### ISSUE TITLE
MarkText is not saving 'Show Sidebar' and 'Show Tab Bar' mode

### ISSUE THREAD

**Issue by mryujitanaka** [marktext/marktext#2918]
MarkText is not saving the state mode of 'Show Sidebar' and 'Show Tab Bar'. I have to enable it every time that I launch the program. The version I am using is 0.16.3, and it's a flatpak package of the app.

**Comment by fxha** [comment]
We haven't currently support for view state, but you can enable this by default via [hidden settings](https://github.com/marktext/marktext/blob/master/docs/PREFERENCES.md#view) that may be removed later. This feature should be added with our workspaces design later this year.

**Comment by YalandHong** [comment]
> MarkText is not saving the state mode of 'Show Sidebar' and 'Show Tab Bar'. I have to enable it every time that I launch the program. The version I am using is 0.16.3, and it's a flatpak package of the app.

Please upvote and track #1274
