### ISSUE TITLE
Can't use alt key on mac

### ISSUE THREAD

**Issue by mklilley** [marktext/marktext#2920]
### Description
Can't use alt+3 to type # symbol on my macOS keyboard

### Steps to reproduce

hold alt+3

**Expected behavior:**

Hash symbol will appear on screen

**Actual behavior:**
Nothing appears on screen.

**Link to an example: [optional]**

### Versions

- MarkText:v0.16.3
- Operating system: MacOS 12.01

**Comment by YalandHong** [comment]
Possible dup of #2645 and #2235.

It may be fixed in the next version.

**Comment by mklilley** [comment]
Ah, sorry for creating a duplicate and thanks for replying to me - I appreciate that.
