### ISSUE TITLE
turn off  or customize word wrapping, text alignment

### ISSUE THREAD

**Issue by lex-x-x** [marktext/marktext#2923]
### Describe your feature request

Customize word wrapping and text alignment

### What problem does this feature solve? [optional]

I didn`t found how to turn off wrapping of a text, or set in up at 80 column.
Text aligned always at the center of the screen

### Additional context [optional]
Huge amount of usefull space is lost.
![Selection_019](https://user-images.githubusercontent.com/2036586/150672372-b4290c63-67c2-4a39-8cc8-016335b328ca.png)
For example - sublime text view
![Selection_020](https://user-images.githubusercontent.com/2036586/150672427-533d0729-979a-4cb9-bae7-233859071e84.png)

**Comment by YalandHong** [comment]
https://github.com/marktext/marktext/issues/2654#issuecomment-945149376
