### ISSUE TITLE
Flickering when adding or removing lines and moving page

### ISSUE THREAD

**Issue by mangoepic** [marktext/marktext#2940]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

The bug doesn't happen when the scrollbar (and the screen following) doesn't get moved:

https://user-images.githubusercontent.com/71931749/151219887-aa309c21-8e67-4971-8b27-a81e049a8918.mp4

But if you are moving the scrollbar (and the whole page) by adding or removing lines this flickering appears, you can also see the scrollbar jump up every time it flickers:

https://user-images.githubusercontent.com/71931749/151220107-ea81fb69-1962-472f-bc3c-cfef2e3647ac.mp4

(Note that the only two keys I'm pressing on Mark Text here are enter and backspace)

**Expected behavior:**

No flickering

**Actual behavior:**

See second video

### Versions

- MarkText version:
![image](https://user-images.githubusercontent.com/71931749/151220484-ade3c827-eed9-4bfd-954b-5f81c2be301e.png)

- Operating system:
![image](https://user-images.githubusercontent.com/71931749/151220514-4b8680da-9d03-4c1a-9274-ecacc73ee6af.png)

**Comment by GambitFPS** [comment]
I have the same problem

**Comment by YalandHong** [comment]
Dup of #2470. This is going to be fixed in the next version.
