### ISSUE TITLE
Release plan v0.17.0

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2941]
### Release plan

- [x] Test Github Actions release pipeline w/o publishing binaries (we moved from different CI)
- [x] Merge remaining PRs:
  - [x] #2935
  - [x] #2930
- [x] Update changelog (#2887)
- [x] Publish GitHub release candidate (`v0.17.0-rc.1`)
- [x] Testing
- [x] Fix all (critical) bugs from feedback (`pre-release` label only) and publish new release candidates on demand
- [x] Update documentation
- [x] Update release notes and close all remaining issues
- [x] Create stable GitHub release (`v0.17.0`)
- [x] Pre-publish testing and maintenance
- [x] Publish stable GitHub release (`v0.17.0`)

### Post release plan

- [x] Suspend feature freeze
- [ ] Update website
- [x] Merge `develop` into `master`
- [x] Publish Flathub package

### Schedule

- Release candidate is planned for the end of January
- Stable release is planned for mid February (probably 1-2 weeks after first release candidate)

**Comment by RuikangSun** [comment]
Awesome! Is there a time line to predict the release date? I can't wait to try stable v0.17!

**Comment by fxha** [comment]
### 0.17.1 hotfix

Hotfix release to fix #3074.

- [ ] Merge remaining PRs:
  - [ ] #3089
  - [ ] #3076
- [ ] Update changelog 
- [ ] Update release notes and close all remaining issues
- [ ] Create stable GitHub release (`v0.17.1`)
- [ ] Pre-publish testing and maintenance
- [ ] Publish stable GitHub release (`v0.17.1`)

### Post release plan

- [ ] Merge `develop` into `master`
- [ ] Publish Flathub package

### Schedule

Soon
