### ISSUE TITLE
建议：在打开已存在的Markdown文件时不要更改源文件！

### ISSUE THREAD

**Issue by hungtcs** [marktext/marktext#295]
### 建议描述
如果我开启自动保存功能，并且打开了一个我用其他编辑器写的Markdown文档，本软件有可能会破坏我的原文件，例如我的文件内容为
```
this is a [link]
[link]: https://somewhere.com
```
用本软件打开之后，不做任何操作再关闭，我的文件内容变成了
```
this is a [link]
```
下面的内容被删除掉了，在使用本软件打开hexo博客文件的时候也存在相同的问题

**Comment by Jocs** [comment]
@hungtcs Mark Text does not support  [reference link](https://github.github.com/gfm/#links) now. Can you update this issue into a feature request issue for [reference link](https://github.github.com/gfm/#links)?

And I'll implement it in v0.12.x.
