### ISSUE TITLE
relativeImage bug report

### ISSUE THREAD

**Issue by jhl1789** [marktext/marktext#2956]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1.  set perferences: relative image folder name 
./${filename}
2.  paste a picture into test.md

**Expected behavior:**

the picture path is ./test/xxx.png

**Actual behavior:**

the picture path is ./${filename}/xxx.png

**Link to an example: [optional]**

### Versions

- MarkText version: release 0.16.3
- Operating system: win10
-

**Comment by jhl1789** [comment]
![image](https://user-images.githubusercontent.com/56823343/151684806-a29777cf-ce27-4fc9-b9e9-16de20dd75a6.png)

**Comment by gerryge** [comment]
I have the same issue, ${filename} doesn't work.

**Comment by YalandHong** [comment]
I think 0.16.3 does not support variable path name. Please use [0.17.0-rc](https://github.com/marktext/marktext/releases/tag/v0.17.0-rc.1) or wait for its stable release.

----

0.16.3应该还不支持你所说的功能。请尝试使用0.17.0-rc，或者等待0.17.0正式版发布。
