### ISSUE TITLE
Optimize behaviors for inserting quotes and brackets

### ISSUE THREAD

**Issue by Lorilandly** [marktext/marktext#2959]
### Describe your feature request

When inserting quotes, a pair of it will be automatically inserted
```
SpongeBob said    // press "
SpongeBob said "" // a pair of it inserted
```
This behavior is convenient, but not always. For example
```
print hello!
      ^          // want to insert parenthesis here
print ()hello!   // this happens
       ^         // then I press `del` to remove one of the parenthesis
print hello!     // both parenthesis disappears???
```
My suggestion is that a pair of quotes/brackets should only be inserted only if it is at the end of a sentence or if it is in front of a space. If the cursor is in front of a character, only a single quote/bracket should be inserted.

### What problem does this feature solve? [optional]

see above

**Comment by YalandHong** [comment]
Dup of #2534. Please consider adding #2534 to your fixed tickets. Thanks!
