### ISSUE TITLE
ALT+F4 does nothing (v0.17.0-rc.1)

### ISSUE THREAD

**Issue by maltebp** [marktext/marktext#2964]
### Description
The shortcut `ALT+F4` usually closes the application (and is a common shortcut for Windows applications), but in the pre-release it does nothing.

### Steps to reproduce

1. Open application
2. Press key combination: `ALT+F4`

**Expected behavior:**
Application closes

**Actual behavior:**
Nothing happens

### Versions

- MarkText version: v0.17.0-rc.1
- Operating system: Windows 10 Home 20H2

**Comment by fxha** [comment]
`Alt+F4` isn't provided by Electron because we set `setIgnoreMenuShortcuts(true)` (https://github.com/electron/electron/issues/32674). We can temporally work around this by adding a listener for `Alt+F4` on Windows.

**Comment by maltebp** [comment]
Seems like there are more keybindings that aren't working, e.g. Ctrl+1, Ctrl+2 etc. for setting header style, as well as F11 for fullscreen.

**Comment by fxha** [comment]
> Ctrl+1, Ctrl+2 etc. for setting header style

We changed default key bindings, please see [default key bindings](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md#available-key-bindings). The heading size can now be changed with `Ctrl+Shift+1` and `Ctrl+1` is used for tabs.

**Comment by maltebp** [comment]
> > Ctrl+1, Ctrl+2 etc. for setting header style
> 
> We changed default key bindings, please see [default key bindings](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md#available-key-bindings). The heading size can now be changed with `Ctrl+Shift+1` and `Ctrl+1` is used for tabs.

Ah, fair enough. The shortcuts in the `@` quick formatting thing are not updated though:
![image](https://user-images.githubusercontent.com/42169660/152955461-c5474be4-70a5-4228-b794-d747bd35d458.png)
