### ISSUE TITLE
Ability to open images with external tools

### ISSUE THREAD

**Issue by kiyoka** [marktext/marktext#2968]
### Describe your feature request

I want to open and edit images directly in an external tool.
Or I want to copy the full path of an image to the clipboard.

### What problem does this feature solve? [optional]

When creating a manual with screen captures, you may want to edit the captured images.
Since Mark Text does not have the ability to get the absolute path of the image, you need to select the image outside of Mark Text and open it.
It would be helpful if I could open the image directly from Mark Text's UI with paint.exe or get the absolute path.

### How about a UI like this?
![open_image_file1](https://user-images.githubusercontent.com/80378/151961612-d90d92f2-e3e1-49a0-84ff-e9301acf6400.png)
![open_image_file2](https://user-images.githubusercontent.com/80378/151962232-9305b400-b0e6-4ae6-ae62-d982b6ab1a76.png)

**Comment by YalandHong** [comment]
Duplicate of #2321

**Comment by kiyoka** [comment]
Thanks for letting me know about the duplication.
I see that there are other people who have requested this.

**Comment by kiyoka** [comment]
This feature request is duplicated.
If I were to submit a pull request, I would submit it for #2321.
