### ISSUE TITLE
In order to protect the security of the file content, please support reference link

### ISSUE THREAD

**Issue by hungtcs** [marktext/marktext#297]
### Description
If a file has some reference link, marktext will remove it automatically, this is not a good practice, usually it will cause my file content to be lost.

If I just open the file but do not edit it, editor should not modify the contents of the file.

**Comment by Jocs** [comment]
@hungtcs I already add this `feature request` to project `version 0.12.xx`. we can discuss some details here, or you have any good ideas about this feature?

**Comment by hungtcs** [comment]
@Jocs sorry, not yet. I think the important thing is not reference link, if the content of file does not comply with marktext, why not display it directly
