### ISSUE TITLE
copying latex phrases from my document and pasting them does not working

### ISSUE THREAD

**Issue by OuttaSpaceTime** [marktext/marktext#2971]
### Description

Pasting latex from my markdown files does not work properly.

### Steps to reproduce

1. Write some latex like $\sum x_i$
2. Copy only latex or the complete text
3. paste and notice that $$ signs are being trimmed off

**Expected behavior:** $ symbols should not be trimmed

### Versions

- MarkText version: v0.16.3
- Operating system: Ubuntu

**Comment by YalandHong** [comment]
Possible dup of #1638

**Comment by OuttaSpaceTime** [comment]
yes can be closed! thanks I searched for that issue but didn't found
