### ISSUE TITLE
Add option to set word wrap or page size from the editor

### ISSUE THREAD

**Issue by bessszilard** [marktext/marktext#2972]
### Describe your feature request

First of all, thank you for this fantastic open-source markdown editor. It would be great to select the word wrap or the page width in the editor, the same way we choose the font size line-height [1]. I partly did it by decreasing the font size and zooming in the window, but that is not a long-term solution since the window's zoom of the editor resets when I reopen the program.

[1] ![image](https://user-images.githubusercontent.com/48211034/152233130-eeb230ca-e14f-45d4-a384-f1cd6f0c69c4.png)

**Comment by YalandHong** [comment]
Have you tried https://github.com/marktext/marktext/issues/2654#issuecomment-945149376 ?

**Comment by bessszilard** [comment]
Thanks, great, it solved my problem!
