### ISSUE TITLE
How to download other language dictionaries

### ISSUE THREAD

**Issue by aborruso** [marktext/marktext#2985]
### Question description

Hi, how to use the GUI to download other dictionaries?

Thank you

![image](https://user-images.githubusercontent.com/30607/152680569-2dc9b2f7-a3b1-4608-aac1-3e275d0d39ab.png)

**Comment by fxha** [comment]
It seems like you are using macOS or Windows. You can add additional languages via your OS settings, as noted in the description below the language selection. Open your OS settings, select "Language" and navigate to "Time & language". Now, you can add a new language to your OS and download the keyboard and spelling packages.

**Comment by aborruso** [comment]
> as noted in the description below the language selection. Open your OS settings, select "Language" and navigate to "Time & language".

Thank you @fxha. I was looking for "Language"  e "Time & language" in my Mark Text settings.

What about to change 

`Additional languages may be added through "Language" in your "Time & language" settings`

into

`Additional languages may be added through "Language" in your OS "Time & language" settings`

Mark Text is really a great tool.
