### ISSUE TITLE
所有的md文件打开为空文件

### ISSUE THREAD

**Issue by wozqh** [marktext/marktext#299]
### Description

window下，所有的md文件都不能正常查看，打开显示为空白文件，但是用其他软件打开是有显示内容的

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text:
- OS:

**Comment by Jocs** [comment]
maybe duplicated with #265 , you can goto this issue for more detail.

**Comment by Jocs** [comment]
@wozqh 请参照 #265 解决方案。

**Comment by feijie825** [comment]
你可以删除所有用户数据后重试：
1. 备份 "%appdata%\marktext-folder" 
2. 删除 "%appdata%\marktext-folder"文件夹
3. 尝试打开一个文件

**Comment by Jocs** [comment]
@wozqh 删除用户数据后，可以了吗

**Comment by wozqh** [comment]
可以了，但是现在会有时出现无法编辑的情况，添加不了内容

**Comment by Jocs** [comment]
@wozqh 能具体描述下问题吗？

**Comment by wozqh** [comment]
怎么又出现打开为空文件的情况了啊

**Comment by Jocs** [comment]
@wozqh 安装最新版本出现的问题？

**Comment by wozqh** [comment]
最新版解决这个问题了吗

**Comment by Jocs** [comment]
安装最新版后再尝试

>你可以删除所有用户数据后重试：

>备份 "%appdata%\marktext-folder"
>删除 "%appdata%\marktext-folder"文件夹
>尝试打开一个文件
