### ISSUE TITLE
Broken syntax highlighting in code blocks after re-import 

### ISSUE THREAD

**Issue by rootex-** [marktext/marktext#30]
It is currently impossible to re-import a project without loosing syntax highlighting. That's truly disappointing. Fix this, please.

This is what happens after re-import:
![](https://i.imgur.com/BwKec4V.png)

Should be
\```scala
sealed trait Tree[+A]
\```
instead of plain:
\```
sealed trait Tree[+A]
\```

**Comment by Jocs** [comment]
Thank you for reporting this bug, I'll fix it in the next release version.

**Comment by rootex-** [comment]
Now, that was a quick response, thank you :+1:

**Comment by SuperSandro2000** [comment]
I think that is related to this: when you don't have spaces in a table they will be added even if I don't save the file.
Before:
*Foo
* Bar
After:
*Foo

*Bar
This matters because GitHub puts a little more space between the lines if they have a free line between them.

**Comment by Jocs** [comment]
@SuperSandro2000 This is another bug

Now Mark Text only support loose list, all not loose list will be convert to loose list

[GitHub Flavored Markdown # list](https://github.github.com/gfm/#lists)

You can open another issue to report this bug, Bus it's will cost a long time to fix it.

**Comment by rootex-** [comment]
Awesome job ☕
