### ISSUE TITLE
Trailing spaces and newline

### ISSUE THREAD

**Issue by keesse** [marktext/marktext#300]
### Description
If I end a line with 2 spaces, instead of displaying a newline, the next line is displayed at the end of the first line.

From the [Markdown spec](https://daringfireball.net/projects/markdown/syntax) :  
> When you do want to insert a \<br /\> break tag using Markdown, you end a line with two or more spaces, then type return.

### Steps to reproduce

1. [First step]
line one\<space\>\<space\>
line two

**Expected behavior:** [What you expected to happen]
line one   
line two

**Actual behavior:** [What actually happened]
line one line two

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: 0.10.21
- OS: Windows 10 + latest patches

**Comment by Jocs** [comment]
@keesse We already are working on the feature `soft\hard line break`, and almost finished, you can build the latest master branch to use these features, or wait for the next release version.

**Comment by keesse** [comment]
@Jocs, good to hear, for the rest, Mark Text is really super! :-)

**Comment by keesse** [comment]
@Jocs thank you very much, it works fine with 0.11.42, both on Windows as on Linux :-)
