### ISSUE TITLE
How to use the command line script?

### ISSUE THREAD

**Issue by pogusanqian** [marktext/marktext#3003]
### Question description
How to use the command line script?

![Snipaste_2022-02-10_16-04-26](https://user-images.githubusercontent.com/69836873/153363894-eda1ea8b-f24c-40cf-909a-d47b3c83617f.png)

**Comment by fxha** [comment]
@pogusanqian You need to set a script or application path like `/tmp/customUploader.sh` or `.bat`. In your case, this script need to execute `node foo.js`.
