### ISSUE TITLE
OSX arm64 builds damaged

### ISSUE THREAD

**Issue by carlskii** [marktext/marktext#3004]
Model Name:	iMac
  Model Identifier:	iMac21,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB

 System Version:	macOS 12.1 (21C52)
  Kernel Version:	Darwin 21.2.0

I tried the latest marktext-arm64.dmg and the marktext-arm64-mac.zip files but the MarkText binary is being reported as damaged. 

“MarkText” is damaged and can’t be opened. You should move it to the Bin."

**Comment by Patrick-Dong** [comment]
same here

**Comment by YalandHong** [comment]
Possible dup of #2983

**Comment by yaxarat** [comment]
@YalandHong thanks for the link. The solution (workaround) posted there has worked for me!
Basically, run this in your terminal:
```
xattr -cr /Applications/MarkText.app
```

**Comment by sjijavadze-sugarcrm** [comment]
I still get this, apple silicon, I tried the `sudo xattr -cr /Applications/MarkText.app` and still get:
```
xattr: [Errno 1] Operation not permitted: '/Applications/MarkText.app/Contents/MacOS/MarkText'
xattr: [Errno 1] Operation not permitted: '/Applications/MarkText.app/Contents/MacOS/MarkText'
xattr: [Errno 1] Operation not permitted: '/Applications/MarkText.app/Contents/MacOS'
xattr: [Errno 1] Operation not permitted: '/Applications/MarkText.app/Contents/MacOS'
xattr: [Errno 1] Operation not permitted: '/Applications/MarkText.app/Contents/LICENSE'
xattr: [Errno 1] Operation not permitted: '/Applications/MarkText.app/Contents/LICENSE'
xattr: [Errno 1] Operation not permitted: '/Applications/MarkText.app/Contents/Resources/de.lproj'
...
```

And the list goes on.

**Comment by elephantatech** [comment]
command works after I closed the message to move to trash. I clicked on cancel and then tried again the command it worked now.
