### ISSUE TITLE
Alternative Dictionaries

### ISSUE THREAD

**Issue by rc4-studio** [marktext/marktext#3008]
First, let me thank you for this wonderful app!
One of the features I use the most is spellchecking. However, Portugal has new writing rules for more than 12 years now, and somehow Google still uses dictionaries based on the previous ones. As I understand, Marktext's dictionary is the same as Google's, and I can't compile a new .bdic file. Therefore, it would be nice to have a way to add alternative dictionaries.
Thank you!

**Comment by fxha** [comment]
You can replace your dictionary locally if you like, but we won't add a UI option for this. All dictonaries are saved in the `dictionaries` subdirectory of the [application data directory](https://github.com/marktext/marktext/blob/develop/docs/APPLICATION_DATA_DIRECTORY.md).

**Comment by rc4-studio** [comment]
So far I'm aware. The problem is that I cannot compile new .bdic files, for as I understand I would have to compile all of chromium from start. Anyway, thank you for your time.
