### ISSUE TITLE
copy paste image upload failed

### ISSUE THREAD

**Issue by Redcxx** [marktext/marktext#3013]
### Description
I am on windows, exactly the same as https://github.com/marktext/marktext/issues/2347
it says a PR has been submitted fixing it 29 days ago, but I encountered it just now

drag image can be uploaded to github successfully, but not copied & paste.

- [x ] Can you reproduce the issue? 

### Steps to reproduce

1. download
2. open
3. copy and paste any image

**Expected behavior:**
upload to github

**Actual behavior:**
failed, with a copy to clipboard warning

**Link to an example: [optional]**

### Versions

- MarkText version: 0.16.3
- Operating system: windows

**Comment by YalandHong** [comment]
For windows, try to use version 0.17.0: https://github.com/marktext/marktext/releases/tag/v0.17.0-rc.1

**Comment by WenHv587** [comment]
> For windows, try to use version 0.17.0-rc1:
> 
> https://github.com/marktext/marktext/releases/tag/v0.17.0-rc.1
> 
> or you can wait for its stable release.

这个版本也不行呀~ windows10

**Comment by maxchiron** [comment]
> > For windows, try to use version 0.17.0-rc1:
> > https://github.com/marktext/marktext/releases/tag/v0.17.0-rc.1
> > or you can wait for its stable release.
> 
> 这个版本也不行呀~ windows10

https://github.com/marktext/marktext/issues/3360#issuecomment-1254541573
