### ISSUE TITLE
reverse indentation

### ISSUE THREAD

**Issue by Hyppothalamus** [marktext/marktext#3014]
### Describe your feature request

you can indent lists with tab but for as far i have seen i cant seem to do the reverse with shift+tab

### What problem does this feature solve?

reverse indentation in list / everywhere

**Comment by YalandHong** [comment]
Are you using 0.16.3? Maybe you should try 0.17.0?

https://github.com/marktext/marktext/issues/205#issuecomment-1016493939

**Comment by fxha** [comment]
Hey @Hyppothalamus, this feature was implemented in v0.17.0 which will be released soon.
