### ISSUE TITLE
Your system does not have picgo installed, please install it before use

### ISSUE THREAD

**Issue by Kuronekoo** [marktext/marktext#3017]
I am sure I have installed latest version PicGo in my mac ,and I used PicGo for a very long time.
But still, it comes a notice "Your system does not have picgo installed, please install it before use"
My Marktext version is v0.17.0-rc.2 ,and PicGo version is 2.3.0, Macos Catalina 10.15.7 (19H2)

![image](https://user-images.githubusercontent.com/26434287/154035436-e2e689a2-a138-48bf-84b5-91992aa1a2af.png)

**Comment by fxha** [comment]
@Kuronekoo How is the CLI tool from PicGo named on your system?

**Comment by Kuronekoo** [comment]
Where can I find the CLI tool ?&nbsp;








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Felix ***@***.***&gt;; 
发送时间: 2022年2月17日(星期四) 凌晨0:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [marktext/marktext] Your system does not have picgo installed, please install it before use (Issue #3017)





 
@Kuronekoo How is the CLI tool from PicGo named on your system?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kuronekoo** [comment]
![image](https://user-images.githubusercontent.com/26434287/154656290-6a693904-a4f9-4cf8-9bba-446c92e85283.png)

**Comment by fxha** [comment]
You have to add the path to PicGo binary to your `PATH` environment variable according there documentation.

**Comment by stefanolomo** [comment]
> You have to add the path to PicGo binary to your `PATH` environment variable according there documentation.

Can you give me the documentation in wich says that? I have been looking for it so long... Thanks!

**Comment by fxha** [comment]
@stefanolomo You have to add the Picgo binary path to systems variables like [here](https://www.java.com/en/download/help/path.html).
