### ISSUE TITLE
Hope to add a feature similar to vscode user snippets

### ISSUE THREAD

**Issue by Gahotx** [marktext/marktext#3023]
I hope the marktext can add a function that allows users to customize shortcut keys and then output a code template, such as the user snippets of vscode. (https://code.visualstudio.com/docs/editor/userdefinedsnippets)

**Comment by YalandHong** [comment]
Possible dup of #2182

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2182. You may want to subscribe there for further updates.
