### ISSUE TITLE
Relative image folder name not available

### ISSUE THREAD

**Issue by ExcueseLin** [marktext/marktext#3029]
### Description

1. Prefer relative asserts folder  is  ON;
2. Relative image folder name is  "${filename}"
3. But image path is  "/Documents/${filename}/2022-02-17-21-18-15-image.png" 

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/55143045/154490949-e0367116-ec96-4846-9da6-114a9971a6dd.png">

I think path is   /Documents/test/2022-02-17-21-18-15-image.png , because my file name is test . 

### Versions

-MarkText version: v0.16.3
Operating system: macOS Big Sur

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that you are using v0.16.3 that doesn't support image variables. If you like, you can try the latest release candidate that support image variables. In your case, `${filename}` is just a directory without any meaning.
