### ISSUE TITLE
Images don't display in Visual Studio Code

### ISSUE THREAD

**Issue by WeberAlex** [marktext/marktext#3042]
### Question description

I use Markdown for compatibility reasons. To my dismay, when I set a local image path in Mark Text `Ctrl + Shift + I` the image does not display when I open the `.md` file in VS Code.

Mark Text uses absolute paths while VS Code seems to only accept relative paths. Of course I can switch to source code mode `Ctrl + E` to change the paths, but there is probably a better way.

**Comment by mangoepic** [comment]
this sounds more like a vscode issue 🤔

**Comment by WeberAlex** [comment]
If someone uses both apps, I welcome some advice on the best way to manage local image links. To my knowledge there is not preferences in Mark Text to select an absolute image path or a relative image path when I insert images. Could it apply as a feature request? I am not even sure?

**Comment by fxha** [comment]
You can set image handing via settings. The image is automatically copied/saved relative if you configure to prefer relative links and the file is saved.

![](https://user-images.githubusercontent.com/22716132/154844805-5b301d6f-5593-4f37-965a-60d78b4454c4.png)

@WeberAlex You want to select a file without coping that should be relative? I guess is is a valid option, but we got a few issues with error handling of different drives etc.

**Comment by WeberAlex** [comment]
@fxha 

Thanks Felix, I have tested the the Option Relative Image folder name in the Preferences, and it works. I can see my local images in Mark Text and VS Code.

Yes, I would like to select the option to use a relative path without copying the image if possible .
