### ISSUE TITLE
Can code blocks display line numbers?

### ISSUE THREAD

**Issue by XieCangfeng** [marktext/marktext#3055]
## Excuse me, can code blocks display line numbers?
请问一下，代码块可以显示行号吗？
### I believe that the code block that can display line numbers is very exciting. Can I turn on the display of line numbers?
![image](https://user-images.githubusercontent.com/77087350/154849964-0c3aa23b-1323-4b0a-942e-749ca9477d54.png)

**Comment by YalandHong** [comment]
Dup of #2605. Line number is currently disabled due to performance issue.

----

这个问题有人提过了：#2605

由于性能上的问题，MarkText暂时禁用了这个功能。

**Comment by XieCangfeng** [comment]
OK, 了解啦
