### ISSUE TITLE
can not paste image from Clipboard

### ISSUE THREAD

**Issue by capeskychung** [marktext/marktext#3067]
### Description

can not paste image from  Clipboard to marktext 

- [ x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** paste image success

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- MarkText version: 0.17.0
- Operating system: Win10

**Comment by benmepham** [comment]
I'm having the same issue pasting images. MarkText version 0.17.0, OS: Linux (AppImage)

**Comment by hisola1024** [comment]
先按ctrl+f，再按ctrl+v 就可以粘贴了，暂时先这样用吧

**Comment by sixone-tx** [comment]
the same issue . MarkText version 0.17.0, OS: macos 11.6.4

**Comment by bijzz** [comment]
Same issue with 0.17.0 on Win.
Was working with 0.16.3 on Win.

**Comment by super2346** [comment]
the same issue . MarkText version 0.17.0, OS: macOS Big Sur 11.6

**Comment by haolibai** [comment]
same issue here. ctrl+f then ctrl+v works! But this is a bug still.
