### ISSUE TITLE
Multi language Translation Support

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#308]
### Description

Mark text seems to be absent in English only, so can you correspond to Japanese, Chinese, etc?
By the way, I am a Japanese user.

### Versions

- Mark Text: v0.11.42
- OS:Windows 10

**Comment by Jocs** [comment]
@keito940 , Do you mean that the new version download link absent in `Japanese` and `Chinese` readme?

PR is appreciated!:smile:

**Comment by fxha** [comment]
I guess duplicate of https://github.com/marktext/marktext/issues/138#issuecomment-380867653.
