### ISSUE TITLE
Support  tight lists

### ISSUE THREAD

**Issue by SuperSandro2000** [marktext/marktext#31]
MarkText should support tight lists. Currently all lists are converted to loose ones.
```Before:
* Foo
* Bar

After:
* Foo

* Bar
``` 
As discussed here: https://github.com/marktext/marktext/issues/30#issuecomment-374125455

**Comment by SuperSandro2000** [comment]
I would categories this issue as quite severe as it is the last one that stops me from using marktext. I don't really care if it has advanced features. I just want to render my GitHub readme similar to how it looks later on the web offline.

**Comment by Jocs** [comment]
@SuperSandro2000 Do you have any ideas on how to distinguish loose list and tight list when you input bullet or order list?

**Comment by SuperSandro2000** [comment]
Your could look for two line breaks (ignoring spaces and trans) without a list indicator (* or -) between them.

**Comment by Jocs** [comment]
@SuperSandro2000 Yes, I know how to distinguish loose and tight list when import markdown, I mean how to distinguish between them when you write with Mark Text, There is one solution, I add a user preference file, people can select whether to use loose list or tight list. when import markdown, I will not convert loose list to tight list or convert tight list to loose list.

This issue also has a new feature **user preference** file, So it will take me some time to finish it, stay tuned.

**Comment by SuperSandro2000** [comment]
My bad. Missunderstud you.

A setting would be ideal. You could put the theme setting in that file too.

As a quick fix you could implement that you don't convert them.

**Comment by Jocs** [comment]
- wowowowo
  - wowowow
  - wowowowo
