### ISSUE TITLE
Problem with marktext-0.11.42-x86_64.AppImage

### ISSUE THREAD

**Issue by keesse** [marktext/marktext#310]
### Description
The AppImage does not work for me (Ubuntu 18.04 64 bit)

### Steps to reproduce

1. [First step]
When started from the GUI, I can choose yes or no to install, but then nothing happens

When starting from the commandline:

$ ./marktext-0.11.42-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_markteE1DVwf/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text:
- OS:

**Comment by fxha** [comment]
Yes, seems the same issue as https://github.com/electron-userland/electron-builder/issues/2958.

@Jocs The strange thing is that I can successfully build and execute my self-build appimage on Linux. Can you try again with different electron builder versions and test to execute these or upload it somewhere?

**Comment by Jocs** [comment]
@fxha Do you mean build and execute `appimage` on Mac? but I am not sure weather I can execute `appimage` on Mac successfully.

I'll try this evening.

**Comment by fxha** [comment]
Only build and test it on a VM or unpack it (maybe you can mout the appimage and check against my electron-build "tree" comment). Otherwise I have to build marktext/marktext and upload it. So that you can publish it manually. The main problem is when you update Mark Text/download latest version it will instantly fail to execute. It seems like an electron-builder issue if build on macOS.

**Comment by Jocs** [comment]
@fxha I think the current solution should be that you build an appImage locally and then manually update it to the latest release version?

**Comment by Jocs** [comment]
>Do we have to update the checksums and provide all build because of electron-updater? 

Have you determined that the problem is caused by the the new version of electron-builder?
Is it possible to revert the electron-builder back to the previous version to solve this problem?

**Comment by fxha** [comment]
I cannot reproduce the problem because I only have Linux and Windows system(s). So you have to try it yourself.

**Comment by keesse** [comment]
@fxha thank you very much, it works fine now!
