### ISSUE TITLE
Sorting of folders by numbers/alphatabit, and option for sorting in the settings

### ISSUE THREAD

**Issue by bxff** [marktext/marktext#3116]
### Description

As the title says, I cannot sort the folders by numbers or whatever, it is different every time I open the application.

The files are sorted well, but still there is no option to change the sorting, the options in the setting on sidebar is also not available for some reason, I wasn't able to understand why.

<img width="181" alt="Screenshot 2022-03-10 at 9 35 37 PM" src="https://user-images.githubusercontent.com/51504045/157704092-76dc39f5-c5ad-4cdd-973d-ecbc071bce82.png">

### Steps to reproduce

1. Create folders, starting with 1, 2, 3, etc
2. Open the app on that folder
3. See the results.

Expected behavior: to see the option to change the sorting, just like in Typora, File Explore, Obsidian, and pretty much any app with files list in them.

Actual behavior: weird structure, with no way to know what is where, and why.

### Versions

- MarkText: Just downloaded.
- Operating system: MacOS Montesey.

**Comment by YalandHong** [comment]
Possible dup of #1248 and #2078

**Comment by bxff** [comment]
Any comment on when this could be fixed, I have found similar issues dating as back as 2018.

**Comment by OOaker** [comment]
It's not solved and the answer seems incorrect. Tested comprehensively with names of just letters, just numbers, mixed, special chars and so on. Even manipulated the timestamps of the subfolders and so on. As the OP mentioned notes are sorted perfectly fine but subfolders seem to be unsorted. They are listed 1:1 as read from the disk. The order seems to be the actual order from the WinAPI without ANY sorting applied. This means a newly created folder will always be last even if I manipulate all it's timestamps.
