### ISSUE TITLE
Can't copy full links

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#312]
### Description
Copying the [entire link](http://example.com) is not possible, while copying a part of it is possible.

### Steps to reproduce

1. Type `[Rolling boulder](https://latimesherocomplex.files.wordpress.com/2011/08/ij1_ia_454_r.jpg)`
2. Press on `Rolling boulder`
3. Select the link `https://latimesherocomplex.files.wordpress.com/2011/08/ij1_ia_454_r.jpg`
4. Try to copy it

**Expected behavior:** That the link gets copied

**Actual behavior:** Nothing happens

**Link to an example:**
![2018-05-31_11-50-11](https://user-images.githubusercontent.com/10220080/40775631-d1c43fe0-64c8-11e8-8e44-53512f060887.gif)
(I'm not sure why the mouse cursor looks like that in the GIF)

### Versions

- Mark Text: v 0.11.42
- OS: Windows 10

**Comment by Jocs** [comment]
@stefnotch thanks for reporting this issue, I test it on my computer and make sure it's a bug now.
It will be fixed in the next released version!
