### ISSUE TITLE
Find & Find and Replace not working in Source Code Mode

### ISSUE THREAD

**Issue by villares** [marktext/marktext#3124]
### Description

Can't use find or find and replace on Source Code Mode.

- [ X] Can you reproduce the issue? 

### Steps to reproduce

1. Enter **Source Code Mode** (ctrl + E or via menu)
2. Invoke **Replace**, with ctrl + R or **Find** ctrl + F, also via menu.

**Expected behavior:**

The **Find and Replace** or **Find** panels should open 

**Actual behavior:**

Nothing happens.

### Versions

- MarkText version: v0.17.1
- Operating system: Manjaro-XFCE

**Comment by YalandHong** [comment]
Duplicate of #1864

**Comment by mitchcapper** [comment]
Basic support is fixed by #3129
