### ISSUE TITLE
图片加载失败 load image failed

### ISSUE THREAD

**Issue by chomue** [marktext/marktext#3126]
### Description
使用picgo+gitee上传图片后在markdown文件中无法正常显示。
！！！gitee仓库图像上传正常
！！！直接访问url链接图像显示正常
### Versions

- MarkText version: 0.17.1
- Operating system: win11

https://user-images.githubusercontent.com/50108526/158516500-dfd72f0b-cc66-4a63-9a37-533954b1464f.mp4

https://user-images.githubusercontent.com/50108526/158516508-14e1ddc2-385f-45c7-92de-fccc6674f101.mp4

https://user-images.githubusercontent.com/50108526/158516511-fb243ff5-d68d-4a69-9d53-e9f278a9b1dc.mp4

**Comment by TravisL24** [comment]
你好，我用picgo+git遇到了类似的问题，请问您是怎么解决的吗？
