### ISSUE TITLE
当删除文件时（即点击move to trash）出现错误，具体错误提示如图所示

### ISSUE THREAD

**Issue by fantab01** [marktext/marktext#3137]
![微信图片_20220317203132](https://user-images.githubusercontent.com/45958766/158809480-fb9fe034-31d4-4ded-be91-dfdb8c73cbcb.png)

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #3150. You may want to subscribe there for further updates.
