### ISSUE TITLE
Fenced code blocks in lists 

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#314]
### Description

Fenced code blocks in lists don't work very well.

### Steps to reproduce

1. Type `- ` to create a list
2. Type 3 backticks (`) to create a fenced code block
![image](https://user-images.githubusercontent.com/10220080/40777510-562b6380-64ce-11e8-9687-32633c9f000a.png)
3. Type some code
![image](https://user-images.githubusercontent.com/10220080/40777601-9cafddae-64ce-11e8-8bd8-8d5c617969a1.png)
4. Try to add another line to the list

**Expected behavior:** That I can easily add more list items. 

**Actual behavior:** Doesn't work

### Versions

- Mark Text: v 0.11.42
- OS: Windows 10

**Comment by Jocs** [comment]
Hi, @stefnotch you can follow these steps to create more list items.

1. Type - to create a list
2. Type 3 backticks (`) to create a fenced code block
3. Type some code
4. **Use arrow down to create a paragraph after code block**
5. Press enter to convert this paragraph to list item.

Can this way solve you problem?

**Comment by stefnotch** [comment]
@Jocs Yes, this does work. I expected that clicking with the mouse below the list/code block would also work.

Well, I still have a bug report:
1. Type `- ` to create a list
2. Type 3 backticks (`) to create a fenced code block (Don't type a language)
3. Hit Enter:
![image](https://user-images.githubusercontent.com/10220080/40778873-08628228-64d3-11e8-91f9-8721c7920218.png)

Expected: It doesn't create another list item.

Actual: It created another list item


Also, there are some other issues that I ran into while using fenced code blocks with lists, but I have troubles reproducing them.

**Comment by Jocs** [comment]
>Expected: It doesn't create another list item.

It is indeed a small bug. input and not input language will cause different results.

>Also, there are some other issues that I ran into while using fenced code blocks with lists, but I have troubles reproducing them.

Scenes that use fenced code blocks in list items are inherently small, and there are sometimes bugs that are not easily discovered.

**Comment by stefnotch** [comment]
@Jocs Created a new issue. https://github.com/marktext/marktext/issues/315

Thank you for your help. I can close this one for now. 😄
