### ISSUE TITLE
`Move To Trash` results in `Failed to create FileOperation instance`

### ISSUE THREAD

**Issue by itamadev** [marktext/marktext#3150]
### Description

When using the `Move To Trash` action it results in an error.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Create or access any project
2. Select a file
3. Click the `Move To Trash` option

**Expected behavior:**

The file should move to trash after the user has been notified of the action and warned.

**Actual behavior:**

An error occurs and the file remains untouched

**Link to an example: [optional]**

![example](https://user-images.githubusercontent.com/37014285/159203755-ccc11359-6689-41c1-87a5-3a6e70b9d4f3.gif)

### Versions

- MarkText version: 0.17.1
- Operating system: Windows 10

**Comment by itamark-dev** [comment]
I'm aware this issue is some sort of a duplicate of #3137, 
I wanted to make it more descriptive and written as the contribution guidelines suggest.

**Comment by WeberAlex** [comment]
I am experiencing the same bug using MarkText 0.17.1 (portable) in Windows 11. The files are saved locally. I use an admin. account.

**Comment by mangoepic** [comment]
Same here, I tried running MarkText normally and as Administrator. I can create folders and directories but not move them to trash

I have Windows 11 21H2

**Comment by mohalikeyou** [comment]
Same here, I made MarkText as admin, and the file did stay in local disk, but i met this problem yet....

**Comment by stefanolomo** [comment]
Same here

**Comment by themistbeforedawn** [comment]
At the end of 2022, it's still there.

**Comment by sharmankin** [comment]
At the march of 2023, it's still there.

**Comment by StoneMoe** [comment]
meet this issue on Windows, with a file saved on samba network location

**Comment by XR-stb** [comment]
same here

**Comment by CNW-HuyDk** [comment]
well, it's April 2025 and still there

**Comment by dismalbone** [comment]
got this today

**Comment by Kircerta** [comment]
I confirm this issue exist. I saved the file in a folder inside documents, on Windows 11. I can not delete markdown files within the Marktext application itself.
