### ISSUE TITLE
Download buttons on the Marktext website are broken (all lead to a 404 page)

### ISSUE THREAD

**Issue by pensierinmusica** [marktext/marktext#3152]
### Description

Download buttons on the Marktext website are broken (all lead to a 404 page)

- [x] Can you reproduce the issue? 

### Steps to reproduce

Go to the website (https://marktext.app/) and click on any of the download buttons.

**Expected behavior:**

Correct download to start

**Actual behavior:**

The buttons lead to a 404 page

**Link to an example: [optional]**

https://github.com/marktext/marktext/releases/latest/download/marktext.dmg

### Versions

- MarkText version:
- Operating system:

**Comment by pensierinmusica** [comment]
@Jocs and @fxha any chance this could be promptly fixed? Thanks!

**Comment by YalandHong** [comment]
It's weird. I think it should have been fixed by https://github.com/marktext/website/issues/60

**Comment by fxha** [comment]
Seems to be an issue with the website distribution but I haven't access to the service. Hopefully @Jocs can resolve the issue soon if he has some leisure time.

**Comment by pensierinmusica** [comment]
@YalandHong @fxha @Jocs now the website doesn't even load anymore.. 

<img width="1496" alt="screenshot" src="https://user-images.githubusercontent.com/3594037/173866800-514706c0-6783-4ff6-a29a-a6e86bf0543e.png">

**Comment by YalandHong** [comment]
Dup of https://github.com/marktext/website/issues/66

**Comment by Jocs** [comment]
The new official website is already available, https://www.marktext.cc/
