### ISSUE TITLE
打开一个.md文件会自动删除空行

### ISSUE THREAD

**Issue by YYorozuya** [marktext/marktext#3155]
Marktext会在有些地方添加空行，在有些地方删除空行，因为有些文件我希望保留很多自己的格式，可不可以添加一个可选项，让marktext不要强制更改原来文件的格式。
Sorry for my poor English, thanks.

**Comment by DYH-Hong** [comment]
Dup of #1354 and #2189

Also from https://github.com/marktext/marktext/issues/2189#issue-632789752:

The removal of empty lines is currently not addressed as it would require a significant work to our markdown parser and data structure
