### ISSUE TITLE
type "Ctrl+1" cannot generate Header 1 in a new paragraph.

### ISSUE THREAD

**Issue by SgtPepperr** [marktext/marktext#3156]
### Question description
I just update my marktext version from **0.16.x to 0.17.0**. Then I find I can't **get Header 1 by typing `Ctrl+1`** when I start a new paragraph,while I can do this in the last version.The other numbers are the same.I am not sure it's a bug or some incorrect settings have been made.

**Comment by DYH-Hong** [comment]
Since 0.17, `Ctrl+number` is used to switch tab.

See [marktext/KEYBINDINGS_OSX.md at develop · marktext/marktext](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS_OSX.md) for the default key bindings for your OS.

**Comment by SgtPepperr** [comment]
Thank you.I have checked the default key bindings and got the reason.

### Suggesiton

Since the default key bindings have changed,maybe the settings in the below image should change too. At least I got confused when I saw this because typing does not correspond to the actual effect.
![](https://raw.githubusercontent.com/SgtPepperr/ImgStg/master/img/20220324142039.png)
