### ISSUE TITLE
Key binding for Source Code Mode in 0.11.42 do not work

### ISSUE THREAD

**Issue by keesse** [marktext/marktext#316]
### Description

When in Marktext 0.11.42, Ctrl+U does not work  
In the older version it was Ctrl+Shift+S which now works as Save As, such as most programs

### Steps to reproduce

**Expected behavior:**  Switch to and back from Source Code mode

**Actual behavior:**  Nothing happens

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: 0.11.42
- OS: Windows 10 64 bit, Ubuntu 18.04 64 bit

**Comment by fxha** [comment]
Yeah, we changed the shortcuts to support save as and there are some problems with non-US-keyboards. As a workaround you can take a look at the table [here](https://github.com/marktext/marktext/issues/216#issuecomment-391810085).

**Comment by keesse** [comment]
Yes, Ctrl+Super+U works on Linux, thanks for pointing me to the table

**Comment by jkrzefski** [comment]
I might face a similar problem on macOS. The shortcut for enabling source code mode works fine, but I cannot leave source code mode with the same shortcut. Sadly no other variation seems to work and I have to use the menu. Is this a known issue already or does it relate with one?

macOS version: High Sierra, 10.13.4
Mark Text version: 0.11.42

**Comment by Jocs** [comment]
@jkrzefski I test it on my Mac, yes, it is another issue, can you please open another issue about the problem what you found. thanks.:smile:

**Comment by jkrzefski** [comment]
@Jocs I just did. Thank you for the quick response.

**Comment by fxha** [comment]
@keesse I'm closing this issue because we "fix" the problem with source code mode shortcut. It's now on `Ctrl+Alt+S`. Further keyboard problems are still tracked in #216.
