### ISSUE TITLE
double click wrong selection

### ISSUE THREAD

**Issue by Li-An** [marktext/marktext#3161]
### Description

When I doubleclick a word, Marktext selects the word and the space after the word quite frequently.

- [ ] Can you reproduce the issue? 

### Steps to reproduce

Doubleclick a word in a text.

**Expected behavior:**

**select the word only**

### Versions

- MarkText version: 0.17.0
- Operating system: Win 10 64 bits

**Comment by DYH-Hong** [comment]
Duplicate of #2166
