### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by xAvatar6969** [marktext/marktext#3162]
### Description

I'm using Windows 11 and there isn't any animation for the window (open, minimize, close).

- [ x ] Can you reproduce the issue? 

### Steps to reproduce

1. open Marktext
2. minimize Marktext
3. close Marktext

**Expected behavior:**

Animations

**Actual behavior:**

No animations

### Versions

- MarkText version: 0.17.1
- Operating system: Windows 11 21H2

**Comment by fxha** [comment]
Upstream bug: https://github.com/electron/electron/issues/32993.
