### ISSUE TITLE
How to use command line script?

### ISSUE THREAD

**Issue by hollywh** [marktext/marktext#3163]
### Question description

What are the input and output content format requirements for the uploader command line script?

**Comment by hollywh** [comment]
I found it works with this script:
```
#!/bin/bash
img="$(picgo u $1)"
echo $img|tail -n 1|awk '{print $NF}'
```
test with command:
`./picgo_upload.sh ~/tmpphotos/JPA.png`
The output as(url only):
`http://192.168.1.223:18081/imgs/JPA.png`

**Comment by qqlyg** [comment]
> 

windows11 how to do ?
