### ISSUE TITLE
Build failed with Exit Code: ENOENT. (spawn /usr/bin/python ENOENT)

### ISSUE THREAD

**Issue by colorfulappl** [marktext/marktext#3175]
### Description

- [x] Can you reproduce the issue? 

#### Issue Details

While I'm trying to build the latest version of MarkText by command
```bash
yarn run build
```
, it failed with message:
```log
...
  ⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
    at /Users/test/marktext/node_modules/builder-util/src/util.ts:133:18
    at exithandler (node:child_process:406:5)
    at ChildProcess.errorhandler (node:child_process:418:5)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
  • Above command failed, retrying 5 more times
  • Above command failed, retrying 4 more times
  • Above command failed, retrying 3 more times
  • Above command failed, retrying 2 more times
  • Above command failed, retrying 1 more times
  • Above command failed, retrying 0 more times
  • building block map  blockMapFile=build/marktext-arm64-mac.zip.blockmap
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I did not install Pytyhon2, so there is not `/usr/bin/python` on my system.
I tried to set `PYTHON_HOME` to my installed Python3, but it failed with another error while executing python code.

#### Root cause

Seems it's a dependency issue of electron-builder:
https://github.com/electron-userland/electron-builder/issues/6726

#### Workaround

I upgrade electron-builder version to `23.0.3` in `package.json`, it can be built normally.

But since I'm not familiar with MarkText, I'm not sure whether this upgrade will introduce another compatibility issues.

### Steps to reproduce

1. `git checkout develop`
2. `git pull`
3. `yarn install`
4. `yarn run build`

**Expected behavior:**

Build success.

**Actual behavior:**

Build failed with message listed above.

### Versions

- MarkText version:
    develop (commit 2bb405a03ee52cfba2afe53da4656abb799a0727)
- Operating system:
    macOS 12.3

**Comment by happyslowly** [comment]
I also ran into this issue, and I solved it by following steps:
1. `pyenv install 2.7.18`
2. `export PYTHON_PATH=$HOME/.pyenv/versions/2.7.18/bin/python`
3. `yarn run build`
