### ISSUE TITLE
Keep the image's original name when i paste it from my local PC

### ISSUE THREAD

**Issue by xtay573269555** [marktext/marktext#3177]
### Describe your feature request

Hope to add the option to keep the image's original name when i paste it from my local PC.
I set the images saved to `${filename}.assets` folder.

### What problem does this feature solve? [optional]
Keep the image name more readable. The image name is changed to a random string now.

Thanks for reading.

**Comment by YalandHong** [comment]
Related to #3119.

**Comment by YalandHong** [comment]
Related to #3119.
