### ISSUE TITLE
Markdown style on headings can not apply to the sidebar

### ISSUE THREAD

**Issue by sillysillyc** [marktext/marktext#3178]
### Description

when giving headings some markdown style it won't behave correct.
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. give a underline style on heading 1 text like： '# \<u>一、heading 1 text\</u>'

**Expected behavior:**

the text shows with underline style instead of the source code;

**Actual behavior:**

 it behaves noramlly in main body with underline style, but it shows like: '\<u>一、heading 1 text\</u>' in sider bar

**Link to an example: [optional]**

### Versions

- MarkText version: v0.17.1
- Operating system:  macOS Monterey 12.3

**Comment by mangoepic** [comment]
![image](https://user-images.githubusercontent.com/71931749/161957752-271a3fe4-6e5b-4e66-999d-b0824361737f.png)
It seems to work in MarkText v0.17.1, Windows 11 21H2

**Comment by sillysillyc** [comment]
just like this
 <img width="760" alt="截屏2022-04-06 18 48 57" src="https://user-images.githubusercontent.com/30365172/161958675-c4097059-e57f-4ff2-abc7-fc405f6aa373.png">

**Comment by mangoepic** [comment]
Ah, I see now, same happens here too
![image](https://user-images.githubusercontent.com/71931749/161959560-789b5a48-2822-4290-850a-b8c2df1871b8.png)

I would call the issue "Header style symbols displayed in Table of Contents"

**Comment by sillysillyc** [comment]
i mean the red part did not apply the style, and do you think It don't look very harmonious
![image](https://user-images.githubusercontent.com/30365172/161969522-94f1a441-63f3-4ea4-8df7-d37038f6185f.png)

**Comment by mangoepic** [comment]
> i mean the red part did not apply the style, and do you think It don't look very harmonious? ![image](https://user-images.githubusercontent.com/30365172/161969522-94f1a441-63f3-4ea4-8df7-d37038f6185f.png)

I wouldn't have expected the style to get applied, just the style modifiers to get removed... Getting applied could be interesting but I don't think it's necessary.... For example if you want to underline every header, they would all be underlined in the table of contents which would make it less readable

**Comment by sillysillyc** [comment]
alright, thanks for following the issue, but still look forward to your guys apllying the style someday

**Comment by mangoepic** [comment]
@sillysillyc why did you close it, the bug is still there I'm just adding my thoughts, not a dev. 😄

**Comment by sillysillyc** [comment]
@mangoepic will this issue be fixed?  I thought you guys think it is not a bug and you would not fix that so i closed it...haha
