### ISSUE TITLE
Copy-pasting title deletes text

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#321]
### Description

Copy pasting a title from a website replaces the current line instead of appending it

### Steps to reproduce

1. Go to https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange
2. Select `XMLHttpRequest`
3. `CTRL+C`
4. Open MarkText
5. Write `Goodbye World`
6. `CTRL+V`

**Expected behavior:** That the text (`XMLHttpRequest`) gets appended to `Goodbye World`

**Actual behavior:** `Goodbye World` gets replaced by the text

### Versions

- Mark Text: v 0.11.42
- OS: Windows 10

**Comment by fxha** [comment]
Thanks @stefnotch.

To give some more details: the bug remove text before the inserted heading only.
