### ISSUE TITLE
snap安装，无法使用中文输入法

### ISSUE THREAD

**Issue by honyxiao** [marktext/marktext#322]
### Description

使用snap安装的，无法使用中文输入法。
使用appimage包，能使用中文输入法。

### Steps to reproduce

1. 安装 sudo snap install --classic --dangerous marktext_0.11.42_amd64.snap
2. 启动
3. 切换输入法无效

**Expected behavior:** 能使用中文输入法

**Actual behavior:** 无法使用中文输入法

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: v 0.11.42
- OS: ubuntu 18.04 (gnome、fcitx google拼音)

**Comment by fxha** [comment]
I'm closing this issue because we dropped snap support. The flatpak application supports fcitx as far as I know.

**Comment by oSoMoN** [comment]
This might come in late, but I thought I'd inform you that snaps now support fcitx input as of https://github.com/ubuntu/snapcraft-desktop-helpers/commit/5a5ab9f20c8825c81692db6dced75ec9ed8a8820.

Simply rebuilding an existing snap against the latest desktop-gtk3 part would enable fcitx input.
