### ISSUE TITLE
the website seems to be down

### ISSUE THREAD

**Issue by Not-a-web-Developer** [marktext/marktext#3226]
### Description

https://marktext.app seems to be down (is reporting ERR_CONNECTION_CLOSED on chromium based browsers and PR_END_OF_FILE_ERROR on firefox); I tried loading the website on multiple devices and networks, and it didn't load.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. opening https://marktext.app in a browser.

**Expected behavior:**

the website would open.

**Actual behavior:**

the website didn't open.

**Comment by winstonDeGreef** [comment]
Currently i'm getting the following error instead: `marktext.app unexpectedly closed the connection.`. I'm running Chrome `Version 100.0.4896.75 (Official Build) (64-bit)` on Ubuntu.

**Comment by FireInIceCode** [comment]
I can't load it by Microsoft Edge on Windows 11, either.

**Comment by TheMathGuyd** [comment]
On mac,
- Safari does not load the page
- Firefox give the error `PR_END_OF_FILE_ERROR`

If the issue is not trivial to fix, can the dns be updated to redirect to the github repo temporarily?

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #3194. You may want to subscribe there for further updates.
