### ISSUE TITLE
JSON Schema validation

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#324]
### Description

Validate settings (`preferences.md` code block) with JSON Schema. If the validation fails, load default settings.

http://json-schema.org/

**Comment by Jocs** [comment]
I think that we can validate user preferences before he save it, if it not validated, we can show some message in the opened window?

**Comment by fxha** [comment]
Sounds good, but how to check if current file is `preferences.md`. We have to hard code full-path for macOS, Linux and Windows.

**Comment by Jocs** [comment]
@fxha 

In the open window, save a state value, such as `isOpenPreference`. When saving, transfer this state value to the main process. So we know weather it is save user preferences?

**Comment by Jocs** [comment]
@fxha Maybe I will optimize the user preference recently and change it to the operation interface, which will be more convenient to use.
