### ISSUE TITLE
Blank line auto-disappear, Is a file optimization or a bug?

### ISSUE THREAD

**Issue by Youpen-y** [marktext/marktext#3267]
I insert some blank lines in a file and save it. but everytime when I open it again, I find the blank lines have been deleted. Is a file optimization or just a bug? If it was a optimization, is there a method to close this behavior?

**Comment by wuya666** [comment]
I don't think it's an optimization nor a bug, it just follows the Markdown language standard where multiple blank lines are not meaningful. If you want to <i>display</i> multiple adjacent blank lines, you should put an `&nbsp;` entity or `<br />` tag on that line and it will show up  as a blank line, something like:

```
Hello
&nbsp;
&nbsp;
<br/>
<br/>

World
```

There will be five blank lines between `Hello` and `World` like this:

Hello
&nbsp;
&nbsp;
<br/>
<br/>

World

**Comment by Youpen-y** [comment]
Thanks for your explanation, I got it.
