### ISSUE TITLE
Information in marktext/docs/APPLICATION_DATA_DIRECTORY.md is incorrect

### ISSUE THREAD

**Issue by dgl-dev** [marktext/marktext#3276]
### Description
Info provided
"Application Data Directory
The per-user application data directory is located in the following directory:

%APPDATA%\marktext on Windows
$XDG_CONFIG_HOME/marktext or ~/.config/marktext on Linux
~/Library/Application Support/marktext on macOS"
- [ ] Can you reproduce the issue? Yes, the documentation doesn't change

### Steps to reproduce

N/A

I expected the information to be correct

**Actual behavior:**

The information states that the themes/export directory is in the ~/.config/marktext on Linux
That is not so, here's the actual contents
```
limawhiskeydelta@penguin:~/.config/marktext$ ls
 blob_storage   dataCenter.json  'Local Storage'              preferences.json               SingletonCookie
 Cache          dictionaries      logs                        recently-used-documents.json   SingletonLock
'Code Cache'    Dictionaries     'Network Persistent State'   screenshot                     SS
 Crashpad       GPUCache          Preferences                'Session Storage'               window-state.json
```

### Versions

- MarkText version: [marktext-x86_64.AppImage](https://github.com/marktext/marktext/releases/download/v0.17.1/marktext-x86_64.AppImage)
108 MB
Mar 07, 2022
- Operating system: Debian, Buster

**Comment by fxha** [comment]
Actually, this is the right directory which contains both Electron cache/settings and MarkText settings as described in our documentation. E.g. `~/.config/marktextthemes/export/` is the default location for CSS files for PDF output or `~/.config/marktext/preferences.json` contains settings. Depending on your build version this may be `marktext` with a suffix.

**Comment by dgl-dev** [comment]
First, the docs say "$XDG_CONFIG_HOME/marktext` or `~/.config/marktext` on Linux", not ~/.config/marktextthemes/export/
Second,  there is no such in .config as the ls output I included shows
```
limawhiskeydelta@penguin:~/.config/marktext$ ls
 blob_storage   dataCenter.json  'Local Storage'              preferences.json               SingletonCookie
 Cache          dictionaries      logs                        recently-used-documents.json   SingletonLock
'Code Cache'    Dictionaries     'Network Persistent State'   screenshot                     SS
 Crashpad       GPUCache          Preferences                'Session Storage'
```
Third, I've used find to search the entire system for marktext, marktext/export, marktextthemes, themes with no success - the search `sudo find / -type d -name "themes"` finds the themes for ghostscript, JetBrains, inkscape, GIMP, ... but not marktext

SO,...???

**Comment by fxha** [comment]
> First, the docs say "$XDG_CONFIG_HOME/marktextor~/.config/marktext` on Linux", not ~/.config/marktextthemes/

I fixed my typo from above.

> Second, there is no such in .config as the ls output I included shows

In your example from above, you're located in the settings folder (`~/.config/marktext`). You need to create the themes' folder inside the MarkText's settings folder. E.g. run the following command when located in `~/.config/marktext`:

```
$ mkdir -p themes/export
$ touch my-theme.css
```

**Comment by dgl-dev** [comment]
Thanks, cool!
If someone wiill give me the info, I'll try to convert the old format themes to json

Les Dunaway
770-490-7546 <http://voice.google.com/calls?a=nc,%2B17704907546>



On Sun, May 29, 2022, at 16:38, Felix Häusler wrote:
> 
> 
>> First, the docs say "$XDG_CONFIG_HOME/marktextor~/.config/marktext` on Linux", not ~/.config/marktextthemes/
>> 
> I fixed my typo from above.
> 
>> Second, there is no such in .config as the ls output I included shows
>> 
> In your example from above, you're located in the settings folder (`~/.config/marktext`). You need to create the themes' folder inside the MarkText's settings folder. E.g. run the following command when located in `~/.config/marktext`:
> 
> `$ mkdir -p themes/export
> $ touch my-theme.css
`
