### ISSUE TITLE
How to modify multiple instances?

### ISSUE THREAD

**Issue by fanrongqitiancai** [marktext/marktext#3277]
### Question description

I want to open multiple marktexts at the same time. How to modify the code to achieve,

marktext\src\main\index. js

There is a piece of code in

// Make MarkText a single instance application.

if (!process.mas && process.env.NODE_ENV !== 'development') {

const gotSingleInstanceLock = app. requestSingleInstanceLock()

if (!gotSingleInstanceLock) {

process. stdout. write('Other MarkText instance detected: exiting...\n')

app. exit()

}

}

I commented and there was an error in the compilation.

**Comment by fxha** [comment]
You can open multiple editor windows of MarkText or use a different [application data directory](https://github.com/marktext/marktext/blob/master/docs/PORTABLE.md). Starting MarkText without the lock above may lead to undefined behavior and isn't supported.
