### ISSUE TITLE
Disabling source code mode via shortcut does not work

### ISSUE THREAD

**Issue by jkrzefski** [marktext/marktext#328]
### Description

I found an issue with the keyboard shortcuts unter macOS when I tried to toggle the source code mode. Enabling it by pressing CMD+U works fine, but disabling it seems impossible to achieve by shortcuts. I tried a few different variations of the expected CMD+U shortcut but I eventually gave up. It seems to me that disabling the source code mode via keyboard shortcut not possible in the current build. 

### Steps to reproduce

1. Switch to source code mode
2. Try to switch back to normal by pressing CMD+U

**Expected behavior:** I expected the editor to switch back to normal mode. 

**Actual behavior:** It actually did not.

### Versions

- Mark Text: 0.11.42
- OS: macOS High Sierra, 10.13.4

**Comment by fxha** [comment]
@Jocs Before you change shortcuts again: I think we have a conflict with CodeMirror's shortcuts which are enabled by default: [CodeMirror's keymaps](https://github.com/codemirror/CodeMirror/blob/master/src/input/keymap.js#L8-L47). Do you wanted this "feature" or did not you know that?

e.g: ` "Ctrl-U": "undoSelection"`

**Comment by Jocs** [comment]
@fxha 

I know that the previous shortcuts and codemirror shortcuts conflict, but I did not specifically see and what shortcut keys conflict, I just simply think that `alt + ctrl + s` is more suitable for switching source code mode. If this doesn't work on Linux or Windows, I'll consider solving the problem of shortcuts with codemirror

**Comment by fxha** [comment]
I am currently using Windows and `Ctrl+Z` only works inside CodeMirror text area. So might be a similar issue (#311). I'll test `ctrl+alt+s` this evening.

**Comment by Jocs** [comment]
@fxha 
>I am currently using Windows and Ctrl+Z only works inside CodeMirror text area. 

Do you mean that `Ctrl + Z` dose not work on Windows?

**Comment by fxha** [comment]
Yes, on Linux and Windows (#311).

**Comment by Jocs** [comment]
I’m also confused about shortcuts, because many work well on Mac, and it’s not normal for windows and Linux.
