### ISSUE TITLE
Feature: ability to insert an empty line between elements

### ISSUE THREAD

**Issue by rootex-** [marktext/marktext#33]
Say, we have a code block and a table following right after the code block, right in the next line. In this case, we have a problem: inability to insert an empty line or anything else between the code block and the table.

**Comment by Jocs** [comment]
😢 Yes, It's really a problem, Now Mark Text only have one way to insert new line between code block and table, choose the source code mode, insert new line, and back to realtime mode...

but it's not convenient.

**Comment by Jocs** [comment]
@rootex- Do you have any idea on how to insert new line between code block and table.

**Comment by rootex-** [comment]
@Jocs One of the simplest solutions might be an automatic generation of an empty line after the element (code block, table, etc).
Another solution can be actually a very cool feature: "A pannel with auto-appearing elements". If there is no line between two elements, draw a little "plus" button between them on the left, thus you offer to insert a line. Pretty intuitive UI, right? 
In perspective, that pannel could be extended with additional options and cool features and provide an app with some extra interactivity.

**Comment by Jocs** [comment]
@rootex- I also think the second solution is cool, it's more visible for users, there is maybe a third solution, It is already in Mark Text, add two code blocks, use arrow up and down between them, You can see a new line inserted automatically. But I forget add this feature to table block.
