### ISSUE TITLE
Text cursor skips lines in paragraphs

### ISSUE THREAD

**Issue by jkrzefski** [marktext/marktext#330]
### Description

I have a couple of paragraphs in my markdown file that are long enough to fill multiple lines each. When I use the `up` and `down` arrow keys to move the text cursor one line up, it skips to the next paragraph instead. To get further up inside a paragraph I have to keep going left until I reach the previous line. I am not sure if this is intentional or not because I know these paragraphs are just one line each in plain markdown. But either way this is frustrating and counterintuitive. The whole point of Mark Text is to make working with markdown files easier. This bug (or feature?) defeats that purpose.

### Steps to reproduce

1. Have paragraphs of multiple lines each.
2. Navigate the text cursor up and down using the `up` and `down` arrow keys

**Expected behavior:** The text cursor goes up **one line**.

**Actual behavior:** The text cursor goes up **one paragraph**.

### Versions

- Mark Text: 0.11.42
- OS: macOS High Sierra, 10.13.4

**Comment by Jocs** [comment]
@jkrzefski I agree with you that Mark Text really should handle the up and down arrow keys in a more natural way, instead of jumping directly to the previous or next paragraph.

But in order to achieve this natural way, it may take some time, but we will achieve it.
