### ISSUE TITLE
marktext.app is down

### ISSUE THREAD

**Issue by stevesobol** [marktext/marktext#3312]
The domain is registered, but my web browser says there is an NXDOMAIN when I try to visit https://marktext.app.

Thanks

**Comment by aHappyConstant** [comment]
Duplicate of #3243 and #3284

**Comment by lianxia2020** [comment]
[https://marktext.app](https://marktext.app/)/Cannot open while accessing this site, Browser tips:DNS_PROBE_FINISHED_NXDOMAIN

**Comment by aleung** [comment]
https://github.com/marktext/website/issues/70

**Comment by imran-ur-rahman** [comment]
![Marktext app Domain Error](https://user-images.githubusercontent.com/41681974/183702904-a6ac3a6c-ac05-4fdd-b018-ae9316eb2443.png)

**Comment by Jocs** [comment]
The new official website is already available, https://www.marktext.cc/
