### ISSUE TITLE
[BUG]: cannot open it on m1

### ISSUE THREAD

**Issue by h3n4l** [marktext/marktext#3333]
### Description
I download version 0.17.1 and install it.
"MarkText" is damaged and can't be open for Mac M1 Pro 14'.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Download Marktext v0.17.1.

![CleanShot 2022-07-01 at 02 50 10@2x](https://user-images.githubusercontent.com/87714218/176755313-07d83597-4202-4e2d-8ed8-e4ac6320eaa8.png)

2. Install it
3. Open it
<img width="261" alt="CleanShot 2022-07-01 at 02 50 56@2x" src="https://user-images.githubusercontent.com/87714218/176755428-4e8e25bf-4f0c-49a7-b3bc-ad566cd0a237.png">

### Versions

- MarkText version: v0.17.1 arm64 dmg
- Operating system:
<img width="698" alt="CleanShot 2022-07-01 at 02 51 24@2x" src="https://user-images.githubusercontent.com/87714218/176755501-9965840b-7ba9-4297-92b4-8cb9b530b673.png">

**Comment by YalandHong** [comment]
Dup of #2983.

The file isn't broken. Iit's just not signed. Newer version of MacOS prevent you from running untrusted software.

You may also encounter such error in other apps and you need to manually mark them as trusted.

**Comment by h3n4l** [comment]
> Dup of #2983.
> 
> 
> 
> The file isn't broken. Iit's just not signed. Newer versions of MacOS prevent you from running untrusted software.
> 
> 
> 
> You may also encounter such error in other apps and you need to manually mark them as trusted.

Thanks, let me try it

**Comment by fxha** [comment]
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2983. You may want to subscribe there for further updates.
