### ISSUE TITLE
When entering hyperlink tab should jump to next brackets.

### ISSUE THREAD

**Issue by Emptyfruit** [marktext/marktext#334]
### Description

When entering hyperlink tab should jump to next brackets.

### Steps to reproduce

1. On a new line press hyperlink hotkey (CMD+L)
2. write the link description in square brackets
3. press `tab` (intuitively)

**Expected behavior:** [What you expected to happen]
I'd expect it to jump to round brackets for writing or pasting the link. I don't think there is lots of use cases when you need tabs inside link description.
**Actual behavior:** [What actually happened]
tab is inserted inside link description

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: v 0.11.42
- OS: 10.13.4

**Comment by Jocs** [comment]
@Emptyfruit I think there are also users who may use tabs in `[]` to insert spaces. So this demand may not be established

**Comment by Emptyfruit** [comment]
@Jocs I don't think you'd ever need to insert several spaces inside link description. It is such a rare case, that the person won't break to hit 4 spaces. On the contrary, pressing tab is just an intuitive flow, resulting in deleting unwanted spaces and using key arrows in the end. As i understood, the goal of this app is to make writing md as easy as simple text, so the flow is important here.

Also, some markdown interpreters ignore such spaces.
