### ISSUE TITLE
Package marktext as a vscode extension

### ISSUE THREAD

**Issue by infogulch** [marktext/marktext#3346]
### Describe your feature request

Marktext is a great UI for writing markdown, and would be nice to use in coding contexts. Have you considered packaging marktext as a vscode (vscodium) extension? This would enable users to edit notes and documentation with marktext alongside my normal code and notes in their normal development environment.

I think it would be especially useful for note taking extension sets like [Foam](https://foambubble.github.io/foam/).

### What problem does this feature solve?

This would enable broader use of marktext's great markdown editor in other contexts.

### Additional context

I'm not sure how much work it would be to translate the editor from an electron app into a form suitable as a vscode extension. Any input from someone familiar with both would be great.

**Comment by YalandHong** [comment]
Related to https://github.com/marktext/marktext/issues/2404, https://github.com/marktext/marktext/issues/2493, https://github.com/marktext/marktext/issues/2503, #3143

MarkText may not support this feature officially. But the core is written in JS. So theoretically it will work outside electron with some modifications.

**Comment by infogulch** [comment]
Thank you for referencing those issues. I'm surprised that my search did not turn them up; didn't look at page 2 I guess 😞
