### ISSUE TITLE
Marktext.app May be available for sale

### ISSUE THREAD

**Issue by SunsetMkt** [marktext/marktext#3371]
### Description
Marktext.app is down.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Visit marktext.app
2. It's not available.

**Expected behavior:**
The website works.

**Actual behavior:**
It shows "Marktext.app May be available for sale".

**Link to an example: https://marktext.app/**

### Versions

- MarkText version: Doesn't matter.
- Operating system: Doesn't matter.

**Comment by SunsetMkt** [comment]
#3348

**Comment by LevZed** [comment]
You forgot the "about" section
![изображение](https://user-images.githubusercontent.com/20744932/182886730-20708e7a-12ab-4618-9ec4-cf711f50679e.png)

**Comment by LevZed** [comment]
> You forgot the "about" section ![изображение](https://user-images.githubusercontent.com/20744932/182886730-20708e7a-12ab-4618-9ec4-cf711f50679e.png)

@CouldBeThis

**Comment by CouldBeThis** [comment]
@LevZed I think you have to be a maintainer to edit that in the project settings, it is not available to PRs as far as I know.
