### ISSUE TITLE
Error log message if you abort html or pdf export dialog 

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#338]
### Description

If you export a document and  abort the save dialog, a log entry is written.

**Problem:** I guess a empty string is send to the export function.

### Steps to reproduce

1. Click on `Export (Styled) HTML` or `Export PDF`
2. A native file save dialog is opened; click `x` or cancel the dialog
3. Log file has a new entry: `[ERROR] Cannot save file without path.`

**Expected behavior:** [What you expected to happen]

No error log entry.

**Actual behavior:** [What actually happened]

See above.

### Versions

- Mark Text: < v0.10.21 and master (upcoming v0.12.x)

**Comment by Jocs** [comment]
@fxha It seems that error happened in method `handleResponseForExport` of file:`./src/main/actions/file.js`.

We need to judge weather the filePath is existed, because if user click `cancel` button, the filePath is `undefined`.

PR is welcomed!
