### ISSUE TITLE
Sidebar always on / 侧边栏常开

### ISSUE THREAD

**Issue by IzayoiAster** [marktext/marktext#3383]
请问能否提供“打开程序时默认打开侧边栏”之类的选项呢，因为经常使用侧边栏，每次都要手动开启有些麻烦
Could you provide an option like "open the sidebar by default when opening marktext"? as the sidebar is often used

**Comment by tccrabyoguy** [comment]
[https://github.com/marktext/marktext/blob/develop/docs/PREFERENCES.md](https://github.com/marktext/marktext/blob/develop/docs/PREFERENCES.md)

这里有设置方法

**Comment by IzayoiAster** [comment]
> https://github.com/marktext/marktext/blob/develop/docs/PREFERENCES.md
> 
> 这里有设置方法

感谢，找到了
