### ISSUE TITLE
hope can have portable version (windows

### ISSUE THREAD

**Issue by bluelovers** [marktext/marktext#34]
### Description

希望能有免安裝版
另外是不是沒有類似工具列的東西? (好像沒看見

或者也許可以考慮像 Haroopad 一樣
有類似這種可以直接點擊的

![2018-03-19-20-30-41-1](https://user-images.githubusercontent.com/167966/37595699-b3be771a-2bb4-11e8-8ef6-c382a324a09e.jpg)

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

### Versions

- Mark Text: marktext-setup-0.6.14.exe
- OS: windows 10 1709

**Comment by Jocs** [comment]
@bluelovers Hi, 希望你提供操作系统型号和版本，因为有快捷键，所以暂时不考虑工具列。如果是 OS X 系统，有免安装版本。

**Comment by Jocs** [comment]
- wowowow 
  - wowow
   - wowowow
- wowowo

**Comment by bluelovers** [comment]
@Jocs windows 10 1709

雖然不確定是不是
不過看起來 windows 版結構與 https://github.com/meowtec/Imagine/releases
相似

所以應該也能提供解壓縮就可以的 windows portable 版

另外提供 像 Haroopad 一樣
的看起來雖然是語法提示 但實際上又等於是工具列一樣的東西也不錯

希望能考慮考慮

------------

以及似乎沒有滑鼠右鍵選單?

**Comment by SuperSandro2000** [comment]
I think you can just unzip the installer.

**Comment by Jocs** [comment]
@bluelovers Left click to open context menu is in the TODU LIST now.
