### ISSUE TITLE
marktext.app domain showing a for sale advert

### ISSUE THREAD

**Issue by brendanbbbb** [marktext/marktext#3407]
The link on the github project for marktext.app takes you to a for-sale landing page. Domain should be removed from the project to update to something valid.

Location
![image](https://user-images.githubusercontent.com/20751806/185264040-dff180bb-224e-43ee-b619-dd34156d9e11.png)

Result
![image](https://user-images.githubusercontent.com/20751806/185263932-c1cfa2d3-a73b-4c9d-a0c6-a9ee3ebe213a.png)

**Comment by filbotblue** [comment]
I am also seeing a similar thing.

![image](https://user-images.githubusercontent.com/96255204/186940925-7bfbd65c-6161-4cb9-8ec8-a8b49e2f9d2a.png)

**Comment by ctwhome** [comment]
yep, not fixed still.

**Comment by Jocs** [comment]
The new official website is already available：https://www.marktext.cc/
