### ISSUE TITLE
Switching from source code mode back to normal collapses code blocks

### ISSUE THREAD

**Issue by jkrzefski** [marktext/marktext#342]
### Description

I have a document with some paragraphs and some code blocks. When I switch from source code mode back to normal mode, all the code blocks are collapsed to one line with no visible content. When I click inside such a code block, it expands and shows its content. As far as I have observed it, it stays expanded until I switch to source code mode and back to normal again.

Side note: I found that the collapsed code blocks also expand when I switch the theme. I suspect this is because a theme switch triggers a layout reload.

### Steps to reproduce

1. Have a document with code blocks in it
2. Switch to source code mode
3. Switch back to normal mode

**Expected behavior:** The code blocks should be expanded as normal.

**Actual behavior:** The code blocks are collapsed until you click on them or switch the theme.

### Versions

- Mark Text: 0.12.20
- OS: macOS 10.13.4

**Comment by Jocs** [comment]
@jkrzefski 

Can you show me a picture or gif about:

>all the code blocks are collapsed to one line with no visible content.

**Comment by jkrzefski** [comment]
@Jocs No problem. I made three quick screenshots.

### Normal mode:
![bildschirmfoto 2018-06-17 um 15 54 16](https://user-images.githubusercontent.com/11394739/41508565-3bce2c12-7247-11e8-9361-4c7de3deef7d.png)

### Switch to source code mode:
![bildschirmfoto 2018-06-17 um 15 54 37](https://user-images.githubusercontent.com/11394739/41508575-5c5bee6a-7247-11e8-922b-6fda0aafe2d5.png)

### Switch back to normal mode:
![bildschirmfoto 2018-06-17 um 15 54 55](https://user-images.githubusercontent.com/11394739/41508578-621069bc-7247-11e8-8cb6-4fd9ec1c89eb.png)
