### ISSUE TITLE
我想要对齐方式的设置

### ISSUE THREAD

**Issue by Crzq** [marktext/marktext#3420]
我想要文字靠左对齐，可是找不到设置。

**Comment by remyhuang03** [comment]
Markdown本身没有文字排版功能，可以内嵌html代码指定text-align

**Comment by Crzq** [comment]
我想让全文都是向左对齐，像Typora那样；但是它默认是居中的盒子。

**Comment by Davion2017** [comment]
可以设置编辑界面的最大宽度，设置成100%的话就会默认从屏幕最左边开始显示了
在preference -> Editor -> Text editor settings -> maximun width of text editor

**Comment by Crzq** [comment]
Good job, bro! This's absolutely what I want!
