### ISSUE TITLE
Bug: macOS arm version not working

### ISSUE THREAD

**Issue by Neko-vecter** [marktext/marktext#3427]
The macOS version of marktext 0.17.1 

The version I try.
[marktext-arm64.dmg](https://github.com/marktext/marktext/releases/download/v0.17.1/marktext-arm64.dmg)
[marktext-arm64-mac.zip](https://github.com/marktext/marktext/releases/download/v0.17.1/marktext-arm64-mac.zip)

System info 
macOS 12.5
M1 Pro (MacBook Pro 14)

**Comment by nrthbound** [comment]
@Neko-vecter Could you please add some context? What do you mean it isn't working? What happens when you try to use it? Do you get an error? Does it just CTD?

**Comment by Neko-vecter** [comment]
just show damaged. x64 version is fine.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/36069884/186312468-4189f52d-a7e4-458d-9aa3-2d8bbc8287dc.png">

**Comment by YalandHong** [comment]
Duplicate of #2983

**Comment by Neko-vecter** [comment]
> Duplicate of #2983

Can is issue be fix on later version?

**Comment by Neko-vecter** [comment]
> Duplicate of #2983

I think this issue can’t be fix.
I just Close this issue
