### ISSUE TITLE
Inconsistent color scheme in source code mode with dark theme

### ISSUE THREAD

**Issue by jkrzefski** [marktext/marktext#343]
### Description

The color scheme of the source code mode with the dark theme appears to be broken. It seems to be a mix of light and dark theme.

* The background around the text area is from the light theme.
* The background of the text area is from the dark theme.
* The text color is from the dark theme.
* The background of the paragraph that the text cursor is in is from the light theme.

### Steps to reproduce

1. Activate the dark theme
2. Activate the source code mode

**Expected behavior:** The color scheme should match the dark theme.

**Actual behavior:** The color scheme seems to be a mix of both themes.

### Versions

- Mark Text: 0.12.20
- OS: 10.13.4

**Comment by Jocs** [comment]
@jkrzefski thanks for report this bug, can you help with this issue and submit a PR?

**Comment by jkrzefski** [comment]
@Jocs Unfortunately not for two reasons:

1. I am not that familiar with `vue.js`.
2. I have basically no time.

**Comment by Jocs** [comment]
@jkrzefski thanks all the same, we will fix it asap.
