### ISSUE TITLE
fail to export pdf if markdown file too big

### ISSUE THREAD

**Issue by easyeda2021** [marktext/marktext#3433]
### Description

if the markdown file too big to export pdf, and no any error message
![图片](https://user-images.githubusercontent.com/29702100/187032221-0702429d-3961-48d8-9b88-a2c3ea1649f9.png)

- [x ] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]create big markdown, over 8w words, 18w text, 1200 images
2. [Second step]open and export pdf
3. [and so on...]nothing happen

**Expected behavior:**
export pdf

**Actual behavior:**
nothing happen

**Link to an example: [optional]**

### Versions

- MarkText version: v0.17.1
- Operating system: win10 and win11

**Comment by StephenChips** [comment]
Can you provide the Markdown file that marktext failed to export to?

**Comment by easyeda2021** [comment]
> Can you provide the Markdown file that marktext failed to export to?
Yes，but I didn't attach the images, its too many, please check
thanks
[LCEDA-Pro-Tutorial_v1.8.22.md](https://github.com/marktext/marktext/files/9449930/LCEDA-Pro-Tutorial_v1.8.22.md)

**Comment by StephenChips** [comment]
Tested, it worked, but very slow. It took around 30 seconds to complete exporting. Here are codes that do the job, which locates at the file `src/main/menu/actions`.

![image](https://user-images.githubusercontent.com/17926083/187367798-89c278b0-42a4-4815-8f18-8ff1d9c7df9e.png)

`console.time` and `console.timeEnd` is added by me just for debugging, and they printed:

![image](https://user-images.githubusercontent.com/17926083/187368235-5e9afa15-05d3-4936-bf84-acb9bf789188.png)



Maybe we should add some prompts and UI/UX effects while exporting.

**Comment by easyeda2021** [comment]
> 

yes, you are right, when I add the images, it takes 4minutes to export PDF, when I wait it more than 30s no result, I thought it was failed without errors

**Comment by easyeda2021** [comment]
typora faster than marktext

**Comment by easyeda2021** [comment]
it isn't a bug. I closed this issue,

thank you
