### ISSUE TITLE
In preview mode > should be able to delete emoji with one backspace

### ISSUE THREAD

**Issue by dcookwebdev** [marktext/marktext#345]
### Description

It is possible to insert emoji with a keyword between two colons.
Deleting an emoji takes too long in preview mode with just using delete. It will take it out of emoji mode and make it a full string again. Then you are deleting one character at a time.

It's just counter-intuitive.

### Steps to reproduce

1. make an emoji with `:heart:`
2. delete the emoji

**Expected behavior:** [What you expected to happen]
One backspace will delete a rendered emoji.

**Actual behavior:** [What actually happened]
You need many backspaces to delete it.

### Versions

- Mark Text:0.12.20
- OS: macOS

**Comment by Jocs** [comment]
I may not agree with this because if I just want to change \:camel: to \:cat:. In fact, I don't really want to delete it all but just need to remove the `mel` character and then add the `t` character.

**Comment by Jocs** [comment]
But in markdown syntax, emoji is not just one character, it's a string to present a emoji, like :\cat:.

**Comment by Jocs** [comment]
I'LL close this issue, if you have any other detail, you can still comment here.
