### ISSUE TITLE
Website is not loading!

### ISSUE THREAD

**Issue by phtdacosta** [marktext/marktext#3472]
Simple as that, https://marktext.app/ is not loading properly in here, there is only a blank page. I am using the lastest version of Firefox (105.0.1)

**Comment by axb21** [comment]
In case it's helpful, at one point Firefox gave me a HSTS error when I tried to visit https://marktext.app/.

Now it says:
```
 The domain name
Marktext.app

May be available for sale

This domain name (without content) may be available for sale or lease by its owner through Bodis's domain sales platform. 
```
:scream:

**Comment by featherbear** [comment]
See https://github.com/marktext/marktext/pull/3350

**Comment by Jocs** [comment]
The new official website is already available, https://www.marktext.cc/
