### ISSUE TITLE
PDF export should not export the tab bar

### ISSUE THREAD

**Issue by dcookwebdev** [marktext/marktext#348]
### Description

PDF export currently exports the tab bar. It should not.

### Steps to reproduce

1. write stuff
2. make sure tab bar is visible
3. export to PDF

**Expected behavior:** [What you expected to happen]
PDF output should be a clean page without any UI elements.

### Versions

- Mark Text: 0.12.20
- OS: macOS

**Comment by jkrzefski** [comment]
I can confirm this. The tab bar is visible in PDF exports. Also, as @dcookwebdev says there should be no ui elements present in the export, I propose that an export should disregard the theme setting and always display the result in light theme.

**Comment by Jocs** [comment]
@dcookwebdev thanks for reporting this, we'll fix it asap.

**Comment by fxha** [comment]
Search-bar, notifications etc are displayed in the PDF too. I think the best way to solve this, #354, #349 and #360 is to use a proper pdf library.

**Comment by jkrzefski** [comment]
I assume the current view (including theme, sidebar, tabs, etc.) is just rendered by a pdf tool. If that is true, I think a solution would be to make a dedicated view for exports only with no ui-elements and a standardized theme setting and let that be rendered by the pdf tool.

**Comment by dcookwebdev** [comment]
@jkrzefski that solution will probably result in some unwanted behavior as we have now. Whatever is being used now to render a PDF is basically doing a one page screenshot. When you have multiple pages etc. it won't work. As @fxha has suggested a proper conversion library should be used instead.

Have a separate theme/style sheet applied (rather than what is used for the UI) is absolutely ideal as you have suggested @jkrzefski.

Lots of issues can be solved with the proper library.
Look at you #355 #354 #349 #360 👀
