### ISSUE TITLE
PDF export should have more parameters

### ISSUE THREAD

**Issue by 1dancook** [marktext/marktext#349]
### Description

A user should be able to define more parameters for PDF export. Example: top, bottom, left, right margins. Page size. Header/footer related parameters. Page numbering. etc.

### Versions

- Mark Text: 0.12.20
- OS: macOS

**Comment by fxha** [comment]
Electron recently added some [options](https://github.com/electron/electron/pull/18984/files#diff-9b078be8f43e00e3b99edb5be31fa353R1228) to the PDF functions.

**Comment by Jocs** [comment]
>Electron recently added some options to the PDF functions.

Great, I think we can add these parameters later.

**Comment by fxha** [comment]
Page numbering is currently not possible but other options are available with v0.16.0 soon.
