### ISSUE TITLE
Marktext is adding extra newlines for each list point

### ISSUE THREAD

**Issue by wireva** [marktext/marktext#3494]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create new doc
2. add a list by typing `- test`
3. add a few more points by pressing enter and typing something
4. go to source mode

**Expected behavior:**

```md
# test

- test
- test2
- test3
```

**Actual behavior:**

```md
# test

- test

- test2

- test3
```

### Versions

- MarkText version: v0.17.1
- Operating system: Manjaro

**Comment by wireva** [comment]
Same issue when using `*` instead of `-`. 
This behaviour is especially annoying if the produced markdown is later consumed by other markdown parser which will actually render that extra newline out (e.g. docusaurus)

**Comment by Sciss** [comment]
I also found this confusing. There is a preferences setting to turn this off: Preferences > Markdown > Lists > Prefer loose list items. If you turn that option off, you get 'tight' lists. If you click the [info link](https://spec.commonmark.org/0.29/#loose), it seems the reasoning is that with 'loose' lists you have a `<p>` paragraph around each list item.

**Comment by Sciss** [comment]
Duplicate of #2881

**Comment by wireva** [comment]
thank you for the info!
