### ISSUE TITLE
Do you know Chinese?

### ISSUE THREAD

**Issue by 89ck** [marktext/marktext#3496]
### Question description

If you know Chinese, can you make a Chinese version?

**Comment by qi-xmu** [comment]
github有人发汉化包 https://github.com/chinayangxiaowei/marktext-chinese-language-pack
后期作者应该会做国际化。

**Comment by JiaHaoXiong** [comment]
+1

**Comment by 89ck** [comment]
没有linux的汉化打包版本。

**Comment by qi-xmu** [comment]
> 没有linux的汉化打包版本。

这个应该可以自己打包吧哈哈，不过我没有尝试。
