### ISSUE TITLE
软件里怎么输入空行啊兄弟们55555

### ISSUE THREAD

**Issue by ape660** [marktext/marktext#3499]
### Question description

软件里enter输入空行，重新打开以后空行就被删了。有人知道怎么维持空行吗？

**Comment by wtf-ff** [comment]
貌似marktext不支持空行，我一直拿“---”假装空行的

**Comment by nen9mA0** [comment]
现在好像不行，因为软件自带一个自动格式化脚本，然后markdown的标准格式没有这种空行的写法（我印象在哪里看到过用的是github的一个markdown标准格式）。这个 [issue](https://github.com/marktext/marktext/issues/2189) 提到了类似的问题。包括你可能也发现了当你只是想看一个markdown文件，但往往打开以后就要提示你要不要保存，也是因为这个格式化功能。我其实挺希望把它做成可以开关，或者像issue里提到的文件只读时不修改

**Comment by liqiwenx** [comment]
> 现在好像不行，因为软件自带一个自动格式化脚本，然后markdown的标准格式没有这种空行的写法（我印象在哪里看到过用的是github的一个markdown标准格式）。这个 [issue](https://github.com/marktext/marktext/issues/2189) 提到了类似的问题。包括你可能也发现了当你只是想看一个markdown文件，但往往打开以后就要提示你要不要保存，也是因为这个格式化功能。我其实挺希望把它做成可以开关，或者像issue里提到的文件只读时不修改

作者目前还在维护这个仓库吗？还是基本已经处于半脱坑状态？这个问题1年前提出来好像到现在没有动静。而且很多pr也没人审核了。issue也在累计。

**Comment by nen9mA0** [comment]
> > 现在好像不行，因为软件自带一个自动格式化脚本，然后markdown的标准格式没有这种空行的写法（我印象在哪里看到过用的是github的一个markdown标准格式）。这个 [issue](https://github.com/marktext/marktext/issues/2189) 提到了类似的问题。包括你可能也发现了当你只是想看一个markdown文件，但往往打开以后就要提示你要不要保存，也是因为这个格式化功能。我其实挺希望把它做成可以开关，或者像issue里提到的文件只读时不修改
> 
> 作者目前还在维护这个仓库吗？还是基本已经处于半脱坑状态？这个问题1年前提出来好像到现在没有动静。而且很多pr也没人审核了。issue也在累计。

看commit记录似乎暂时AFK了，我三四个月前就因为没有内部链接跳转的功能来issue里找这个问题（之前一直用的typora，这个功能我还挺依赖的），发现很多人提就想着等下一个release发布应该会修，然后到最近发现仓库还是一直没有更新，于是前两天自己动手丰衣足食拖了个代码下来自己编译了。

有一说一我觉得这项目实在好用，如果一些bug能完善一下简直完美，就这样暂停维护的话实在可惜

**Comment by luohongzhan** [comment]
只能使用\<br\> 来换行，使用了下确实不方便，已经回去使用typora了
