### ISSUE TITLE
Icon Color

### ISSUE THREAD

**Issue by ahmmu15** [marktext/marktext#35]
I was wondering if you can change the color/s of the icon, because it doesn't look good on a dark background _(for example: I'm using [Win10 dark theme](https://image.ibb.co/emBFkH/ccc.png), and I can't see the icon when I pinned it to the task bar)_.

Thank you 💯

**Comment by Jocs** [comment]
@ahmmu15 same issue as #24, Thank you for your reporting, the new icon is under designing, This issue will be closed.
