### ISSUE TITLE
Tree view should be separate from "Toggle Side Bar"

### ISSUE THREAD

**Issue by dcookwebdev** [marktext/marktext#350]
### Description

Currently "Toggle Side Bar" includes the tree view. It may be better for the tree view and side bar to be in separate toggles.

The user can hide the tree view and keep the side bar buttons visible. Then click on any buttons would produce the necessary UI. (Search/Tree/Headings).

### Versions

- Mark Text: 0.12.20
- OS: macOS

**Comment by Jocs** [comment]
You can hide the `tree view` by click the button in the side bar. hope this can help you!

**Comment by dcookwebdev** [comment]
Okay I think that's nice @Jocs  thank you! I'll close this.
