### ISSUE TITLE
这个仓库现在很少维护吗？好像更新和发版本频率很慢。

### ISSUE THREAD

**Issue by liqiwenx** [marktext/marktext#3501]
### Question description
这个作品很棒啊，可好像更新的比较慢，几个月才合一次commit，版本也发的很慢，issuse数量也在累计。想请问一下是仓库是维护人员人手不够吗？还是开发人员内部在做大的更新？

**Comment by Adkimsm** [comment]
看 @Jocs 的 GitHub Profile 的 Commits 记录，貌似是最近没有更新

**Comment by Winson-Huang** [comment]
同问，是不是作者最近太忙了呀？还是说想完全放弃这个项目了？

Do the developers plan to stop maintaining this project? @Jocs @fxha

**Comment by Winson-Huang** [comment]
This is definitely a awesome project, really hope it can keep alive.

**Comment by jacobwhall** [comment]
I'm also concerned about this. @Jocs hasn't been active on GitHub for a while, and [they appear to have exclusive control of this repo](https://github.com/marktext/marktext/issues/3348#issuecomment-1185920421). I want to give the maintainers space to breathe here, but I also think the community will have to step in at some point.

I just released an unofficial build for Linux [in my fork](https://github.com/jacobwhall/marktext/releases/tag/v0.17.2-unofficial), if anyone is interested in collaborating with me, please reach out.

**Comment by Adkimsm** [comment]
[Auto reply] Hello, I have something to do at the moment, I will deal 
with it later, please leave a message if you have anything need me.

**Comment by Jocs** [comment]
My work and life have changed a lot in the past year, but now that I'm back to open source, I'm going to start maintaining marktext again, and I'll be bringing new products soon

**Comment by Adkimsm** [comment]
[Auto reply] Hello, I have something to do at the moment, I will deal 
with it later, please leave a message if you have anything need me.

**Comment by Winson-Huang** [comment]
太棒了！期待你接下来的工作！
