### ISSUE TITLE
 "autoPairQuote" should be smarter

### ISSUE THREAD

**Issue by dcookwebdev** [marktext/marktext#351]
### Description

Currently if you type something like `they're` you will get an auto-paired apostrophe and so you have `they're'`.

The `autopairquote` feature should be smarter to determine when to create a paired quote.

### Versions

- Mark Text: 0.12.20 
- OS: macOS

**Comment by Jocs** [comment]
There is a question here. When should an auto pair and when should be forbidden?

**Comment by maxgrossman** [comment]
just started using the app (super fun!)

When writing possessives like `data's` or `features'`, the autopairquote is frustrating.

This quirk wouldn't stop me from using the app (seriously, it rules), but I think a solution could be to hack the keyboard with some hotkey for the autopairquote (maybe `ctrl+quote button`).

Thoughts?
Again, thanks so much for making this!

**Comment by Jocs** [comment]
I have seen many editors do auto pair only on double quotes. So we should cancel auto pair on single quotes to avoid this weird behavior.

**Comment by stefnotch** [comment]
@Jocs Suggestion: Only auto pair if it's not preceded by a letter/number.

e.g.
`It's` <--No auto pairing, because there is a letter before the quote
`'hi'`<--Auto pairing, because there is nothing before the quote
`He is so "intelligent"` <--Auto pairing, because there is a whitespace before the quote

**Comment by Jocs** [comment]
@stefnotch It is a good idea that the single quoted auto pair is only implemented if the front is not a letter.

Can you submit a PR about this?
