### ISSUE TITLE
软件不支持中文

### ISSUE THREAD

**Issue by shuncon** [marktext/marktext#3515]
软件不支持中文

**Comment by MHYCWasTaken** [comment]
看似支持啊
![图片](https://user-images.githubusercontent.com/89076764/204121554-477651df-1867-4111-a701-5d9c752180a1.png)
你的意思是菜单没有汉化吗

**Comment by Radium-bit** [comment]
> 看似支持啊 ![图片](https://user-images.githubusercontent.com/89076764/204121554-477651df-1867-4111-a701-5d9c752180a1.png) 你的意思是菜单没有汉化吗

我想他说的是这个意思

**Comment by pifeifei** [comment]
![image](https://user-images.githubusercontent.com/45787170/209495462-de5318f6-f09c-427d-94ee-eef04370d13e.png)

没有汉化，这里的 language 一直是灰色的。

**Comment by melodyjerry** [comment]
> ![image](https://user-images.githubusercontent.com/45787170/209495462-de5318f6-f09c-427d-94ee-eef04370d13e.png)
> 
> 没有汉化，这里的 language 一直是灰色的。

同

**Comment by kingofbd** [comment]
一个国人主导开发的md软件，没有汉化，笑话 :D

**Comment by huanmin123** [comment]
66666666  没有汉化我去,搞笑呢
