### ISSUE TITLE
auto-save should be on by default

### ISSUE THREAD

**Issue by dcookwebdev** [marktext/marktext#352]
### Description

It's all in the title. 

### Versions

- Mark Text: 0.12.20
- OS: macOS

**Comment by Jocs** [comment]
I think this should be configured by the user. Users can set whether they need to be automatically saved in the configuration file.

**Comment by dcookwebdev** [comment]
@Jocs I agree they should be able to set it. Do you think a majority of users want autosave off or on?

**Comment by Jocs** [comment]
@dcookwebdev 

>Do you think a majority of users want autosave off or on?

Sorry, I can't answer this question, because I didn't do a survey, I will change autosave to default, if there is strong evidence that users prefer to save automatically

**Comment by Jocs** [comment]
I'LL close this issue, if you have any other information or detail, you can comment in this issue, or just reopen it.
