### ISSUE TITLE
bullet list marker should be all (*, -, +) not just one

### ISSUE THREAD

**Issue by dcookwebdev** [marktext/marktext#353]
### Description

Currently a user needs to set up a bullet list marker in preferences as either one of `*`, `-` or `+`. They should all be used and it's necessary to ask the user to pick between them.

### Versions

- Mark Text: 0.12.20
- OS: macOS

**Comment by Jocs** [comment]
Now you should be free to use `+`  -`  ` *`.

```markdown
* list one

- list two

+ list three
```

will be output as it is.

the setting `bulletListMarker` in preferences file just use for copy and paste from other place.

**Comment by dcookwebdev** [comment]
@Jocs  okay I see! Thank you!

Should the preference just be taken out then to avoid confusion?

**Comment by Jocs** [comment]
I think that write documents or user manual of Mark Text, it should be a better solution

**Comment by Jocs** [comment]
@dcookwebdev I'll close this issue if no more detail, If you have any question, you can reopen it.
