### ISSUE TITLE
needs customizable css for pdf export

### ISSUE THREAD

**Issue by 1dancook** [marktext/marktext#354]
### Description

It would be great if there could be customizable CSS for the PDF export. Would be ideal to have this set up so a user can select it when they export to PDF. 

### Versions

- Mark Text: 0.12.20
- OS: macOS

**Comment by Jocs** [comment]
Yes, very good advice, we also have plans to output PDF files with different themes, but we don't have time to complete the work before the 1.0 release.

**Comment by biji** [comment]
Pleae make pdf output similiar to current editor theme :D

**Comment by Jocs** [comment]
@biji This will be improved in the future.

**Comment by fxha** [comment]
Documentation for export themes coming soon.
