### ISSUE TITLE
no way to do page breaks (related to PDF export and print)

### ISSUE THREAD

**Issue by 1dancook** [marktext/marktext#355]
### Description

It would be great to include a way to have page breaks for PDF export or print. 
For the "preview" view, you could render something like:
`--------------------------page break---------------------------`

and of course in source code view you will have something like:
```
<div class="page-break"></div>
```

#### Menu item as well
Attached to this is also the necessity to include a page break option in the menu somewhere.

### Versions

- Mark Text: 0.12.20
- OS: macos

**Comment by jkrzefski** [comment]
I am having issues with page breaks in PDF exports altogether. It seems like an exports only contains the first page and cuts off the rest of the text.

**Comment by Jocs** [comment]
@jkrzefski I think this should be another issue, can you open another issue about the problem you described?

**Comment by jkrzefski** [comment]
@Jocs Sure thing. See #360

**Comment by dcookwebdev** [comment]
In relation to #360 I believe that a good way to handle exporting PDF (from what I know anyway) is to do this kind of flow:

1. convert markdown to html
2. apply css styling (what the user picked)
3. convert html to pdf
4. write to disk

I don't know what kind of libraries are available to the conversion steps but I'm sure they exist.

**Comment by fxha** [comment]
@1dancook  I think we can close this issue because you can produce a page break with `<div style="page-break-before: always;"></div>`?

- `page-break-after`
- `page-break-before`

**Comment by 1dancook** [comment]
Yes I know about this way and it’s what I do. I think it’s okay to close this however it may be good to provide users with this knowledge.

**Comment by fxha** [comment]
Yes, that's right and we still need a end user documentation.
