### ISSUE TITLE
Windows Installation produces warning by Windows Defender Smartscreen

### ISSUE THREAD

**Issue by ayoayco** [marktext/marktext#358]
### Description
Windows Installation produces warning by Windows Defender Smartscreen

### Steps to reproduce

1. Run .exe installer on Windows 10

**Expected behavior:** Installation should start

**Actual behavior:** Installation is prevented by Windows Defender

A dialog pops up with the following warning message:
> Windows protected your PC
> Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

### Versions

- Mark Text: marktext-setup-0.12.20.exe
- OS: Windows 10 Enterprise (ver. 1803, build 17134.112)

**Comment by fxha** [comment]
Thanks @ayoayco,

this is a known problem because we do not have a code signing certificate for windows. So we have to ask @Jocs whether he  was willing to buy such a certificate. I think it costs around 300-500$/€ per year. But if you don't trust us, you can build Mark Text yourself. At the moment there's nothing we can do about it.

The same applies to the macOS certificate too which will be signed before version 1.0.

**Comment by Jocs** [comment]
@fxha 

I have a question. Under the premise of no certificate, MarkText can be installed under windows system?

Under the macOs system, it is possible to continue the installation.

**Comment by fxha** [comment]
Yes, you can click on `More info` -> `run anyway`.

**Comment by Jocs** [comment]
@ayoayco At present, we do not have the conditions to purchase this certificate. After all, this is an open source project and there is no continuous source of funding, so we also hope that companies or individuals can sponsor Mark Text.

**Comment by fxha** [comment]
@ayoayco I'm closing this, sorry. There's nothing we can do at the moment. If you/others have problems with antivirus solutions, please reopen or comment on this issue. We will fix these issues and contact the manufacturer.

**Comment by ayoayco** [comment]
No problem. I just thought I should report it, not knowing it was already a known issue. Thanks for the informative responses.

Its a very good product. Cheers!
