### ISSUE TITLE
Open local markdown file when you click on it in another tab

### ISSUE THREAD

**Issue by stigbosmans** [marktext/marktext#359]
### Description

I would like to propose notebook functionality. I envision an optional sidebar that lists all subpages which are part of the notebook. A proper open-source & cross-platform, markdown based notebook editor with realtime rendering is currently missing. I think marktext could fill this gap.
If you guys think this feature fits in the vision of marktext I'd be happy to add a PR.

**Comment by Jocs** [comment]
Can you explain more detail or show some examples about this feature request?

**Comment by sg-s** [comment]
+1 

all you would need is that if you click a link to a local .md file, that file opens in the current window.

**Comment by stigbosmans** [comment]
Yes, I was thinking to add two menu items (1. Add Notebook, 2. Open Notebook) to the File menu. 
The "Add notebook" function creates a new folder on the hard disk, in which individual md files can be stored. The "Open Notebook" opens a file browse window and allows the user to select a folder which contain .md files. When either of these menu items is activated a sidebar is displayed which contains quick links to all .md files stored in the folder. Furthermore, at the top of sidebar a new .md file can be easily created by submitting the name of the file in a textbox. After submitting this, the file will be automatically added to the notebook folder and displayed in the sidebar.

**Comment by stigbosmans** [comment]
Si in short, you could see this as a wrapper around the editor which adds very basic notebook functionality.

**Comment by sg-s** [comment]
that's great, but perhaps my suggestion is even simpler -- you wouldn't need any extra UX elements, or the concept of a "notebook" -- links to other markdown files would simply open when clicked.

**Comment by Jocs** [comment]
@stigbosmans Currently Mark Text can also create or open a folder and create and edit file in a folder. Why do you still need this feature?

**Comment by fxha** [comment]
@stigbosmans @sg-s @Jocs Personally I think that we can talk about bookmarking files and/or folders aka projects. Why did you not create a folder and open the folder directly or create a symbolic link `marktext %folder_path%`? I don't understand the purpose of this - bookmarks are a better option for quick opening files/folders.

**Comment by Jocs** [comment]
In fact, there is also a planned feature, `quick open`, like bookmark. which allows you to open recently opened files, projects, and has search function. But I'm still not sure if there is such a demand?

**Comment by sg-s** [comment]
@fxha I think my suggestion is different, unless I misunderstand you. 

What I envision is having a folder with a bunch of `.md` files in it. I want to be able to manually create links to these files from one of them using a standard markdown link: `[text](link)` and when I click on that, that .mf file should open in the same window. 

If such a feature exists, it will allow you to have a de-facto local wiki up and running, with WYSIWYG editing.

**Comment by fxha** [comment]
@sg-s If I understand you right, you want to open another (editing)window/tab if you click on a link which points to a local markdown file?

@stigbosmans Is that what you mean too?

**Comment by sg-s** [comment]
@fxha no, when I click on a link to another .md file that is stored locally, I want the editor the open that file in the same window (and close the previous file)

just like clicking a link in a web browser.

**Comment by fxha** [comment]
Okay, sounds good. However I would recommend to use `Ctrl+Left Mouse Button` to open a link in the default browser or if the url/path is a local markdown file in another tab and `Ctrl+{Shift or Alt or ...}+Left Mouse Button` to close current file and open the local file in the same tab. One problem could be that the current editor don't support to close and open a file in the same tab.

**Comment by sg-s** [comment]
none of those options work for me. 

i have two files, `test.md` and `test2.md`

the contents of `test.md` are:

```
wow so [link](./test2.md)
```

I can't open `test2` by any combination of clicking I have tried. I've tried Cmd, Opt and Ctrl and in all combinations and nothing works.

**Comment by sg-s** [comment]
@fxha even opening in a new tab would be great!

**Comment by fxha** [comment]
> I can't open test2 by any combination of clicking I have tried. I've tried Cmd, Opt and Ctrl and in all combinations and nothing works.

It's not yet implemented; it was just a suggestion to use these two shortcuts.

**Comment by Jocs** [comment]
@stigbosmans @sg-s we finally use CmdOrCtrl + click to open a link or local markdown file. and this feature will be released in the next version.
