### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by telekrex** [marktext/marktext#3597]
### I want to contribute, but..

I'm seeing so many open issues and pull requests gone without review, latest release was 1 year ago. Yet there's a very expensive Patreon advertised in the readme. I really like this app and would like to contribute, but would I be wasting my time?

**Comment by SamuelMiller** [comment]
I would also like to contribute, but there seems to be little development on this project as of late.

**Comment by JiFish** [comment]
I came here to report a couple of bugs/annoyances, but since that will likely fall on deaf ears can anyone recommend a markdown editor that is still being actively developed?

**Comment by SamuelMiller** [comment]
> I came here to report a couple of bugs/annoyances, but since that will likely fall on deaf ears can anyone recommend a markdown editor that is still being actively developed?
There is Typora, but's development seems very incremental, largely just bug fixes as of late. Still more active than MarkText. However, it is closed-sourced.

**Comment by SamuelMiller** [comment]
> I came here to report a couple of bugs/annoyances, but since that will likely fall on deaf ears can anyone recommend a markdown editor that is still being actively developed?
There is Typora, but's development seems very incremental, largely just bug fixes as of late. Still more active than MarkText. However, it is closed-sourced.

**Comment by Teloshav** [comment]
> I came here to report a couple of bugs/annoyances, but since that will likely fall on deaf ears can anyone recommend a markdown editor that is still being actively developed?

@JiFish Is there a chance you could briefly go over the bugs you've encountered?

I've been having a look around and I'm going to see what kind of things I could do to at least just get rid of as many bugs as I can.

I have no guarantees, but I would like to give it my best attempt.

- Teloshav

**Comment by jacobwhall** [comment]
I've been [maintaining a fork of MarkText](https://github.com/jacobwhall/marktext/releases), with a bunch of PRs from this repository merged in. Please reach out if you'd be interested in helping with it.

**Comment by Jocs** [comment]
My work and life have changed a lot in the past year, but now that I'm back to open source, I'm starting to maintain marktext again

**Comment by lxorb** [comment]
Really appreciate the time and effort you've put into marktext, but considering that there are 672 open issues right now, I get the feeling this repo is still abandoned (3 years after this issue was originally opened). 
Have hence been developing an alternative, see [github.com/lxorb/nibeditor](https://github.com/lxorb/nibeditor).
