### ISSUE TITLE
如何退出无序列表？How to get out of an unordered list?

### ISSUE THREAD

**Issue by timerring** [marktext/marktext#3598]
### Question description

中文版本：

marktext中是否有像Typora中 `ctrl + [` 的方式切换出列表状态？例如在无序列表中回车的话会继续创建下一个列表项，目前仅发现三种方式：
+ 连续两次空格
+ 切换源码模式自己减少缩进
+ 或者在左侧的列表图标中选择New Paragraph。不知道它旁边的写的是什么快捷键？ 内容是`⬆^N`。

以上两种方式非常不方便，是否存在快捷键的方式退出无序列表呢？

---
English Version：

Is there a way in marktext like `ctrl + [` in Typora to switch out of the list state? For example, if you press Enter in the unordered list, it will continue to create the next list item. Currently, only three methods have been found:
+ Toggle source mode to reduce indentation yourself
+ two spaces in a row
+ Or select New Paragraph from the list icon on the left. I don't know what shortcut key is written next to it? The content is `⬆^N`.

The above two methods are very inconvenient. Is there a shortcut key to exit the unordered list?

**Comment by timerring** [comment]
![image](https://user-images.githubusercontent.com/89397553/224883561-24f924ef-4371-4417-bcd2-9b739b215bd3.png)
它是什么快捷键呢？ What shortcut key is it?

**Comment by sakana-fish-owo** [comment]
`⬆^N`= shift + ctrl +N
或者在下一行多按一次回车键
![image](https://i.imgur.com/IHaaXof.gif)

**Comment by timerring** [comment]
Thanks a lot :)
