### ISSUE TITLE
Add MathJax support

### ISSUE THREAD

**Issue by dopsi** [marktext/marktext#36]
### Description

It would be nice to have MathJax integration (to allow to display mathematics in MarkDown),
in the same way [`pandoc`](https://pandoc.org/) does.

**Expected behavior:** Allow editing the formula and render it once the focus leaves it (I'm not really sure about the terminology).

**Link to a library:** I found [mathjax-electron](https://github.com/nteract/mathjax-electron) which seems to allow to do what I suggest.

If you give me some guidance, I could do a pull request, but I don't really know where to begin.

**Comment by Jocs** [comment]
Support inline and block Math is already in the [TODOLIST](https://github.com/marktext/marktext/blob/master/.github/TODOLIST.md), I really hope someone can help me with these new features in TODO LIST, Yeah, before start we need to discuss it，This issue will be the place to discuss this new feature.

**Comment by Jocs** [comment]
@dopsi I create a PR #89 , Can you help to review these codes?

**Comment by fxha** [comment]
@Jocs Export to pdf and html does not work.

**Comment by Jocs** [comment]
@fxha OK, I'll check it. 👍

**Comment by Jocs** [comment]
@fxha The math can not be seen when export PDF and styled HTML.

**Comment by RoyiAvital** [comment]
I see there is a Math support based on KaTeX.
Any chance having an option to use MathJaX as well?

KaTeX lacks many features which are enabled in MathJaX.

Thank You.

**Comment by Jocs** [comment]
@RoyiAvital Sorry, we don't currently support MathJaX. What are the requirements, KaTeX can't satisfy you?

**Comment by RoyiAvital** [comment]
@Jocs , KaTeX doesn't support any environment (For instance `align`).

**Comment by Jocs** [comment]
@RoyiAvital I need to do some research on KaTeX and MathJax before I can better answer your question. If you really want some feature only MathJax support, feature request issue is welcomed.

**Comment by RoyiAvital** [comment]
@Jocs, Well this issues is exactly that - Feature request for MathJax support.
All needed it to open it so it might be solved.

If someone wants to write serious Math in MarkDown it must use MathJax.

**Comment by Masacroso** [comment]
It will be awesome to have mathjax support, as already said katex lacks many features what makes useless for many scenarios.
