### ISSUE TITLE
Easier Sidebar Opening

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#361]
### Description
**Feature Request:**
Make it easier to open the side bar. Currently, the only way to open it is to use the menu:
![image](https://user-images.githubusercontent.com/10220080/41544894-29f6c822-731a-11e8-88c8-b63b75777e8f.png)

**Possible suggestions:**
- Move the mouse to the left edge of the screen &rarr; sidebar opens
- Keyboard shortcut
- Extra button. For example:
![image](https://user-images.githubusercontent.com/10220080/41545120-b95c47a8-731a-11e8-8088-7be09f018fc5.png)

### Versions

- Mark Text: v 0.12.20
- OS: Windows 10

**Comment by Jocs** [comment]
I think keyboard shortcut is a better solution, because this is not intrusive to the interface. Do you have any idea about the shortcut?
