### ISSUE TITLE
很久没更新了？你们这些人还挺活跃

### ISSUE THREAD

**Issue by mgl-pub** [marktext/marktext#3611]
### Question description

不在维护了吗？ 很好的一个开源项目 可惜了呢 还有那个域名 不可用了吗？

**Comment by yanjingfan** [comment]
> ### Question description
> 不在维护了吗？ 很好的一个开源项目 可惜了呢 还有那个域名 不可用了吗？

marktext小bug很多，维护起来费时费力，还不讨好，哈哈，感觉花几十块买个typora也不是不行

**Comment by swordnine** [comment]
不支持中文挺可惜的

**Comment by erica-bing** [comment]
> 不支持中文挺可惜的

有中文的呢，github已经有中文版本了，只是官方不支持中文。

**Comment by mgl-pub** [comment]
> > ### Question description
> > 不在维护了吗？ 很好的一个开源项目 可惜了呢 还有那个域名 不可用了吗？
> 
> marktext小bug很多，维护起来费时费力，还不讨好，哈哈，感觉花几十块买个typora也不是不行

买了是买了 没多少钱 但是不开源 用着心里不踏实  所以也一直关注marktext

**Comment by itdaling** [comment]
你们还在用marktext吗？我是菜鸟，我不知道我应不应该用？

**Comment by Gearace** [comment]
> 你们还在用marktext吗？我是菜鸟，我不知道我应不应该用？

别用，marktext最大的毛病就是打字快了或者粘贴+打字，然后ctrl+z，你本意可能只是后退一步，结果你刚才的所有操作都没了！！！个人感觉是martktext是把文件内容先读入内存，在内存上编辑而不是直接编辑内容。这是typora最大的区别，你可以同时用这两个软件再加上vscode打开同一个文档，就能明显的感觉到typora和vscode的编辑是同步的，而marktext会提示你文档已更改。

**Comment by shisaru292** [comment]
![image](https://github.com/marktext/marktext/assets/87224749/a3eafa61-2571-4d01-a0ea-477052857b98)
Marktext is an excellent piece of software. I think the author of this open source project is working on a mobile version. Marktext is great but the commercialization is a big problem for an  individual developer. Good luck. 🍀
BTW, I think the appearance of Marktext is better than most obsidian themes.

**Comment by mgl-pub** [comment]
> 你们还在用marktext吗？我是菜鸟，我不知道我应不应该用？

目前typora为主，这个比较稳定，marktext就是唯一一个优点就是免费开源😂

**Comment by Aurorxa** [comment]
好像不更新了

**Comment by zhouxinghong** [comment]
目前为止所有体验过的最好用的，没有之一。

**Comment by AdySnowflake** [comment]
> 目前为止所有体验过的最好用的，没有之一。
> 
> 另外，提醒各位一下最好别用所谓的非官方中文版，因为你不知道别人特意另起炉灶搞个中文版的目的是什么（这年头有些人为了获取别人的个人隐私信息和数据简直不择手段、无所不用其极...）如果此人真的有开源精神，为何不直接在本项目下给官方作者提交中文翻译补丁呢？而是要特意山寨官方作者的项目弄个什么中文版。。。

幽默
首先，marktext作者虽然是国人，但是对待中文（这里特指简体中文，不包括台湾繁体）态度很消极https://github.com/marktext/marktext/issues/138#issuecomment-1430749085 ，这里猜测可能和他的政治倾向有关，具体可以看他github仓库有关国内政治的内容。
第二点，marktext通过MIT协议进行开源，目前fork出去的两个简中分支都是在此基础上修改并分发的代码，这并不违反MIT开源协议。如果你觉得不安全，可以去审查代码或者自己构建，构建方法和源仓库是一致的。不是很懂你说的获取别人隐私、开源精神、山寨官方是什么意思。
