### ISSUE TITLE
How to add subscript in math block 

### ISSUE THREAD

**Issue by CaffineAddic** [marktext/marktext#3613]
### Question description

I want to create F and subscript theta

How can I do this <sub> tag doesn't work in $$ block 

Also is there a easier way like ^ for superscript like ~"word"~ maybe

**Comment by CarrotDLaw** [comment]
MarkText uses KaTeX, which supports a subset of LaTeX, to render maths blcoks. You may use `_` for subscript, like `F_\theta`.

For more information about KaTeX functions, please view [https://katex.org/docs/supported.html](https://katex.org/docs/supported.html).

**Comment by CaffineAddic** [comment]
Thanks a lot for everything 
how about subscript of a subscript 
like F sub theta sub i

**Comment by CaffineAddic** [comment]
Thanks I got it I can use F _{theta_i}
