### ISSUE TITLE
When exporting to HTML and PDF, the italicized content in the original text cannot be correctly recognized.

### ISSUE THREAD

**Issue by sundays0** [marktext/marktext#3615]
When exporting to HTML and PDF, the italicized content in the original text cannot be correctly recognized.

The following image shows the effect of exporting italic content to HTML, which is clearly incorrect:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/41354065/232649307-5067bdb8-c41a-42c5-8fde-d9316caa5016.png">

Versions

- MarkText version: v0.17.1
- Operating system: macOS 13.3.1

**Comment by CarrotDLaw** [comment]
What is the source code of this line?

**Comment by sundays0** [comment]
Source code is:

[粘贴的图形-1.png]

2023年4月18日 18:05，CarrotDLaw ***@***.***> 写道：



What is the source code of this line?

**Comment by CarrotDLaw** [comment]
Hmm I don't think I can view the image of the source code.

**Comment by dbkand** [comment]
Oh, sorry, the source code is here:
_<font color="Grey">Published on 2023-04-17</font>_

**Comment by sundays0** [comment]
Oh, sorry, the source code is here:

`_<font color="Grey">Published on 2023-04-17</font>_`

**Comment by CarrotDLaw** [comment]
Maybe it's due to the HTML tags inside. 

`<em><font color="Grey">Published on 2023-04-17</font></em>` works fine.

**Comment by dbkand** [comment]
Okay, thanks for your advice.

**Comment by sundays0** [comment]
Okay, thanks for your advice.
