### ISSUE TITLE
Remove expired "marktext.app" domain from GitHub repo metadata

### ISSUE THREAD

**Issue by paulwwisl** [marktext/marktext#3620]
Remove expired "marktext.app" domain from GitHub repo metadata

It is still there 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/129515995/236004736-3a109d8e-187d-47ba-b18e-c55e8a28d15c.png">

See also [Remove expired "marktext.app" domain (](https://github.com/marktext/marktext/commit/aed36dbf320b17bdd0e44398d5cfe45a4d357940)
and https://github.com/marktext/website/issues/75

**Comment by Jocs** [comment]
The new official website is already available, https://www.marktext.cc/
