### ISSUE TITLE
Is this project still being worked on? 

### ISSUE THREAD

**Issue by Pomax** [marktext/marktext#3624]
### Question description

The last release was a year ago, and the code has seemingly not been touched since. Is this project still alive? If not, can it be archived so that folks know to keep looking for a new markdown editor?

**Comment by delinx** [comment]
I don't think its active anymore sadly

**Comment by Muttsuri** [comment]
They should at least mark it as such.
Either something on README or just lock the repo.
Sadly it also seems that uses have split into each one their own, for (around 3k forks).
It would be cool if someone could pick up the project. Part of me wonders about it but I ain't sure I'm good enough (then again, slow is better than stoped I guess...)

**Comment by avatar1024** [comment]
I agree it's a shame that's it's been abandoned cause it's a great piece of software. I haven't found a better Free Software real time preview markdown editor

**Comment by Muttsuri** [comment]
I've been looking, and it seems this depends on an actually maintained project called [muya](https://github.com/marktext/muya).
Seems to be like an attempt to move MarkText's features to a browser based interface, which can be clearly be adapted into this electron app.
I don't know why the move to the page states `"Our team believes that Muya should not be limited to desktop applications."` which tbh feels like a flimsy excuse to drop this when the web markdown editor is a way more busy market while as you said I have yet to find a better one, a focus on this one would in theory lead to capturing a more starved market I think.

I did look at the code to see if I could find where does the application check if the image is being pasted from clipboard, so I could find where to do the base64 conversion (something I would love to have, but I have to use a side python script to convert the image to a data:base64 string) but I had a really hard time wrapping my head around the code. I wish I was better and that I could offer up to start maintaining, but I know my skills are not yet there :(

**Comment by Pomax** [comment]
Stay on target - this issue isn't really for venting, it's just to ask the maintainer whether they are still committed to this repo. If you use different editors, or think you can create your own, then that's not for discussing here. No need to disparage the people who put in _a lot_ of work making this project, even if that work stopped. People have lives, and priorities shift =)

**Comment by Muttsuri** [comment]
I apologize if it sounded like that, it was not at all my intent. I'm mostly saying that unfortunately I don't have the skills to maintain this project, even in collaboration with the creators.
Perhaps I meant more to propose some form to reactivate activity in this project by having someone help manage this repo, exactly for that purpose, since the authors may not have the capability right now to actively check in to the project.

**Comment by stephanlamoureux** [comment]
this is the best looking markdown editor on Linux...crazy that it seems to be dead.

**Comment by jacobwhall** [comment]
I've been merging a bunch of outstanding PRs on this repository into [my fork](https://github.com/jacobwhall/marktext), and [releasing builds for Linux](https://github.com/jacobwhall/marktext/releases). It ain't much but might help some folks keep using MarkText for a while, and maybe we could start some longer-term maintenance work. Please reach out if you'd like to help.

**Comment by WilczynskiT** [comment]
Hello @jacobwhall @stephanlamoureux @Muttsuri @Pomax @avatar1024 @delinx 

I have taken the initiative to reactivate the project under a new repository. You can find the reactivated project here: https://github.com/wilcz-com/wMarkText

Your assistance will be greatly appreciated =D

Best regards,
WilczynskiT

**Comment by Muttsuri** [comment]
@WilczynskiT
@jacobwhall seems to have started the same kind of initiative, would it not be better to join efforts?

**Comment by WilczynskiT** [comment]
@Muttsuri Yes, certainly, you're right. I didn't notice that @jacobwhall  initiated the effort - it's better to unite forces than to divide them.

**Comment by jacobwhall** [comment]
@WilczynskiT @Muttsuri please get in touch if you'd like to help strategize our next move. @axelrindle has been making good progress reworking the build system and updating some of the dependencies.

**Comment by Pomax** [comment]
As much as I appreciate people wanting to fork this project: this issue is not the place for that discussion. This was a clear question for the owners of _this_ repo, and every comment about forking, or how much they wish it were still alive, is irrelevant to that question.

I'm closing this issue, because no one who just wants to know whether they should start using this benefits from _yet another_ "let's discuss forking and doing new work" thread when they thought they were looking at whether or not the project's still maintained.
