### ISSUE TITLE
字数多了之后文字输入卡顿

### ISSUE THREAD

**Issue by wwb521** [marktext/marktext#3626]
After increasing the number of words, the text input becomes sluggish. I hope to optimize it, but I don't want the text to be recorded in sections
字数多了之后，文字输入变得卡顿，希望优化一下，我不希望让文字分篇记录

**Comment by A-caibird** [comment]
很多软件都是这样的typora也是，你该分页就分页了

**Comment by ilaziness** [comment]
@rookie-lian 这个项目是死了吗？很久没更新了。

**Comment by wwb521** [comment]
> 很多软件都是这样的typora也是，你该分页就分页了

typora没遇到卡顿，目前显示有7万字，依旧流畅，marktext不行，打字有延迟

**Comment by wwb521** [comment]
> @rookie-lian 这个项目是死了吗？很久没更新了。

可能是死了，bug多，维护跟不上，日积月累，作者也可能不知道先修复哪个了，索性就摆烂了

**Comment by WilczynskiT** [comment]
Dear @wwb521  ,

I hope this message finds you well. I wanted to inform you that the MarkText project has been abandoned. However, I have taken the initiative to reactivate the project under a new repository. You can find the reactivated project here: https://github.com/wilcz-com/wMarkText

I kindly request you to kindly transfer this issue to the new repository and continue the discussion and development efforts there. Your continued support and contributions would be greatly appreciated.

Thank you for your understanding and cooperation.

Best regards,
WilczynskiT

**Comment by lianglllll** [comment]
目前20w字卡的不行

**Comment by Deemo119** [comment]
1w字就卡了
