### ISSUE TITLE
Default export theme setting

### ISSUE THREAD

**Issue by mben42** [marktext/marktext#3632]
### Describe your feature request

Add a setting to modify default export theme.

### What problem does this feature solve? [optional]

Currently we have to modify theme at each startup, it applies only while MarkText stays open.

**Comment by WilczynskiT** [comment]
Dear @mben42  ,

I hope this message finds you well. I wanted to inform you that the MarkText project has been abandoned. However, I have taken the initiative to reactivate the project under a new repository. You can find the reactivated project here: https://github.com/wilcz-com/wMarkText

I kindly request you to kindly transfer this issue to the new repository and continue the discussion and development efforts there. Your continued support and contributions would be greatly appreciated.

Thank you for your understanding and cooperation.

Best regards,
WilczynskiT
