### ISSUE TITLE
如何在build时将release上传到 github release

### ISSUE THREAD

**Issue by slcnx** [marktext/marktext#3635]
### Question description

我构建时出现这个报错， skipped publishing  file=marktext-x86_64.rpm reason=existing type not compatible with publishing type tag=v0.17.1 version=0.17.1 existingType=release publishingType=draft
![image](https://github.com/marktext/marktext/assets/35824750/8bec8dbb-1eeb-4977-9c82-83163f2e5a0b)

**Comment by WilczynskiT** [comment]
Dear @slcnx  ,

I hope this message finds you well. I wanted to inform you that the MarkText project has been abandoned. However, I have taken the initiative to reactivate the project under a new repository. You can find the reactivated project here: https://github.com/wilcz-com/wMarkText

I kindly request you to kindly transfer this issue to the new repository and continue the discussion and development efforts there. Your continued support and contributions would be greatly appreciated.

Thank you for your understanding and cooperation.

Best regards,
WilczynskiT

**Comment by tumine** [comment]
您好！我已收到您发送的邮件，稍后我会查看邮件，如果有进一步需求，我会与您再联系。谢谢！
