### ISSUE TITLE
Dark or Light theme according to system-wide theme as default theme

### ISSUE THREAD

**Issue by D3vil0p3r** [marktext/marktext#3649]
### Describe your feature request

Currently MarkText runs the first time with CadmiumLight theme, also for those systems with dark GTK theme. Could you please implement a logic to set, at first run, a dark or light theme according to the system-wide theme?

### What problem does this feature solve? [optional]

To not have a super white window on a system-wide dark environment.

**Comment by WilczynskiT** [comment]
Dear @D3vil0p3r  ,

I hope this message finds you well. I wanted to inform you that the MarkText project has been abandoned. However, I have taken the initiative to reactivate the project under a new repository. You can find the reactivated project here: https://github.com/wilcz-com/wMarkText

I kindly request you to kindly transfer this issue to the new repository and continue the discussion and development efforts there. Your continued support and contributions would be greatly appreciated.

Thank you for your understanding and cooperation.

Best regards,
WilczynskiT

I think that we should add this feature

**Comment by D3vil0p3r** [comment]
Opened at https://github.com/wilcz-com/wMarkText/issues/5

**Comment by berot3** [comment]
> Opened at https://github.com/wilcz-com/wMarkText/issues/5

Did the link change?

**Comment by WilczynskiT** [comment]
> > Opened at https://github.com/wilcz-com/wMarkText/issues/5
> 
> Did the link change?

Yes, I was not first, here is the actual project now: https://github.com/jacobwhall/marktext
