### ISSUE TITLE
Typo in sidebar context menu item

### ISSUE THREAD

**Issue by zpalexander** [marktext/marktext#365]
### Description

In the sidebar folder browser, the context menu that's opened by right clicking on either a directory or file in the sidebar has a typo. The menu item for moving a directory or file to the trash is labeled "Move to Trach", when it should be labeled "Move to Trash".

### Steps to reproduce

1. Set the sidebar to visible if it isn't already
2. Open a directory of files with File > Open Project
3. Right click on any of the directories or files shown in the sidebar within the directory you just opened
4. A context menu will appear with an item "Move to Trach"

**Expected behavior:** The label reads "Move to Trash"

**Actual behavior:** The label reads "Move to Trach"

**Link to an example:** String is hardcoded here - https://github.com/marktext/marktext/blob/dc79014147f641ba454e820d133fb8314387a497/src/renderer/contextMenu/sideBar/menuItems.js#L56

### Versions

- Mark Text: v0.12.20
- OS: MacOS

**Comment by zpalexander** [comment]
I'll follow up shortly with a PR

**Comment by fxha** [comment]
@zpalexander Thanks for your PR!
