### ISSUE TITLE
Project's web link does not work

### ISSUE THREAD

**Issue by kataras** [marktext/marktext#3655]
The described: https://marktext.app/ found in the repository:

![image](https://github.com/marktext/marktext/assets/22900943/ea49ad0f-3faa-4a36-830c-e958b4924d87)

Does **NOT** navigate to the MarkText website:

![image](https://github.com/marktext/marktext/assets/22900943/9f0708b5-26e9-490c-9123-e881b3f87a30)

**Comment by Jocs** [comment]
The new official website is already available, https://www.marktext.cc/
