### ISSUE TITLE
[Feature request] Image resize in markdown document resizes image, and retains markdown image format.

### ISSUE THREAD

**Issue by ghost** [marktext/marktext#3658]
### Describe your feature request

If a user resizes an image in a markdown document, the markdown is changed to a HTML img element and the width/height attributes are set. It would useful to have the image resized and retain the markdown for an image ![image.jpg](image.jpg) rather than <img src="image.jpg" /> Ideally this could be a setting in the preferences, so users can choose which option they prefer for a document.

### What problem does this feature solve? [optional]

1. Having to manually resize images
2. changing the markdown format to HTML

**Comment by Jocs** [comment]
The markdown syntax actually does not support image resizing, so the img tag is used
