### ISSUE TITLE
Did maintainer died?

### ISSUE THREAD

**Issue by kem-a** [marktext/marktext#3668]
There are 43 PR pending. What is the status of this project? Would be great if someone with access could edit first page and update status.

**Comment by julianschelb** [comment]
Not the maintainer, definitely hoping he's all good. Regardless, You could've phrased that a tad differently, don't you think?

**Comment by kem-a** [comment]
I could, but my intention was to make a more screaming sarcastic title to draw attention from somebody who is actually involved with the project.

**Comment by svenboulanger** [comment]
MarkText is likely close to being left as-is by the maintainers due to lack of time since 2020. You can read about it in the pinned issue [here](https://github.com/marktext/marktext/issues/1290).
