### ISSUE TITLE
'<' char will break the file on next open

### ISSUE THREAD

**Issue by Ldoppea** [marktext/marktext#37]
### Description

Double bug in one here : 
- When you open a file containing a `<` in a code block followed by a-Z char, All the text will be deleted after the `<` occurrence till the end of line. Then the file is automatically saved and so you lose the line content forever.

### Steps to reproduce

1. create a file with the following
```
`if ( itemCount < s ) // some comment ` : followed by a space is good

`if ( itemCount <s ) // some comment ` : followed by a char from alphabet will truncate the line
```
2. open this file using Marktext
3. second line is truncated
4. file is saved with truncated altered content

**Expected behavior:** [What you expected to happen]
- Marktext should correctly handle `<`
- Marktext shouldn't save the file directly after `open` command but only on user input (ctrl-s or autosave when typing)

**Actual behavior:** [What actually happened]
- File is altered

### Versions

- Mark Text: 0.6.14
- OS: Windows 10

**Comment by Ldoppea** [comment]
Also the following file will be opened empty : 

```
`if ( itemCount < s ) // some comment ` : followed by a space is good

`if ( itemCount <s ) // some comment ` : followed by a char from alphabet will truncate the line

`if ( itemCount <3 ) // some comment ` : this will break the file
```

**Comment by Jocs** [comment]
Sorry, I can not re-play this bug in my Mac, Can you explain it more detail or only occur on windows system?

**Comment by Ldoppea** [comment]
Here are a few screenshots : 
- Step1 : this is the file created from VisualStudio code (or whatever text editor)
![step1](https://user-images.githubusercontent.com/1884255/37610740-b2df1e4e-2ba0-11e8-967b-974929eeba6d.PNG)
- Step2 : this is the file content when opened in Marktext
![step2](https://user-images.githubusercontent.com/1884255/37610753-bbc3bc4a-2ba0-11e8-966f-cb3e1e81dc73.PNG)

- Step3 : this is the file content when I open it again in VisualStudio code (I did not saved it in Marktext)
![step3](https://user-images.githubusercontent.com/1884255/37610763-c3084f98-2ba0-11e8-8123-d9b1eb84c13b.PNG)

And regarding my first command, same thing, but all the file is cleared.

I'll try this on my mac this evening to check if it is specific to Windows or not.

**Comment by Jocs** [comment]
@Ldoppea 
Wait for you to verify， It's 1:00 in the morning, I need to go sleep. bye!

**Comment by Ldoppea** [comment]
Just tried on OSX Sierra and I was able to reproduce the bug.

**Comment by Jocs** [comment]
@Ldoppea I reproduce it, [parse5](https://github.com/inikulin/parse5) treat `<s` in `if (itemCount <s)` as `<s>` element. So some error occur. I'll open an issue in parse5. thank you!

**Comment by Jocs** [comment]
😿 My fault, I forget escape the raw markdown when I parse it to HTML, It will be fixed.

![](https://i.loli.net/2018/03/20/5ab0d697ee582.jpg)
