### ISSUE TITLE
Strong+Emphasis `***my text***` doesn't work

### ISSUE THREAD

**Issue by hyde1** [marktext/marktext#370]
### Description

[Description of the bug or feature]

Strong + Emphasis doesn't seems to work

### Steps to reproduce

Insert this code:
````
***Test***
````

**Expected behavior:** [What you expected to happen]

Should render strong+emphasis like that:

***Test***

**Actual behavior:** [What actually happened]

Doesn't render neither strong nor emphasis

### Versions

- Mark Text: v 0.12.20
- OS: macOS 10.13.4

**Comment by Jocs** [comment]
Thanks for reporting this issue, PR is also welcomed?

**Comment by Jocs** [comment]
@hyde1 now you can write like this to strong and emphasis some text.

```md
**_TEXT_** other text
```
