### ISSUE TITLE
Pasting text when other text is selected appends instead of replaces it

### ISSUE THREAD

**Issue by jkrzefski** [marktext/marktext#371]
### Description

When a text is in the clipboard and I select some text in my document and then paste the text from my clipboard, the selected text is not replaced by the pasted text but instead the pasted text gets appended to the selected text. It does not matter if I use shortcuts (CMD + V) or the context menu or the menu bar. The behavior is consistent throughout all of them. I made a simple example for this:

### Steps to reproduce

1. Get the word `bar` into your clipboard.
2. Open a new document.
3. Write the word `foo` and select it.
4. Paste the content of your clipboard into the document while `foo` is still selected.

**Expected behavior:** The text present in the document should be `bar`.

**Actual behavior:** The text present in the document is actually `foobar`.

### Versions

- Mark Text: 0.12.20
- OS: macOS 10.13.4

**Comment by jkrzefski** [comment]
I cannot make a gif right now, maybe later today. But I did a bit more testing and found some interesting behavior:

The described issue only occurs when I select the text via the keyboard shortcut `CMD + ←` (and therefore select the text from my position to the beginning of the line) **or** by using `CMD + A` to select the entire document. So To make my example from above more specific:

1. Get the word `bar` in your clipboard.
2. Open a new document.
3. Write the word `foo` and select it **by pressing either `CMD + ←` or `CMD + A`**.
4. Paste the content of your clipboard into the document while `foo` is still selected.

I hope this helps with this issue.

**Comment by fxha** [comment]
@Jocs @jkrzefski I can also not reproduce the issue with your description on Linux. Neither with `Ctrl+A` nor manual selection.

**Comment by jkrzefski** [comment]
@Jocs @fxha I made this quick gif. While recording it, I noticed something else: The paste completely ignores the selection and pastes into the last position of the text cursor.

![marktext](https://user-images.githubusercontent.com/11394739/41606541-2e96d5fa-73e4-11e8-91cc-8353b1727020.gif)

**Comment by Jocs** [comment]
@jkrzefski thanks, According to the description in the gif, I finally reproduced this bug. This is indeed a strange bug. We will fix it as soon as possible, and hope you can help find the reasons?

**Comment by jkrzefski** [comment]
I will definitely do more research for this issue and in case I find something interesting, I will let you guys know. But I don't think that I can help with the code. I would like to dive a little deeper into this project and actually contribute something, but my time management is quite terrible, so I make no promises there.

**Comment by Jocs** [comment]
@jkrzefski It does not matter, but still looking forward to seeing you contribute to mark text
