### ISSUE TITLE
Mac 14.1.1 (23B81) 无法使用该程序

### ISSUE THREAD

**Issue by Qicloud-W** [marktext/marktext#3713]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. 终端执行brew install --cask mark-text 安装成功 无法打开
![image](https://github.com/marktext/marktext/assets/50508002/35efb205-bc13-4ea2-b575-96ceea141464)

2. release 下载安装 安装成功 无法打开
![image](https://github.com/marktext/marktext/assets/50508002/35efb205-bc13-4ea2-b575-96ceea141464)
5. 暂未尝试自己构建

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- MarkText version:
- Operating system:

**Comment by 1one2two** [comment]
@Qicloud-W `xattr -cr /Applications/MarkText.app`

**Comment by suredream** [comment]
@1one2two many thanks!

**Comment by shuiRong** [comment]
if you see
`option -r not recognized`
use below instead.
`xattr -c /Applications/MarkText.app`
