### ISSUE TITLE
您有打算在未来支持像vim一样的操作方式吗?

### ISSUE THREAD

**Issue by WellerQu** [marktext/marktext#372]
### Description

这是一个feature, 期望您能使marktext支持vim的键位操作以及vim的几种常用模式, 比如hjkl, normal, insert, command等

[Description of the bug or feature]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text:
- OS: MacOS

**Comment by Jocs** [comment]
暂时还没有这样的打算，一个重要的原因，我自己对 vim 不是太熟悉。

另一方面，支持 vim 的键位操作，有什么优势吗？

**Comment by WellerQu** [comment]
支持vim的操作, 我个人认为可以有效提高编辑效率. 如果以按键次数作为评估标准的话.

**Comment by saivan** [comment]
I translated this to try to understand it, but I also agree that vim support would be pretty awesome! Even if its just basic support.

**Comment by Jocs** [comment]
@saivan I changed my mind after I used HHBK, Maybe I will support vim later.

**Comment by forgethub** [comment]
期待vim功能，应该有很多vim控和狂热爱好者

**Comment by forgethub** [comment]
i look forward to support vim

**Comment by PXNPXN** [comment]
+1

**Comment by delusiondreamer** [comment]
+1
