### ISSUE TITLE
Support setting custom font

### ISSUE THREAD

**Issue by nsrosenqvist** [marktext/marktext#373]
I find the default code view font quite distracting and the font option in the menu only allows me to set color, size and line-height. Would you consider implementing an option to set font for each view?

**Comment by fxha** [comment]
@nsrosenqvist I think this is a good suggestion. You mean the code block font, right?

```
code block
```

**Comment by fxha** [comment]
@nsrosenqvist As @Jocs already mentioned, `editorFontFamily` can control the preview and source code font. The default font is Open Sans. You can find the detailed settings in

- macOS: `Mark Text` -> `User preferences` or
- else: `File` -> `Preferences`

with the latest version(s). Hope this helps.

**Comment by nsrosenqvist** [comment]
I didn't see an option there for the source code view and surely you can't set both with the same property? Because you wouldn't want the same for the two, one should be monospaced and the other not. Or is it called something other than editorFontFamily?
