### ISSUE TITLE
会修改原有的文本内容。

### ISSUE THREAD

**Issue by N94P** [marktext/marktext#377]
会修改原文本内容！！！！！

HEXO 文章标题部分格式为：
```
---
title: 标题
date: 2018-06-20
tags: 标签
---
```

marktext打开会，会把最后一行识别为标题并且去掉末尾标签，改为

```
---
title: 标题
date: 2018-06-20
## tags: 标签
```
好像只会修改最后一行。

**Comment by N94P** [comment]
我不确定这是个问题还是定位为WYSIWYG编辑器的feature，但是就目前来说，编辑HEXO的文章时，确实影响到我使用了…

**Comment by Jocs** [comment]
@N94P 能把你完整的 markdown 文件，或者会出 bug 的文件发我邮箱吗？ransixi@gmail.com

**Comment by Jocs** [comment]
@N94P 邮件已经收到，很用心的视频，但是我打开没什么问题，请问下你 Mark Text 的版本，以及操作系统版本？

**Comment by N94P** [comment]
mac OS 10.13.5 (17F77)

中文 readme 中的marktext-0.9.25版本

我试一下0.12.25

**Comment by Jocs** [comment]
version 0.9.25 估计对 front-matter 还不支持，请使用 0.12.25

**Comment by Jocs** [comment]
@N94P 有时间的话，可以提交一个 PR，帮忙更新下 中文 readme。thanks
