### ISSUE TITLE
列表操作错乱

### ISSUE THREAD

**Issue by minosss** [marktext/marktext#380]
### Description

在列表编辑的时候很有问题，光标会有点乱跳，代码模式没事。
这样错误几次后，按删除光标会越让越上一行

### Steps to reproduce

1. 输入一个列表几行，有序无序都行

```
1. a
2. b
3. c
```

2. 到最后一行回车 `c`

```
1. a
2. b
3. c
4.
```

3. 按删除会把前面的内容也顶掉

```
1. a
2. bc
```

### Versions

- Mark Text: v0.12.25
- OS: MacOS 10.13.5

**Comment by Jocs** [comment]
>按删除会把前面的内容也顶掉

到这一步我没法复现，`按删除` 具体是指哪一个键？`backspace` or `fn + backspace` ?

**Comment by Jocs** [comment]
@minosss 具体重现步骤是怎样的：

比如输入文本内容是什么？
光标在哪？
怎么操作？
出现什么问题？

**Comment by minosss** [comment]
内容是什么都行，重要是用菜单的功能换成列表

1. 输入a `shift+enter`
2. 输入b  `shift+enter`
3. 点击 Paragraph -> Order List ，a和b会生成列表
4. 单击列表就会格式就会错

![jietu20180620-191352](https://user-images.githubusercontent.com/1515069/41655061-268f6b44-74be-11e8-9a84-6cb46e30e8ee.gif)

**Comment by Jocs** [comment]
非常感谢，我已经能够重现这个 bug 了。我们会尽快修复
