### ISSUE TITLE
有打算支持复制上传图片么？

### ISSUE THREAD

**Issue by asdufocdma** [marktext/marktext#382]
有打算支持剪切板复制上传图片么？虽然提供了上传图片，但是直接复制粘贴感觉更cool~

**Comment by Jocs** [comment]
具体怎么操作呢？有详细的描述步骤吗？

**Comment by asdufocdma** [comment]
在编辑文档过程需要插入图片时，使用微信QQ或者系统自带的截图工具截取图片，在文档中粘贴复制的图片，这时自动上传图片，然后生成对应的warkdown语句，将图片显示出来。

**Comment by Jocs** [comment]
@asdufocdma 在之后，我们会提供插件 API，插件开发者可以开发插件来实现这个功能。应该是和 #97 重复了。
