### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by NourEddineX** [marktext/marktext#384]
### Description
inline HTML would be great !!
something like that
  
![](https://i.imgur.com/FkxRrsv.png)

_screenshot from [marker](https://github.com/fabiocolacio/Marker)_

### Versions

- Mark Text: 0.12.25
- OS: linux

**Comment by Jocs** [comment]
Sorry,  it seems that [GFM](https://github.github.com/gfm/) does not support `style` attribute in tags, we will not support recently.
