### ISSUE TITLE
Expanding Accessibility Through Localization Support

### ISSUE THREAD

**Issue by riceshowerX** [marktext/marktext#3850]
I was wondering if you might consider adding localization support, starting with Chinese and potentially expanding to other languages in the future. This enhancement could make the project more accessible to a broader audience, allowing even more people to benefit from its functionality.

**Comment by DYH-Hong** [comment]
Dup of #138.

Since the official development seems halted, please consider subscribe [this fork](https://github.com/jacobwhall/marktext/issues/7).

---

这个问题已经被反复提过了（#138）

官方似乎停止更新marktext了。请考虑移步到[另一个fork项目里](https://github.com/jacobwhall/marktext/issues/7)

**Comment by riceshowerX** [comment]
> #138 的重复。
> 
> 由于官方开发似乎已停止，请考虑订阅[此分叉](https://github.com/jacobwhall/marktext/issues/7)。
> 
> 这个问题已经被反复提过了（#138）
> 
> 官方似乎停止更新marktext了。请考虑移步到[另一个fork项目里](https://github.com/jacobwhall/marktext/issues/7)

Thanks for the reminder! It's a bit disappointing that the original author is no longer maintaining the project, but I'm glad to see that other developers are continuing it. I'll be sure to keep an eye on those forks. Hopefully there will be Windows support in the future. Thanks again for letting me know!
