### ISSUE TITLE
id would be cool if : Re-open the last file at startup

### ISSUE THREAD

**Issue by RobinKrier** [marktext/marktext#386]
simple function but versy usefull...
When i work, i use full screen with multiple tab and focus.
When i re-open the program i like to found thing like i lets them...

**Comment by RobinKrier** [comment]
i try to be more specific but my english is not very good, sorry...

**Comment by Jocs** [comment]
My English is also not good, I basically understand what you mean, Do you mean open the last edit file or project when we reopen Mark Text?

**Comment by RobinKrier** [comment]
yep totally !

**Comment by FlappyHeart** [comment]
That's just what I need. Because I am usually working with the same folder. 
I had clone the source code and about to making a version with Chinese.

**Comment by Jocs** [comment]
@FlappyHeart HI, we already has the the plan #138  , So you can transition Mark Text to Chinese when we start this work, but we will do it after version 1.0 released.

**Comment by wedza** [comment]
I would also like this feature. Personally, I love using Mark Text to take notes, but sadly, I have to reopen my folder everytime I launch it (which is very annoying).

Like other compétitors, we can imagine a setting to open a specific folder at startup.
![image](https://user-images.githubusercontent.com/20335741/41822538-a234eb44-77f1-11e8-9d67-39f5aa27b2a3.png)

**Comment by gitfineon** [comment]
I would prefer to reopen previous session. Which means 
* on every "open file" & "save file" action store the file path to a session file
* with every "close tab" remove this path from the session file
* launching the application checks the session file and reopens all files. If a file does not exist anymore, drop it from the session file

**Comment by fxha** [comment]
Closing this issue in favour of #988.
