### ISSUE TITLE
low Startup Performance

### ISSUE THREAD

**Issue by thaikolja** [marktext/marktext#3862]
### Slow Startup Performance

**System Details:**

- **Device:** iMac 2021
- **OS:** macOS 15.0 Beta (24A5331b)
- **Processor:** Apple M1
- **Memory:** 16 GB

**Description:**

MarkText is an outstanding Markdown editor—thank you! However, its startup performance is a significant drawback.

- **Cold Start:** Takes over **12 seconds** to fully launch and display the interface.
- **Warm Start:** Even after closing and reopening within a few minutes, it still takes over **3 seconds**.

In comparison, other editors like MacDown launch in just **0.65 seconds**.

**Request for Feedback:**

I'm curious if others are experiencing similar startup delays with MarkText or if it is just me. I genuinely appreciate the UI and features, and if the startup time improves, I'd love to make it my primary editor.

**Comment by heit0r** [comment]
You're probably must facing some other performance issue bc it opens in less than 4 secs in my old dual core Intel Core i3 M 390 running linux. Still, for a 100mb app it seems too much for me. For comparison, Chrome opens faster or _gives the feeling_ of it. Other heavier apps also start up faster.

**Comment by heit0r** [comment]
You're probably must facing some other performance issue bc it opens in less than 4 secs in my old dual core Intel Core i3 M 390 running linux. Still, for a 100mb app it seems too much for me. For comparison, Chrome and Firefox opens faster _or gives the feeling_ of it. Other heavier apps also start up faster.

**Comment by thaikolja** [comment]
> You're probably must facing some other performance issue bc it opens in less than 4 secs in my old dual core Intel Core i3 M 390 running Linux.

I haven't found a way to increase the speed and instead switched to [**Typora**](https://typora.io/), which is also [installable on Linux](https://support.typora.io/Typora-on-Linux/). It's the perfect Markdown and writing app in my opinion. MarkText had its last release in March 2022... It feels a bit dead to me.

In case you'd like to have a look:

![Typora](https://i.imgur.com/oiav3Bk.png)

And `CMD` + `/` lets you see the unformatted code:

![Typora unformatted](https://i.imgur.com/rEJcyi6.png)

**Comment by heit0r** [comment]
Thank you! I was definitely looking for an alternative. I'm gonna try this out, thank you.

**Comment by rowieh** [comment]
> I'm curious if others are experiencing similar startup delays with MarkText or if it is just me.

I have the same issues as you with my MacBook Pro M2. Even a warm start is taking about 5 seconds on my M2, a cold start definitly longer. Maybe it has something to do with the M-range processors. I can check if my old Intel mac is having the same startup times. As far as I'm aware of it don't.

**Comment by thaikolja** [comment]
> > I'm curious if others are experiencing similar startup delays with MarkText or if it is just me.
> 
> I have the same issues as you with my MacBook Pro M2. Even a warm start is taking about 5 seconds on my M2, a cold start definitly longer. Maybe it has something to do with the M-range processors. I can check if my old Intel mac is having the same startup times. As far as I'm aware of it don't.

If you find anything out, please share.

**Comment by rowieh** [comment]
> > I'm curious if others are experiencing similar startup delays with MarkText or if it is just me.
> 
> I have the same issues as you with my MacBook Pro M2. Even a warm start is taking about 5 seconds on my M2, a cold start definitly longer. Maybe it has something to do with the M-range processors. I can check if my old Intel mac is having the same startup times. As far as I'm aware of it don't.

Today I tested on my 10-year old Intel MacBookPro. The Intel Mac is significantly faster then M2, with cold starts as well as warm starts. 
Right now I don't have time for debugging a little more, but I will do that later on. Maybe you guys know a good startingpoint for debugging this type of issues?

**Comment by rowieh** [comment]
Today I did some extra test on my M2 MacBookPro and 2013 Intel MacBookPro. The first thing I noticed is (as mentioned before) that the Intel MacBookPro is faster then on the M2, while the hardware is much slower of course. But, I find out that the app is eating a lot of resources on both Mac's. Looking at the resources used, there is something really wrong on both mac's. Because of the heavy resource usage (even when not in use) the battery is draining very fast.

Here a screenshot of the M2 process:
<img width="694" alt="MarkText" src="https://github.com/user-attachments/assets/550a0d50-d44d-49f8-890d-d1e2272e73db">

And a part of the process tree of the MarkText process on the M2:
```
    1496 Thread_11674
    + 1496 thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801836bd3]
    +   1496 _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff80183b1d3]
    +     1496 node::OnFatalError(char const*, char const*)  (in Electron Framework) + 444799  [0x114e94e0f]
    +       1496 uv_run  (in Electron Framework) + 319  [0x111756b1f]
    +         1496 uv_free_interface_addresses  (in Electron Framework) + 1310  [0x11176800e]
    +           1496 kevent  (in libsystem_kernel.dylib) + 10  [0x7ff8018011ee]
    +             1496 ???  (in <unknown binary>)  [0x7ff8914069a8]
    1496 Thread_11675
    + 1496 thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801836bd3]
    +   1496 _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff80183b1d3]
    +     1496 node::OnFatalError(char const*, char const*)  (in Electron Framework) + 435111  [0x114e92837]
    +       1496 node::OnFatalError(char const*, char const*)  (in Electron Framework) + 445266  [0x114e94fe2]
    +         1496 uv_cond_wait  (in Electron Framework) + 9  [0x111762b79]
    +           1496 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1242  [0x7ff80183b758]
    +             1496 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7ff8017ff0ee]
    +               1496 ???  (in <unknown binary>)  [0x7ff8914069a8]
    1496 Thread_11676
    + 1496 thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801836bd3]
    +   1496 _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff80183b1d3]
    +     1496 node::OnFatalError(char const*, char const*)  (in Electron Framework) + 435111  [0x114e92837]
    +       1496 node::OnFatalError(char const*, char const*)  (in Electron Framework) + 445266  [0x114e94fe2]
    +         1496 uv_cond_wait  (in Electron Framework) + 9  [0x111762b79]
    +           1496 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1242  [0x7ff80183b758]
    +             1496 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7ff8017ff0ee]
    +               1496 ???  (in <unknown binary>)  [0x7ff8914069a8]
    1496 Thread_11677
    + 1496 thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801836bd3]
    +   1496 _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff80183b1d3]
    +     1496 node::OnFatalError(char const*, char const*)  (in Electron Framework) + 435111  [0x114e92837]
    +       1496 node::OnFatalError(char const*, char const*)  (in Electron Framework) + 445266  [0x114e94fe2]
    +         1496 uv_cond_wait  (in Electron Framework) + 9  [0x111762b79]
    +           1496 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1242  [0x7ff80183b758]
    +             1496 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7ff8017ff0ee]
    +               1496 ???  (in <unknown binary>)  [0x7ff8914069a8]
    1496 Thread_11682
    + 1496 thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801836bd3]
    +   1496 _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff80183b1d3]
    +     1496 node::SetTracingController(v8::TracingController*)  (in Electron Framework) + 65891  [0x114f040f3]
    +       1496 uv_sem_wait  (in Electron Framework) + 16  [0x111763120]
    +         1496 semaphore_wait_trap  (in libsystem_kernel.dylib) + 10  [0x7ff8017fc52e]
    +           1496 ???  (in <unknown binary>)  [0x7ff8914069a8]
    1496 Thread_11720
    + 1496 thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801836bd3]
    +   1496 _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff80183b1d3]
    +     1496 fse_run_loop  (in fsevents.node) + 93  [0x10da286cd]
    +       1496 CFRunLoopRun  (in CoreFoundation) + 40  [0x7ff8019970a4]
    +         1496 CFRunLoopRunSpecific  (in CoreFoundation) + 560  [0x7ff801914a4c]
    +           1496 __CFRunLoopRun  (in CoreFoundation) + 1365  [0x7ff8019155fb]
    +             1496 __CFRunLoopServiceMachPort  (in CoreFoundation) + 145  [0x7ff801916b70]
    +               1496 mach_msg  (in libsystem_kernel.dylib) + 19  [0x7ff8017fc89a]
    +                 1496 mach_msg_overwrite  (in libsystem_kernel.dylib) + 692  [0x7ff8018035e4]
    +                   1496 mach_msg2_internal  (in libsystem_kernel.dylib) + 78  [0x7ff80180a72d]
    +                     1496 mach_msg2_trap  (in libsystem_kernel.dylib) + 10  [0x7ff8017fc5b2]
    +                       1496 ???  (in <unknown binary>)  [0x7ff8914069a8]


Total number in stack (recursive counted multiple, when >=5):
        69       ???  (in <unknown binary>)  [0x7ff8914069a8]
        27       _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff80183b1d3]
        27       thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801836bd3]
        16       __psynch_mutexwait  (in libsystem_kernel.dylib) + 10  [0x7ff8017fe882]
        16       _pthread_mutex_firstfit_lock_slow  (in libsystem_pthread.dylib) + 214  [0x7ff801836921]
        16       _pthread_mutex_firstfit_lock_wait  (in libsystem_pthread.dylib) + 76  [0x7ff801838b14]
        15       mach_msg  (in libsystem_kernel.dylib) + 19  [0x7ff8017fc89a]
        15       mach_msg2_internal  (in libsystem_kernel.dylib) + 78  [0x7ff80180a72d]
        15       mach_msg2_trap  (in libsystem_kernel.dylib) + 10  [0x7ff8017fc5b2]
        15       mach_msg_overwrite  (in libsystem_kernel.dylib) + 692  [0x7ff8018035e4]
        14       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 10663288  [0x1132cee98]
        12       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 0  [0x1128a3920]
        11       ???  (in Rosetta Runtime Routines)  [0x1005e1150]
        10       __error  (in libsystem_kernel.dylib) + 0  [0x7ff8017fcd03]
        10       __psynch_mutexdrop  (in libsystem_kernel.dylib) + 10  [0x7ff8017fe9ba]
        10       _pthread_mutex_firstfit_unlock_slow  (in libsystem_pthread.dylib) + 243  [0x7ff801836b57]
        10       _pthread_mutex_firstfit_wake  (in libsystem_pthread.dylib) + 20  [0x7ff801838ba2]
        10       uv_mutex_lock  (in Electron Framework) + 9  [0x111762b39]
        9       ???  (in Rosetta Runtime Routines)  [0x12204f1b4]
        9       uv_mutex_unlock  (in Electron Framework) + 9  [0x111762b99]
        8       pthread_mutex_lock  (in libsystem_pthread.dylib) + 0  [0x7ff8018364d5]
        8       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 10266876  [0x11326e21c]
        8       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 10457482  [0x11329caaa]
        7       __CFRunLoopServiceMachPort  (in CoreFoundation) + 145  [0x7ff801916b70]
        7       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 10574264  [0x1132b92d8]
        7       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 10574669  [0x1132b946d]
        6       CFRunLoopRunSpecific  (in CoreFoundation) + 560  [0x7ff801914a4c]
        6       __CFRunLoopRun  (in CoreFoundation) + 1365  [0x7ff8019155fb]
        6       _pthread_mutex_firstfit_lock_slow  (in libsystem_pthread.dylib) + 0  [0x7ff80183684b]
        6       pthread_mutex_unlock  (in libsystem_pthread.dylib) + 0  [0x7ff801836959]
        6       uv_async_send  (in Electron Framework) + 0  [0x111756350]
        6       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 10700527  [0x1132d800f]
        5       ???  (in <unknown binary>)  [0x7ff8914052bc]
        5       mach_absolute_time  (in libsystem_kernel.dylib) + 26  [0x7ff8017fc921]
        5       stat$INODE64  (in libsystem_kernel.dylib) + 10  [0x7ff8017fdae2]
        5       v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*)  (in Electron Framework) + 10537214  [0x1132b021e]
```

So there is definitely something going wrong on the M2 as well as the Intel OS.

**Comment by thaikolja** [comment]
Thanks for sharing the results. Being Electron, I'd have expected it to pop up just like any other Electron app, such as VS Code.

To me, it seems like a CPU issue. In your logs, I see that it's using Rosetta, which makes non-ARM apps available for the M chips. My guess is the culprit is Rosetta.

**Comment by rowieh** [comment]
> To me, it seems like a CPU issue. In your logs, I see that it's using Rosetta, which makes non-ARM apps available for the M chips. My guess is the culprit is Rosetta.

I guess you might be right about that. That could also explain why the M2 is slower then the old Intel mac, because the Intel doesn't need the Rosetta translation.
