### ISSUE TITLE
打开之后不进行任何操作，关闭会提示是否保存

### ISSUE THREAD

**Issue by N94P** [marktext/marktext#387]
RT。

不进行任何操作其实是 **进行了点击** 。但我没有进行任何文本的编辑。点击文档空白区域之后文本名显示小红点，关闭时会提示保存。

**Comment by AlexanderMisel** [comment]
其实还有就是，提示框太难看。和软件整体风格不搭。

**Comment by Jocs** [comment]
@AlexanderMisel 你是指原生提示保存的提示框吗？

**Comment by AlexanderMisel** [comment]
是的。Typora的HTML Modal提示好看很多。

**Comment by Jocs** [comment]
@AlexanderMisel 我不太确定你指的是什么 Modal，能发一个截图吗

**Comment by AlexanderMisel** [comment]
这样的：
![default](https://user-images.githubusercontent.com/7542439/41825528-e60cc5b4-7853-11e8-9381-07b96c4ecc0b.png)

**Comment by AlexanderMisel** [comment]
还有“丢弃”的英文应该是discard。写成Delete怪怪的。
