### ISSUE TITLE
Less confusing closing dialog

### ISSUE THREAD

**Issue by SaintDI** [marktext/marktext#388]
### Description

![image-20180621-1148](https://user-images.githubusercontent.com/18102192/41698699-fddfc64e-7549-11e8-94a9-5b47c537c200.png)

To me, "Delete" button is quite confusing — it seems like this is file delete option. Maybe "Discard" button instead would be better?

### Versions

- Mark Text: v 0.12.25
- OS: Windows 10

Thanks.

**Comment by Jocs** [comment]
How to generate this save dialog?

**Comment by Shadowghost** [comment]
@Jocs Open Mark Text, write something, don't save and exit Mark Text with the X in the top right.

**Comment by Jocs** [comment]
@SaintDI @Shadowghost `Delete`: just means don't save these files and close the APP.

**Comment by Shadowghost** [comment]
@Jocs I know, but I'd favor `Discard` or `Discard changes`, since you discard your changes. `Delete` sounds like the file gets deleted, which isn't the case. Besides that I think `Discard` is the common operator for this kind of operation.

**Comment by SaintDI** [comment]
Yeah, I understand, but I'm talking about user experience in general. Maybe
it's kind of subjective and it's only my personal problem. But usually in
same dialogs I see "discard" word instead "delete".

**Comment by Jocs** [comment]
@SaintDI @Shadowghost How about `Don't save`?

**Comment by SaintDI** [comment]
Is fine too.

**Comment by Jocs** [comment]
@SaintDI @Shadowghost PR is welcome， can you please submit a PR about this issue, use `Don't save` to replace `Delete`?
