### ISSUE TITLE
Menu bar broken latest Dev build on windows

### ISSUE THREAD

**Issue by SuperSandro2000** [marktext/marktext#39]
On the latest source the menu bar at the top is broken and replaced by a context menu.

**Comment by notAlaanor** [comment]
What do you mean by broken? The menu bar has been moved to a context menu in the corner to accommodate a custom Windows titlebar. This is what I'm seeing on the latest dev build:
![marktext-win](https://user-images.githubusercontent.com/17591936/37636866-9b21f174-2c58-11e8-9b8e-0c441b4b2d2d.png)

**Comment by SuperSandro2000** [comment]
I don't like the change as it is very strange and confusing and sometimes the menu appears in the middle of the screen.
And every normal windows app has this bar.

**Comment by Jocs** [comment]
I think Mark Text is concise editor， Mark Text wants the user to focus as much as possible on the text they are writing, it wants to hide everything that might distract the user.  we also can add a toggle between the current context menu and previous menu bar. Or just hide the previous menu bar when user is typing...

**Comment by notAlaanor** [comment]
I'm not sure how we could hide a native menu bar frequently, but an option to switch between a native and integrated window frame would be good. Another option could be to draw the menu bar ourselves, so that it fits with the theme, but retains the familiar layout.

**Comment by SuperSandro2000** [comment]
@Jocs I don't think the classical menu style would distract you at all.

**Comment by Jocs** [comment]
As @notAlaanor say, We can not set the dark theme of the previous menu bar, So @notAlaanor think a a custom Windows titlebar is needed.

**Comment by Jocs** [comment]
@SuperSandro2000 @notAlaanor This issue will be closed, but we can still discuss about menu bar in windows.
