### ISSUE TITLE
Marktext-setup-0.12.25.exe don't supports x86  no longer.

### ISSUE THREAD

**Issue by linpengcheng** [marktext/marktext#390]
### Description

Marktext 0.12.25  don't supports windows 7 x86  no longer.

### Versions

- Mark Text: 0.12.25
- OS: windows 7 32bit

**Comment by fxha** [comment]
@linpengcheng Could you give me some more details. I extracted the archive and both x86 and x86_64 application is packed into it. I also tested it on a old Win7-x86 VM without problems.
