### ISSUE TITLE
搜索功能在我的WIN10上无法展示搜索结果

### ISSUE THREAD

**Issue by NorDorado** [marktext/marktext#393]
### Description

搜索文档中含有的内容时，搜索栏没有展示搜索结果，也没有未匹配的提示。
![](https://i.loli.net/2018/06/22/5b2c72facb121.png)
在搜索文档中未含有的内容时，有no matched file的正确提示
![](https://i.loli.net/2018/06/22/5b2c72facf264.png)

软件是卸载原版本之后再安装的，搜索栏还是没法正确展示搜索到的结果。

### Versions

- Mark Text:0.12.25
- OS:windows10 64位

**Comment by Jocs** [comment]
请问你是打开的项目吗？`open project` ，这儿的搜索只针对在项目中搜索

**Comment by NorDorado** [comment]
是的，通过 open project 打开的文件夹。

![文件夹.png](https://i.loli.net/2018/06/22/5b2c82e22e6d7.png)

**Comment by NorDorado** [comment]
之前不小心点到了关闭这个问题。。。难受

**Comment by Jocs** [comment]
>之前不小心点到了关闭这个问题。。。难受

什么意思？是问题还存在，还是误操作？

**Comment by NorDorado** [comment]
问题还存在，之前关闭这个话题是在点comment的时候不小心点到旁边的close了，抱歉

**Comment by Jocs** [comment]
@NorDorado 不好意思我现在无法重现这个 bug，能帮我们找一下问题吗？可以 clone 项目，安装依赖，npm run dev。在本地跑一下，打开控制台，看下具体原因，以便我们修改。我觉得可能是样式问题？

**Comment by NorDorado** [comment]
我也不太清楚，刚刚在舍友电脑上复现了这个问题，我是按照您的那个演示图操作的，这是我操作的过程gif图

![GUOCHENG1.gif](https://i.loli.net/2018/06/22/5b2cc991a60b2.gif)

https://i.loli.net/2018/06/22/5b2cc991a60b2.gif

**Comment by NorDorado** [comment]
您好，我在安装依赖，不过晚上有课程，晚点给您消息

**Comment by Jocs** [comment]
👌，thanks

**Comment by NorDorado** [comment]
大佬，我是第一次调试，chrome 按照教程进了node.js的控制台，可是操作没有输出啊
![截图1.png](https://i.loli.net/2018/06/22/5b2cf8120a969.png)
![截图2.png](https://i.loli.net/2018/06/22/5b2cf81156bf6.png)
是哪里出了问题吗

**Comment by NorDorado** [comment]
log4cplus 提示ERROR已经解决了。。。可是还是没有输出
![qq 20180622213320](https://user-images.githubusercontent.com/36447758/41779275-e6c97e1c-7663-11e8-8f43-6ece1ee69772.png)
![qq 20180622213343](https://user-images.githubusercontent.com/36447758/41779288-f339fd5c-7663-11e8-9045-3204df59ee04.png)

**Comment by Jocs** [comment]
@NorDorado 你是新创建的文档对吧？不是打开已有的文档。
