### ISSUE TITLE
Issues on math equations

### ISSUE THREAD

**Issue by AlexanderMisel** [marktext/marktext#399]
### Description

1. Math equations are not fully generated when switching view mode from source.
2. Inline equations font size is larger than normal text.

### Steps to reproduce

1. Go to source code view
2. Insert following code `Suppose $b>0$, what's the value of $\lim_{a\to0}\frac{-b+\sqrt{b^2-4ac}}{2a}$ ?`
3. Switch to real time view

**Expected behavior:** Typora layout
![default](https://user-images.githubusercontent.com/7542439/41806084-3e6122a8-76e9-11e8-847d-85d380102869.png)

**Actual behavior:** Mark Text initial layout
![default](https://user-images.githubusercontent.com/7542439/41806095-9a6f5808-76e9-11e8-89fa-d729913fc92e.png)

Mark Text layout after moving the caret
![default](https://user-images.githubusercontent.com/7542439/41806092-6e5c21b0-76e9-11e8-9348-bbadf96d1b4c.png)

**Link to an example:** no link

### Versions

- Mark Text: v 0.12.25
- OS: Windows 7 64bit

**Comment by fxha** [comment]
Thanks for reporting the issue @AlexanderMisel.

> Inline equations font size is larger than normal text.

Yeah, seems not aligned but on the other side the upper-case sigma symbol is aligned.

![mt_math_issue](https://user-images.githubusercontent.com/22716132/41817881-00425d32-77a4-11e8-9fa4-f12f481d2685.png)

**Comment by Jocs** [comment]
@AlexanderMisel We'll fix it asap.
