### ISSUE TITLE
export as Styled HTML error

### ISSUE THREAD

**Issue by ricosmall** [marktext/marktext#40]
### Description

When export the document as `Styled HTML`, then open the exported HTML file in browser, the code part display wrong even couldn't scroll.

### Steps to reproduce

1. Type some content, insert a piece of code, like below:

![image](https://user-images.githubusercontent.com/18362949/37630896-e9641574-2c21-11e8-81cd-d7c35c2edee8.png)

2. Export the file as `Styled HTML`, operate step: `file` => `Export` => `Styled HTML`

![image](https://user-images.githubusercontent.com/18362949/37630963-630c6a20-2c22-11e8-9048-d2a6bc61b155.png)

3. Open it in browser (Chrome or Safari), will be this:

![image](https://user-images.githubusercontent.com/18362949/37631979-f2ce1560-2c26-11e8-9cba-3d57bcafc78d.png)

**Expected behavior:** Display in right way, at least could scroll in code area

**Actual behavior:** Part of code was hidden and could not scroll in code area

**Link to an example:** Append my file content below:

<pre>
# Title

javascript

```javascript
function add (a, b) {
  return a + b;
}
```

sh

```sh
sudo chmod +x yourfile.js
./yourfile.js
```

python

```python
def func (a, b) {
  return a * b;
}
```
</pre>

### Versions

- Mark Text: 0.6.14.117
- OS: macOS 10.13.3

**Comment by Jocs** [comment]
This bug report is very clear, Thank you. I'll fix it as soon as possible.

**Comment by Jocs** [comment]
@ricosmall I can not reproduce this bug in my development environment, So I will release v0.7.16 recently, And see if it will happen in this version.

**Comment by ricosmall** [comment]
@Jocs I will update to new release version and test again, then write my feedback here.

**Comment by Jocs** [comment]
@ricosmall new version has been released, have a try.

**Comment by ricosmall** [comment]
@Jocs I have tested the new version, but got the same consequence like before. I am trying to find the code but not success yet. 🤣

**Comment by Jocs** [comment]
@ricosmall I test it in my computer, And this issue didn't happen.

<img width="934" alt="3" src="https://user-images.githubusercontent.com/9712830/37871876-6c7911d2-302b-11e8-94a3-27691bde1ca8.png">

Can you help figure out this issue?

Is there any Chrome extensions that affect this code block style?

**Comment by ricosmall** [comment]
@Jocs My safari has no extension, but I got the same consequence like it in chrome, just display wrong.

**Comment by Jocs** [comment]
@ricosmall Your Mark Text version?

**Comment by Jocs** [comment]
I'll close this issue if no more information.
