### ISSUE TITLE
[feature request] make table of contents in sidebar collapsible

### ISSUE THREAD

**Issue by sg-s** [marktext/marktext#404]
### Description

right now, it shows every heading in a nested structure. what I would like is a "foldable" TOC so that you can see only the h1 headings, for example. clicking on the first h1 heading should expand that section and show all the sub headings

**Comment by gitfineon** [comment]
Indeed, this is absolutely necessary for the TOC View. Instead of collapse all by default, I would like to see a default (e.g. down to h3) configurable in  in the preferences.

**Comment by Jocs** [comment]
Nice feature, we are also consider of this.

**Comment by Jocs** [comment]
Add in https://github.com/marktext/marktext/pull/778
