### ISSUE TITLE
export as Styled HTML error 2

### ISSUE THREAD

**Issue by ricosmall** [marktext/marktext#41]
### Description

When export as Styled HTML, the symbol which should be just existed in editor was exported to HTML file.

### Steps to reproduce

1. Type some content:

![image](https://user-images.githubusercontent.com/18362949/37632253-522ffd9c-2c28-11e8-8886-1ae6ea14b8a2.png)

2. Export file as Styled HTML:

![image](https://user-images.githubusercontent.com/18362949/37632276-6f8a91f4-2c28-11e8-94cd-28e1bf72c3d2.png)

3. Open file in browser (Chrome or Safari):

![image](https://user-images.githubusercontent.com/18362949/37632324-a461fb7e-2c28-11e8-87a3-a4291e9861cc.png)

**Expected behavior:** Couldn't see the symbol in exported file.
**Actual behavior:** The symbol is displayed in the exported file.

**Link to an example:**  Append my file below:

<pre>
# Title

javascript

```
function add (a, b) {
  return a + b;
}
```

sh

```
sudo chmod +x yourfile.js
./yourfile.js
```

python

```
def func (a, b) {
  return a * b;
}
```
</pre>

### Versions

- Mark Text: 0.6.14.117
- OS: macOS 10.13.3

**Comment by Jocs** [comment]
Thank you, Any PRs are welcomed.
