### ISSUE TITLE
中文输入体验不流畅

### ISSUE THREAD

**Issue by WanderHuang** [marktext/marktext#412]
### Description

1. 在标题、代码后面继续输入中文时，打入的字符会被撤销掉，导致无法续接中文。只能在这几种格式之后先插入一段英文字母，然后才能输入中文。
2. 另外看两个issue里面提到windows中ctrl + z 和ctrl + shift + z不能用。我这也是。版本详情在后面。

### Steps to reproduce

1. 快捷键调出标题，输入中文，字符被撤销掉了
2. 快捷键调出code，输入code，移动光标到code后，输入中文，字符被撤销掉
3. ctrl + z 无法撤销，每次只能手动删除

**Expected behavior:** `ctrl + num`或者ctrl + `之后能够继续输入中文

**Actual behavior:** 需要插入英文字符，并在写完后面的中文后，删掉之前的英文字符。操作繁琐。

**Link to an example:** 

![default](https://user-images.githubusercontent.com/18475942/42196107-b4d5f45a-7eae-11e8-8fd5-2c409d0d248f.gif)

### Versions
- Mark Text: v 0.11.42
- OS: Windows 10

**Comment by Jocs** [comment]
@WanderHuang gif 图片貌似没加载出来？

**Comment by WanderHuang** [comment]
刚才可能没开shadowsocks 已传上来了

**Comment by Jocs** [comment]
这可能和使用的输入法有关，你是使用的什么输入法？搜狗输入法也会有这个问题吗？

**Comment by WanderHuang** [comment]
嗯用的是搜狗。
![default](https://user-images.githubusercontent.com/18475942/42196321-ea956fc0-7eaf-11e8-9c22-4c836bd2260e.png)

**Comment by WanderHuang** [comment]
刚发现另外一个问题：
1. 本地存储好readme.md，在marktext中引入图片
2. 引用方式为`![image](https://github.com/xxxx/xxx/xxx.gif)`
3. 提交后在github中编辑readme.md，变成了`!\[image\](https://github.com/xxxx/xxx/xxx.gif)`
4. 结果：图片没法识别出来，在预览处显示为`![image](https://github.com/xxxx/xxx/xxx.gif)`，链接高亮可点击跳转到图片
5. 后续步骤： 删除中括号前的`\`后，预览图片正常

**Comment by Jocs** [comment]
@WanderHuang 你是怎么在 marktext 中引入图片的？导致其加入了转义字符`\`

**Comment by WanderHuang** [comment]
我想了一下，应该是这个原因引起的：
![default](https://user-images.githubusercontent.com/18475942/42369107-8159234c-813b-11e8-84c9-6357032e5f1b.gif)

- 右边的文档不是用marktext写的，直接整个image过来就会有问题，多了转义

- 而只复制链接就没有这个问题

顺便提一下，marktext打开其他文件编写的md文件时，会出现不一致的地方....

**Comment by Jocs** [comment]
@WanderHuang 原来你喜欢黑色主题啊，引起这个问题的原因可能是复制导致的，我需要再测试下。你也可以帮忙找找具体原因

**Comment by WanderHuang** [comment]
嗯是复制的问题，测了一下全局复制。

1. 图片复制复制不过去
2. []这两个符号有转义，其他的没
![test](https://user-images.githubusercontent.com/18475942/42371544-601cb692-8142-11e8-967c-b37ecad95764.png)

**Comment by sanguigu** [comment]
根本不能输入中文

**Comment by Jocs** [comment]
@sanguigu 请报告一下软件及操作系统版本号。

**Comment by ywl913** [comment]
是搜狗输入法的锅，你换win10自带的输入法就没这毛病

**Comment by Jocs** [comment]
@WanderHuang 最新版本还有这个问题吗？

**Comment by WanderHuang** [comment]
> @WanderHuang 最新版本还有这个问题吗？

新版本没有这个问题了，界面也好看一些
