### ISSUE TITLE
Add Functional Bracket Auto-Completion

### ISSUE THREAD

**Issue by CisBetter** [marktext/marktext#414]
### Description

Many modern code editors such as Atom, GNOME Builder and VS Code contain bracket auto-completion.
Mark Text already places closing brackets whenever an opening bracket is typed. However, when reaching the auto-completed closing bracket and typing the bracket again it just adds a second bracket in front of the auto-completed one.

I suggest that typing a closing bracket in front of a bracket moves the cursor behind the bracket as if it was not added by auto-completion.
An already very good implementation of this feature can be seen in Atom Text Editor (see Expected behaviour).

### Steps to reproduce

1. type opening bracket
2. *(optional)* Enter some text.
3. type closing bracket

**Expected behaviour:**

![marktext-bug1-atom](https://user-images.githubusercontent.com/17952058/42230237-bd7df708-7ee8-11e8-9cf9-61daec15547f.gif)

**Actual behaviour:**

![marktext-bug1](https://user-images.githubusercontent.com/17952058/42230146-88fd11bc-7ee8-11e8-8f7e-7029c3e04dc8.gif)

**Link to an example:**
*See **Expected behaviour:***

### Versions

- Mark Text: v 0.12.25
- OS:
  - Type: [GNU](https://www.gnu.org/gnu/linux-and-gnu.html)
  - Kernel: Linux-Libre
    - Version: 4.17.3-1

**Comment by Jocs** [comment]
Yeh, I agree with you, it's a better user experience to move the cursor behind when user input the close bracket. PR is also welcomed!
