### ISSUE TITLE
add cursorBlinking

### ISSUE THREAD

**Issue by qsimpleq** [marktext/marktext#417]
### Description

Hello, is it possible to add cursorBlinking (or something like this name) option in config, for editing blinking speed (0 value = disable blinking).

Or maybe i can do this right now something else way?

Thanks.

### Versions

- Mark Text: marktext-0.12.25-x86_64.AppImage
- OS: Ubuntu 18.04

**Comment by qsimpleq** [comment]
I'm really need the possibility to turn off the blinking.

**Comment by Jocs** [comment]
@qsimpleq Can you tell me why you need this feature?

**Comment by qsimpleq** [comment]
If briefly, the flickering of the cursor in the editor interfere me because of the light form of epilepsy.

**Comment by Jocs** [comment]
Ok, I'll take this feature into consideration, but I also will balance the implementation cost and benefits of this feature.

Thanks.

**Comment by Jocs** [comment]
I found that the cursor is already blinking, the latest version of Mark Text， and on my macOs
