### ISSUE TITLE
Previews of inline math equations

### ISSUE THREAD

**Issue by AlexanderMisel** [marktext/marktext#419]
### Description

Previews of inline math equations wraps when not needed

### Steps to reproduce

**Expected behavior:** [What you expected to happen]
![default](https://user-images.githubusercontent.com/7542439/42608481-86294e00-85ba-11e8-936c-648ec32b4cd4.png)

**Actual behavior:** [What actually happened]
![default](https://user-images.githubusercontent.com/7542439/42608422-3492bc3e-85ba-11e8-81d6-75d6726ab6ac.png)

**Link to an example:** no link

### Versions

- Mark Text: v 0.12.25
- OS: Windows 7 64bit

**Comment by Jocs** [comment]
Thanks for report this issue, it seems a style error, PR is also welcomed.
