### ISSUE TITLE
View is broken after drag and drop

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#42]
### Description

Drag and drop don't work and destroys the editor.

### Steps to reproduce

1. Write markdown file (and exit editor)
2. Drag and drop markdown file into the editor
3. Editor view is broken

**Expected behavior:**

When the drag and drop event is accepted, the file should be loaded as markdown.

**Actual behavior:**

Editor view is broken. You cannot edit text anymore and the tilebar disappears on windows. Furthermore the editor cannot be closed, until you send force kill.

### Images

**Working editor (open...):**

![mt_default](https://user-images.githubusercontent.com/22716132/37654576-f1e3a158-2c42-11e8-8e37-86cb7d8f6f9d.png)

**Drag and drop on Linux (Gnome):**

![mt_drag_drop](https://user-images.githubusercontent.com/22716132/37654590-faf42aa6-2c42-11e8-853c-9efb6678d009.png)

**Drag and drop on Windows:**

![mt_win_drag_drop](https://user-images.githubusercontent.com/22716132/37654593-feba4e4a-2c42-11e8-8bb8-cab267f57e0c.png)

### Versions

- Mark Text: 0.7.17
- OS: Linux (Gnome) and Windows 10

**Comment by Jocs** [comment]
@fxha Sorry for the poor documents, It's in 

>edit menu => insert image => upload to cloud

This is an experiment feature.

But the view broken is really a bug need to fix.
