### ISSUE TITLE
Exported styled HTML doesn't use KaTeX fonts

### ISSUE THREAD

**Issue by AlexanderMisel** [marktext/marktext#420]
### Description

When exporting a document with math equations, the KaTeX fonts used in the HTML aren't exported, thus fallback font Times New Roman is used

### Steps to reproduce

**Expected behavior:** [What you expected to happen]
![default](https://user-images.githubusercontent.com/7542439/42609142-a287b354-85bd-11e8-8374-3394bdc8a23a.png)

**Actual behavior:** [What actually happened]
![default](https://user-images.githubusercontent.com/7542439/42609126-8fa10452-85bd-11e8-9192-ad102113bb18.png)

**Link to an example:** no link

### Versions

- Mark Text: v 0.12.25
- OS: Windows 7 64bit

**Comment by Jocs** [comment]
Thanks for report this issue, PR is also welcomed.
