### ISSUE TITLE
Feature Request: RTL support

### ISSUE THREAD

**Issue by mrg0lden** [marktext/marktext#421]
### Description

Support for writing from Right-To-Left for RTL languages such as Arabic and Hebrw
[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]
Being able to change direction, or at best the editor can manage text direction automatically ([dir=auto]).

**Actual behavior:** [What actually happened]

There's no way to change text direction as of the time this issue was opened.

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

This is how it looks now

![image](https://user-images.githubusercontent.com/8347078/42631433-e06bdf86-85e2-11e8-94d6-367fbc27daee.png)

Arabic text should start from right and ends to left.

### Versions

- Mark Text: 0.12.25
- OS: Windows 10 1804 64bit

**Comment by Jocs** [comment]
>Being able to change direction, or at best the editor can manage text direction automatically 

How editor can manage text direction automatically?

**Comment by mrg0lden** [comment]
@Jocs If it uses HTML viewer as I think, we can add the attribute `dir="auto"` which will handle directions perfectly.

**Comment by mohsenkhanpour** [comment]
Please implement this feature. I can help with testing if someone can submit a PR.

**Comment by mohsenkhanpour** [comment]
@Jocs Yes. 
I can live with the text being aligned to left however my main problem is when I am using a rtl language and add an English word, it breaks the whole style and the text is not readable anymore.

@mrg0lden A fast and quick solution is using an online rtl markdown editor.
http://www.sobhe.ir/moratab/
http://dariubs.github.io/rtlmd/

**Comment by fxha** [comment]
One question: is the text saved "normal" (left-to-right) and only displayed RTL?

**Comment by mohsenkhanpour** [comment]
@fxha Yes. definitely. It's more a matter of styling rather than programming.  
When I copy the text from these editors and paste into Mark Text or VSCode, the words will jumble up. However when I use them in a Jekyll blog they show correctly.

To further clarify:
This text is one saved markdown file hosted on GitHub. (Viewed on GitHub too.)
![screenshot_1](https://user-images.githubusercontent.com/28626829/43015241-4b878ed2-8c64-11e8-8105-7eb0ef0476f9.jpg)
After applying this code with a custom CSS extension:

![screenshot_2](https://user-images.githubusercontent.com/28626829/43015242-4d1368c0-8c64-11e8-88e3-b4ae414ce20e.jpg)

The text is shown currently.
![screenshot_3](https://user-images.githubusercontent.com/28626829/43015244-4ef1f9f4-8c64-11e8-8ace-2afe30279ac5.jpg)

**Comment by mrg0lden** [comment]
@jocs I'd like to help, but I find myself lost in the source code xD. I'd appreciate any kind of clues.

**Comment by Jocs** [comment]
@mrg0lden I think you don't need electron experience, but you need some html\css knowledge.

**Comment by Jocs** [comment]
@fxha Is it needed to add a menu item to select `ltr` or `rtl` ? or any other ideas?

**Comment by fxha** [comment]
@Jocs Yeah I think it's the best to add a settings option and a dynamic direction (`ltr` or `rtf`) to the editor HTML element.

**Comment by Jocs** [comment]
@fxha Default setting is also needed as you said.

**Comment by enyaxu** [comment]
Seems that we need add menu and option for control text direction, I would push a request later. So we could discuss further more.

**Comment by Jocs** [comment]
@enyaxu Ok, As we discussed, first we need to add a default configuration to the user preference, and we can modify the writing direction of the currently edited document in the menu. The options in menu item do not affect the configuration in user preference, you can refer to line ending implement.

**Comment by enyaxu** [comment]
@Jocs Thank you for your suggestions.

**Comment by mrg0lden** [comment]
@Jocs Can't we actaully have a direction per paragraph? (or tags such as <p><h1> etc)
In chrome there's something similar to that, in input fields I can change the direction by right clicking on the field or by a shortcut (ctrl+shift).

**Comment by mrg0lden** [comment]
@mohsenkhanpour Just wanted to ensure that `dir=auto` is an attribute not a css property
```<p dir=auto editable>test</p>
<p dir=auto editable>تجربة</p>```
a working example: http://jsfiddle.net/fwxg3ute/

**Comment by enyaxu** [comment]
Push a request, please test.

**Comment by Jocs** [comment]
@enyaxu ok, thanks.

**Comment by talothman** [comment]
Examples: 
https://codepen.io/siamak/pen/rAmBb

**Comment by mohamnag** [comment]
it this supported only on win? I don't see any menu item to switch direction on mac.

**Comment by mshamaseen** [comment]
Hmm, how can I make the direction RTL? I'm using Linux but i can't find the option on the edit menu

**Comment by Enlight432** [comment]
This problem can be solved with HTML when writing in MarkText, but it's troublesome, tiring, and repetitive. I hope this problem is solved by default
