### ISSUE TITLE
Don't create Untitled-1 unless the user enters some text.

### ISSUE THREAD

**Issue by johnblommers** [marktext/marktext#422]
### Description

marktext creates *Untitled-1* even when the user types in no text. Perhaps the user just wanted to check for updates. Finding none, they exit marketext but are then inconveniently prompted if they want to save Untitled-1. The prompting is inappropriate.

### Steps to reproduce

1. Launch marktext
2. Exit marktext

**Expected behavior:** [What you expected to happen]

I would expect marktext to exit silently.

**Actual behavior:** [What actually happened]

marktext asks to save Untitled-1 which is empty.

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: v 0.12.25
- OS: macOS 10.11.6 El Capitan
- OS: Ubuntu 16.04 LTS

**Comment by stefnotch** [comment]
I think that [this PR](https://github.com/marktext/marktext/pull/391) should address this issue.

**Comment by johnblommers** [comment]
Agreed ✅

**Comment by Jocs** [comment]
@johnblommers @stefnotch That PR still has some problem and not finished, So it is not merged.
