### ISSUE TITLE
Loli.net sucks

### ISSUE THREAD

**Issue by lolinet-sucks** [marktext/marktext#426]
### Loli.net sucks

Uploading files are sent to i.loli.net  but we cannot delete files from this site
Team is not reactive to delete content. When a content is reported for deletion the content MUST BE deleted !

For European customers : This site is not GDPR compliant ! 

### Steps to reproduce

1. In Marktext : upload an image

**Expected behavior:** File in document or in a separated link

**Actual behavior:** file sent to i.loli.net

### Versions

- Mark Text: 0.11.42
- OS: Windows 10

**Comment by Jocs** [comment]
@lolinet-sucks I am very sorry to bring you these troubles. Loli.net is just an experimental function. Later, we still hope to support the function of uploading pictures through plug-ins. Users can configure the account and password of the picture cloud by themselves.
