### ISSUE TITLE
Support DataURL images

### ISSUE THREAD

**Issue by wdhwg001** [marktext/marktext#429]
### Description

Currently, MarkText doesn't support dataurl images.

### Steps to reproduce

1. write `![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAAXNSR0IArs4c6QAABktJREFUWAnFWH2IVFUU/503o7vb7s5sioKVldsHZSEZoeYHpKTY5u66UEtkEkYYfUB/WFAZYYT5RxYVVhBUUiRRxO66uklflqumYiWVGpVaahpJOTO7y9o6M7ffebPjvDfz3rznYtuFN++ej3vu75573znnjsCvbTdVOJFcACMLYTAZYsZRdQQgv5I+xP7HQOwdtEjCz8S54IunkfbULJjsWsrqPeUFZj8EXQRdQ9Z4wNRyQb3kHSR9kO8DpA8imt2KBXUnC8PC99wA1Wt/plbSQw9zMiu8mUBNXci7MNFX0FKzJ1DboVAAaINL7iC4SQ75ue+KbIMlz6Ep1hHGeMFLOc/9t+AUkTEzkMm2oy35KvaakUEgcx7sTM1E2nx5jrc1aG7KZReiI29HY9VhP2ULurVps3b4wSkkMwXpgW+gH6VPs+xQAnOZj3wY2GY0t70Nnf0Xe01mMQw0ewkCeSKGOp8D1r2wInN48K9ANF6NKhmNaPQ6WNZSiLxHnf5AWyDI9MAHXmdSeFj30dVXBxtxabyOqKxGY/xnF9eL6DIxDPQsBbJPMULUeqkUePIaWuIPFGieUrQnTnJgnZNZvi9P08iK8joe0k1943Dq9EbONdlDWmBFrIXOEKRhhukrbLNWDQmcmp9ffRwSvYW9o2Vny5pHnXJ6MPkDD+k1TqZ3X06gIjYeDfKPS97ROwnZzHLyZjFfx7gpR9jfAwsvoSm+w6WrREdiNbJYVsJ3MaKT8xmHH4md+F1ib8J0loDTL8+ku3mGW/mMo61qLvYqPncQxHYen8dKbVnfl/KKOJJ+MM/RLWZVEqaxiilu6dNzCYpe82jGCGWr0JF88ox0s4kiaxadof06BouwIXG+igmQJVOoUACPtGR9zS3N+M1j87PmGUaKnfTmm0ikfqSn55bVzwmZPKyZ2rXses4umQKGicc51crEsuYwFnxGoFl/C8wYBksILnxCEFOv9qI5o1rPadwt12QqNptKzJZTLq3m2i2kb8YnJo7+1HSevWk0dSPtTSE/7tI9G8LAXswgQC02A5oxFyCZXEEtj4NP7lxJ8vejwYf4eAY7+q4FMi3ktYaLFNQsNNuDuWqmPXGYqw4GKZLmdj7CQPoy01iQywtTaW99ohUZZgqYUW6BHyX7GXMn8iNh0zI9TDP2V/giY+enfBqw24QP8k117yM6YhIXdizMVIypeo3Qr5gtd4ewuyF/5nDLNuJI6jiBvs1yaQnW908IHNt43u8sKu4L1LMVpEdf+TOol5whNC2VsJhbsBgZJpi2xG9c7Rf2M9LahFtr/igx2hTbwEXt5AKnlsjcjCNKDm6xfQtzi4dGXUKwd7NyeQsDmaP07EpvMxLi4mTsYze4xXLA25CTKwOMecsQqajnNi2gpHzSh4nw6voEOvuud1qx+8bsLeEVMwwa0GbqcltcabaxrNTCsqpYz0F/iObYC4P0IXQlbsIAdnOLy5dqmUylw0auK1LBLS5hFzGIJbU458H58b+52euKFIrJXS5GQ90BSKSZH1ifi+8kRPahuXank2X3TS5LlPBLGfNyAFWQja4plTs4Yuzc6OCAk29BxLqBID/gY391g/JeLvgNVGoJVpSrc1fN21x2/AjBhFygziu0J7fS9TPypPvNXGtZs21QbkGB6uoZg4FIJZqrjpUAy2uFqgcHlbk7boDrU832pTpvrPit22lFmtBUy8vSEFpb6llu1eOhRwoSboA6Um/8MPf7GhFW1GLWoGLE83YZ76voELT3TITJaBV9j4Mboiv7SwHqGfkp1U2QWo34NwWq2QTSzfP3Fa82xxCvOokUqUjvRUhnLmTvcqbRu/yPjb95WyKyrhSgSrSU1xu/3lf/z2ahtfAVO4HofyUiLJPkLyd7ePtMHmPiG7wBKpKFsW7+scMswD94hr0xYogswXTp9weooNSTV8ZmESTruGFswiurOojN+wx6YdEQpJdq3zjpNWgIPMF3GBufpt7T0eEB5udq6+UfQ+mHePe4k6xyuTs/IuRbt5WeGxtbngenA88eYH66TclROCUzGBPrWTDoBUff9aSraVZLJdZzLJm0KglaiMgviPDMNca25s3n30MHmLcQ9GbJpFUJ1ebRHRMI+lL2T3MRWvp/y5K0HWNrNjq9Rv6Z9i+GNPiMeo0tRQAAAABJRU5ErkJggg==)` inside an empty document.

**Expected behavior:** You may see a skype icon.
![incomingcallbrandingimage](https://user-images.githubusercontent.com/8943519/42955868-0fdc58f8-8bb1-11e8-9e3d-1731e29dd933.png)

**Actual behavior:** It just doesn't work, the editor says the image is broken.

**Link to an example:** 
![image](https://user-images.githubusercontent.com/8943519/42955752-cea3d320-8bb0-11e8-8ccb-80fbe60e009b.png)

### Versions

- Mark Text: 0.12.25
- OS: Windows 10 1804 x64

**Comment by Jocs** [comment]
Nice feature, PR is also welcomed!

**Comment by fxha** [comment]
@Jocs I think this is a good feature. However, it's dangerous too because you could inject code into Mark Text as well. We must ensure that it's implemented correctly without possibility to inject code and also I would disable this feature by default.
