### ISSUE TITLE
Notepad option gone from the context menu

### ISSUE THREAD

**Issue by frederickrb** [marktext/marktext#43]
### Description

[Description of the bug or feature]

Hi.
This is a simple and straightforward thing. After installing and testing Mark Text, I've noticed that the "Text Document" option from the New menu, in the Windows Explorer context menu (right click) has gone. It only came back after uninstalling Mark Text and rebooting the system. I realize this tool is a good alternative to Notepad, but I don't really like having my options taken away from me.

- Mark Text:
- OS:Windows 10 (64-bit)

**Comment by SuperSandro2000** [comment]
https://github.com/marktext/marktext/pull/26

**Comment by SuperSandro2000** [comment]
This would be fixed by this https://github.com/marktext/marktext/pull/26
It got sadly not yet merged and prevents me from using marktext on windows.
