### ISSUE TITLE
[...] is displayed in gray and orange

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#432]
### Description

`[...]` is displayed in gray and orange.

### Steps to reproduce

1. Write `[...]`

**Expected behavior:** [What you expected to happen]

normal text color

**Actual behavior:** [What actually happened]

![mt_bug_ui](https://user-images.githubusercontent.com/22716132/43012316-4b5a2eba-8c46-11e8-82da-717a0e9e7ca4.png)

### Versions

- Mark Text: 0.12.25

**Comment by Jocs** [comment]
`[...]` will be recognized as [shortcut reference link](https://github.github.com/gfm/#links).

**Comment by fxha** [comment]
@Jocs Is it a wanted feature or a bug? I think it's a problem with the `[TOC]` highlighting.

**Comment by Jocs** [comment]
We haven't started implementing the TOC yet, as you know. so now the highlight of the TOC is exactly what it should be considered as a link. When the TOC function is implemented later, it will be modified.

**Comment by fxha** [comment]
My problem is that I use `[...]` (instead of `...`) as ellipsis in quotes. First of all it's highlighted and also not displayed as `[...]` but as `...`.

**Example:**

```markdown
> foo [...] bar

foo [...] bar
```

Github:

> foo [...] bar

foo [...] bar

Mark Text:

![mt_bug_00](https://user-images.githubusercontent.com/22716132/43160589-e3eb96c2-8f85-11e8-9ca3-6caf9e2156aa.png)

What's your opinion? Should we display `[...]` without style?

**Comment by fxha** [comment]
> Can we use ... as a link text?

Yes, it seems so.

> Also, if we don't find the link reference of some reference link, should we show a warning (orange highlight as above) or should it not be processed(without style)?

That's a good question and it's difficult to answer, because I think the user should be able to use `[some text]` in his document. If you highlight it, you prevent the usage or you have to escape the square brackets.

**Comment by Jocs** [comment]
OK， I'll mark this as a optimization.

**Comment by aladagemre** [comment]
I agree user should be able to use [sometext]. Type the following and you will see brackets are hidden, 0 is orange.

> train_data[0]

Although this is a code segment, sometimes using it inline without code highlighting is more practical. In these cases, not being able to see the brackets is a bit annoying.

**Comment by Jocs** [comment]
@aladagemre What's the `[sometext]` meaning in markdown syntax?

**Comment by aladagemre** [comment]
Hi @Jocs,

It does not have any meaning if it's not followed by another bracket, parenthesis or column (:). But it may have meaning in the text context, regardless of Markdown syntax.

Other editors do not remove the brackets if it's alone without following characters.

**Comment by Jocs** [comment]
>Other editors do not remove the brackets if it's alone without following characters.

@aladagemre I'll rethinking this feature or issue later. and I agree with you that we show not hidden the brackets, it maybe has some meanings when user use `brackets`.

**Comment by fxha** [comment]
@Jocs I think we should definitely not highlight `[...]` because of the comments above and this "feature" break `[[link](#)]` rendering. It should be displayed as [[link](#)] but is displayed as `[link(#)]`.

**Comment by fxha** [comment]
> `[...]` will be recognized as [shortcut reference link](https://github.github.com/gfm/#links).

@Jocs Did you mean [reference link](https://github.github.com/gfm/#reference-link)?

![mt_ref_link](https://user-images.githubusercontent.com/22716132/54216826-adc64900-44ea-11e9-85e6-0f9a4f813979.png)

**Comment by Jocs** [comment]
@fxha Yes, to highlight the reference link, I need to look at GFM again, and then optimize.
