### ISSUE TITLE
Embed images into exported HTML document

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#433]
### Description

Add a option to embed images into exported HTML document or copy all images into `%document_name-images%` folder. So that you can easily move the HTML document (and image folder).

**Comment by enyaxu** [comment]
I think we should create folder when export html document, this folder can hold html itself, and other dependence resources, like fonts, images, etc...
link with font export issue #420

**Comment by Jocs** [comment]
Yes, there is a problem here, and we need a function to copy the picture to the current folder, and output it as a folder when outputting html.

**Comment by Jocs** [comment]
I think it's a trend to put images on the cloud in the future？ so I would like to make a plugin that can upload images to the cloud.

**Comment by fxha** [comment]
I think that's a good idea and it would be great to change the default image provider (as mentioned  in #426). However, any user should be able to decide whether he want to upload the image to cloud or save locally.

**Comment by fxha** [comment]
Closing in favour of #549.
