### ISSUE TITLE
Don't autocomplete _ and * in code- and math blocks

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#434]
### Description

It would be great if `_` and `*` is not autocomplete to `_<cursor>_` and `*<cursor>*` in ~~code- and~~ math blocks. What's your opinion?

**Comment by fxha** [comment]
> what's your meaning in code- ?

code-blocks

**Comment by enyaxu** [comment]
code-block use codemirror

**Comment by Jocs** [comment]
@enyaxu yes！

**Comment by fxha** [comment]
OK, I was wrong; only math blocks.

**Comment by JayceCao** [comment]
I think the autocompletion for `_` and `*` is not necessary. I just need one `_` in the normal text, but marktext gives me two when I insert a `_`, so that I have to delete the other. It's not convenient. In my opinion, the best way is to make this feature a modifiable preference.

**Comment by Jocs** [comment]
@fxha @JayceCao We already have `autoPairMarkdownSyntax` option in user preference to disable markdown syntax autocompletion `*` and `_`.
