### ISSUE TITLE
Slugify heading text and add slug text as HTML id

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#435]
### Description

Slugify heading text and add slug text as HTML id. Why? e.g. you can navigate to the heading (`[go to heading 'a b'](#a-b)`).

**Example:**

Markdown:

```
# a

foo

# a b

bar

```

exported HTML:

```
...
<h1 id="a">a</h1>
...
<h1 id="a-b">a b</h1>
...
```

**Comment by enyaxu** [comment]
This feature had been done when you use 'Export to Html' and not in 'Export to styled Html', we just need to change 'Export to styled html' functional.
