### ISSUE TITLE
Feature Request: Toolbox appearing when selecting text.

### ISSUE THREAD

**Issue by mohsenkhanpour** [marktext/marktext#436]
### Description

Feature request.

### Steps to reproduce

Not needed.

**Expected behavior:** Show a toolbox when selecting text.

**Actual behavior:** 

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: Future versions
- OS: All

It would be a good idea to show a toolbox when selecting text. It saves a lot of time comparing to going to the menu. Also it helps focusing on the content.
Sample from [Uncolored](https://github.com/n457/Uncolored) which is written in Electron too:
![2018-07-20_22-02-16](https://user-images.githubusercontent.com/28626829/43016803-42f99cce-8c69-11e8-930c-fc9ff6f626cc.gif)

**Comment by enyaxu** [comment]
Nice feature.

**Comment by Jocs** [comment]
This is a good feature. We have thought about doing this. We can do the same thing with the shortcut keys, but you need to be familiar with the shortcut keys. Before adding this feature to marktext, I need to know how many people need it. Like this feature, if you support this feature, please 👍 it.

**Comment by Jocs** [comment]
@mohsenkhanpour 

Is it what you want?

![1539142450489](https://user-images.githubusercontent.com/9712830/46711789-78d67180-cc80-11e8-886e-3569e792b031.jpg)

**Comment by mohsenkhanpour** [comment]
@Jocs Great job! Very nice. Yes. It is much more faster than selecting from the menu if you don't know the keyboard shortcuts (which is the case for most of my clients). 
What buttons are gonna be on the toolbox?

**Comment by Jocs** [comment]
@mohsenkhanpour  

>What buttons are gonna be on the toolbox?

All the inline syntax in the format menu.
