### ISSUE TITLE
Sort files within a folder

### ISSUE THREAD

**Issue by pp611** [marktext/marktext#438]
### Description

With a project with multiple folders, the files with a folder are not sorted (or I could not figure out by what order the files are sorted). In the screen capture, most of the files are sorted by ascending names, but `2014-07` appeared ahead of `2014-04`.

<img width="776" alt="screen shot 2018-07-24 at 10 28 48" src="https://user-images.githubusercontent.com/12554834/43166859-a0bae0ee-8f4c-11e8-8503-dfa4c5cc2a9f.png">

Ideally the default order would the file descending modification time, even better each folder can set the sorting option (e.g., name ascending/descending, modification time ascending/descending, etc) and be saved in preferences.

It would be nice to set as a default preference of showing files with only `.md` and `.txt` extensions. So the MacOS `.DS_Store` won't show up in the left bar.

### Steps to reproduce

Open a project with folders and folders have multiple files

### Versions

- Mark Text: 0.12.25
- OS: MacOS 10.13.6

**Comment by AmauriAires** [comment]
May I work on this?
