### ISSUE TITLE
Windows: Wrong context menu position

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#44]
### Description

The context menu (which replaced the menu bar) is opened on random positions on the screen - sometimes outside the editor. The bug appears mostly on second monitor.

### Images

![mt_win_context_menu](https://user-images.githubusercontent.com/22716132/37654859-ccca0ab4-2c43-11e8-9b05-879fcada50df.png)

### Versions

- Mark Text: 0.7.17
- OS: Windows 10 dual monitors

**Comment by Jocs** [comment]
@notAlaanor Can you help with this issue, thank you!

**Comment by fxha** [comment]
@Jocs Created PR #46 for a fix.
