### ISSUE TITLE
Checkbox without text breaks layout

### ISSUE THREAD

**Issue by juliushaertl** [marktext/marktext#441]
### Description

Having a checkbox without a text after it breaks the rendered markdown layout.

### Steps to reproduce

1. Add the following markdown (in the regular wysiwyg edit mode)
```
- [ ] 1

- [ ] 2

Test
```
2. Remove the text from 2 (in the regular wysiwyg edit mode)
```
- [ ] 1

- [ ] 

Test
```

3. Move cursor to 5th line (Test)

4. Close and reopen the document

**Expected behavior:** [What you expected to happen]

![screenshot from 2018-07-30 12-31-07](https://user-images.githubusercontent.com/3404133/43392600-77105b14-93f4-11e8-9095-48c9aa529a97.png)

**Actual behavior:** [What actually happened]
![screenshot from 2018-07-30 12-30-30](https://user-images.githubusercontent.com/3404133/43392608-7ae7d9ba-93f4-11e8-95a2-cdda81047ab4.png)

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: 0.12.25
- OS: Linux

**Comment by fxha** [comment]
@juliushaertl Thanks for reporting the issue. There are problems with switching between source and preview-mode too. I guess it's a parser problem.
