### ISSUE TITLE
Can I open an existing file in new tab of an existing window?

### ISSUE THREAD

**Issue by JayceCao** [marktext/marktext#442]
### Description

How can I open an existing file in new tab of an existing window? When I open a file, it always opens the file in a new window.

### Versions

- Mark Text: v0.12.25
- OS: macOS

**Comment by fxha** [comment]
Unfortunately there is currently no way to open a file from another location than the project in the same window. @Jocs  and I have already talked about this topic but without definite results.

The original idea was to add a option to open a new window and all remaining menu items open in the current window. E.g:

- New file
- Open new window
- Open file (within current window)
- Open project (within current window)

or

- New file
- Open new window
- Open ->
  - Open file (within current window)
  - Open project (within current window)

**Comment by JayceCao** [comment]
The feature of `Open project` satisfies my need. Closed this issue.
