### ISSUE TITLE
Debugger Setup MarkText with VSCode

### ISSUE THREAD

**Issue by pp611** [marktext/marktext#445]
### Description

I plan to do a fork and do some experiments with the source code. Can any of the project member share some debug configuration (for, ex., VSCode). A few line of setup instruction would be even better.

### Versions

- Mark Text: 0.12.25
- OS: MacOS 10.13.6

**Comment by enyaxu** [comment]
@pp611 You can see my PR.

**Comment by stefnotch** [comment]
Link to PR: https://github.com/marktext/marktext/pull/446
