### ISSUE TITLE
Exported output includes what should be display symbols

### ISSUE THREAD

**Issue by Ketrel** [marktext/marktext#447]
### Description

Creating a bulleted list in the following format shows a carriage return-like symbol in non-source views

    * Test Item  
      Something else

    * Test Item 2  
      Something Again

    * Test Item 3  
        Something yet more

(there are two spaces after each test item)

These show in all but source view, and when exporting PDF, these symbols are included.

### Steps to reproduce

1. Make a list as laid out in description
2. Export as PDF
3. View PDF

**Expected behavior:** 
Symbols indicating trailing spaces should not be present in PDF

**Actual behavior:** 
Symbols indicating trailing spaces are present in PDF

### Versions

- Mark Text: 0.12.25
- OS: Windows 10 1803

**Comment by Jocs** [comment]
@Ketrel thank you for report this issue, I think it's a `good to first` issue, so PR is also welcomed.
