### ISSUE TITLE
Broken markdown file

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#448]
### Description

I managed to create a .md file that MarkText cannot display at all:
```
- Regarding the "favourites", what is the desired behavior:

  - Normal results & favourites are displayed, however, the favourites are higher up (boost)

  - Only the favourites are 

- 
- 

- 

- 

- 


```

### Steps to reproduce

1. Start MarkText
2. Switch to source code mode
3. Copy-paste the text above
4. Switch back to the default mode

### Versions

- Mark Text: v 0.12.25
- OS: Windows 10

**Comment by enyaxu** [comment]
@stefnotch 
Could you upload screen capture?  I can't reproduce this issues from my mac.
![kapture 2018-08-02 at 22 27 06](https://user-images.githubusercontent.com/40362568/43590796-70086c46-96a4-11e8-9fae-7ed3dba0951b.gif)

**Comment by stefnotch** [comment]
Sure:
![2018-08-02_18-45-26](https://user-images.githubusercontent.com/10220080/43598123-44da09b4-9684-11e8-91be-31e59c55b3e6.gif)


(Tested it on 2 different PCs, 100% reproduction rate. If you copy-paste the text into the source code mode thingy, it apparently doesn't always get reproduced?)

**Comment by fxha** [comment]
Thanks @stefnotch, this is definitely a bug:

```
TypeError: Cannot read property 'key' of undefined
    at ContentState.importCursor (importMarkdown.js?4b04:390)
    at Muya.setMarkdown (index.js?64a7:507)
    at Muya.init (index.js?64a7:102)
    at new Muya (index.js?64a7:54)
    at VueComponent.eval (editor.vue?7b20:160)
    at Array.eval (vue.esm.js?a026:1837)
    at flushCallbacks (vue.esm.js?a026:1758)
    at <anonymous>
```

Commit 486eb93

**Comment by enyaxu** [comment]
@fxha 
I push a PR to fix this. Please review.

**Comment by Joshuasony** [comment]
I've got a similar issue, not sure if it has to do with source code mode. 
But Marktext won't display anything in certain .md files - doesn't matter if I open them by doubleclicking the file or open it via menu of Marktext. 

It works for some documents, but not for others. Couldn't find out why.

MacOS 10.14
Marktext 0.12.25

**Comment by Jocs** [comment]
@Joshuasony  Can you send me a broken file? ransixi@gmail.com
