### ISSUE TITLE
Latex 预览挡住公式

### ISSUE THREAD

**Issue by zombiecong** [marktext/marktext#450]
### Description

如图
<img width="899" alt="screen shot 2018-08-05 at 8 24 58 pm" src="https://user-images.githubusercontent.com/7962780/43685876-a6524cfe-98ed-11e8-9ff8-d04456ac51a7.png">

### Steps to reproduce

公式如下：
```
$$\begin{bmatrix} 1 & 0 & -1 \end{bmatrix} \times \left[ \begin{array}{c} 1 \\ 2 \\ 1 \end{array} \right] = \begin{bmatrix} 1 & 0 & -1 \\ 2 & 0 & -2 \\ 1 & 0 & -1 \end{bmatrix} $$
```

**PS:** 貌似`Latex`里的内容复制粘贴会少东西，公式最好手动输入一下。

### Versions

- Mark Text: v0.12.25
- OS: macOS 10.13.5 Beta

**Comment by Jocs** [comment]
@zombiecong 
目前 Latex 分为数学公式输入分为三种。

* inline 语法

```markdown
$a \ne b$
```

* display 语法

```markdown
$$a \ne b$$
```

* block 语法

```markdown
$$
a \ne b
$$
```

出现该issue 中问题的应该是 inline 语法。对于如此长的数学公式，我们推荐使用第三种 block 语法，将其拆分为多行输入。如下：
![1534060587597](https://user-images.githubusercontent.com/9712830/43999913-d4243876-9e48-11e8-93ce-d1fb6c3068f1.jpg)

对于使用inline math 语法导致展示遮住公式的问题，我们会在后续修复。欢迎持续关注。

**Comment by zombiecong** [comment]
@Jocs 收到，谢谢。
