### ISSUE TITLE
Empty list item exception

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#451]
### Description

A list with empty list item text throws an exception.

### Steps to reproduce

1. Create a list with at least one empty list item. E.g:

```
- a

- 

- 

- d<cursor>
```

2. Click on the empty list item in preview mode
3. Check console error log

**Expected behavior:** [What you expected to happen]

No exception

**Actual behavior:** [What actually happened]

```
Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at findNearestParagraph (domManipulate.js?596c:17)
    at Selection.getCursorRange (selection.js?eaba:771)
    at ContentState.updateState (updateCtrl.js?27d0:296)
    at HTMLDivElement.changeHandler (index.js?64a7:378)
```

Commit 486eb93

### Versions

- Mark Text: v0.10.25
- OS: all

**Comment by Jocs** [comment]
@fxha For some reasons, I only had time on weekends to check the issues and review code. So thank you!

**Comment by stefnotch** [comment]
I can still reproduce this issue.

Test document:
```
### Scheidung

- Verschuldensscheidung

  - Varianten:

    - Allein

    - Ueberwiegendes

    - Gleichteilig

  - Siehe Pflichten

- Zerruettungsscheidung

  - Krankheit

    - z.B. Ehemann wird zum Zombie, Ehemann wird sehr geisteskrank

  - Trennung 3/6 Jahre getrennt von einander leben

- 
```

**Comment by fxha** [comment]
@stefnotch Yes, that's true when switching from source code mode back the `span` inside `li` is missing. 

Error message:

```
dom.js?956f:26 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at findNearestParagraph (dom.js?956f:26)
    at Selection.getCursorRange (index.js?d47e:771)
    at ContentState.selectionChange (paragraphCtrl.js?6d3e:20)
    at setTimeout (keyboard.js?a29c:52)
```

**Comment by Jocs** [comment]
@fxha @stefnotch This problem maybe caused by me, I have rewrite the `importMarkdown` function. I'll fixed asap.

**Comment by fxha** [comment]
@Jocs You can look at my PR #456. You have to detect a empty list item and add a empty `span` element.

**Comment by Jocs** [comment]
@fxha Ok, Thanks!
