### ISSUE TITLE
Not working hotkeys Undo/Redo

### ISSUE THREAD

**Issue by 0object** [marktext/marktext#468]
### Description

Not working hotkey Undo/Redo Ctrl+Z/Ctrl+Shift+Z. Other hotkeys does work.

### Steps to reproduce

1. Enter text
2. I want undo action
3. Shortcut keys undo does not work. I use the command in menu.

**Link to an example:** https://youtu.be/_mk0gayxPIU

### Versions

- Mark Text: 0.12.25
- Os: Windows 10

**Comment by fxha** [comment]
Duplicate of #311 and #216
