### ISSUE TITLE
How to change font for codes?

### ISSUE THREAD

**Issue by Fangyh09** [marktext/marktext#471]
### Description

Can not change font for codes
### Steps to reproduce
\`\`\` python
print("hello world!")
\`\`\`

### Versions

- Mark Text: v 0.12.25
- OS: macOS 10.13.4

**Comment by Jocs** [comment]
We have not this feature yet, in the near future, you can shadow the style by custom theme.

**Comment by Fangyh09** [comment]
@Jocs Thanks for the reply.
