### ISSUE TITLE
Code block colors change after switching to source code mode and back

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#474]
### Description

When you have a code block and switch to source code mode and back again, the colors will change.

### Steps to reproduce

1. Create a code block with the following text
```
    //test
# h1
<br>
```
2. Switch to source code mode
3. Switch back

**Expected behavior:** The colors stay black and white

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/10220080/44570142-1c290100-a77d-11e8-8341-77c65a4e51aa.png)

### Versions

- Mark Text: v 0.12.25
- OS: Windows 10

**Comment by stefnotch** [comment]
https://github.com/marktext/marktext/issues/171 might be related?

**Comment by Jocs** [comment]
@stefnotch I think there is no relationship between these two issues.

**Comment by Jocs** [comment]
@stefnotch Because we set the mode to `markdown` at source code mode, but we didn't remove the mode when we change back to preview edit mode. But I don't know how to delete markdown mode in codemirror. help is wanted.
