### ISSUE TITLE
Format of math block broke after pressing ESC

### ISSUE THREAD

**Issue by liyz15** [marktext/marktext#476]
### Description

After pressing ESC, the format of math block is broken

### Steps to reproduce

1. Insert a math block such as
```
$$
e=mc^2
$$
```
and leave the edit mode.

2. Press ESC, the "2" at the subscript dropped down

**Expected behavior:** The ESC won't affect the math block

**Actual behavior:** It did

### Versions

- Mark Text: 0.12.25
- OS: macOS 10.13.6

**Comment by Jocs** [comment]
@liyz15 What‘s the meaning of ` leave the edit mode.` ? and can you show me some broken picture or screenshots ?

**Comment by liyz15** [comment]
@Jocs It just means stop editing the equation. Actually if you don't, pressing ESC will break the equation preview.

![kapture 2018-08-24 at 22 27 13](https://user-images.githubusercontent.com/32741741/44590156-08b57e80-a7ed-11e8-8716-a4c637dc7e4e.gif)
