### ISSUE TITLE
Add Support for GDScript Syntax Highlighting

### ISSUE THREAD

**Issue by infosisio** [marktext/marktext#478]
GDScript is the official scripting language of the promising Godot game engine.

It is rising in popularity and becoming a force on its own for game development.

Supporting it for syntax highlighting makes total sense imo.

**Comment by fxha** [comment]
We use CodeMirror to display code blocks. Unfortunately `GDScript` syntax highliting is not available, you can find a list of all  languages [here](https://codemirror.net/mode/). Maybe you or someone else can provide/create a custom syntax file.

**Comment by Jocs** [comment]
@infosisio We have change the highlight library from `CodeMirror` to `Prism`, but it still not support `GDScript` you can make a PR to prism add `GDScript` highlight support.
