### ISSUE TITLE
App freezes when double-clicking on .md file in Ubuntu (18.04)

### ISSUE THREAD

**Issue by Pimichi** [marktext/marktext#481]
### Description

First of great job with the marktext app it's great and I love. The real-time feature is what makes this app truly useful IMO. I really appreciate the work.

I am using Ubuntu 18.04.1 LTS. When I want to open a markdown *.md file from the file browser (Nautilus) with a double-click, the app opens up and then "freezes". Opening the system monitor shows 4 marktext processes, out of which one has a "high" CPU usage (30-40% with a Intel® Core™ i5-7260U CPU @ 2.20GHz × 4 ). This process is also very memory intense gathering up to 2+ GB of RAM! The file I was trying to open only had a few lines of text. Before my entire system froze, I killed the processes after approx. 10-15s. I also have the theme set to dark mode. After double-clicking a .md file it opens up in the light theme. I don't know what's going on but it feels like some kind of "infinite loop".

I can however open all files, if I open the marktext app first and then drag the files from the file browser onto the app window. It then opens up a new window with the contents of the "dropped file". Also choosing "Open file" via the menu works. It's just a bit tiresome always having to open files like that when you want to edit just a few lines.

I'd really like to help and solve the issue. However I have no idea where to start and what files I have to look at. What function gets called when double clicking on it, etc.. So I appreciate the work once again and many thanks again for all the work and time you have put into it. 

### Steps to reproduce

1. Open up the default file browser in Ubuntu (Files/ Nautilus) 
2. Locate any .md file
3. Double-click the .md to open it in marktext

**Expected behavior:** Open .md file so I can read and edit it

**Actual behavior:** Marktext open and freezes

### Versions

- Mark Text: v 0.12.25
- OS:  Ubuntu 18.04.1 LTS

**Comment by fxha** [comment]
Thank @Pimichi, there's a problem while checking for a markdown file because Mark Text tries to load and parse the executable itself.
