### ISSUE TITLE
'Open Project' command. Maybe rename to 'Open folder'

### ISSUE THREAD

**Issue by tenbob** [marktext/marktext#485]
There is a menu command and also a button labelled 'Open project'. Without the documentation I am not sure what they do. What seems to happen is it opens a folder so you can view the files in the sidebar. Then you can click any md file to open it. 

Maybe I'm missing something important. But if it just opens a folder, why not simply call it 'Open folder'. This would avoid confusing the user.

Thanks for your great work on this project. I don't want to sound like I'm complaining. I just want to help developing the best product.

**Comment by Jocs** [comment]
Very good advice, PR is also welcomed.
