### ISSUE TITLE
Show filename while hovering over marktext file on dock

### ISSUE THREAD

**Issue by Joshuasony** [marktext/marktext#487]
Hi there
Marktext is awesome, thank you for that! 
Since i'm starting to use Marktext more frequently on MacOS, I'm working on several files at the same time. Some of them I minimize to the dock. 
It would be really helpful, if I could hover over on Marktext file and then see the filename. At the moment, it only says "Marktext":
![grafik](https://user-images.githubusercontent.com/7139459/45139872-81cfb100-b1b1-11e8-99d7-53d80a248bcd.png)

Sketchapp for example displays the filename:
![grafik](https://user-images.githubusercontent.com/7139459/45139932-a9267e00-b1b1-11e8-8e05-295d9db517ba.png)

I'm not a developer, so I can't code it myself. But maybe somebody else can? 
Cheerio, Josh

**Comment by Jocs** [comment]
@Joshuasony Thanks for your advice, I think it's a good idea to show the file name when hover over marktext file.

**Comment by Jocs** [comment]
@Joshuasony It will show the filename and project name `filename - project` when you open project, otherwise it will only show filename when you hover dock.

**Comment by Joshuasony** [comment]
@Jocs, when will this be released? Could still use this on a daily basis. :)

**Comment by Jocs** [comment]
@Joshuasony Hi, you can build marktext for yourself, or just wait for the next release version, I think it will be coming in the next month.
