### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by webdq** [marktext/marktext#489]
1. 建议把3种预览模式从菜单里独立出3个按钮
2. 建议增加软件的主题配色，修改滚动条的颜色，滚动的时候不能一眼找到滚动条的位置
3. 搜索斗图，向下滚动总会加载重复的图片

**Comment by Jocs** [comment]
> 建议把3种预览模式从菜单里独立出3个按钮

应该是 3 中编辑模式？很多菜单中的功能可以独立出来，比如导出等，但是目前需要设计师的帮忙。

>  建议增加软件的主题配色，修改滚动条的颜色，滚动的时候不能一眼找到滚动条的位置

这个可以提交 PR，修改滚动条样式就好。

> 搜索斗图，向下滚动总会加载重复的图片

这个是接口返回的，我需要验证下是接口重复，还是 marktext 的问题，当然能帮忙验证就更好了。
