### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#49]
### Description

If I start the app I get an application crash on master. See image below.

![mt_crash](https://user-images.githubusercontent.com/22716132/37704109-32e674f4-2cf8-11e8-8ae7-6f11cf1306ea.png)

### Versions

- Mark Text: latest master
- OS: Windows 10

**Comment by Jocs** [comment]
@fxha Sorry，master is not stable, I'll fix it soon!

**Comment by Jocs** [comment]
@fxha The crash is fixed, but the user preferences can not be use now,
