### ISSUE TITLE
Funny math rendering

### ISSUE THREAD

**Issue by amirhosseindavoody** [marktext/marktext#490]
### Description

I have a markdown file with the following content, when I open the file the math rendering is funny as you see in the image below. As soon as I click on the equation block, the rendering fixes.

```
## White noise spectral density

The power spectrum at frequency $\lambda \in [-\pi,\pi]$ can be obtained by taking the Fourier transform of the _autocovariances_ $\gamma(\tau)$ of orders $\tau=-\infty,...,-1,0,1,...\infty$:

$$
f(\lambda) = \frac{1}{2\pi} \sum_{\tau=-\infty}^\infty \gamma(\tau) e^{-i\lambda\tau} \,.
$$
```

![image](https://user-images.githubusercontent.com/8355965/45230973-317b5080-b290-11e8-9575-211f493cbc3f.png)

### Versions

- Mark Text: v0.12.25
- OS: MacOS high-sierra

**Comment by josephscade** [comment]
Same issue here on Ubuntu GNU/Linux.
Maybe there is a problem with the function `displayMath`...

**Comment by Jocs** [comment]
@amirhosseindavoody I have encountered this problem, but I don’t know how to solve it. So help is wanted.
