### ISSUE TITLE
Status on muya separation

### ISSUE THREAD

**Issue by samiralajmovic** [marktext/marktext#491]
What is status on muya separation (any ongoing effort?) and how can I help?

**Comment by Jocs** [comment]
@samiralajmovic At present, the development of marktext and the separation of muya are in sync, and I am also thinking about whether I need to rewrite muya in `typescript`. Of course, the cost will be relatively large. There are follow-up progress, I will inform you in this issue.

**Comment by Jocs** [comment]
@samiralajmovic Muya is developed in this repo https://github.com/marktext/muya, I'll close this issue now, If YOU want to help develop, you can go to look into that repo, thanks. any issue or question you can raise in that reop.
