### ISSUE TITLE
marktext在win上面ctrl+z和撤销功能丢失或非常不灵活

### ISSUE THREAD

**Issue by yanzzchn** [marktext/marktext#500]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text:
- OS:

**Comment by Jocs** [comment]
和 #311 重复
