### ISSUE TITLE
Split view (dual panel view)

### ISSUE THREAD

**Issue by sbstn87** [marktext/marktext#502]
### Description

Would it be possible to introduce a split view fin the Mark Text? What I mean is a view where the screen is split in two, where you can see both the source (with syntax highlighting) and the rendered text at the same time.

It should look like this:
https://4bds6hergc-flywheel.netdna-ssl.com/wp-content/uploads/2016/10/Remarkable-Interface.png

Best regards,
Sebastian

**Comment by Jocs** [comment]
@sbstn87 we will add  a preview viewer on the right, when you are in the source code mode.
