### ISSUE TITLE
Additional markdown functionality

### ISSUE THREAD

**Issue by sbstn87** [marktext/marktext#504]
Hi guys,

I have found something like this:
https://mdp.tylingsoft.com/

It seems that this markdown editor has a very rich formatting capabilities
- footnotes
- fontawesome
- subscripts and superscripts
- maring
- and many more

How much of those will you be able/willing to implement in Mark Text?

Best regards,
Sebastian

**Comment by Jocs** [comment]
* [x] footnotes
* [ ] fontawesome
* [x] subscripts and superscripts
* [ ] maring

and chart and flowchart will be implement,  and so on.
