### ISSUE TITLE
Import dialog disappears

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#509]
### Description

Drag and dropping a markdown file into Mark Text makes the import dialog disappear after a few seconds and appear if you move the mouse.

In addition the import dialog image is missing. I guess invalid image path.

### Steps to reproduce

1. drag and drop markdown file
2. don't move the mouse -> dialog disappears
3. move the mouse -> dialog appears again

**Expected behavior:** [What you expected to happen]

The dialog should stay visible like the image upload dialog.

**Actual behavior:** [What actually happened]

see *Description*

![mt_drag_drop_box](https://user-images.githubusercontent.com/22716132/46916921-4b136480-cfc1-11e8-96a6-ecedd04ddf74.png)

### Versions

- Mark Text: v0.13.43 (pre-release)

**Comment by Jocs** [comment]
The dialog will disappear after you drop the file or when you drag out of window. it indeed this way.

**Comment by fxha** [comment]
It sound a bit odd but I can only reproduce the issue on Linux (both X11 and Wayland). If I don't move the cursor the dialog disappear and appear when I move my cursor again.

Sorry for the bad image quality 😄 

![mt_dialog](https://user-images.githubusercontent.com/22716132/47041168-64b2d880-d188-11e8-87ae-8fc9b01414ac.gif)

**Comment by fxha** [comment]
I have discovered that the following line is translated to `/static/sprite.svg#import_file-usage` which don't exists in the packaged application:

https://github.com/marktext/marktext/blob/c004b7300d250a2258aa3841eb9e11554abcd1dc/src/renderer/components/import/index.vue#L39

The file exists in `dist/electron` directory. I think it's a `webpack` problem but I am not familiar with it. Could you please change the path from `import_file.svg` to `/static` instead of `/dist/electron/static`.

**Comment by Jocs** [comment]
>Import dialog disappears

Do you mean the `import icon` disappears?

**Comment by Jocs** [comment]
sure, I'll fix it.
