### ISSUE TITLE
Windows defender warning

### ISSUE THREAD

**Issue by hjoensson** [marktext/marktext#51]
I downloaded and started the latest version for Windows just now, 0.7.17. I have not installed Marktext before.

Windows Defender complained that it was unsafe to install this. Have anyone more seen this?
(It doesn't feel good to click on "Run anyway"...)

Regards
Henrik

**Comment by SuperSandro2000** [comment]
When I opened the installer for the first time it showed me the same annoying smart screen alert. Common for self compiled installers. About the trust: You need to decide that yourself or compile from source.
