### ISSUE TITLE
Multiple pdf exporting bugs

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#510]
### Description

1. Exported code blocks are not highlighted as code blocks. The text background is gray only (image 1).
2. The black background disappears if you export in dark theme (image 2).
3. Exporting a pdf document several times in succession will export the markdown document several times (image 2). If you have a markdown document `a`, it get exported as `a` the first time then `a\na` then `a\na\na` etc.

### Steps to reproduce

Example code (replace ` \``` ` with  ` ``` `):

```markdown
foo

\```
if (foo) {
  !bar
}
\```

bar
```

see *Description*

**Expected behavior:** [What you expected to happen]

1. Code blocks are represented as code blocks - like in the HTMl document.
2. Either black background or black font color.
3. The document should be exported once

**Actual behavior:** [What actually happened]

image 1:

![mt_pdf_export](https://user-images.githubusercontent.com/22716132/46917041-c6294a80-cfc2-11e8-94f7-c4b37d3999c5.png)

image 2:

![mt_pdf_export_dark](https://user-images.githubusercontent.com/22716132/46917046-caedfe80-cfc2-11e8-97eb-e5a6837afbae.png)

### Versions

- Mark Text: v0.13.43 (pre-release)

**Comment by Jocs** [comment]
>Exported code blocks are not highlighted as code blocks. The text background is gray only (image 1).

Yes, the highlight disappeared. I'll fix it.


>The black background disappears if you export in dark theme (image 2).

I have rewrite PDF export, it will export only the `github theme` in both editor theme, but we can add more export theme in the future, not only the `github theme`.

>Exporting a pdf document several times in succession will export the markdown document several times (image 2). If you have a markdown document a, it get exported as a the first time then a\na then a\na\na etc.

👍 It's a problem, I'll fix it.
