### ISSUE TITLE
[prismjs] `<%text%>` is not displayed properly

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#517]
### Description

`<*>` is not displayed correctly, where `*` is an arbitrary string without spaces. The bug is not reproducible on `https://prismjs.com/test.html`.

### Steps to reproduce

**Example 1:**

```cpp
#include <iostream>
#include "header.hpp"

template<typename T>
class Foo {
public:
    Foo();
};

template<typename T>
Foo<T>::Foo() {}

template<typename T>
T a() {
  return 0;
}

int main()
{
    Foo<int> bar;

    int i = 1;
    i <<= 1 && 6 >> 2;

    // --> <b> <--
    // --> <<b>> <--

    std::cout << (1 << (1 && (6 >> 2))) << "\n";

    return i;
}
```

**Example 2:**

```
<a>
```

**Expected behavior:** [What you expected to happen]

see `Steps to reproduce`

**Actual behavior:** [What actually happened]

![mt_codeblock_bug](https://user-images.githubusercontent.com/22716132/47366128-4d6e7080-d6dd-11e8-8b96-21fe1242d3ef.png)

### Versions

- Mark Text: master 39e1ea8

---

Edit: Code highlighting is not available with the standalone application - non `npm run dev`.

**Comment by Jocs** [comment]
@fxha That's strange, the `<%text%>` disappeared. I'll fixed it.

>  Code highlighting is not available with the standalone application 

Do you mean the highlighting is not available after run `npm build`?

**Comment by fxha** [comment]
> Do you mean the highlighting is not available after run npm build?

Yes, that's right.
