### ISSUE TITLE
[Enhancement] add logger and kill process after error

### ISSUE THREAD

**Issue by SuperSandro2000** [marktext/marktext#52]
To better track down errors you should implement a better logger for such crashes and make sure the marktext processes are killed.

![](https://i.imgur.com/XgXQMKM.png)
![](https://i.imgur.com/eMj5YW5.png)
I think you need a Windows PC or a good VM.

**Comment by Jocs** [comment]
@SuperSandro2000 AutoSave is still under development, How did this error happen?

**Comment by SuperSandro2000** [comment]
Open MarkText. I will do a PR when I am done with fixing stuff

You should think about adding a proper logger to handle such problems. Unpacking the asar, finding the line and finding something to search for in code is annoying!

**Comment by SuperSandro2000** [comment]
I would be really happy if you may use a different branch for heavily wip stuff that does not compile or work at all and break other stuff. I just wanted to try the other PR if the windows functionality would break and now I need to fix a whole bunch of stuff.

**Comment by SuperSandro2000** [comment]
@Jocs and another Bug I found related to this one. The process is not killed after pressing ok. Very annoying too.

**Comment by SuperSandro2000** [comment]
#53 fixes 2 of 3 startup crashes

**Comment by Jocs** [comment]
I am still working on auto save and user preferences, I maybe create a dev branch, not push directly to the master.

**Comment by SuperSandro2000** [comment]
This would be awesome! I think it is always a good practice to keep the master branch at least compilable that the program won't crash on startup.
