### ISSUE TITLE
Typewriter Mode 回车时滚动条大幅跳动影响写作体验

### ISSUE THREAD

**Issue by atai-doul** [marktext/marktext#520]
### Description

Typewriter Mode 下，在已经输入了超过一屏文字时回车换行时，滚动条老是跑到上面去了，窗口模式看不到正在写的那一行，全屏时文字内容老是上下跳动。非常影响写作体验。

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. 书写
2. 回车

### Versions

- Mark Text:v 0.13.50
- Operating system:macOS 10.14.1 Beta (18B67a)

**Comment by MrHeer** [comment]
@Jocs I'm very like this mode and I want to fix it, Can you reopen this issue?

**Comment by Jocs** [comment]
@MrHeer reopened.
