### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#521]
### Description

Since the latest version of Marktext (v 0.13.50), word wrapping does not work anymore

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Type a lot of words e.g.
`The cat (Felis catus, or Felis silvestris catus, literally "woodland cat"), often referred to as the domestic cat to distinguish from other felids and felines, is a small, typically furry, carnivorous mammal. It is often called house cat`

**Expected behavior:**

That words stay together and only spaces turn into line-breaks.
```
blablabla 
distinguish 
blabla
```

**Actual behavior:**

A word get broken right in the middle. e.g.

```
blablabla distin
guish blabla
```

### Versions

- Mark Text: v 0.13.50
- Operating system: Windows 10

**Comment by stefnotch** [comment]
Sure! Here you go, a screenshot:

![image](https://user-images.githubusercontent.com/10220080/47506501-7a9f5800-d870-11e8-95b0-31281ac5db8e.png)

The text is simply:
```
MarkText MarkText MarkText MarkText MarkText MarkText MarkText MarkText
```

As you can see, the line break is in the middle of a word.

**Comment by Jocs** [comment]
Yeh, I think it's a style error, PR is also welcomed!
