### ISSUE TITLE
Paste after last line

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#522]
### Description

Pasting text does not work under certain circumstances.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Open Marktext (new file)
2. Hit Enter (`\n`) 5 times 
3. Try to paste the following (unformatted) text: Amazing text

**Expected behavior:**

That the text gets pasted

**Actual behavior:**

Nothing happens

### Versions

- Mark Text: v 0.13.50
- Operating system: Windows 10

**Comment by fxha** [comment]
@stefnotch Does `Ctrl+Alt+S` (switch to source code mode) work for you on Windows? On my Windows machine it doesn't but on Linux it "just works".

**Comment by stefnotch** [comment]
@fxha `Ctrl+Alt+S` doesn't seem to work for me on Windows.

**Comment by fxha** [comment]
@stefnotch I guess default German keyboard layout (de-DE)?

**Comment by fxha** [comment]
I think that the keyboard binding issues are electron issues because I have the same problem on Linux when launching the Windows application with wine. Electron has many open issues regarding this topic. When I have some time I'll hopefully can solve the problem. Maybe handle shortcuts by our self or somehow different...

**Comment by stefnotch** [comment]
@fxha About handling shortcuts in Electron, you could reasonably quickly hack together something with a simple library like:
https://www.npmjs.com/package/mousetrap
https://github.com/matthewshirley/node-iohook
https://github.com/matthewshirley/node-mousetrap

**Comment by Jocs** [comment]
@stefnotch Thanks, the has issue has been fixed, we'll release a hotfix version these days.

**Comment by fxha** [comment]
> About handling shortcuts in Electron, you could reasonably quickly hack together something with a simple library like

Yes, I'll definitive take a look at these resources.

As regards the `Ctrl+Alt+S` issue, it's a electron v3 bug. I can reproduce it with a simple application on Windows and I'll report it later.
