### ISSUE TITLE
What chart.js Supporting?

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#524]
### Describe your feature request

Those who told me to support `tui.chart`, do you think about supporting `chart.js`?

**Comment by Jocs** [comment]
What `cahrt.js` ? Can you give me a link?

**Comment by keito940** [comment]
[this.](http://www.chartjs.org/docs/latest/)

**Comment by Jocs** [comment]
* [chart.js](https://github.com/chartjs/Chart.js)

* [tui.chart](https://github.com/nhnent/tui.chart)

* [vega-lite](https://vega.github.io/vega-lite/)

* [vega](https://vega.github.io/vega/examples/)

I also found vega-lite and vega!

**Comment by keito940** [comment]
How about Vega-Lite?
Unlike tui.chart, vega and chart.js, it is easy to have JSON or CSV knowledge
Being able to make a diagram and compatibility with Mark Text is good,
I think Vega-Lite would be nice.

Also, I made a text system that can describe Chart Graphic on CSV Base by [Tui.Editor](https://github.com/nhnent/tui.editor/wiki/Extensions).
Because troublesome parts and so on will be adjusted on Vega-Lite side.

~~~markdown
```vega-lite
a,b
C,2
C,7
C,4
D,1
D,3
D,6
E,8
E,4
E,7

mark,bar
x.field,date
x.type,nominal
y.aggregate,average
y.field.b
y.type,quantitative
```
~~~



Graph Source By [Introduction to Vega-Lite](https://vega.github.io/vega-lite/tutorials/getting_started.html).
