### ISSUE TITLE
Wrapping words split them in the middle

### ISSUE THREAD

**Issue by chmike** [marktext/marktext#532]
### Description

Typing a line that wraps result in word cut in the middle and continue on next line.

- [ ] Can you reproduce the issue? 
yes: `[x]`

### Steps to reproduce

Type text that is longer than a horizontal line and that wraps. 

**Expected behavior:**

Line should wrap between words at spaces.

**Actual behavior:**

The last word is cut in the middle and resume on next line. 

**Link to an example: [optional]**

![capture-20181030102700-702x57](https://user-images.githubusercontent.com/235856/47708553-98810a00-dc2e-11e8-9371-591ef6ba8feb.png)

### Versions

- Mark Text: 0.13.50
- Operating system: Linux (Ubuntu)

**Comment by chmike** [comment]
Other example :

![image](https://user-images.githubusercontent.com/235856/47709000-a5522d80-dc2f-11e8-83cd-d2363b080883.png)

Source code of the above example:

![image](https://user-images.githubusercontent.com/235856/47709032-bbf88480-dc2f-11e8-9f90-842ba8a8c779.png)

**Comment by fxha** [comment]
The issue has been fixed in v0.13.53.
