### ISSUE TITLE
Show vertical table grid lines as white in dark mode

### ISSUE THREAD

**Issue by kibiz0r** [marktext/marktext#537]
### Describe your feature request

It's impossible to see the vertical table grid lines when you're in dark mode. Presumably, it's because they are still rendered as gray? The monitor I'm on right now sucks, so it's hard to tell.

### What problem does this feature solve? [optional]

Being able to see table grid lines when you're in dark mode.

**Comment by Jocs** [comment]
@kibiz0r Do you mean the vertical line of table cell?

**Comment by kibiz0r** [comment]
Yes, only the vertical lines are invisible or at least hard to see. The even/odd horizontal striping shows up fine. Edited to clarify.
