### ISSUE TITLE
Allow moving/dragging table cells

### ISSUE THREAD

**Issue by kibiz0r** [marktext/marktext#538]
### Describe your feature request

When working with a table where I want to select a range of cells and move just those cells, there's no easy way to do that.

I'd like to be able to select a set of cells, then drag them around in a table to change their row/column indices.

### What problem does this feature solve? [optional]

For example, I had a situation today where I wanted to add one cell to one column of a table without shifting any of the cells of the other columns. I basically just had to do cut-paste over and over.

Another way of solving my problem would be the ability to insert a single cell and shift the rest of the cells in its row/column to the right/down.

**Comment by fxha** [comment]
Thanks @kibiz0r, this has been already discussed - see #32.

@Jocs Do you plan this feature still post v1.0?

**Comment by kibiz0r** [comment]
I did see that, but I interpreted that request as being able to reorder rows and columns, not discrete cells. But if that's the intention, then yeah dupe this. :+1:

**Comment by OverShifted** [comment]
@Jocs Can I ask what happened to this feature request?
