### ISSUE TITLE
Theme setting is not being saved

### ISSUE THREAD

**Issue by acostalima** [marktext/marktext#54]
### Description

I changed my theme setting to dark and after I restarted Mark Text the theme setting switched back to white. This is a bit annoying because I always have to change the theme whenever I open Mark Text. 

### Steps to reproduce

1. Click on the hamburguer menu on the top left corner
2. Go to "Theme"
3. Select "Dark"
4. Restart Mark Text

**Expected behavior:**

Theme setting is persisted after restart.

**Actual behavior:**

Theme setting is not persisted after restart.

### Versions

- Mark Text: 0.7.17
- OS: Windows 10 Version 1709 Build 16299.309

**Comment by fxha** [comment]
The current version don't save settings at exit. Preferences are work in progress and should be supported in the next version.

**Comment by SuperSandro2000** [comment]
Dupe with that https://github.com/marktext/marktext/issues/16

**Comment by acostalima** [comment]
@SuperSandro2000 my bad then. I guess we can close this.
