### ISSUE TITLE
Redo doesn't work

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#542]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Write a few lines
2. Press undo two or three times
3. Press redo

Please note: You have to use the menu to undo/redo on Linux and Windows without the keybinding fix - which is not yet published.

**Expected behavior:**

Restore the last line.

**Actual behavior:**

Redo doesn't work.

### Versions

- Mark Text: master f3198ae
- Operating system: Linux and Windows

@Jocs Can you confirm the issue on macOS?

**Comment by Jocs** [comment]
That's strange, I did nothing about the `history` at this commit, and I test it on may Mac, it works well.

**Comment by fxha** [comment]
>  I did nothing about the history at this commit

I tested the issue with commit f3198ae. The issue may be somewhere else.

**Comment by fxha** [comment]
I guess it's a problem with the limited undo/redo stack. I noticed that I have to press `Ctrl+Z` two times at the position where it's impossible to restore more operations. I'm closing the issue because we will change the stack implementation soon. 

![mt_redo](https://user-images.githubusercontent.com/22716132/48026367-26388a00-e146-11e8-80c8-e32753d0381b.gif)

**Comment by NickG13** [comment]
It still doesn't work...

**Comment by hitriyvalenok** [comment]
Confirm. Doesn't work. Almost 2022 :(
