### ISSUE TITLE
Delete in front of a code block

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#544]
### Description

When the user presses `Del` and the cursor is in front of a code block, the contents of the code block will get moved out of the code block

- [x] Can you reproduce the issue? 

### Steps to reproduce

    CURSOR AT THE END AND DELETE |
    ```
    aaaaaaah
    ```

1. Paste the above into MarkText
2. Place the cursor at the end of the first line
3. Press delete

**Expected behavior:**

**Actual behavior:**

    CURSOR AT THE END AND DELETE |aaaaaaah

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.53
- Operating system: Windows 10

**Comment by stefnotch** [comment]
I'm not entirely sure. Some options:
- the backticks \`\`\` could get deleted 
- nothing should happen

**Comment by Jocs** [comment]
@stefnotch What about this:

```markdown
for bar<cursor>
\```javascript
const a = 'ddd'
\```
```

after press `Del`

```markdown
for barcosnt a = 'ddd'
```

And the code block deleted, and codes are appended after the previous text, If the code block more that one line, Nothing happen, and do not delete the code block.

**Comment by stefnotch** [comment]
@Jocs Sounds good! 👍
