### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#545]
### Description

Code blocks are not highlighted when you load a document or insert a code block in source code mode.

- [x] Can you reproduce the issue? 

### Steps to reproduce

```markdown
foo

\```json
{
  "key1": "value",
  "key2": "value"
}
\```

bar

```

1. Insert the code sample without `\` in source code mode
2. Place the cursor not in the code block
3. Switch to preview mode

**Expected behavior:**

Code is highlighted.

**Actual behavior:**

Code is not highlighted.

**Link to an example: [optional]**

### Versions

- Mark Text: v0.13.53 and master

**Comment by Jocs** [comment]
@fxha The reason for this problem is that when switching from source mode to preview mode, this time it will load the code needed for highlighting. This is an asynchronous process, but this time you need to render the code block, but the asynchronous code has not returned.  thus causing the highlight to fail.

**Comment by Jocs** [comment]
This problem is put first, because if you want to fix this problem, you need to wait for the highlight code to complete, then re-render the required code block, Because we'll refactor the underlying design, maybe this problem will be solved naturally.

**Comment by fxha** [comment]
BTW syntax highlighting for [markup languages](https://prismjs.com/examples.html#language-markup) like HTML or XML does not work. It seems you have to set special class names.

**Comment by Jocs** [comment]
<img width="930" alt="2018-11-13 11 32 50" src="https://user-images.githubusercontent.com/9712830/48423870-75ad3480-e79c-11e8-8a72-ab14619d5158.png">

@fxha I just test the html block, it works?

**Comment by fxha** [comment]
@Jocs  Do you mean the HTML block? I'm talking about the code block and there isn't a `html` or `xml` entry.

![mt_code_block_html](https://user-images.githubusercontent.com/22716132/48428495-6feb2b00-e76b-11e8-933d-fec502c01a65.png)

**Comment by Jocs** [comment]
@fxha This is a problem, because prism does not has a `html` language, it use the name of `markup`.

**Comment by fxha** [comment]
Can we create an alias for `html`, `svg` and `xml`?

**Comment by Jocs** [comment]
I think we can, I'll have a try.
