### ISSUE TITLE
Cannot export PDF in Source Code mode

### ISSUE THREAD

**Issue by yanzijun** [marktext/marktext#55]
### Description
I use mark-text with downloading Linux AppImage file. I am using Unbuntu 16.04, and I open a new file to write something. If I enable `View` -> `Source Code` setting, I can't export file as PDF.

[Description of the bug or feature]
Can't export file as PDF when enable `source code` setting in view.

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
When I click `export` as `PDF` , should open a window ask me store the file in where. 

**Actual behavior:** [What actually happened]
Nothing happened after I clicked `export` as `PDF`.

### Versions

- Mark Text: Linux latest version
- OS: Ubuntu 16.04.4 LTS (Xenial Xerus)

**Comment by Jocs** [comment]
@yanzijun the issue will be fixed in the next release version.

**Comment by yanzijun** [comment]
@Jocs  Thanks.
