### ISSUE TITLE
Pasting XML

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#552]
### Description
`<artifactId>derbyclient</artifactId>`

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Copy the following text `<artifactId>derbyclient</artifactId>`
2. Paste it into MarkText 
3. It will be HTML and you can't change it. You can't put backticks ` before and after it. You can't hit enter when the cursor is at the end of the text. 

**Expected behavior:**
That the pasted text initially is HTML, but after wrapping it in backticks `, it should get parsed as normal code. And pasting it into something like this should work flawlessly.
```
`paste the HTML here`
```

**Actual behavior:**
It gets interpreted as HTML and you can't do a thing about it.

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.53
- Operating system: Windows 10

**Comment by fxha** [comment]
Thanks @stefnotch, there is definitely a problem. I tested it with the following example: https://www.w3schools.com/xml/note.xml.

**Comment by Jocs** [comment]
@stefnotch Can you still reproduce this issue on the latest version?

**Comment by fxha** [comment]
Fixed on latest master.

**Comment by stefnotch** [comment]
Fixed. 👍
