### ISSUE TITLE
Paste text with \n into code block language

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#553]
### Description
You can paste text into the language field of a code block. This works as intended. (e.g. `java`) However, you can also paste text with line breaks `\n` into the language field of a code block.

- [x] Can you reproduce the issue? 

### Steps to reproduce

    ```java
    this is a code block
    ```

1. Create a code block
2. Set it's language to java  
3. Copy some long text with line breaks

long
text 
with 
line breaks

4. Put your cursor in the language field of the code block `jav|a`
5. Paste the text you just copied

**Expected behavior:**
Not sure.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/10220080/48314428-b0ab3e80-e5c9-11e8-95fe-8facead08a6b.png)

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.53
- Operating system: Windows 10

**Comment by Jocs** [comment]
>Put your cursor in the language field of the code block jav|a

Why do you want to paste text into the language input filed? not in the code block below language input?

**Comment by stefnotch** [comment]
Well, it was an accident. However, as the outcome was rather unexpected (see picture), I decided to report it.

**Comment by Jocs** [comment]
That's a solution, PR is welcomed.
