### ISSUE TITLE
Cannot insert multiple empty lines in a fenced code block

### ISSUE THREAD

**Issue by netvl** [marktext/marktext#558]
### Description

Pressing return in a fenced code block does not work on its own line, i.e. you cannot insert multiple empty lines when typing.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a fenced code block.
2. Press return multiple times inside the code block.

**Expected behavior:**

Multiple empty lines are inserted.

**Actual behavior:**

Only one empty line is inserted. Further presses of the return key do nothing.

**Link to an example: [optional]**

### Versions

- Mark Text: 0.13.53 (latest in homebrew)
- Operating system: macOS High Sierra

**Comment by Jocs** [comment]
We have restricted the input of multiple lines of blank lines, and input a maximum of one blank line. Why do you need to enter multiple blank lines?

**Comment by mudassirzulfiqar** [comment]
Thats good

**Comment by netvl** [comment]
@Jocs because I want to format the code as I want. Suppose I want to write two lines of code which are one-line function definitions:
```scala
def something: String = "a"

def somethingElse: String = "b"
```
Currently to do this, I have to do nontrivial things, like typing the entire code block in one piece and then splitting it into multiple "paragraphs" afterwards. This disrupts the flow *immensely*.

**Comment by Jocs** [comment]
>I wonder why there is such a restriction at all?

Initially it was only in the HTML block, because if there is are empty line in the HTML block, which will cause the markdown parser to parse error, but the HMTL block and the Code Block share a component, so the Code Block also imposes this restriction. It seems that this is indeed a problem. We will fix it later.
