### ISSUE TITLE
Missing preferences menu

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#56]
The "Marktext" application menu is not shown on OSs other than OSX. Maybe we could move the preferences entry into file or edit menu, so that you can edit preferences on Linux and Windows?

### Versions

- Mark Text: latest
- OS: not OSX

**Comment by Jocs** [comment]
@fxha Does use `Ctrl + ,` shortcut work ?

**Comment by fxha** [comment]
I don't think so, because see [here](https://github.com/marktext/marktext/blob/9e89a653fbf737044f34efdd9758d03c75fe4239/src/main/menus/index.js#L14).

**Comment by Jocs** [comment]
@fxha Aha, I forget I just add Mart Text menu to OS X system, Because I only have Mac OS X system, So I can not test whether it is work when add Mark Text menu to other system.

If it not work, Add preference menu item to file menu in Windows and Linux systems.

```javascript
if (platform !== 'darwin') {
    // add preferences to file menu
}
```

Can you fix this problem?

![](https://i.loli.net/2018/03/22/5ab3bdf4bf012.jpg)

**Comment by fxha** [comment]
Only preferences and quit works. Is that correct?

![mt_menu](https://user-images.githubusercontent.com/22716132/37778459-479a88de-2dea-11e8-8099-bc19716d28c9.png)

Edit: My theme hides menu separators.

**Comment by Jocs** [comment]
Can you hide `About Mark Text`, `Services`, `Hide Mark Text`, `Hide Others`, `Show All` menu items when Mart Text in Windows and Linux ? or other idea?

**Comment by fxha** [comment]
Btw. what does `Services` do? For `About Mark Text` we could display a message box and hide the others or add  `preferences` and `quit` to file and `check for updates` to help.

Can you send me a screenshot from `about` dialog?

**Comment by Jocs** [comment]
![1521732701833](https://user-images.githubusercontent.com/9712830/37780223-465544d4-2e29-11e8-86ed-aabf6170505f.jpg)

Just like this.

Many Apps in Mac, have a `APP name` menu, and have `about`, `services`, `quit`, 'check for update' etc, in this menu. But I don't know how to display these menu item in Windows or Linux.

**Comment by Jocs** [comment]
@fxha But I think when user click `About...`, show them a message box in the render process. this is a good idea. and not use this build in message box.

**Comment by fxha** [comment]
![mt_dd](https://user-images.githubusercontent.com/22716132/37785452-795d71d2-2dfa-11e8-935b-1fed72684d38.png)

![mt_about](https://user-images.githubusercontent.com/22716132/37785451-792ff040-2dfa-11e8-8920-2f6f5a07f6d2.png)

I have problems with the icon/information, but I will check that on Windows. Maybe replace the message box with a custom design (#58).

**Comment by Jocs** [comment]
@fxha I prefer use dialog in [element-ui](https://github.com/ElemeFE/element) to show the `About` info. just like this. Because Mark Text has already used it.

![about](https://user-images.githubusercontent.com/9712830/37786341-6e7ac084-2e37-11e8-8180-23b2b2e2a4a0.jpg)

**Comment by SuperSandro2000** [comment]
I would reorder it like:
Preferences
Check for updates
About mark text
