### ISSUE TITLE
Relative Image URL Broken

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#562]
### Description

MarkText saves (relative) image URLs in a rather incompatible way. e.g.
`![pictures\1\Cameras_in_Flax](pictures\1\Cameras_in_Flax.png)`
It also removes the alt-text.
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open MarkText
2. Type `![this text will be removed]()`
3. Use the file picker to select a relative image file
4. Save the document
5. Close MarkText
6. Open MarkText again
7. Image URLs are like that

**Expected behavior:**
`![The alt-text that I wrote 30 seconds ago](./pictures/1/Cameras_in_Flax.png)`

**Actual behavior:**

`![pictures\1\Cameras_in_Flax](pictures\1\Cameras_in_Flax.png)`
**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.53
- Operating system: Windows 10

**Comment by stefnotch** [comment]
Also, it might be a good idea to URL-encode the URLs.

**Comment by Jocs** [comment]
>it might be a good idea to URL-encode the URLs.

Do you mean encode image to `base64` ?

**Comment by stefnotch** [comment]
Sorry, I should have been clearer. What I meant is this:
```javascript
console.log(encodeURI("https://www.example.com/url/with freaking spaces.png"))

// > https://www.example.com/url/with%20freaking%20spaces.png
```
