### ISSUE TITLE
Using `tab` to move between table cells is broken

### ISSUE THREAD

**Issue by tmr232** [marktext/marktext#564]
### Description

Pressing `tab` in a table cell moves to the next cell, but then selects the cell showing the context menu, making it impossible to keep tabbing between cells.

- [X] Can you reproduce the issue?

### Steps to reproduce

1. Create a table with content
2. Place cursor in the first cell
3. Press `tab`
4. The next cell is now selected, with the context menu displayed
5. Press `tab` again

**Expected behavior:**

Cursor moves to the next cell

**Actual behavior:**

Nothing happens

### Versions

- Mark Text: v 0.13.53
- Operating system: Ubuntu 14.04

**Comment by Jocs** [comment]
Thanks, it's a problem, do you need to select the next cell's content when you press tab?

**Comment by tmr232** [comment]
No, I just want to move between tabs.
also, this seems to happen when just selecting text. If I select text on a single line, the context-menu pops up. Then if I press either `tab` or `return` they are ignored.

**Comment by fxha** [comment]
@Jocs The problem is that the format box receive to focus and we cannot longer `tab` to the next cell.

**Comment by Jocs** [comment]
@fxha maybe we don't need to selection the next cell's text, so the format box will not be shown? when you press `tab` just jump to the next cell at the offset 0.
