### ISSUE TITLE
Exception when removing a code block in a specific case

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#568]
### Description

Many exceptions when removing a code block in a specific case. The code block must be at the beginning of the document, other text may follow but the cursor have to be in the next line at index `0`.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a code block without language identifier and press `enter`. Cursor should be outside the code block.
2. Press `Ctrl+A` followed by `backspace`
3. See stack trace

**Link to an example: [optional]**

![mt_code_block_ctrl_a](https://user-images.githubusercontent.com/22716132/48790590-f8c81080-ecef-11e8-8515-d83269329ec9.gif)

**Expected:**

Cursor should jump into the code clock, like with language identifier, and no exceptions.

### Stack Trace

```
index.js?d47e:724 Uncaught TypeError: Cannot read property 'nodeType' of null /muya/lib/selection/index.js?d47e
    at getNodeAndOffset (index.js?d47e:724)
    at Selection.setCursorRange (index.js?d47e:745)
    at ContentState.setCursor (index.js?51a3:132)
    at ContentState.partialRender (index.js?51a3:171)
    at ContentState.inputHandler (inputCtrl.js?0fc2:122)
    at HTMLDivElement.inputHandler (keyboard.js?a29c:129)
```

### Versions

- Mark Text: master dd0cfb1 / v0.13.53
- Operating system: all

**Comment by Jocs** [comment]
@fxha i can not reproduce this issue again, can you reproduce it?

**Comment by fxha** [comment]
The issue seems to be fixed by the primsjs rebase.
