### ISSUE TITLE
Invalid language identifier when pressing enter

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#569]
### Description

Crash when you press `enter` after choosing a valid code block language identifier.

- [x] Can you reproduce the issue? 

Potential duplicate of #553.

### Steps to reproduce

1. Create a code block with a valid language identifier (e.g. `cpp`) and press enter. Cursor should be inside the code block.
2. Set cursor inside the language identifier (`cp<cursor>p`) and press `enter`
3. See stack trace

**Link to an example: [optional]**

![mt_code_block_enter](https://user-images.githubusercontent.com/22716132/48791015-ff0abc80-ecf0-11e8-9351-24b4672b45f5.gif)

### Stack Trace

```
index.js?51a3:417 Uncaught TypeError: Cannot read property 'key' of undefined /src/muya/lib/contentState/index.js
    at ContentState.insertAfter (index.js?51a3:417)
    at ContentState.enterHandler (enterCtrl.js?3dca:328)
    at HTMLDivElement.handler (keyboard.js?a29c:98)
```

### Versions

- Mark Text: master dd0cfb1 / v0.13.53
- Operating system: all

**Comment by Jocs** [comment]
I think we need to prevent the default enter behavior when the cursor is in the language input filed.

发自我的 iPhone
