### ISSUE TITLE
HTML Escaped characters invisible in list

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#571]
### Description
```
- 3 &lt; 5
```
![image](https://user-images.githubusercontent.com/10220080/48903448-dc48e700-ee5b-11e8-9236-ccc87012878e.png)

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a new list `-`
2. Type `3 &lt; 5`

**Expected behavior:**

That `&lt;` is visible as a `<`

**Actual behavior:**

`&lt;` is invisible 

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows 10

**Comment by Jocs** [comment]
@stefnotch fixed
