### ISSUE TITLE
(Using Ubuntu 18.04)  Remove column in table doesn't work; nothing happens.

### ISSUE THREAD

**Issue by CAtoDC** [marktext/marktext#572]
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text:
- Operating system:

**Comment by Jocs** [comment]
@fxha I test it on macOS, and it's work well, can you help test it on windows and Linux?

**Comment by Jocs** [comment]
@CAtoDC fixed, and not release.
