### ISSUE TITLE
Opening a file opens an entirely new instance of marktext

### ISSUE THREAD

**Issue by CAtoDC** [marktext/marktext#574]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

I expected the file would be opened in the existing instance of MarkText.
**Actual behavior:**

A separate instance of MarkText was opened with the new file.
**Link to an example: [optional]**

### Versions

- Mark Text:  0.13.65
- Operating system:  Ubuntu Liinux 18.04 (Chrome 70)

**Comment by fxha** [comment]
Thanks @CAtoDC, this behavior results from the very beginning where we didn't have tabs. I think this is a good idea to open the file as a new tab instead of opening a new window.

@Jocs What do you think?

**Comment by Jocs** [comment]
Add a user setting, `openFileInNewWindow`, the default value is `true`, if the setting is `false`, then open the file in a new tab page?

**Comment by CAtoDC** [comment]
That's a great idea.

Excellent work all around, by the way.

**Comment by CAtoDC** [comment]
Also:

Just so we're clear, I'm not really seeing a "tab" - just another instance
of the application. The "Untitled 1" application is what the application
started with - an empty screen.

Using File --> Open File results in the second instance of the application
(not a tab within the first instance).

[image: Screenshot at 14-46-27.png]

**Comment by fxha** [comment]
> Using File --> Open File results in the second instance of the application (not a tab within the first instance).

Yes, that's right. We haven't implement @Jocs suggestion yet. You can open a new tab with `File -> New Tab` or toggle the tabbar under `View -> Toggle Tab Bar`. At the moment you can only open tabs within the same directory (`File -> Open Folder` or `View -> Toggle Side Bar` and click the icon).

**Comment by CAtoDC** [comment]
Got it.  Thanks!

**Comment by RickyWong33** [comment]
quite useful if implemented

**Comment by fxha** [comment]
@CAtoDC @RickyWong33 We added a settings option `openFilesInNewWindow` to open files in a new window (`true`) or tab (`false`). I'm thinking about to add an option for folders as well in v0.15.x but first we need to refactor some code to implement this feature for folders.
