### ISSUE TITLE
Functional Brackets End Bracket Improvement

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#577]
### Describe your feature request
MarkText already has [Functional Bracket Auto-Completion](https://github.com/marktext/marktext/issues/414), however, the current implementation makes typing brackets and similar things (`**`)rather annoying.

When typing square brackets, the user usually types `[` `some letters` `]`. However, this ends up being `[some letters]]`, because of the functional brackets auto-completion. It would be great if typing the closing bracket wouldn't cause duplicated brackets.

### What problem does this feature solve? [optional]

Better functional brackets auto-completion

### Additional context [optional]

This already seems to work for the end brackets of links `[]()` (Last round bracket)

![image](https://user-images.githubusercontent.com/10220080/49039565-6c6e8f80-f1c0-11e8-9351-c2b6200ff267.png)
Also, a little suggestion: The auto-created closing bracket could be colored differently (light grey), to make it clear that typing it again will not duplicate a bracket.

**Comment by Jocs** [comment]
@stefnotch I think this is already fixed?

**Comment by stefnotch** [comment]
I can confirm that this is fixed. 👍
