### ISSUE TITLE
TODOLIST: Add rename (custom top dialog)

### ISSUE THREAD

**Issue by DXXL** [marktext/marktext#58]
### Description

*TODOLIST*: Add option to rename the file

Because electron's default dialog which is used for actions on the file is not capable of displaying a text field, a custom dialog is needed.

I have developed a custom top dialog inspired by macOS' dialog and tried to keep the minimalistic design of marktext. The dialog I created can not only be used to show rename dialog but can be used to create any custom dialog.
If you want changes to the design just comment, and I will implement them. That's why I first wanted to post an issue. I also still have to write tests for it. If you like I can then implement 'move to' as well.

**Link to an example:** You can have a look at it, in this fork (dev branch): [https://github.com/DXXL/marktext](https://github.com/DXXL/marktext)

**Comment by Jocs** [comment]
@DXXL thank you, I think a screenshot is better than the code.

Can you show me one screenshot of this top dialog.

**Comment by DXXL** [comment]
Of course, I can :)

No dialog is shown:
![nodialog](https://user-images.githubusercontent.com/14121906/37784825-fe21a44e-2df8-11e8-8c21-be4faa2d16ed.png)

Then the dialog animates in and disables the editor below.
![withdialog](https://user-images.githubusercontent.com/14121906/37784826-fe412526-2df8-11e8-980f-d3c82d73eeb6.png)

It has an animation which fades tile bar shadow and the background (which is then disabled). The dialog appears from under the title bar, similar to top dialogs in macOS. The dialog can have any contents: All possible dialogs are defined as extra components in a subfolder of TopDialog named "Dialogs", then you just need to ```commit('SHOW_TOP_DIALOG', 'Name of dialog to show')```.

**Comment by DXXL** [comment]
@Jocs You are right... 🤔 move to would require using the save dialog. But I thought we don‘t need to display the whole path dialog when only renaming files. It‘s your decision ;)

**Comment by DXXL** [comment]
Since the default save dialog and open dialog are displayed in a sperate windows anyway, they could use be used for those actions while using top dialog for other warnings or actions that just need a decision, without making a design break.

**Comment by DXXL** [comment]
I had some time to implement moveTo, that would look as follows:
<img width="1312" alt="screen shot 2018-03-22 at 21 37 45" src="https://user-images.githubusercontent.com/14121906/37797137-51236a68-2e19-11e8-94a1-dd1c9a8a3f19.png">

**Comment by SuperSandro2000** [comment]
I wouldn't recommend to use a custom save dialog on windows anyway.
Is a move to dialog really necessary? Save as is always an option and you could abuse it to rename the file too.

**Comment by Jocs** [comment]
@SuperSandro2000 `Save as...` like copy, and `Move to...` is cut operation.

**Comment by Jocs** [comment]
@DXXL I think  We can rename this file when open the `move to` dialog, if the path is not changed, it is a rename operation, if the path changed, it is a  move to operation. 

But, a custom `rename` dialog is also necessary when people click the file name in the title bar or click the rename menu item.

If you have time and a `move to` feature PR is welcomed.

thank you!

**Comment by DXXL** [comment]
That would be like that:

![screen shot 2018-03-23 at 08 26 32](https://user-images.githubusercontent.com/14121906/37816591-f0d39556-2e73-11e8-9a11-4907ab43fcff.png)

I will create a PR once I have the tests. Thanks for your advice ;)

**Comment by SuperSandro2000** [comment]
@Jocs oh yeah. Still think that a custom dialog will have problems acrros os's as we may need one for each system and then they are not consistent with the is or miss folders/features.

**Comment by DXXL** [comment]
Hey, I have everything ready now for your review. Before I make a PR: What about tests? Should they be added?

**Comment by Jocs** [comment]
You can add PR first, and add test latter...

So I can review the code first.
