### ISSUE TITLE
Quick Open File

### ISSUE THREAD

**Issue by Trudko** [marktext/marktext#581]
Is it possible to quickly open certain file in mark text? I am looking for file finder like functionality common in other text editors like visual code studio, atom or sublime text. I often find my self opening same files inside of my project / folder.

**Comment by fxha** [comment]
@Trudko Do you mean something like that?

![img](https://camo.githubusercontent.com/43c615153a5207d24d96dbb2c6c89a84fc64ce7c/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3637313337382f323234313435362f31303064623662382d396364332d313165332d396233612d3536396336623530636336302e706e67)

At the moment we only have recently opened files in the `File` menu and a sidebar (`View -> Toggle Side Bar`) where you can open a directory and multiple files.

![mt_img](https://user-images.githubusercontent.com/22716132/49181058-aa9db780-f356-11e8-9713-6f6068e38e79.png)

**Comment by Jocs** [comment]
@Trudko `Quick Open` is in our roadmap, stay tuned.

**Comment by dessalines** [comment]
This could draw a list of files from recently opened, and the current folder.

**Comment by fxha** [comment]
@Jocs Quick open command work successful with command palette:

![mt_command_palette](https://user-images.githubusercontent.com/22716132/66766867-71f3c780-eeaf-11e9-9035-cd99f8bd1425.gif)

**Comment by Jocs** [comment]
@fxha It's so cool, can't wait for it.
