### ISSUE TITLE
How to set the font of the window title

### ISSUE THREAD

**Issue by SeehopeHuang** [marktext/marktext#582]
I use your masterpiece :) on my Windows 10 operation system.
But it seems so uncomfortable for reading a title text of the software window with the default Chinese font called "Simsum", and is not harmonious compared with the default English font.(can't upload pictures here)
So, is there a way to set this font? Can it be changed to "Microsoft Yahei"?
Or if it's very complex for you to modify this, please ignore my question to do anything more important.
Thank you all for this work.

**Comment by Jocs** [comment]
>can't upload pictures here
<img width="686" alt="2018-11-29 3 50 55" src="https://user-images.githubusercontent.com/9712830/49206947-9b6a4880-f3ee-11e8-8acf-25fbef893e04.png">

>So, is there a way to set this font? Can it be changed to "Microsoft Yahei"?

U can set the font family in user setting.
