### ISSUE TITLE
Exporting a document with black theme activated produce a black document

### ISSUE THREAD

**Issue by madeindjs** [marktext/marktext#583]
### Description

Exporting a document with black theme activated produce a black document. See my export example :
[ererere.pdf](https://github.com/marktext/marktext/files/2628737/ererere.pdf)

### Steps to reproduce

1. Set setting "theme" to "dark"
2. Write someting
3. Export it as .pdf document

**Expected behavior:**

I think it should be cleaner with a white backround. Imagine ink cousumed if you want to print it on a paper..

**Actual behavior:**

See my export example :
[ererere.pdf](https://github.com/marktext/marktext/files/2628737/ererere.pdf)

### Versions

- Mark Text: 0.13.65
- Operating system: Ubuntu 18.10

**Comment by fxha** [comment]
This also applies to the light theme. The inner background has a different white color.

**Comment by Jocs** [comment]
@madeindjs Yes, it's really a bug, thanks for your report. we'll fixed it in the next release version.
