### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by CAtoDC** [marktext/marktext#585]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
Type this:  [Google](https://www.google.com)  
2. [Second step]

3. [and so on...]

**Expected behavior:**

I expected a hyperlink to be created.
**Actual behavior:**
Although the formatting is correct, the hyperlink does not work.

Nothing
**Link to an example: [optional]**

### Versions

- Mark Text:  0.13.65
- Operating system:  Windows 10 (and also Ubuntu 18.04); Chrome 70 for both operating systems

**Comment by CAtoDC** [comment]
![2018-11-28_hyperlink](https://user-images.githubusercontent.com/8337820/49241180-13c41000-f3d5-11e8-9343-a50254eca360.png)
![2018-11-28_hyperlink_syntax](https://user-images.githubusercontent.com/8337820/49241181-13c41000-f3d5-11e8-93c0-d2ede3c0a0cb.png)

**Comment by CAtoDC** [comment]
Didn't mean to close the issue previously. It's still a problem.

**Comment by Jocs** [comment]
@CAtoDC Can you explain more detail?

**Comment by CAtoDC** [comment]
When I create a hyperlink, like this:  [Google] (https://www.google.com)
the hyperlink will look right (i.e., the css will render), but the
hyperlink itself won't work.  It is not clickable.

**Comment by Jocs** [comment]
Yes，we'll add `clickable ` feature later.

**Comment by fxha** [comment]
This issue is being tracked in #425.
