### ISSUE TITLE
Inline Math foramt issue

### ISSUE THREAD

**Issue by littlecatheart** [marktext/marktext#593]
![image](https://user-images.githubusercontent.com/43427550/49447876-8c323300-f812-11e8-93c0-489cb7711c90.png)

**Comment by Jocs** [comment]
What's the markdown content of the math block?

**Comment by littlecatheart** [comment]
$\pi \rightarrow \mathbb{M}$

**Comment by littlecatheart** [comment]
Also you can see "3" in the equation is a little cut off
