### ISSUE TITLE
中文输入法下标题中数字和小数点的输入

### ISSUE THREAD

**Issue by shoujiaxin** [marktext/marktext#595]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. 切换到中文输入法
2. `# + 空格` 开始标题，标题以带小数点的数字为序，如 `1.2.3`
3. 先输入数字，再使用句号键输入小数点。此时第一个小数点会变成中文的句号，之后的小数点正常

**Expected behavior:**

`1.2.3`

**Actual behavior:**

`1。2.3`

**Link to an example: [optional]**

![](https://i.loli.net/2018/12/06/5c08e9bc3efaa.gif)

### Versions

- Mark Text: v 0.13.65
- Operating system: macOS 10.14.2

**Comment by Jocs** [comment]
@shoujiaxin 我刚才测试了，我这边是正常的，请问是什么输入法？

**Comment by shoujiaxin** [comment]
> @shoujiaxin 我刚才测试了，我这边是正常的，请问是什么输入法？

用的系统自带输入法，中文用的双拼，只有在 Mark Text 才会有这个问题，奇怪

**Comment by Jocs** [comment]
@shoujiaxin 我刚才用系统自带的输入法，也出现了一样的问题，换成搜狗输入法就好了。应该是输入法和Chrome 组合的坑，之后升级 Electron 可能会自动修复这个问题了。

**Comment by Jocs** [comment]
我将关闭这个问题，如果你有新的意见和想法，欢迎重新打开这个 issue。
