### ISSUE TITLE
Feature Request: Support for custom themes / better font settings 

### ISSUE THREAD

**Issue by AndyChen2005121** [marktext/marktext#600]
### Describe your feature request

**Add support for custom themes**, plus make the custom font selected in Prefrences be displayed **globally**.

### What problem does this feature solve? [optional]

1. Some of us are tired of the two dull themes.
2. Custom fonts settings doesn't affect code blocks & other possible locations.

### Additional context [optional]

I think this is not so hard - other editors such as Typora already had advanced theming support.

**Comment by fxha** [comment]
Thanks @AndyChen2005121 for you ideas and feedback. At the moment we focused  on basic features, improving functionality and stability. Also @Jocs rewrites `muya` (Mark Text backend) to improve compatibility, performance and usability - such as a high level API and documentation.

> Some of us are tired of the two dull themes.

This is a duplicate of #174 and #375 and was planned after v1.0 but I think it will be available with plugins or maybe with the new `muya` version. One possibility here would be to patch the `light.css` and/or `dark.css` in the [theme](https://github.com/marktext/marktext/tree/master/src/muya/themes) directory by yourself. The core issue is that not all styles are outsourced in these two files and we might break backward compatibility later.

> Custom fonts settings doesn't affect code blocks & other possible locations.

Duplicate of #373 and #467. I think I'll look into it.

We also have a lot of similar feature on our [roadmap](https://github.com/marktext/marktext/blob/master/.github/ROADMAP.md) for the next year, all contributions are welcome.

**Comment by AndyChen2005121** [comment]
thanks for you reply! 👍
