### ISSUE TITLE
Shift+Left in Hyperlinks selects one character at a time

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#601]
### Description

Same issues as https://github.com/marktext/marktext/issues/513 and https://github.com/marktext/marktext/issues/240 , however, this one is about text in hyperlinks `[this text right here](www.example.com)`
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a hyperlink `[this text right here](www.example.com)`
2. Follow the steps in the other issues

**Expected behavior:**

See other issues

**Actual behavior:**

See other issues

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows 10

**Comment by Jocs** [comment]
@fxha Does this issue only existed on Windows and Linux? I can not reproduce it.
