### ISSUE TITLE
UML diagrams using PlantUML as backend

### ISSUE THREAD

**Issue by mlopezgva** [marktext/marktext#603]
### Describe your feature request

UML diagrams like old StackEdit (with a hack) allowed to do, using [PlantUML](https://plantuml.com) syntax and parser. It seems that UML has been asked previously in #238 and #218.

There are other things to address, but it is so this request don't fall into oblivion...

### What problem does this feature solve?

Not a problem, but a hassle :wink: . The need to add static images and edit the diagrams outside the editor. since PlantUML is an almost standalone java program (it requires Graphviz/dot for some diagrams), and very easy to install and use, it would be very nice to use it. It outputs diagrams in PNG, SVG and, for sequence diagrams, even ASCII-art :smiley:.

#### PlantUML is a component that allows to quickly write:

- Sequence diagram
- Use Case diagram
- Class diagram
- Activity diagram
- Component diagram
- State diagram
- Object diagram
- Deployment diagram  (in beta, but it's functional)
- Timing diagram (in beta, but it's functional)

#### The following non-UML diagrams are also supported:

- Wireframe graphical interface
- Archimate diagram
- Specification and Description Language (SDL)
- Ditaa diagram
- Gantt diagram (it's in beta and I still prefer Mermaid, but mermaid lacks some features for Gantt diagrams PlauntUML already has)
- Mathematic with
  - AsciiMath (which I prefer over LaTeX, see [my issue for Remarkable](https://github.com/jamiemcg/Remarkable/issues/271)) or
  - JLaTeXMath notation

They have an endpoint for online use, but, like I said, it can be downloaded and used offline, which is one of the goal of MarkText.

### Additional context [optional]

The syntaax could be a codeblock with uml type:
```
    ```uml
    [optional @startuml]
    :Here the UML code;
    [optional @enduml]
    ```
```

**Comment by Jocs** [comment]
@mlopezgva We'll support mermaid, flowchart.js and [js-sequence-diagram](https://github.com/bramp/js-sequence-diagrams), vega-lite in the next version. Do you still need `PlantUML ` ?

**Comment by mlopezgva** [comment]
Vega is very good (a bit over-verbose to me, but that's from my own point of view).

Mermaid can produce tree and (admittedly) fairly good gantt diagrams, but with some glitches that diminishes the user experience. I hope they solve them (if thay still have them!).
flowchat.js is OK. However, I once need to use it and it has some bugs and I ended using PlauntUML SDL to render the diagram. js-sequence-diagram output does not look professional.

PlantUML covers all of them (maybe with the exception of the flowchart, but SDL diagram looks similar enough). It also has:
- [ERD](https://github.com/plantuml/plantuml/issues/31) (entity-relationship database diagram)
- [WBS](http://plantuml.com/en/wbs-diagram) (Work Breakdown Structure)
- [MindMaps](http://plantuml.com/en/mindmap-diagram)

Having ERD and WBS, at least for project documents, are more valuable, and since all other diagrams (wich are not covered by any of the aforementioned) are made with PlantUML, there is no need to have yet another resource.

But, if you don't feel like adding PlantUML as backend for diagrams, it is, after all, your project.

My thought was that, since this is a desktop program, IF the user has PlantUML, (s)he could *activate* the PlantUML feature and use his/her local PlantUML. Or even configure an endpoint (I have a dedicated virtual machine to render UML, MarkDown and AsciiDoc) such as plantuml.com and go for it. I made it using PHP and no TomCat at all... It is done with one call and the response can be saved to  a cache directory or injected directly to the output.

There is also the alternative to [use PlantUML with an FTP interface](http://plantuml.com/ftp). This allows sending many snippets (diagram sources) using `PUT` and get the images using `GET`, thus having just one call to / instance of PlantUML.

> NOTE
> I am moving to AsciiDoc, as it offers much more control and elements and PlantUML integration (AsciiDoctor, at least). But for non-demanding documents I still use MD and, because of the projects documentation, PlantUML.

**Comment by StoltHD** [comment]
D3.js and visjs (https://visjs.org/)  will be a good alternative...
Markvis is a markdown-it plugin, but last updated 2 years ago...

**Comment by Beurt** [comment]
>
> ```
>     ```uml
>     [optional @startuml]
>     :Here the UML code;
>     [optional @enduml]
>     ```
> ```

In the [Qownnotes](https://github.com/qownnotes) projects, there is [a plugin](https://github.com/qownnotes/scripts/tree/master/render-plantuml) doing that with mostly the same syntax:

```
    ```plantuml
    [optional @startuml or @startsomethingelse]
    some plantuml, or graphviz or whatever data
    [optional @enduml or @endsomethingelse]
    ```
```
The compatibility between the two editors would be very nice.
