### ISSUE TITLE
There is no more beautiy than marktext

### ISSUE THREAD

**Issue by Aecu** [marktext/marktext#612]
It is realy nice job, clean and neat.
i cannot love it no more!

By the way , i think we need a content or jump table to focus on what we want ,when the text becomes bigger and bigger ( of couse it can just because it is realy attractive ).

hope it can be a small semicircle hide on the left side, when Tab pressed or mouse move over, it can be expend to a list,

**Comment by Aecu** [comment]
i hope i can use Ctrl + V to paste a pic in the text, you can save the pic in the same folder with the text and with a default name

**Comment by Aecu** [comment]
i can create a folder , but i cannot delete one

**Comment by fxha** [comment]
> By the way , i think we need a content or jump table to focus on what we want ,when the text becomes bigger and bigger

He have already a table of contents side bar - `View -> Toggle Side Bar` and click on `H`.

> i hope i can use Ctrl + V to paste a pic in the text, you can save the pic in the same folder with the text and with a default name

This topic was already discussed in #97 and #433. We will add drag and drop and image pasting when we implemented #433.

> i can create a folder , but i cannot delete one

What do you mean? Do you talk about the sidebar?

**Comment by Aecu** [comment]
> What do you mean? Do you talk about the sidebar?

Ths for your reply, i mean when i open a folder with command open Folder(ctrl+Shift+o) , i will get a dir list, and i can create folder under a folder, but i did not find command delete it.  and if i rename a folder form other place, the folder list will cotain the folder before rename.  and sometime the software will break down.

**Comment by fxha** [comment]
> but i did not find command delete it

Have you tried `Move To Trash`?

> and if i rename a folder form other place, the folder list will cotain the folder before rename

Yes that's true, we don't listen for changes - may be an improvement.

**Comment by fxha** [comment]
@Aecu Please feel free to reopen the issue if necessary.
