### ISSUE TITLE
Optional Metadata

### ISSUE THREAD

**Issue by uroybd** [marktext/marktext#614]
Often we use markdown editor to write personal stuff or blog posts. Nowadays blogs are increasingly using markdown in their content writing widgets. Many static-site generator like Jekyll uses yaml metadata from post file to get idea of the content. It would've been an nice addition.

I propose a separate metadata menu to add meta content. It will keep the awesome writing experience intact. Metadata will be added in the beginning of the file only if user provides any. Else it will be like a simple Markdown file.

P.S. I'm familiar with the technologies you're working on. If you agree to add feature like this, I would like to contribute.

**Comment by Jocs** [comment]
<img width="1156" alt="2018-12-17 6 41 58" src="https://user-images.githubusercontent.com/9712830/50082267-7a498a80-022b-11e9-9b96-ac1450b31e5e.png">

Do you mean this?menu -> paragraph ->yaml front matter

**Comment by uroybd** [comment]
That may work too. But I was thinking about separate place in the sidebar for metadata which will keep the main editor section clean.

**Comment by Jocs** [comment]
@uroybd But there is a question, we store the edit content in a markdown file, not in json or other data structure. So where should I put the metadata?

**Comment by uroybd** [comment]
Well, that is not that hard.

If anyone adds metadata, we simply convert them to yaml and append them
into the beginning of the file.

And, on opening file, we can easily detect if metadata exists there. We can
parse and add them in our meta editor.

**Comment by balupton** [comment]
The SSG DocPad uses https://github.com/bevry/docmatter for the header extraction, perhaps it would be of use
