### ISSUE TITLE
Improvements for "Open Recent"

### ISSUE THREAD

**Issue by H16Y** [marktext/marktext#616]
### Describe your feature request

Currently, Mark Text only records files that are opened in it. But it does not record files that are created and saved. I have to open the saved file to add it into recent files. It will be better if recent files include saved files as well.

**Comment by Jocs** [comment]
how to record created or saved files?

**Comment by H16Y** [comment]
@Jocs Thanks for your response!
In my opinion, you may add files to the recent list right after they are successfully saved at a location.
