### ISSUE TITLE
Indent line by at least 4 spaces or 1 tab don't produce a code block in preview mode

### ISSUE THREAD

**Issue by Aecu** [marktext/marktext#617]
### Description

~~if i am not in the source code mode,  i can use tab to format my text.~~
~~when i switch to source code mode and then close it.~~
~~the new page will Render my simple text as code format. ~~

> Thanks @Aecu, it's the expected behavior.
> 
> > To produce a code block in Markdown, simply indent every line of the block by at least 4 spaces or 1 tab.
> 
> The actual problem is that the preview mode does not correspond to the standard.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Wirte a h4 title or some other title
2. follow a simple text as description, but with a tab at the beginning
~~3. open source code mode~~
~~4. close source code mode~~

**Expected behavior:**
h4 title
```
simple text
```

**Actual behavior:**
h4 title
[tab]simple text

### Versions
- Operating system: win7

**Comment by Aecu** [comment]
it always take a lot of time to reopen a new MT when i open another .md file even thought there was an MT opened already.  it was same as that when i want to use MT under Open Folder Mode

**Comment by fxha** [comment]
Thanks @Aecu, it's the expected behavior.

> To produce a code block in Markdown, simply indent every line of the block by at least 4 spaces or 1 tab.

The actual problem is that the preview mode does not correspond to the standard.
