### ISSUE TITLE
Aidou dialog background

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#62]
### Description

Aidou dialog background is not transparent and I cannot click on this area to hide the dialog. Even if I set the background is `none` or `transparent`.

### Steps to reproduce

Switch to dark theme and open aidou dialog.

**Expected behavior:**

Transparent background and I can easily hide the dialog.

**Actual behavior:**

![mt_not_clickable_area](https://user-images.githubusercontent.com/22716132/37822074-b572af9e-2e85-11e8-935e-69d3c11500e9.png)

### Versions

- Mark Text: latest
- OS: linux

**Comment by Jocs** [comment]
@fxha Are you saying that you cannot distinguish the colors of dialogs and modals? So you don't know where to click to hide the dialog？

**Comment by fxha** [comment]
@Jocs I mean, can you hide the dialog background (the big rectangle), because if you click on it the search box cannot be hidden?

**Comment by Jocs** [comment]
@fxha I think you should click outer of this big rectangle to hide this dialog. Do you like the `Aidou`? I feel Non-chinese users do not like this feature? So I want to hide it in user preferences. User can enable this feature by change the user preference.

**Comment by fxha** [comment]
@Jocs Good solution, no i don't use it.
