### ISSUE TITLE
怎么修改成中文？

### ISSUE THREAD

**Issue by huaimutou** [marktext/marktext#620]
### Question description

怎么修改成中文？？

**Comment by Jocs** [comment]
目前只有英文版的

**Comment by fxha** [comment]
Multi-language support is being tracked in #138.

**Comment by jiehuo666** [comment]
有中文版的吗

**Comment by feikeyan** [comment]
有点难啊

**Comment by lvhejin** [comment]
建议增加中文包

**Comment by rhl88** [comment]
不是说是中国人开发的么？没有中文？

**Comment by Woshiweizhuangzhezhier** [comment]
不是中国开发的

**Comment by wenpo1975** [comment]
直接下这个就行了
https://github.com/chinayangxiaowei/marktext-chinese-language-pack

**Comment by lvhejin** [comment]
中文版本下载地址：https://github.com/chinayangxiaowei/marktext-chinese-language-pack/releases
编译好的，下载即可使用
![image](https://user-images.githubusercontent.com/13688508/225069509-9344fd7d-8d42-4429-bd96-af271e6d4307.png)

![image](https://user-images.githubusercontent.com/13688508/225069845-605400f4-b4b7-4b20-bb39-cd54b94c117e.png)
