### ISSUE TITLE
Installing npm peer dependency 

### ISSUE THREAD

**Issue by anishmittal2020** [marktext/marktext#623]
I am trying to install [marktext](https://github.com/marktext/marktext) globally using npm (after cloning the repository) on Ubuntu 18.4: 

    npm install -g

`npm WARN dagre-d3-renderer@0.5.8 requires a peer of d3@^4.13.0 but none is installed. You must install peer dependencies yourself.`

How should I install, the peer dependency for the global package? Please give the command so that it is safe and prevents future conflicts.

---

I did `npm install -g  d3@^4.13.0` but I still get the same error.

Is this a good idea to install the dependency globally? Also, do I need to lock this at the version globally to prevent auto update when I do global update

**Comment by Jocs** [comment]
@anishmittal2020 Now we use `yarn` as the package manager, just run

```sh
yarn
```

after you clone this project. and run 

```sh
npm run dev
```

for develop, and run:

```sh
npm run build
```

for build.

**Comment by fxha** [comment]
> I am trying to install marktext globally using npm (after cloning the repository)

Thanks @anishmittal2020, this is not supported. Mark Text is a desktop application which must be build as described above. Mark Text setup/binary is located under the `build` folder.
