### ISSUE TITLE
light theme's color 

### ISSUE THREAD

**Issue by Aecu** [marktext/marktext#624]
Could i set the title bar's color of light theme?  when everything is white or light,the MarkText awlays hide in the white background which always as the defalut backgroud color of most software such as browser.

**Comment by Aecu** [comment]
![tt](https://user-images.githubusercontent.com/18171360/50371763-20b2d880-05fc-11e9-86fd-b4ad899f6fe8.png)

**Comment by Jocs** [comment]
You can change the style file, and build Mark Text for yourself, now we didn't support or provide a config option to set the title bar background color.
