### ISSUE TITLE
Improvement for auto scroll

### ISSUE THREAD

**Issue by H16Y** [marktext/marktext#628]
### Describe your feature request

Currently, when I type to the last line of the application window, and start a new line, the program does not auto scroll to the end (so I cannot see the line I am going to type). Only after I type something in the new line, I can see the last line. 
I think the program can scroll to the new line as soon as I start a new line.

### What problem does this feature solve? [optional]

Better user experience.

### Additional context [optional]

![5](https://user-images.githubusercontent.com/45055956/50392991-eda04e80-078d-11e9-9e77-b2960b2749e7.gif)

As shown in the gif, it is inconvenient if I start a new line and cannot see it immediately.

**Comment by Bratal** [comment]
good evening,
we are two students in computer sciences  (with @Ziirofan), and in order to validate our class about open source project we are  going to start working on this issue (and others if we have enough time).

**Comment by fxha** [comment]
Thanks for looking into this @Bratal and @Ziirofan. Please let us know if you have any questions.

**Comment by Bratal** [comment]
great ! If you need beta testing please let us know ! we were already using mark text before this class.

**Comment by Jocs** [comment]
@Bratal any updates about this issue?

**Comment by crimson-med** [comment]
Hello all I have the same issue and using marktext for creating documentation on projects it is usually quite long and this feature would be helpful as I could be able to actually see what I'm typing without having to stop and scroll.

**Comment by Jocs** [comment]
@all Add this issue to project 0.16.0
