### ISSUE TITLE
Select then delete bug

### ISSUE THREAD

**Issue by H16Y** [marktext/marktext#629]
### Description

Partial selection + `Ctrl+A` produces exceptions.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Enter one line of text.
2. Press `Enter` to start a new line.
3. Select the entered text.
3. Press `Ctrl+A`.
4. Press `Delete`.

**Expected behavior:**

No exceptions.

**Actual behavior:**

Exceptions that can make realtime preview abnormal.

**Link to an example: [optional]**

![6](https://user-images.githubusercontent.com/45055956/50393343-9bacf800-0790-11e9-824b-003e29f1fdad.gif)

### Versions

- Mark Text: v 0.13.65
- Operating system: Win10 1607 x64

**Comment by Jocs** [comment]
@H16Y Yeh, it a serious bug, thanks for reporting this issue, we'l fix it soon.
