### ISSUE TITLE
Disable editor while dialog is shown

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#63]
### Description

Feature/bug? :butterfly: 

### Steps to reproduce

![mt_bug](https://user-images.githubusercontent.com/22716132/37822802-d7ce8926-2e87-11e8-92c3-ca8fdb29927e.gif)

### Versions

- Mark Text: latest
- OS: linux

**Comment by Jocs** [comment]
@fxha I think the best user experience is to disable the editor, But it is not a big bug...

Let's fix some big bugs first. 😸
