### ISSUE TITLE
Selection cannot be cancelled by up / down keys

### ISSUE THREAD

**Issue by H16Y** [marktext/marktext#630]
### Description

Partial selection cannot be cancelled by `up` or `down` keys.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Select some text (must be in the same line).
2. Press `up` or `down` on keyboard.

**Expected behavior:**

Selection is cancelled.

**Actual behavior:**

Nothing happens.

**Link to an example: [optional]**

![7](https://user-images.githubusercontent.com/45055956/50393516-baf85500-0791-11e9-895b-cd4cfecadc91.gif)

### Versions

- Mark Text: v 0.13.65
- Operating system: Win10 1607 x64

**Comment by Jocs** [comment]
@H16Y Thanks for your reporting this bug, we'll fix it in the next release version.
