### ISSUE TITLE
Cursor position bug

### ISSUE THREAD

**Issue by h6a8ke1k** [marktext/marktext#634]
### Description

In a numbered list, when the text exceeds the line width and go to a new line, the cursor position is not expected when clicking below the list.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Start a numbered list.
2. Type in random characters until it starts a new line.
3. Click below the list.

**Expected behavior:**

Cursor position in the last line.

**Actual behavior:**

Cursor position in the first line of the last number.

**Link to an example: [optional]**

![9](https://user-images.githubusercontent.com/46216438/50509199-01b2bb80-0ac0-11e9-891b-b50b67f29ff4.gif)

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows

**Comment by Jocs** [comment]
This issue is already fixed in master branch, and will release in the coming version.
