### ISSUE TITLE
Select & paste bug

### ISSUE THREAD

**Issue by h6a8ke1k** [marktext/marktext#635]
### Description

When select using keyboard, paste will not override the selection. Instead, it leaves something in the original position.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Select using `Ctrl+Left` or `Ctrl+Right`.
2. Paste something.

**Expected behavior:**

The new content override the selection.

**Actual behavior:**

Something in the selection remains.

**Link to an example: [optional]**

![10](https://user-images.githubusercontent.com/46216438/50509497-13e12980-0ac1-11e9-9fd0-5ff8f692280e.gif)

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows

**Comment by mupchrch** [comment]
Additionally, cutting content (cmd + x) only removes the last letter.

**Comment by Jocs** [comment]
@mupchrch Thanks this bug has been fixed on master, and it will released in the next version.
