### ISSUE TITLE
When inserting a line break to the first item of nested list, the new line is a paragraph

### ISSUE THREAD

**Issue by maxloh** [marktext/marktext#636]
### Description

When inserting a line break to the first item of nested unordered list, the next line should be a list item.
However, marktext treat the new line as a paragraph instead of a unordered list item.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a nested unorder list
2. Press enter

#### Expected behavior:

Next line is a unordered list item, like this:

- Try insert line break in the end of this line
- New Line added
  - aaaaaaaaaaaaaaaaaaa

#### Actual behavior:

Next line is a paragraph, like this (markdown source code generated from marktext):

- Try insert line break in the end of this line

  New Line added
  - aaaaaaaaaaaaaaaaaaa

#### Link to an example: [optional]

```
- Try insert line break in the end of this line
  - aaaaaaaaaaaaaaaaaaa
```

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows 10 17763.195

**Comment by Jocs** [comment]
@maxloh I maybe don't think this a problem. for example:

you have this markdown bellow:

```md
- Try insert line break in the end of this line<cursor>
  - nested list
```

paragraph `Try insert line break in the end of this line` and list `- nested list` are at the same level, both of them are child of the outer list item. if you press `enter`,it will create another paragraph between `Try insert line break in the end of this line` and list `- nested list`. **If you want to turn it into a list item, please press `enter` again**.

**Comment by maxloh** [comment]
@Jocs The flow you described may not be straightforward for most people, at least for those who familiar with office software.

When you press enter in Microsoft Word, LibreOffice or Google Docs in the situation above, a new list item  is added. To add a new paragraph instead, you could press <kbd>enter</kbd> and then <kbd>delete</kbd>.

Consider that most people have experience dealing with office software. I think that following their flow would make marktext more easy to use.

**Comment by Jocs** [comment]
I hope everyone can talk about the way they like by 👍

**Comment by fxha** [comment]
> If you want to turn it into a list item, please press enter again.

Just one observation: I have no particular problem with this behavior but it's a little bit inconsistent because `- foo<enter>` always produces a new list item but not in this  particular case.
