### ISSUE TITLE
Start MarkText with a specific markdown document

### ISSUE THREAD

**Issue by arty-name** [marktext/marktext#64]
### Description

I am using MarkText as AppImage on Ubuntu Linux. When I pass a filename as a command line parameter to MarkText.AppImage it just starts with a blank document. Therefore I cannot integrate it in desktop environment nicely, like opening markdown documents in MarkText with a double-click.

### Steps to reproduce

1. Download latest MarkText.AppImage on Linux and make it executable
2. Start it from the command line passing a path and name of existing markdown document as a parameter

**Expected behavior:** MarkText starts with this markdown document open

**Actual behavior:** MarkText starts with a blank document

### Versions

- Mark Text: marktext-0.7.17-x86_64.AppImage
- OS: Ubuntu Linux 17.04

**Comment by fxha** [comment]
This issue is already fix on master. It should work with version 0.8.4

**Comment by arty-name** [comment]
That’s great to know, and thanks for the very quick response! Are there any estimations when the 0.8.x branch going to be released?

**Comment by Jocs** [comment]
@arty-name This weekend, but not very sure.

😺
