### ISSUE TITLE
CLI executable such that I can open files or directories in Mark Text via the command line

### ISSUE THREAD

**Issue by balupton** [marktext/marktext#640]
### Describe your feature request

I would like to be able to do:

```
touch index.md
marktext index.md
```

To open the `index.md` file.

### What problem does this feature solve? [optional]

Allows me to easily setup a command to open my blog's markdown files in Mark Text.

**Comment by balupton** [comment]
For now, one can use the Get Info window on a markdown file, on macos, then change the file association for all to Mark Text, then they can do:

```
open index.md
```

**Comment by balupton** [comment]
Okay, the Get Info file association thing isn't necessary, one can do this:

```
touch index.md
open -a /Applications/Mark\ Text.app index.md
```

**Comment by hyphone** [comment]
sadly this does not seem to work on Linux via the Flatpak version on Flathub.

`flatpak run com.github.marktext.marktext 'file/to/open.md`'

just opens a new window

**Comment by fxha** [comment]
@heymind Yes, that is true. I thought directories work too because it is implemented in the editor window but it's not checked while parsing arguments. It will be available in the next release.

**Comment by fxha** [comment]
This feature will be available in the next release.

**Comment by balupton** [comment]
> This feature will be available in the next release.

any docs?

**Comment by fxha** [comment]
I think it's a good idea to document the settings although we'll create whole new settings at some time.

@balupton You have to set the settings option `openFilesInNewWindow` to `false` on master or in upcoming v0.14.x.

**Comment by kaicataldo** [comment]
I couldn't find builtin support for this, but here's a little Bash snippet for anyone who comes across this like I did.

Put the following in your `.bashrc` (this is for the default install location in macOS; change the path for your respective OS):

```bash
marktext() {
  open -a /Applications/Mark\ Text.app $1
}

```
and then you can open Mark Text on the command line using:

```console
$ marktext path/to/file-or-directory
```

**Comment by marcggl** [comment]
@balupton

I'm using _MacOS Monterey_ (_12.2.1_) and _MarkText 0.17.1_. I tried with

`open -a /Applications/Mark\ Text.app ~/.zshrc`

I got
```
The application /Applications/Mark Text.app cannot be opened for an unexpected reason, 
error=Error Domain=NSCocoaErrorDomain Code=260 "The file “Mark Text.app” couldn’t be opened because there is no such file." 
UserInfo={NSURL=file:///Applications/Mark%20Text.app, NSFilePath=/Applications/Mark Text.app, NSUnderlyingError=0x600000edc7e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

I searched better and I found that the correct alias may be

`alias marktext="open -a /Applications/MarkText.app"`

When I run 

`marktext ~/.zshrc`

the unique effect I observe is the switch to MarkText which is already open without the required file
