### ISSUE TITLE
Manage Tags

### ISSUE THREAD

**Issue by ymjonline** [marktext/marktext#641]
### Tag in MD header

Marktext is the most awesome Markdown editor so far (except that images can't be pasted yet, but that's another feature request)
As a editor of standalone files it is close to perfect.

It still lacks a layer of management to make it a replacement of e.g. Evernote and the likes.

The request is to use the YAML header and *tag* in particular to organize, search, sort notes.

### Better notes management

Ability to organize, sort, search, categorize notes as opposed to  dodgy folder structure.

**Comment by Jocs** [comment]
Maybe you need a notepad or memo software and support markdown input. At the moment, Mark Text is a pure markdown editor, there is no storage function, and no notebook function is added. I am also thinking about adding these functions to Mark Text. Or do write another software called `markNote`, which is used exclusively as a notepad or memo, with local storage and cloud storage (icloud or Google Drive, etc.), do you have any suggestions?

**Comment by ymjonline** [comment]
I've been looking *everywhere* for such a note management tool that would wrap around Marktext, to no avail.

The closest I can get is 
- Joplin: but poor mobile app and not plain MD.  Metadata is not handled via YAML but through its own format

- Notable: No mobile app, which is a must for note-taking
And still miss the picture pasting feature from MarkText itself

everything points back to Evernote and this is very frustrating (and not an option)

**Comment by Ir1d** [comment]
What about saving the tags in the meta part of markdown files:

```
--
tags: xxx, xxx
--
```

Honestly I'm not sure what's the difference between a markdown editor and a note-taking app.
Perhaps the gap can be filled by plugins (#375 )

@fxha I propose to reopen this issue, it would be great if tags can be parsed and maintained

**Comment by Jocs** [comment]
>meta part.

Do you mean use extra files to store the `meta part.`? or just the front matter?

**Comment by pecigonzalo** [comment]
I think what could be useful is to have a way of searching or listing by tag (tags in Front Matter) kind of how it done in Notable.
We can search them with the search bar right now, but there is no "clean" way of doing to only point at tags.

**Comment by brainchild0** [comment]
> Maybe you need a notepad or memo software and support markdown input. At the moment, Mark Text is a pure markdown editor, there is no storage function, and no notebook function is added. I am also thinking about adding these functions to Mark Text. Or do write another software called `markNote`, which is used exclusively as a notepad or memo, with local storage and cloud storage (icloud or Google Drive, etc.), do you have any suggestions?

@Jocs: I am wondering why you would consider distributing a separate application for notes. It seems that most of the functionality would be common with the file editor. If you were to implement notes features, what are the advantages of a separate application?
