### ISSUE TITLE
Add recently used directories to recently opened files

### ISSUE THREAD

**Issue by bluelovecute** [marktext/marktext#643]
### Describe your feature request

now can only record  recent opened files , but not folders

**Comment by pihentagy** [comment]
It seems to be not working for me on 0.15 and 0.15.1.

To be clear, what I did:
* Opened a folder via File / Open Folder
* Opened another folder via File / Open Folder
* Quit Marktext
* Open Marktext
* File / Open Recent / there are just 2 files from the directories, but not folders

**Comment by fxha** [comment]
@pihentagy Thanks for reporting the issue and the issue is already fixed in the latest develop version.

**Comment by pihentagy** [comment]
Thanks. Can I get the develop version without downloading the sources?

**Comment by pihentagy** [comment]
Ok, I can see recent diretories, but I'd like to improve it: show directories separate to files, either:
* in one list with a divider between them
* in separate list recently opened files and recently opened directories

**Comment by fxha** [comment]
@pihentagy 

> Thanks. Can I get the develop version without downloading the sources?

You can download the latest release candiate (RC) [from Github](https://github.com/marktext/marktext/releases) like `0.16.0-rc.2`.

> Ok, I can see recent diretories, but I'd like an improved version of it: show directories separate to files, either:

Please see issue #1608.
