### ISSUE TITLE
[suggetion] flatpak  build

### ISSUE THREAD

**Issue by breadlesscode** [marktext/marktext#65]
Hi guys,

I love your app :) Thanks for this :+1: 

Is it possible to add a flatpak build? Im using Deepin OS and this distribution is using flatpak.

Is that an easy step, or a complex one?

**Comment by Jocs** [comment]
Sorry, it seems that `electron-builder` still does not support `flatpak` build.

We'll consider adding flatpaks if / when electron-builder supports them.

**Comment by breadlesscode** [comment]
Than maybe a .deb file? :)

**Comment by fxha** [comment]
You can also install the [AppImage](https://github.com/marktext/marktext/releases) or snap package.

```
chmod +x marktext-0.8.12-x86_64.AppImage
./marktext-0.8.12-x86_64.AppImage
```

Then `Would you like to integrate <package> with your system?` click `yes` to install or `no` to execute Mark Text.

**Comment by SuperSandro2000** [comment]
I don't think we mark text should be build for every platform. If the app image works there is no reason right?

**Comment by breadlesscode** [comment]
Okay thank you guys :+1:

**Comment by fxha** [comment]
@breadlesscode Mark Text is now available via [flatpak/flathub](https://flathub.org/apps/details/com.github.marktext.marktext):

```
sudo flatpak install flathub com.github.marktext.marktext
```
