### ISSUE TITLE
Support Emphasis Mark.

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#654]
### Describe your feature request
Hi. I Figured out ruby ​​notation at #257.
Japanese Free Novel Site [Hameln](https://syosetu.org/) Arrange Sytle Kenten a.k.a. Asian Emphasis Mark.
```markdown
なぜ鬼は|人間<ぼくたち>を食べるのか？

<<食べなければならない>>のか？

English Translation (My Translation Ver.):Why Demons Eat Humans? Why **You Have To** Eat Human?
```

![retgrt4wtre5](https://user-images.githubusercontent.com/15725120/51470234-a91cc880-1db6-11e9-8f8c-23e196368694.PNG)

P.S. It is the dialogue of the latest talk at the time that Japanese Comic "The Promised Neverland" was released.
Since details are spoiled, please wait for the book containing that story.
People who do not read should read until the latest publication.
(As of January 21, 2019)

**Comment by fxha** [comment]
I'll mark this as feature request but it will related to many changes because this is not supported markdown and the characters `<` and `>` are reserved for HTML tags - like your other issue. I could imagine a feature which must first be enabled and restrict the HTML tag set. Meaning only predefined HTML tags are allowed and other tags are interpreted as Ruby or Kenten characters.

**Comment by keito940** [comment]
I got an Idea.
How about this kind of thing? 
```markdown
なぜ鬼は|人間{ぼくたち}を食べるのか？

{{食べなければならない}}のか？

```
In this case you can achieve both HTML tags and ruby ​​tags.
Markdown Not Use `{` and `}`.

**Comment by Jocs** [comment]
@keito940 I think you can try raw html syntax like bellow, this already support in the latest released version:

```md
<ruby>なぜ鬼は|人間<rt>ぼくたち</rt></ruby>を食べるのか？
<ruby>食べなければならない<rt>......</rt></ruby>のか？
```

and the render result is 

<ruby>なぜ鬼は|人間<rt>ぼくたち</rt></ruby>を食べるのか？
<ruby>食べなければならない<rt>......</rt></ruby>のか？

**Comment by Jocs** [comment]
I think custom theme will solve this problem, and custom is under our plan, so closed this issue.

@keito940 You can refer this page https://hanzi.pro/manual/yangshi_biaozhunhua#qiangdiao_yu_zhongdian
