### ISSUE TITLE
marktext hangs when navigating certain markdown file

### ISSUE THREAD

**Issue by kykc** [marktext/marktext#655]
### Description

marktext hangs when navigating certain markdown document with PgUp and PgDown keys

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open marktext
2. Switch to Dark Mode (probably not related, but just to be sure)
3. Save [this](https://raw.githubusercontent.com/kykc/marktext-issue/master/test.md) document somewhere on your drive
4. Open saved file in marktext
5. Scroll to the end of document with mouse and leave cursor there (I mean text editor cursor)
6. Now try to navigate using PgUp/PgDown keys. Marktext will hang after 3-4 times

**Expected behavior:**

Expected it to work 😸 

**Actual behavior:**

Editor hangs. From the looks of it renderer process catches infinite loop, as it consumes the whole processor core after hanging. Reproduced on both Windows and Linux, if it would be hard to reproduce on your end will gladly provide proof gif.

### Versions

- Mark Text: 0.13.65 (appImage on Linux and portable executable on Windows)
- Operating system: `Windows 10 1809` and `Ubuntu 18.04.1`

**Comment by fxha** [comment]
Thanks @kykc, I can reproduce the issue with this minimal example when pressing multiple times `Page Down`:

```md
Emphasis, aka italics, with *asterisks* or _underscores_.

Strong emphasis, aka bold, with **asterisks** or __underscores__.
```

It will hang on `Emphasis, aka italics, with *asterisks* or <cursor>_underscores_.`. Maybe a Regular expression DoS.

**Comment by fxha** [comment]
I really don't know how to debug this issue. I have tried the node debugger, some `printf` debugging and so on but always no response from V8 or not the right code area. The only option would be to use x86 debugging but we are using JS, so that's not an option. The following code areas doesn't seem to be affected: 

- **muya:**
  - `eventHandler`
  - `contentState` high level APIs
  - renderer methods inside `contentState`
    - not tested: `parser/render`
  - marked.js
  - `selection` stuff
  - muya plugins
- **renderer:**
  - high level functions in `components/editorWithTabs`

We could prevent PageDown/-Up keys and manually scroll the page as it's no reproducible without PageDown/-Up, but it will not fix the real issue.

**Comment by fxha** [comment]
@Jocs We should disable page down/up key until this is resolved or we implemented custom scrolling for these two keys. I guess that page down/up action is manage by Chromium.

**Comment by Jocs** [comment]
@fxha 
>It will hang on Emphasis, aka italics, with *asterisks* or <cursor>_underscores_.. Maybe a Regular expression DoS.

Can you reproduce this on both Windows and Linux? I don't know whether I am trying in the wrong way, I can not reproduce it on macOS.

**Comment by fxha** [comment]
Yes, I always can. Please copy the [example](https://github.com/marktext/marktext/issues/655#issuecomment-456157431) and put the cursor to the first line inside `Emphasis` and press multiple times <kbd>PageDown</kbd>.

**Comment by Jocs** [comment]
@fxha I still can't reproduce this, it's maybe only on Windows and Linux systems?

**Comment by fxha** [comment]
@Jocs I guess it was an upstream Electron issue because I cannot longer reproduce the issue.  ac3617d was the last commit the error occurred but since ffdb758 everything seems fine. I need to confirm this on Windows too.

**Comment by DutchPete** [comment]
I am not sure I understand this.

If an upgrade to Electron 6 solves this, how can we achieve this upgrade? Or do we need to wait till Mark Text version 0.16 is out?
Please advise.

**Comment by fxha** [comment]
Yes that's true. We may release a nightly version to test whether it was really fixed or not.
