### ISSUE TITLE
Making images display smaller

### ISSUE THREAD

**Issue by Yournished** [marktext/marktext#659]
I want to use Mark Text to take notes. Sometimes I have images that go along with the notes and I want to embed the image into the notes where it's explained. Unfortunately, if the image is very large, sometimes this leads to not very readable text and too much scrolling. I would like to embed an image in such a way that Mark Text displays it scaled down to some size, but the original file is still available and can be opened to view it in full resolution.

I know width isn't really part of image embedding in Markdown. Luckily, we have support for HTML, which does allow it. So I tried to do this with HTML by adding `<img src="img.jpg" width=300 />` (without an HTML block) to my file, but while this inserts the image correctly, the width is ignored. If I actually use the insert HTML block feature, which creates a div element, then the image no longer shows up (I'm guessing relative paths are not supported?). How come?

**Comment by fxha** [comment]
Thanks @Yournished,

> the width is ignored.

Yes, your right. HTML images should be scalable via `width` and `height`.

> I'm guessing relative paths are not supported

Relative paths are supported and are relative to the file's directory. If the file is unsaved it should be relative to the application working directory. I guess it's an issue with HTML image tags.

**Comment by Jocs** [comment]
>I would like to embed an image in such a way that Mark Text displays it scaled down to some size, but the original file is still available and can be opened to view it in full resolution.

We'll support `width` and `height` property in `img` tag later.

**Comment by Jocs** [comment]
> then the image no longer shows up (I'm guessing relative paths are not supported?). How come?

I test this, and it works well, So can you give me more info about this problem.

**Comment by fxha** [comment]
> We'll support width and height property in img tag later.

I guess markedjs (dompurify when pasted) removes the HTML attributes.

**Comment by Yournished** [comment]
@fxha Hey, I've been really busy so I couldn't really get back to you but I wanted to say I really appreciate you looking into this issue! Very refreshing to see a developer actually care about issues. I'll definitely try it again when 0.14 is out to see if it's fixed.

FYI, I mostly do this because images in my notes are often too large. Shrinking them would sometimes destroy useful data, generating thumbnails would create clutter as I would now have to maintain two versions of each image. For my use case, the true solution would be to have a setting in Marktext that governs the default behavior for displaying images with no width specified. So I'm thinking config options like `image_size_min`, `image_size_max`, `image_dpi_min`, `image_dpi_max` according to which Marktext could shrink or stretch images embedded with ordinary Markdown to the desired size, if necessary. This way the file itself would not specify image size, instead each machine running Marktext would display images in the way suitable for that installation (eg. to account for different screen DPIs).

@Jocs Here's how I'm getting it:

1. Make an empty folder
2. Create a file `img.png` in this folder
3. Also create `test.md`, containing `<img src='img.png' width=300/>`
4. Open in Marktext, it shows shows up as the "broken link icon" instead of the actual image.

Things I tried:

- Removing width
- Putting `300` in quotes
- `"img.png"` instead of single quotes
- `/img.png`
- `./img.png`

None of these work, I still get a broken link icon. This is on two different computers (Linux and Windows). What does work is:

- Using classic MD syntax: `![](img.png)` (image shows but obviously can't change size)
- Absolute path: `<img src='/home/funnyusername/test_folder/img.png' width=300/>`

Actually I now realize that if I give absolute path, then width is also respected.

**Comment by bonnebulle** [comment]
Hum, not exactly what you discuss here
In my case, the image (re)sizing is a problem in MarkText (_client side_, not on _server side_, when published/rended online).
For me adding `image_size_mini` `mage_size_max` (last comment) in a CSS customization section can help.
