### ISSUE TITLE
Incorrect rendering of pipe in code block within table

### ISSUE THREAD

**Issue by ByMedion** [marktext/marktext#660]
### Description

`|` with backslash and `|` in backquotes not working in tables.

Example:
```
| Flag | Required | Values           | Description      |
|:----:|:--------:|:----------------:|:-----------------|
| `-o` | yes      | `[*.zip\|*.7z]`  | Output file path |
```

Expected:

Flag | Required | Values | Description
---- | ---------- | ------- | ------------
`-o` | yes | `[*.zip\|*.7z]` | Output file path

Got this:

![78](https://user-images.githubusercontent.com/23483788/51787014-9242f100-217d-11e9-9047-2b74b61c6e07.png)

### Versions

- Mark Text: 0.13.65
- OS: Win x64

**Comment by fxha** [comment]
Thanks @ByMedion, this is a known bug in our markdown parser `marked.js` which is already fixed upstream.

**Comment by N0rbert** [comment]
I'm suffering from this bug on MarkText 0.16.3. Minimal reproducible example is below:

```
| **Command**                                                            | **Done?** |
|:-----------------------------------------------------------------------|:---------:|
| `sudo apt purge $(dpkg -l | grep ^ii | grep grub | awk '{print $2}')`  | v         |
```

It is rendered wrong:

> ![wrong](https://user-images.githubusercontent.com/309456/108862291-256edf00-7601-11eb-887c-1359e617912e.png)

For example Typora and ReText shows this table correctly. But your cool marked [fails](https://johnmacfarlane.net/babelmark2/?text=%7C+**Command**++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++%7C+**Done%3F**+%7C%0A%7C%3A-----------------------------------------------------------------------%7C%3A---------%3A%7C%0A%7C+%60sudo+apt+purge+%24(dpkg+-l+%7C+grep+%5Eii+%7C+grep+grub+%7C+awk+%27%7Bprint+%242%7D%27)%60++%7C+v+++++++++%7C%0A).
