### ISSUE TITLE
Fatal error when a directory is removed

### ISSUE THREAD

**Issue by ByMedion** [marktext/marktext#661]
### Description

Fatal error occurred when deleting directory that was created outside MarkText.

![step1](https://user-images.githubusercontent.com/23483788/51787576-e3a2ae80-2184-11e9-8af3-3ada2aa98c76.png)

### Step 1: create subfolder in opened folder in MarkText.
After this step an untitled folder appears in MarkText.

![step2](https://user-images.githubusercontent.com/23483788/51787577-e3a2ae80-2184-11e9-8819-8a323ad18a62.png)

### Step 2: set new name to created folder

![step3](https://user-images.githubusercontent.com/23483788/51787578-e43b4500-2184-11e9-8c0d-2feaaff8a345.png)

After this steps we have two duplicates with default and new name.

### Step 3: delete folder

![step4](https://user-images.githubusercontent.com/23483788/51787579-e43b4500-2184-11e9-8e35-cff2c5f21cb0.png)

### Versions

- Mark Text: 0.13.65
- OS: Windows 10 x64

**Comment by fxha** [comment]
I'll take a look at [atom/watcher](https://github.com/atom/watcher) because this is actually an [upstream issue](https://github.com/paulmillr/chokidar/issues/566) on Windows. Other filesystem watcher libraries seem to have even more issues.

**Comment by fxha** [comment]
Closing this issue because we fixed the UI issue when removing a folder on Windows and the upstream issue seems fixed (tested with latest master).
