### ISSUE TITLE
What is the character and number of left-top?

### ISSUE THREAD

**Issue by heyconnor** [marktext/marktext#666]
### What is the character and number in left-top for?

I notice there is a character and number in left-top, and it seems nothing occured when I changed it. What is it for?

**Comment by Jocs** [comment]
`word count` , `paragraph count` etc.

**Comment by stefnotch** [comment]
Suggestion: A hover text for the number in the top-left corner. 

It took me a while to figure out what the number was for at the beginning as well. So, implementing a hover text would nicely address this issue while not cluttering the interface.

![image](https://user-images.githubusercontent.com/10220080/52128075-42a86d80-2634-11e9-9cee-1f8bf9184bea.png)

**Comment by stefnotch** [comment]
Also, congratulation on creating the devil's issue ( #666 )
