### ISSUE TITLE
Is there a flow chart function?

### ISSUE THREAD

**Issue by youmoxiaozi** [marktext/marktext#669]
Does the next version have the following functions?
1. flow chart
2. Localized Language

**Comment by fxha** [comment]
> flow chart

Diagram support is tracked in #218 and should be supported in the next version.

There is also an experimental diagram support in `v0.13.65`. You can use gant, sequence and flowchart diagrams but not vega-lite. Examples can be found here: https://github.com/marktext/marktext/pull/529#issuecomment-434728528.

> Localized Language

No, duplicate of https://github.com/marktext/marktext/issues/138#issuecomment-380867653

**Comment by wf5w** [comment]
Ok. Just got marktext and like it.

But, I see nothing about the installation of a flowchart and graphing tools.

How do I do that, so I can use both in the markdown text.

Thank you.
Jerry
