### ISSUE TITLE
Disable autocompletion in inline math

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#673]
### Describe your feature request

Autocompletion for inline math (`$1+2=3$`) should be disabled because `_` is completed to `_<cursor>_`. It should use the autocompletion "lite" like math blocks.

**Comment by Jocs** [comment]
>It should use the autocompletion "lite" like math blocks.

What do you mean `autocompletion "lite"` ?

**Comment by fxha** [comment]
The autocompletion for block math (`$$`).

**Comment by Jocs** [comment]
@fxha Sorry I still do not understand this issue exactly. can you explain it more detail?

**Comment by fxha** [comment]
We disabled autocompletion for `_` and `*` for math blocks in [5ff7f7b](https://github.com/marktext/marktext/commit/5ff7f7b92e6b35ebd17a8a60932ad127715a0d82) and the same should apply to inline math because when writing LaTeX you only want one `_` and `*` character.

**Comment by Jocs** [comment]
@fxha I got it. thanks
