### ISSUE TITLE
Installing as default editor

### ISSUE THREAD

**Issue by djsylvester** [marktext/marktext#68]
### Description

After installing all text (.txt) files changed to MarkText icon causing any of those files to be opened by this app due to it automatically changing the default.

### Steps to reproduce

1. Install
2. Look at the icon for any text (.txt) file in a directory

**Expected behavior:**
Not to change default application settings without permission.

**Actual behavior:**
Default changed to MarkText for text files. Users may have other editors (as I do) for editing such as Notepad++, Editpad, Vim, etc. which they may prefer to remain default, especially when one is just trying out the software. A user should be asked which file formats they *want* associated with the app, if any. Shouldn't assume they want to change or, are giving up their current tool(s). 

**Link to an example:**
None required.

### Versions

- Mark Text: v0.7.17
- OS: Windows 7 x64

**Comment by SuperSandro2000** [comment]
Related to that: https://github.com/marktext/marktext/pull/26
When using the electron association with txt files the ``New -> Text Document`` entry in the windows context menu is just somehow 'corrupted'.

**Comment by fxha** [comment]
I think this issue has nothing to do with PR #26. @djsylvester asks about a setup option to select file associations (like `.txt` or `.md`).

I wonder why ever should we associated text file (`.txt`, `.text`) with Mark Text?

**Comment by Jocs** [comment]
@fxha I think I just want Mark Text to open (`.txt`, `.text`) files...

But I am not sure if the `fileAssociations` with  (`.txt`, `.text`) ext caused this bug.

Have you verified this on a Windows system ?

**Comment by SuperSandro2000** [comment]
I have verified it multiple times. Running MarkText directly causes the bug obvious not but using the installer it does.

**Comment by Jocs** [comment]
@SuperSandro2000 we released the v0.8.12, has the problem been solved?

**Comment by djsylvester** [comment]
Just installed v0.8.12 and it did not change file association for .txt files, only .md files. I'm also able to choose "open with" and change to the other markdown editor I have installed which is great. Will most likely uninstall the other after I've had time to play and make decision.

Thanks for such a quick turnaround.

**Comment by SuperSandro2000** [comment]
@Jocs yes

**Comment by Jocs** [comment]
@SuperSandro2000 Ok, I'll close this issue now.
