### ISSUE TITLE
Export to PDF while using dark theme generates black PDF

### ISSUE THREAD

**Issue by tonydiep** [marktext/marktext#683]
### Description

If you're using the dark theme and you export to PDF, the PDF is a big rectangle of black.

- [X] Can you reproduce the issue? 

### Steps to reproduce

1. Theme -> Dark
2. File -> Export -> PDF

**Expected behavior:**

Black text on white background

**Actual behavior:**

* Black text (presumably) on black background

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: CentOS Linux release 7.6.1810 (Core)

**Comment by raphaelmartin** [comment]
Even theme > Light produces a big white rectangle...

**Comment by fxha** [comment]
Duplicate of #583
