### ISSUE TITLE
Inserting Codeblock should automatically set cursor into language field

### ISSUE THREAD

**Issue by JonnyCodewalker** [marktext/marktext#684]
At the moment you have to use the mouse to click into the language field in order to set the language for a code-block (using arrow buttons does not work). 

If the language field would be where the cursor is when inserting the field with @ you could set the language for a code-block without getting the hands of the keyboard.

It would have to be implemented that simply pressing tab then selected the actual code-block though, in order to not disturb current behaviour to much.

**Comment by fxha** [comment]
As I understand, you want another list with all languages when e.g. pressing `Tab` in the quick insert code block pop-up or just that the language field is default selected? With the latter, I agree :+1:

**Comment by JonnyCodewalker** [comment]
Just that it is automatically selected. If it is and you don't a language you could simply press enter/tab to get to the codeblock itself, but if it isn't automatically selected and you want to use a language you have to use the mouse or type it out instead of using @ insertion.

**Comment by Jocs** [comment]
@JonnyCodewalker There are about three ways to insert a `code block`.

1. type `@` and select code block.

2. Use `paragraph menu` or shortcut `Option + Command + c`.

3. type \``` and and language name, press `enter` to create a `code block`.

And you want the 1 and 2 ways should autofocus in the language field after you create the code block?

And the cursor should also focus the language field by mouse up and down between paragraphs?

**Comment by JonnyCodewalker** [comment]
@Jocs yes, 1 should autofocus the langauge field, but make it trivial to exit the languagefield (enter or tab). Not sure what you mean about the cursor. But currently @ is not usable as a shortcut for creating a codeblock if you actually want to use a language since it requires you to lift your hands from the keyboard, grab the mouse and manually klick into the language field. (not usable meaning it is not a shortcut, it creates more work than the "barebones" ``` )

**Comment by Jocs** [comment]
@JonnyCodewalker I agree with you, I also don't want to move my hands away from keyboard when I am write some documents.
