### ISSUE TITLE
Enable [TOC] to generate Table of Contents

### ISSUE THREAD

**Issue by JonnyCodewalker** [marktext/marktext#685]
Typora supports the shorthand [TOC] to generate a table of contents. That is really awesome for longer texts. Maybe Mark Text should include it as well.

**Comment by fxha** [comment]
Thanks @JonnyCodewalker, this was discussed in #80 and we'll support TOC only when exporting as HTML/PDF but not in the editor, at least in the near future.

**Comment by nie312122330** [comment]
export pdf  with toc ,  i want like Typora  gen toc

![image](https://user-images.githubusercontent.com/46509964/157156570-4b6bf8a1-f137-475f-ae15-6ba4c5fbe171.png)
![image](https://user-images.githubusercontent.com/46509964/157156632-f4e3eb6e-b566-4b2d-a1b2-005adb99112f.png)
![image](https://user-images.githubusercontent.com/46509964/157156721-002c548f-0ca1-43d9-b059-54f4cf5f8e1c.png)

**Comment by skjerns** [comment]
Following up on this:

It seems like this only shows headings of level 1 and 2. Would it be possible to also include all levels of headings? I mainly use Headings level 3 and 4, and it would be great if they would also show up in the PDF TOC.
