### ISSUE TITLE
Option to hide Scrollbars

### ISSUE THREAD

**Issue by JonnyCodewalker** [marktext/marktext#686]
It would be awesome to have an option to hide the scrollbar, since it doesn't integrate well and users might want to simply hide it.

**Comment by Jocs** [comment]
@JonnyCodewalker If there is no scrollbar, user will think the page can not scroll?

**Comment by JonnyCodewalker** [comment]
Which is why it should be an option, if it is included. And it definitely should not be the default^^.
But for example i really dislike scrollbars and disable them wherever I can.

**Comment by Jocs** [comment]
OK, maybe we will add an option to hide the scroll bar later, but it will be displayed by default, of course, the demand priority will be lower.
