### ISSUE TITLE
Ctrl + Q does not close windows (Appimage)

### ISSUE THREAD

**Issue by JonnyCodewalker** [marktext/marktext#687]
### Description
When pressing CTRL+Q Noving happens. 

- [x] Can you reproduce the issue? 
### Steps to reproduce

1. Open Marktext
2. Try to use CTL+Q to quit.

**Expected behavior:**
Application quits.

**Actual behavior:**
Nothing happened.

### Versions

- Mark Text: 0.13.65
- Operating system: Solus 3.9999

**Comment by fxha** [comment]
Thanks @JonnyCodewalker, we currently use `Alt+F4` on Linux and Windows to exit the application. If you want to change it, please see [key bindings](https://github.com/marktext/marktext/blob/master/doc/KEYBINDINGS.md) and set `windowCloseWindow` to `Ctrl+Q`.
