### ISSUE TITLE
Is there a way to bulk export?

### ISSUE THREAD

**Issue by raghu12133** [marktext/marktext#689]
Current export feature is bound to export a single document. Are there ways to bulk export `directories` or `multiple documents` ?

**Comment by fxha** [comment]
Unfortunately, we do not support multiple exports yet. If there is sufficient interest, we can add this feature to our to-do list.

**Comment by Jocs** [comment]
If there are more users who need this feature, we will consider adding it. If you need this feature, please 👍 it.

**Comment by fxha** [comment]
Closing because there is now no demand for this feature.
