### ISSUE TITLE
GTK integration

### ISSUE THREAD

**Issue by fbruetting** [marktext/marktext#690]
### Describe your feature request

Currently Marktext uses GTK dialogs, but the window decoration and menus are totally out of place on GTK desktops like Gnome.

### What problem does this feature solve?

The application does not integrate with all the others on GTK desktops.

**Comment by fxha** [comment]
Yes, that's true and this has been discussed in #39. We're using our own style based on the current theme, except for file dialogs and the hamburger menu. The native title bar is only enabled on macOS because we can modify the title bar.

**Comment by fbruetting** [comment]
If every sole app developer decides to do a window style on its own,  we will see total chaos. Guess I’ll have to switch to another one then.

**Comment by fxha** [comment]
I'm sorry to hear that. I mean, I like the idea of Client-Side Decoration for Linux but it's currently not supported by Electron (upstream electron/electron#11907). The only option is to use a custom titlebar or waste vertical space. So it's maybe not the best option, but to follow our philosophy to be a clean, simple and minimalist editor it's fine. Maybe we should add an option to use the native titlebar without controls like vscode, @fbruetting?

**Comment by fbruetting** [comment]
Ah ok, then the problem is due to electron (I first assumed that you don’t care). I **relly** like your program, would be damn cool if this would be fixed then! Having the a regular title bar with an additional menu bar would fix the UX issue, but a real header bar would be more awesome and effective.

You can of course also get a clean canvas with title bars or header bars when you change to full-screen mode via F11! In fact that’s even more clean than the current solution, as then also the whole title bar would disappear (it then will be displayed if you move the mouse to the top edge). Currently, the title bar still gets displayed in full-screen mode. 😜
