### ISSUE TITLE
markdown slide editor like marp

### ISSUE THREAD

**Issue by linpengcheng** [marktext/marktext#691]
markdown slide editor like https://github.com/yhatt/marp

**Comment by fxha** [comment]
I think this was an idea but I'm personally against it because Mark Text is a pure markdown editor. What do you think about it, @Jocs?

**Comment by Jocs** [comment]
In fact, I have thought about this before, by adding some comments to support the presentation, but this demand is not high priority.

```md
<!-- slide 1 -->
### topic 1
* wowow

<!-- slide 2 -->
### topic 2
> quote
```

**Comment by Jocs** [comment]
Close the issue because we don't support the feature very much. Thanks for your advice.
