### ISSUE TITLE
line number in the gutter

### ISSUE THREAD

**Issue by Umryuan** [marktext/marktext#693]
### Describe your feature request

add line number at editor's gutter

### What problem does this feature solve? [optional]

easy to find the specific line in the document

### Additional context [optional]

![example](https://discourse-cdn-sjc1.com/business6/uploads/github_atom/original/3X/4/d/4d8e637858d6556f4bebf9217318ccab46d6a7ea.png)

**Comment by Umryuan** [comment]
just like the picture :smiley:

**Comment by Jocs** [comment]
@Umryuan Do you mean gutter in `code block` or the whole document?

**Comment by Umryuan** [comment]
What i want is whole document (easy to target to a specific location),and i can use a switch to control it (on/off) 
@Jocs

**Comment by Jocs** [comment]
@Umryuan I think you can use the source code mode? if you want to use gutter.

**Comment by Umryuan** [comment]
I have used the source code mode, and it basically satisfied my needs.
:bug: But i found a bug:
When i turn on  the source code mode, and then if i change the editor tab, nothing will happen, i still see the former file, changing tab feature seems failed.
My os is Ubuntu 16.04, you can verify whether it is a bug or not. :hammer: 
And Mark Text version is v 0.13.65.

**Comment by fxha** [comment]
> When i turn on the source code mode, and then if i change the editor tab, nothing will happen, i still see the former file, changing tab feature seems failed.
My os is Ubuntu 16.04, you can verify whether it is a bug or not. hammer
And Mark Text version is v 0.13.65.

Please see #606.

**Comment by Jocs** [comment]
@Umryuan I'll close this issue if no more info, fill free to reopen it if you have any other question.
