### ISSUE TITLE
Default to LF

### ISSUE THREAD

**Issue by fbruetting** [marktext/marktext#694]
### Description

All sane operating systems use LF for line endings (all Linux systems, all UNIX systems, MacOS, etc.), and so do about all programming applications (git, IDEs, etc.). Please make this the default, it even gets more and more common to be the default on stupid Windows systems, as far as I know.

**Comment by fxha** [comment]
We will not change that. Unix(-like) operating systems uses `LF` by default and Windows `CRLF`, but this can be changed in the preferences (`endOfLine`).

**Comment by fbruetting** [comment]
On my Linux system it was CRLF and was always set back to CRLF when I tried to change that…

**Comment by fxha** [comment]
That's weird, can you please post your settings (at least `endOfLine` value)? The file should be located under `~/.config/marktext/preference.md` or `~/.var/app/com.github.marktext.marktext/config/marktext/preference.md` for flatpak.
