### ISSUE TITLE
Using extended code identifiers breaks code blocks

### ISSUE THREAD

**Issue by lostpebble** [marktext/marktext#697]
### Description

When using code identifiers (info strings when opening code fences) such as `typescript jsx`, we get some weird behavour where the inital opening fence is ignored - which obviously causes the next regular text to be seen as code now, like so:

![image](https://user-images.githubusercontent.com/1508863/53298999-219afd00-382d-11e9-8df0-ea3c2ee85432.png)

Those extra identifiers are important because of things like JSX, which are differentiated from regular TypeScript or JavaScript by adding that extra term in the info string.

If for the sake of development simplicity on your side, Mark Text just treats those blocks as regular TypeScript (as if we only marked it `typescript` without the `jsx` extra) I'm fine with that too - I just would like to have the editor display the code blocks correctly at least and not skip over that opening fence altogether.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Write a code block that starts with a opening fence that has an info string of `typescript jsx`
2. See that it doesn't display correctly

**Expected behavior:**

Regular code blocks at the least. Best case is full code syntax highlighting, of course.

### Versions

- Mark Text: 0.13.65
- Operating system: Windows 10

**Comment by fxha** [comment]
Thanks @lostpebble, you can use `tsx` to combine both `typescript` and `jsx` and it seems to be a parser issue.

CommonMark/GFM Spec: https://github.github.com/gfm/#example-112

> An info string can be provided after the opening code fence. Opening and closing spaces will be stripped, **and the first word**, prefixed with language-, **is used as the value** for the class attribute of the code element within the enclosing pre element.

**Comment by lostpebble** [comment]
Thanks! `tsx` is sorting me out fine now.

**Comment by Jocs** [comment]
@lostpebble Can you show me the test markdown file which will cause this issue?

**Comment by fxha** [comment]
@Jocs you have to load the following file without `\` or insert it in source code mode and switch back:

```
foo

\```cpp python
size_t i = 0;

int main() {
  return 0;
}
\```

foo
```

**Comment by Jocs** [comment]
@lostpebble @fxha I reproduce this issue, but under what circumstances will the code block require two languages?

**Comment by lostpebble** [comment]
> Those extra identifiers are important because of things like JSX, which are differentiated from regular TypeScript or JavaScript by adding that extra term in the info string.

As mentioned in my first post. It was what my IDE recommended to me (WebStorm) while auto-completing the info strings.

I see now, thanks to @fxha that I can just use the simple `tsx` - BUT, from what I can see on my project on github, using only `tsx` is not actually doing proper code syntax highlighting on the actual JSX elements like that (https://github.com/lostpebble/pullstate - see the second code block with some JSX in it). Whereas it works fine with `typescript jsx`.

If WebStorm recommends it, and GitHub functions better for it, is it not standard Markdown syntax? I'm not sure if they are just doing their own thing - I know that some docs on the standard refer to a single string (not sure if that includes the whole line though),
