### ISSUE TITLE
The app not open on Windows 10

### ISSUE THREAD

**Issue by candidodmv** [marktext/marktext#698]
### Question description

I downloaded marktext-0.13.65.exe and Moeditor-0.2.0-win32-x64.zip but either nothing happens when try to open with double click.

**Comment by fxha** [comment]
Could you please run `marktext-0.13.65.exe --version` and send us the output? You can also try to run pure Electron: [v3.0.9](https://github.com/electron/electron/releases/tag/v3.0.9) and/or [v4.0.15](https://github.com/electron/electron/releases/tag/v4.0.5).

**Comment by candidodmv** [comment]
there's no output when i ran this command  "marktext-0.13.65.exe --version"

**Comment by fxha** [comment]
I think thats an issue with your OS or Electron. Maybe Windows block the execution of Mark Text or other compatibility issues. We cannot reproduce the issue, so no action can be taken on our side. If you experience further problems with Electron or Chromium, please open an upstream issue. As mentioned above, you can try to launch pure Electron to be sure: [Windows x64](https://github.com/electron/electron/releases/download/v3.0.9/electron-v3.0.9-win32-x64.zip) or [Windows x86](https://github.com/electron/electron/releases/download/v3.0.9/electron-v3.0.9-win32-ia32.zip).

**Comment by candidodmv** [comment]
@fxha  I've found the cause of this issue: Windows filter SmartScreen was blocking the execution,cause of this, when i try to run i've got no one response even throught console prompt. Thanks so much for attention, and sorry for any inconvenience.
