### ISSUE TITLE
Invalidate image cache when modified on disk

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#703]
### Description

An image is not correctly reloaded when the image is modified on disk.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create image: `![](a.png)`
2. Change `a.png` on disk

**Expected behavior:**

The modified image is displayed.

**Actual behavior:**

The image is not reloaded because it's fetched from cache.

### Versions

- Mark Text: all
- Operating system: all

**Comment by Jocs** [comment]
> Change `a.png` on disk

Do you mean change the name of `a.png` or just replace it to another image with the same name?

**Comment by fxha** [comment]
> Do you mean change the name of `a.png` or just replace it to another image with the same name?

Just modify the existing image. E.g. change the color from red to black.

**Comment by Jocs** [comment]
Is this issue the same with #656 ?

**Comment by fxha** [comment]
I don't think so because we add all images to an "image cache", so we don't have to make continuous http requests but local files may be modified. I think the issue is that we add local files (`file://%path%`) to the cache as well.

**Comment by Jocs** [comment]
After listening to (after we'll do) the local image modification, you also need to inform the editor to reload the markdown file. At this same time, we also need to clear the image cache to ensure the image is loaded?

**Comment by fabiospampinato** [comment]
@fxha Isn't Electron just caching `file://` urls on its own? 🤔

**Comment by fxha** [comment]
> Isn't Electron just caching `file://` urls on its own?

@fabiospampinato  I don't think so because it's only locally, so it wouldn't make any sense, but Chromium may prevent to reload the image because the URL is the same as before on the same HTML element and we may need to add a semi-random suffix like `?r=0`. However, the main issue is  that we don't listen for image changes on disk.

**Comment by fabiospampinato** [comment]
> but Chromium may prevent to reload the image because the URL is the same as before on the same HTML element and we may need to add a semi-random suffix like ?r=0

That's what I meant, i.e. the following:

>  I think the issue is that we add local files (file://%path%) to the cache as well.

I don't think is correct, you don't need to do anything to get this behavior.

**Comment by fxha** [comment]
> > I think the issue is that we add local files (file://%path%) to the cache as well.
>
> I don't think is correct, you don't need to do anything to get this behavior.

If I remember correctly, we're using a map/cache that maps paths/URL's to images for better render performance, so we can reuse the old DOM element instead making another HTTP request. But I'm not totally sure and currently don't have any time to invest the issue.

@fabiospampinato Do you have a similar issue in Notable? That would mean Chromium does caching.

**Comment by fabiospampinato** [comment]
> If I remember correctly, we're using a map/cache that maps paths/URL's to images for better render performance, so we can reuse the old DOM element instead making another HTTP request.

That's interesting, does that help performance a lot? 🤔

> @fabiospampinato Do you have a similar issue in Notable? That would mean Chromium does caching.

[Yes](https://github.com/notable/notable/issues/630), and I'm not doing any kind of manual caching.

**Comment by kiyoka** [comment]
I think it is possible to use a periodic timer to check the update time of image files.

**Comment by rugk** [comment]
Same issue in https://github.com/marktext/marktext/issues/2320

**Comment by kiyoka** [comment]
I have experimented with this issue and found it to be quite difficult.
It seems that Chromium caches the same URL even if I disable the caching of the loadImageMap variable.
