### ISSUE TITLE
Wrong padding when copying a loose list into a tight list

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#706]
### Description

When pasting a list from a different type (loose/tight) into another list, the list types are mixed.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create tight list:
```
- a
- b
- c
```
2. Copy following text:
```
- d

- e

- f
```
3. Set cursor behind `b` and paste the loose list into tight list.

**Expected behavior:**

Either a loose or tight list:

```
- a

- bd

- c

- e

- f
```

or

```
- a
- bd
- c
- e
- f
```

**Actual behavior:**

```
- a
- bd
- c

- e

- f
```

### Versions

- Mark Text: v0.13.65
- Operating system: all

**Comment by Jocs** [comment]
I think copying a loose list to a tight list, or vice versa, the result should be a loose list.
