### ISSUE TITLE
Exception when combining two lists with text in between

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#707]
### Description

An exception occurs when combining two lists with text in between and you make the text to a list.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Template:
```
- a
- b

<cursor>foo

- c
- d
```
2. Write `-<space>` before `foo` to create a list

**Expected behavior:**

The three lists (two lists and the new one) should be combined to a single list.

**Actual behavior:**

Runtime exception.

### Versions

- Mark Text: v0.13.65
- Operating system: all

**Comment by Jocs** [comment]
>The three lists (two lists and the new one) should be combined to a single list.

is it possible to became one loose list and two tight list if you set the prefer list is `loose list`? Because the first and the last lists are tight list.

**Comment by fxha** [comment]
That's true. If `preferLooseListItem` is set to `true` everything is fine except the lists are not combined until you re-parse the document with markedjs.

**Comment by Jocs** [comment]
>until you re-parse the document with markedjs.

will markedjs treat it as one loose list?

**Comment by fxha** [comment]
Yes, it does. As per CommonMark/GFM the following list is a loose list:

```
- a
- d

- c

- d
- e
```

But in this issue it should be a tight list because my default list settings is tight and I want to combine both.

**Comment by Jocs** [comment]
@fxha That's strange, I can not reproduce this issue when I follow you `reproduce steps`. Can you reproduce this bug?

**Comment by fxha** [comment]
Yes, you have to set `preferLooseListItem` to `false`.

**Comment by Jocs** [comment]
It explains the matter. I can reproduce it now.
