### ISSUE TITLE
A hard line break followed by a list doesn't work in preview mode

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#708]
### Description

A list (item) is not recognized as a list when a paragraph ends with a hard line break in preview mode. I don't know if this is allowed in CommonMark and/or GFM because markedjs parses the following code as normal paragraph and list:

```
foo  
- list item
```

is parsed as 

```
foo  

- list item
```

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Write:
```
foo<space><space>
```
2. Press `Shift+Enter`
3. Write a list: `- list item`

**Expected behavior:**

At least a paragraph and a separate list.

**Actual behavior:**

The paragraph is displayed fine but the list is rendered as text and highlighted in gray.

### Versions

- Mark Text: v0.13.65
- Operating system: all

**Comment by Jocs** [comment]
>The paragraph is displayed fine but the list is rendered as text and highlighted in gray.

Can you show me a screenshot?

**Comment by fxha** [comment]
![mt_hard_line_break_list](https://user-images.githubusercontent.com/22716132/53816712-55300280-3f64-11e9-8166-72b78ea007a9.gif)

**Comment by Jocs** [comment]
@fxha I guess that you you want `- bar` will auto to create one list?

**Comment by fxha** [comment]
Yes, that's right but also markedjs parses this example wrong. It's parsed as paragraph and list but not as paragraph with hard line break and list. If you parse

```
foo  
- list item
```

markedjs returns

```
foo  

- list item
```

**Comment by Jocs** [comment]
>that's right but also markedjs parses this example wrong.

How to reproduce this, I find that markedjs still reserve two space at the end to `foo`?

**Comment by fxha** [comment]
> How to reproduce this, I find that markedjs still reserve two space at the end to foo?

Yes, my bad. The example above missing two spaces behind `foo`.
