### ISSUE TITLE
Upstream: prismjs highlighting issues

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#709]
### Description

@Jocs Can you please update our `prism.js` fork because there are multiple issue like:

```cpp
// Set language to cpp
int a() {
  size_t a = 0; // "size_t" is not highlighted
  int64_t b = 0;
}

// Only the first line is highlighted
/*
 * Text
 */
```

**Comment by Jocs** [comment]
@fxha Did `prism.js` already fix this issue?

**Comment by fxha** [comment]
Yes, they have except for `size_t`. Maybe I'll open an issue for that.

**Comment by Jocs** [comment]
@fxha I have updated `prism.js` to the latest commit. but it does not highlight `size_t`. then I found [file](https://github.com/PrismJS/prism/blob/master/components/prism-cpp.js) does not has the keywords `size_t`.

**Comment by fxha** [comment]
The syntax file looks strange because most of the specified keyword aren't keywords. To match a variable type you have to match something like `[a-zA-Z_][a-zA-Z0-9_]*\s` and have to consider further language features.
