### ISSUE TITLE
Add sidebar feature: filebrowser, outlines and tabs

### ISSUE THREAD

**Issue by linpengcheng** [marktext/marktext#71]
### Description

[Add sidebar feature: filebrowser, outlines and md-syntax-list]

### Versions

- Mark Text: 0.7.17
- OS: windows 7

**Comment by Jocs** [comment]
The outline will be included in the sidebar, but the markdown syntax list will not be included.

Because they are already in the paragraph menu and format menu. You also can use shortcuts for these markdown syntax.

**Comment by SonnyBrooks** [comment]
I'd love to see this feature. It'd move me off of Bear.
