### ISSUE TITLE
Default Folder

### ISSUE THREAD

**Issue by S-R0** [marktext/marktext#711]
### Select Default Folder

Would be great to be able to set a default folder on app open! Its a bit of a pain at the moment having to manually open my markdown snippets folder every time I boot the app!

**Comment by fxha** [comment]
Related to #519.

**Comment by fxha** [comment]
@Jocs @S-R0 I think we can close this in favor of #386 and #437?

**Comment by LyteFM** [comment]
I've found a workaround to set a default folder, [at least when not on a mac](https://github.com/marktext/marktext/blob/f5995a24dce043b97fe5d63e32595ec6735bf471/src/main/app.js#L62): You can simply modify your Marktext-Shortcut and pass the path of your default folder as command line argument. On Ubuntu, this can be done by opening `alacarte` (“Main Menu”) and changing the command to:
```
/path/to/marktext.AppImage /path/to/defaultfolder
```
