### ISSUE TITLE
Incorrect autocompletion when using strong format

### ISSUE THREAD

**Issue by PogopunkXIII** [marktext/marktext#739]
### Description

When typing in either `*` or `_` for strong format the autocomplete exhibits some unexpected behavior.

- [x] Can you reproduce the issue? 

### Steps to reproduce

*Note: This occurs with both `*` and `_`*

1. On a blank line type `*`
2. Observe the autocomplete generates a 2nd `*` for emphasized format
3. Without moving the cursor, type another `*`
4. Observe that a third `*` is typed, but not auto-completed
5. Without moving the cursor, type another `*`
6. Observe that this moves the cursor over the existing `*`

**Expected behavior:**

1. Type two `*`
2. Observe 4 `*` with the cursor in the middle like so: `**|**`

**Actual behavior:**

See: Steps to reproduce.

**Link to an example: [optional]**

### Versions

- Mark Text: 0.13.65
- Operating system: Windows 10

**Comment by fxha** [comment]
We've noticed the same thing. The problem was that three `*` are defined as thematic break and we have made changes to correct this on master.

**Comment by mupchrch** [comment]
@fxha is #609 the same issue? If so, you could close that one too while you're at it! 😄
