### ISSUE TITLE
Can't make a comma-separated list of dollar ($) amounts

### ISSUE THREAD

**Issue by mupchrch** [marktext/marktext#740]
### Description

I can't create a comma-separated list of dollar ($) amounts.

It seems dollar signs are being paired and creating math items of some kind. Additionally, I can't even escape the dollar signs with a backslash (\\).

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Copy and paste (or type out) the following into the editor: `$1, $2, $3, $4`
2. Observe issue.

**Expected behavior:**

I expect to see exactly the text that I typed in with no additional formatting.

**Actual behavior:**

I see some of the text looking weird.

**Example:**

![image](https://user-images.githubusercontent.com/5797698/54048482-f1961700-41a7-11e9-9016-a8b9d705c65c.png)

### Versions

- Mark Text: v0.13.65
- Operating system: MacOS v10.12.6

**Comment by fxha** [comment]
Thanks @mupchrch, this is the expected behavior. Dollars (`$text$`) are used for inline math but

1. Both CommomMark and GFM don't support markdown math, so it should be optional via a settings option
2. Dollars should be escapable with `\$` (**bug**)

**Comment by Jocs** [comment]
@mupchrch @fxha Yes it's a bug, as @fxha mentioned above, Both `inline math` and `block math` are not standard syntax in `CommomMark` and `GFM`. So we'll add the user setting option to not enable `math` by default, but you can enable them in user setting in the future.

>Dollars should be escapable with \$ (bug)

Yes it's a bug, there are still other bugs in math syntax, for example can not nested in list, we'll fixed it latter.
