### ISSUE TITLE
Print callback is not called when cancelling the print dialog

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#749]
### Description

When calling `webContents.print` and cancelling the native print dialog the callback is not called directly, only when you open another dialog and/or close the window, which results in undefined behavior and/or an application crash. This upstream issue affects all Electron versions since v3.0.9. If this issue is not fixed till the next release, we have to disable the `File -> Print` feature temporarily.

See upstream electron/electron#16085.

### Versions

- Mark Text: after v0.13.65 (master)
- Operating system: all

**Comment by fxha** [comment]
The initial issue was fixed by the Electron team but this issue is still blocked due a subsequent issue that freeze the whole renderer.

**Comment by Jocs** [comment]
>a subsequent issue that freeze the whole renderer.

I didn't track this issue before, which `subsequent issue` will cause the renderer process freezing?

**Comment by fxha** [comment]
The new issue is tracked in [Electron#19008](https://github.com/electron/electron/issues/19008) but please see [my comment](https://github.com/electron/electron/issues/16085#issuecomment-506869309) for details.
