### ISSUE TITLE
Cannot expand save menu on MAC

### ISSUE THREAD

**Issue by napstercc** [marktext/marktext#751]
### Description

When trying to expand the save menu on mac, it doesn't expand.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Save a document on MAC os 
2. Click the small expand icon to browse folders
3. Bug here

**Expected behavior:**

The save menu expands and we can click through folders
**Actual behavior:**

**Link to an example: https://www.dropbox.com/s/nj7p0ufdq7ca2lw/Screenshot%202019-03-12%2000.43.29.png?dl=0**

### Versions

- Mark Text:
- Operating system:

**Comment by fxha** [comment]
@napstercc Which macOS and Mark Text version do you use?

**Comment by Jerakin** [comment]
I have the same issue
![Screen Shot 2019-03-20 at 11 44 36](https://user-images.githubusercontent.com/5273682/54678545-a663f880-4b05-11e9-9243-06e0afbc9c71.png)

**Comment by napstercc** [comment]
Here;s my info:
![Screen Shot 2019-03-21 at 9 01 30 PM](https://user-images.githubusercontent.com/2672696/54794217-c0442f00-4c1c-11e9-89ac-92534a35304b.png)

**Comment by Jocs** [comment]
@napstercc @Jerakin Can you update you macOs to latest version, and test weather still has this issue?

**Comment by Jerakin** [comment]
Sorry, updating isn't an option to me (work computer)

**Comment by Jocs** [comment]
I'll close this issue, because I think it's not an issue of Mark Text, it maybe due to old macOs version or Electron bugs.
