### ISSUE TITLE
No space around copy-pasted links

### ISSUE THREAD

**Issue by nitingupta910** [marktext/marktext#752]
### Description

When copying some text from web browser (chrome) which contains a link or a inline code block `like this` and pasting it in marktext, there is no space around the link or the copied inline-code-block. See screenshot below.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. copy some text from google chrome which contains some hyperlink or an inline-code-block
2. paste it into marktext
3. BUG: there is no space around hyperlink.

**Expected behavior:**

space should be there around the copy-pasted link.

**Actual behavior:**

No space around pasted link

**Link to an example: [optional]**

<img width="804" alt="Screen Shot 2019-03-11 at 10 34 12 PM" src="https://user-images.githubusercontent.com/1069854/54176950-e532e800-444d-11e9-996b-4fe923a7ad71.png">

NOTE: no space around the two links, or any of inline-code-blocks in the line copy pasted from web.

### Versions

- Mark Text: 0.13.65
- Operating system: MacOS Mojave 10.14.2

**Comment by fxha** [comment]
Thanks @nitingupta910, this issue is only reproducible with a Chromium-based browser.

**Comment by Jocs** [comment]
@nitingupta910 Can you give me the line of the coped text. I'll use to test this bug.

**Comment by nitingupta910** [comment]
@Jocs you can copy-paste any line containing a link. I copied a line from here for e.g.: https://flutter.dev/docs/development/ui/layout

**Comment by Jocs** [comment]
@nitingupta910 fixed almost vanished space.

**Comment by nitingupta910** [comment]
Thanks. Any plans to create a new release soon?

**Comment by nitingupta910** [comment]
I ran the latest master (commit 5d23b08ea98c85de62b0b030eaf02de5af6657ab) to test this fix but found another issue related to it: there are now two spaces before and after the link.

<img width="724" alt="Screen Shot 2019-03-12 at 9 58 54 PM" src="https://user-images.githubusercontent.com/1069854/54254714-1543bf00-4512-11e9-8f4d-a6566de4eb00.png">

**Note**:
 - There are always two spaces _before_ a link e.g. the "ListTile" link
 - After the link, if there is a character like comma then there is no extra space e.g. after "ListTile" or "Material Library" link (correct behavior), otherwise you can see an extra space _after_ the link too e.g. after the "Card" link.

Please let me know if I should file a separate bug for this or we should reopen this one.

**Comment by Jocs** [comment]
>Please let me know if I should file a separate bug for this or we should reopen this one.

Thanks, I think you can reopen this issue, I'll take a look this evening.
