### ISSUE TITLE
Image inside HTML is not loaded

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#754]
### Description

An HTML image (`<img ...>`) is not displayed as image when it's inside a HTML block.

- [x] Can you reproduce the issue? 

### Steps to reproduce
```
<p align="center"><img src="https://raw.githubusercontent.com/marktext/marktext/master/static/logo-small.png" width="100" height="100"></p>
```

### Versions

- Mark Text: all
- Operating system: all

**Comment by Jocs** [comment]
@fxha strange, if I replace the `p` tag with `div`, and the image is rendered.

**Comment by fxha** [comment]
The image is even rendered when you parse:

```
<p align="center">
<img src="https://raw.githubusercontent.com/marktext/marktext/master/static/logo-small.png" width="100" height="100">
</p>
```

**Comment by fxha** [comment]
@Jocs This issue is still present with:

```html
<a href="https://github.com/marktext/marktext/graphs/contributors"><img src="https://opencollective.com/marktext/contributors.svg?width=890" /></a>
```
