### ISSUE TITLE
Issues related to bold or italic text

### ISSUE THREAD

**Issue by h6a8ke1k** [marktext/marktext#755]
### Description

When unbold the text in a part of bolded text, the whole bolded text will become unbolded.
When making a part of bolded text italic, the italic style cannot be removed using keyboard shortcuts or floating toolbox.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Make a word bold.
2. Select one character in the word.
3. Using keyboard shortcuts or floating toolbox to unbold, or italicise.

**Expected behavior:**

Only the character in the word will become unbold.
The italic style can be removed.

**Actual behavior:**

The whole word becomes unbold.
The italic style cannot be removed.

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows

**Comment by Jocs** [comment]
@h6a8ke1k I think this is the correct behavior in Mark Text, So this issue will be closed.
