### ISSUE TITLE
Cursor position issues in bulleted / numbered lists

### ISSUE THREAD

**Issue by h6a8ke1k** [marktext/marktext#756]
### Description

The issues present when using `Up` or `Down` on the keyboard to change the line the cursor at.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a bulleted / numbered list with multiple items.
2. Use `Up` or `Down` to move the cursor among the items.

**Expected behavior:**

The cursor column position will not change.

**Actual behavior:**

The cursor comes to the end of the lines when moving up and the beginning of the lines when moving down.

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows

**Comment by Jocs** [comment]
This is the default behavior and interaction of Mark Text, it will not change for the time being, thank you.
