### ISSUE TITLE
Rendering not correct when inputing chinese characters after bold / italic text

### ISSUE THREAD

**Issue by h6a8ke1k** [marktext/marktext#757]
### Description

Rendering of chinese characters is not correct after bold / italic text. However, the rendering is correct after changing the cursor to a new line. (Maybe the issue is caused by the Microsoft Chinese IME on Win10?)

- [x] Can you reproduce the issue? 

### Steps to reproduce

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows 10

**Comment by Jocs** [comment]
@h6a8ke1k Can you show me one screen shot? or in Chinese?

**Comment by h6a8ke1k** [comment]
@Jocs For your reference:
![11](https://user-images.githubusercontent.com/46216438/54278212-babb6900-45cc-11e9-9e03-72ff04400217.gif)

**Comment by Jocs** [comment]
This is already fixed in the master, and will release in 0.14.0, fill free to reopen it if you have any other question.
