### ISSUE TITLE
brew cask update

### ISSUE THREAD

**Issue by jamesstidard** [marktext/marktext#76]
I see that the brew cask appears to be pointed at an older release then the current. Does this need to be manually updated? 

I did look a little bit into this to see if I could submit the update myself but ended up unsure of how to do it. I see there is a `appcast` attribute on the cask description which I thought might mean it could automatically detect new GitHub releases.

**Comment by Jocs** [comment]
@jamesstidard [update a cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) 
maybe this will work?

**Comment by jamesstidard** [comment]
@Jocs Don't know how I missed this when looking. [Submitted](https://github.com/caskroom/homebrew-cask/pull/45170), thanks.

**Comment by Jocs** [comment]
@jamesstidard thanks for you! If you like, you can submit a PR to change the screenshot in the README after you installed the latest version Mark Text.

**Comment by jamesstidard** [comment]
@Jocs Sure. Just to check, do you mean this screenshot?

![](https://raw.githubusercontent.com/marktext/marktext/master/doc/brew-cask.jpg)

**Comment by Jocs** [comment]
@jamesstidard yes, A `.gif` image is prefer

👍
