### ISSUE TITLE
Emojis don't work properly

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#769]
### Description

I discovered various issues and errors when using emojis:

- emojis are a little to big*
- emojis are not colored*
- top margin in emoji pop-up
- many exceptions when selecting an emoji using the emoji pop-up and click behind the emoji (`:hammer: <click>`)

- [x] Can you reproduce the issue? 

\*: in preview mode but when exporting everything is fine and emojis are colored.

### Steps to reproduce

![mt_emojis](https://user-images.githubusercontent.com/22716132/54451342-f1bb8700-4752-11e9-8373-5d6cdf7b5bcb.gif)

### Versions

- Mark Text: v0.13.65 and master
- Operating system: all

**Comment by Jocs** [comment]
>emojis are a little to big*

I'll resize it later.

>emojis are not colored*

Can not reproduce it on macOs, So can you help with this?

>top margin in emoji pop-up

I'll fix it.

many exceptions when selecting an emoji using the emoji pop-up and click behind the emoji (:hammer: <click>)

I'll take a look.

**Comment by Jocs** [comment]
>emojis are not colored*
>top margin in emoji pop-up

I can not reproduce these two issues.
