### ISSUE TITLE
Allow window transparency

### ISSUE THREAD

**Issue by FelixZY** [marktext/marktext#776]
### Describe your feature request

I thought it would be nice with optional window transparency for Mark Text.

![semi-transparent](https://user-images.githubusercontent.com/2656517/54526706-db424500-4977-11e9-8232-2a8b8368d96c.JPG)

### Additional context

I was looking for a good looking markdown editor and found Mark Text. I like it but wanted a bit of transparency to the window.

I have already implemented this feature using `browserWindow.opacity` where the user may set the window transparency to any value in the range 0.3->1.0 (default 1.0) via Mark Text's preferences.

My implementation does not add any blur, it simply makes the window more transparent. Based on official documentation the implementation should work on windows and mac (tested on windows) and have no effect on linux.

Please let me know if this would be interesting and I can submit a PR.

**Comment by Jocs** [comment]
> My implementation does not add any blur, it simply makes the window more transparent. Based on >official documentation the implementation should work on windows and mac (tested on windows) >and have no effect on linux.

I know it that macOs has this feature, but I didn't test it on windows. does windows also has transparent background?

>Please let me know if this would be interesting and I can submit a PR.

We have the plan add transparent and blur background only on sidebar, But I don't why you need the text(markdown) input area to be transparent?

**Comment by FelixZY** [comment]
> I know it that macOs has this feature, but I didn't test it on windows. does windows also has transparent background?

My personal implementation works for both windows and macOS as it uses the `BrowserWindow.opacity` property. It does not add any blur however (which may or may not be desired on macOS).

> We have the plan add transparent and blur background only on sidebar, But I don't why you need the text(markdown) input area to be transparent?

I just thought it would be a neat feature. I like to have my terminal windows be semi-transparent and think it looks nice. My personal implementation keeps the window opaque as default but allows the user to make it semi-transparent if they wish.

**Comment by Jocs** [comment]
On macOs, I add `vibrancy： dark` to make the window transparent.

```diff
new BrowserWindow({
    show: false,
    minWidth: 450,
    minHeight: 220,
    +vibrancy: 'dark',
    webPreferences: {
      experimentalFeatures: true,
      nodeIntegration: true,
      webSecurity: false
    },
    useContentSize: true,
    frame: false,
    titleBarStyle: 'hiddenInset',
    width: 1200,
    height: 800
  })
```

But I didn't test it on Windows.

**Comment by FelixZY** [comment]
According to official documentation, `vibrancy` is macOS only (https://electronjs.org/docs/api/browser-window). Maybe a combination?

**Comment by fxha** [comment]
@Jocs @FelixZY I like the idea even if it's only supported on macOS and Windows. I would add `windowOpacity` (`float`, default `1`) and `vibrancy` (`string`, default`none` - if needed ). If `vibrancy` is  one of the strings defined in the documentation apply the effect, if not check `windowOpacity` on macOS.

**Comment by FelixZY** [comment]
@fxha How about implementing `semiTransparentWindow` (`boolean` default `false`) where a check is made behind the scenes for macOS. If macOS, inject `vibrancy: dark`, else inject `opacity: 0.95` in the `BrowserWindow` settings.

Perhaps the vibrancy on macOS could be adapted to match the current theme?
> `vibrancy` String (optional) - Add a type of vibrancy effect to the window, only on macOS. Can be `appearance-based`, `light`, `dark`, `titlebar`, `selection`, `menu`, `popover`, `sidebar`, `medium-light` or `ultra-dark`. Please note that using `frame: false` in combination with a vibrancy value requires that you use a non-default `titleBarStyle` as well.

I could alter my current solution to accommodate this but will need someone to run tests on mac as I do not own one.

**Comment by Jocs** [comment]
>Perhaps the vibrancy on macOS could be adapted to match the current theme?

Yes, if the current theme is `dark`, the `vibrancy: dark` is preferred, if the theme is `light`, the value `light` of vibrancy is preferred.

**Comment by fxha** [comment]
@FelixZY @Jocs What is the current status of this?

**Comment by fxha** [comment]
Closing the issue as no further information has been provided. Please feel free to reopen with more information.
