### ISSUE TITLE
Throws an exception on first load

### ISSUE THREAD

**Issue by pgolebiowski** [marktext/marktext#78]
### Steps to reproduce

1. Have a fresh machine that has never seen mark text before
2. brew cask install mark-text
3. Click the app icon in Launcher

**Expected behavior:** don't throw an exception xd

**Actual behavior:** exception xd

<img width="412" alt="screen shot 2018-03-25 at 22 00 21" src="https://user-images.githubusercontent.com/7394091/37879353-f4fd7146-3077-11e8-8a5d-6826237bf2e5.png">

### Versions

- Mark Text: https://github.com/marktext/marktext/releases/download/v0.8.12/marktext-0.8.12.dmg
- OS: macOS 10.13.3

**Comment by asciimo** [comment]
Reproduced on Ubuntu 16.04.4 (marktext-0.8.12-x86_64.AppImage).
