### ISSUE TITLE
Goto, kind of like how caret.io have it

### ISSUE THREAD

**Issue by TobiasDev** [marktext/marktext#783]
### Describe your feature request
I would to have a short cut (eg. something like ctrl+p), where I can quickly start typing a note name and it gives me suggestions. This is quite common in code editors, I would love to see this in Mark Text as well! :) 

### What problem does this feature solve? [optional]
It would just make it faster for me to go between notes. Which I really love personally. 

### Additional context [optional]
I do love the design of MarkText, but maybe taking some small hints from caret.io for the folders and such would also be a nice to have. :D But that is just my personal opionon.

**Comment by fxha** [comment]
@TobiasDev Could you please explain your feature request in a little more detail. Is it related to #581?

**Comment by TobiasDev** [comment]
Yep, sorry I missed that issue! But that is exactly what I meant. :D
