### ISSUE TITLE
Open file that is a symbolic link to another file

### ISSUE THREAD

**Issue by hong-duc** [marktext/marktext#784]
### Describe your feature request
Can handle symbolic link file

### What problem does this feature solve? [optional]
I can use marktext with symbolic file

**Comment by Jocs** [comment]
What's symbolic link?

**Comment by hong-duc** [comment]
It is soft link, I usually call it symbolic link, It only on linux

More info here:
https://www.cyberciti.biz/faq/creating-soft-link-or-symbolic-link/

**Comment by Jocs** [comment]
What features do you need to help you with soft link? Can you explain more detail.

**Comment by fxha** [comment]
@Jocs We do not follow links on all operating systems because a symbolic link is neigher a file nor directory. This is easy to fix/solve because the filesystem resolves the link and node has a high level API for this.
