### ISSUE TITLE
Question about loose list item

### ISSUE THREAD

**Issue by jlnbdt** [marktext/marktext#785]
### Question description

Hello,

I've only been using Mark Text for a short time and I'm wondering about one thing. Each time I use lists, I have to uncheck the "Loose list item" option to get "normal" lists (i.e. lists in which the items are not separated by a white line).

Is this behaviour normal? What is its purpose?

Thank you :)

**Comment by Jocs** [comment]
Order list, bullet list and task list are have two type: loose list and tight list, the difference is that the gap between two loose list item is greater than tight list. You can look into this [GFM](https://github.github.com/gfm/#list).

And Mark Text support both loose and tight list. you can change the `loose/tight` in `paragraph` menu, you can also change the default value in user preference. `"preferLooseListItem": true`. you will always create a loose list item after you set it to `true`.

**Comment by jlnbdt** [comment]
Thank you very much for this explanation 👍
