### ISSUE TITLE
Can not load image when the extension in the url is missing

### ISSUE THREAD

**Issue by leaves4j** [marktext/marktext#79]
### Description
Support using SVG as an image
### Steps to reproduce
`![svg_image](svg_url)` not work
### Versions

- Mark Text: 0.7.17
- OS: macOS 10.13.3

**Comment by Jocs** [comment]
I just test weather Mark Text support SVG image, I found that the SVG image is OK.
![1522069937807](https://user-images.githubusercontent.com/9712830/37908348-917b7c4e-313a-11e8-830c-cc225635901d.jpg)

Can you give me a failed SVG url? So I test it.

**Comment by leaves4j** [comment]
svg url: http://www.plantuml.com/plantuml/svg/SyfFqhLppCbCJbMmKiX8pSd91m00 
![](http://www.plantuml.com/plantuml/svg/SyfFqhLppCbCJbMmKiX8pSd91m00)

**Comment by SuperSandro2000** [comment]
This misses the svg ending

**Comment by leaves4j** [comment]
We can determine the type by Content-Type

**Comment by Jocs** [comment]
@leaves4j Anyway, I think Mark Text should try once more after caret leave image src.
