### ISSUE TITLE
MarkText within Auto File Association

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#794]
### Describe your feature request

Is there a plan to add a function that automatically performs

file association at the time of installation like Typora used before?

**Comment by Jocs** [comment]
@keito940 Can you tell me what is `file association`? or can you describe you feature request more detail?

**Comment by keito940** [comment]
Whenever install the Markdown editor, Editor associate the Markdown file,
but this editor does not associate the Markdown file, so I want it to feature request.

**Comment by fxha** [comment]
Markdown files are automatically associated with Mark Text on Windows via setup and in the next release on Linux (Flatpak and installed AppImage). macOS I don't know.

**Comment by Jocs** [comment]
@keito940 What's your operation system version?

**Comment by keito940** [comment]
Windows 10.

**Comment by fxha** [comment]
@keito940 Markdown files should be automatically registered with `marktext-setup-0.13.65.exe`. Can you confirm this or which package are you using?

**Comment by keito940** [comment]
@fxha Yes.

**Comment by fxha** [comment]
@keito940 Can you please reinstall Mark Text via setup. I've tested it earlier on Windows and files like `.md` are associated.

**Comment by keito940** [comment]
@fxha
It seems that file association has already been done. I'm sorry.

What I want to say is that I am unhappy with the fact that the file description for `.md` associated with Mark Text is MD File.
