### ISSUE TITLE
When running for a long time, it get slower and slower

### ISSUE THREAD

**Issue by AnCoSONG** [marktext/marktext#795]
### Question description
 Just write a long text and gradually it gets slower when you keep typing.

 Is this my personal experience??
what is the solution?

**Comment by Jocs** [comment]
@AnCoSONG Can you tell me how long the file is? word count? how many code blocks?

**Comment by AnCoSONG** [comment]
> @AnCoSONG Can you tell me how long the file is? word count? how many code blocks?
More than 25 code blocks.
In fact, it has not too many words, only about 600 words in Chinese and English.

**Comment by AnCoSONG** [comment]
Only get slower when type in code blocks actually

**Comment by Jocs** [comment]
>Only get slower when type in code blocks actually

Yes, we highlight code block after every typing, we'll optimize it later.
