### ISSUE TITLE
Notification doesn't work any more

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#807]
### Description

Mark Text renderer notification doesn't work any more on master (`src/renderer/services/notification/index.js`).

### Versions

- Mark Text: master
- Operating system: all

**Comment by Jocs** [comment]
@fxha is there the background of notification is missing? this should be fixed in #796

**Comment by fxha** [comment]
There are no notifications but the notification code is triggered.

**Comment by Jocs** [comment]
the `color` in notification is `#fff`, and the background is also `#fff` so can not see it?
