### ISSUE TITLE
Can not remove row or column by context menu

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#813]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Cmd + T to create a table.
2. right click in the table.
3.the remove row or remove column is not shown.

**Expected behavior:**

The context menu contains the remove row or column.

**Actual behavior:**

But not contains remove row or column.

**Link to an example: [optional]**

### Versions

- Mark Text: master
- Operating system: macOs

**Comment by Jocs** [comment]
You need to put the cursor on the cell text if you want to do this.

**Comment by fxha** [comment]
@Jocs Why did you reopen this issue?

**Comment by Jocs** [comment]
Because the previous bug fix will cause another problem, unable to copy and cut by context menu, because when the context menu is displayed, it only refers to the start of the cursor, so I reopened the issue, in fact, it is now possible to insert rows or columns, just the cursor Must be on the text,  I still don't know why.
