### ISSUE TITLE
Loose/tight list error after change by the menu

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#823]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. write markdown:

   ```md
   1) foo
   2) bar
   ```
2. change the loose/tight type by menu, it became a loose list in preview mode.

3. turn into source code mode, it still tight list.

**Expected behavior:**

The list became a loose list.

**Actual behavior:**

It still shown as a tight list in source code mode

**Link to an example: [optional]**

### Versions

- Mark Text:
- Operating system:

**Comment by Jocs** [comment]
@fxha Can you reproduce this again? I can not reproduce it.

**Comment by fxha** [comment]
Seems to be accidentally fixed :laughing:
