### ISSUE TITLE
Side-by-side editing

### ISSUE THREAD

**Issue by thurrott** [marktext/marktext#83]
### Description

This is a feature-request, not a bug. For many, side-by-side editing, with an editor view on the one side and a live preview on the other, is key.

Thanks!

**Comment by notAlaanor** [comment]
I believe this goes against the theme of Mark Text, where everything is minimal and right in front of you. Maybe @Jocs can comment on this.

**Comment by Jocs** [comment]
@thurrott 
The Mark Text editor previews in real time. The area you edit is the preview area, which combines the two together without switching back to the preview and edit modes. This experience is not better?
