### ISSUE TITLE
Replace empty tabs

### ISSUE THREAD

**Issue by Aviortheking** [marktext/marktext#830]
### Describe your feature request

Hi, Hi would like to see an option to change de way we open new, recents, existing files
actually when I launch Mark Text and want to open a file i do File -> Open File but the editor launch it an a new window.

It would be awesome if we could choose where to open theses files like
* new window
* new tab
and when there is an empty default file just replace the empty default file

### What problem does this feature solve? [optional]

not having to close the unused window

**Comment by fxha** [comment]
> - new window
> - new tab

We added a settings option to control whether new files should be opened in a new window or as a tab. The next release will be released soon.

> and when there is an empty default file just replace the empty default file

This will be fixed in v0.15.x.

**Comment by Aviorleking** [comment]
cool thanks !
