### ISSUE TITLE
Loose/tight list error when update paragraph to list

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#831]
### Description

Loose/tight list wrong behavior.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. step 1, set preferLooseList to true in user preference file.
```md
- foo
- bar
-<cursor>zar
- foo
- bar
```

2. press `space` key on keyboard.

**Expected behavior:**

it show became one loose list.

**Actual behavior:**

it became three list, two tight list and one middle loose list. when you change to source code mode, then back, it became one loose list.

**Link to an example: [optional]**

### Versions

- Mark Text: All
- Operating system: All

**Comment by Jocs** [comment]
Another list problem:

1. Set preferLooseList to false.

```md
- foo

- bar

-<cursor>zar

- foo

- bar
```

2. press `space` on keyboard.

Expect behavior:

It became one loose list.

Actual behavior:

It became three list, two loose list and one tight list.

**Comment by fxha** [comment]
@Jocs I cannot reproduce this with the latest master?

**Comment by Jocs** [comment]
@fxha because of #707 ? A PR is raised to fix these two issues, #829

**Comment by fxha** [comment]
@Jocs Another issue on master. Insert code below in source-code mode and switch back to preview. `-bar` is displayed as list item too. I think somewhere missing a space check.

```
- foo
- foo 
-bar
- foo 
- foo
```

**Comment by Jocs** [comment]
I think this is another issue that belongs to #829, I'll open another PR to fix it.

**Comment by Jocs** [comment]
@fxha This is also a problem with upstream `markedjs`, because I test it on the master of `markedjs`.
