### ISSUE TITLE
Windows Defender didn't recognize publisher

### ISSUE THREAD

**Issue by lcdessantos** [marktext/marktext#84]
Got this when running the installer on Windows 10:

![2018-03-27](https://user-images.githubusercontent.com/29223317/37951037-4e4ab444-3171-11e8-934c-ce61107be518.png)

**Comment by SuperSandro2000** [comment]
Dupe #51
Please search at least before opening a new issue

**Comment by SuperSandro2000** [comment]
I would add a label like ``Can't fix``

**Comment by Jocs** [comment]
@SuperSandro2000 There already a label named  `wontfix`
