### ISSUE TITLE
selectionChange may be null

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#848]
### Description

`selectionChange(...)` may be `null` in `getCommonParent(...)` in [paragraphCtrl.js@L20](https://github.com/marktext/marktext/blob/21e6ebc1ff0b8762d436ec23196b7b9a132535dc/src/muya/lib/contentState/paragraphCtrl.js#L20).

### Versions

- Mark Text: master/pre-release
- Operating system: all

**Comment by Jocs** [comment]
This may be fixed in #875.
