### ISSUE TITLE
Can not recognize inline syntax if they are in multiple lines

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#851]
### Description

if markdown inline syntax in multiple lines, Mark Text can not recognize it.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. write foo **bar
2. press <kbd>Shift</kbd> + <kbd>Enter</kbd>
3. write bar** zar

**Expected behavior:**

foo **bar
bar** zar

**Actual behavior:**

foo \*\*bar
bar\*\* zar

**Link to an example: [optional]**

### Versions

- Mark Text: All versions
- Operating system: All system

**Comment by fxha** [comment]
@Jocs There is another issue:

```
a
b
c

d
```

should be rendered as:

```
a b c

d
```

Is this related to this issue or should I open another issue for this?

**Comment by Jocs** [comment]
Do you mean `soft line break` show be rendered in one line? I already explain this in the #849 .

**Comment by fxha** [comment]
> Do you mean soft line break show be rendered in one line?

I think so or add at least a settings option to do so because there is not way to add a soft line break in Mark Text preview mode.

> A conforming parser may render a soft line break in HTML either as a line break or as a space.
> 
> A renderer may also provide an option to render soft line breaks as hard line breaks.

**Comment by Jocs** [comment]
>I think so or add at least a settings option to do so because there is not way to add a soft line break in Mark Text preview mode.

<kbd>Shift</kbd> + <kbd>Enter</kbd> will create a soft line break, if you type two `space` after the first line, it will turn into a hard line break.

>A renderer may also provide an option to render soft line breaks as hard line breaks.

Yes, we can use `css` style to make a soft line break display in two lines.

**Comment by fxha** [comment]
> Yes, we can use css style to make a soft line break display in two lines.

I think we should "render a soft line break in HTML either as a line break or as a space."

**Comment by Jocs** [comment]
>I think we should "render a soft line break in HTML either as a line break or as a space."

Do you mean let user to choose `a line break` or `space` when export html or PDF?

**Comment by fxha** [comment]
> Do you mean let user to choose a line break or space when export html or PDF?

Actually, let the user choose the soft line break behavior (line break or space) in Mark Text because all parsers render a soft line break as space except Mark Text - but it makes sense to render it as line break for a better distinction.

**Comment by Jocs** [comment]
> but it makes sense to render it as line break for a better distinction.

Yes, that's why we render a soft line break in two lines.
