### ISSUE TITLE
Emoji name mismatch

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#856]
### Description

Mark Text emoji's and GitHub's have different names.

**Related links:**

- https://gist.github.com/rxaviers/7360908
- https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb

**Comment by Jocs** [comment]
Hi, @fxha , which emojis are dismatched?

**Comment by fxha** [comment]
I don't know, but all emojis in [README.md](https://github.com/marktext/marktext/blob/master/README.md) are not rendered and I expect there are more missing.

**Comment by Jocs** [comment]
>I don't know, but all emojis in README.md are not rendered and I expect there are more missing.

Oh, I'll take a look when develop 0.15.0.

**Comment by Jocs** [comment]
Mark Text should use this emoji data https://github.com/github/gemoji/blob/master/db/emoji.json.

And github support emojis is:  https://api.github.com/emojis

**Comment by Jocs** [comment]
Mark Text support: 1432 emojis (from above emoji.json)
GitHub full list: 1510 emojis(from API above)

And missing emojis are:

:atom: :basecamp: :basecampy: :bowtie: :electron: :feelsgood: :finnadie: :goberserk: :godmode: :hurtrealbad: :neckbeard: :octocat: :rage1: :rage2: :rage3: :rage4: :shipit: :squirrel: :suspect: :trollface:
