### ISSUE TITLE
# in Code block gets rendered as Heading 

### ISSUE THREAD

**Issue by Montimort** [marktext/marktext#865]
when writing code with # comments in a code block (´´´ #stuff ´´´ ) the #stuff is highlighted as Heading. VSCode and Gitlab don't do that

**Comment by Jocs** [comment]
How to reproduce it, can you give more info?

**Comment by Montimort** [comment]
create a md file with this content: 
# Simple minimal demo markdown
- [ ] Configure network
	- [ ] `As long there is no line between this line and the next`
    ```
    # This is interpreted as heading
    # and also this.

    ```

**Comment by Montimort** [comment]
Github correctly marks it, Marktext not

**Comment by Jocs** [comment]
@Montimort Can you give me the source code of you markdown file, not the rendered file by GitHub.

You can show me a screenshot or use `\` to prevent Github preview it.

**Comment by Montimort** [comment]
you can find it in this zip file
[errordemo.zip](https://github.com/marktext/marktext/files/3046816/errordemo.zip)

**Comment by Jocs** [comment]
What's the version of Mark Text? I test this markdown file by the master branch, and it's look well.

**Comment by Montimort** [comment]
v 0.13.65 on Win 10 

    Am Freitag, 5. April 2019, 09:40:03 MESZ hat Ran Luo <notifications@github.com> Folgendes geschrieben:  
 
 
What's the version of Mark Text? I test this markdown file by the master branch, and it's look well.

**Comment by Jocs** [comment]
@Montimort This issue has been fixed in master branch, and we'll release a new version these days.
