### ISSUE TITLE
New page 

### ISSUE THREAD

**Issue by BenTearzz** [marktext/marktext#866]
### Describe your feature request

Since I really like Mark Text, I think I could use it really well for school. I got really happy when I saw that you exported to .PDF, but it would be nice if you could put a page break. Perhaps this could be done with a regular line break but where it consists of dots or something so that you can tell it apart in the markdown editor.

### What problem does this feature solve? [optional]

Creating documents with content split onto certain pages, useful for school.

**Comment by fxha** [comment]
Duplicate of #355.

**Comment by BenTearzz** [comment]
Oh sorry, thought I had looked through the issues but apparently not :/

**Comment by BenTearzz** [comment]
I've looked at the duplicate issue, I'm not quite sure if page breaks exists or not after reading that. @fxha

**Comment by fxha** [comment]
You can insert HTML/CSS to produce a page break: `<div style="page-break-before: always;"></div>`.

- `page-break-after`
- `page-break-before`

**Comment by CluelessD3v** [comment]
> You can insert HTML/CSS to produce a page break: `<div style="page-break-before: always;"></div>`.
> 
> * `page-break-after`
> * `page-break-before`

Sorry necro, but I get an "Empty Html block" when I use that code, any idea?
