### ISSUE TITLE
How to configure webstorm for debug this project can breakpoint in mainThread?

### ISSUE THREAD

**Issue by 625781186** [marktext/marktext#868]
Thank you very much for your efforts in this project.

I've been studying this project lately, but debugging is a problem.
### Or recommend breakpoint debugging tutorials and settings for other editors.
![image](https://user-images.githubusercontent.com/30521429/55571588-5c4f5980-5738-11e9-8e04-e14241a6f3b9.png)

**Comment by fxha** [comment]
We're using vscode with [this](https://github.com/marktext/marktext/blob/master/.vscode/launch.json) configuration. If you run `npm run dev` (`./.electron-vue/dev-runner.js`) you can use the `remote-debugging-port` on `8315`.

**Comment by 625781186** [comment]
Sorry , I try it , but can't stop in breakpoint when I open single file.

![image](https://user-images.githubusercontent.com/30521429/55603930-ccdd9100-579f-11e9-997c-35ccee875f88.png)
--------------------------------------------------------
I using chrome://insepect 

![image](https://user-images.githubusercontent.com/30521429/55603982-1a59fe00-57a0-11e9-997e-f3129829498c.png)
### at 1 insepect not found `main` folder
![image](https://user-images.githubusercontent.com/30521429/55604141-fb0fa080-57a0-11e9-82f3-cea0e99641c5.png)

### at 2 insepect I add folder to workspace and add breakpoint , still can't stop
![image](https://user-images.githubusercontent.com/30521429/55604038-6ad15b80-57a0-11e9-82a9-10e8cbc4df3d.png)

**Comment by fxha** [comment]
> Sorry , I try it , but can't stop in breakpoint when I open single file.

You need to install `Debugger for Chrome` in vscode.

> I using chrome://insepect [...]
> at 2 insepect not found main folder [...]
> at 1 insepect I add folder to workspace and add breakpoint , still can't stop

Yes, thats right because the `main` scripts don't run in the renderer process but in the main process.
