### ISSUE TITLE
git-lfs / travis-ci

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#87]
Can you please update `git-lfs` in `.travis.yml`, because it always fails to download and install. E.g. use [brew](https://github.com/git-lfs/git-lfs/wiki/Installation#mac-osx) on OSX or temporarily disable OSX build on travis-ci because current build tries to start/hang for 4 hours?

I don't know whether this is because of free open source service or configuration, but the paid service works perfectly fine.

**Comment by Jocs** [comment]
Can you please create a PR for updating` git-lfs`.
👍

**Comment by SuperSandro2000** [comment]
Is there the need to install lfs? I read in a changelog that travis has already lfs installed and if not maybe do it via sudo or homebrew and not from a repo.
