### ISSUE TITLE
List parse error

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#870]
### Description

```md
- [x] foo
- [x] bar
- zar
- rar
```

write markdown above in source code mode, it will be parsed as one bullet list. not a task list and a bullet list.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. write markdown above in source code mode.
2. turn to preview mode.
3. only one bullet list show(by front icon)

**Expected behavior:**

Two list one is task list and the other is bullet list.

**Actual behavior:**

Only one bullet list shown.

**Link to an example: [optional]**

### Versions

- Mark Text: master
- Operating system: All

**Comment by Jocs** [comment]
GitHub also recognize it as one list,  But I think we need to distinguish task list and bullet list by `front icon`, @fxha what do you think?

**Comment by fxha** [comment]
According to GFM Spec markedjs is correct and muya not because it doesn't exist a task list, just a task list item which must be inside a bullet list. So this is a bug in muya because a task list don't exist. I think we should simply show the bullet list icon and remove the `ag-task-list` marker.
