### ISSUE TITLE
Would you release app for  Windows (32bit)?

### ISSUE THREAD

**Issue by linpengcheng** [marktext/marktext#88]
### Description

[Would you release app for  Windows (32bit)?]

### Versions

- Mark Text: 0.8.12
- OS: windows 7 (32 bit)

**Comment by SuperSandro2000** [comment]
Is there even a Windows version that does not have x64?

**Comment by linpengcheng** [comment]
Many Win7 x86 are upgraded from XP x86, Win7 x86 users should be more than x64, of course, the programmer group x64 more。Enterprise development, many programmers also want to support x86, so use x86

**Comment by Jocs** [comment]
@linpengcheng I think you are right, Can you help and create a PR to support (32bit)?

**Comment by Jocs** [comment]
@notAlaanor help wanted. 🎁

**Comment by notAlaanor** [comment]
Is there a problem compiling an x86 version? It should work as far as I know.

**Comment by Jocs** [comment]
@linpengcheng saied:

>Many Win7 x86 are upgraded from XP x86, Win7 x86 users should be more than x64, of course, the programmer group x64 more。Enterprise development, many programmers also want to support x86, so use x86

**Comment by fxha** [comment]
@Jocs We cannot generate x86 and x86_64 nsis setups at the same time because they override itself. We can add a new build script target like `"release:win32": "node .electron-vue/build.js && electron-builder --win --ia32"`, so that you can build the x86 nsis setup, rename it and generate all other packages.

**Comment by SuperSandro2000** [comment]
You run just the command above right?
It is not that easy

**Comment by fxha** [comment]
### Windows installation instructions

First of all install [nodejs](https://nodejs.org/en/download/) and [git](https://git-scm.com/download/win).

Open `cmd.exe` and go to marktext source folder - there must be a `package.json` file. Then run:

1. `npm install` - this might take a while
2. `npm run build`
3. Mark Text setup is located under `build` or use`build\win-ia32-unpacked` folder - have fun
