### ISSUE TITLE
How to copy rich text from marktext and paste it to just like MS-word or web-input-area?

### ISSUE THREAD

**Issue by dingxianye** [marktext/marktext#885]
I selected full text using cmd+a on my mac
Copy using cmd+c
Then paste using cmd+v to web input area
Only markdown format text there
I hope to copy and paste RICH TEXT

**Comment by Jocs** [comment]
Now we only have `copy as HTML`, `copy as Markdown` and `copy as plain text`. If demand a new feature, can you explain you feature request more detail.

**Comment by Jocs** [comment]
What `web input area` do you mean?

**Comment by dingxianye** [comment]
Just think you are writing a mail in web Gmail
Set font size & color, then copy full content and paste to word, you can see what you typed in Gmail ( text retains changed font size & color, that is what I called RICH TEXT )
`copy as HTML`, `copy as Markdown` and `copy as plain text` can not get the same effect as I told above
I'd like to have a function maybe named `copy as RichText`

I hope it works like this:
![image](https://user-images.githubusercontent.com/19801767/55668063-ec0b1a00-5896-11e9-8775-c01557002504.png)

Now marktext works like this:
![image](https://user-images.githubusercontent.com/19801767/55668084-24aaf380-5897-11e9-9934-03baded18042.png)

**Comment by dingxianye** [comment]
Or make it easy
Do marktext have PREVIEW? I didn't find it
If I can preview in web browser or inner browser, I think I can copy it correctly

**Comment by Jocs** [comment]
I understand what you say now, you want to copy text from Mark Text, and paste it to `ms word` or `page`. we'll take this into consideration, PR is also welcomed.

**Comment by Jocs** [comment]
This feature will be release in the coming version 0.14.0.
