### ISSUE TITLE
List indenting does not conform to CommonMark spec (breaks on BitBucket)

### ISSUE THREAD

**Issue by SimonEast** [marktext/marktext#887]
### Description

Mark Text adds 2 spaces to indent sub-bullets inside a list, however [the CommonMark spec](https://commonmark.org/help/tutorial/10-nestedLists.html) says it should be 4. I've also noticed that on BitBucket, sub-items with only 2 spaces of indentation are not indented but are shown on the same level.

- [x] Can you reproduce the issue? 

### Steps to reproduce

When I create a list like:

* Main bullet point
  * Sub bullet point
  * Sub bullet point

**Expected behavior:**

I would expect Mark Text to save the output file as:

```
* Main bullet point
    * Sub bullet point
    * Sub bullet point
```

**Actual behavior:**

Instead it saves it as:

```
* Main bullet point
  * Sub bullet point
  * Sub bullet point
```

And when rendered inside BitBucket, the list appears like:

* Main bullet point
* Sub bullet point
* Sub bullet point

### Versions

- Mark Text: v0.13.65 and v0.14.0-rc.1
- Operating system: Windows 10

**Comment by SimonEast** [comment]
Actually... a deeper look into the spec has [this example](https://spec.commonmark.org/0.28/#example-257) that says 2 spaces should be enough. The number of spaces needs to actually match the size of the "list marker". This doesn't quite align to [this tutorial doc](https://commonmark.org/help/tutorial/10-nestedLists.html) I posted earlier.

Hmmm.... Well since 4 spaces is not invalid. I wonder if that would still be possible to output 4 in order to support BitBucket (otherwise Mark Text will be pretty useless when I'm writing for BitBucket 😞).

**Comment by fxha** [comment]
@SimonEast I'm quoting from GFM/CommonMark:

> [...] a sequence of lines Ls constitute a sequence of blocks Bs starting with a non-whitespace character, and M is a list marker of width W followed by 1 ≤ N ≤ 4 spaces, then the result of prepending M and the following spaces to the first line of Ls, and indenting subsequent lines of Ls by W + N spaces, is a list item with Bs as its contents.

Only the original Markdown Spec by John Gruber’s required a  list indentation by either 4 spaces or one tab. You can change the `tabSize` for tab indentation in settings but this settings is currently ignored for markdown indentation. I think this is a bug and `tabSize` setting should control the indentation of the document (e.g. lists). So I labled this issue as `bug` to fix `tabSize` settings.

**Comment by fxha** [comment]
We fixed the issue and added an option to adjust list indentation:

> - **listIndentation**: The list indentation of sub list items (`"dfm"`, `"tab"` or number `1-4`)
>   - `tab`: Indent subsequent paragraphs by one tab.
>   - `dfm`: Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab, we are using 4 spaces (used by Bitbucket and Daring Fireball Markdown Spec).
>   - `number`: Dynamic indent subsequent paragraphs by the given number (1-4) plus list marker width (default).

For Bitbucket and Daring Fireball Markdown Spec you must set `"listIndentation": "dfm"` (supported by upcoming release or master).

**Comment by fxha** [comment]
Subsequent paragraphs are still not exported correctly.
