### ISSUE TITLE
Pay attention to the .gitignore file

### ISSUE THREAD

**Issue by XanatosX** [marktext/marktext#888]
### Describe your feature request

I'm using the editor to write documentation for our projects. These documentation files exist inside of a repository together with code an IDE relevant config files/folders.

It would be nice if the editor could ignore those special folders and do not show it in the folder overview if they are excluded in the .gitignore file.

![image](https://user-images.githubusercontent.com/10531466/55715233-9ba9ce80-59f4-11e9-9abd-3837ac0c5b1f.png)

### What problem does this feature solve? [optional]

This feature will allow hiding folders in the folder overview to the left. The feature will scan for a .gitignore file and will auto hide those folders right away.

**Comment by fxha** [comment]
@XanatosX Which application version and operation system do you use?

**Comment by XanatosX** [comment]
I'm using Windows 10. The application version is 0.13.65

![image](https://user-images.githubusercontent.com/10531466/55721329-5e007200-5a03-11e9-9a43-59da87303791.png)


![image](https://user-images.githubusercontent.com/10531466/55721284-3c06ef80-5a03-11e9-851f-6d5edd915d20.png)

**Comment by fxha** [comment]
This issue should be fixed on master and we also ignored dotfiles. If you like, you can try the latest release candidate [here](https://github.com/marktext/marktext/releases/tag/v0.14.0-rc.1).

**Comment by XanatosX** [comment]
I will give it a try thank you 👍
