### ISSUE TITLE
No single opening bracket in code mode

### ISSUE THREAD

**Issue by RobertJndw** [marktext/marktext#895]
### Description
There is no possibility to write a single opening bracket in code mode. Usually in code editors you get autocompletion when you type a opening bracket but with 'delete'-key before the closing bracket you are able to delete just the closing bracket.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a code block
2. Type '('
3. Move cursor between the brackets
4. Hit 'delete'-key

**Expected behavior:**
The closing bracket should be removed while the opening bracket remains

**Actual behavior:**
The closing bracket gets removed along with the opening bracket

### Versions

- Mark Text: v0.14.0-rc.1
- Operating system: Windows 10 Pro 1809 Build 17763.404

**Comment by Jocs** [comment]
Two ways to solve your problem:

1. open `Preference` and set `"autoPairBracket": false`.

or

2. type `{<cursor>}`, put one space between `{<cursor|space>}`, then press `delete` key.

**Comment by RobertJndw** [comment]
Thanks for your answer, I think the second one is the more convenient way 😄
