### ISSUE TITLE
Example to create diagrams

### ISSUE THREAD

**Issue by coffeemug13** [marktext/marktext#898]
### Question description
On the websites you show examples of diagrams. Please provide some examples how to create/write them. Maybe also as hint with the "@"

**Comment by Jocs** [comment]
This feature is still in the test, there will be some problems in the export HTML, it should be launched at 0.15.x (May)

Yeh，it will be show in the `@` menu.(quick insert menu)

**Comment by Jocs** [comment]
If you want to experience new features, you can remove the comments and package the app yourself.https://github.com/marktext/marktext/blob/749af381f1fd002e760a901af39fa2b890cbb8c8/src/muya/lib/ui/quickInsert/config.js#L43
