### ISSUE TITLE
Quick Question: Electron App right? Why not for Windows?

### ISSUE THREAD

**Issue by praveenscience** [marktext/marktext#9]
Hey @marktext,

Since this app is an Electron App, why don't you consider releasing for Windows and Linux too? I can help you if you need. 😸 

Cheers!

**Comment by Jocs** [comment]
@praveenscience Because I don't have a windows computer, A windows and Linux version sounds great, If you submit a pr, I will be very grateful.

![](https://i.loli.net/2018/03/10/5aa2c51778fa7.jpg)

**Comment by praveenscience** [comment]
Anytime... 👍  Is it possible to make me a collaborator? So that I can send PRs? 😸  Hey, also, make this "Shout an issue" not "Shot an issue".

![image](https://user-images.githubusercontent.com/1830380/37276411-83ac71a2-25d9-11e8-98c4-b4689ec90ba6.png)

I have [submitted a PR](https://github.com/marktext/website/pull/1).

**Comment by Jocs** [comment]
@praveenscience 3Q, I have merged that PR, fork the repo, update your code, and send PRs?

![](https://i.loli.net/2018/03/12/5aa64ee717882.jpg)

**Comment by praveenscience** [comment]
I have started working on this... Little bit of struggles here and there... There seems to be no PR for this one, but just binaries... 🐱

**Comment by Jocs** [comment]
there is some problem with the [Travil Ci](https://travis-ci.org/marktext/marktext), Because of this, So I can not release windows and Linux versions, I've been solving the problem all day, but I still can't finish it. Can you help me find the reason why Travil Ci failed?

**Comment by praveenscience** [comment]
Travis CI* Yep... Sure, I am just debugging on it... 😄

**Comment by praveenscience** [comment]
You need to let travis know how build for windows and linux. It uses a container specific for iOS. :(

**Comment by Jocs** [comment]
@praveenscience I have released v0.6.14, you can download it, and try it in you windows computer.

**Comment by praveenscience** [comment]
Perfect! :)
