### ISSUE TITLE
Cannot launch after fresh install on macOS

### ISSUE THREAD

**Issue by timwis** [marktext/marktext#90]
### Description

I just installed the app for the first time and I get an error when I try to open it. As a result, there's no way for me to use the app.

### Steps to reproduce

1. Download via macOS button on readme
2. Open application by right-clicking > Open and "allow unidentified source" thing

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

<img width="420" alt="screen shot 2018-03-28 at 12 54 44 pm" src="https://user-images.githubusercontent.com/761444/38044311-5da04d52-3287-11e8-98f2-ee254aa9b70d.png">

### Versions

- Mark Text:
- OS: 10.13.3

**Comment by timwis** [comment]
FYI I tried it from the releases page and it worked. (.dmg link)

**Comment by Jocs** [comment]
@timwis same as #78 , I'll fix the bug in the next release version.

**Comment by fxha** [comment]
Had the same problem with my experimental x86 windows build. Both #78 and #90 should be fixed with commit [bb6e030](https://github.com/marktext/marktext/pull/93/commits/bb6e030201de228799cc3526a6d09db2e5b62232).
