### ISSUE TITLE
CommonMark Spec 0.29 and GFM Spec 0.29

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#905]
### Description

We need to update the markdown specification to:

- [CommonMark Spec 0.29](https://spec.commonmark.org/0.29/)
- [GitHub Flavored Markdown Spec 0.29](https://github.github.com/gfm/)

**Diff:**

- [CommonMark Spec changes in 0.29](https://spec.commonmark.org/0.29/changes.html)

**Comment by Jocs** [comment]
Do you mean update the README.md?

**Comment by fxha** [comment]
Update muya if necessary and markedjs but this is done upstream already.

**Comment by Jocs** [comment]
Yes, the subsequent development of muya should be based on the new standard, but for now, the Spec in the readme and the [comment](https://github.com/marktext/marktext/blob/82d4c74f6292ec4f62501a24e660bb6581b60d0a/src/muya/lib/utils/exportMarkdown.js#L6) in code are modified first.

**Comment by fxha** [comment]
@Jocs Can we close this issue or is it still needed?

**Comment by Jocs** [comment]
@closed
