### ISSUE TITLE
Cannot install via homebrew

### ISSUE THREAD

**Issue by timwis** [marktext/marktext#91]
### Description

Homebrew installation fails saying `mark-text` is unavailable / no cask exists.

### Steps to reproduce

1. `brew cask install mark-text`

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

<img width="779" alt="screen shot 2018-03-28 at 12 58 58 pm" src="https://user-images.githubusercontent.com/761444/38044468-df92fc1a-3287-11e8-8d27-90886e26c819.png">

### Versions

- Mark Text:
- OS: macOS 10.13.3

**Comment by Jocs** [comment]
@timwis Same as #22
