### ISSUE TITLE
The format of references is not displayed when the md file was exported as pdf or html

### ISSUE THREAD

**Issue by WelkinYang** [marktext/marktext#913]
### Description

The format of references is not displayed when the md file was exported as pdf or html
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [use the [^id]]
2. [export file as pdf or html]
3. [and so on...]

**Expected behavior:**

![image](https://user-images.githubusercontent.com/18493279/55929431-3bfb2f80-5c4f-11e9-9aba-7eafd3b5aae1.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/18493279/55929444-50d7c300-5c4f-11e9-8940-36c2b84f139c.png)

**Link to an example: [optional]**

### Versions

- Mark Text:
- Operating system:

**Comment by Jocs** [comment]
>The format of references

What do you mean `format of references`?

**Comment by WelkinYang** [comment]
> > The format of references
> 
> What do you mean `format of references`?

Quotation Markers for Papers and Documents which was used by [^x] in Markdown.
For example:
I learn some paper [^1][^2][^3]
# REFERENCES 
[^1]: xxx
[^2]: xxx
[^3]: xxx

**Comment by Jocs** [comment]
@WelkinYang Can you paste you markdown file so I can test it. pls put in a `md` code block.

**Comment by WelkinYang** [comment]
> @WelkinYang Can you paste you markdown file so I can test it. pls put in a `md` code block.
I post my md file here.
https://paste.ubuntu.com/p/VGQfBP4SWZ/

**Comment by Jocs** [comment]
thanks.

**Comment by atodniAr** [comment]
I got a somehow different issue. 
This is how my references look like in editor:
![image](https://user-images.githubusercontent.com/29804397/67377927-fc77ad80-f5b8-11e9-92a6-9d497d10f28c.png)
If I exported it to pdf or html, the whole reference content would just disappear.
I'm on macOS Catalina with Mark Text 0.15.1

**Comment by atodniAr** [comment]
Oh and as you can see, the link did not render correctly in editor if it's after the reference syntax.

**Comment by Jocs** [comment]
@atodniAr I think you are describe another issue about reference link/image, and this issue is talk about the `footnote` support? can you open another issue about the bug on reference syntax.

**Comment by Jocs** [comment]
@WelkinYang Duplicated with #193 ?

**Comment by atodniAr** [comment]
> @atodniAr I think you are describe another issue about reference link/image, and this issue is talk about the `footnote` support? can you open another issue about the bug on reference syntax.

Hi Jocs, yes the reference link rendering is part of the problem, but the image I shown above is ref link in footnote. It's somehow like WelkinYang's situation, but a bit different as when I export it as html or pdf, all the footnotes disappeared.

**Comment by Jocs** [comment]
>but the image I shown above is ref link in footnote.

It's normal link? not reference link.

We are already work on `support footnote`, you can see more info in this PR https://github.com/marktext/marktext/pull/1546.
