### ISSUE TITLE
Remove table block error

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#938]
### Description

write a table and a paragraph bellow, select All, press backspace, error happened.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. create a table. and input some text in every cells.
2. create a paragraph bellow.
3. select the text at the offset 0 in the first cell to the paragraph.
4. press backspace.

**Expected behavior:**

Delete the table and some text in paragraph.

**Actual behavior:**

Error happened, and no longer writable.

**Link to an example: [optional]**

<img width="1177" alt="屏幕快照 2019-04-14 上午1 59 17" src="https://user-images.githubusercontent.com/9712830/56083567-34a77200-5e59-11e9-8d79-96f0e2f223ea.png">

### Versions

- Mark Text: v0.14.0
- Operating system: All

**Comment by fxha** [comment]
I don't know how to reproduce this issue. What did you mean by "select the text at the offset 0 in the first cell to the paragraph"?

The only issue is when deleting the paragraph:

```
Uncaught TypeError: Cannot read property 'children' of undefined
    at A.children [as clickHandler] (webpack:/src/muya/lib/contentState/clickCtrl.js:114)
    at HTMLDivElement.clickHandler (webpack:/src/muya/lib/eventHandler/clickEvent.js:91)
```

**Comment by Jocs** [comment]
Another way to reproduce this issue:

type markdown bellow:

```md
| <selectionStart>foo | bar |     |
| --- | --- | --- |
|     |     |     |
|     |     |     |
|     |     | zar<selectionEnd> |
```

Select text as above, then press backspace , error happened. All editor gone.
