### ISSUE TITLE
[Website] maxOS -> macOS

### ISSUE THREAD

**Issue by luckman212** [marktext/marktext#939]
Hello,

Not a bugreport with marktext, just the website:
![image](https://user-images.githubusercontent.com/1992842/56087020-b33be980-5e30-11e9-8b12-7eb658cfcfbf.png)

it should be "macOS" 😊

**Comment by Jocs** [comment]
Ithink this maybe fixed, please remove browser cache and reload browser again.


发自我的 iPhone

**Comment by luckman212** [comment]
Yes, after refreshing it's fixed. Thank you!
