### ISSUE TITLE
All the data deleted when   put down Command-Z as source code mod in mac

### ISSUE THREAD

**Issue by yujiaao100** [marktext/marktext#94]
### Description

[Description of the bug or feature]
     All the data deleted when   put down Command-Z as source code mod in mac

### Steps to reproduce
1.  edit something without source code
2. change to source code
3. push Command-Z and then all things editing will be delete

**Expected behavior:** [What you expected to happen]
Command-Z undo last input
**Actual behavior:** [What actually happened]
Command-Z delete all things editing
**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

### Versions

- Mark Text: 版本 0.7.17 (0.7.17.189)
- OS:  macOS Sierra 10.12.6

**Comment by Jocs** [comment]
@yujiaao100 thank you for reporting this bug.
