### ISSUE TITLE
Feature Request: open other types of text files

### ISSUE THREAD

**Issue by sahil48** [marktext/marktext#940]
### Describe your feature request

I would like to be able to open .taskpaper files and other text based files in marktext, preferably with syntax highlighting, because it is more convenient to have all text files open in one app rather than multiple applications. Currently, marktext only allows markdown and .txt files to be open. It would be great to have an option to permit other text file formats to be open by marktext, possibly as a gigantic code block, and specify the syntax highlighting for the given file to apply.

**Comment by Jocs** [comment]
Is .taskpaper file is a standard markdown file?

发自我的 iPhone

**Comment by sahil48** [comment]
.taskpaper is not a standard markdown file, but a text-based file format (https://guide.taskpaper.com/getting-started/). It's used more for keeping track of different tasks that you need to do. I find it convenient to have it opened alongside other markdown files because it helps guide me in what other files I would be opening.

In this feature request, I was also alluding to the ability to open other types of files like code files (ex. .java files) so that they can be edited and also copied and pasted more easily to markdown files. In a similar way, being able to open image files and .csv files so that they can be copied and pasted in opened marktext documents more easily would also be nice.

**Comment by fxha** [comment]
Mark Text is just a markdown editor, we'll not support other file type like java source files. I think that `taskpaper` files are out of scope also because it's a proprietary application and file format. What is your option, @Jocs?

**Comment by Jocs** [comment]
At least for now, Mark Text will only support editing of markdown files in the near future. This guarantees the unity of responsibility.
