### ISSUE TITLE
Two spaces linebreak

### ISSUE THREAD

**Issue by Li-An** [marktext/marktext#941]
### Description

Traditionally, two spaces at the end of a line gives a linebreak in Markdown. Not in Mark Text. After hitting Enter, I get a new paragraph.

- [ ] Can you reproduce the issue? yes: `[x]`

### Steps to reproduce

Type two spaces + Enter.

**Expected behavior:**

The cursor should go to next line in the same parapraph. Not create a new paragraph.

**Actual behavior:**
It creates a new paragraph.

### Versions

- Mark Text: v0.14.0
- Operating system: Win 10 64 bits

**Comment by Jocs** [comment]
>Traditionally, two spaces at the end of a line gives a linebreak in Markdown. Not in Mark Text. After hitting Enter, I get a new paragraph.

If you want to create a soft line break or hard line break, pls use `Shift` + `Enter`.
a hard line break with 2 space after the first line.

**Comment by Li-An** [comment]
OK, thanks.
