### ISSUE TITLE
Copy paste code block does not respect indentation

### ISSUE THREAD

**Issue by domlysz** [marktext/marktext#942]
### Description

When copy paste a text from a code fence, the pasted text loses the indentation

### Steps to reproduce

1. create a new code fence and write 3 lines with different level of indentation (4 spaces for one tab)

```
no indent
    first level indent
        second level indent
```

2. copy the text and paste it in another text editor, the result look like this :

```
no indent
 first level indent
 second level indent
```

**Expected behavior:**

Respecting indentation setup

**Actual behavior:**

Each indented line have only 2 spaces at the beginning regardless of their level of indentation

### Versions

- Mark Text: 0.14
- Operating system: Linux Ubuntu 64bits

**Comment by fantazer** [comment]
have same problem, pls fix it
