### ISSUE TITLE
Whether gitlab is supported？

### ISSUE THREAD

**Issue by icodeing** [marktext/marktext#944]
After I edit marktext, I submit it to git, and I can see the result in gitlab. However, when I edited Markdown in gitlab and pulled it up again locally and opened it with Marktext, I found that the layout and layout were all messed up.
Looking forward to the solution

**Comment by Jocs** [comment]
Hi, can you paste a copy of you markdown file here, so we can test?

**Comment by icodeing** [comment]
### 获取代码信息接口


| 接口详情 |                  |
| ---- | ---------------- |
| 请求地址 | /getcode |
| 请求方式 | GET              |

请求参数：

| 参数名     | 类型  | 是否必须 | 说明  |
| ------- | --- | ---- | --- |
| code | int | 是    |     |

Common：

| 字段         | 类型     | 说明     | 描述  |
|:---------- | ------ | ------ | --- |
| aCode | string | 通用代码   |     |
| aName | string | 通用代码说明 |     |

#### 返回结果：

```json
{
 "status": "success",
 "data": [{
 "aCode": "01",
 "aName": "私用"
}, {
 "aCode": "02",
 "aName": "共用"
}]
}
```

I don't know if it works after pasting and copying the web page, but if you copy Markdown from gitlab into a text file and then from a text file into Marktext you can display the original format. If I copied the source code directly from gitlab to Marktext, the layout would definitely be garbled, as I used version 0.13.65.

**Comment by Jocs** [comment]
Please put you markdown file in a fence code block, so I can see the source code?

发自我的 iPhone

**Comment by icodeing** [comment]
你的什么邮件？把格式都弄没了~

**Comment by Jocs** [comment]
我的意思你可以把你的 markdown 文件复制到评论区：只需要将它放到一个 markdown code block 里面就好了。

```md
### Sample markdown

- foo
- bar
```
