### ISSUE TITLE
Toggle formatting

### ISSUE THREAD

**Issue by skyblue002** [marktext/marktext#945]
### Describe your feature request

It would really help writing to flow better if the shortcuts were toggle on/off, particularly for formatting that has start and end tags, such as: bold, italic, and strikethrough.

### What problem does this feature solve? [optional]

This solves the lack of a toggle function. It allows text to flow more smoothly when typing. It also helps to imitate other editors (both markdown and non-markdown), thus making the transition to this app easier.

### Additional context [optional]

At the moment, if I'm typing a sentence and want to make something bold, I would press cmd+b (MacOS). At this point, it would add four asterisks and put the cursor at the center. Then, whatever I type would be bold. But, if I press cmd+b again, it removes all the bold formatting. It would be nice if the second cmd+b were to turn it off. At this point, I have to either move the cursor past the two end asterisks or type them in manually. It doesn't flow that well when writing.

**Comment by Jocs** [comment]
>It would be nice if the second cmd+b were to turn it off. 

What do you mean `turn it off`?

**Comment by fxha** [comment]
@Jocs Like in your favourite office application, click on bold and you write text in bold until you disable bold text.

**Comment by Jocs** [comment]
@fxha like rich text editor?

**Comment by fxha** [comment]
Yes exactly.

**Comment by skyblue002** [comment]
@Jocs I apologize for my delayed response, I didn't see that you had replied to me. I agree with what @fxha had said. My suggestion is comparable to the way formatting works in office applications (or, as you had said, in a rich text editor).

**Comment by Jocs** [comment]
@skyblue002 The markdown syntax is quite different from rich text. There is a clear sign in the markdown that identifies the end of the markdown syntax, so it's hard to type input like rich text.

**Comment by skyblue002** [comment]
@Jocs the [Ulysses](https://ulysses.app/) editor is a markdown editor and has this feature, so I know that it is possible. When toggling the format (e.g. bold, italic, etc.) off, the cursor shifts past the end of the markdown tag, so that you can keep typing uninterrupted.

**Comment by Jocs** [comment]
Close this issue because the feature conflicts with the current Muya design. or you can put the cursor before the markdown syntax marker manually?
