### ISSUE TITLE
Please provide a Linux install instruction

### ISSUE THREAD

**Issue by DIYer22** [marktext/marktext#95]
Please provide a Linux install instruction

### Description

I download Linux vision `marktext-0.8.12-x86_64.AppImage`
I don't find any instruction for Linux
and I try : 
```bash
chmod +x marktext-0.8.12-x86_64.AppImage
./marktext-0.8.12-x86_64.AppImage
```
raise this error:
![screenshot from 2018-03-29 20-21-18](https://user-images.githubusercontent.com/10448025/38088689-427c5f08-338f-11e8-99d1-11f6e7d20495.png)

My system is `ubuntu 16.04`
And I am not Familiar about front-end stack.
Thanks！

**Comment by DIYer22** [comment]
I try `./marktext-0.8.12-x86_64.AppImage` another time
And it has been worked ......

**Comment by SuperSandro2000** [comment]
#78 #90
