### ISSUE TITLE
the window close button are not aligned to right side in Windows

### ISSUE THREAD

**Issue by orangejuice** [marktext/marktext#950]
### Description

the window close button are not aligned to right side in Windows 10 OS.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

for example:
![](https://i.loli.net/2019/04/16/5cb50d929d7c9.jpg)

the window close button are exactly closed to the right side of screen.

**Actual behavior:**

![](https://i.loli.net/2019/04/16/5cb50d4eceaf7.jpg)

(the white background color make it not visible, please select it to see the boundary)

**Link to an example: [optional]**

### Versions

- Mark Text: 0.14
- Operating system: windows 10

**Comment by fxha** [comment]
@orangejuice We using a custom theme but we can change the buttons to look like the Windows buttons.

**Comment by orangejuice** [comment]
@fxha actually just justify the close icon in custom theme aligned to right side, then it would be fine, right? 😆
