### ISSUE TITLE
when words over than the sidebar width, the layout will get messy

### ISSUE THREAD

**Issue by orangejuice** [marktext/marktext#951]
### Description

when words over than the sidebar width, the layout will get messy

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

![](https://i.loli.net/2019/04/16/5cb50fcc0aa6b.jpg)

**Link to an example: [optional]**

### Versions

- Mark Text: 0.14
- Operating system: windows 10

**Comment by fxha** [comment]
@Jocs I think we can close this issue because I removed the above view in #1034 because I think it's redundant and also not necessary. Find in files or the tree view should be used instead or do you want to keep this view?

**Comment by Jocs** [comment]
I still want to keep the list view for two reasons:
1. Sometimes a markdown file will be found in a deeply nested folder, which is not easy to find. The list view allows all markdown files in a folder to be displayed at a flat level.
2. list view shows more information than tree view, such as updated time, creation time, etc.

**Comment by fxha** [comment]
OK, if you have time you can review #1054 first and the we can discuss this in the associated PR because #1054 is blocking other PRs.

**Comment by Jocs** [comment]
@fxha I will review as soon as possible, it should be in the last one or two days.

**Comment by Jocs** [comment]
Closed due to we deprecated the list view in the next released version.
