### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by TobiasDev** [marktext/marktext#955]
### Describe your feature request
I love MarkText (it is missing a mobile app, but I can always use something else for that at the moment), but one thing I'm personally missing is that it could encrypt all my notes. Maybe I'm using MarkText in a "wrong" way, because I'm currently using it as an Evernote alternative, for all my notes. After Evernote I switched to Joplin, which is quite good, but does have it's knacks. 

I don't know if this is possible in MarkText, but if possible I would love to see encryption included in it, so when I store my notes in the cloud not worrying about everyone being able to read them. 

Maybe togheter with NextCloud sync in the same way Joplin does it, it is also open-source, so in theory someone could look into how Joplin solved these features. 

### What problem does this feature solve? [optional]
It would feel safer since I want to be able to access my notes both on mobile and pc, so I store them in the cloud.

**Comment by fxha** [comment]
Mark Text is a markdown editor and so this feature is not very high prioritized but I think we can add encryption via a plugin later. You could use gocryptfs or NextCloud extensions if possible. The main focus is still to improve the overall user experience and stability of Mark Text. Personally, I think the file system, cloud provider/sync application should implement encryption and not Mark Text.

For mobile please see #639.

**Comment by TobiasDev** [comment]
Yeah, the problem with letting NextCloud do it, is that I can't sync a whole folder to my phone. :( So I would have to sync note per note. Unless it is done by the writing app, but I can understand that is a low prio task! :)

**Comment by fxha** [comment]
I'm closing the issue because the request is currently out of scope of Mark Text.
