### ISSUE TITLE
The absolute path of an image displays incomplete

### ISSUE THREAD

**Issue by HuadingLing** [marktext/marktext#956]
### Description

When using the absolute path way (by using the menu) to insert an image, the absolute path of an image in realtime preview displays incomplete (**missing the last letter** of the expanded-name)

For example, the absolute path of the image is:

```
L:\GitHub\test1\im.jpg
```

in realtime preview (missing "g"):

![1](https://user-images.githubusercontent.com/41478600/56296259-b43a8700-6160-11e9-8383-9cb75d358437.PNG)

same as png or gif file

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text: 0.14.0
- Operating system: Windows 7

**Comment by fxha** [comment]
I think there are two issues. The first is that the image `alt` attribute is an absolute path on Windows and the second that  `titleContent` and `srcContent` are wrong in [image.js](https://github.com/marktext/marktext/blob/f4f5ba3e007d2868331bcc16615fde9fa188e26c/src/muya/lib/parser/render/renderInlines/image.js#L22) when the path contains special characters like `-` and `_` on all operating systems.

**Linux:**

```
src: file:///home/felix/projects/nodejs/marktext/static/logo-96px.png
titleContent: ["![logo-96p"]
srcContent: ["(/home/felix/projects/nodejs/marktext/static/logo-96px.pn"]
token: {
  alt: "logo96px"
  backlash: {first: "", second: ""}
  marker: "!["
  range: {start: 0, end: 71}
  raw: "![logo-96px](/home/felix/projects/nodejs/marktext/static/logo-96px.png)"
  src: "/home/felix/projects/nodejs/marktext/static/logo-96px.png"
  srcAndTitle: "/home/felix/projects/nodejs/marktext/static/logo-96px.png"
  title: ""
  type: "image"
}
```


**Windows:**

```
src: file://C:\Users\Felix\Documents\nodejs\marktext\static\logo-96px.png
titleContent: ["![C:\Users\Felix\Documents\nodejs\marktext\static\logo-96"]
srcContent: ["](C:\Users\Felix\Documents\nodejs\marktext\static\logo-96px.p"]
token: {
  alt: "C\Users\Felix\Documents\nodejs\marktext\static\logo96px"
  backlash: {first: "", second: ""}
  marker: "!["
  range: {start: 0, end: 123}
  raw: "![C:\Users\Felix\Documents\nodejs\marktext\static\logo-96px](C:\Users\Felix\Documents\nodejs\marktext\static\logo-96px.png)"
  src: "C:\Users\Felix\Documents\nodejs\marktext\static\logo-96px.png"
  srcAndTitle: "C:\Users\Felix\Documents\nodejs\marktext\static\logo-96px.png"
  title: ""
}
```

**Comment by fxha** [comment]
### Steps to reproduce

This issue can lead to a renderer freeze!

1. Create an image named e.g. `luca-bravo-217276-unsplash.jpg`
2. Write foo and insert an absolute image via menu
3. Set cursor after `76-unspla)<cursor>` and press space (path is inserted wrong)

![mt_img_crassh](https://user-images.githubusercontent.com/22716132/56852006-bf867300-6915-11e9-91a0-72fb7da4d4f8.png)

**Comment by Jocs** [comment]
@fxha  I think this issue no longer existed on develop branch? can you help confirm this.
