### ISSUE TITLE
Headers' level not displayed properly in Side Bar

### ISSUE THREAD

**Issue by die4live** [marktext/marktext#966]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. create a new md file with content:

```
# H1-0

## H2-0.1

### H3-0.1.1

## H2-0.2

### H3-0.2.1

#### H4-0.2.1.1

### H3-0.2.2

## H2-0.3
```

2. the levels will be like this:
![image](https://user-images.githubusercontent.com/1461437/56488240-6e8b0f00-6510-11e9-98a7-93c5b87bbc3c.png)

3. but the right way should be (from another editor Typora):
![image](https://user-images.githubusercontent.com/1461437/56488249-75b21d00-6510-11e9-8dd3-8e7729178244.png)

**Expected behavior:**

All the headers with same level should be align with or without any sub header.

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text: v0.14.0
- Operating system: MacOS

**Comment by die4live** [comment]
And I can't understand why some show `#` and some not.

What's more, the folding/unfold status is not remembered EVEN without close and reopen. Each time you move focus area to text editor, the TOC will be restore into all folded.

One more thing, clicking on the header in side bar have no effect, which is expected to jump to that header in the text edit area with auto scrolling, or what's the point of having this feature used for?

**Comment by Jocs** [comment]
@die4live yes, we need to remove the front `#` if it's a header marker. PRs is also welcomed.
