### ISSUE TITLE
Tab to send text cursor at the end of a block

### ISSUE THREAD

**Issue by Li-An** [marktext/marktext#967]
### Describe your feature request

Hello, I’ve tested a lot of Markdown editors and MarkText is one of my favorites. But it lacks a feature I love in Caret (https://caret.io/). 
In both, when typing Markdown syntax, there is an auto completion functionality very handy (like `*text*`, first * shows automatically second * and you type your text.  
In Caret, text cursor can be send automatically after last Markdown character with Tab key. Very very handy. I wish it could be the same in MarkText.

**Comment by Jocs** [comment]
Can you explain you feature request more detail?

**Comment by Li-An** [comment]
I will try (my English is not very good).

Suppose you want to type this block `**this is it**`. You type `**` in MarkText and you have `**|**` showing and you begin to type your text. At the end of you text, you need to move the cursor outside the `**`. For this, you have to click outside `**this is it**` to move the text cursor or use the direction arrows.

In Caret, **Tab** puts automatically the text cursor at the end of the block (even if there is other content after the block).

If it’s still not clear, I will try to make a capture :-)

**Comment by Jocs** [comment]
@Li-An Thanks, I understood now, I think the feature is very useful!

**Comment by Li-An** [comment]
Great you like it :-) I may suggest other features I like as I tested every Markdown Editor for Windows I think :-)
