### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by lengain** [marktext/marktext#971]
### Describe your feature request
Autosave is an important feature of edit/write software that prevents users from losing written content for a variety of reasons.
another
When I exit the software, if I change the content of the text, I want to add a reminder whether to save the modified content

**Comment by fxha** [comment]
We already have an auto save feature under `File -> Auto Save`. I think we should improve this feature to support a save delay. "File Recovery" and sessions/workspaces will be implemented also soon (#732).

**Comment by scouredimage** [comment]
If you can't make a stable editor maybe enable this by default? I just had it crash on me and lose an hour's worth of work. Never again will I use this product.

**Comment by AchalS-iglu** [comment]
> If you can't make a stable editor maybe enable this by default? I just had it crash on me and lose an hour's worth of work. Never again will I use this product.

just had the same issue :/
