### ISSUE TITLE
HTML export: Make font embedding optional

### ISSUE THREAD

**Issue by mahdix** [marktext/marktext#972]
### Describe your feature request

When exporting to HTML, the output size is too big (1.9MB) which can cause issue in some cases. 
Please provide a flag where is checked, fonts will be embedded inside output HTML, otherwise, they will be linked or just named in the css without a link to source of the font.

**Comment by Jocs** [comment]
@mahdix In fact, I am not sure whether the user accepts a folder, including images, fonts, css, html, etc. when outputting html?

**Comment by mahdix** [comment]
Some people may need to email the output HTML and sending a 1.9MB html file as email for a one line content does not seem very interesting.

What I'm trying to say is that there should be a way to have a smaller output file (either by putting assets separately or linking to them from online websites e.g. for publicly available fonts)

**Comment by fxha** [comment]
The problem here is that katex resources are added by default that should be only included if the markdown document contains math (blocks).

**Comment by cplerch** [comment]
There is nothing wrong with embedding binary resources in a HTML file as long as those blobs are referenced from within the document. Clearly, embedding unused resources, like all this KaTex stuff, even when never used in the document, is inefficient and annoying.
