### ISSUE TITLE
文字和公式排版问题

### ISSUE THREAD

**Issue by McGiRG3z** [marktext/marktext#974]
![image](https://user-images.githubusercontent.com/48904579/56844249-d90cc800-68df-11e9-9cd2-115d6fe0ffcc.png)

![image](https://user-images.githubusercontent.com/48904579/56844253-ec1f9800-68df-11e9-91b1-e4f68f63a6b8.png)

开发者你好，

我是由Typora转用Mark Text的，目前最为困扰的是文字和公式混合排版的问题，如图所示，如果一个公式比较“高”，那么排版就看起来很奇怪了，能不能像Typora那样，文字和公式能够水平居中对齐，看起来会和谐很多。谢谢!

**Comment by Jocs** [comment]
>我是由Typora转用Mark Text的，目前最为困扰的是文字和公式混合排版的问题，如图所示，如果一个公式比较“高”，那么排版就看起来很奇怪了，能不能像Typora那样，文字和公式能够水平居中对齐，看起来会和谐很多。谢谢!

感谢你的建议，这应该是一个行内数学公式？我们在后续会修改，当然，也希望你提交一个修复的 PR。

**Comment by McGiRG3z** [comment]
> 
> 
> > 我是由Typora转用Mark Text的，目前最为困扰的是文字和公式混合排版的问题，如图所示，如果一个公式比较“高”，那么排版就看起来很奇怪了，能不能像Typora那样，文字和公式能够水平居中对齐，看起来会和谐很多。谢谢!
> 
> 感谢你的建议，这应该是一个行内数学公式？我们在后续会修改，当然，也希望你提交一个修复的 PR。

谢谢超快回复！

是行内公式，我使用的分数是\dfrac 。

**Comment by Jocs** [comment]
@McGiRG3z 能把你的数学公式贴到这儿吗？便于调试

**Comment by McGiRG3z** [comment]
> 
> 
> @McGiRG3z 能把你的数学公式贴到这儿吗？便于调试


测试公式一：$\dfrac{a}{1+\dfrac{b}{c}}$

测试公式二：$\frac{a}{1+\frac{b}{c}}$


![image](https://user-images.githubusercontent.com/48904579/56847360-56e6c880-690c-11e9-9a27-77df29740aa6.png)

![image](https://user-images.githubusercontent.com/48904579/56847362-61a15d80-690c-11e9-8d7a-974a66a705b4.png)
