### ISSUE TITLE
Regression: math block edit and preview box

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#982]
### Description

Math blocks (`$$\n ... \n$$`) should be editable without the HTML hover edit protection.

### Steps to reproduce

1. Write `$$<enter> foo <enter>$$<enter>bar`
2. Hover over the math block (the HTML edit protection is shown)
3. Click inside the math block

**Expected behavior:**

No HTML edit protection should be shown and the math preview and edit box is shown when clicking inside the box.

**Actual behavior:**

![mt_math_block_edit](https://user-images.githubusercontent.com/22716132/56851108-b0022c80-690b-11e9-9507-fce5d98dabce.png)

### Versions

- Mark Text: master
- Operating system: all

**Comment by Jocs** [comment]
@fxha Do you mean click the math preview and jump to edit math block directly?
