### ISSUE TITLE
Support pasting image (directly) from clipboard.

### ISSUE THREAD

**Issue by iondex** [marktext/marktext#993]
### Describe your feature request

Support paste image directly from clipboard.

1. Some applications (e.g. screenshot app, or Wechat) can save image in clipboard, pasting directly from clipboard into editor would be very convenient.
2. Copy a image file in Explorer, and then paste it in the editor. This would also be useful.

This feature seems not very hard to implement under Windows. Not sure for other platforms.

**Comment by fxha** [comment]
Duplicate of #627
