### ISSUE TITLE
Support of full or large width of edit 

### ISSUE THREAD

**Issue by yodatak** [marktext/marktext#994]
### Describe your feature request
I want to be able on large screen to use a larger edit width

### Additional context [optional]
![Capture d’écran de 2019-04-29 22-50-41](https://user-images.githubusercontent.com/704477/56926188-62372100-6ad1-11e9-9216-3a22cdbc8576.png)

**Comment by yodatak** [comment]
I think this issue could help #750

**Comment by Jocs** [comment]
We should add a custom editor width in a future release.

**Comment by fxha** [comment]
Duplicate of #1053
