### ISSUE TITLE
Mark Text Preference

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#998]
### General

AutoSave: Boolean `true` of `false`

autoSaveDelay (#971) 

Remember last typewriter and focus mode: Boolean #519 

titleBarStyle: String `csd`(macOS only), `custom` or `native`

openFilesInNewWindow: Boolean `true` of `false`

aidou: Boolean `true` or `false`

keybindings

File Sort in folder: by created time, modifed time or title. #438 

Start up options:

-   open custom folder (with auto show sidebar and hide tabs)
    
-   open last opened folder and tabs (width auto show sidebar and tabs) #437 #386 
    
-   open blank tab. (hide hide sidebar and tabs)
    

Language: (v0.17.0) #138 #308 

Import and Export user setting file (`json file`).

subscription user need to input E-mail (v0.17.0)

### Editor

Font Size: default is 16px and the range is 12px ~ 18px #264 

editorFontFamily: default is `Open Sans`

lineHeight: default is `1.6` range is 1.2 ~ 2

autoPairBracket: Boolean

autoPairMarkdownSyntax: Boolean

autoPairQuote: Boolean

endOfLine: `default` `lr` `crlf`

textDirection: `ltr` or `rtl`

codeFontFamily: `DejaVu Sans Mono`

codeFontSize: default is `14px` range is 12px ~ 18px

hideQuickInsertHint: Boolean

Image: paste and drag drop image action, select one: #627 #549 #97 

1.  upload to cloud if user added his own image cloud.
    
2.  Special folder, we'll create a default folder and user can change it. #949 
    
3.  relative path if file already saved to somewhere or absolute path.
    

If user insert image by input `![]()` or shortcut, user can select one of above three action. #922 

Move all or single images to the default folder or upload to cloud.

### Markdown

preferLooseListItem: Boolean

bulletListMarker: default is `-`, you can also select `*` and `+`.

orderListDelimiter: default is `.` you can also select `)`

preferHeadingStyle: `atx` or `setext`

tabSize: 4space or another ?

listIndentation: `dfm`, `tab` or number `1~4`.

### Themes

Select the offical 6 themes.

Open the themes folder so you can modify the offical themes.(v0.16.0) **notice user backup first**. #902 

Import Custom theme (a folder includes fonts file?)(v0.16.0) #959 #174

**Comment by Jocs** [comment]
@fxha I advanced Mark Text Preference to v0.15.0 because I found that many of the features of v0.15.0 are currently related to Mark Text Preference.

**Comment by fxha** [comment]
I think we should prefix the entries with the category like `file`, `editor` etc.

> Remember last typewriter and focus mode: Boolean #519

Please note that this can be overwritten by a session, so we can use the settings as default/fallback values.

> Import and Export user setting file

What do you mean? `electron-store` saves data as JSON file.

> subscription user need to input E-mail 

What do you mean?

Please add `autoSaveDelay` (#971) to the list, so that changes are saved after a short delay to improve performance. Do you plan to add "real" GUI settings in v0.15.0?

I think I can commit a WIP PR from  main refactoring later or tomorrow. I think we have to rebase a lot if we working on both issues simultaneously.

**Comment by Jocs** [comment]
>I think we should prefix the entries with the category like file, editor etc.

Now I divide the Mark Text Preference into four categories, universal, editor, markdown, theme, and the file you said should be markdown?

**Comment by fxha** [comment]
@Jocs Please convert the list above in a task list to track missing features.

**Comment by renehummen** [comment]
@Jocs I would like to configure Mark Text such that the _Sidebar_ and _Tabbar_ always show up when opening a new window, i.e. as default behavior. Can this be added in the general section of the preferences as toggleable items?

**Comment by Jocs** [comment]
@renehummen In the future, a new feature should be supported. Mark Text will remember the last closed state, so if the sideBar was displayed last time, then the sideBar is displayed again when newly open Mark Text.
